# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client\Orgs\ActionFileAttachDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActionFileAttachDialog(object):
    def setupUi(self, ActionFileAttachDialog):
        ActionFileAttachDialog.setObjectName(_fromUtf8("ActionFileAttachDialog"))
        ActionFileAttachDialog.resize(1185, 985)
        self.gridLayout_4 = QtGui.QGridLayout(ActionFileAttachDialog)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget = QtGui.QTabWidget(ActionFileAttachDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabAction = QtGui.QWidget()
        self.tabAction.setObjectName(_fromUtf8("tabAction"))
        self.gridLayout = QtGui.QGridLayout(self.tabAction)
        self.gridLayout.setMargin(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tblActionFileAttach = CTableView(self.tabAction)
        self.tblActionFileAttach.setObjectName(_fromUtf8("tblActionFileAttach"))
        self.gridLayout.addWidget(self.tblActionFileAttach, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabAction, _fromUtf8(""))
        self.tabProphylaxisPlanning = QtGui.QWidget()
        self.tabProphylaxisPlanning.setObjectName(_fromUtf8("tabProphylaxisPlanning"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabProphylaxisPlanning)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblProphylaxisPlanningFileAttach = CTableView(self.tabProphylaxisPlanning)
        self.tblProphylaxisPlanningFileAttach.setObjectName(_fromUtf8("tblProphylaxisPlanningFileAttach"))
        self.gridLayout_5.addWidget(self.tblProphylaxisPlanningFileAttach, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabProphylaxisPlanning, _fromUtf8(""))
        self.tabEvent = QtGui.QWidget()
        self.tabEvent.setObjectName(_fromUtf8("tabEvent"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabEvent)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblEventFileAttach = CTableView(self.tabEvent)
        self.tblEventFileAttach.setObjectName(_fromUtf8("tblEventFileAttach"))
        self.gridLayout_3.addWidget(self.tblEventFileAttach, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabEvent, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblCount = QtGui.QLabel(ActionFileAttachDialog)
        self.lblCount.setObjectName(_fromUtf8("lblCount"))
        self.horizontalLayout_4.addWidget(self.lblCount)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnSign = QtGui.QPushButton(ActionFileAttachDialog)
        self.btnSign.setObjectName(_fromUtf8("btnSign"))
        self.horizontalLayout_3.addWidget(self.btnSign)
        self.cmbSign = QtGui.QComboBox(ActionFileAttachDialog)
        self.cmbSign.setObjectName(_fromUtf8("cmbSign"))
        self.cmbSign.addItem(_fromUtf8(""))
        self.cmbSign.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cmbSign)
        self.btnOpenFile = CAttachButton(ActionFileAttachDialog)
        self.btnOpenFile.setObjectName(_fromUtf8("btnOpenFile"))
        self.horizontalLayout_3.addWidget(self.btnOpenFile)
        self.btnPrint = QtGui.QPushButton(ActionFileAttachDialog)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.horizontalLayout_3.addWidget(self.btnPrint)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.groupBoxFilters = QtGui.QGroupBox(ActionFileAttachDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxFilters.sizePolicy().hasHeightForWidth())
        self.groupBoxFilters.setSizePolicy(sizePolicy)
        self.groupBoxFilters.setMaximumSize(QtCore.QSize(278, 16777215))
        self.groupBoxFilters.setObjectName(_fromUtf8("groupBoxFilters"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxFilters)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chkFilterLastName = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkFilterLastName.setObjectName(_fromUtf8("chkFilterLastName"))
        self.verticalLayout.addWidget(self.chkFilterLastName)
        self.edtFilterLastName = QtGui.QLineEdit(self.groupBoxFilters)
        self.edtFilterLastName.setObjectName(_fromUtf8("edtFilterLastName"))
        self.verticalLayout.addWidget(self.edtFilterLastName)
        self.chkFilterFirstName = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkFilterFirstName.setObjectName(_fromUtf8("chkFilterFirstName"))
        self.verticalLayout.addWidget(self.chkFilterFirstName)
        self.edtFilterFirstName = QtGui.QLineEdit(self.groupBoxFilters)
        self.edtFilterFirstName.setObjectName(_fromUtf8("edtFilterFirstName"))
        self.verticalLayout.addWidget(self.edtFilterFirstName)
        self.chkFilterPatrName = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkFilterPatrName.setObjectName(_fromUtf8("chkFilterPatrName"))
        self.verticalLayout.addWidget(self.chkFilterPatrName)
        self.edtFilterPatrName = QtGui.QLineEdit(self.groupBoxFilters)
        self.edtFilterPatrName.setObjectName(_fromUtf8("edtFilterPatrName"))
        self.verticalLayout.addWidget(self.edtFilterPatrName)
        self.chkFilterEventId = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkFilterEventId.setObjectName(_fromUtf8("chkFilterEventId"))
        self.verticalLayout.addWidget(self.chkFilterEventId)
        self.edtFilterEventId = QtGui.QLineEdit(self.groupBoxFilters)
        self.edtFilterEventId.setObjectName(_fromUtf8("edtFilterEventId"))
        self.verticalLayout.addWidget(self.edtFilterEventId)
        self.lblFilterSigned = QtGui.QLabel(self.groupBoxFilters)
        self.lblFilterSigned.setObjectName(_fromUtf8("lblFilterSigned"))
        self.verticalLayout.addWidget(self.lblFilterSigned)
        self.cmbFilterSigned = QtGui.QComboBox(self.groupBoxFilters)
        self.cmbFilterSigned.setObjectName(_fromUtf8("cmbFilterSigned"))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.cmbFilterSigned)
        self.chkFilterOrgStructure = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkFilterOrgStructure.setObjectName(_fromUtf8("chkFilterOrgStructure"))
        self.verticalLayout.addWidget(self.chkFilterOrgStructure)
        self.cmbFilterOrgStructure = COrgStructureComboBox(self.groupBoxFilters)
        self.cmbFilterOrgStructure.setObjectName(_fromUtf8("cmbFilterOrgStructure"))
        self.verticalLayout.addWidget(self.cmbFilterOrgStructure)
        self.lblFilterPerson = QtGui.QLabel(self.groupBoxFilters)
        self.lblFilterPerson.setObjectName(_fromUtf8("lblFilterPerson"))
        self.verticalLayout.addWidget(self.lblFilterPerson)
        self.cmbFilterPerson = CPersonComboBoxEx(self.groupBoxFilters)
        self.cmbFilterPerson.setEnabled(True)
        self.cmbFilterPerson.setObjectName(_fromUtf8("cmbFilterPerson"))
        self.verticalLayout.addWidget(self.cmbFilterPerson)
        self.chkFilterSNILS = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkFilterSNILS.setEnabled(False)
        self.chkFilterSNILS.setObjectName(_fromUtf8("chkFilterSNILS"))
        self.verticalLayout.addWidget(self.chkFilterSNILS)
        self.chkFilterActionType = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkFilterActionType.setObjectName(_fromUtf8("chkFilterActionType"))
        self.verticalLayout.addWidget(self.chkFilterActionType)
        self.cmbActionType = CActionTypeComboBoxEx(self.groupBoxFilters)
        self.cmbActionType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbActionType.sizePolicy().hasHeightForWidth())
        self.cmbActionType.setSizePolicy(sizePolicy)
        self.cmbActionType.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbActionType.setObjectName(_fromUtf8("cmbActionType"))
        self.verticalLayout.addWidget(self.cmbActionType)
        self.lblFilterDate = QtGui.QLabel(self.groupBoxFilters)
        self.lblFilterDate.setObjectName(_fromUtf8("lblFilterDate"))
        self.verticalLayout.addWidget(self.lblFilterDate)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkFilterBegDate = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkFilterBegDate.setObjectName(_fromUtf8("chkFilterBegDate"))
        self.horizontalLayout.addWidget(self.chkFilterBegDate)
        self.edtFilterBegDate = QtGui.QDateEdit(self.groupBoxFilters)
        self.edtFilterBegDate.setCalendarPopup(True)
        self.edtFilterBegDate.setObjectName(_fromUtf8("edtFilterBegDate"))
        self.horizontalLayout.addWidget(self.edtFilterBegDate)
        self.chkFilterEndDate = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkFilterEndDate.setObjectName(_fromUtf8("chkFilterEndDate"))
        self.horizontalLayout.addWidget(self.chkFilterEndDate)
        self.edtFilterEndDate = QtGui.QDateEdit(self.groupBoxFilters)
        self.edtFilterEndDate.setCalendarPopup(True)
        self.edtFilterEndDate.setObjectName(_fromUtf8("edtFilterEndDate"))
        self.horizontalLayout.addWidget(self.edtFilterEndDate)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lblFilterDocumentDate = QtGui.QLabel(self.groupBoxFilters)
        self.lblFilterDocumentDate.setObjectName(_fromUtf8("lblFilterDocumentDate"))
        self.verticalLayout.addWidget(self.lblFilterDocumentDate)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.chkFilterDocumentBegDate = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkFilterDocumentBegDate.setObjectName(_fromUtf8("chkFilterDocumentBegDate"))
        self.horizontalLayout_5.addWidget(self.chkFilterDocumentBegDate)
        self.edtFilterDocumentBegDate = QtGui.QDateEdit(self.groupBoxFilters)
        self.edtFilterDocumentBegDate.setCalendarPopup(True)
        self.edtFilterDocumentBegDate.setObjectName(_fromUtf8("edtFilterDocumentBegDate"))
        self.horizontalLayout_5.addWidget(self.edtFilterDocumentBegDate)
        self.chkFilterDocumentEndDate = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkFilterDocumentEndDate.setObjectName(_fromUtf8("chkFilterDocumentEndDate"))
        self.horizontalLayout_5.addWidget(self.chkFilterDocumentEndDate)
        self.edtFilterDocumentEndDate = QtGui.QDateEdit(self.groupBoxFilters)
        self.edtFilterDocumentEndDate.setCalendarPopup(True)
        self.edtFilterDocumentEndDate.setObjectName(_fromUtf8("edtFilterDocumentEndDate"))
        self.horizontalLayout_5.addWidget(self.edtFilterDocumentEndDate)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.chkFilterTypeDoc = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkFilterTypeDoc.setObjectName(_fromUtf8("chkFilterTypeDoc"))
        self.verticalLayout.addWidget(self.chkFilterTypeDoc)
        self.cmbTypeDoc = QtGui.QComboBox(self.groupBoxFilters)
        self.cmbTypeDoc.setEnabled(False)
        self.cmbTypeDoc.setObjectName(_fromUtf8("cmbTypeDoc"))
        self.cmbTypeDoc.addItem(_fromUtf8(""))
        self.cmbTypeDoc.addItem(_fromUtf8(""))
        self.cmbTypeDoc.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.cmbTypeDoc)
        self.chkFilterIdentify = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkFilterIdentify.setObjectName(_fromUtf8("chkFilterIdentify"))
        self.verticalLayout.addWidget(self.chkFilterIdentify)
        self.cmbFilterIdentify = CMultivalueComboBox(self.groupBoxFilters)
        self.cmbFilterIdentify.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterIdentify.sizePolicy().hasHeightForWidth())
        self.cmbFilterIdentify.setSizePolicy(sizePolicy)
        self.cmbFilterIdentify.setObjectName(_fromUtf8("cmbFilterIdentify"))
        self.verticalLayout.addWidget(self.cmbFilterIdentify)
        self.chkUserCert = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkUserCert.setObjectName(_fromUtf8("chkUserCert"))
        self.verticalLayout.addWidget(self.chkUserCert)
        self.cmbUserCert = CCertComboBox(self.groupBoxFilters)
        self.cmbUserCert.setMaximumSize(QtCore.QSize(251, 16777215))
        self.cmbUserCert.setObjectName(_fromUtf8("cmbUserCert"))
        self.verticalLayout.addWidget(self.cmbUserCert)
        self.cmbPersonCert = CPersonComboBoxEx(self.groupBoxFilters)
        self.cmbPersonCert.setMaximumSize(QtCore.QSize(251, 16777215))
        self.cmbPersonCert.setObjectName(_fromUtf8("cmbPersonCert"))
        self.verticalLayout.addWidget(self.cmbPersonCert)
        self.signs = QtGui.QTextBrowser(self.groupBoxFilters)
        self.signs.setMaximumSize(QtCore.QSize(16777215, 150))
        self.signs.setObjectName(_fromUtf8("signs"))
        self.verticalLayout.addWidget(self.signs)
        self.gbValidationResult = QtGui.QGroupBox(self.groupBoxFilters)
        self.gbValidationResult.setObjectName(_fromUtf8("gbValidationResult"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbValidationResult)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.chkValidationSuccess = QtGui.QCheckBox(self.gbValidationResult)
        self.chkValidationSuccess.setChecked(True)
        self.chkValidationSuccess.setObjectName(_fromUtf8("chkValidationSuccess"))
        self.verticalLayout_2.addWidget(self.chkValidationSuccess)
        self.chkValidationUnavailable = QtGui.QCheckBox(self.gbValidationResult)
        self.chkValidationUnavailable.setChecked(True)
        self.chkValidationUnavailable.setObjectName(_fromUtf8("chkValidationUnavailable"))
        self.verticalLayout_2.addWidget(self.chkValidationUnavailable)
        self.chkValidationError = QtGui.QCheckBox(self.gbValidationResult)
        self.chkValidationError.setChecked(True)
        self.chkValidationError.setObjectName(_fromUtf8("chkValidationError"))
        self.verticalLayout_2.addWidget(self.chkValidationError)
        self.chkValidationNoResult = QtGui.QCheckBox(self.gbValidationResult)
        self.chkValidationNoResult.setChecked(True)
        self.chkValidationNoResult.setObjectName(_fromUtf8("chkValidationNoResult"))
        self.verticalLayout_2.addWidget(self.chkValidationNoResult)
        self.verticalLayout.addWidget(self.gbValidationResult)
        self.chkNotSignaturePerson = QtGui.QCheckBox(self.groupBoxFilters)
        self.chkNotSignaturePerson.setObjectName(_fromUtf8("chkNotSignaturePerson"))
        self.verticalLayout.addWidget(self.chkNotSignaturePerson)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnFilterApply = QtGui.QPushButton(self.groupBoxFilters)
        self.btnFilterApply.setObjectName(_fromUtf8("btnFilterApply"))
        self.horizontalLayout_2.addWidget(self.btnFilterApply)
        self.btnFilterReset = QtGui.QPushButton(self.groupBoxFilters)
        self.btnFilterReset.setObjectName(_fromUtf8("btnFilterReset"))
        self.horizontalLayout_2.addWidget(self.btnFilterReset)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxFilters, 0, 1, 1, 1)

        self.retranslateUi(ActionFileAttachDialog)
        self.tabWidget.setCurrentIndex(0)
        self.cmbFilterSigned.setCurrentIndex(0)
        self.cmbTypeDoc.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ActionFileAttachDialog)

    def retranslateUi(self, ActionFileAttachDialog):
        ActionFileAttachDialog.setWindowTitle(_translate("ActionFileAttachDialog", "Подписание документов", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAction), _translate("ActionFileAttachDialog", "Действие", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProphylaxisPlanning), _translate("ActionFileAttachDialog", "ККДН", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEvent), _translate("ActionFileAttachDialog", "События", None))
        self.lblCount.setText(_translate("ActionFileAttachDialog", "Записей в списке: 0", None))
        self.btnSign.setText(_translate("ActionFileAttachDialog", "Подписать", None))
        self.cmbSign.setItemText(0, _translate("ActionFileAttachDialog", "Выбранный документ", None))
        self.cmbSign.setItemText(1, _translate("ActionFileAttachDialog", "Все неподписанные", None))
        self.btnOpenFile.setText(_translate("ActionFileAttachDialog", "Просмотр", None))
        self.btnPrint.setText(_translate("ActionFileAttachDialog", "Печать", None))
        self.groupBoxFilters.setTitle(_translate("ActionFileAttachDialog", "Фильтры", None))
        self.chkFilterLastName.setText(_translate("ActionFileAttachDialog", "Фамилия", None))
        self.chkFilterFirstName.setText(_translate("ActionFileAttachDialog", "Имя", None))
        self.chkFilterPatrName.setText(_translate("ActionFileAttachDialog", "Отчество", None))
        self.chkFilterEventId.setText(_translate("ActionFileAttachDialog", "Код карточки", None))
        self.lblFilterSigned.setText(_translate("ActionFileAttachDialog", "Показать", None))
        self.cmbFilterSigned.setItemText(0, _translate("ActionFileAttachDialog", "все", None))
        self.cmbFilterSigned.setItemText(1, _translate("ActionFileAttachDialog", "не подписанные врачом", None))
        self.cmbFilterSigned.setItemText(2, _translate("ActionFileAttachDialog", "не подписанные МО", None))
        self.cmbFilterSigned.setItemText(3, _translate("ActionFileAttachDialog", "подписанные МО", None))
        self.cmbFilterSigned.setItemText(4, _translate("ActionFileAttachDialog", "подписанные врачом без подписи МО", None))
        self.cmbFilterSigned.setItemText(5, _translate("ActionFileAttachDialog", "все не подписанные", None))
        self.cmbFilterSigned.setItemText(6, _translate("ActionFileAttachDialog", "все подписанные врачом", None))
        self.chkFilterOrgStructure.setText(_translate("ActionFileAttachDialog", "Отделение", None))
        self.lblFilterPerson.setText(_translate("ActionFileAttachDialog", "Врач", None))
        self.chkFilterSNILS.setText(_translate("ActionFileAttachDialog", "Искать по СНИЛС", None))
        self.chkFilterActionType.setText(_translate("ActionFileAttachDialog", "Тип действия", None))
        self.lblFilterDate.setText(_translate("ActionFileAttachDialog", "Дата изменения", None))
        self.chkFilterBegDate.setText(_translate("ActionFileAttachDialog", "С", None))
        self.chkFilterEndDate.setText(_translate("ActionFileAttachDialog", "по", None))
        self.lblFilterDocumentDate.setText(_translate("ActionFileAttachDialog", "Дата документа", None))
        self.chkFilterDocumentBegDate.setText(_translate("ActionFileAttachDialog", "С", None))
        self.chkFilterDocumentEndDate.setText(_translate("ActionFileAttachDialog", "по", None))
        self.chkFilterTypeDoc.setText(_translate("ActionFileAttachDialog", "Вид документа", None))
        self.cmbTypeDoc.setItemText(0, _translate("ActionFileAttachDialog", "pdf", None))
        self.cmbTypeDoc.setItemText(1, _translate("ActionFileAttachDialog", "xml", None))
        self.cmbTypeDoc.setItemText(2, _translate("ActionFileAttachDialog", "sms", None))
        self.chkFilterIdentify.setText(_translate("ActionFileAttachDialog", "Идентификаторы", None))
        self.chkUserCert.setText(_translate("ActionFileAttachDialog", "Поиск документов", None))
        self.gbValidationResult.setTitle(_translate("ActionFileAttachDialog", "Результат валидации", None))
        self.chkValidationSuccess.setText(_translate("ActionFileAttachDialog", "Пройдена успешно", None))
        self.chkValidationUnavailable.setText(_translate("ActionFileAttachDialog", "Не подлежит валидации", None))
        self.chkValidationError.setText(_translate("ActionFileAttachDialog", "Ошибки", None))
        self.chkValidationNoResult.setText(_translate("ActionFileAttachDialog", "Не проверены", None))
        self.chkNotSignaturePerson.setText(_translate("ActionFileAttachDialog", "Исключить документы без подписей участников", None))
        self.btnFilterApply.setText(_translate("ActionFileAttachDialog", "Применить", None))
        self.btnFilterReset.setText(_translate("ActionFileAttachDialog", "Сбросить", None))

from Events.ActionTypeComboBoxEx import CActionTypeComboBoxEx
from OrgStructComboBoxes import COrgStructureComboBox
from PersonComboBoxEx import CPersonComboBoxEx
from library.Attach.AttachButton import CAttachButton
from library.CertComboBox import CCertComboBox
from library.MultivalueComboBox import CMultivalueComboBox
from library.TableView import CTableView
