# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client_test\Orgs\ContractEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ContractEditorDialog(object):
    def setupUi(self, ContractEditorDialog):
        ContractEditorDialog.setObjectName(_fromUtf8("ContractEditorDialog"))
        ContractEditorDialog.resize(1086, 821)
        self.gridLayout_8 = QtGui.QGridLayout(ContractEditorDialog)
        self.gridLayout_8.setMargin(2)
        self.gridLayout_8.setSpacing(2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.splitter_3 = QtGui.QSplitter(ContractEditorDialog)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.widget = QtGui.QWidget(self.splitter_3)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.widget)
        self.gridLayout_6.setMargin(2)
        self.gridLayout_6.setSpacing(2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblFinance = QtGui.QLabel(self.widget)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout_6.addWidget(self.lblFinance, 1, 0, 1, 1)
        self.cmbFinance = CRBComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFinance.sizePolicy().hasHeightForWidth())
        self.cmbFinance.setSizePolicy(sizePolicy)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout_6.addWidget(self.cmbFinance, 1, 1, 1, 1)
        self.lblBegDate = QtGui.QLabel(self.widget)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout_6.addWidget(self.lblBegDate, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(356, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 4, 7, 1, 2)
        self.lblGrouping = QtGui.QLabel(self.widget)
        self.lblGrouping.setObjectName(_fromUtf8("lblGrouping"))
        self.gridLayout_6.addWidget(self.lblGrouping, 2, 0, 1, 1)
        self.lblEndDate = QtGui.QLabel(self.widget)
        self.lblEndDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout_6.addWidget(self.lblEndDate, 4, 2, 1, 1)
        self.edtGrouping = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtGrouping.sizePolicy().hasHeightForWidth())
        self.edtGrouping.setSizePolicy(sizePolicy)
        self.edtGrouping.setMaxLength(64)
        self.edtGrouping.setObjectName(_fromUtf8("edtGrouping"))
        self.gridLayout_6.addWidget(self.edtGrouping, 2, 1, 1, 1)
        self.edtNumber = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtNumber.sizePolicy().hasHeightForWidth())
        self.edtNumber.setSizePolicy(sizePolicy)
        self.edtNumber.setMaxLength(64)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout_6.addWidget(self.edtNumber, 1, 5, 1, 1)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_6.addWidget(self.line, 5, 0, 1, 9)
        self.edtFinanceSubtypeCode = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFinanceSubtypeCode.sizePolicy().hasHeightForWidth())
        self.edtFinanceSubtypeCode.setSizePolicy(sizePolicy)
        self.edtFinanceSubtypeCode.setMaxLength(16)
        self.edtFinanceSubtypeCode.setObjectName(_fromUtf8("edtFinanceSubtypeCode"))
        self.gridLayout_6.addWidget(self.edtFinanceSubtypeCode, 1, 3, 1, 1)
        self.edtEndDate = CDateEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout_6.addWidget(self.edtEndDate, 4, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(356, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 1, 7, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(356, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 3, 7, 1, 2)
        self.lblRecipient = QtGui.QLabel(self.widget)
        self.lblRecipient.setObjectName(_fromUtf8("lblRecipient"))
        self.gridLayout_6.addWidget(self.lblRecipient, 6, 0, 1, 1)
        self.edtDate = CDateEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout_6.addWidget(self.edtDate, 2, 3, 1, 1)
        self.cmbRecipient = COrgComboBox(self.widget)
        self.cmbRecipient.setObjectName(_fromUtf8("cmbRecipient"))
        self.gridLayout_6.addWidget(self.cmbRecipient, 6, 1, 1, 6)
        self.lblFinanceSubtypeCode = QtGui.QLabel(self.widget)
        self.lblFinanceSubtypeCode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFinanceSubtypeCode.setObjectName(_fromUtf8("lblFinanceSubtypeCode"))
        self.gridLayout_6.addWidget(self.lblFinanceSubtypeCode, 1, 2, 1, 1)
        self.edtBegDate = CDateEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout_6.addWidget(self.edtBegDate, 4, 1, 1, 1)
        self.lblNumber = QtGui.QLabel(self.widget)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.gridLayout_6.addWidget(self.lblNumber, 1, 4, 1, 1)
        self.btnSelectRecipient = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectRecipient.sizePolicy().hasHeightForWidth())
        self.btnSelectRecipient.setSizePolicy(sizePolicy)
        self.btnSelectRecipient.setObjectName(_fromUtf8("btnSelectRecipient"))
        self.gridLayout_6.addWidget(self.btnSelectRecipient, 6, 7, 1, 1)
        self.lblResolution = QtGui.QLabel(self.widget)
        self.lblResolution.setObjectName(_fromUtf8("lblResolution"))
        self.gridLayout_6.addWidget(self.lblResolution, 3, 0, 1, 1)
        self.lblDate = QtGui.QLabel(self.widget)
        self.lblDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout_6.addWidget(self.lblDate, 2, 2, 1, 1)
        self.lblRecipientOGRN = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRecipientOGRN.sizePolicy().hasHeightForWidth())
        self.lblRecipientOGRN.setSizePolicy(sizePolicy)
        self.lblRecipientOGRN.setScaledContents(False)
        self.lblRecipientOGRN.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRecipientOGRN.setObjectName(_fromUtf8("lblRecipientOGRN"))
        self.gridLayout_6.addWidget(self.lblRecipientOGRN, 7, 2, 1, 1)
        self.lblRecipientINN = QtGui.QLabel(self.widget)
        self.lblRecipientINN.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRecipientINN.setObjectName(_fromUtf8("lblRecipientINN"))
        self.gridLayout_6.addWidget(self.lblRecipientINN, 7, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(352, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 7, 8, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(352, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 9, 8, 1, 1)
        self.edtRecipientINN = QtGui.QLineEdit(self.widget)
        self.edtRecipientINN.setMaxLength(10)
        self.edtRecipientINN.setReadOnly(True)
        self.edtRecipientINN.setObjectName(_fromUtf8("edtRecipientINN"))
        self.gridLayout_6.addWidget(self.edtRecipientINN, 7, 1, 1, 1)
        self.edtResolution = QtGui.QLineEdit(self.widget)
        self.edtResolution.setMaxLength(64)
        self.edtResolution.setObjectName(_fromUtf8("edtResolution"))
        self.gridLayout_6.addWidget(self.edtResolution, 3, 1, 1, 6)
        spacerItem5 = QtGui.QSpacerItem(356, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 2, 7, 1, 2)
        self.cmbPayer = COrgComboBox(self.widget)
        self.cmbPayer.setObjectName(_fromUtf8("cmbPayer"))
        self.gridLayout_6.addWidget(self.cmbPayer, 11, 1, 1, 6)
        self.edtPayerINN = QtGui.QLineEdit(self.widget)
        self.edtPayerINN.setMaxLength(10)
        self.edtPayerINN.setReadOnly(True)
        self.edtPayerINN.setObjectName(_fromUtf8("edtPayerINN"))
        self.gridLayout_6.addWidget(self.edtPayerINN, 12, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(352, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 13, 8, 1, 1)
        self.lblRecipientAccount = QtGui.QLabel(self.widget)
        self.lblRecipientAccount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRecipientAccount.setObjectName(_fromUtf8("lblRecipientAccount"))
        self.gridLayout_6.addWidget(self.lblRecipientAccount, 8, 0, 1, 1)
        self.cmbPayerAccount = COrgAccComboBox(self.widget)
        self.cmbPayerAccount.setObjectName(_fromUtf8("cmbPayerAccount"))
        self.gridLayout_6.addWidget(self.cmbPayerAccount, 13, 1, 1, 1)
        self.lblPayer = QtGui.QLabel(self.widget)
        self.lblPayer.setObjectName(_fromUtf8("lblPayer"))
        self.gridLayout_6.addWidget(self.lblPayer, 11, 0, 1, 1)
        self.edtRecipientBank = QtGui.QLineEdit(self.widget)
        self.edtRecipientBank.setReadOnly(True)
        self.edtRecipientBank.setObjectName(_fromUtf8("edtRecipientBank"))
        self.gridLayout_6.addWidget(self.edtRecipientBank, 9, 1, 1, 6)
        spacerItem7 = QtGui.QSpacerItem(352, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 14, 8, 1, 1)
        self.cmbRecipientAccount = COrgAccComboBox(self.widget)
        self.cmbRecipientAccount.setObjectName(_fromUtf8("cmbRecipientAccount"))
        self.gridLayout_6.addWidget(self.cmbRecipientAccount, 8, 1, 1, 1)
        self.lblRecipientKBK = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRecipientKBK.sizePolicy().hasHeightForWidth())
        self.lblRecipientKBK.setSizePolicy(sizePolicy)
        self.lblRecipientKBK.setScaledContents(False)
        self.lblRecipientKBK.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRecipientKBK.setObjectName(_fromUtf8("lblRecipientKBK"))
        self.gridLayout_6.addWidget(self.lblRecipientKBK, 8, 2, 1, 1)
        self.edtPayerBank = QtGui.QLineEdit(self.widget)
        self.edtPayerBank.setReadOnly(True)
        self.edtPayerBank.setObjectName(_fromUtf8("edtPayerBank"))
        self.gridLayout_6.addWidget(self.edtPayerBank, 14, 1, 1, 6)
        self.btnSelectPayer = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectPayer.sizePolicy().hasHeightForWidth())
        self.btnSelectPayer.setSizePolicy(sizePolicy)
        self.btnSelectPayer.setObjectName(_fromUtf8("btnSelectPayer"))
        self.gridLayout_6.addWidget(self.btnSelectPayer, 11, 7, 1, 1)
        self.lblPayerBank = QtGui.QLabel(self.widget)
        self.lblPayerBank.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPayerBank.setObjectName(_fromUtf8("lblPayerBank"))
        self.gridLayout_6.addWidget(self.lblPayerBank, 14, 0, 1, 1)
        self.lblPayerKBK = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPayerKBK.sizePolicy().hasHeightForWidth())
        self.lblPayerKBK.setSizePolicy(sizePolicy)
        self.lblPayerKBK.setScaledContents(False)
        self.lblPayerKBK.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPayerKBK.setObjectName(_fromUtf8("lblPayerKBK"))
        self.gridLayout_6.addWidget(self.lblPayerKBK, 13, 2, 1, 1)
        self.lblPayerINN = QtGui.QLabel(self.widget)
        self.lblPayerINN.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPayerINN.setObjectName(_fromUtf8("lblPayerINN"))
        self.gridLayout_6.addWidget(self.lblPayerINN, 12, 0, 1, 1)
        self.edtPayerOGRN = QtGui.QLineEdit(self.widget)
        self.edtPayerOGRN.setMaxLength(64)
        self.edtPayerOGRN.setReadOnly(True)
        self.edtPayerOGRN.setObjectName(_fromUtf8("edtPayerOGRN"))
        self.gridLayout_6.addWidget(self.edtPayerOGRN, 12, 3, 1, 4)
        self.edtRecipientOGRN = QtGui.QLineEdit(self.widget)
        self.edtRecipientOGRN.setMaxLength(64)
        self.edtRecipientOGRN.setReadOnly(True)
        self.edtRecipientOGRN.setObjectName(_fromUtf8("edtRecipientOGRN"))
        self.gridLayout_6.addWidget(self.edtRecipientOGRN, 7, 3, 1, 4)
        self.lblPayerOGRN = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPayerOGRN.sizePolicy().hasHeightForWidth())
        self.lblPayerOGRN.setSizePolicy(sizePolicy)
        self.lblPayerOGRN.setScaledContents(False)
        self.lblPayerOGRN.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPayerOGRN.setObjectName(_fromUtf8("lblPayerOGRN"))
        self.gridLayout_6.addWidget(self.lblPayerOGRN, 12, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(352, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 8, 8, 1, 1)
        self.lblRecipientBank = QtGui.QLabel(self.widget)
        self.lblRecipientBank.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRecipientBank.setObjectName(_fromUtf8("lblRecipientBank"))
        self.gridLayout_6.addWidget(self.lblRecipientBank, 9, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(352, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 12, 8, 1, 1)
        self.edtRecipientKBK = QtGui.QLineEdit(self.widget)
        self.edtRecipientKBK.setMaxLength(30)
        self.edtRecipientKBK.setObjectName(_fromUtf8("edtRecipientKBK"))
        self.gridLayout_6.addWidget(self.edtRecipientKBK, 8, 3, 1, 4)
        self.lblPayerAccount = QtGui.QLabel(self.widget)
        self.lblPayerAccount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPayerAccount.setObjectName(_fromUtf8("lblPayerAccount"))
        self.gridLayout_6.addWidget(self.lblPayerAccount, 13, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.widget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_6.addWidget(self.line_2, 10, 0, 1, 9)
        self.edtPayerKBK = QtGui.QLineEdit(self.widget)
        self.edtPayerKBK.setMaxLength(30)
        self.edtPayerKBK.setObjectName(_fromUtf8("edtPayerKBK"))
        self.gridLayout_6.addWidget(self.edtPayerKBK, 13, 3, 1, 4)
        self.scrollArea = QtGui.QScrollArea(self.splitter_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1252, 852))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSpecification = QtGui.QWidget()
        self.tabSpecification.setObjectName(_fromUtf8("tabSpecification"))
        self._2 = QtGui.QGridLayout(self.tabSpecification)
        self._2.setMargin(4)
        self._2.setSpacing(4)
        self._2.setObjectName(_fromUtf8("_2"))
        self.tblSpecification = CInDocTableView(self.tabSpecification)
        self.tblSpecification.setObjectName(_fromUtf8("tblSpecification"))
        self._2.addWidget(self.tblSpecification, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabSpecification, _fromUtf8(""))
        self.tabTariff = QtGui.QWidget()
        self.tabTariff.setObjectName(_fromUtf8("tabTariff"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabTariff)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter_2 = QtGui.QSplitter(self.tabTariff)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(3)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.pnlTariffFilter = QtGui.QWidget(self.splitter_2)
        self.pnlTariffFilter.setMinimumSize(QtCore.QSize(0, 50))
        self.pnlTariffFilter.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pnlTariffFilter.setObjectName(_fromUtf8("pnlTariffFilter"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pnlTariffFilter)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblCode = QtGui.QLabel(self.pnlTariffFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setSizeIncrement(QtCore.QSize(0, 0))
        self.lblCode.setBaseSize(QtCore.QSize(0, 0))
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.horizontalLayout.addWidget(self.lblCode)
        self.edtCode = QtGui.QLineEdit(self.pnlTariffFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCode.sizePolicy().hasHeightForWidth())
        self.edtCode.setSizePolicy(sizePolicy)
        self.edtCode.setSizeIncrement(QtCore.QSize(0, 0))
        self.edtCode.setBaseSize(QtCore.QSize(0, 0))
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.horizontalLayout.addWidget(self.edtCode)
        self.chkFilterDate = QtGui.QCheckBox(self.pnlTariffFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterDate.sizePolicy().hasHeightForWidth())
        self.chkFilterDate.setSizePolicy(sizePolicy)
        self.chkFilterDate.setSizeIncrement(QtCore.QSize(1, 0))
        self.chkFilterDate.setBaseSize(QtCore.QSize(1, 0))
        self.chkFilterDate.setObjectName(_fromUtf8("chkFilterDate"))
        self.horizontalLayout.addWidget(self.chkFilterDate)
        self.edtFilterDate = CDateEdit(self.pnlTariffFilter)
        self.edtFilterDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterDate.sizePolicy().hasHeightForWidth())
        self.edtFilterDate.setSizePolicy(sizePolicy)
        self.edtFilterDate.setMinimumSize(QtCore.QSize(120, 0))
        self.edtFilterDate.setSizeIncrement(QtCore.QSize(0, 0))
        self.edtFilterDate.setBaseSize(QtCore.QSize(0, 0))
        self.edtFilterDate.setObjectName(_fromUtf8("edtFilterDate"))
        self.horizontalLayout.addWidget(self.edtFilterDate)
        self.btnApplyFilter = QtGui.QPushButton(self.pnlTariffFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnApplyFilter.sizePolicy().hasHeightForWidth())
        self.btnApplyFilter.setSizePolicy(sizePolicy)
        self.btnApplyFilter.setSizeIncrement(QtCore.QSize(1, 0))
        self.btnApplyFilter.setBaseSize(QtCore.QSize(1, 0))
        self.btnApplyFilter.setObjectName(_fromUtf8("btnApplyFilter"))
        self.horizontalLayout.addWidget(self.btnApplyFilter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblEventType = QtGui.QLabel(self.pnlTariffFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventType.sizePolicy().hasHeightForWidth())
        self.lblEventType.setSizePolicy(sizePolicy)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.horizontalLayout_2.addWidget(self.lblEventType)
        self.cmbEventType = CRBComboBox(self.pnlTariffFilter)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.horizontalLayout_2.addWidget(self.cmbEventType)
        self.lblTariffType = QtGui.QLabel(self.pnlTariffFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTariffType.sizePolicy().hasHeightForWidth())
        self.lblTariffType.setSizePolicy(sizePolicy)
        self.lblTariffType.setObjectName(_fromUtf8("lblTariffType"))
        self.horizontalLayout_2.addWidget(self.lblTariffType)
        self.cmbTariffType = QtGui.QComboBox(self.pnlTariffFilter)
        self.cmbTariffType.setObjectName(_fromUtf8("cmbTariffType"))
        self.horizontalLayout_2.addWidget(self.cmbTariffType)
        self.lblTariffBatch = QtGui.QLabel(self.pnlTariffFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTariffBatch.sizePolicy().hasHeightForWidth())
        self.lblTariffBatch.setSizePolicy(sizePolicy)
        self.lblTariffBatch.setObjectName(_fromUtf8("lblTariffBatch"))
        self.horizontalLayout_2.addWidget(self.lblTariffBatch)
        self.edtTariffBatch = QtGui.QLineEdit(self.pnlTariffFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTariffBatch.sizePolicy().hasHeightForWidth())
        self.edtTariffBatch.setSizePolicy(sizePolicy)
        self.edtTariffBatch.setMaxLength(100)
        self.edtTariffBatch.setObjectName(_fromUtf8("edtTariffBatch"))
        self.horizontalLayout_2.addWidget(self.edtTariffBatch)
        self.lblService = QtGui.QLabel(self.pnlTariffFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblService.sizePolicy().hasHeightForWidth())
        self.lblService.setSizePolicy(sizePolicy)
        self.lblService.setObjectName(_fromUtf8("lblService"))
        self.horizontalLayout_2.addWidget(self.lblService)
        self.cmbService = CRBServiceComboBox(self.pnlTariffFilter)
        self.cmbService.setObjectName(_fromUtf8("cmbService"))
        self.horizontalLayout_2.addWidget(self.cmbService)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tblTariffs = CInDocTableView(self.splitter_2)
        self.tblTariffs.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblTariffs.setObjectName(_fromUtf8("tblTariffs"))
        self.pnlTariff = QtGui.QWidget(self.splitter_2)
        self.pnlTariff.setObjectName(_fromUtf8("pnlTariff"))
        self.gridLayout = QtGui.QGridLayout(self.pnlTariff)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.pnlTariff)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(3)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tblTariffExpense = CInDocTableView(self.splitter)
        self.tblTariffExpense.setObjectName(_fromUtf8("tblTariffExpense"))
        self.tblTariffAttach = CInDocTableView(self.splitter)
        self.tblTariffAttach.setObjectName(_fromUtf8("tblTariffAttach"))
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabTariff, _fromUtf8(""))
        self.tabContingent = QtGui.QWidget()
        self.tabContingent.setObjectName(_fromUtf8("tabContingent"))
        self._3 = QtGui.QGridLayout(self.tabContingent)
        self._3.setMargin(4)
        self._3.setSpacing(4)
        self._3.setObjectName(_fromUtf8("_3"))
        self.tblContingent = CInDocTableView(self.tabContingent)
        self.tblContingent.setObjectName(_fromUtf8("tblContingent"))
        self._3.addWidget(self.tblContingent, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabContingent, _fromUtf8(""))
        self.tabContragent  = QtGui.QWidget()
        self.tabContragent .setObjectName(_fromUtf8("tabContragent "))
        self._4 = QtGui.QGridLayout(self.tabContragent )
        self._4.setMargin(4)
        self._4.setSpacing(4)
        self._4.setObjectName(_fromUtf8("_4"))
        self.tblContragents = CInDocTableView(self.tabContragent )
        self.tblContragents.setObjectName(_fromUtf8("tblContragents"))
        self._4.addWidget(self.tblContragents, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabContragent , _fromUtf8(""))
        self.tabMisc = QtGui.QWidget()
        self.tabMisc.setObjectName(_fromUtf8("tabMisc"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabMisc)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblExpensePrecision = QtGui.QLabel(self.tabMisc)
        self.lblExpensePrecision.setObjectName(_fromUtf8("lblExpensePrecision"))
        self.gridLayout_2.addWidget(self.lblExpensePrecision, 26, 3, 1, 1)
        self.chkExposeDisciplineByMonth = QtGui.QCheckBox(self.tabMisc)
        self.chkExposeDisciplineByMonth.setObjectName(_fromUtf8("chkExposeDisciplineByMonth"))
        self.gridLayout_2.addWidget(self.chkExposeDisciplineByMonth, 10, 2, 1, 9)
        self.chkExposeDisciplineByBatch = QtGui.QCheckBox(self.tabMisc)
        self.chkExposeDisciplineByBatch.setObjectName(_fromUtf8("chkExposeDisciplineByBatch"))
        self.gridLayout_2.addWidget(self.chkExposeDisciplineByBatch, 13, 2, 1, 9)
        self.lblExposeIfContinuedEventFinished = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExposeIfContinuedEventFinished.sizePolicy().hasHeightForWidth())
        self.lblExposeIfContinuedEventFinished.setSizePolicy(sizePolicy)
        self.lblExposeIfContinuedEventFinished.setObjectName(_fromUtf8("lblExposeIfContinuedEventFinished"))
        self.gridLayout_2.addWidget(self.lblExposeIfContinuedEventFinished, 7, 0, 1, 2)
        spacerItem10 = QtGui.QSpacerItem(410, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 25, 3, 1, 8)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 0, 10, 1, 1)
        self.lblDefaultExportFormat = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDefaultExportFormat.sizePolicy().hasHeightForWidth())
        self.lblDefaultExportFormat.setSizePolicy(sizePolicy)
        self.lblDefaultExportFormat.setObjectName(_fromUtf8("lblDefaultExportFormat"))
        self.gridLayout_2.addWidget(self.lblDefaultExportFormat, 0, 0, 1, 2)
        self.btnCalculation = QtGui.QToolButton(self.tabMisc)
        self.btnCalculation.setObjectName(_fromUtf8("btnCalculation"))
        self.gridLayout_2.addWidget(self.btnCalculation, 30, 3, 1, 2)
        spacerItem12 = QtGui.QSpacerItem(278, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 24, 9, 1, 2)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 1, 10, 1, 1)
        self.edtRegionalTariffRegulationFactor = QtGui.QDoubleSpinBox(self.tabMisc)
        self.edtRegionalTariffRegulationFactor.setDecimals(4)
        self.edtRegionalTariffRegulationFactor.setMaximum(9999.9999)
        self.edtRegionalTariffRegulationFactor.setSingleStep(0.01)
        self.edtRegionalTariffRegulationFactor.setObjectName(_fromUtf8("edtRegionalTariffRegulationFactor"))
        self.gridLayout_2.addWidget(self.edtRegionalTariffRegulationFactor, 25, 2, 1, 1)
        self.edtCoefficient = QtGui.QDoubleSpinBox(self.tabMisc)
        self.edtCoefficient.setDecimals(4)
        self.edtCoefficient.setMaximum(99.9999)
        self.edtCoefficient.setSingleStep(0.01)
        self.edtCoefficient.setObjectName(_fromUtf8("edtCoefficient"))
        self.gridLayout_2.addWidget(self.edtCoefficient, 21, 2, 1, 1)
        self.edtCoefficientEx = QtGui.QDoubleSpinBox(self.tabMisc)
        self.edtCoefficientEx.setDecimals(4)
        self.edtCoefficientEx.setMaximum(99.9999)
        self.edtCoefficientEx.setSingleStep(0.01)
        self.edtCoefficientEx.setObjectName(_fromUtf8("edtCoefficientEx"))
        self.gridLayout_2.addWidget(self.edtCoefficientEx, 22, 2, 1, 1)
        self.lblCoefficientEx = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCoefficientEx.sizePolicy().hasHeightForWidth())
        self.lblCoefficientEx.setSizePolicy(sizePolicy)
        self.lblCoefficientEx.setObjectName(_fromUtf8("lblCoefficientEx"))
        self.gridLayout_2.addWidget(self.lblCoefficientEx, 22, 0, 1, 2)
        self.lblCoefficientEx2 = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCoefficientEx2.sizePolicy().hasHeightForWidth())
        self.lblCoefficientEx2.setSizePolicy(sizePolicy)
        self.lblCoefficientEx2.setObjectName(_fromUtf8("lblCoefficientEx2"))
        self.gridLayout_2.addWidget(self.lblCoefficientEx2, 23, 0, 1, 2)
        self.edtCoefficientEx2 = QtGui.QDoubleSpinBox(self.tabMisc)
        self.edtCoefficientEx2.setDecimals(4)
        self.edtCoefficientEx2.setMaximum(99.9999)
        self.edtCoefficientEx2.setSingleStep(0.01)
        self.edtCoefficientEx2.setObjectName(_fromUtf8("edtCoefficientEx2"))
        self.gridLayout_2.addWidget(self.edtCoefficientEx2, 23, 2, 1, 1)
        self.lblRegionalTariffRegulationFactor = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRegionalTariffRegulationFactor.sizePolicy().hasHeightForWidth())
        self.lblRegionalTariffRegulationFactor.setSizePolicy(sizePolicy)
        self.lblRegionalTariffRegulationFactor.setObjectName(_fromUtf8("lblRegionalTariffRegulationFactor"))
        self.gridLayout_2.addWidget(self.lblRegionalTariffRegulationFactor, 25, 0, 1, 2)
        self.edtLimitExceeding = QtGui.QDoubleSpinBox(self.tabMisc)
        self.edtLimitExceeding.setDecimals(2)
        self.edtLimitExceeding.setMaximum(999999999.99)
        self.edtLimitExceeding.setObjectName(_fromUtf8("edtLimitExceeding"))
        self.gridLayout_2.addWidget(self.edtLimitExceeding, 28, 2, 1, 1)
        self.edtLimitOfFinancing = QtGui.QDoubleSpinBox(self.tabMisc)
        self.edtLimitOfFinancing.setMaximum(999999999.99)
        self.edtLimitOfFinancing.setObjectName(_fromUtf8("edtLimitOfFinancing"))
        self.gridLayout_2.addWidget(self.edtLimitOfFinancing, 29, 2, 1, 1)
        self.chkExposeIfContinuedEventFinished = QtGui.QCheckBox(self.tabMisc)
        self.chkExposeIfContinuedEventFinished.setEnabled(True)
        self.chkExposeIfContinuedEventFinished.setText(_fromUtf8(""))
        self.chkExposeIfContinuedEventFinished.setObjectName(_fromUtf8("chkExposeIfContinuedEventFinished"))
        self.gridLayout_2.addWidget(self.chkExposeIfContinuedEventFinished, 7, 2, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 28, 3, 1, 8)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem15, 29, 3, 1, 8)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 30, 7, 1, 4)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem17, 2, 10, 1, 1)
        self.edtActualAmount = QtGui.QDoubleSpinBox(self.tabMisc)
        self.edtActualAmount.setMaximum(999999999.99)
        self.edtActualAmount.setObjectName(_fromUtf8("edtActualAmount"))
        self.gridLayout_2.addWidget(self.edtActualAmount, 30, 2, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(261, 19, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem18, 19, 9, 1, 2)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem19, 21, 3, 1, 8)
        spacerItem20 = QtGui.QSpacerItem(410, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem20, 22, 3, 1, 8)
        spacerItem21 = QtGui.QSpacerItem(410, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem21, 23, 3, 1, 8)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem22, 26, 7, 1, 4)
        spacerItem23 = QtGui.QSpacerItem(278, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem23, 20, 9, 1, 2)
        self.lblPricePrecision = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPricePrecision.sizePolicy().hasHeightForWidth())
        self.lblPricePrecision.setSizePolicy(sizePolicy)
        self.lblPricePrecision.setObjectName(_fromUtf8("lblPricePrecision"))
        self.gridLayout_2.addWidget(self.lblPricePrecision, 26, 0, 1, 2)
        self.edtPricePrecision = QtGui.QSpinBox(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPricePrecision.sizePolicy().hasHeightForWidth())
        self.edtPricePrecision.setSizePolicy(sizePolicy)
        self.edtPricePrecision.setMaximum(9)
        self.edtPricePrecision.setProperty("value", 2)
        self.edtPricePrecision.setObjectName(_fromUtf8("edtPricePrecision"))
        self.gridLayout_2.addWidget(self.edtPricePrecision, 26, 2, 1, 1)
        self.edtExpensePrecision = QtGui.QSpinBox(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtExpensePrecision.sizePolicy().hasHeightForWidth())
        self.edtExpensePrecision.setSizePolicy(sizePolicy)
        self.edtExpensePrecision.setMaximum(9)
        self.edtExpensePrecision.setProperty("value", 2)
        self.edtExpensePrecision.setObjectName(_fromUtf8("edtExpensePrecision"))
        self.gridLayout_2.addWidget(self.edtExpensePrecision, 26, 4, 1, 1)
        self.lblPriceListExternal = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPriceListExternal.sizePolicy().hasHeightForWidth())
        self.lblPriceListExternal.setSizePolicy(sizePolicy)
        self.lblPriceListExternal.setObjectName(_fromUtf8("lblPriceListExternal"))
        self.gridLayout_2.addWidget(self.lblPriceListExternal, 20, 0, 1, 2)
        self.lblExposeDiscipline = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExposeDiscipline.sizePolicy().hasHeightForWidth())
        self.lblExposeDiscipline.setSizePolicy(sizePolicy)
        self.lblExposeDiscipline.setObjectName(_fromUtf8("lblExposeDiscipline"))
        self.gridLayout_2.addWidget(self.lblExposeDiscipline, 10, 0, 1, 2)
        self.lblPriceList = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPriceList.sizePolicy().hasHeightForWidth())
        self.lblPriceList.setSizePolicy(sizePolicy)
        self.lblPriceList.setObjectName(_fromUtf8("lblPriceList"))
        self.gridLayout_2.addWidget(self.lblPriceList, 19, 0, 1, 2)
        self.lblOrgCategory = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgCategory.sizePolicy().hasHeightForWidth())
        self.lblOrgCategory.setSizePolicy(sizePolicy)
        self.lblOrgCategory.setObjectName(_fromUtf8("lblOrgCategory"))
        self.gridLayout_2.addWidget(self.lblOrgCategory, 24, 0, 1, 2)
        self.lblVisitExposition = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblVisitExposition.sizePolicy().hasHeightForWidth())
        self.lblVisitExposition.setSizePolicy(sizePolicy)
        self.lblVisitExposition.setObjectName(_fromUtf8("lblVisitExposition"))
        self.gridLayout_2.addWidget(self.lblVisitExposition, 1, 0, 1, 2)
        self.lblCoefficient = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCoefficient.sizePolicy().hasHeightForWidth())
        self.lblCoefficient.setSizePolicy(sizePolicy)
        self.lblCoefficient.setObjectName(_fromUtf8("lblCoefficient"))
        self.gridLayout_2.addWidget(self.lblCoefficient, 21, 0, 1, 2)
        self.lblActionExposition = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblActionExposition.sizePolicy().hasHeightForWidth())
        self.lblActionExposition.setSizePolicy(sizePolicy)
        self.lblActionExposition.setObjectName(_fromUtf8("lblActionExposition"))
        self.gridLayout_2.addWidget(self.lblActionExposition, 2, 0, 1, 2)
        self.chkExposeDisciplineByEvent = QtGui.QCheckBox(self.tabMisc)
        self.chkExposeDisciplineByEvent.setObjectName(_fromUtf8("chkExposeDisciplineByEvent"))
        self.gridLayout_2.addWidget(self.chkExposeDisciplineByEvent, 15, 2, 1, 9)
        self.lblLimitOfFinancing = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLimitOfFinancing.sizePolicy().hasHeightForWidth())
        self.lblLimitOfFinancing.setSizePolicy(sizePolicy)
        self.lblLimitOfFinancing.setObjectName(_fromUtf8("lblLimitOfFinancing"))
        self.gridLayout_2.addWidget(self.lblLimitOfFinancing, 29, 0, 1, 2)
        self.chkExposeDisciplineByClient = QtGui.QCheckBox(self.tabMisc)
        self.chkExposeDisciplineByClient.setObjectName(_fromUtf8("chkExposeDisciplineByClient"))
        self.gridLayout_2.addWidget(self.chkExposeDisciplineByClient, 14, 2, 1, 9)
        self.lblLimitExceeding = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLimitExceeding.sizePolicy().hasHeightForWidth())
        self.lblLimitExceeding.setSizePolicy(sizePolicy)
        self.lblLimitExceeding.setObjectName(_fromUtf8("lblLimitExceeding"))
        self.gridLayout_2.addWidget(self.lblLimitExceeding, 28, 0, 1, 2)
        self.lblActualAmount = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblActualAmount.sizePolicy().hasHeightForWidth())
        self.lblActualAmount.setSizePolicy(sizePolicy)
        self.lblActualAmount.setObjectName(_fromUtf8("lblActualAmount"))
        self.gridLayout_2.addWidget(self.lblActualAmount, 30, 0, 1, 2)
        self.lblExposeByLastEventContract = QtGui.QLabel(self.tabMisc)
        self.lblExposeByLastEventContract.setEnabled(False)
        self.lblExposeByLastEventContract.setObjectName(_fromUtf8("lblExposeByLastEventContract"))
        self.gridLayout_2.addWidget(self.lblExposeByLastEventContract, 7, 3, 1, 1)
        self.chkExposeExternalServices = QtGui.QCheckBox(self.tabMisc)
        self.chkExposeExternalServices.setText(_fromUtf8(""))
        self.chkExposeExternalServices.setObjectName(_fromUtf8("chkExposeExternalServices"))
        self.gridLayout_2.addWidget(self.chkExposeExternalServices, 6, 2, 1, 1)
        self.lblExposeExternalServices = QtGui.QLabel(self.tabMisc)
        self.lblExposeExternalServices.setObjectName(_fromUtf8("lblExposeExternalServices"))
        self.gridLayout_2.addWidget(self.lblExposeExternalServices, 6, 0, 1, 2)
        self.lblPayType = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPayType.sizePolicy().hasHeightForWidth())
        self.lblPayType.setSizePolicy(sizePolicy)
        self.lblPayType.setObjectName(_fromUtf8("lblPayType"))
        self.gridLayout_2.addWidget(self.lblPayType, 31, 0, 1, 1)
        self.lblCsgExposition = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCsgExposition.sizePolicy().hasHeightForWidth())
        self.lblCsgExposition.setSizePolicy(sizePolicy)
        self.lblCsgExposition.setObjectName(_fromUtf8("lblCsgExposition"))
        self.gridLayout_2.addWidget(self.lblCsgExposition, 4, 0, 1, 2)
        self.chkDisableInAccounts = QtGui.QCheckBox(self.tabMisc)
        self.chkDisableInAccounts.setObjectName(_fromUtf8("chkDisableInAccounts"))
        self.gridLayout_2.addWidget(self.chkDisableInAccounts, 32, 2, 1, 3)
        self.cmbDateOfCsgExposition = QtGui.QComboBox(self.tabMisc)
        self.cmbDateOfCsgExposition.setObjectName(_fromUtf8("cmbDateOfCsgExposition"))
        self.cmbDateOfCsgExposition.addItem(_fromUtf8(""))
        self.cmbDateOfCsgExposition.addItem(_fromUtf8(""))
        self.cmbDateOfCsgExposition.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbDateOfCsgExposition, 4, 2, 1, 3)
        spacerItem24 = QtGui.QSpacerItem(261, 19, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem24, 31, 9, 1, 2)
        self.chkExposeByLastEventContract = QtGui.QCheckBox(self.tabMisc)
        self.chkExposeByLastEventContract.setEnabled(False)
        self.chkExposeByLastEventContract.setText(_fromUtf8(""))
        self.chkExposeByLastEventContract.setObjectName(_fromUtf8("chkExposeByLastEventContract"))
        self.gridLayout_2.addWidget(self.chkExposeByLastEventContract, 7, 4, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem25, 32, 7, 1, 4)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem26, 27, 8, 1, 3)
        self.chkExposeByAccountType = QtGui.QCheckBox(self.tabMisc)
        self.chkExposeByAccountType.setObjectName(_fromUtf8("chkExposeByAccountType"))
        self.gridLayout_2.addWidget(self.chkExposeByAccountType, 17, 2, 1, 3)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem27, 26, 12, 1, 1)
        self.label = QtGui.QLabel(self.tabMisc)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 26, 5, 1, 1)
        self.cmbDateOfVisitExposition = QtGui.QComboBox(self.tabMisc)
        self.cmbDateOfVisitExposition.setObjectName(_fromUtf8("cmbDateOfVisitExposition"))
        self.cmbDateOfVisitExposition.addItem(_fromUtf8(""))
        self.cmbDateOfVisitExposition.addItem(_fromUtf8(""))
        self.cmbDateOfVisitExposition.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbDateOfVisitExposition, 1, 2, 1, 3)
        self.cmbDefaultExportFormat = CRBComboBox(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDefaultExportFormat.sizePolicy().hasHeightForWidth())
        self.cmbDefaultExportFormat.setSizePolicy(sizePolicy)
        self.cmbDefaultExportFormat.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.cmbDefaultExportFormat.setObjectName(_fromUtf8("cmbDefaultExportFormat"))
        self.gridLayout_2.addWidget(self.cmbDefaultExportFormat, 0, 2, 1, 3)
        self.cmbDateOfActionExposition = QtGui.QComboBox(self.tabMisc)
        self.cmbDateOfActionExposition.setObjectName(_fromUtf8("cmbDateOfActionExposition"))
        self.cmbDateOfActionExposition.addItem(_fromUtf8(""))
        self.cmbDateOfActionExposition.addItem(_fromUtf8(""))
        self.cmbDateOfActionExposition.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbDateOfActionExposition, 2, 2, 1, 3)
        self.edtTariffCoeffValuePrecision = QtGui.QSpinBox(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTariffCoeffValuePrecision.sizePolicy().hasHeightForWidth())
        self.edtTariffCoeffValuePrecision.setSizePolicy(sizePolicy)
        self.edtTariffCoeffValuePrecision.setMaximum(9)
        self.edtTariffCoeffValuePrecision.setProperty("value", 2)
        self.edtTariffCoeffValuePrecision.setObjectName(_fromUtf8("edtTariffCoeffValuePrecision"))
        self.gridLayout_2.addWidget(self.edtTariffCoeffValuePrecision, 26, 6, 1, 1)
        self.cmbExposeDisciplineByInsurer = QtGui.QComboBox(self.tabMisc)
        self.cmbExposeDisciplineByInsurer.setObjectName(_fromUtf8("cmbExposeDisciplineByInsurer"))
        self.cmbExposeDisciplineByInsurer.addItem(_fromUtf8(""))
        self.cmbExposeDisciplineByInsurer.addItem(_fromUtf8(""))
        self.cmbExposeDisciplineByInsurer.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbExposeDisciplineByInsurer, 11, 2, 1, 3)
        self.cmbPriceListExternal = CPriceListComboBox(self.tabMisc)
        self.cmbPriceListExternal.setObjectName(_fromUtf8("cmbPriceListExternal"))
        self.gridLayout_2.addWidget(self.cmbPriceListExternal, 20, 2, 1, 3)
        self.edtOrgCategory = QtGui.QLineEdit(self.tabMisc)
        self.edtOrgCategory.setMaxLength(1)
        self.edtOrgCategory.setObjectName(_fromUtf8("edtOrgCategory"))
        self.gridLayout_2.addWidget(self.edtOrgCategory, 24, 2, 1, 5)
        self.cmbActionExposition = QtGui.QComboBox(self.tabMisc)
        self.cmbActionExposition.setObjectName(_fromUtf8("cmbActionExposition"))
        self.cmbActionExposition.addItem(_fromUtf8(""))
        self.cmbActionExposition.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbActionExposition, 2, 5, 1, 2)
        self.cmbPriceList = CPriceListComboBoxEx(self.tabMisc)
        self.cmbPriceList.setObjectName(_fromUtf8("cmbPriceList"))
        self.gridLayout_2.addWidget(self.cmbPriceList, 19, 2, 1, 3)
        self.chkExposeDisciplineByOncology = QtGui.QCheckBox(self.tabMisc)
        self.chkExposeDisciplineByOncology.setObjectName(_fromUtf8("chkExposeDisciplineByOncology"))
        self.gridLayout_2.addWidget(self.chkExposeDisciplineByOncology, 18, 2, 1, 1)
        self.cmbPayType = QtGui.QComboBox(self.tabMisc)
        self.cmbPayType.setObjectName(_fromUtf8("cmbPayType"))
        self.cmbPayType.addItem(_fromUtf8(""))
        self.cmbPayType.addItem(_fromUtf8(""))
        self.cmbPayType.addItem(_fromUtf8(""))
        self.cmbPayType.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbPayType, 31, 2, 1, 3)
        self.cmbVisitExposition = QtGui.QComboBox(self.tabMisc)
        self.cmbVisitExposition.setObjectName(_fromUtf8("cmbVisitExposition"))
        self.cmbVisitExposition.addItem(_fromUtf8(""))
        self.cmbVisitExposition.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbVisitExposition, 1, 5, 1, 2)
        self.lblOnlyEventsPassedExpertise = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOnlyEventsPassedExpertise.sizePolicy().hasHeightForWidth())
        self.lblOnlyEventsPassedExpertise.setSizePolicy(sizePolicy)
        self.lblOnlyEventsPassedExpertise.setObjectName(_fromUtf8("lblOnlyEventsPassedExpertise"))
        self.gridLayout_2.addWidget(self.lblOnlyEventsPassedExpertise, 5, 0, 1, 1)
        self.chkOnlyEventsPassedExpertise = QtGui.QCheckBox(self.tabMisc)
        self.chkOnlyEventsPassedExpertise.setText(_fromUtf8(""))
        self.chkOnlyEventsPassedExpertise.setObjectName(_fromUtf8("chkOnlyEventsPassedExpertise"))
        self.gridLayout_2.addWidget(self.chkOnlyEventsPassedExpertise, 5, 2, 1, 1)
        self.chkExposeDisciplineBySourceOrg = QtGui.QCheckBox(self.tabMisc)
        self.chkExposeDisciplineBySourceOrg.setObjectName(_fromUtf8("chkExposeDisciplineBySourceOrg"))
        self.gridLayout_2.addWidget(self.chkExposeDisciplineBySourceOrg, 12, 2, 1, 1)
        spacerItem28 = QtGui.QSpacerItem(20, 131, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem28, 34, 0, 1, 1)
        self.cmbCounter = CRBComboBox(self.tabMisc)
        self.cmbCounter.setObjectName(_fromUtf8("cmbCounter"))
        self.cmbCounter.addItem(_fromUtf8(""))
        self.cmbCounter.addItem(_fromUtf8(""))
        self.cmbCounter.addItem(_fromUtf8(""))
        self.cmbCounter.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbCounter, 33, 2, 1, 3)
        self.lblCounter = QtGui.QLabel(self.tabMisc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCounter.sizePolicy().hasHeightForWidth())
        self.lblCounter.setSizePolicy(sizePolicy)
        self.lblCounter.setObjectName(_fromUtf8("lblCounter"))
        self.gridLayout_2.addWidget(self.lblCounter, 33, 0, 1, 2)
        self.tabWidget.addTab(self.tabMisc, _fromUtf8(""))
        self.tabNote = QtGui.QWidget()
        self.tabNote.setObjectName(_fromUtf8("tabNote"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabNote)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.edtNote = QtGui.QTextEdit(self.tabNote)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout_3.addWidget(self.edtNote, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabNote, _fromUtf8(""))
        self.tabAttributes = QtGui.QWidget()
        self.tabAttributes.setObjectName(_fromUtf8("tabAttributes"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabAttributes)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblAttributes = CInDocTableView(self.tabAttributes)
        self.tblAttributes.setObjectName(_fromUtf8("tblAttributes"))
        self.gridLayout_5.addWidget(self.tblAttributes, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabAttributes, _fromUtf8(""))
        self.tabTariffCoefficients = QtGui.QWidget()
        self.tabTariffCoefficients.setObjectName(_fromUtf8("tabTariffCoefficients"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabTariffCoefficients)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblTariffCoefficients = CInDocTableView(self.tabTariffCoefficients)
        self.tblTariffCoefficients.setObjectName(_fromUtf8("tblTariffCoefficients"))
        self.verticalLayout.addWidget(self.tblTariffCoefficients)
        self.tabWidget.addTab(self.tabTariffCoefficients, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_8.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.layoutButtons = QtGui.QHBoxLayout()
        self.layoutButtons.setSpacing(4)
        self.layoutButtons.setObjectName(_fromUtf8("layoutButtons"))
        self.lblTarifs = QtGui.QLabel(ContractEditorDialog)
        self.lblTarifs.setObjectName(_fromUtf8("lblTarifs"))
        self.layoutButtons.addWidget(self.lblTarifs)
        self.btnAdd = QtGui.QPushButton(ContractEditorDialog)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.layoutButtons.addWidget(self.btnAdd)
        self.btnImport = QtGui.QPushButton(ContractEditorDialog)
        self.btnImport.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnImport.setDefault(False)
        self.btnImport.setObjectName(_fromUtf8("btnImport"))
        self.layoutButtons.addWidget(self.btnImport)
        self.btnExport = QtGui.QPushButton(ContractEditorDialog)
        self.btnExport.setObjectName(_fromUtf8("btnExport"))
        self.layoutButtons.addWidget(self.btnExport)
        self.btnImportXML = QtGui.QPushButton(ContractEditorDialog)
        self.btnImportXML.setMinimumSize(QtCore.QSize(100, 0))
        self.btnImportXML.setDefault(False)
        self.btnImportXML.setObjectName(_fromUtf8("btnImportXML"))
        self.layoutButtons.addWidget(self.btnImportXML)
        self.btnExportXML = QtGui.QPushButton(ContractEditorDialog)
        self.btnExportXML.setMinimumSize(QtCore.QSize(100, 0))
        self.btnExportXML.setDefault(False)
        self.btnExportXML.setObjectName(_fromUtf8("btnExportXML"))
        self.layoutButtons.addWidget(self.btnExportXML)
        self.btnImportCSV = QtGui.QPushButton(ContractEditorDialog)
        self.btnImportCSV.setObjectName(_fromUtf8("btnImportCSV"))
        self.layoutButtons.addWidget(self.btnImportCSV)
        self.btnExportXLS = QtGui.QPushButton(ContractEditorDialog)
        self.btnExportXLS.setObjectName(_fromUtf8("btnExportXLS"))
        self.layoutButtons.addWidget(self.btnExportXLS)
        self.btnPrint = CPrintButton(ContractEditorDialog)
        self.btnPrint.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnPrint.setDefault(False)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.layoutButtons.addWidget(self.btnPrint)
        self.lblTariffStatus = QtGui.QLabel(ContractEditorDialog)
        self.lblTariffStatus.setObjectName(_fromUtf8("lblTariffStatus"))
        self.layoutButtons.addWidget(self.lblTariffStatus)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layoutButtons.addItem(spacerItem29)
        self.buttonBox = QtGui.QDialogButtonBox(ContractEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.layoutButtons.addWidget(self.buttonBox)
        self.gridLayout_8.addLayout(self.layoutButtons, 1, 0, 1, 1)
        self.lblExpensePrecision.setBuddy(self.edtExpensePrecision)
        self.lblExposeIfContinuedEventFinished.setBuddy(self.chkExposeIfContinuedEventFinished)
        self.lblDefaultExportFormat.setBuddy(self.cmbDefaultExportFormat)
        self.lblCoefficientEx.setBuddy(self.edtCoefficientEx)
        self.lblCoefficientEx2.setBuddy(self.edtCoefficientEx2)
        self.lblRegionalTariffRegulationFactor.setBuddy(self.edtRegionalTariffRegulationFactor)
        self.lblPricePrecision.setBuddy(self.edtPricePrecision)
        self.lblExposeDiscipline.setBuddy(self.chkExposeDisciplineByMonth)
        self.lblPriceList.setBuddy(self.cmbPriceList)
        self.lblOrgCategory.setBuddy(self.edtOrgCategory)
        self.lblVisitExposition.setBuddy(self.cmbDateOfVisitExposition)
        self.lblCoefficient.setBuddy(self.edtCoefficient)
        self.lblActionExposition.setBuddy(self.cmbDateOfActionExposition)
        self.lblExposeByLastEventContract.setBuddy(self.chkExposeByLastEventContract)
        self.lblExposeExternalServices.setBuddy(self.chkExposeExternalServices)
        self.lblCsgExposition.setBuddy(self.cmbDateOfCsgExposition)
        self.lblOnlyEventsPassedExpertise.setBuddy(self.chkOnlyEventsPassedExpertise)
        self.lblCounter.setBuddy(self.cmbCounter)

        self.retranslateUi(ContractEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        self.cmbDateOfCsgExposition.setCurrentIndex(0)
        self.cmbDateOfVisitExposition.setCurrentIndex(0)
        self.cmbDateOfActionExposition.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ContractEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ContractEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ContractEditorDialog)
        ContractEditorDialog.setTabOrder(self.cmbFinance, self.edtGrouping)
        ContractEditorDialog.setTabOrder(self.edtGrouping, self.edtResolution)
        ContractEditorDialog.setTabOrder(self.edtResolution, self.edtBegDate)
        ContractEditorDialog.setTabOrder(self.edtBegDate, self.cmbRecipient)
        ContractEditorDialog.setTabOrder(self.cmbRecipient, self.edtRecipientINN)
        ContractEditorDialog.setTabOrder(self.edtRecipientINN, self.cmbRecipientAccount)
        ContractEditorDialog.setTabOrder(self.cmbRecipientAccount, self.edtRecipientBank)
        ContractEditorDialog.setTabOrder(self.edtRecipientBank, self.cmbPayer)
        ContractEditorDialog.setTabOrder(self.cmbPayer, self.edtPayerINN)
        ContractEditorDialog.setTabOrder(self.edtPayerINN, self.cmbPayerAccount)
        ContractEditorDialog.setTabOrder(self.cmbPayerAccount, self.edtPayerBank)
        ContractEditorDialog.setTabOrder(self.edtPayerBank, self.btnImport)
        ContractEditorDialog.setTabOrder(self.btnImport, self.btnExport)
        ContractEditorDialog.setTabOrder(self.btnExport, self.btnImportXML)
        ContractEditorDialog.setTabOrder(self.btnImportXML, self.btnExportXML)
        ContractEditorDialog.setTabOrder(self.btnExportXML, self.btnImportCSV)
        ContractEditorDialog.setTabOrder(self.btnImportCSV, self.btnPrint)
        ContractEditorDialog.setTabOrder(self.btnPrint, self.buttonBox)

    def retranslateUi(self, ContractEditorDialog):
        ContractEditorDialog.setWindowTitle(_translate("ContractEditorDialog", "Dialog", None))
        self.lblFinance.setText(_translate("ContractEditorDialog", "Тип финансирования", None))
        self.lblBegDate.setText(_translate("ContractEditorDialog", "Период с", None))
        self.lblGrouping.setText(_translate("ContractEditorDialog", "Группа", None))
        self.lblEndDate.setText(_translate("ContractEditorDialog", "по", None))
        self.edtEndDate.setDisplayFormat(_translate("ContractEditorDialog", "dd.MM.yyyy", None))
        self.lblRecipient.setText(_translate("ContractEditorDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Получатель</span></p></body></html>", None))
        self.edtDate.setDisplayFormat(_translate("ContractEditorDialog", "dd.MM.yyyy", None))
        self.lblFinanceSubtypeCode.setText(_translate("ContractEditorDialog", "Подтип", None))
        self.edtBegDate.setDisplayFormat(_translate("ContractEditorDialog", "dd.MM.yyyy", None))
        self.lblNumber.setText(_translate("ContractEditorDialog", "Номер", None))
        self.btnSelectRecipient.setText(_translate("ContractEditorDialog", "...", None))
        self.lblResolution.setText(_translate("ContractEditorDialog", "Основание", None))
        self.lblDate.setText(_translate("ContractEditorDialog", "Дата", None))
        self.lblRecipientOGRN.setText(_translate("ContractEditorDialog", "ОГРН", None))
        self.lblRecipientINN.setText(_translate("ContractEditorDialog", "ИНН", None))
        self.edtRecipientINN.setInputMask(_translate("ContractEditorDialog", "9999999999; ", None))
        self.edtPayerINN.setInputMask(_translate("ContractEditorDialog", "9999999999; ", None))
        self.lblRecipientAccount.setText(_translate("ContractEditorDialog", "Р/C", None))
        self.lblPayer.setText(_translate("ContractEditorDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Плательщик</span></p></body></html>", None))
        self.lblRecipientKBK.setText(_translate("ContractEditorDialog", "КБК", None))
        self.btnSelectPayer.setText(_translate("ContractEditorDialog", "...", None))
        self.lblPayerBank.setText(_translate("ContractEditorDialog", "Банк", None))
        self.lblPayerKBK.setText(_translate("ContractEditorDialog", "КБК", None))
        self.lblPayerINN.setText(_translate("ContractEditorDialog", "ИНН", None))
        self.lblPayerOGRN.setText(_translate("ContractEditorDialog", "ОГРН", None))
        self.lblRecipientBank.setText(_translate("ContractEditorDialog", "Банк", None))
        self.lblPayerAccount.setText(_translate("ContractEditorDialog", "Р/C", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpecification), _translate("ContractEditorDialog", "Спецификация", None))
        self.lblCode.setText(_translate("ContractEditorDialog", "Код услуги начинается с", None))
        self.chkFilterDate.setText(_translate("ContractEditorDialog", "Действующие на дату", None))
        self.btnApplyFilter.setText(_translate("ContractEditorDialog", "Применить", None))
        self.lblEventType.setText(_translate("ContractEditorDialog", "Событие", None))
        self.lblTariffType.setText(_translate("ContractEditorDialog", "Тарифицируется", None))
        self.lblTariffBatch.setText(_translate("ContractEditorDialog", "Группа", None))
        self.lblService.setText(_translate("ContractEditorDialog", "Услуга", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTariff), _translate("ContractEditorDialog", "Тариф", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabContingent), _translate("ContractEditorDialog", "Контингент", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabContragent ), _translate("ContractEditorDialog", "Контрагенты", None))
        self.lblExpensePrecision.setText(_translate("ContractEditorDialog", "Точность представления статей затрат", None))
        self.chkExposeDisciplineByMonth.setText(_translate("ContractEditorDialog", "На каждый месяц отдельно", None))
        self.chkExposeDisciplineByBatch.setText(_translate("ContractEditorDialog", "На каждую группу тарифа отдельно", None))
        self.lblExposeIfContinuedEventFinished.setText(_translate("ContractEditorDialog", "Продлённые события выставлять, если закрыто продолжение", None))
        self.lblDefaultExportFormat.setText(_translate("ContractEditorDialog", "Формат экспорта счетов по умолчанию", None))
        self.btnCalculation.setText(_translate("ContractEditorDialog", "...", None))
        self.lblCoefficientEx.setText(_translate("ContractEditorDialog", "Коэффициент тарифа при превышении предела", None))
        self.lblCoefficientEx2.setText(_translate("ContractEditorDialog", "Коэффициент тарифа при превышении второго предела", None))
        self.lblRegionalTariffRegulationFactor.setText(_translate("ContractEditorDialog", "Коэффициент районного регулирования тарифов", None))
        self.lblPricePrecision.setText(_translate("ContractEditorDialog", "Точность представления цены тарифа", None))
        self.lblPriceListExternal.setToolTip(_translate("ContractEditorDialog", "Ищет тарифы в указанном договоре, если их нет в данном", None))
        self.lblPriceListExternal.setText(_translate("ContractEditorDialog", "Источник тарифов", None))
        self.lblExposeDiscipline.setText(_translate("ContractEditorDialog", "Формировать счёт", None))
        self.lblPriceList.setText(_translate("ContractEditorDialog", "Прайс-лист", None))
        self.lblOrgCategory.setText(_translate("ContractEditorDialog", "Категория ЛПУ", None))
        self.lblVisitExposition.setText(_translate("ContractEditorDialog", "Выставлять визиты", None))
        self.lblCoefficient.setText(_translate("ContractEditorDialog", "Коэффициент тарифа", None))
        self.lblActionExposition.setText(_translate("ContractEditorDialog", "Выставлять мероприятия", None))
        self.chkExposeDisciplineByEvent.setText(_translate("ContractEditorDialog", "На каждое событие отдельно", None))
        self.lblLimitOfFinancing.setText(_translate("ContractEditorDialog", "Лимит финансирования", None))
        self.chkExposeDisciplineByClient.setText(_translate("ContractEditorDialog", "На каждого пациента отдельно", None))
        self.lblLimitExceeding.setText(_translate("ContractEditorDialog", "Предел превышения", None))
        self.lblActualAmount.setText(_translate("ContractEditorDialog", "Фактическая сумма", None))
        self.lblExposeByLastEventContract.setText(_translate("ContractEditorDialog", "Продлеваемые события выставлять по договору продолжения", None))
        self.lblExposeExternalServices.setText(_translate("ContractEditorDialog", "Выставлять услуги, выполненные в других ЛПУ", None))
        self.lblPayType.setText(_translate("ContractEditorDialog", "Тип расчета", None))
        self.lblCsgExposition.setText(_translate("ContractEditorDialog", "Выставлять КСГ", None))
        self.chkDisableInAccounts.setText(_translate("ContractEditorDialog", "Не отображать в разделе Счета", None))
        self.cmbDateOfCsgExposition.setItemText(0, _translate("ContractEditorDialog", "Независимо от законченности события, дата КСГ в периоде договора", None))
        self.cmbDateOfCsgExposition.setItemText(1, _translate("ContractEditorDialog", "По законченным событиям, дата КСГ в периоде договора", None))
        self.cmbDateOfCsgExposition.setItemText(2, _translate("ContractEditorDialog", "По законченным событиям, дата окончания события в периоде договора", None))
        self.chkExposeByAccountType.setText(_translate("ContractEditorDialog", "Разделять по типам реестров счетов", None))
        self.label.setText(_translate("ContractEditorDialog", "Точность представления значения коэфф.тарифа", None))
        self.cmbDateOfVisitExposition.setItemText(0, _translate("ContractEditorDialog", "Независимо от законченности события, дата визита в периоде договора", None))
        self.cmbDateOfVisitExposition.setItemText(1, _translate("ContractEditorDialog", "По законченным событиям, дата визита в периоде договора", None))
        self.cmbDateOfVisitExposition.setItemText(2, _translate("ContractEditorDialog", "По законченным событиям, дата окончания события в периоде договора", None))
        self.cmbDateOfActionExposition.setItemText(0, _translate("ContractEditorDialog", "Независимо от законченности события, дата мероприятия в периоде договора", None))
        self.cmbDateOfActionExposition.setItemText(1, _translate("ContractEditorDialog", "По законченным событиям, дата мероприятия в периоде договора", None))
        self.cmbDateOfActionExposition.setItemText(2, _translate("ContractEditorDialog", "По законченным событиям, дата окончания события в периоде договора", None))
        self.cmbExposeDisciplineByInsurer.setItemText(0, _translate("ContractEditorDialog", "Без разделения по страховым компаниям", None))
        self.cmbExposeDisciplineByInsurer.setItemText(1, _translate("ContractEditorDialog", "На каждую страховую компанию отдельно (группировка по ОГРН)", None))
        self.cmbExposeDisciplineByInsurer.setItemText(2, _translate("ContractEditorDialog", "На каждый филиал страховой компании отдельно", None))
        self.cmbActionExposition.setItemText(0, _translate("ContractEditorDialog", "по врачу мероприятия", None))
        self.cmbActionExposition.setItemText(1, _translate("ContractEditorDialog", "по врачу события", None))
        self.chkExposeDisciplineByOncology.setText(_translate("ContractEditorDialog", "Онкологические случаи отдельно", None))
        self.cmbPayType.setItemText(0, _translate("ContractEditorDialog", "не задано", None))
        self.cmbPayType.setItemText(1, _translate("ContractEditorDialog", "наличный", None))
        self.cmbPayType.setItemText(2, _translate("ContractEditorDialog", "безналичный", None))
        self.cmbPayType.setItemText(3, _translate("ContractEditorDialog", "комбинированный", None))
        self.cmbVisitExposition.setItemText(0, _translate("ContractEditorDialog", "по врачу визита", None))
        self.cmbVisitExposition.setItemText(1, _translate("ContractEditorDialog", "по врачу события", None))
        self.lblOnlyEventsPassedExpertise.setText(_translate("ContractEditorDialog", "Выставлять только прошедшие экспертизу События", None))
        self.chkExposeDisciplineBySourceOrg.setText(_translate("ContractEditorDialog", "На каждого направителя отдельно", None))
        self.cmbCounter.setItemText(0, _translate("ContractEditorDialog", "не задано", None))
        self.cmbCounter.setItemText(1, _translate("ContractEditorDialog", "наличный", None))
        self.cmbCounter.setItemText(2, _translate("ContractEditorDialog", "безналичный", None))
        self.cmbCounter.setItemText(3, _translate("ContractEditorDialog", "комбинированный", None))
        self.lblCounter.setText(_translate("ContractEditorDialog", "Счетчик номеров реестров", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMisc), _translate("ContractEditorDialog", "Прочее", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNote), _translate("ContractEditorDialog", "Примечание", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAttributes), _translate("ContractEditorDialog", "Атрибуты", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTariffCoefficients), _translate("ContractEditorDialog", "Коэффициенты тарифа", None))
        self.lblTarifs.setText(_translate("ContractEditorDialog", "Тарифы:", None))
        self.btnAdd.setText(_translate("ContractEditorDialog", "Добавить", None))
        self.btnImport.setText(_translate("ContractEditorDialog", "Импорт", None))
        self.btnExport.setText(_translate("ContractEditorDialog", "Экспорт", None))
        self.btnImportXML.setText(_translate("ContractEditorDialog", "Импорт из XML", None))
        self.btnExportXML.setText(_translate("ContractEditorDialog", "Экспорт в XML", None))
        self.btnImportCSV.setText(_translate("ContractEditorDialog", "Импорт из CSV", None))
        self.btnExportXLS.setText(_translate("ContractEditorDialog", "Экспорт в XLS", None))
        self.btnPrint.setText(_translate("ContractEditorDialog", "Печать", None))
        self.lblTariffStatus.setText(_translate("ContractEditorDialog", "Кол-во записей: 0", None))

from OrgComboBox import COrgAccComboBox, COrgComboBox
from PriceListComboBox import CPriceListComboBox, CPriceListComboBoxEx
from RefBooks.Service.RBServiceComboBox import CRBServiceComboBox
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.PrintTemplates import CPrintButton
from library.crbcombobox import CRBComboBox
