# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\Orgs\PersonSubstitution.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PersonSubstitution(object):
    def setupUi(self, PersonSubstitution):
        PersonSubstitution.setObjectName(_fromUtf8("PersonSubstitution"))
        PersonSubstitution.resize(1178, 599)
        self.gridLayout_2 = QtGui.QGridLayout(PersonSubstitution)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget = QtGui.QWidget(PersonSubstitution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2.addWidget(self.widget, 0, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnPrint = QtGui.QPushButton(PersonSubstitution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPrint.sizePolicy().hasHeightForWidth())
        self.btnPrint.setSizePolicy(sizePolicy)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.horizontalLayout.addWidget(self.btnPrint)
        self.btnApply = QtGui.QPushButton(PersonSubstitution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnApply.sizePolicy().hasHeightForWidth())
        self.btnApply.setSizePolicy(sizePolicy)
        self.btnApply.setObjectName(_fromUtf8("btnApply"))
        self.horizontalLayout.addWidget(self.btnApply)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(PersonSubstitution)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridlayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.chkFIO = QtGui.QCheckBox(self.layoutWidget)
        self.chkFIO.setChecked(False)
        self.chkFIO.setObjectName(_fromUtf8("chkFIO"))
        self.gridlayout.addWidget(self.chkFIO, 0, 1, 1, 2)
        self.edtFIO = QtGui.QLineEdit(self.layoutWidget)
        self.edtFIO.setEnabled(False)
        self.edtFIO.setObjectName(_fromUtf8("edtFIO"))
        self.gridlayout.addWidget(self.edtFIO, 1, 1, 1, 2)
        self.chkPost = QtGui.QCheckBox(self.layoutWidget)
        self.chkPost.setChecked(False)
        self.chkPost.setObjectName(_fromUtf8("chkPost"))
        self.gridlayout.addWidget(self.chkPost, 2, 1, 1, 2)
        self.cmbPost = CRBComboBox(self.layoutWidget)
        self.cmbPost.setEnabled(False)
        self.cmbPost.setObjectName(_fromUtf8("cmbPost"))
        self.gridlayout.addWidget(self.cmbPost, 3, 1, 1, 2)
        self.chkSpeciality = QtGui.QCheckBox(self.layoutWidget)
        self.chkSpeciality.setChecked(False)
        self.chkSpeciality.setObjectName(_fromUtf8("chkSpeciality"))
        self.gridlayout.addWidget(self.chkSpeciality, 4, 1, 1, 2)
        self.cmbSpeciality = CRBComboBox(self.layoutWidget)
        self.cmbSpeciality.setEnabled(False)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridlayout.addWidget(self.cmbSpeciality, 5, 1, 1, 2)
        self.lblBegDate = QtGui.QLabel(self.layoutWidget)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridlayout.addWidget(self.lblBegDate, 6, 1, 1, 1)
        self.edtBegDate = CDateEdit(self.layoutWidget)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridlayout.addWidget(self.edtBegDate, 6, 2, 1, 1)
        self.lblEndDate = QtGui.QLabel(self.layoutWidget)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridlayout.addWidget(self.lblEndDate, 7, 1, 1, 1)
        self.edtEndDate = CDateEdit(self.layoutWidget)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridlayout.addWidget(self.edtEndDate, 7, 2, 1, 1)
        self.chkOnlyActive = QtGui.QCheckBox(self.layoutWidget)
        self.chkOnlyActive.setChecked(True)
        self.chkOnlyActive.setObjectName(_fromUtf8("chkOnlyActive"))
        self.gridlayout.addWidget(self.chkOnlyActive, 8, 1, 1, 2)
        self.btnFilterReset = QtGui.QPushButton(self.layoutWidget)
        self.btnFilterReset.setObjectName(_fromUtf8("btnFilterReset"))
        self.gridlayout.addWidget(self.btnFilterReset, 10, 2, 1, 1)
        self.treeOrgStructure = QtGui.QTreeView(self.layoutWidget)
        self.treeOrgStructure.setObjectName(_fromUtf8("treeOrgStructure"))
        self.gridlayout.addWidget(self.treeOrgStructure, 0, 0, 11, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem1, 9, 2, 1, 1)
        self.tblPersonnel = CTableView(self.splitter)
        self.tblPersonnel.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblPersonnel.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblPersonnel.setSortingEnabled(True)
        self.tblPersonnel.setObjectName(_fromUtf8("tblPersonnel"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.splitter_2)
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblSubstitutionPeriods = CTableView(self.gridLayoutWidget_2)
        self.tblSubstitutionPeriods.setSortingEnabled(True)
        self.tblSubstitutionPeriods.setObjectName(_fromUtf8("tblSubstitutionPeriods"))
        self.gridLayout_3.addWidget(self.tblSubstitutionPeriods, 0, 0, 1, 3)
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)

        self.retranslateUi(PersonSubstitution)
        QtCore.QObject.connect(self.btnApply, QtCore.SIGNAL(_fromUtf8("clicked()")), PersonSubstitution.accept)
        QtCore.QObject.connect(self.chkFIO, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFIO.setEnabled)
        QtCore.QObject.connect(self.chkSpeciality, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSpeciality.setEnabled)
        QtCore.QObject.connect(self.chkPost, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbPost.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(PersonSubstitution)

    def retranslateUi(self, PersonSubstitution):
        PersonSubstitution.setWindowTitle(_translate("PersonSubstitution", "Сервис замещения сотрудников", None))
        self.btnPrint.setText(_translate("PersonSubstitution", "Печатать (F6)", None))
        self.btnPrint.setShortcut(_translate("PersonSubstitution", "F6", None))
        self.btnApply.setText(_translate("PersonSubstitution", "Закрыть", None))
        self.chkFIO.setText(_translate("PersonSubstitution", "ФИО", None))
        self.chkPost.setText(_translate("PersonSubstitution", "Должность", None))
        self.chkSpeciality.setText(_translate("PersonSubstitution", "Специальность", None))
        self.lblBegDate.setText(_translate("PersonSubstitution", "Дата начала периода", None))
        self.lblEndDate.setText(_translate("PersonSubstitution", "Дата окончания периода", None))
        self.chkOnlyActive.setText(_translate("PersonSubstitution", "Только активные записи", None))
        self.btnFilterReset.setText(_translate("PersonSubstitution", "Сбросить", None))

from library.DateEdit import CDateEdit
from library.TableView import CTableView
from library.crbcombobox import CRBComboBox
