# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\Samson\UP_s11\client\Orgs\PersonComboBoxExPopup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PersonComboBoxExPopup(object):
    def setupUi(self, PersonComboBoxExPopup):
        PersonComboBoxExPopup.setObjectName(_fromUtf8("PersonComboBoxExPopup"))
        PersonComboBoxExPopup.resize(490, 560)
        self.gridlayout = QtGui.QGridLayout(PersonComboBoxExPopup)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.tabWidget = QtGui.QTabWidget(PersonComboBoxExPopup)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabList = QtGui.QWidget()
        self.tabList.setObjectName(_fromUtf8("tabList"))
        self.vboxlayout = QtGui.QVBoxLayout(self.tabList)
        self.vboxlayout.setMargin(4)
        self.vboxlayout.setSpacing(4)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblPerson = CTableView(self.tabList)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblPerson.sizePolicy().hasHeightForWidth())
        self.tblPerson.setSizePolicy(sizePolicy)
        self.tblPerson.setObjectName(_fromUtf8("tblPerson"))
        self.verticalLayout.addWidget(self.tblPerson)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_fio = QtGui.QLabel(self.tabList)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fio.sizePolicy().hasHeightForWidth())
        self.label_fio.setSizePolicy(sizePolicy)
        self.label_fio.setObjectName(_fromUtf8("label_fio"))
        self.horizontalLayout.addWidget(self.label_fio)
        self.edit_fio = QtGui.QLineEdit(self.tabList)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_fio.sizePolicy().hasHeightForWidth())
        self.edit_fio.setSizePolicy(sizePolicy)
        self.edit_fio.setAutoFillBackground(False)
        self.edit_fio.setMaxLength(16777215)
        self.edit_fio.setObjectName(_fromUtf8("edit_fio"))
        self.horizontalLayout.addWidget(self.edit_fio)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.vboxlayout.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tabList, _fromUtf8(""))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.gridlayout1 = QtGui.QGridLayout(self.tabSearch)
        self.gridlayout1.setMargin(4)
        self.gridlayout1.setSpacing(4)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.lblOrgStructure = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblOrgStructure.setSizePolicy(sizePolicy)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridlayout1.addWidget(self.lblOrgStructure, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(231, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem, 11, 0, 1, 2)
        self.lblSpeciality = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSpeciality.sizePolicy().hasHeightForWidth())
        self.lblSpeciality.setSizePolicy(sizePolicy)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridlayout1.addWidget(self.lblSpeciality, 4, 0, 1, 1)
        self.lblActivity = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblActivity.sizePolicy().hasHeightForWidth())
        self.lblActivity.setSizePolicy(sizePolicy)
        self.lblActivity.setObjectName(_fromUtf8("lblActivity"))
        self.gridlayout1.addWidget(self.lblActivity, 5, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 141, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem1, 10, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout1.addWidget(self.buttonBox, 11, 2, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(self.tabSearch)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridlayout1.addWidget(self.cmbOrgStructure, 1, 1, 1, 2)
        self.cmbSpeciality = CRBComboBox(self.tabSearch)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridlayout1.addWidget(self.cmbSpeciality, 4, 1, 1, 2)
        self.cmbActivity = CRBComboBox(self.tabSearch)
        self.cmbActivity.setObjectName(_fromUtf8("cmbActivity"))
        self.gridlayout1.addWidget(self.cmbActivity, 5, 1, 1, 2)
        self.cmbOrganisation = COrgComboBox(self.tabSearch)
        self.cmbOrganisation.setEnabled(False)
        self.cmbOrganisation.setObjectName(_fromUtf8("cmbOrganisation"))
        self.gridlayout1.addWidget(self.cmbOrganisation, 0, 1, 1, 2)
        self.lblOrganisation = QtGui.QLabel(self.tabSearch)
        self.lblOrganisation.setObjectName(_fromUtf8("lblOrganisation"))
        self.gridlayout1.addWidget(self.lblOrganisation, 0, 0, 1, 1)
        self.chkDeallocatedPerson = QtGui.QCheckBox(self.tabSearch)
        self.chkDeallocatedPerson.setObjectName(_fromUtf8("chkDeallocatedPerson"))
        self.gridlayout1.addWidget(self.chkDeallocatedPerson, 7, 1, 1, 2)
        self.lblPost = QtGui.QLabel(self.tabSearch)
        self.lblPost.setObjectName(_fromUtf8("lblPost"))
        self.gridlayout1.addWidget(self.lblPost, 2, 0, 1, 1)
        self.cmbPost = CRBComboBox(self.tabSearch)
        self.cmbPost.setObjectName(_fromUtf8("cmbPost"))
        self.gridlayout1.addWidget(self.cmbPost, 2, 1, 1, 2)
        self.chkSpeciality = QtGui.QCheckBox(self.tabSearch)
        self.chkSpeciality.setChecked(True)
        self.chkSpeciality.setObjectName(_fromUtf8("chkSpeciality"))
        self.gridlayout1.addWidget(self.chkSpeciality, 3, 1, 1, 2)
        self.chkOnlyDoctors = QtGui.QCheckBox(self.tabSearch)
        self.chkOnlyDoctors.setChecked(True)
        self.chkOnlyDoctors.setObjectName(_fromUtf8("chkOnlyDoctors"))
        self.gridlayout1.addWidget(self.chkOnlyDoctors, 8, 1, 1, 2)
        self.cmbTariffCategory = CRBComboBox(self.tabSearch)
        self.cmbTariffCategory.setObjectName(_fromUtf8("cmbTariffCategory"))
        self.gridlayout1.addWidget(self.cmbTariffCategory, 6, 1, 1, 2)
        self.lblTariffCategory = QtGui.QLabel(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTariffCategory.sizePolicy().hasHeightForWidth())
        self.lblTariffCategory.setSizePolicy(sizePolicy)
        self.lblTariffCategory.setObjectName(_fromUtf8("lblTariffCategory"))
        self.gridlayout1.addWidget(self.lblTariffCategory, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.gridlayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.label_fio.setBuddy(self.edit_fio)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblActivity.setBuddy(self.cmbActivity)
        self.lblOrganisation.setBuddy(self.cmbOrganisation)
        self.lblPost.setBuddy(self.cmbPost)
        self.lblTariffCategory.setBuddy(self.cmbTariffCategory)

        self.retranslateUi(PersonComboBoxExPopup)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PersonComboBoxExPopup)
        PersonComboBoxExPopup.setTabOrder(self.tabWidget, self.cmbOrganisation)
        PersonComboBoxExPopup.setTabOrder(self.cmbOrganisation, self.cmbOrgStructure)
        PersonComboBoxExPopup.setTabOrder(self.cmbOrgStructure, self.cmbPost)
        PersonComboBoxExPopup.setTabOrder(self.cmbPost, self.chkSpeciality)
        PersonComboBoxExPopup.setTabOrder(self.chkSpeciality, self.cmbSpeciality)
        PersonComboBoxExPopup.setTabOrder(self.cmbSpeciality, self.cmbActivity)
        PersonComboBoxExPopup.setTabOrder(self.cmbActivity, self.cmbTariffCategory)
        PersonComboBoxExPopup.setTabOrder(self.cmbTariffCategory, self.chkDeallocatedPerson)
        PersonComboBoxExPopup.setTabOrder(self.chkDeallocatedPerson, self.chkOnlyDoctors)
        PersonComboBoxExPopup.setTabOrder(self.chkOnlyDoctors, self.buttonBox)

    def retranslateUi(self, PersonComboBoxExPopup):
        PersonComboBoxExPopup.setWindowTitle(_translate("PersonComboBoxExPopup", "Form", None))
        self.label_fio.setText(_translate("PersonComboBoxExPopup", "ФИО врача ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabList), _translate("PersonComboBoxExPopup", "Результат поиска", None))
        self.lblOrgStructure.setText(_translate("PersonComboBoxExPopup", "&Подразделение", None))
        self.lblSpeciality.setText(_translate("PersonComboBoxExPopup", "&Специальность", None))
        self.lblActivity.setText(_translate("PersonComboBoxExPopup", "&Вид деятельности", None))
        self.lblOrganisation.setText(_translate("PersonComboBoxExPopup", "&ЛПУ", None))
        self.chkDeallocatedPerson.setText(_translate("PersonComboBoxExPopup", "Уволенные/Заблокированные", None))
        self.lblPost.setText(_translate("PersonComboBoxExPopup", "&Должность", None))
        self.chkSpeciality.setText(_translate("PersonComboBoxExPopup", "Учитывать специальность", None))
        self.chkOnlyDoctors.setText(_translate("PersonComboBoxExPopup", "Учитывать только врачебные должности", None))
        self.lblTariffCategory.setText(_translate("PersonComboBoxExPopup", "&Тарифная категория", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), _translate("PersonComboBoxExPopup", "&Поиск", None))

from OrgComboBox import COrgComboBox
from OrgStructComboBoxes import COrgStructureComboBox
from library.TableView import CTableView
from library.crbcombobox import CRBComboBox
