# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\samson\UP_s11\client_test\Orgs\TariffAddDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TariffAddDialog(object):
    def setupUi(self, TariffAddDialog):
        TariffAddDialog.setObjectName(_fromUtf8("TariffAddDialog"))
        TariffAddDialog.resize(853, 589)
        self.horizontalLayout_7 = QtGui.QHBoxLayout(TariffAddDialog)
        self.horizontalLayout_7.setMargin(4)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tabWidget = QtGui.QTabWidget(TariffAddDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget.setAcceptDrops(False)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setMargin(4)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widget_4 = QtGui.QWidget(self.widget)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.formLayout = QtGui.QFormLayout(self.widget_4)
        self.formLayout.setMargin(0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.groupBox = QtGui.QGroupBox(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setMargin(4)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.edtDate = CDateEdit(self.groupBox)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.verticalLayout_4.addWidget(self.edtDate)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.edtTariff = QtGui.QLineEdit(self.groupBox)
        self.edtTariff.setText(_fromUtf8(""))
        self.edtTariff.setObjectName(_fromUtf8("edtTariff"))
        self.verticalLayout_4.addWidget(self.edtTariff)
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.widget_4)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setMargin(4)
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.cmbTariffType = QtGui.QComboBox(self.groupBox_2)
        self.cmbTariffType.setObjectName(_fromUtf8("cmbTariffType"))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.cmbTariffType.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.cmbTariffType)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.cmbAid = CRBComboBox(self.groupBox_2)
        self.cmbAid.setObjectName(_fromUtf8("cmbAid"))
        self.verticalLayout_5.addWidget(self.cmbAid)
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.groupBox_2)
        self.verticalLayout_6.addWidget(self.widget_4)
        self.horizontalLayout_2.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(self.tab)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setMargin(4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.widget_2)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setMargin(4)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.chkContract = QtGui.QCheckBox(self.groupBox_3)
        self.chkContract.setObjectName(_fromUtf8("chkContract"))
        self.horizontalLayout_4.addWidget(self.chkContract)
        self.edtFilter = QtGui.QLineEdit(self.groupBox_3)
        self.edtFilter.setObjectName(_fromUtf8("edtFilter"))
        self.horizontalLayout_4.addWidget(self.edtFilter)
        self.btnApplyfilter = QtGui.QPushButton(self.groupBox_3)
        self.btnApplyfilter.setObjectName(_fromUtf8("btnApplyfilter"))
        self.horizontalLayout_4.addWidget(self.btnApplyfilter)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.tblService = CInDocTableView(self.widget_2)
        self.tblService.setObjectName(_fromUtf8("tblService"))
        self.verticalLayout_3.addWidget(self.tblService)
        self.lblChecked = QtGui.QLabel(self.widget_2)
        self.lblChecked.setText(_fromUtf8(""))
        self.lblChecked.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblChecked.setObjectName(_fromUtf8("lblChecked"))
        self.verticalLayout_3.addWidget(self.lblChecked)
        self.widget_3 = QtGui.QWidget(self.widget_2)
        self.widget_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnClear = QtGui.QPushButton(self.widget_3)
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.horizontalLayout.addWidget(self.btnClear)
        self.btnAll = QtGui.QPushButton(self.widget_3)
        self.btnAll.setObjectName(_fromUtf8("btnAll"))
        self.horizontalLayout.addWidget(self.btnAll)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.widget_5 = QtGui.QWidget(self.tab)
        self.widget_5.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setMargin(4)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnCancel = QtGui.QPushButton(self.widget_5)
        self.btnCancel.setMinimumSize(QtCore.QSize(100, 0))
        self.btnCancel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnCancel.setAutoDefault(False)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.btnAdd = QtGui.QPushButton(self.widget_5)
        self.btnAdd.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAdd.setAutoDefault(False)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.horizontalLayout_3.addWidget(self.btnAdd)
        self.gridLayout.addWidget(self.widget_5, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.edtDateChange = CDateEdit(self.tab_2)
        self.edtDateChange.setObjectName(_fromUtf8("edtDateChange"))
        self.horizontalLayout_5.addWidget(self.edtDateChange)
        self.chkOnlyUET = QtGui.QCheckBox(self.tab_2)
        self.chkOnlyUET.setObjectName(_fromUtf8("chkOnlyUET"))
        self.horizontalLayout_5.addWidget(self.chkOnlyUET)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.tblTariff = QtGui.QTableWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblTariff.sizePolicy().hasHeightForWidth())
        self.tblTariff.setSizePolicy(sizePolicy)
        self.tblTariff.setObjectName(_fromUtf8("tblTariff"))
        self.tblTariff.setColumnCount(0)
        self.tblTariff.setRowCount(0)
        self.horizontalLayout_8.addWidget(self.tblTariff)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setHorizontalSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblTariffServices = CTableView(self.groupBox_4)
        self.tblTariffServices.setObjectName(_fromUtf8("tblTariffServices"))
        self.gridLayout_4.addWidget(self.tblTariffServices, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.widget_6 = QtGui.QWidget(self.tab_2)
        self.widget_6.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setMargin(4)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnCancelChange = QtGui.QPushButton(self.widget_6)
        self.btnCancelChange.setMinimumSize(QtCore.QSize(100, 0))
        self.btnCancelChange.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnCancelChange.setAutoDefault(False)
        self.btnCancelChange.setObjectName(_fromUtf8("btnCancelChange"))
        self.horizontalLayout_6.addWidget(self.btnCancelChange)
        self.btnSaveChange = QtGui.QPushButton(self.widget_6)
        self.btnSaveChange.setMinimumSize(QtCore.QSize(0, 0))
        self.btnSaveChange.setAutoDefault(False)
        self.btnSaveChange.setObjectName(_fromUtf8("btnSaveChange"))
        self.horizontalLayout_6.addWidget(self.btnSaveChange)
        self.verticalLayout.addWidget(self.widget_6)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.tabWidget)
        self.label.setBuddy(self.edtDate)
        self.label_2.setBuddy(self.edtTariff)
        self.label_4.setBuddy(self.cmbTariffType)
        self.label_3.setBuddy(self.cmbAid)

        self.retranslateUi(TariffAddDialog)
        self.tabWidget.setCurrentIndex(0)
        self.cmbTariffType.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(TariffAddDialog)
        TariffAddDialog.setTabOrder(self.edtDate, self.edtTariff)
        TariffAddDialog.setTabOrder(self.edtTariff, self.cmbTariffType)
        TariffAddDialog.setTabOrder(self.cmbTariffType, self.cmbAid)
        TariffAddDialog.setTabOrder(self.cmbAid, self.tblService)
        TariffAddDialog.setTabOrder(self.tblService, self.btnClear)

    def retranslateUi(self, TariffAddDialog):
        TariffAddDialog.setWindowTitle(_translate("TariffAddDialog", "Dialog", None))
        self.groupBox.setTitle(_translate("TariffAddDialog", "Основные параметры", None))
        self.label.setText(_translate("TariffAddDialog", "Дата начала", None))
        self.label_2.setText(_translate("TariffAddDialog", "Тариф", None))
        self.groupBox_2.setTitle(_translate("TariffAddDialog", "Дополнительные параметры", None))
        self.label_4.setText(_translate("TariffAddDialog", "Тарифицируется", None))
        self.cmbTariffType.setItemText(0, _translate("TariffAddDialog", "Посещение", None))
        self.cmbTariffType.setItemText(1, _translate("TariffAddDialog", "Событие", None))
        self.cmbTariffType.setItemText(2, _translate("TariffAddDialog", "Мероприятие по количеству", None))
        self.cmbTariffType.setItemText(3, _translate("TariffAddDialog", "Визит-день", None))
        self.cmbTariffType.setItemText(4, _translate("TariffAddDialog", "Событие по койко-дням", None))
        self.cmbTariffType.setItemText(5, _translate("TariffAddDialog", "Мероприятие по УЕТ", None))
        self.cmbTariffType.setItemText(6, _translate("TariffAddDialog", "Мероприятие по количеству и тарифу койки", None))
        self.cmbTariffType.setItemText(7, _translate("TariffAddDialog", "Визиты по мероприятию", None))
        self.cmbTariffType.setItemText(8, _translate("TariffAddDialog", "Визиты по МЭС", None))
        self.cmbTariffType.setItemText(9, _translate("TariffAddDialog", "Событие по МЭС", None))
        self.cmbTariffType.setItemText(10, _translate("TariffAddDialog", "Событие по МЭС с учётом длительности", None))
        self.cmbTariffType.setItemText(11, _translate("TariffAddDialog", "Визиты по профилю", None))
        self.cmbTariffType.setItemText(12, _translate("TariffAddDialog", "Событие по МЭС с учётом уровня выполнения и длительности", None))
        self.cmbTariffType.setItemText(13, _translate("TariffAddDialog", "Краснодар,П13: событие по КСГ с учётом длительности и операций", None))
        self.cmbTariffType.setItemText(14, _translate("TariffAddDialog", "Мурманск,2015: стационар", None))
        self.label_3.setText(_translate("TariffAddDialog", "Ед. Уч.", None))
        self.groupBox_3.setTitle(_translate("TariffAddDialog", "Фильтр", None))
        self.chkContract.setText(_translate("TariffAddDialog", "По договору", None))
        self.btnApplyfilter.setText(_translate("TariffAddDialog", "Применить", None))
        self.btnClear.setText(_translate("TariffAddDialog", "Очистить выбор", None))
        self.btnAll.setText(_translate("TariffAddDialog", "Выделить все", None))
        self.btnCancel.setText(_translate("TariffAddDialog", "Отмена", None))
        self.btnAdd.setText(_translate("TariffAddDialog", "Добавить", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TariffAddDialog", "Добавление", None))
        self.label_5.setText(_translate("TariffAddDialog", "На дату:", None))
        self.chkOnlyUET.setText(_translate("TariffAddDialog", "Только тарифы с УЕТ", None))
        self.groupBox_4.setTitle(_translate("TariffAddDialog", "Список услуг с выбранным тарифом", None))
        self.btnCancelChange.setText(_translate("TariffAddDialog", "Отмена", None))
        self.btnSaveChange.setText(_translate("TariffAddDialog", "Сохранить", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TariffAddDialog", "Замена", None))

from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.TableView import CTableView
from library.crbcombobox import CRBComboBox
