# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\samson\UP_s11\client\RefBooks\ActionType\GroupActionTypeEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GroupActionTypeEditorDialog(object):
    def setupUi(self, GroupActionTypeEditorDialog):
        GroupActionTypeEditorDialog.setObjectName(_fromUtf8("GroupActionTypeEditorDialog"))
        GroupActionTypeEditorDialog.resize(712, 811)
        self.verticalLayout = QtGui.QVBoxLayout(GroupActionTypeEditorDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(GroupActionTypeEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.chkChkShowInForm = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkShowInForm.sizePolicy().hasHeightForWidth())
        self.chkChkShowInForm.setSizePolicy(sizePolicy)
        self.chkChkShowInForm.setText(_fromUtf8(""))
        self.chkChkShowInForm.setObjectName(_fromUtf8("chkChkShowInForm"))
        self.horizontalLayout_11.addWidget(self.chkChkShowInForm)
        self.chkShowInForm = QtGui.QCheckBox(self.tab)
        self.chkShowInForm.setEnabled(False)
        self.chkShowInForm.setCheckable(True)
        self.chkShowInForm.setChecked(True)
        self.chkShowInForm.setObjectName(_fromUtf8("chkShowInForm"))
        self.horizontalLayout_11.addWidget(self.chkShowInForm)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 7, 0, 1, 5)
        self.edtMaxOccursInEvent = QtGui.QSpinBox(self.tab)
        self.edtMaxOccursInEvent.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMaxOccursInEvent.sizePolicy().hasHeightForWidth())
        self.edtMaxOccursInEvent.setSizePolicy(sizePolicy)
        self.edtMaxOccursInEvent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.edtMaxOccursInEvent.setObjectName(_fromUtf8("edtMaxOccursInEvent"))
        self.gridLayout_2.addWidget(self.edtMaxOccursInEvent, 20, 1, 1, 3)
        self.horizontalFrame = QtGui.QFrame(self.tab)
        self.horizontalFrame.setEnabled(False)
        self.horizontalFrame.setObjectName(_fromUtf8("horizontalFrame"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cmbBegAgeUnit = QtGui.QComboBox(self.horizontalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbBegAgeUnit.setObjectName(_fromUtf8("cmbBegAgeUnit"))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cmbBegAgeUnit)
        self.edtBegAgeCount = QtGui.QLineEdit(self.horizontalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAgeCount.sizePolicy().hasHeightForWidth())
        self.edtBegAgeCount.setSizePolicy(sizePolicy)
        self.edtBegAgeCount.setMaxLength(3)
        self.edtBegAgeCount.setObjectName(_fromUtf8("edtBegAgeCount"))
        self.horizontalLayout_4.addWidget(self.edtBegAgeCount)
        self.lblAgeSep = QtGui.QLabel(self.horizontalFrame)
        self.lblAgeSep.setObjectName(_fromUtf8("lblAgeSep"))
        self.horizontalLayout_4.addWidget(self.lblAgeSep)
        self.cmbEndAgeUnit = QtGui.QComboBox(self.horizontalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbEndAgeUnit.setObjectName(_fromUtf8("cmbEndAgeUnit"))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cmbEndAgeUnit)
        self.edtEndAgeCount = QtGui.QLineEdit(self.horizontalFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAgeCount.sizePolicy().hasHeightForWidth())
        self.edtEndAgeCount.setSizePolicy(sizePolicy)
        self.edtEndAgeCount.setMaxLength(3)
        self.edtEndAgeCount.setObjectName(_fromUtf8("edtEndAgeCount"))
        self.horizontalLayout_4.addWidget(self.edtEndAgeCount)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.horizontalFrame, 2, 1, 1, 4)
        self.chkAge = QtGui.QCheckBox(self.tab)
        self.chkAge.setObjectName(_fromUtf8("chkAge"))
        self.gridLayout_2.addWidget(self.chkAge, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.edtBegDate = CDateEdit(self.tab)
        self.edtBegDate.setEnabled(False)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout_7.addWidget(self.edtBegDate)
        self.lblActionTypeValidTo = QtGui.QLabel(self.tab)
        self.lblActionTypeValidTo.setEnabled(False)
        self.lblActionTypeValidTo.setObjectName(_fromUtf8("lblActionTypeValidTo"))
        self.horizontalLayout_7.addWidget(self.lblActionTypeValidTo)
        self.endEndDate = CDateEdit(self.tab)
        self.endEndDate.setEnabled(False)
        self.endEndDate.setCalendarPopup(True)
        self.endEndDate.setObjectName(_fromUtf8("endEndDate"))
        self.horizontalLayout_7.addWidget(self.endEndDate)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 17, 1, 1, 4)
        self.chkSex = QtGui.QCheckBox(self.tab)
        self.chkSex.setObjectName(_fromUtf8("chkSex"))
        self.gridLayout_2.addWidget(self.chkSex, 0, 0, 1, 1)
        self.chkActionTypeValidFrom = QtGui.QCheckBox(self.tab)
        self.chkActionTypeValidFrom.setObjectName(_fromUtf8("chkActionTypeValidFrom"))
        self.gridLayout_2.addWidget(self.chkActionTypeValidFrom, 17, 0, 1, 1)
        self.chkContext = QtGui.QCheckBox(self.tab)
        self.chkContext.setObjectName(_fromUtf8("chkContext"))
        self.gridLayout_2.addWidget(self.chkContext, 18, 0, 1, 1)
        self.chkExposeDateSelector = QtGui.QCheckBox(self.tab)
        self.chkExposeDateSelector.setObjectName(_fromUtf8("chkExposeDateSelector"))
        self.gridLayout_2.addWidget(self.chkExposeDateSelector, 22, 0, 1, 1)
        self.cmbExposeDateSelector = QtGui.QComboBox(self.tab)
        self.cmbExposeDateSelector.setEnabled(False)
        self.cmbExposeDateSelector.setObjectName(_fromUtf8("cmbExposeDateSelector"))
        self.cmbExposeDateSelector.addItem(_fromUtf8(""))
        self.cmbExposeDateSelector.addItem(_fromUtf8(""))
        self.cmbExposeDateSelector.addItem(_fromUtf8(""))
        self.cmbExposeDateSelector.addItem(_fromUtf8(""))
        self.cmbExposeDateSelector.addItem(_fromUtf8(""))
        self.cmbExposeDateSelector.setItemText(4, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbExposeDateSelector, 22, 1, 1, 4)
        self.edtContext = QtGui.QLineEdit(self.tab)
        self.edtContext.setEnabled(False)
        self.edtContext.setMaxLength(64)
        self.edtContext.setObjectName(_fromUtf8("edtContext"))
        self.gridLayout_2.addWidget(self.edtContext, 18, 1, 1, 4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.chkChkShowTime = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkShowTime.sizePolicy().hasHeightForWidth())
        self.chkChkShowTime.setSizePolicy(sizePolicy)
        self.chkChkShowTime.setText(_fromUtf8(""))
        self.chkChkShowTime.setObjectName(_fromUtf8("chkChkShowTime"))
        self.horizontalLayout_8.addWidget(self.chkChkShowTime)
        self.chkShowTime = QtGui.QCheckBox(self.tab)
        self.chkShowTime.setEnabled(False)
        self.chkShowTime.setObjectName(_fromUtf8("chkShowTime"))
        self.horizontalLayout_8.addWidget(self.chkShowTime)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 4, 0, 1, 5)
        self.chkNeedAttachFile = QtGui.QCheckBox(self.tab)
        self.chkNeedAttachFile.setObjectName(_fromUtf8("chkNeedAttachFile"))
        self.gridLayout_2.addWidget(self.chkNeedAttachFile, 23, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.chkChkShowBegDate = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkShowBegDate.sizePolicy().hasHeightForWidth())
        self.chkChkShowBegDate.setSizePolicy(sizePolicy)
        self.chkChkShowBegDate.setText(_fromUtf8(""))
        self.chkChkShowBegDate.setObjectName(_fromUtf8("chkChkShowBegDate"))
        self.horizontalLayout_13.addWidget(self.chkChkShowBegDate)
        self.chkShowBegDate = QtGui.QCheckBox(self.tab)
        self.chkShowBegDate.setEnabled(False)
        self.chkShowBegDate.setObjectName(_fromUtf8("chkShowBegDate"))
        self.horizontalLayout_13.addWidget(self.chkShowBegDate)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 3, 0, 1, 5)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.chkPreferable = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkPreferable.sizePolicy().hasHeightForWidth())
        self.chkPreferable.setSizePolicy(sizePolicy)
        self.chkPreferable.setText(_fromUtf8(""))
        self.chkPreferable.setObjectName(_fromUtf8("chkPreferable"))
        self.horizontalLayout_12.addWidget(self.chkPreferable)
        self.chkIsPreferable = QtGui.QCheckBox(self.tab)
        self.chkIsPreferable.setEnabled(False)
        self.chkIsPreferable.setObjectName(_fromUtf8("chkIsPreferable"))
        self.horizontalLayout_12.addWidget(self.chkIsPreferable)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 19, 0, 1, 5)
        self.cmbSex = QtGui.QComboBox(self.tab)
        self.cmbSex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbSex, 0, 1, 1, 2)
        self.statusLayout = QtGui.QHBoxLayout()
        self.statusLayout.setObjectName(_fromUtf8("statusLayout"))
        self.chkChkEditStatus = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkEditStatus.sizePolicy().hasHeightForWidth())
        self.chkChkEditStatus.setSizePolicy(sizePolicy)
        self.chkChkEditStatus.setText(_fromUtf8(""))
        self.chkChkEditStatus.setObjectName(_fromUtf8("chkChkEditStatus"))
        self.statusLayout.addWidget(self.chkChkEditStatus)
        self.chkEditStatus = QtGui.QCheckBox(self.tab)
        self.chkEditStatus.setEnabled(False)
        self.chkEditStatus.setObjectName(_fromUtf8("chkEditStatus"))
        self.statusLayout.addWidget(self.chkEditStatus)
        self.gridLayout_2.addLayout(self.statusLayout, 8, 0, 1, 5)
        self.chkServiceType = QtGui.QCheckBox(self.tab)
        self.chkServiceType.setObjectName(_fromUtf8("chkServiceType"))
        self.gridLayout_2.addWidget(self.chkServiceType, 21, 0, 1, 1)
        self.cmbServiceType = CActionServiceTypeComboBox(self.tab)
        self.cmbServiceType.setEnabled(False)
        self.cmbServiceType.setObjectName(_fromUtf8("cmbServiceType"))
        self.gridLayout_2.addWidget(self.cmbServiceType, 21, 1, 1, 4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.chkAssistant = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAssistant.sizePolicy().hasHeightForWidth())
        self.chkAssistant.setSizePolicy(sizePolicy)
        self.chkAssistant.setText(_fromUtf8(""))
        self.chkAssistant.setObjectName(_fromUtf8("chkAssistant"))
        self.horizontalLayout_10.addWidget(self.chkAssistant)
        self.chkHasAssistant = QtGui.QCheckBox(self.tab)
        self.chkHasAssistant.setEnabled(False)
        self.chkHasAssistant.setObjectName(_fromUtf8("chkHasAssistant"))
        self.horizontalLayout_10.addWidget(self.chkHasAssistant)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 6, 0, 1, 5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.chkChkRequiredCoordination = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkRequiredCoordination.sizePolicy().hasHeightForWidth())
        self.chkChkRequiredCoordination.setSizePolicy(sizePolicy)
        self.chkChkRequiredCoordination.setText(_fromUtf8(""))
        self.chkChkRequiredCoordination.setObjectName(_fromUtf8("chkChkRequiredCoordination"))
        self.horizontalLayout_9.addWidget(self.chkChkRequiredCoordination)
        self.chkRequiredCoordination = QtGui.QCheckBox(self.tab)
        self.chkRequiredCoordination.setEnabled(False)
        self.chkRequiredCoordination.setObjectName(_fromUtf8("chkRequiredCoordination"))
        self.horizontalLayout_9.addWidget(self.chkRequiredCoordination)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 5, 0, 1, 5)
        self.chkMaxOccursInEvent = QtGui.QCheckBox(self.tab)
        self.chkMaxOccursInEvent.setObjectName(_fromUtf8("chkMaxOccursInEvent"))
        self.gridLayout_2.addWidget(self.chkMaxOccursInEvent, 20, 0, 1, 1)
        self.duplicationLayout = QtGui.QHBoxLayout()
        self.duplicationLayout.setObjectName(_fromUtf8("duplicationLayout"))
        self.chkChkDuplication = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkDuplication.sizePolicy().hasHeightForWidth())
        self.chkChkDuplication.setSizePolicy(sizePolicy)
        self.chkChkDuplication.setText(_fromUtf8(""))
        self.chkChkDuplication.setObjectName(_fromUtf8("chkChkDuplication"))
        self.duplicationLayout.addWidget(self.chkChkDuplication)
        self.chkDuplication = QtGui.QCheckBox(self.tab)
        self.chkDuplication.setEnabled(False)
        self.chkDuplication.setObjectName(_fromUtf8("chkDuplication"))
        self.duplicationLayout.addWidget(self.chkDuplication)
        self.gridLayout_2.addLayout(self.duplicationLayout, 13, 0, 1, 5)
        self.execPersLayout = QtGui.QHBoxLayout()
        self.execPersLayout.setObjectName(_fromUtf8("execPersLayout"))
        self.chkChkEditExecPers = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkEditExecPers.sizePolicy().hasHeightForWidth())
        self.chkChkEditExecPers.setSizePolicy(sizePolicy)
        self.chkChkEditExecPers.setText(_fromUtf8(""))
        self.chkChkEditExecPers.setObjectName(_fromUtf8("chkChkEditExecPers"))
        self.execPersLayout.addWidget(self.chkChkEditExecPers)
        self.chkEditExecPers = QtGui.QCheckBox(self.tab)
        self.chkEditExecPers.setEnabled(False)
        self.chkEditExecPers.setObjectName(_fromUtf8("chkEditExecPers"))
        self.execPersLayout.addWidget(self.chkEditExecPers)
        self.gridLayout_2.addLayout(self.execPersLayout, 11, 0, 1, 5)
        self.begDateLayout = QtGui.QHBoxLayout()
        self.begDateLayout.setObjectName(_fromUtf8("begDateLayout"))
        self.chkChkEditBegDate = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkEditBegDate.sizePolicy().hasHeightForWidth())
        self.chkChkEditBegDate.setSizePolicy(sizePolicy)
        self.chkChkEditBegDate.setText(_fromUtf8(""))
        self.chkChkEditBegDate.setObjectName(_fromUtf8("chkChkEditBegDate"))
        self.begDateLayout.addWidget(self.chkChkEditBegDate)
        self.chkEditBegDate = QtGui.QCheckBox(self.tab)
        self.chkEditBegDate.setEnabled(False)
        self.chkEditBegDate.setObjectName(_fromUtf8("chkEditBegDate"))
        self.begDateLayout.addWidget(self.chkEditBegDate)
        self.gridLayout_2.addLayout(self.begDateLayout, 9, 0, 1, 5)
        self.endDateLayout = QtGui.QHBoxLayout()
        self.endDateLayout.setObjectName(_fromUtf8("endDateLayout"))
        self.chkChkEditEndDate = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkEditEndDate.sizePolicy().hasHeightForWidth())
        self.chkChkEditEndDate.setSizePolicy(sizePolicy)
        self.chkChkEditEndDate.setText(_fromUtf8(""))
        self.chkChkEditEndDate.setObjectName(_fromUtf8("chkChkEditEndDate"))
        self.endDateLayout.addWidget(self.chkChkEditEndDate)
        self.chkEditEndDate = QtGui.QCheckBox(self.tab)
        self.chkEditEndDate.setEnabled(False)
        self.chkEditEndDate.setObjectName(_fromUtf8("chkEditEndDate"))
        self.endDateLayout.addWidget(self.chkEditEndDate)
        self.gridLayout_2.addLayout(self.endDateLayout, 10, 0, 1, 5)
        self.noteLayout = QtGui.QHBoxLayout()
        self.noteLayout.setObjectName(_fromUtf8("noteLayout"))
        self.chkChkEditNote = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkEditNote.sizePolicy().hasHeightForWidth())
        self.chkChkEditNote.setSizePolicy(sizePolicy)
        self.chkChkEditNote.setText(_fromUtf8(""))
        self.chkChkEditNote.setObjectName(_fromUtf8("chkChkEditNote"))
        self.noteLayout.addWidget(self.chkChkEditNote)
        self.chkEditNote = QtGui.QCheckBox(self.tab)
        self.chkEditNote.setEnabled(False)
        self.chkEditNote.setObjectName(_fromUtf8("chkEditNote"))
        self.noteLayout.addWidget(self.chkEditNote)
        self.gridLayout_2.addLayout(self.noteLayout, 12, 0, 1, 5)
        self.cmbNeedAttachFile = QtGui.QComboBox(self.tab)
        self.cmbNeedAttachFile.setEnabled(False)
        self.cmbNeedAttachFile.setObjectName(_fromUtf8("cmbNeedAttachFile"))
        self.cmbNeedAttachFile.addItem(_fromUtf8(""))
        self.cmbNeedAttachFile.addItem(_fromUtf8(""))
        self.cmbNeedAttachFile.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbNeedAttachFile, 23, 1, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 24, 0, 1, 5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkChkIgnoreVisibleRights = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkIgnoreVisibleRights.sizePolicy().hasHeightForWidth())
        self.chkChkIgnoreVisibleRights.setSizePolicy(sizePolicy)
        self.chkChkIgnoreVisibleRights.setText(_fromUtf8(""))
        self.chkChkIgnoreVisibleRights.setObjectName(_fromUtf8("chkChkIgnoreVisibleRights"))
        self.horizontalLayout.addWidget(self.chkChkIgnoreVisibleRights)
        self.chkIgnoreVisibleRights = QtGui.QCheckBox(self.tab)
        self.chkIgnoreVisibleRights.setEnabled(False)
        self.chkIgnoreVisibleRights.setObjectName(_fromUtf8("chkIgnoreVisibleRights"))
        self.horizontalLayout.addWidget(self.chkIgnoreVisibleRights)
        self.gridLayout_2.addLayout(self.horizontalLayout, 14, 0, 1, 5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chkChkEditSetPerson = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkEditSetPerson.sizePolicy().hasHeightForWidth())
        self.chkChkEditSetPerson.setSizePolicy(sizePolicy)
        self.chkChkEditSetPerson.setText(_fromUtf8(""))
        self.chkChkEditSetPerson.setObjectName(_fromUtf8("chkChkEditSetPerson"))
        self.horizontalLayout_2.addWidget(self.chkChkEditSetPerson)
        self.chkEditSetPerson = QtGui.QCheckBox(self.tab)
        self.chkEditSetPerson.setEnabled(False)
        self.chkEditSetPerson.setObjectName(_fromUtf8("chkEditSetPerson"))
        self.horizontalLayout_2.addWidget(self.chkEditSetPerson)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 15, 0, 1, 5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.chkChkEditOrg = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkChkEditOrg.sizePolicy().hasHeightForWidth())
        self.chkChkEditOrg.setSizePolicy(sizePolicy)
        self.chkChkEditOrg.setText(_fromUtf8(""))
        self.chkChkEditOrg.setObjectName(_fromUtf8("chkChkEditOrg"))
        self.horizontalLayout_3.addWidget(self.chkChkEditOrg)
        self.chkEditOrg = QtGui.QCheckBox(self.tab)
        self.chkEditOrg.setEnabled(False)
        self.chkEditOrg.setObjectName(_fromUtf8("chkEditOrg"))
        self.horizontalLayout_3.addWidget(self.chkEditOrg)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 16, 0, 1, 5)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cmbDefaultStatus = CActionStatusComboBox(self.tab_2)
        self.cmbDefaultStatus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDefaultStatus.sizePolicy().hasHeightForWidth())
        self.cmbDefaultStatus.setSizePolicy(sizePolicy)
        self.cmbDefaultStatus.setObjectName(_fromUtf8("cmbDefaultStatus"))
        self.gridLayout_3.addWidget(self.cmbDefaultStatus, 0, 1, 1, 2)
        self.cmbDefaultBegDate = QtGui.QComboBox(self.tab_2)
        self.cmbDefaultBegDate.setEnabled(False)
        self.cmbDefaultBegDate.setObjectName(_fromUtf8("cmbDefaultBegDate"))
        self.cmbDefaultBegDate.addItem(_fromUtf8(""))
        self.cmbDefaultBegDate.addItem(_fromUtf8(""))
        self.cmbDefaultBegDate.addItem(_fromUtf8(""))
        self.cmbDefaultBegDate.addItem(_fromUtf8(""))
        self.cmbDefaultBegDate.addItem(_fromUtf8(""))
        self.cmbDefaultBegDate.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbDefaultBegDate, 3, 1, 1, 2)
        self.chkIsMorphologyRequired = QtGui.QCheckBox(self.tab_2)
        self.chkIsMorphologyRequired.setObjectName(_fromUtf8("chkIsMorphologyRequired"))
        self.gridLayout_3.addWidget(self.chkIsMorphologyRequired, 12, 0, 1, 1)
        self.chkAddVisit = QtGui.QCheckBox(self.tab_2)
        self.chkAddVisit.setEnabled(False)
        self.chkAddVisit.setObjectName(_fromUtf8("chkAddVisit"))
        self.gridLayout_3.addWidget(self.chkAddVisit, 16, 1, 1, 1)
        self.chkAddVisitGroup = QtGui.QCheckBox(self.tab_2)
        self.chkAddVisitGroup.setObjectName(_fromUtf8("chkAddVisitGroup"))
        self.gridLayout_3.addWidget(self.chkAddVisitGroup, 16, 0, 1, 1)
        self.cmbAddVisitScene = CRBComboBox(self.tab_2)
        self.cmbAddVisitScene.setEnabled(False)
        self.cmbAddVisitScene.setObjectName(_fromUtf8("cmbAddVisitScene"))
        self.cmbAddVisitScene.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbAddVisitScene, 16, 2, 1, 1)
        self.chkDefaultExecPerson = QtGui.QCheckBox(self.tab_2)
        self.chkDefaultExecPerson.setObjectName(_fromUtf8("chkDefaultExecPerson"))
        self.gridLayout_3.addWidget(self.chkDefaultExecPerson, 6, 0, 1, 1)
        self.cmbDefaultPersonInEditor = QtGui.QComboBox(self.tab_2)
        self.cmbDefaultPersonInEditor.setEnabled(False)
        self.cmbDefaultPersonInEditor.setObjectName(_fromUtf8("cmbDefaultPersonInEditor"))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEditor.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbDefaultPersonInEditor, 8, 1, 1, 2)
        self.cmbDefaultDirectionDate = QtGui.QComboBox(self.tab_2)
        self.cmbDefaultDirectionDate.setEnabled(False)
        self.cmbDefaultDirectionDate.setObjectName(_fromUtf8("cmbDefaultDirectionDate"))
        self.cmbDefaultDirectionDate.addItem(_fromUtf8(""))
        self.cmbDefaultDirectionDate.addItem(_fromUtf8(""))
        self.cmbDefaultDirectionDate.addItem(_fromUtf8(""))
        self.cmbDefaultDirectionDate.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbDefaultDirectionDate, 1, 1, 1, 2)
        self.cmbDefaultMKB = QtGui.QComboBox(self.tab_2)
        self.cmbDefaultMKB.setEnabled(False)
        self.cmbDefaultMKB.setObjectName(_fromUtf8("cmbDefaultMKB"))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.cmbDefaultMKB.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbDefaultMKB, 10, 1, 1, 2)
        self.chkDefaultPersonInEvent = QtGui.QCheckBox(self.tab_2)
        self.chkDefaultPersonInEvent.setObjectName(_fromUtf8("chkDefaultPersonInEvent"))
        self.gridLayout_3.addWidget(self.chkDefaultPersonInEvent, 7, 0, 1, 1)
        self.cmbDefaultPersonInEvent = QtGui.QComboBox(self.tab_2)
        self.cmbDefaultPersonInEvent.setEnabled(False)
        self.cmbDefaultPersonInEvent.setObjectName(_fromUtf8("cmbDefaultPersonInEvent"))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultPersonInEvent.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbDefaultPersonInEvent, 7, 1, 1, 2)
        self.chkExecPersonRequired = QtGui.QCheckBox(self.tab_2)
        self.chkExecPersonRequired.setObjectName(_fromUtf8("chkExecPersonRequired"))
        self.gridLayout_3.addWidget(self.chkExecPersonRequired, 9, 0, 1, 1)
        self.chkDefaultSetPersonInEvent = QtGui.QCheckBox(self.tab_2)
        self.chkDefaultSetPersonInEvent.setObjectName(_fromUtf8("chkDefaultSetPersonInEvent"))
        self.gridLayout_3.addWidget(self.chkDefaultSetPersonInEvent, 5, 0, 1, 1)
        self.lblAddVisitType = QtGui.QLabel(self.tab_2)
        self.lblAddVisitType.setEnabled(False)
        self.lblAddVisitType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAddVisitType.setObjectName(_fromUtf8("lblAddVisitType"))
        self.gridLayout_3.addWidget(self.lblAddVisitType, 17, 1, 1, 1)
        self.cmbAddVisitType = CRBComboBox(self.tab_2)
        self.cmbAddVisitType.setEnabled(False)
        self.cmbAddVisitType.setObjectName(_fromUtf8("cmbAddVisitType"))
        self.cmbAddVisitType.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbAddVisitType, 17, 2, 1, 1)
        self.edtOffice = QtGui.QLineEdit(self.tab_2)
        self.edtOffice.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOffice.sizePolicy().hasHeightForWidth())
        self.edtOffice.setSizePolicy(sizePolicy)
        self.edtOffice.setObjectName(_fromUtf8("edtOffice"))
        self.gridLayout_3.addWidget(self.edtOffice, 15, 1, 1, 2)
        self.chkDefaultDirectionDate = QtGui.QCheckBox(self.tab_2)
        self.chkDefaultDirectionDate.setObjectName(_fromUtf8("chkDefaultDirectionDate"))
        self.gridLayout_3.addWidget(self.chkDefaultDirectionDate, 1, 0, 1, 1)
        self.chkDefaultOrg = QtGui.QCheckBox(self.tab_2)
        self.chkDefaultOrg.setObjectName(_fromUtf8("chkDefaultOrg"))
        self.gridLayout_3.addWidget(self.chkDefaultOrg, 13, 0, 1, 1)
        self.chkDefaultMKB = QtGui.QCheckBox(self.tab_2)
        self.chkDefaultMKB.setObjectName(_fromUtf8("chkDefaultMKB"))
        self.gridLayout_3.addWidget(self.chkDefaultMKB, 10, 0, 1, 1)
        self.chkDefaultStatus = QtGui.QCheckBox(self.tab_2)
        self.chkDefaultStatus.setObjectName(_fromUtf8("chkDefaultStatus"))
        self.gridLayout_3.addWidget(self.chkDefaultStatus, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 19, 0, 1, 3)
        self.cmbDefaultPlannedEndDate = QtGui.QComboBox(self.tab_2)
        self.cmbDefaultPlannedEndDate.setEnabled(False)
        self.cmbDefaultPlannedEndDate.setObjectName(_fromUtf8("cmbDefaultPlannedEndDate"))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultPlannedEndDate.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbDefaultPlannedEndDate, 2, 1, 1, 2)
        self.cmbDefaultEndDate = QtGui.QComboBox(self.tab_2)
        self.cmbDefaultEndDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDefaultEndDate.sizePolicy().hasHeightForWidth())
        self.cmbDefaultEndDate.setSizePolicy(sizePolicy)
        self.cmbDefaultEndDate.setObjectName(_fromUtf8("cmbDefaultEndDate"))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.cmbDefaultEndDate.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbDefaultEndDate, 4, 1, 1, 2)
        self.cmbDefaultExecPerson = CPersonComboBoxEx(self.tab_2)
        self.cmbDefaultExecPerson.setEnabled(False)
        self.cmbDefaultExecPerson.setObjectName(_fromUtf8("cmbDefaultExecPerson"))
        self.gridLayout_3.addWidget(self.cmbDefaultExecPerson, 6, 1, 1, 2)
        self.chkDefaultPersonInEditor = QtGui.QCheckBox(self.tab_2)
        self.chkDefaultPersonInEditor.setObjectName(_fromUtf8("chkDefaultPersonInEditor"))
        self.gridLayout_3.addWidget(self.chkDefaultPersonInEditor, 8, 0, 1, 1)
        self.chkDefaultEndDate = QtGui.QCheckBox(self.tab_2)
        self.chkDefaultEndDate.setObjectName(_fromUtf8("chkDefaultEndDate"))
        self.gridLayout_3.addWidget(self.chkDefaultEndDate, 4, 0, 1, 1)
        self.chkDefaultPlannedEndDate = QtGui.QCheckBox(self.tab_2)
        self.chkDefaultPlannedEndDate.setObjectName(_fromUtf8("chkDefaultPlannedEndDate"))
        self.gridLayout_3.addWidget(self.chkDefaultPlannedEndDate, 2, 0, 1, 1)
        self.cmbDefaultOrg = CPolyclinicComboBox(self.tab_2)
        self.cmbDefaultOrg.setEnabled(False)
        self.cmbDefaultOrg.setObjectName(_fromUtf8("cmbDefaultOrg"))
        self.gridLayout_3.addWidget(self.cmbDefaultOrg, 13, 1, 1, 2)
        self.cmbIsMorphologyRequired = QtGui.QComboBox(self.tab_2)
        self.cmbIsMorphologyRequired.setEnabled(False)
        self.cmbIsMorphologyRequired.setObjectName(_fromUtf8("cmbIsMorphologyRequired"))
        self.cmbIsMorphologyRequired.addItem(_fromUtf8(""))
        self.cmbIsMorphologyRequired.addItem(_fromUtf8(""))
        self.cmbIsMorphologyRequired.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbIsMorphologyRequired, 12, 1, 1, 2)
        self.chkOffice = QtGui.QCheckBox(self.tab_2)
        self.chkOffice.setObjectName(_fromUtf8("chkOffice"))
        self.gridLayout_3.addWidget(self.chkOffice, 15, 0, 1, 1)
        self.edtAmount = QtGui.QSpinBox(self.tab_2)
        self.edtAmount.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmount.sizePolicy().hasHeightForWidth())
        self.edtAmount.setSizePolicy(sizePolicy)
        self.edtAmount.setObjectName(_fromUtf8("edtAmount"))
        self.gridLayout_3.addWidget(self.edtAmount, 14, 1, 1, 2)
        self.chkDefaultBegDate = QtGui.QCheckBox(self.tab_2)
        self.chkDefaultBegDate.setEnabled(True)
        self.chkDefaultBegDate.setObjectName(_fromUtf8("chkDefaultBegDate"))
        self.gridLayout_3.addWidget(self.chkDefaultBegDate, 3, 0, 1, 1)
        self.chkAmount = QtGui.QCheckBox(self.tab_2)
        self.chkAmount.setObjectName(_fromUtf8("chkAmount"))
        self.gridLayout_3.addWidget(self.chkAmount, 14, 0, 1, 1)
        self.cmbExecPersonRequired = QtGui.QComboBox(self.tab_2)
        self.cmbExecPersonRequired.setEnabled(False)
        self.cmbExecPersonRequired.setObjectName(_fromUtf8("cmbExecPersonRequired"))
        self.cmbExecPersonRequired.addItem(_fromUtf8(""))
        self.cmbExecPersonRequired.addItem(_fromUtf8(""))
        self.cmbExecPersonRequired.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbExecPersonRequired, 9, 1, 1, 2)
        self.cmbDefaultSetPersonInEvent = QtGui.QComboBox(self.tab_2)
        self.cmbDefaultSetPersonInEvent.setEnabled(False)
        self.cmbDefaultSetPersonInEvent.setObjectName(_fromUtf8("cmbDefaultSetPersonInEvent"))
        self.cmbDefaultSetPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultSetPersonInEvent.addItem(_fromUtf8(""))
        self.cmbDefaultSetPersonInEvent.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbDefaultSetPersonInEvent, 5, 1, 1, 2)
        self.grpPropertiesFields = QtGui.QGroupBox(self.tab_2)
        self.grpPropertiesFields.setFlat(False)
        self.grpPropertiesFields.setCheckable(True)
        self.grpPropertiesFields.setChecked(False)
        self.grpPropertiesFields.setObjectName(_fromUtf8("grpPropertiesFields"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.grpPropertiesFields)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.chkPropertyAssignedVisible = QtGui.QCheckBox(self.grpPropertiesFields)
        self.chkPropertyAssignedVisible.setChecked(True)
        self.chkPropertyAssignedVisible.setObjectName(_fromUtf8("chkPropertyAssignedVisible"))
        self.verticalLayout_2.addWidget(self.chkPropertyAssignedVisible)
        self.chkPropertyUnitVisible = QtGui.QCheckBox(self.grpPropertiesFields)
        self.chkPropertyUnitVisible.setChecked(True)
        self.chkPropertyUnitVisible.setObjectName(_fromUtf8("chkPropertyUnitVisible"))
        self.verticalLayout_2.addWidget(self.chkPropertyUnitVisible)
        self.chkPropertyNormVisible = QtGui.QCheckBox(self.grpPropertiesFields)
        self.chkPropertyNormVisible.setChecked(True)
        self.chkPropertyNormVisible.setObjectName(_fromUtf8("chkPropertyNormVisible"))
        self.verticalLayout_2.addWidget(self.chkPropertyNormVisible)
        self.chkPropertyEvaluationVisible = QtGui.QCheckBox(self.grpPropertiesFields)
        self.chkPropertyEvaluationVisible.setChecked(True)
        self.chkPropertyEvaluationVisible.setObjectName(_fromUtf8("chkPropertyEvaluationVisible"))
        self.verticalLayout_2.addWidget(self.chkPropertyEvaluationVisible)
        self.gridLayout_3.addWidget(self.grpPropertiesFields, 18, 0, 1, 3)
        self.chkMKBRequired = QtGui.QCheckBox(self.tab_2)
        self.chkMKBRequired.setObjectName(_fromUtf8("chkMKBRequired"))
        self.gridLayout_3.addWidget(self.chkMKBRequired, 11, 0, 1, 1)
        self.cmbMKBRequired = QtGui.QComboBox(self.tab_2)
        self.cmbMKBRequired.setEnabled(False)
        self.cmbMKBRequired.setObjectName(_fromUtf8("cmbMKBRequired"))
        self.cmbMKBRequired.addItem(_fromUtf8(""))
        self.cmbMKBRequired.addItem(_fromUtf8(""))
        self.cmbMKBRequired.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbMKBRequired, 11, 1, 1, 2)
        self.chkDefaultStatus.raise_()
        self.cmbDefaultStatus.raise_()
        self.chkDefaultDirectionDate.raise_()
        self.cmbDefaultDirectionDate.raise_()
        self.chkDefaultPlannedEndDate.raise_()
        self.cmbDefaultPlannedEndDate.raise_()
        self.chkDefaultBegDate.raise_()
        self.cmbDefaultBegDate.raise_()
        self.chkDefaultEndDate.raise_()
        self.cmbDefaultEndDate.raise_()
        self.chkDefaultExecPerson.raise_()
        self.cmbDefaultExecPerson.raise_()
        self.chkDefaultPersonInEvent.raise_()
        self.cmbDefaultPersonInEvent.raise_()
        self.chkDefaultPersonInEditor.raise_()
        self.cmbDefaultPersonInEditor.raise_()
        self.chkDefaultMKB.raise_()
        self.cmbDefaultMKB.raise_()
        self.chkIsMorphologyRequired.raise_()
        self.cmbIsMorphologyRequired.raise_()
        self.chkDefaultOrg.raise_()
        self.cmbDefaultOrg.raise_()
        self.chkAmount.raise_()
        self.edtAmount.raise_()
        self.chkOffice.raise_()
        self.edtOffice.raise_()
        self.chkAddVisitGroup.raise_()
        self.chkAddVisit.raise_()
        self.cmbAddVisitScene.raise_()
        self.lblAddVisitType.raise_()
        self.cmbAddVisitType.raise_()
        self.grpPropertiesFields.raise_()
        self.chkExecPersonRequired.raise_()
        self.cmbExecPersonRequired.raise_()
        self.chkDefaultSetPersonInEvent.raise_()
        self.cmbDefaultSetPersonInEvent.raise_()
        self.chkMKBRequired.raise_()
        self.cmbMKBRequired.raise_()
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(GroupActionTypeEditorDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GroupActionTypeEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        self.cmbExecPersonRequired.setCurrentIndex(0)
        self.cmbMKBRequired.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), GroupActionTypeEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), GroupActionTypeEditorDialog.reject)
        QtCore.QObject.connect(self.chkSex, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSex.setEnabled)
        QtCore.QObject.connect(self.chkContext, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtContext.setEnabled)
        QtCore.QObject.connect(self.chkMaxOccursInEvent, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtMaxOccursInEvent.setEnabled)
        QtCore.QObject.connect(self.chkDefaultStatus, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDefaultStatus.setEnabled)
        QtCore.QObject.connect(self.chkDefaultPlannedEndDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDefaultPlannedEndDate.setEnabled)
        QtCore.QObject.connect(self.chkDefaultEndDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDefaultEndDate.setEnabled)
        QtCore.QObject.connect(self.chkDefaultDirectionDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDefaultDirectionDate.setEnabled)
        QtCore.QObject.connect(self.chkDefaultExecPerson, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDefaultExecPerson.setEnabled)
        QtCore.QObject.connect(self.chkDefaultPersonInEvent, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDefaultPersonInEvent.setEnabled)
        QtCore.QObject.connect(self.chkDefaultPersonInEditor, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDefaultPersonInEditor.setEnabled)
        QtCore.QObject.connect(self.chkDefaultMKB, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDefaultMKB.setEnabled)
        QtCore.QObject.connect(self.chkIsMorphologyRequired, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbIsMorphologyRequired.setEnabled)
        QtCore.QObject.connect(self.chkDefaultOrg, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDefaultOrg.setEnabled)
        QtCore.QObject.connect(self.chkAmount, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAmount.setEnabled)
        QtCore.QObject.connect(self.chkOffice, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtOffice.setEnabled)
        QtCore.QObject.connect(self.chkChkShowInForm, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkShowInForm.setEnabled)
        QtCore.QObject.connect(self.chkAssistant, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkHasAssistant.setEnabled)
        QtCore.QObject.connect(self.chkPreferable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkIsPreferable.setEnabled)
        QtCore.QObject.connect(self.chkChkShowTime, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkShowTime.setEnabled)
        QtCore.QObject.connect(self.chkChkRequiredCoordination, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkRequiredCoordination.setEnabled)
        QtCore.QObject.connect(self.chkServiceType, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbServiceType.setEnabled)
        QtCore.QObject.connect(self.chkExposeDateSelector, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbExposeDateSelector.setEnabled)
        QtCore.QObject.connect(self.chkDefaultBegDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDefaultBegDate.setEnabled)
        QtCore.QObject.connect(self.chkActionTypeValidFrom, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegDate.setEnabled)
        QtCore.QObject.connect(self.chkActionTypeValidFrom, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblActionTypeValidTo.setEnabled)
        QtCore.QObject.connect(self.chkActionTypeValidFrom, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.endEndDate.setEnabled)
        QtCore.QObject.connect(self.chkAddVisit, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbAddVisitScene.setEnabled)
        QtCore.QObject.connect(self.chkAddVisit, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbAddVisitType.setEnabled)
        QtCore.QObject.connect(self.chkAddVisitGroup, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkAddVisit.setEnabled)
        QtCore.QObject.connect(self.chkAddVisit, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblAddVisitType.setEnabled)
        QtCore.QObject.connect(self.chkAge, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.horizontalFrame.setEnabled)
        QtCore.QObject.connect(self.chkChkShowBegDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkShowBegDate.setEnabled)
        QtCore.QObject.connect(self.chkChkEditStatus, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkEditStatus.setEnabled)
        QtCore.QObject.connect(self.chkChkEditEndDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkEditEndDate.setEnabled)
        QtCore.QObject.connect(self.chkChkEditExecPers, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkEditExecPers.setEnabled)
        QtCore.QObject.connect(self.chkChkEditNote, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkEditNote.setEnabled)
        QtCore.QObject.connect(self.chkChkDuplication, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkDuplication.setEnabled)
        QtCore.QObject.connect(self.chkChkIgnoreVisibleRights, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkIgnoreVisibleRights.setEnabled)
        QtCore.QObject.connect(self.chkExecPersonRequired, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbExecPersonRequired.setEnabled)
        QtCore.QObject.connect(self.chkDefaultSetPersonInEvent, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDefaultSetPersonInEvent.setEnabled)
        QtCore.QObject.connect(self.chkChkEditBegDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkEditBegDate.setEnabled)
        QtCore.QObject.connect(self.chkNeedAttachFile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbNeedAttachFile.setEnabled)
        QtCore.QObject.connect(self.chkMKBRequired, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbMKBRequired.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(GroupActionTypeEditorDialog)
        GroupActionTypeEditorDialog.setTabOrder(self.edtBegDate, self.endEndDate)
        GroupActionTypeEditorDialog.setTabOrder(self.endEndDate, self.chkPropertyAssignedVisible)
        GroupActionTypeEditorDialog.setTabOrder(self.chkPropertyAssignedVisible, self.chkPropertyUnitVisible)
        GroupActionTypeEditorDialog.setTabOrder(self.chkPropertyUnitVisible, self.chkPropertyNormVisible)
        GroupActionTypeEditorDialog.setTabOrder(self.chkPropertyNormVisible, self.chkPropertyEvaluationVisible)
        GroupActionTypeEditorDialog.setTabOrder(self.chkPropertyEvaluationVisible, self.buttonBox)

    def retranslateUi(self, GroupActionTypeEditorDialog):
        GroupActionTypeEditorDialog.setWindowTitle(_translate("GroupActionTypeEditorDialog", "Dialog", None))
        self.chkShowInForm.setText(_translate("GroupActionTypeEditorDialog", "Разрешается выбор в формах ввода событий", None))
        self.edtMaxOccursInEvent.setToolTip(_translate("GroupActionTypeEditorDialog", "0 - нет ограничения", None))
        self.cmbBegAgeUnit.setItemText(1, _translate("GroupActionTypeEditorDialog", "Д", None))
        self.cmbBegAgeUnit.setItemText(2, _translate("GroupActionTypeEditorDialog", "Н", None))
        self.cmbBegAgeUnit.setItemText(3, _translate("GroupActionTypeEditorDialog", "М", None))
        self.cmbBegAgeUnit.setItemText(4, _translate("GroupActionTypeEditorDialog", "Г", None))
        self.edtBegAgeCount.setInputMask(_translate("GroupActionTypeEditorDialog", "000; ", None))
        self.lblAgeSep.setText(_translate("GroupActionTypeEditorDialog", "по", None))
        self.cmbEndAgeUnit.setItemText(1, _translate("GroupActionTypeEditorDialog", "Д", None))
        self.cmbEndAgeUnit.setItemText(2, _translate("GroupActionTypeEditorDialog", "Н", None))
        self.cmbEndAgeUnit.setItemText(3, _translate("GroupActionTypeEditorDialog", "М", None))
        self.cmbEndAgeUnit.setItemText(4, _translate("GroupActionTypeEditorDialog", "Г", None))
        self.edtEndAgeCount.setInputMask(_translate("GroupActionTypeEditorDialog", "000; ", None))
        self.chkAge.setText(_translate("GroupActionTypeEditorDialog", "Возраст", None))
        self.edtBegDate.setDisplayFormat(_translate("GroupActionTypeEditorDialog", "dd.MM.yyyy", None))
        self.lblActionTypeValidTo.setText(_translate("GroupActionTypeEditorDialog", " по ", None))
        self.endEndDate.setDisplayFormat(_translate("GroupActionTypeEditorDialog", "dd.MM.yyyy", None))
        self.chkSex.setText(_translate("GroupActionTypeEditorDialog", "Пол", None))
        self.chkActionTypeValidFrom.setText(_translate("GroupActionTypeEditorDialog", "Действует", None))
        self.chkContext.setText(_translate("GroupActionTypeEditorDialog", "Контекст печати", None))
        self.chkExposeDateSelector.setText(_translate("GroupActionTypeEditorDialog", "В счёт включать по дате", None))
        self.cmbExposeDateSelector.setItemText(0, _translate("GroupActionTypeEditorDialog", "Окончания мероприятия", None))
        self.cmbExposeDateSelector.setItemText(1, _translate("GroupActionTypeEditorDialog", "Начала мероприятия", None))
        self.cmbExposeDateSelector.setItemText(2, _translate("GroupActionTypeEditorDialog", "Назначения мероприятия", None))
        self.cmbExposeDateSelector.setItemText(3, _translate("GroupActionTypeEditorDialog", "Взятитя биоматериала", None))
        self.chkShowTime.setText(_translate("GroupActionTypeEditorDialog", "Показывать в интерфейсе время назначения/начала/окончания", None))
        self.chkNeedAttachFile.setText(_translate("GroupActionTypeEditorDialog", "Требует прикрепления файла", None))
        self.chkShowBegDate.setText(_translate("GroupActionTypeEditorDialog", "Показывать в интерфейсе дату начала действия", None))
        self.chkIsPreferable.setText(_translate("GroupActionTypeEditorDialog", "Является предпочитаемым(-ой)", None))
        self.cmbSex.setItemText(1, _translate("GroupActionTypeEditorDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("GroupActionTypeEditorDialog", "Ж", None))
        self.chkEditStatus.setText(_translate("GroupActionTypeEditorDialog", "Редактировать состояние", None))
        self.chkServiceType.setText(_translate("GroupActionTypeEditorDialog", "Вид услуги", None))
        self.chkHasAssistant.setText(_translate("GroupActionTypeEditorDialog", "Требуется ввод ассистента", None))
        self.chkRequiredCoordination.setText(_translate("GroupActionTypeEditorDialog", "Требует обязательного согласования", None))
        self.chkMaxOccursInEvent.setText(_translate("GroupActionTypeEditorDialog", "Макс. количество в событии", None))
        self.chkDuplication.setText(_translate("GroupActionTypeEditorDialog", "Разрешить дублирование", None))
        self.chkEditExecPers.setText(_translate("GroupActionTypeEditorDialog", "Редактировать исполнителя", None))
        self.chkEditBegDate.setText(_translate("GroupActionTypeEditorDialog", "Редактировать дату начала", None))
        self.chkEditEndDate.setText(_translate("GroupActionTypeEditorDialog", "Редактировать дату выполнения", None))
        self.chkEditNote.setText(_translate("GroupActionTypeEditorDialog", "Редактировать примечание", None))
        self.cmbNeedAttachFile.setItemText(0, _translate("GroupActionTypeEditorDialog", "не требовать", None))
        self.cmbNeedAttachFile.setItemText(1, _translate("GroupActionTypeEditorDialog", "требовать по Исполнителю", None))
        self.cmbNeedAttachFile.setItemText(2, _translate("GroupActionTypeEditorDialog", "требовать по Назначившему", None))
        self.chkIgnoreVisibleRights.setText(_translate("GroupActionTypeEditorDialog", "Игнорировать права видимости действий из событий", None))
        self.chkEditSetPerson.setText(_translate("GroupActionTypeEditorDialog", "Редактировать назначившего", None))
        self.chkEditOrg.setText(_translate("GroupActionTypeEditorDialog", "Редактировать место выполнения", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("GroupActionTypeEditorDialog", "Основная информация", None))
        self.cmbDefaultBegDate.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultBegDate.setItemText(1, _translate("GroupActionTypeEditorDialog", "Текущая дата", None))
        self.cmbDefaultBegDate.setItemText(2, _translate("GroupActionTypeEditorDialog", "Дата начала события", None))
        self.cmbDefaultBegDate.setItemText(3, _translate("GroupActionTypeEditorDialog", "Дата окончания события", None))
        self.cmbDefaultBegDate.setItemText(4, _translate("GroupActionTypeEditorDialog", "Дата окончания действия", None))
        self.cmbDefaultBegDate.setItemText(5, _translate("GroupActionTypeEditorDialog", "Номерок на работу", None))
        self.chkIsMorphologyRequired.setText(_translate("GroupActionTypeEditorDialog", "Заполнение «морфологии»", None))
        self.chkAddVisit.setText(_translate("GroupActionTypeEditorDialog", "Добавление визита", None))
        self.chkAddVisitGroup.setText(_translate("GroupActionTypeEditorDialog", "Добавлять визит", None))
        self.cmbAddVisitScene.setItemText(0, _translate("GroupActionTypeEditorDialog", "Место", None))
        self.chkDefaultExecPerson.setText(_translate("GroupActionTypeEditorDialog", "Исполнитель по умолчанию", None))
        self.cmbDefaultPersonInEditor.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultPersonInEditor.setItemText(1, _translate("GroupActionTypeEditorDialog", "Не заполняется", None))
        self.cmbDefaultPersonInEditor.setItemText(2, _translate("GroupActionTypeEditorDialog", "Назначивший действие", None))
        self.cmbDefaultPersonInEditor.setItemText(3, _translate("GroupActionTypeEditorDialog", "Ответственный за событие", None))
        self.cmbDefaultPersonInEditor.setItemText(4, _translate("GroupActionTypeEditorDialog", "Пользователь", None))
        self.cmbDefaultPersonInEditor.setItemText(5, _translate("GroupActionTypeEditorDialog", "Пользователь мед.работник", None))
        self.cmbDefaultDirectionDate.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultDirectionDate.setItemText(1, _translate("GroupActionTypeEditorDialog", "Дата начала события", None))
        self.cmbDefaultDirectionDate.setItemText(2, _translate("GroupActionTypeEditorDialog", "Текущая дата", None))
        self.cmbDefaultDirectionDate.setItemText(3, _translate("GroupActionTypeEditorDialog", "Синхронизация по дате выполнения", None))
        self.cmbDefaultMKB.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не используется", None))
        self.cmbDefaultMKB.setItemText(1, _translate("GroupActionTypeEditorDialog", "По заключительному", None))
        self.cmbDefaultMKB.setItemText(2, _translate("GroupActionTypeEditorDialog", "По диагнозу назначившего действие", None))
        self.cmbDefaultMKB.setItemText(3, _translate("GroupActionTypeEditorDialog", "Синхронизировать с заключительным", None))
        self.cmbDefaultMKB.setItemText(4, _translate("GroupActionTypeEditorDialog", "Синхронизировать с диагнозом назначившего действие", None))
        self.cmbDefaultMKB.setItemText(5, _translate("GroupActionTypeEditorDialog", "Вводится непосредственно", None))
        self.cmbDefaultMKB.setItemText(6, _translate("GroupActionTypeEditorDialog", "Синхронизировать с предварительным диагнозом", None))
        self.chkDefaultPersonInEvent.setText(_translate("GroupActionTypeEditorDialog", "Исполнитель в событии", None))
        self.cmbDefaultPersonInEvent.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultPersonInEvent.setItemText(1, _translate("GroupActionTypeEditorDialog", "Не заполняется", None))
        self.cmbDefaultPersonInEvent.setItemText(2, _translate("GroupActionTypeEditorDialog", "Назначивший действие", None))
        self.cmbDefaultPersonInEvent.setItemText(3, _translate("GroupActionTypeEditorDialog", "Ответственный за событие", None))
        self.cmbDefaultPersonInEvent.setItemText(4, _translate("GroupActionTypeEditorDialog", "Пользователь", None))
        self.cmbDefaultPersonInEvent.setItemText(5, _translate("GroupActionTypeEditorDialog", "Пользователь мед.работник", None))
        self.cmbDefaultPersonInEvent.setItemText(6, _translate("GroupActionTypeEditorDialog", "Пользователь завершивший действие", None))
        self.chkExecPersonRequired.setText(_translate("GroupActionTypeEditorDialog", "Контроль исполнителей", None))
        self.chkDefaultSetPersonInEvent.setText(_translate("GroupActionTypeEditorDialog", "Назначивший в событии", None))
        self.lblAddVisitType.setText(_translate("GroupActionTypeEditorDialog", "Тип", None))
        self.cmbAddVisitType.setItemText(0, _translate("GroupActionTypeEditorDialog", "Тип", None))
        self.chkDefaultDirectionDate.setText(_translate("GroupActionTypeEditorDialog", "Дата назначения", None))
        self.chkDefaultOrg.setText(_translate("GroupActionTypeEditorDialog", "Организация по умолчанию", None))
        self.chkDefaultMKB.setText(_translate("GroupActionTypeEditorDialog", "МКБ и морфология по умолчанию", None))
        self.chkDefaultStatus.setText(_translate("GroupActionTypeEditorDialog", "С&остояние", None))
        self.cmbDefaultPlannedEndDate.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultPlannedEndDate.setItemText(1, _translate("GroupActionTypeEditorDialog", "Следующий день от даты назначения", None))
        self.cmbDefaultPlannedEndDate.setItemText(2, _translate("GroupActionTypeEditorDialog", "Следующий рабочий день от даты назначения", None))
        self.cmbDefaultPlannedEndDate.setItemText(3, _translate("GroupActionTypeEditorDialog", "Дата талона на Работу", None))
        self.cmbDefaultPlannedEndDate.setItemText(4, _translate("GroupActionTypeEditorDialog", "Дата начала + количество", None))
        self.cmbDefaultPlannedEndDate.setItemText(5, _translate("GroupActionTypeEditorDialog", "Дата начала + длительность", None))
        self.cmbDefaultEndDate.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultEndDate.setItemText(1, _translate("GroupActionTypeEditorDialog", "Текущая дата", None))
        self.cmbDefaultEndDate.setItemText(2, _translate("GroupActionTypeEditorDialog", "Дата начала события", None))
        self.cmbDefaultEndDate.setItemText(3, _translate("GroupActionTypeEditorDialog", "Дата окончания события", None))
        self.cmbDefaultEndDate.setItemText(4, _translate("GroupActionTypeEditorDialog", "Дата начала действия", None))
        self.cmbDefaultEndDate.setItemText(5, _translate("GroupActionTypeEditorDialog", "Синхронизация по дате начала действия", None))
        self.chkDefaultPersonInEditor.setText(_translate("GroupActionTypeEditorDialog", "Исполнитель в отд.редакторе", None))
        self.chkDefaultEndDate.setText(_translate("GroupActionTypeEditorDialog", "&Дата окончания", None))
        self.chkDefaultPlannedEndDate.setText(_translate("GroupActionTypeEditorDialog", "Планируемая дата выполнения", None))
        self.cmbIsMorphologyRequired.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не проверяется", None))
        self.cmbIsMorphologyRequired.setItemText(1, _translate("GroupActionTypeEditorDialog", "Мягкий контроль", None))
        self.cmbIsMorphologyRequired.setItemText(2, _translate("GroupActionTypeEditorDialog", "Жесткий контроль", None))
        self.chkOffice.setText(_translate("GroupActionTypeEditorDialog", "Кабине&т", None))
        self.chkDefaultBegDate.setText(_translate("GroupActionTypeEditorDialog", "Дата начала", None))
        self.chkAmount.setText(_translate("GroupActionTypeEditorDialog", "Ко&личество", None))
        self.cmbExecPersonRequired.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не проверяется", None))
        self.cmbExecPersonRequired.setItemText(1, _translate("GroupActionTypeEditorDialog", "Мягкий контроль", None))
        self.cmbExecPersonRequired.setItemText(2, _translate("GroupActionTypeEditorDialog", "Жёсткий контроль", None))
        self.cmbDefaultSetPersonInEvent.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не определено", None))
        self.cmbDefaultSetPersonInEvent.setItemText(1, _translate("GroupActionTypeEditorDialog", "Ответственный за событие", None))
        self.cmbDefaultSetPersonInEvent.setItemText(2, _translate("GroupActionTypeEditorDialog", "Исполнитель действия", None))
        self.grpPropertiesFields.setTitle(_translate("GroupActionTypeEditorDialog", "Настройка визуализации колонок свойств в редакторе Действия", None))
        self.chkPropertyAssignedVisible.setText(_translate("GroupActionTypeEditorDialog", "Колонка «назначено»", None))
        self.chkPropertyUnitVisible.setText(_translate("GroupActionTypeEditorDialog", "Колонка «единица измерения»", None))
        self.chkPropertyNormVisible.setText(_translate("GroupActionTypeEditorDialog", "Колонка «норма»", None))
        self.chkPropertyEvaluationVisible.setText(_translate("GroupActionTypeEditorDialog", "Колонка «оценка»", None))
        self.chkMKBRequired.setText(_translate("GroupActionTypeEditorDialog", "Требовать заполнение МКБ", None))
        self.cmbMKBRequired.setItemText(0, _translate("GroupActionTypeEditorDialog", "Не проверяется", None))
        self.cmbMKBRequired.setItemText(1, _translate("GroupActionTypeEditorDialog", "Мягкий контроль", None))
        self.cmbMKBRequired.setItemText(2, _translate("GroupActionTypeEditorDialog", "Жёсткий контроль", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("GroupActionTypeEditorDialog", "Умолчания", None))

from Events.ActionServiceType import CActionServiceTypeComboBox
from Events.ActionStatus import CActionStatusComboBox
from Orgs.OrgComboBox import CPolyclinicComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
