# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client\RefBooks\ActionPropertyTemplate\ActionPropertyTemplateEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActionPropertyTemplateEditorDialog(object):
    def setupUi(self, ActionPropertyTemplateEditorDialog):
        ActionPropertyTemplateEditorDialog.setObjectName(_fromUtf8("ActionPropertyTemplateEditorDialog"))
        ActionPropertyTemplateEditorDialog.resize(484, 298)
        ActionPropertyTemplateEditorDialog.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(ActionPropertyTemplateEditorDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.cmbEndAgeUnit = QtGui.QComboBox(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbEndAgeUnit.setObjectName(_fromUtf8("cmbEndAgeUnit"))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbEndAgeUnit, 7, 4, 1, 2)
        spacerItem = QtGui.QSpacerItem(73, 231, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem, 10, 0, 1, 1)
        self.lblGroup = QtGui.QLabel(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGroup.sizePolicy().hasHeightForWidth())
        self.lblGroup.setSizePolicy(sizePolicy)
        self.lblGroup.setObjectName(_fromUtf8("lblGroup"))
        self.gridlayout.addWidget(self.lblGroup, 3, 0, 1, 1)
        self.cmbGroup = CActionPropertyTemplateComboBox(ActionPropertyTemplateEditorDialog)
        self.cmbGroup.setObjectName(_fromUtf8("cmbGroup"))
        self.gridlayout.addWidget(self.cmbGroup, 3, 1, 1, 7)
        self.lblFederalCode = QtGui.QLabel(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFederalCode.sizePolicy().hasHeightForWidth())
        self.lblFederalCode.setSizePolicy(sizePolicy)
        self.lblFederalCode.setObjectName(_fromUtf8("lblFederalCode"))
        self.gridlayout.addWidget(self.lblFederalCode, 1, 0, 1, 1)
        self.lblAgeSep = QtGui.QLabel(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAgeSep.sizePolicy().hasHeightForWidth())
        self.lblAgeSep.setSizePolicy(sizePolicy)
        self.lblAgeSep.setObjectName(_fromUtf8("lblAgeSep"))
        self.gridlayout.addWidget(self.lblAgeSep, 7, 3, 1, 1)
        self.lblService = QtGui.QLabel(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblService.sizePolicy().hasHeightForWidth())
        self.lblService.setSizePolicy(sizePolicy)
        self.lblService.setObjectName(_fromUtf8("lblService"))
        self.gridlayout.addWidget(self.lblService, 8, 0, 1, 1)
        self.cmbService = CRBComboBox(ActionPropertyTemplateEditorDialog)
        self.cmbService.setObjectName(_fromUtf8("cmbService"))
        self.gridlayout.addWidget(self.cmbService, 8, 1, 1, 7)
        self.lblCode = QtGui.QLabel(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridlayout.addWidget(self.lblCode, 0, 0, 1, 1)
        self.lblAbbrev = QtGui.QLabel(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAbbrev.sizePolicy().hasHeightForWidth())
        self.lblAbbrev.setSizePolicy(sizePolicy)
        self.lblAbbrev.setObjectName(_fromUtf8("lblAbbrev"))
        self.gridlayout.addWidget(self.lblAbbrev, 5, 0, 1, 1)
        self.lblRegionalCode = QtGui.QLabel(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRegionalCode.sizePolicy().hasHeightForWidth())
        self.lblRegionalCode.setSizePolicy(sizePolicy)
        self.lblRegionalCode.setObjectName(_fromUtf8("lblRegionalCode"))
        self.gridlayout.addWidget(self.lblRegionalCode, 2, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(ActionPropertyTemplateEditorDialog)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridlayout.addWidget(self.edtCode, 0, 1, 1, 7)
        self.edtBegAgeCount = QtGui.QLineEdit(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAgeCount.sizePolicy().hasHeightForWidth())
        self.edtBegAgeCount.setSizePolicy(sizePolicy)
        self.edtBegAgeCount.setMaxLength(3)
        self.edtBegAgeCount.setObjectName(_fromUtf8("edtBegAgeCount"))
        self.gridlayout.addWidget(self.edtBegAgeCount, 7, 2, 1, 1)
        self.cmbBegAgeUnit = QtGui.QComboBox(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbBegAgeUnit.setObjectName(_fromUtf8("cmbBegAgeUnit"))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbBegAgeUnit, 7, 1, 1, 1)
        self.edtFederalCode = QtGui.QLineEdit(ActionPropertyTemplateEditorDialog)
        self.edtFederalCode.setObjectName(_fromUtf8("edtFederalCode"))
        self.gridlayout.addWidget(self.edtFederalCode, 1, 1, 1, 7)
        self.lblSex = QtGui.QLabel(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSex.sizePolicy().hasHeightForWidth())
        self.lblSex.setSizePolicy(sizePolicy)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridlayout.addWidget(self.lblSex, 6, 0, 1, 1)
        self.lblAge = QtGui.QLabel(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAge.sizePolicy().hasHeightForWidth())
        self.lblAge.setSizePolicy(sizePolicy)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridlayout.addWidget(self.lblAge, 7, 0, 1, 1)
        self.lblName = QtGui.QLabel(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridlayout.addWidget(self.lblName, 4, 0, 1, 1)
        self.edtEndAgeCount = QtGui.QLineEdit(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAgeCount.sizePolicy().hasHeightForWidth())
        self.edtEndAgeCount.setSizePolicy(sizePolicy)
        self.edtEndAgeCount.setMaxLength(3)
        self.edtEndAgeCount.setObjectName(_fromUtf8("edtEndAgeCount"))
        self.gridlayout.addWidget(self.edtEndAgeCount, 7, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(71, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 7, 7, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ActionPropertyTemplateEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 11, 0, 1, 8)
        self.edtAbbrev = QtGui.QLineEdit(ActionPropertyTemplateEditorDialog)
        self.edtAbbrev.setMinimumSize(QtCore.QSize(200, 0))
        self.edtAbbrev.setObjectName(_fromUtf8("edtAbbrev"))
        self.gridlayout.addWidget(self.edtAbbrev, 5, 1, 1, 7)
        self.edtRegionalCode = QtGui.QLineEdit(ActionPropertyTemplateEditorDialog)
        self.edtRegionalCode.setObjectName(_fromUtf8("edtRegionalCode"))
        self.gridlayout.addWidget(self.edtRegionalCode, 2, 1, 1, 7)
        self.cmbSex = QtGui.QComboBox(ActionPropertyTemplateEditorDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbSex, 6, 1, 1, 7)
        self.edtName = QtGui.QLineEdit(ActionPropertyTemplateEditorDialog)
        self.edtName.setMinimumSize(QtCore.QSize(200, 0))
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridlayout.addWidget(self.edtName, 4, 1, 1, 7)
        self.chkCalcParamDoseNomenclatureExpense = QtGui.QCheckBox(ActionPropertyTemplateEditorDialog)
        self.chkCalcParamDoseNomenclatureExpense.setObjectName(_fromUtf8("chkCalcParamDoseNomenclatureExpense"))
        self.gridlayout.addWidget(self.chkCalcParamDoseNomenclatureExpense, 9, 1, 1, 6)
        self.lblGroup.setBuddy(self.cmbGroup)
        self.lblFederalCode.setBuddy(self.edtFederalCode)
        self.lblAgeSep.setBuddy(self.cmbEndAgeUnit)
        self.lblService.setBuddy(self.cmbService)
        self.lblCode.setBuddy(self.edtCode)
        self.lblAbbrev.setBuddy(self.edtAbbrev)
        self.lblRegionalCode.setBuddy(self.edtRegionalCode)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblAge.setBuddy(self.cmbBegAgeUnit)
        self.lblName.setBuddy(self.edtName)

        self.retranslateUi(ActionPropertyTemplateEditorDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ActionPropertyTemplateEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ActionPropertyTemplateEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ActionPropertyTemplateEditorDialog)
        ActionPropertyTemplateEditorDialog.setTabOrder(self.edtCode, self.edtFederalCode)
        ActionPropertyTemplateEditorDialog.setTabOrder(self.edtFederalCode, self.edtRegionalCode)
        ActionPropertyTemplateEditorDialog.setTabOrder(self.edtRegionalCode, self.cmbGroup)
        ActionPropertyTemplateEditorDialog.setTabOrder(self.cmbGroup, self.edtName)
        ActionPropertyTemplateEditorDialog.setTabOrder(self.edtName, self.edtAbbrev)
        ActionPropertyTemplateEditorDialog.setTabOrder(self.edtAbbrev, self.cmbSex)
        ActionPropertyTemplateEditorDialog.setTabOrder(self.cmbSex, self.cmbBegAgeUnit)
        ActionPropertyTemplateEditorDialog.setTabOrder(self.cmbBegAgeUnit, self.edtBegAgeCount)
        ActionPropertyTemplateEditorDialog.setTabOrder(self.edtBegAgeCount, self.cmbEndAgeUnit)
        ActionPropertyTemplateEditorDialog.setTabOrder(self.cmbEndAgeUnit, self.edtEndAgeCount)
        ActionPropertyTemplateEditorDialog.setTabOrder(self.edtEndAgeCount, self.cmbService)
        ActionPropertyTemplateEditorDialog.setTabOrder(self.cmbService, self.chkCalcParamDoseNomenclatureExpense)
        ActionPropertyTemplateEditorDialog.setTabOrder(self.chkCalcParamDoseNomenclatureExpense, self.buttonBox)

    def retranslateUi(self, ActionPropertyTemplateEditorDialog):
        ActionPropertyTemplateEditorDialog.setWindowTitle(_translate("ActionPropertyTemplateEditorDialog", "ChangeMe!", None))
        self.cmbEndAgeUnit.setItemText(1, _translate("ActionPropertyTemplateEditorDialog", "Д", None))
        self.cmbEndAgeUnit.setItemText(2, _translate("ActionPropertyTemplateEditorDialog", "Н", None))
        self.cmbEndAgeUnit.setItemText(3, _translate("ActionPropertyTemplateEditorDialog", "М", None))
        self.cmbEndAgeUnit.setItemText(4, _translate("ActionPropertyTemplateEditorDialog", "Г", None))
        self.lblGroup.setText(_translate("ActionPropertyTemplateEditorDialog", "&Группа", None))
        self.lblFederalCode.setText(_translate("ActionPropertyTemplateEditorDialog", "&Федеральный код", None))
        self.lblAgeSep.setText(_translate("ActionPropertyTemplateEditorDialog", "по", None))
        self.lblService.setText(_translate("ActionPropertyTemplateEditorDialog", "&Услуга", None))
        self.lblCode.setText(_translate("ActionPropertyTemplateEditorDialog", "&Код", None))
        self.lblAbbrev.setText(_translate("ActionPropertyTemplateEditorDialog", "&Сокращение", None))
        self.lblRegionalCode.setText(_translate("ActionPropertyTemplateEditorDialog", "&Региональный код", None))
        self.edtBegAgeCount.setInputMask(_translate("ActionPropertyTemplateEditorDialog", "000; ", None))
        self.cmbBegAgeUnit.setItemText(1, _translate("ActionPropertyTemplateEditorDialog", "Д", None))
        self.cmbBegAgeUnit.setItemText(2, _translate("ActionPropertyTemplateEditorDialog", "Н", None))
        self.cmbBegAgeUnit.setItemText(3, _translate("ActionPropertyTemplateEditorDialog", "М", None))
        self.cmbBegAgeUnit.setItemText(4, _translate("ActionPropertyTemplateEditorDialog", "Г", None))
        self.lblSex.setText(_translate("ActionPropertyTemplateEditorDialog", "&Пол", None))
        self.lblAge.setText(_translate("ActionPropertyTemplateEditorDialog", "&Возраст", None))
        self.lblName.setText(_translate("ActionPropertyTemplateEditorDialog", "На&именование", None))
        self.edtEndAgeCount.setInputMask(_translate("ActionPropertyTemplateEditorDialog", "000; ", None))
        self.cmbSex.setItemText(1, _translate("ActionPropertyTemplateEditorDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ActionPropertyTemplateEditorDialog", "Ж", None))
        self.chkCalcParamDoseNomenclatureExpense.setText(_translate("ActionPropertyTemplateEditorDialog", "Является параметром расчета дозы при назначении ЛС", None))

from Events.ActionPropertyTemplateComboBox import CActionPropertyTemplateComboBox
from library.crbcombobox import CRBComboBox
