# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PROJECTS\samson\UP_s11\client_test\Timeline\TimelineDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TimelineDialog(object):
    def setupUi(self, TimelineDialog):
        TimelineDialog.setObjectName(_fromUtf8("TimelineDialog"))
        TimelineDialog.resize(740, 816)
        self.gridLayout_3 = QtGui.QGridLayout(TimelineDialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter = QtGui.QSplitter(TimelineDialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.calendar = CCalendarWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendar.sizePolicy().hasHeightForWidth())
        self.calendar.setSizePolicy(sizePolicy)
        self.calendar.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendar.setGridVisible(False)
        self.calendar.setObjectName(_fromUtf8("calendar"))
        self.treeOrgStructure = QtGui.QTreeView(self.splitter)
        self.treeOrgStructure.setObjectName(_fromUtf8("treeOrgStructure"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.edtFilterPersonnel = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.edtFilterPersonnel.setObjectName(_fromUtf8("edtFilterPersonnel"))
        self.verticalLayout.addWidget(self.edtFilterPersonnel)
        self.tblPersonnel = CTableView(self.verticalLayoutWidget)
        self.tblPersonnel.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblPersonnel.setObjectName(_fromUtf8("tblPersonnel"))
        self.verticalLayout.addWidget(self.tblPersonnel)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.widget = QtGui.QWidget(TimelineDialog)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnClose = QtGui.QPushButton(self.widget)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.gridLayout.addWidget(self.btnClose, 2, 3, 1, 1)
        self.btnAbsence = QtGui.QPushButton(self.widget)
        self.btnAbsence.setObjectName(_fromUtf8("btnAbsence"))
        self.gridLayout.addWidget(self.btnAbsence, 4, 2, 1, 1)
        self.tblTimeTable = CTimeTableView(self.widget)
        self.tblTimeTable.setObjectName(_fromUtf8("tblTimeTable"))
        self.gridLayout.addWidget(self.tblTimeTable, 0, 0, 2, 3)
        self.btnFill = QtGui.QPushButton(self.widget)
        self.btnFill.setObjectName(_fromUtf8("btnFill"))
        self.gridLayout.addWidget(self.btnFill, 2, 0, 1, 1)
        self.btnFillTime = QtGui.QPushButton(self.widget)
        self.btnFillTime.setObjectName(_fromUtf8("btnFillTime"))
        self.gridLayout.addWidget(self.btnFillTime, 3, 2, 1, 1)
        self.btnPrint = QtGui.QPushButton(self.widget)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.gridLayout.addWidget(self.btnPrint, 2, 1, 1, 1)
        self.btnFillVisitsCount = QtGui.QPushButton(self.widget)
        self.btnFillVisitsCount.setObjectName(_fromUtf8("btnFillVisitsCount"))
        self.gridLayout.addWidget(self.btnFillVisitsCount, 2, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblAmbLoad = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAmbLoad.sizePolicy().hasHeightForWidth())
        self.lblAmbLoad.setSizePolicy(sizePolicy)
        self.lblAmbLoad.setMinimumSize(QtCore.QSize(0, 10))
        self.lblAmbLoad.setObjectName(_fromUtf8("lblAmbLoad"))
        self.gridLayout_2.addWidget(self.lblAmbLoad, 15, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 37, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 25, 0, 1, 1)
        self.lblServLoadValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblServLoadValue.sizePolicy().hasHeightForWidth())
        self.lblServLoadValue.setSizePolicy(sizePolicy)
        self.lblServLoadValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblServLoadValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblServLoadValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblServLoadValue.setObjectName(_fromUtf8("lblServLoadValue"))
        self.gridLayout_2.addWidget(self.lblServLoadValue, 14, 1, 1, 1)
        self.lblAmbDays = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAmbDays.sizePolicy().hasHeightForWidth())
        self.lblAmbDays.setSizePolicy(sizePolicy)
        self.lblAmbDays.setMinimumSize(QtCore.QSize(0, 10))
        self.lblAmbDays.setObjectName(_fromUtf8("lblAmbDays"))
        self.gridLayout_2.addWidget(self.lblAmbDays, 2, 0, 1, 1)
        self.lblAmbDaysValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAmbDaysValue.sizePolicy().hasHeightForWidth())
        self.lblAmbDaysValue.setSizePolicy(sizePolicy)
        self.lblAmbDaysValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblAmbDaysValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblAmbDaysValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblAmbDaysValue.setObjectName(_fromUtf8("lblAmbDaysValue"))
        self.gridLayout_2.addWidget(self.lblAmbDaysValue, 2, 1, 1, 1)
        self.lblHomeHourLoad = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHomeHourLoad.sizePolicy().hasHeightForWidth())
        self.lblHomeHourLoad.setSizePolicy(sizePolicy)
        self.lblHomeHourLoad.setMinimumSize(QtCore.QSize(0, 10))
        self.lblHomeHourLoad.setObjectName(_fromUtf8("lblHomeHourLoad"))
        self.gridLayout_2.addWidget(self.lblHomeHourLoad, 11, 0, 1, 1)
        self.lblHomeHourLoadValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHomeHourLoadValue.sizePolicy().hasHeightForWidth())
        self.lblHomeHourLoadValue.setSizePolicy(sizePolicy)
        self.lblHomeHourLoadValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblHomeHourLoadValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblHomeHourLoadValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblHomeHourLoadValue.setObjectName(_fromUtf8("lblHomeHourLoadValue"))
        self.gridLayout_2.addWidget(self.lblHomeHourLoadValue, 11, 1, 1, 1)
        self.lblServExecValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblServExecValue.sizePolicy().hasHeightForWidth())
        self.lblServExecValue.setSizePolicy(sizePolicy)
        self.lblServExecValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblServExecValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblServExecValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblServExecValue.setObjectName(_fromUtf8("lblServExecValue"))
        self.gridLayout_2.addWidget(self.lblServExecValue, 19, 1, 1, 1)
        self.lblLoad = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLoad.sizePolicy().hasHeightForWidth())
        self.lblLoad.setSizePolicy(sizePolicy)
        self.lblLoad.setMinimumSize(QtCore.QSize(0, 10))
        self.lblLoad.setObjectName(_fromUtf8("lblLoad"))
        self.gridLayout_2.addWidget(self.lblLoad, 13, 0, 1, 1)
        self.lblAbsenceDays = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAbsenceDays.sizePolicy().hasHeightForWidth())
        self.lblAbsenceDays.setSizePolicy(sizePolicy)
        self.lblAbsenceDays.setMinimumSize(QtCore.QSize(0, 10))
        self.lblAbsenceDays.setObjectName(_fromUtf8("lblAbsenceDays"))
        self.gridLayout_2.addWidget(self.lblAbsenceDays, 1, 0, 1, 1)
        self.lblExpDays = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExpDays.sizePolicy().hasHeightForWidth())
        self.lblExpDays.setSizePolicy(sizePolicy)
        self.lblExpDays.setMinimumSize(QtCore.QSize(0, 10))
        self.lblExpDays.setObjectName(_fromUtf8("lblExpDays"))
        self.gridLayout_2.addWidget(self.lblExpDays, 4, 0, 1, 1)
        self.lblHourLoad = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHourLoad.sizePolicy().hasHeightForWidth())
        self.lblHourLoad.setSizePolicy(sizePolicy)
        self.lblHourLoad.setMinimumSize(QtCore.QSize(0, 10))
        self.lblHourLoad.setObjectName(_fromUtf8("lblHourLoad"))
        self.gridLayout_2.addWidget(self.lblHourLoad, 8, 0, 1, 1)
        self.lblServHourLoad = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblServHourLoad.sizePolicy().hasHeightForWidth())
        self.lblServHourLoad.setSizePolicy(sizePolicy)
        self.lblServHourLoad.setMinimumSize(QtCore.QSize(0, 10))
        self.lblServHourLoad.setObjectName(_fromUtf8("lblServHourLoad"))
        self.gridLayout_2.addWidget(self.lblServHourLoad, 9, 0, 1, 1)
        self.lblAmbHourLoadValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAmbHourLoadValue.sizePolicy().hasHeightForWidth())
        self.lblAmbHourLoadValue.setSizePolicy(sizePolicy)
        self.lblAmbHourLoadValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblAmbHourLoadValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblAmbHourLoadValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblAmbHourLoadValue.setObjectName(_fromUtf8("lblAmbHourLoadValue"))
        self.gridLayout_2.addWidget(self.lblAmbHourLoadValue, 10, 1, 1, 1)
        self.lblAmbLoadValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAmbLoadValue.sizePolicy().hasHeightForWidth())
        self.lblAmbLoadValue.setSizePolicy(sizePolicy)
        self.lblAmbLoadValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblAmbLoadValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblAmbLoadValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblAmbLoadValue.setObjectName(_fromUtf8("lblAmbLoadValue"))
        self.gridLayout_2.addWidget(self.lblAmbLoadValue, 15, 1, 1, 1)
        self.lblHomeDays = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHomeDays.sizePolicy().hasHeightForWidth())
        self.lblHomeDays.setSizePolicy(sizePolicy)
        self.lblHomeDays.setMinimumSize(QtCore.QSize(0, 10))
        self.lblHomeDays.setObjectName(_fromUtf8("lblHomeDays"))
        self.gridLayout_2.addWidget(self.lblHomeDays, 3, 0, 1, 1)
        self.lblHourLoadValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHourLoadValue.sizePolicy().hasHeightForWidth())
        self.lblHourLoadValue.setSizePolicy(sizePolicy)
        self.lblHourLoadValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblHourLoadValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblHourLoadValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblHourLoadValue.setObjectName(_fromUtf8("lblHourLoadValue"))
        self.gridLayout_2.addWidget(self.lblHourLoadValue, 8, 1, 1, 1)
        self.lblExpDaysValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExpDaysValue.sizePolicy().hasHeightForWidth())
        self.lblExpDaysValue.setSizePolicy(sizePolicy)
        self.lblExpDaysValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblExpDaysValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblExpDaysValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblExpDaysValue.setObjectName(_fromUtf8("lblExpDaysValue"))
        self.gridLayout_2.addWidget(self.lblExpDaysValue, 4, 1, 1, 1)
        self.lblExpHourLoadValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExpHourLoadValue.sizePolicy().hasHeightForWidth())
        self.lblExpHourLoadValue.setSizePolicy(sizePolicy)
        self.lblExpHourLoadValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblExpHourLoadValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblExpHourLoadValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblExpHourLoadValue.setObjectName(_fromUtf8("lblExpHourLoadValue"))
        self.gridLayout_2.addWidget(self.lblExpHourLoadValue, 12, 1, 1, 1)
        self.lblExpExecValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExpExecValue.sizePolicy().hasHeightForWidth())
        self.lblExpExecValue.setSizePolicy(sizePolicy)
        self.lblExpExecValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblExpExecValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblExpExecValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblExpExecValue.setObjectName(_fromUtf8("lblExpExecValue"))
        self.gridLayout_2.addWidget(self.lblExpExecValue, 22, 1, 1, 1)
        self.lblServHourLoadValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblServHourLoadValue.sizePolicy().hasHeightForWidth())
        self.lblServHourLoadValue.setSizePolicy(sizePolicy)
        self.lblServHourLoadValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblServHourLoadValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblServHourLoadValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblServHourLoadValue.setObjectName(_fromUtf8("lblServHourLoadValue"))
        self.gridLayout_2.addWidget(self.lblServHourLoadValue, 9, 1, 1, 1)
        self.lblAmbExecValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAmbExecValue.sizePolicy().hasHeightForWidth())
        self.lblAmbExecValue.setSizePolicy(sizePolicy)
        self.lblAmbExecValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblAmbExecValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblAmbExecValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblAmbExecValue.setObjectName(_fromUtf8("lblAmbExecValue"))
        self.gridLayout_2.addWidget(self.lblAmbExecValue, 20, 1, 1, 1)
        self.lblHomeExec = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHomeExec.sizePolicy().hasHeightForWidth())
        self.lblHomeExec.setSizePolicy(sizePolicy)
        self.lblHomeExec.setMinimumSize(QtCore.QSize(0, 10))
        self.lblHomeExec.setObjectName(_fromUtf8("lblHomeExec"))
        self.gridLayout_2.addWidget(self.lblHomeExec, 21, 0, 1, 1)
        self.lblLoadValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLoadValue.sizePolicy().hasHeightForWidth())
        self.lblLoadValue.setSizePolicy(sizePolicy)
        self.lblLoadValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblLoadValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblLoadValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblLoadValue.setObjectName(_fromUtf8("lblLoadValue"))
        self.gridLayout_2.addWidget(self.lblLoadValue, 13, 1, 1, 1)
        self.lblExecValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExecValue.sizePolicy().hasHeightForWidth())
        self.lblExecValue.setSizePolicy(sizePolicy)
        self.lblExecValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblExecValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblExecValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblExecValue.setObjectName(_fromUtf8("lblExecValue"))
        self.gridLayout_2.addWidget(self.lblExecValue, 18, 1, 1, 1)
        self.lblServExec = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblServExec.sizePolicy().hasHeightForWidth())
        self.lblServExec.setSizePolicy(sizePolicy)
        self.lblServExec.setMinimumSize(QtCore.QSize(0, 10))
        self.lblServExec.setObjectName(_fromUtf8("lblServExec"))
        self.gridLayout_2.addWidget(self.lblServExec, 19, 0, 1, 1)
        self.lblServLoad = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblServLoad.sizePolicy().hasHeightForWidth())
        self.lblServLoad.setSizePolicy(sizePolicy)
        self.lblServLoad.setMinimumSize(QtCore.QSize(0, 10))
        self.lblServLoad.setObjectName(_fromUtf8("lblServLoad"))
        self.gridLayout_2.addWidget(self.lblServLoad, 14, 0, 1, 1)
        self.lblExpHourLoad = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExpHourLoad.sizePolicy().hasHeightForWidth())
        self.lblExpHourLoad.setSizePolicy(sizePolicy)
        self.lblExpHourLoad.setMinimumSize(QtCore.QSize(0, 10))
        self.lblExpHourLoad.setObjectName(_fromUtf8("lblExpHourLoad"))
        self.gridLayout_2.addWidget(self.lblExpHourLoad, 12, 0, 1, 1)
        self.lblAmbExec = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAmbExec.sizePolicy().hasHeightForWidth())
        self.lblAmbExec.setSizePolicy(sizePolicy)
        self.lblAmbExec.setMinimumSize(QtCore.QSize(0, 10))
        self.lblAmbExec.setObjectName(_fromUtf8("lblAmbExec"))
        self.gridLayout_2.addWidget(self.lblAmbExec, 20, 0, 1, 1)
        self.lblNumDaysValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNumDaysValue.sizePolicy().hasHeightForWidth())
        self.lblNumDaysValue.setSizePolicy(sizePolicy)
        self.lblNumDaysValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblNumDaysValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblNumDaysValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblNumDaysValue.setObjectName(_fromUtf8("lblNumDaysValue"))
        self.gridLayout_2.addWidget(self.lblNumDaysValue, 0, 1, 1, 1)
        self.lblNumDays = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNumDays.sizePolicy().hasHeightForWidth())
        self.lblNumDays.setSizePolicy(sizePolicy)
        self.lblNumDays.setMinimumSize(QtCore.QSize(0, 10))
        self.lblNumDays.setObjectName(_fromUtf8("lblNumDays"))
        self.gridLayout_2.addWidget(self.lblNumDays, 0, 0, 1, 1)
        self.lblHomeLoad = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHomeLoad.sizePolicy().hasHeightForWidth())
        self.lblHomeLoad.setSizePolicy(sizePolicy)
        self.lblHomeLoad.setMinimumSize(QtCore.QSize(0, 10))
        self.lblHomeLoad.setObjectName(_fromUtf8("lblHomeLoad"))
        self.gridLayout_2.addWidget(self.lblHomeLoad, 16, 0, 1, 1)
        self.lblHomeLoadValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHomeLoadValue.sizePolicy().hasHeightForWidth())
        self.lblHomeLoadValue.setSizePolicy(sizePolicy)
        self.lblHomeLoadValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblHomeLoadValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblHomeLoadValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblHomeLoadValue.setObjectName(_fromUtf8("lblHomeLoadValue"))
        self.gridLayout_2.addWidget(self.lblHomeLoadValue, 16, 1, 1, 1)
        self.lblHomeDaysValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHomeDaysValue.sizePolicy().hasHeightForWidth())
        self.lblHomeDaysValue.setSizePolicy(sizePolicy)
        self.lblHomeDaysValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblHomeDaysValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblHomeDaysValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblHomeDaysValue.setObjectName(_fromUtf8("lblHomeDaysValue"))
        self.gridLayout_2.addWidget(self.lblHomeDaysValue, 3, 1, 1, 1)
        self.lblHomeExecValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHomeExecValue.sizePolicy().hasHeightForWidth())
        self.lblHomeExecValue.setSizePolicy(sizePolicy)
        self.lblHomeExecValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblHomeExecValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblHomeExecValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblHomeExecValue.setObjectName(_fromUtf8("lblHomeExecValue"))
        self.gridLayout_2.addWidget(self.lblHomeExecValue, 21, 1, 1, 1)
        self.lblExpExec = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExpExec.sizePolicy().hasHeightForWidth())
        self.lblExpExec.setSizePolicy(sizePolicy)
        self.lblExpExec.setMinimumSize(QtCore.QSize(0, 10))
        self.lblExpExec.setObjectName(_fromUtf8("lblExpExec"))
        self.gridLayout_2.addWidget(self.lblExpExec, 22, 0, 1, 1)
        self.lblAbsenceDaysValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAbsenceDaysValue.sizePolicy().hasHeightForWidth())
        self.lblAbsenceDaysValue.setSizePolicy(sizePolicy)
        self.lblAbsenceDaysValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblAbsenceDaysValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblAbsenceDaysValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblAbsenceDaysValue.setObjectName(_fromUtf8("lblAbsenceDaysValue"))
        self.gridLayout_2.addWidget(self.lblAbsenceDaysValue, 1, 1, 1, 1)
        self.lblExpLoad = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExpLoad.sizePolicy().hasHeightForWidth())
        self.lblExpLoad.setSizePolicy(sizePolicy)
        self.lblExpLoad.setMinimumSize(QtCore.QSize(0, 10))
        self.lblExpLoad.setObjectName(_fromUtf8("lblExpLoad"))
        self.gridLayout_2.addWidget(self.lblExpLoad, 17, 0, 1, 1)
        self.lblExpLoadValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExpLoadValue.sizePolicy().hasHeightForWidth())
        self.lblExpLoadValue.setSizePolicy(sizePolicy)
        self.lblExpLoadValue.setMinimumSize(QtCore.QSize(0, 14))
        self.lblExpLoadValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblExpLoadValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblExpLoadValue.setObjectName(_fromUtf8("lblExpLoadValue"))
        self.gridLayout_2.addWidget(self.lblExpLoadValue, 17, 1, 1, 1)
        self.lblExec = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExec.sizePolicy().hasHeightForWidth())
        self.lblExec.setSizePolicy(sizePolicy)
        self.lblExec.setMinimumSize(QtCore.QSize(0, 10))
        self.lblExec.setObjectName(_fromUtf8("lblExec"))
        self.gridLayout_2.addWidget(self.lblExec, 18, 0, 1, 1)
        self.lblAmbHourLoad = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAmbHourLoad.sizePolicy().hasHeightForWidth())
        self.lblAmbHourLoad.setSizePolicy(sizePolicy)
        self.lblAmbHourLoad.setMinimumSize(QtCore.QSize(0, 10))
        self.lblAmbHourLoad.setObjectName(_fromUtf8("lblAmbHourLoad"))
        self.gridLayout_2.addWidget(self.lblAmbHourLoad, 10, 0, 1, 1)
        self.lblAmbPlan = QtGui.QLabel(self.groupBox)
        self.lblAmbPlan.setObjectName(_fromUtf8("lblAmbPlan"))
        self.gridLayout_2.addWidget(self.lblAmbPlan, 5, 0, 1, 1)
        self.lblHomePlan = QtGui.QLabel(self.groupBox)
        self.lblHomePlan.setObjectName(_fromUtf8("lblHomePlan"))
        self.gridLayout_2.addWidget(self.lblHomePlan, 6, 0, 1, 1)
        self.lblAmbPlanValue = QtGui.QLabel(self.groupBox)
        self.lblAmbPlanValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblAmbPlanValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblAmbPlanValue.setObjectName(_fromUtf8("lblAmbPlanValue"))
        self.gridLayout_2.addWidget(self.lblAmbPlanValue, 5, 1, 1, 1)
        self.lblHomePlanValue = QtGui.QLabel(self.groupBox)
        self.lblHomePlanValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblHomePlanValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblHomePlanValue.setObjectName(_fromUtf8("lblHomePlanValue"))
        self.gridLayout_2.addWidget(self.lblHomePlanValue, 6, 1, 1, 1)
        self.lblExpPlan = QtGui.QLabel(self.groupBox)
        self.lblExpPlan.setObjectName(_fromUtf8("lblExpPlan"))
        self.gridLayout_2.addWidget(self.lblExpPlan, 7, 0, 1, 1)
        self.lblExpPlanValue = QtGui.QLabel(self.groupBox)
        self.lblExpPlanValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblExpPlanValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblExpPlanValue.setObjectName(_fromUtf8("lblExpPlanValue"))
        self.gridLayout_2.addWidget(self.lblExpPlanValue, 7, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 3, 2, 1)
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)

        self.retranslateUi(TimelineDialog)
        QtCore.QObject.connect(self.btnClose, QtCore.SIGNAL(_fromUtf8("clicked()")), TimelineDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(TimelineDialog)
        TimelineDialog.setTabOrder(self.calendar, self.treeOrgStructure)
        TimelineDialog.setTabOrder(self.treeOrgStructure, self.tblPersonnel)
        TimelineDialog.setTabOrder(self.tblPersonnel, self.btnFill)
        TimelineDialog.setTabOrder(self.btnFill, self.btnClose)

    def retranslateUi(self, TimelineDialog):
        TimelineDialog.setWindowTitle(_translate("TimelineDialog", "График", None))
        self.edtFilterPersonnel.setPlaceholderText(_translate("TimelineDialog", "Введите фамилию сотрудника...", None))
        self.btnClose.setText(_translate("TimelineDialog", "Закрыть", None))
        self.btnAbsence.setText(_translate("TimelineDialog", "Заполнить отсутствие", None))
        self.btnFill.setText(_translate("TimelineDialog", "Заполнить (F9)", None))
        self.btnFillTime.setText(_translate("TimelineDialog", "Заполнить фактическое время", None))
        self.btnPrint.setText(_translate("TimelineDialog", "Печатать (F6)", None))
        self.btnPrint.setShortcut(_translate("TimelineDialog", "F6", None))
        self.btnFillVisitsCount.setText(_translate("TimelineDialog", "Посещения", None))
        self.groupBox.setTitle(_translate("TimelineDialog", "Врачебная функция", None))
        self.lblAmbLoad.setText(_translate("TimelineDialog", "СПН на приёме:", None))
        self.lblServLoadValue.setText(_translate("TimelineDialog", "0", None))
        self.lblAmbDays.setText(_translate("TimelineDialog", "Дней на приёме:", None))
        self.lblAmbDaysValue.setText(_translate("TimelineDialog", "0", None))
        self.lblHomeHourLoad.setText(_translate("TimelineDialog", "СН на вызовах:", None))
        self.lblHomeHourLoadValue.setText(_translate("TimelineDialog", "0", None))
        self.lblServExecValue.setText(_translate("TimelineDialog", "0", None))
        self.lblLoad.setText(_translate("TimelineDialog", "Средняя подушевая нагрузка:", None))
        self.lblAbsenceDays.setText(_translate("TimelineDialog", "Дней с отсутствием:", None))
        self.lblExpDays.setText(_translate("TimelineDialog", "Дней на КЭР:", None))
        self.lblHourLoad.setText(_translate("TimelineDialog", "Среднечасовая нагрузка:", None))
        self.lblServHourLoad.setText(_translate("TimelineDialog", "СН на обслуживании:", None))
        self.lblAmbHourLoadValue.setText(_translate("TimelineDialog", "0", None))
        self.lblAmbLoadValue.setText(_translate("TimelineDialog", "0", None))
        self.lblHomeDays.setText(_translate("TimelineDialog", "Дней на вызовах:", None))
        self.lblHourLoadValue.setText(_translate("TimelineDialog", "0", None))
        self.lblExpDaysValue.setText(_translate("TimelineDialog", "0", None))
        self.lblExpHourLoadValue.setText(_translate("TimelineDialog", "0", None))
        self.lblExpExecValue.setText(_translate("TimelineDialog", "0", None))
        self.lblServHourLoadValue.setText(_translate("TimelineDialog", "0", None))
        self.lblAmbExecValue.setText(_translate("TimelineDialog", "0", None))
        self.lblHomeExec.setText(_translate("TimelineDialog", "ВП на вызовах:", None))
        self.lblLoadValue.setText(_translate("TimelineDialog", "0", None))
        self.lblExecValue.setText(_translate("TimelineDialog", "0", None))
        self.lblServExec.setText(_translate("TimelineDialog", "ВП на обслуживании:", None))
        self.lblServLoad.setText(_translate("TimelineDialog", "СПН на обслуживании:", None))
        self.lblExpHourLoad.setText(_translate("TimelineDialog", "СН на КЭР:", None))
        self.lblAmbExec.setText(_translate("TimelineDialog", "ВП на приёме:", None))
        self.lblNumDaysValue.setText(_translate("TimelineDialog", "0", None))
        self.lblNumDays.setText(_translate("TimelineDialog", "Количество дней:", None))
        self.lblHomeLoad.setText(_translate("TimelineDialog", "СПН на вызовах:", None))
        self.lblHomeLoadValue.setText(_translate("TimelineDialog", "0", None))
        self.lblHomeDaysValue.setText(_translate("TimelineDialog", "0", None))
        self.lblHomeExecValue.setText(_translate("TimelineDialog", "0", None))
        self.lblExpExec.setText(_translate("TimelineDialog", "ВП на КЭР:", None))
        self.lblAbsenceDaysValue.setText(_translate("TimelineDialog", "0", None))
        self.lblExpLoad.setText(_translate("TimelineDialog", "СПН на КЭР:", None))
        self.lblExpLoadValue.setText(_translate("TimelineDialog", "0", None))
        self.lblExec.setText(_translate("TimelineDialog", "Выполнение плана:", None))
        self.lblAmbHourLoad.setText(_translate("TimelineDialog", "СН на приёме:", None))
        self.lblAmbPlan.setText(_translate("TimelineDialog", "План приёма амбулаторно:", None))
        self.lblHomePlan.setText(_translate("TimelineDialog", "План приёма на дому:", None))
        self.lblAmbPlanValue.setText(_translate("TimelineDialog", "0", None))
        self.lblHomePlanValue.setText(_translate("TimelineDialog", "0", None))
        self.lblExpPlan.setText(_translate("TimelineDialog", "План приёма КЭР:", None))
        self.lblExpPlanValue.setText(_translate("TimelineDialog", "0", None))

from TimeTable import CTimeTableView
from library.CalendarWidget import CCalendarWidget
from library.TableView import CTableView
