# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client\Registry\ClientVaccinationCardDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ClientVaccinationCardDialog(object):
    def setupUi(self, ClientVaccinationCardDialog):
        ClientVaccinationCardDialog.setObjectName(_fromUtf8("ClientVaccinationCardDialog"))
        ClientVaccinationCardDialog.resize(882, 582)
        ClientVaccinationCardDialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        ClientVaccinationCardDialog.setMouseTracking(False)
        self.verticalLayout_9 = QtGui.QVBoxLayout(ClientVaccinationCardDialog)
        self.verticalLayout_9.setMargin(4)
        self.verticalLayout_9.setSpacing(4)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.splitter_5 = QtGui.QSplitter(ClientVaccinationCardDialog)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setHandleWidth(5)
        self.splitter_5.setChildrenCollapsible(False)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.pnlClientInfoBrowser = QtGui.QWidget(self.splitter_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnlClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.pnlClientInfoBrowser.setSizePolicy(sizePolicy)
        self.pnlClientInfoBrowser.setObjectName(_fromUtf8("pnlClientInfoBrowser"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.pnlClientInfoBrowser)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.txtClientInfoBrowser = CTextBrowser(self.pnlClientInfoBrowser)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setReadOnly(True)
        self.txtClientInfoBrowser.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.verticalLayout_8.addWidget(self.txtClientInfoBrowser)
        self.pnlMain = QtGui.QWidget(self.splitter_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnlMain.sizePolicy().hasHeightForWidth())
        self.pnlMain.setSizePolicy(sizePolicy)
        self.pnlMain.setObjectName(_fromUtf8("pnlMain"))
        self.gridLayout = QtGui.QGridLayout(self.pnlMain)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter_2 = QtGui.QSplitter(self.pnlMain)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.pnlFilter = QtGui.QWidget(self.splitter_2)
        self.pnlFilter.setObjectName(_fromUtf8("pnlFilter"))
        self.gridLayout_3 = QtGui.QGridLayout(self.pnlFilter)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cmbFilterVaccinationCalendar = CRBComboBox(self.pnlFilter)
        self.cmbFilterVaccinationCalendar.setObjectName(_fromUtf8("cmbFilterVaccinationCalendar"))
        self.gridLayout_3.addWidget(self.cmbFilterVaccinationCalendar, 0, 1, 1, 1)
        self.lblFilterVaccinationCalendar = QtGui.QLabel(self.pnlFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFilterVaccinationCalendar.sizePolicy().hasHeightForWidth())
        self.lblFilterVaccinationCalendar.setSizePolicy(sizePolicy)
        self.lblFilterVaccinationCalendar.setObjectName(_fromUtf8("lblFilterVaccinationCalendar"))
        self.gridLayout_3.addWidget(self.lblFilterVaccinationCalendar, 0, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.pnlFilter)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.pnlFilterInfection = QtGui.QWidget(self.splitter)
        self.pnlFilterInfection.setObjectName(_fromUtf8("pnlFilterInfection"))
        self.verticalLayout = QtGui.QVBoxLayout(self.pnlFilterInfection)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblFilterInfection = CRBCheckTableView(self.pnlFilterInfection)
        self.tblFilterInfection.setObjectName(_fromUtf8("tblFilterInfection"))
        self.verticalLayout.addWidget(self.tblFilterInfection)
        self.pnlFilterVaccineAndProbe = QtGui.QWidget(self.splitter)
        self.pnlFilterVaccineAndProbe.setObjectName(_fromUtf8("pnlFilterVaccineAndProbe"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.pnlFilterVaccineAndProbe)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tblFilterVaccine = CRBCheckTableView(self.pnlFilterVaccineAndProbe)
        self.tblFilterVaccine.setObjectName(_fromUtf8("tblFilterVaccine"))
        self.horizontalLayout.addWidget(self.tblFilterVaccine)
        self.tblFilterProbe = CRBCheckTableView(self.pnlFilterVaccineAndProbe)
        self.tblFilterProbe.setObjectName(_fromUtf8("tblFilterProbe"))
        self.horizontalLayout.addWidget(self.tblFilterProbe)
        self.gridLayout_3.addWidget(self.splitter, 2, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(self.splitter_2)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabVaccination = QtGui.QWidget()
        self.tabVaccination.setObjectName(_fromUtf8("tabVaccination"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabVaccination)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabVaccinationSplitter = QtGui.QSplitter(self.tabVaccination)
        self.tabVaccinationSplitter.setOrientation(QtCore.Qt.Vertical)
        self.tabVaccinationSplitter.setObjectName(_fromUtf8("tabVaccinationSplitter"))
        self.pnlVaccination = QtGui.QWidget(self.tabVaccinationSplitter)
        self.pnlVaccination.setObjectName(_fromUtf8("pnlVaccination"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pnlVaccination)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tblVaccination = CTableView(self.pnlVaccination)
        self.tblVaccination.setObjectName(_fromUtf8("tblVaccination"))
        self.verticalLayout_2.addWidget(self.tblVaccination)
        self.pnlVaccinationLeftoverSchema = QtGui.QWidget(self.tabVaccinationSplitter)
        self.pnlVaccinationLeftoverSchema.setObjectName(_fromUtf8("pnlVaccinationLeftoverSchema"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pnlVaccinationLeftoverSchema)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tblVaccinationLeftOverSchema = CTableView(self.pnlVaccinationLeftoverSchema)
        self.tblVaccinationLeftOverSchema.setObjectName(_fromUtf8("tblVaccinationLeftOverSchema"))
        self.verticalLayout_3.addWidget(self.tblVaccinationLeftOverSchema)
        self.verticalLayout_4.addWidget(self.tabVaccinationSplitter)
        self.tabWidget.addTab(self.tabVaccination, _fromUtf8(""))
        self.tabProbe = QtGui.QWidget()
        self.tabProbe.setObjectName(_fromUtf8("tabProbe"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabProbe)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tabProbeSplitter = QtGui.QSplitter(self.tabProbe)
        self.tabProbeSplitter.setOrientation(QtCore.Qt.Vertical)
        self.tabProbeSplitter.setObjectName(_fromUtf8("tabProbeSplitter"))
        self.pnlProbe = QtGui.QWidget(self.tabProbeSplitter)
        self.pnlProbe.setObjectName(_fromUtf8("pnlProbe"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pnlProbe)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tblProbe = CTableView(self.pnlProbe)
        self.tblProbe.setObjectName(_fromUtf8("tblProbe"))
        self.verticalLayout_5.addWidget(self.tblProbe)
        self.pnlProbeLeftoverSchema = QtGui.QWidget(self.tabProbeSplitter)
        self.pnlProbeLeftoverSchema.setObjectName(_fromUtf8("pnlProbeLeftoverSchema"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.pnlProbeLeftoverSchema)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tblProbeLeftoverSchema = CTableView(self.pnlProbeLeftoverSchema)
        self.tblProbeLeftoverSchema.setObjectName(_fromUtf8("tblProbeLeftoverSchema"))
        self.verticalLayout_6.addWidget(self.tblProbeLeftoverSchema)
        self.verticalLayout_7.addWidget(self.tabProbeSplitter)
        self.tabWidget.addTab(self.tabProbe, _fromUtf8(""))
        self.tabMedicalExemption = QtGui.QWidget()
        self.tabMedicalExemption.setObjectName(_fromUtf8("tabMedicalExemption"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tabMedicalExemption)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.tabMedicalExemptionSplitter = QtGui.QSplitter(self.tabMedicalExemption)
        self.tabMedicalExemptionSplitter.setOrientation(QtCore.Qt.Vertical)
        self.tabMedicalExemptionSplitter.setObjectName(_fromUtf8("tabMedicalExemptionSplitter"))
        self.pnlMedicalExemption = QtGui.QWidget(self.tabMedicalExemptionSplitter)
        self.pnlMedicalExemption.setObjectName(_fromUtf8("pnlMedicalExemption"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.pnlMedicalExemption)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.tblMedicalExemption = CTableView(self.pnlMedicalExemption)
        self.tblMedicalExemption.setObjectName(_fromUtf8("tblMedicalExemption"))
        self.verticalLayout_10.addWidget(self.tblMedicalExemption)
        self.pnlMedicalExemptionInfections = QtGui.QWidget(self.tabMedicalExemptionSplitter)
        self.pnlMedicalExemptionInfections.setObjectName(_fromUtf8("pnlMedicalExemptionInfections"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.pnlMedicalExemptionInfections)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.tblMedicalExemptionInfections = CTableView(self.pnlMedicalExemptionInfections)
        self.tblMedicalExemptionInfections.setObjectName(_fromUtf8("tblMedicalExemptionInfections"))
        self.verticalLayout_11.addWidget(self.tblMedicalExemptionInfections)
        self.verticalLayout_12.addWidget(self.tabMedicalExemptionSplitter)
        self.tabWidget.addTab(self.tabMedicalExemption, _fromUtf8(""))
        self.tabCert = QtGui.QWidget()
        self.tabCert.setObjectName(_fromUtf8("tabCert"))
        self.certLayout = QtGui.QVBoxLayout(self.tabCert)
        self.certLayout.setMargin(0)
        self.certLayout.setSpacing(0)
        self.certLayout.setObjectName(_fromUtf8("certLayout"))
        self.tabWidget.addTab(self.tabCert, _fromUtf8(""))
        self.tabPlanning = QtGui.QWidget()
        self.tabPlanning.setObjectName(_fromUtf8("tabPlanning"))
        self.planningLayout = QtGui.QVBoxLayout(self.tabPlanning)
        self.planningLayout.setMargin(0)
        self.planningLayout.setSpacing(0)
        self.planningLayout.setObjectName(_fromUtf8("planningLayout"))
        self.tabWidget.addTab(self.tabPlanning, _fromUtf8(""))
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.splitter_5)
        self.buttonBox = QtGui.QDialogButtonBox(ClientVaccinationCardDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_9.addWidget(self.buttonBox)

        self.retranslateUi(ClientVaccinationCardDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ClientVaccinationCardDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ClientVaccinationCardDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ClientVaccinationCardDialog)
        ClientVaccinationCardDialog.setTabOrder(self.cmbFilterVaccinationCalendar, self.tblFilterInfection)
        ClientVaccinationCardDialog.setTabOrder(self.tblFilterInfection, self.tblFilterVaccine)
        ClientVaccinationCardDialog.setTabOrder(self.tblFilterVaccine, self.tblFilterProbe)
        ClientVaccinationCardDialog.setTabOrder(self.tblFilterProbe, self.tabWidget)
        ClientVaccinationCardDialog.setTabOrder(self.tabWidget, self.tblVaccination)
        ClientVaccinationCardDialog.setTabOrder(self.tblVaccination, self.tblVaccinationLeftOverSchema)
        ClientVaccinationCardDialog.setTabOrder(self.tblVaccinationLeftOverSchema, self.tblProbe)
        ClientVaccinationCardDialog.setTabOrder(self.tblProbe, self.tblProbeLeftoverSchema)
        ClientVaccinationCardDialog.setTabOrder(self.tblProbeLeftoverSchema, self.tblMedicalExemption)
        ClientVaccinationCardDialog.setTabOrder(self.tblMedicalExemption, self.tblMedicalExemptionInfections)
        ClientVaccinationCardDialog.setTabOrder(self.tblMedicalExemptionInfections, self.buttonBox)

    def retranslateUi(self, ClientVaccinationCardDialog):
        ClientVaccinationCardDialog.setWindowTitle(_translate("ClientVaccinationCardDialog", "Dialog", None))
        self.txtClientInfoBrowser.setHtml(_translate("ClientVaccinationCardDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>", None))
        self.lblFilterVaccinationCalendar.setText(_translate("ClientVaccinationCardDialog", "План", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVaccination), _translate("ClientVaccinationCardDialog", "Прививки", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProbe), _translate("ClientVaccinationCardDialog", "Пробы", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMedicalExemption), _translate("ClientVaccinationCardDialog", "Медотводы", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCert), _translate("ClientVaccinationCardDialog", "Сертификат", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPlanning), _translate("ClientVaccinationCardDialog", "Планирование", None))

from library.RBCheckTable import CRBCheckTableView
from library.TableView import CTableView
from library.TextBrowser import CTextBrowser
from library.crbcombobox import CRBComboBox
