# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Samson\UP_s11\client_test\Registry\DispExchangeDiagnosisPage.ui'
#
# Created: Wed Dec 20 11:54:44 2023
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DispExchangeDiagnosisPage(object):
    def setupUi(self, DispExchangeDiagnosisPage):
        DispExchangeDiagnosisPage.setObjectName(_fromUtf8("DispExchangeDiagnosisPage"))
        DispExchangeDiagnosisPage.resize(1117, 806)
        self.horizontalLayout = QtGui.QHBoxLayout(DispExchangeDiagnosisPage)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setMargin(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.scrollArea = QtGui.QScrollArea(DispExchangeDiagnosisPage)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1107, 796))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.splitter = QtGui.QSplitter(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tblDiagnosisDispansPlaned = CTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tblDiagnosisDispansPlaned.sizePolicy().hasHeightForWidth())
        self.tblDiagnosisDispansPlaned.setSizePolicy(sizePolicy)
        self.tblDiagnosisDispansPlaned.setObjectName(_fromUtf8("tblDiagnosisDispansPlaned"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPlanExportErrors = QtGui.QWidget()
        self.tabPlanExportErrors.setObjectName(_fromUtf8("tabPlanExportErrors"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabPlanExportErrors)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblPlanExportErrors = CTableView(self.tabPlanExportErrors)
        self.tblPlanExportErrors.setObjectName(_fromUtf8("tblPlanExportErrors"))
        self.verticalLayout.addWidget(self.tblPlanExportErrors)
        self.tabWidget.addTab(self.tabPlanExportErrors, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.lblRowCount = QtGui.QLabel(self.layoutWidget)
        self.lblRowCount.setObjectName(_fromUtf8("lblRowCount"))
        self.verticalLayout_2.addWidget(self.lblRowCount)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setMargin(4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.sbYear = QtGui.QSpinBox(self.groupBox)
        self.sbYear.setMinimum(2017)
        self.sbYear.setMaximum(9999)
        self.sbYear.setObjectName(_fromUtf8("sbYear"))
        self.gridLayout.addWidget(self.sbYear, 0, 1, 1, 1)
        self.cmbMonth = QtGui.QComboBox(self.groupBox)
        self.cmbMonth.setObjectName(_fromUtf8("cmbMonth"))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbMonth, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.chkFilterLastName = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterLastName.sizePolicy().hasHeightForWidth())
        self.chkFilterLastName.setSizePolicy(sizePolicy)
        self.chkFilterLastName.setObjectName(_fromUtf8("chkFilterLastName"))
        self.verticalLayout_6.addWidget(self.chkFilterLastName)
        self.edtFilterLastName = QtGui.QLineEdit(self.groupBox)
        self.edtFilterLastName.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterLastName.sizePolicy().hasHeightForWidth())
        self.edtFilterLastName.setSizePolicy(sizePolicy)
        self.edtFilterLastName.setObjectName(_fromUtf8("edtFilterLastName"))
        self.verticalLayout_6.addWidget(self.edtFilterLastName)
        self.chkFilterFirstName = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterFirstName.sizePolicy().hasHeightForWidth())
        self.chkFilterFirstName.setSizePolicy(sizePolicy)
        self.chkFilterFirstName.setObjectName(_fromUtf8("chkFilterFirstName"))
        self.verticalLayout_6.addWidget(self.chkFilterFirstName)
        self.edtFilterFirstName = QtGui.QLineEdit(self.groupBox)
        self.edtFilterFirstName.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterFirstName.sizePolicy().hasHeightForWidth())
        self.edtFilterFirstName.setSizePolicy(sizePolicy)
        self.edtFilterFirstName.setObjectName(_fromUtf8("edtFilterFirstName"))
        self.verticalLayout_6.addWidget(self.edtFilterFirstName)
        self.chkFilterPatrName = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterPatrName.sizePolicy().hasHeightForWidth())
        self.chkFilterPatrName.setSizePolicy(sizePolicy)
        self.chkFilterPatrName.setObjectName(_fromUtf8("chkFilterPatrName"))
        self.verticalLayout_6.addWidget(self.chkFilterPatrName)
        self.edtFilterPatrName = QtGui.QLineEdit(self.groupBox)
        self.edtFilterPatrName.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterPatrName.sizePolicy().hasHeightForWidth())
        self.edtFilterPatrName.setSizePolicy(sizePolicy)
        self.edtFilterPatrName.setObjectName(_fromUtf8("edtFilterPatrName"))
        self.verticalLayout_6.addWidget(self.edtFilterPatrName)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.chkFilterBirthDay = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterBirthDay.sizePolicy().hasHeightForWidth())
        self.chkFilterBirthDay.setSizePolicy(sizePolicy)
        self.chkFilterBirthDay.setObjectName(_fromUtf8("chkFilterBirthDay"))
        self.horizontalLayout_30.addWidget(self.chkFilterBirthDay)
        self.edtFilterBirthDay = CDateEdit(self.groupBox)
        self.edtFilterBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterBirthDay.sizePolicy().hasHeightForWidth())
        self.edtFilterBirthDay.setSizePolicy(sizePolicy)
        self.edtFilterBirthDay.setDisplayFormat(_fromUtf8("dd.MM.yyyy"))
        self.edtFilterBirthDay.setCalendarPopup(True)
        self.edtFilterBirthDay.setObjectName(_fromUtf8("edtFilterBirthDay"))
        self.horizontalLayout_30.addWidget(self.edtFilterBirthDay)
        self.horizontalLayout_30.setStretch(0, 2)
        self.horizontalLayout_30.setStretch(1, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.chkFilterEndBirthDay = QtGui.QCheckBox(self.groupBox)
        self.chkFilterEndBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterEndBirthDay.sizePolicy().hasHeightForWidth())
        self.chkFilterEndBirthDay.setSizePolicy(sizePolicy)
        self.chkFilterEndBirthDay.setObjectName(_fromUtf8("chkFilterEndBirthDay"))
        self.horizontalLayout_29.addWidget(self.chkFilterEndBirthDay)
        self.edtFilterEndBirthDay = CDateEdit(self.groupBox)
        self.edtFilterEndBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterEndBirthDay.sizePolicy().hasHeightForWidth())
        self.edtFilterEndBirthDay.setSizePolicy(sizePolicy)
        self.edtFilterEndBirthDay.setDisplayFormat(_fromUtf8("dd.MM.yyyy"))
        self.edtFilterEndBirthDay.setCalendarPopup(True)
        self.edtFilterEndBirthDay.setObjectName(_fromUtf8("edtFilterEndBirthDay"))
        self.horizontalLayout_29.addWidget(self.edtFilterEndBirthDay)
        self.horizontalLayout_29.setStretch(0, 2)
        self.horizontalLayout_29.setStretch(1, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_29)
        self.chkFilterAddressOrgStructure = QtGui.QCheckBox(self.groupBox)
        self.chkFilterAddressOrgStructure.setObjectName(_fromUtf8("chkFilterAddressOrgStructure"))
        self.verticalLayout_6.addWidget(self.chkFilterAddressOrgStructure)
        self.cmbFilterAddressOrgStructure = COrgStructureComboBox(self.groupBox)
        self.cmbFilterAddressOrgStructure.setEnabled(False)
        self.cmbFilterAddressOrgStructure.setObjectName(_fromUtf8("cmbFilterAddressOrgStructure"))
        self.verticalLayout_6.addWidget(self.cmbFilterAddressOrgStructure)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.chkFilterSex = QtGui.QCheckBox(self.groupBox)
        self.chkFilterSex.setObjectName(_fromUtf8("chkFilterSex"))
        self.horizontalLayout_28.addWidget(self.chkFilterSex)
        self.cmbFilterSex = QtGui.QComboBox(self.groupBox)
        self.cmbFilterSex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterSex.sizePolicy().hasHeightForWidth())
        self.cmbFilterSex.setSizePolicy(sizePolicy)
        self.cmbFilterSex.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbFilterSex.setObjectName(_fromUtf8("cmbFilterSex"))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.setItemText(0, _fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.horizontalLayout_28.addWidget(self.cmbFilterSex)
        self.horizontalLayout_28.setStretch(0, 2)
        self.horizontalLayout_28.setStretch(1, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblBusyness = QtGui.QLabel(self.groupBox)
        self.lblBusyness.setObjectName(_fromUtf8("lblBusyness"))
        self.horizontalLayout_4.addWidget(self.lblBusyness)
        self.cmbBusyness = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBusyness.sizePolicy().hasHeightForWidth())
        self.cmbBusyness.setSizePolicy(sizePolicy)
        self.cmbBusyness.setObjectName(_fromUtf8("cmbBusyness"))
        self.cmbBusyness.addItem(_fromUtf8(""))
        self.cmbBusyness.setItemText(0, _fromUtf8(""))
        self.cmbBusyness.addItem(_fromUtf8(""))
        self.cmbBusyness.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cmbBusyness)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.chkSocStatuses = QtGui.QCheckBox(self.groupBox)
        self.chkSocStatuses.setObjectName(_fromUtf8("chkSocStatuses"))
        self.horizontalLayout_5.addWidget(self.chkSocStatuses)
        self.chkSocStatusesCondition = QtGui.QCheckBox(self.groupBox)
        self.chkSocStatusesCondition.setEnabled(False)
        self.chkSocStatusesCondition.setObjectName(_fromUtf8("chkSocStatusesCondition"))
        self.horizontalLayout_5.addWidget(self.chkSocStatusesCondition)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.lblFilterSocStatusesBegDate = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFilterSocStatusesBegDate.sizePolicy().hasHeightForWidth())
        self.lblFilterSocStatusesBegDate.setSizePolicy(sizePolicy)
        self.lblFilterSocStatusesBegDate.setObjectName(_fromUtf8("lblFilterSocStatusesBegDate"))
        self.horizontalLayout_38.addWidget(self.lblFilterSocStatusesBegDate)
        self.edtFilterSocStatusesBegDate = CDateEdit(self.groupBox)
        self.edtFilterSocStatusesBegDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterSocStatusesBegDate.sizePolicy().hasHeightForWidth())
        self.edtFilterSocStatusesBegDate.setSizePolicy(sizePolicy)
        self.edtFilterSocStatusesBegDate.setDisplayFormat(_fromUtf8("dd.MM.yyyy"))
        self.edtFilterSocStatusesBegDate.setCalendarPopup(True)
        self.edtFilterSocStatusesBegDate.setObjectName(_fromUtf8("edtFilterSocStatusesBegDate"))
        self.horizontalLayout_38.addWidget(self.edtFilterSocStatusesBegDate)
        self.lblFilterSocStatusesEndDate = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFilterSocStatusesEndDate.sizePolicy().hasHeightForWidth())
        self.lblFilterSocStatusesEndDate.setSizePolicy(sizePolicy)
        self.lblFilterSocStatusesEndDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFilterSocStatusesEndDate.setObjectName(_fromUtf8("lblFilterSocStatusesEndDate"))
        self.horizontalLayout_38.addWidget(self.lblFilterSocStatusesEndDate)
        self.edtFilterSocStatusesEndDate = CDateEdit(self.groupBox)
        self.edtFilterSocStatusesEndDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterSocStatusesEndDate.sizePolicy().hasHeightForWidth())
        self.edtFilterSocStatusesEndDate.setSizePolicy(sizePolicy)
        self.edtFilterSocStatusesEndDate.setDisplayFormat(_fromUtf8("dd.MM.yyyy"))
        self.edtFilterSocStatusesEndDate.setCalendarPopup(True)
        self.edtFilterSocStatusesEndDate.setObjectName(_fromUtf8("edtFilterSocStatusesEndDate"))
        self.horizontalLayout_38.addWidget(self.edtFilterSocStatusesEndDate)
        self.horizontalLayout_38.setStretch(1, 2)
        self.horizontalLayout_38.setStretch(3, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_38)
        self.cmbSocStatusesClass = CSocStatusComboBox(self.groupBox)
        self.cmbSocStatusesClass.setEnabled(False)
        self.cmbSocStatusesClass.setObjectName(_fromUtf8("cmbSocStatusesClass"))
        self.verticalLayout_6.addWidget(self.cmbSocStatusesClass)
        self.cmbSocStatusesType = CRBComboBox(self.groupBox)
        self.cmbSocStatusesType.setEnabled(False)
        self.cmbSocStatusesType.setObjectName(_fromUtf8("cmbSocStatusesType"))
        self.verticalLayout_6.addWidget(self.cmbSocStatusesType)
        self.chkFilterPerson = QtGui.QCheckBox(self.groupBox)
        self.chkFilterPerson.setObjectName(_fromUtf8("chkFilterPerson"))
        self.verticalLayout_6.addWidget(self.chkFilterPerson)
        self.cmbFilterPerson = CPersonComboBoxEx(self.groupBox)
        self.cmbFilterPerson.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterPerson.sizePolicy().hasHeightForWidth())
        self.cmbFilterPerson.setSizePolicy(sizePolicy)
        self.cmbFilterPerson.setWhatsThis(_fromUtf8(""))
        self.cmbFilterPerson.setObjectName(_fromUtf8("cmbFilterPerson"))
        self.cmbFilterPerson.addItem(_fromUtf8(""))
        self.verticalLayout_6.addWidget(self.cmbFilterPerson)
        self.chkFilterMKB = QtGui.QCheckBox(self.groupBox)
        self.chkFilterMKB.setObjectName(_fromUtf8("chkFilterMKB"))
        self.verticalLayout_6.addWidget(self.chkFilterMKB)
        self.horizontalLayout_83 = QtGui.QHBoxLayout()
        self.horizontalLayout_83.setObjectName(_fromUtf8("horizontalLayout_83"))
        self.edtFilterMKBFrom = CICDCodeEdit(self.groupBox)
        self.edtFilterMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtFilterMKBFrom.setSizePolicy(sizePolicy)
        self.edtFilterMKBFrom.setObjectName(_fromUtf8("edtFilterMKBFrom"))
        self.horizontalLayout_83.addWidget(self.edtFilterMKBFrom)
        self.edtFilterMKBTo = CICDCodeEdit(self.groupBox)
        self.edtFilterMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterMKBTo.sizePolicy().hasHeightForWidth())
        self.edtFilterMKBTo.setSizePolicy(sizePolicy)
        self.edtFilterMKBTo.setMaxLength(6)
        self.edtFilterMKBTo.setObjectName(_fromUtf8("edtFilterMKBTo"))
        self.horizontalLayout_83.addWidget(self.edtFilterMKBTo)
        self.verticalLayout_6.addLayout(self.horizontalLayout_83)
        self.chkNotExported = QtGui.QCheckBox(self.groupBox)
        self.chkNotExported.setChecked(True)
        self.chkNotExported.setObjectName(_fromUtf8("chkNotExported"))
        self.verticalLayout_6.addWidget(self.chkNotExported)
        self.chkExportedSuccessfully = QtGui.QCheckBox(self.groupBox)
        self.chkExportedSuccessfully.setChecked(False)
        self.chkExportedSuccessfully.setObjectName(_fromUtf8("chkExportedSuccessfully"))
        self.verticalLayout_6.addWidget(self.chkExportedSuccessfully)
        self.chkExportedWithErrors = QtGui.QCheckBox(self.groupBox)
        self.chkExportedWithErrors.setChecked(False)
        self.chkExportedWithErrors.setObjectName(_fromUtf8("chkExportedWithErrors"))
        self.verticalLayout_6.addWidget(self.chkExportedWithErrors)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnResetFilter = QtGui.QPushButton(self.groupBox)
        self.btnResetFilter.setObjectName(_fromUtf8("btnResetFilter"))
        self.horizontalLayout_3.addWidget(self.btnResetFilter)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnApplyFilter = QtGui.QPushButton(self.groupBox)
        self.btnApplyFilter.setObjectName(_fromUtf8("btnApplyFilter"))
        self.horizontalLayout_3.addWidget(self.btnApplyFilter)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.btnShowReport = QtGui.QPushButton(self.groupBox)
        self.btnShowReport.setObjectName(_fromUtf8("btnShowReport"))
        self.verticalLayout_6.addWidget(self.btnShowReport)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.btnPutEvPlanList = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnPutEvPlanList.setObjectName(_fromUtf8("btnPutEvPlanList"))
        self.verticalLayout_3.addWidget(self.btnPutEvPlanList)
        self.btnExportedPlan = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnExportedPlan.setObjectName(_fromUtf8("btnExportedPlan"))
        self.verticalLayout_3.addWidget(self.btnExportedPlan)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(DispExchangeDiagnosisPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DispExchangeDiagnosisPage)

    def retranslateUi(self, DispExchangeDiagnosisPage):
        DispExchangeDiagnosisPage.setWindowTitle(_translate("DispExchangeDiagnosisPage", "Диспансерные осмотры", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPlanExportErrors), _translate("DispExchangeDiagnosisPage", "Ошибки", None))
        self.lblRowCount.setText(_translate("DispExchangeDiagnosisPage", "Список пуст", None))
        self.groupBox.setTitle(_translate("DispExchangeDiagnosisPage", "Фильтр", None))
        self.label_2.setText(_translate("DispExchangeDiagnosisPage", "Месяц", None))
        self.cmbMonth.setItemText(0, _translate("DispExchangeDiagnosisPage", "все", None))
        self.cmbMonth.setItemText(1, _translate("DispExchangeDiagnosisPage", "январь", None))
        self.cmbMonth.setItemText(2, _translate("DispExchangeDiagnosisPage", "февраль", None))
        self.cmbMonth.setItemText(3, _translate("DispExchangeDiagnosisPage", "март", None))
        self.cmbMonth.setItemText(4, _translate("DispExchangeDiagnosisPage", "апрель", None))
        self.cmbMonth.setItemText(5, _translate("DispExchangeDiagnosisPage", "май", None))
        self.cmbMonth.setItemText(6, _translate("DispExchangeDiagnosisPage", "июнь", None))
        self.cmbMonth.setItemText(7, _translate("DispExchangeDiagnosisPage", "июль", None))
        self.cmbMonth.setItemText(8, _translate("DispExchangeDiagnosisPage", "август", None))
        self.cmbMonth.setItemText(9, _translate("DispExchangeDiagnosisPage", "сентябрь", None))
        self.cmbMonth.setItemText(10, _translate("DispExchangeDiagnosisPage", "октябрь", None))
        self.cmbMonth.setItemText(11, _translate("DispExchangeDiagnosisPage", "ноябрь", None))
        self.cmbMonth.setItemText(12, _translate("DispExchangeDiagnosisPage", "декабрь", None))
        self.label.setText(_translate("DispExchangeDiagnosisPage", "Год", None))
        self.chkFilterLastName.setText(_translate("DispExchangeDiagnosisPage", "Фамилия", None))
        self.chkFilterFirstName.setText(_translate("DispExchangeDiagnosisPage", "Имя", None))
        self.chkFilterPatrName.setText(_translate("DispExchangeDiagnosisPage", "Отчество", None))
        self.chkFilterBirthDay.setText(_translate("DispExchangeDiagnosisPage", "Дата рожд", None))
        self.chkFilterEndBirthDay.setText(_translate("DispExchangeDiagnosisPage", "по", None))
        self.chkFilterAddressOrgStructure.setText(_translate("DispExchangeDiagnosisPage", "По участку", None))
        self.chkFilterSex.setText(_translate("DispExchangeDiagnosisPage", "Пол", None))
        self.cmbFilterSex.setItemText(1, _translate("DispExchangeDiagnosisPage", "М", None))
        self.cmbFilterSex.setItemText(2, _translate("DispExchangeDiagnosisPage", "Ж", None))
        self.lblBusyness.setText(_translate("DispExchangeDiagnosisPage", "Занятость", None))
        self.cmbBusyness.setItemText(1, _translate("DispExchangeDiagnosisPage", "работающие", None))
        self.cmbBusyness.setItemText(2, _translate("DispExchangeDiagnosisPage", "неработающие", None))
        self.chkSocStatuses.setText(_translate("DispExchangeDiagnosisPage", "Соц.статус", None))
        self.chkSocStatusesCondition.setText(_translate("DispExchangeDiagnosisPage", "Не имеет соц.статуса", None))
        self.lblFilterSocStatusesBegDate.setText(_translate("DispExchangeDiagnosisPage", "С", None))
        self.lblFilterSocStatusesEndDate.setText(_translate("DispExchangeDiagnosisPage", "по", None))
        self.chkFilterPerson.setText(_translate("DispExchangeDiagnosisPage", "Врач", None))
        self.cmbFilterPerson.setItemText(0, _translate("DispExchangeDiagnosisPage", "Врач", None))
        self.chkFilterMKB.setText(_translate("DispExchangeDiagnosisPage", "Коды МКБ", None))
        self.edtFilterMKBFrom.setInputMask(_translate("DispExchangeDiagnosisPage", "a00.00; ", None))
        self.edtFilterMKBFrom.setText(_translate("DispExchangeDiagnosisPage", "A.", None))
        self.edtFilterMKBTo.setInputMask(_translate("DispExchangeDiagnosisPage", "a00.00; ", None))
        self.edtFilterMKBTo.setText(_translate("DispExchangeDiagnosisPage", "T99.9", None))
        self.chkNotExported.setText(_translate("DispExchangeDiagnosisPage", "Запланированные, не отправленные", None))
        self.chkExportedSuccessfully.setText(_translate("DispExchangeDiagnosisPage", "Отправленные успешно", None))
        self.chkExportedWithErrors.setText(_translate("DispExchangeDiagnosisPage", "Отправленные с ошибками", None))
        self.btnResetFilter.setText(_translate("DispExchangeDiagnosisPage", "Сбросить", None))
        self.btnApplyFilter.setText(_translate("DispExchangeDiagnosisPage", "Применить", None))
        self.btnShowReport.setText(_translate("DispExchangeDiagnosisPage", "Печать списка", None))
        self.btnPutEvPlanList.setText(_translate("DispExchangeDiagnosisPage", "Экспорт плана диспансерных осмотров", None))
        self.btnExportedPlan.setText(_translate("DispExchangeDiagnosisPage", "Список запланированных в ТФОМС", None))

from library.crbcombobox import CRBComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.ICDCodeEdit import CICDCodeEdit
from library.TableView import CTableView
from Registry.SocStatusComboBox import CSocStatusComboBox
from library.DateEdit import CDateEdit
