# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\Samson\UP_s11\client\Registry\DispExchangeProfilacticPage.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DispExchangeProfilacticPage(object):
    def setupUi(self, DispExchangeProfilacticPage):
        DispExchangeProfilacticPage.setObjectName(_fromUtf8("DispExchangeProfilacticPage"))
        DispExchangeProfilacticPage.resize(1487, 1041)
        self.horizontalLayout = QtGui.QHBoxLayout(DispExchangeProfilacticPage)
        self.horizontalLayout.setMargin(4)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.scrollArea = QtGui.QScrollArea(DispExchangeProfilacticPage)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1477, 1031))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.splitter = QtGui.QSplitter(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tblClients = CTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tblClients.sizePolicy().hasHeightForWidth())
        self.tblClients.setSizePolicy(sizePolicy)
        self.tblClients.setObjectName(_fromUtf8("tblClients"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPlanExportErrors = QtGui.QWidget()
        self.tabPlanExportErrors.setObjectName(_fromUtf8("tabPlanExportErrors"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabPlanExportErrors)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblPlanExportErrors = CTableView(self.tabPlanExportErrors)
        self.tblPlanExportErrors.setObjectName(_fromUtf8("tblPlanExportErrors"))
        self.verticalLayout.addWidget(self.tblPlanExportErrors)
        self.tabWidget.addTab(self.tabPlanExportErrors, _fromUtf8(""))
        self.tabFactInfos = QtGui.QWidget()
        self.tabFactInfos.setObjectName(_fromUtf8("tabFactInfos"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabFactInfos)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tblFactInfos = CTableView(self.tabFactInfos)
        self.tblFactInfos.setObjectName(_fromUtf8("tblFactInfos"))
        self.verticalLayout_4.addWidget(self.tblFactInfos)
        self.tabWidget.addTab(self.tabFactInfos, _fromUtf8(""))
        self.tabFactInvcs = QtGui.QWidget()
        self.tabFactInvcs.setObjectName(_fromUtf8("tabFactInvcs"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabFactInvcs)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tblFactInvcs = CTableView(self.tabFactInvcs)
        self.tblFactInvcs.setObjectName(_fromUtf8("tblFactInvcs"))
        self.verticalLayout_5.addWidget(self.tblFactInvcs)
        self.tabWidget.addTab(self.tabFactInvcs, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.lblClientsCount = QtGui.QLabel(self.layoutWidget)
        self.lblClientsCount.setObjectName(_fromUtf8("lblClientsCount"))
        self.verticalLayout_2.addWidget(self.lblClientsCount)
        self.horizontalLayout_2.addWidget(self.splitter)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setMargin(4)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.cmbKind = QtGui.QComboBox(self.groupBox)
        self.cmbKind.setObjectName(_fromUtf8("cmbKind"))
        self.cmbKind.addItem(_fromUtf8(""))
        self.cmbKind.addItem(_fromUtf8(""))
        self.cmbKind.addItem(_fromUtf8(""))
        self.cmbKind.addItem(_fromUtf8(""))
        self.cmbKind.addItem(_fromUtf8(""))
        self.cmbKind.addItem(_fromUtf8(""))
        self.cmbKind.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbKind, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.sbYear = QtGui.QSpinBox(self.groupBox)
        self.sbYear.setMinimum(2017)
        self.sbYear.setMaximum(9999)
        self.sbYear.setObjectName(_fromUtf8("sbYear"))
        self.gridLayout.addWidget(self.sbYear, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cmbMonth = QtGui.QComboBox(self.groupBox)
        self.cmbMonth.setObjectName(_fromUtf8("cmbMonth"))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbMonth, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.chkFilterLastName = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterLastName.sizePolicy().hasHeightForWidth())
        self.chkFilterLastName.setSizePolicy(sizePolicy)
        self.chkFilterLastName.setObjectName(_fromUtf8("chkFilterLastName"))
        self.verticalLayout_6.addWidget(self.chkFilterLastName)
        self.edtFilterLastName = QtGui.QLineEdit(self.groupBox)
        self.edtFilterLastName.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterLastName.sizePolicy().hasHeightForWidth())
        self.edtFilterLastName.setSizePolicy(sizePolicy)
        self.edtFilterLastName.setObjectName(_fromUtf8("edtFilterLastName"))
        self.verticalLayout_6.addWidget(self.edtFilterLastName)
        self.chkFilterFirstName = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterFirstName.sizePolicy().hasHeightForWidth())
        self.chkFilterFirstName.setSizePolicy(sizePolicy)
        self.chkFilterFirstName.setObjectName(_fromUtf8("chkFilterFirstName"))
        self.verticalLayout_6.addWidget(self.chkFilterFirstName)
        self.edtFilterFirstName = QtGui.QLineEdit(self.groupBox)
        self.edtFilterFirstName.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterFirstName.sizePolicy().hasHeightForWidth())
        self.edtFilterFirstName.setSizePolicy(sizePolicy)
        self.edtFilterFirstName.setObjectName(_fromUtf8("edtFilterFirstName"))
        self.verticalLayout_6.addWidget(self.edtFilterFirstName)
        self.chkFilterPatrName = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterPatrName.sizePolicy().hasHeightForWidth())
        self.chkFilterPatrName.setSizePolicy(sizePolicy)
        self.chkFilterPatrName.setObjectName(_fromUtf8("chkFilterPatrName"))
        self.verticalLayout_6.addWidget(self.chkFilterPatrName)
        self.edtFilterPatrName = QtGui.QLineEdit(self.groupBox)
        self.edtFilterPatrName.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterPatrName.sizePolicy().hasHeightForWidth())
        self.edtFilterPatrName.setSizePolicy(sizePolicy)
        self.edtFilterPatrName.setObjectName(_fromUtf8("edtFilterPatrName"))
        self.verticalLayout_6.addWidget(self.edtFilterPatrName)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.chkFilterBirthDay = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterBirthDay.sizePolicy().hasHeightForWidth())
        self.chkFilterBirthDay.setSizePolicy(sizePolicy)
        self.chkFilterBirthDay.setObjectName(_fromUtf8("chkFilterBirthDay"))
        self.horizontalLayout_30.addWidget(self.chkFilterBirthDay)
        self.edtFilterBirthDay = CDateEdit(self.groupBox)
        self.edtFilterBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterBirthDay.sizePolicy().hasHeightForWidth())
        self.edtFilterBirthDay.setSizePolicy(sizePolicy)
        self.edtFilterBirthDay.setDisplayFormat(_fromUtf8("dd.MM.yyyy"))
        self.edtFilterBirthDay.setCalendarPopup(True)
        self.edtFilterBirthDay.setObjectName(_fromUtf8("edtFilterBirthDay"))
        self.horizontalLayout_30.addWidget(self.edtFilterBirthDay)
        self.horizontalLayout_30.setStretch(0, 2)
        self.horizontalLayout_30.setStretch(1, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.chkFilterEndBirthDay = QtGui.QCheckBox(self.groupBox)
        self.chkFilterEndBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFilterEndBirthDay.sizePolicy().hasHeightForWidth())
        self.chkFilterEndBirthDay.setSizePolicy(sizePolicy)
        self.chkFilterEndBirthDay.setObjectName(_fromUtf8("chkFilterEndBirthDay"))
        self.horizontalLayout_29.addWidget(self.chkFilterEndBirthDay)
        self.edtFilterEndBirthDay = CDateEdit(self.groupBox)
        self.edtFilterEndBirthDay.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterEndBirthDay.sizePolicy().hasHeightForWidth())
        self.edtFilterEndBirthDay.setSizePolicy(sizePolicy)
        self.edtFilterEndBirthDay.setDisplayFormat(_fromUtf8("dd.MM.yyyy"))
        self.edtFilterEndBirthDay.setCalendarPopup(True)
        self.edtFilterEndBirthDay.setObjectName(_fromUtf8("edtFilterEndBirthDay"))
        self.horizontalLayout_29.addWidget(self.edtFilterEndBirthDay)
        self.horizontalLayout_29.setStretch(0, 2)
        self.horizontalLayout_29.setStretch(1, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_29)
        self.chkFilterAddressOrgStructure = QtGui.QCheckBox(self.groupBox)
        self.chkFilterAddressOrgStructure.setObjectName(_fromUtf8("chkFilterAddressOrgStructure"))
        self.verticalLayout_6.addWidget(self.chkFilterAddressOrgStructure)
        self.cmbFilterAddressOrgStructure = COrgStructureComboBox(self.groupBox)
        self.cmbFilterAddressOrgStructure.setEnabled(False)
        self.cmbFilterAddressOrgStructure.setObjectName(_fromUtf8("cmbFilterAddressOrgStructure"))
        self.verticalLayout_6.addWidget(self.cmbFilterAddressOrgStructure)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.chkFilterSex = QtGui.QCheckBox(self.groupBox)
        self.chkFilterSex.setObjectName(_fromUtf8("chkFilterSex"))
        self.horizontalLayout_28.addWidget(self.chkFilterSex)
        self.cmbFilterSex = QtGui.QComboBox(self.groupBox)
        self.cmbFilterSex.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterSex.sizePolicy().hasHeightForWidth())
        self.cmbFilterSex.setSizePolicy(sizePolicy)
        self.cmbFilterSex.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbFilterSex.setObjectName(_fromUtf8("cmbFilterSex"))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.setItemText(0, _fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.horizontalLayout_28.addWidget(self.cmbFilterSex)
        self.horizontalLayout_28.setStretch(0, 2)
        self.horizontalLayout_28.setStretch(1, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblBusyness = QtGui.QLabel(self.groupBox)
        self.lblBusyness.setObjectName(_fromUtf8("lblBusyness"))
        self.horizontalLayout_4.addWidget(self.lblBusyness)
        self.cmbBusyness = QtGui.QComboBox(self.groupBox)
        self.cmbBusyness.setObjectName(_fromUtf8("cmbBusyness"))
        self.cmbBusyness.addItem(_fromUtf8(""))
        self.cmbBusyness.setItemText(0, _fromUtf8(""))
        self.cmbBusyness.addItem(_fromUtf8(""))
        self.cmbBusyness.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cmbBusyness)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.chkSocStatuses = QtGui.QCheckBox(self.groupBox)
        self.chkSocStatuses.setObjectName(_fromUtf8("chkSocStatuses"))
        self.horizontalLayout_5.addWidget(self.chkSocStatuses)
        self.chkSocStatusesCondition = QtGui.QCheckBox(self.groupBox)
        self.chkSocStatusesCondition.setEnabled(False)
        self.chkSocStatusesCondition.setObjectName(_fromUtf8("chkSocStatusesCondition"))
        self.horizontalLayout_5.addWidget(self.chkSocStatusesCondition)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.lblFilterSocStatusesBegDate = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFilterSocStatusesBegDate.sizePolicy().hasHeightForWidth())
        self.lblFilterSocStatusesBegDate.setSizePolicy(sizePolicy)
        self.lblFilterSocStatusesBegDate.setObjectName(_fromUtf8("lblFilterSocStatusesBegDate"))
        self.horizontalLayout_38.addWidget(self.lblFilterSocStatusesBegDate)
        self.edtFilterSocStatusesBegDate = CDateEdit(self.groupBox)
        self.edtFilterSocStatusesBegDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterSocStatusesBegDate.sizePolicy().hasHeightForWidth())
        self.edtFilterSocStatusesBegDate.setSizePolicy(sizePolicy)
        self.edtFilterSocStatusesBegDate.setDisplayFormat(_fromUtf8("dd.MM.yyyy"))
        self.edtFilterSocStatusesBegDate.setCalendarPopup(True)
        self.edtFilterSocStatusesBegDate.setObjectName(_fromUtf8("edtFilterSocStatusesBegDate"))
        self.horizontalLayout_38.addWidget(self.edtFilterSocStatusesBegDate)
        self.lblFilterSocStatusesEndDate = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFilterSocStatusesEndDate.sizePolicy().hasHeightForWidth())
        self.lblFilterSocStatusesEndDate.setSizePolicy(sizePolicy)
        self.lblFilterSocStatusesEndDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFilterSocStatusesEndDate.setObjectName(_fromUtf8("lblFilterSocStatusesEndDate"))
        self.horizontalLayout_38.addWidget(self.lblFilterSocStatusesEndDate)
        self.edtFilterSocStatusesEndDate = CDateEdit(self.groupBox)
        self.edtFilterSocStatusesEndDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterSocStatusesEndDate.sizePolicy().hasHeightForWidth())
        self.edtFilterSocStatusesEndDate.setSizePolicy(sizePolicy)
        self.edtFilterSocStatusesEndDate.setDisplayFormat(_fromUtf8("dd.MM.yyyy"))
        self.edtFilterSocStatusesEndDate.setCalendarPopup(True)
        self.edtFilterSocStatusesEndDate.setObjectName(_fromUtf8("edtFilterSocStatusesEndDate"))
        self.horizontalLayout_38.addWidget(self.edtFilterSocStatusesEndDate)
        self.horizontalLayout_38.setStretch(1, 2)
        self.horizontalLayout_38.setStretch(3, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_38)
        self.cmbSocStatusesClass = CSocStatusComboBox(self.groupBox)
        self.cmbSocStatusesClass.setEnabled(False)
        self.cmbSocStatusesClass.setObjectName(_fromUtf8("cmbSocStatusesClass"))
        self.verticalLayout_6.addWidget(self.cmbSocStatusesClass)
        self.cmbSocStatusesType = CRBComboBox(self.groupBox)
        self.cmbSocStatusesType.setEnabled(False)
        self.cmbSocStatusesType.setObjectName(_fromUtf8("cmbSocStatusesType"))
        self.verticalLayout_6.addWidget(self.cmbSocStatusesType)
        self.chkForPlanning = QtGui.QCheckBox(self.groupBox)
        self.chkForPlanning.setChecked(False)
        self.chkForPlanning.setObjectName(_fromUtf8("chkForPlanning"))
        self.verticalLayout_6.addWidget(self.chkForPlanning)
        self.chkHideUDEvents = QtGui.QCheckBox(self.groupBox)
        self.chkHideUDEvents.setEnabled(False)
        self.chkHideUDEvents.setChecked(True)
        self.chkHideUDEvents.setObjectName(_fromUtf8("chkHideUDEvents"))
        self.verticalLayout_6.addWidget(self.chkHideUDEvents)
        self.chkNotPlanned = QtGui.QCheckBox(self.groupBox)
        self.chkNotPlanned.setChecked(False)
        self.chkNotPlanned.setObjectName(_fromUtf8("chkNotPlanned"))
        self.verticalLayout_6.addWidget(self.chkNotPlanned)
        self.chkNotExported = QtGui.QCheckBox(self.groupBox)
        self.chkNotExported.setChecked(True)
        self.chkNotExported.setObjectName(_fromUtf8("chkNotExported"))
        self.verticalLayout_6.addWidget(self.chkNotExported)
        self.chkExportedSuccessfully = QtGui.QCheckBox(self.groupBox)
        self.chkExportedSuccessfully.setChecked(False)
        self.chkExportedSuccessfully.setObjectName(_fromUtf8("chkExportedSuccessfully"))
        self.verticalLayout_6.addWidget(self.chkExportedSuccessfully)
        self.chkExportedWithErrors = QtGui.QCheckBox(self.groupBox)
        self.chkExportedWithErrors.setChecked(False)
        self.chkExportedWithErrors.setObjectName(_fromUtf8("chkExportedWithErrors"))
        self.verticalLayout_6.addWidget(self.chkExportedWithErrors)
        self.cmbExportedWithErrors = CRecordMultivalueComboBox(self.groupBox)
        self.cmbExportedWithErrors.setObjectName(_fromUtf8("cmbExportedWithErrors"))
        self.verticalLayout_6.addWidget(self.cmbExportedWithErrors)
        self.chkHideSuccess = QtGui.QCheckBox(self.groupBox)
        self.chkHideSuccess.setObjectName(_fromUtf8("chkHideSuccess"))
        self.verticalLayout_6.addWidget(self.chkHideSuccess)
        self.lblDispPassed = QtGui.QLabel(self.groupBox)
        self.lblDispPassed.setObjectName(_fromUtf8("lblDispPassed"))
        self.verticalLayout_6.addWidget(self.lblDispPassed)
        self.cmbDispPassed = QtGui.QComboBox(self.groupBox)
        self.cmbDispPassed.setObjectName(_fromUtf8("cmbDispPassed"))
        self.cmbDispPassed.addItem(_fromUtf8(""))
        self.cmbDispPassed.addItem(_fromUtf8(""))
        self.cmbDispPassed.addItem(_fromUtf8(""))
        self.verticalLayout_6.addWidget(self.cmbDispPassed)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnResetFilter = QtGui.QPushButton(self.groupBox)
        self.btnResetFilter.setObjectName(_fromUtf8("btnResetFilter"))
        self.horizontalLayout_3.addWidget(self.btnResetFilter)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnApplyFilter = QtGui.QPushButton(self.groupBox)
        self.btnApplyFilter.setObjectName(_fromUtf8("btnApplyFilter"))
        self.horizontalLayout_3.addWidget(self.btnApplyFilter)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.btnShowReport = QtGui.QPushButton(self.groupBox)
        self.btnShowReport.setObjectName(_fromUtf8("btnShowReport"))
        self.verticalLayout_6.addWidget(self.btnShowReport)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.btnPlanningProfilactic = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnPlanningProfilactic.setObjectName(_fromUtf8("btnPlanningProfilactic"))
        self.verticalLayout_3.addWidget(self.btnPlanningProfilactic)
        self.btnPutEvPlanList = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnPutEvPlanList.setObjectName(_fromUtf8("btnPutEvPlanList"))
        self.verticalLayout_3.addWidget(self.btnPutEvPlanList)
        self.btnGetEvFactInfos = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnGetEvFactInfos.setObjectName(_fromUtf8("btnGetEvFactInfos"))
        self.verticalLayout_3.addWidget(self.btnGetEvFactInfos)
        self.btnGetEvFactInvcs = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnGetEvFactInvcs.setObjectName(_fromUtf8("btnGetEvFactInvcs"))
        self.verticalLayout_3.addWidget(self.btnGetEvFactInvcs)
        self.btnGetEvPlanQtys = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnGetEvPlanQtys.setObjectName(_fromUtf8("btnGetEvPlanQtys"))
        self.verticalLayout_3.addWidget(self.btnGetEvPlanQtys)
        self.btnPutEvContacts = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnPutEvContacts.setObjectName(_fromUtf8("btnPutEvContacts"))
        self.verticalLayout_3.addWidget(self.btnPutEvContacts)
        self.btnPutEvPlanDates = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnPutEvPlanDates.setObjectName(_fromUtf8("btnPutEvPlanDates"))
        self.verticalLayout_3.addWidget(self.btnPutEvPlanDates)
        self.btnExportedPlan = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnExportedPlan.setObjectName(_fromUtf8("btnExportedPlan"))
        self.verticalLayout_3.addWidget(self.btnExportedPlan)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(DispExchangeProfilacticPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.chkExportedWithErrors, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbExportedWithErrors.setVisible)
        QtCore.QMetaObject.connectSlotsByName(DispExchangeProfilacticPage)
        DispExchangeProfilacticPage.setTabOrder(self.scrollArea, self.tblClients)
        DispExchangeProfilacticPage.setTabOrder(self.tblClients, self.tabWidget)
        DispExchangeProfilacticPage.setTabOrder(self.tabWidget, self.tblPlanExportErrors)
        DispExchangeProfilacticPage.setTabOrder(self.tblPlanExportErrors, self.tblFactInfos)
        DispExchangeProfilacticPage.setTabOrder(self.tblFactInfos, self.tblFactInvcs)
        DispExchangeProfilacticPage.setTabOrder(self.tblFactInvcs, self.cmbKind)
        DispExchangeProfilacticPage.setTabOrder(self.cmbKind, self.sbYear)
        DispExchangeProfilacticPage.setTabOrder(self.sbYear, self.cmbMonth)
        DispExchangeProfilacticPage.setTabOrder(self.cmbMonth, self.chkFilterLastName)
        DispExchangeProfilacticPage.setTabOrder(self.chkFilterLastName, self.edtFilterLastName)
        DispExchangeProfilacticPage.setTabOrder(self.edtFilterLastName, self.chkFilterFirstName)
        DispExchangeProfilacticPage.setTabOrder(self.chkFilterFirstName, self.edtFilterFirstName)
        DispExchangeProfilacticPage.setTabOrder(self.edtFilterFirstName, self.chkFilterPatrName)
        DispExchangeProfilacticPage.setTabOrder(self.chkFilterPatrName, self.edtFilterPatrName)
        DispExchangeProfilacticPage.setTabOrder(self.edtFilterPatrName, self.chkFilterBirthDay)
        DispExchangeProfilacticPage.setTabOrder(self.chkFilterBirthDay, self.edtFilterBirthDay)
        DispExchangeProfilacticPage.setTabOrder(self.edtFilterBirthDay, self.chkFilterEndBirthDay)
        DispExchangeProfilacticPage.setTabOrder(self.chkFilterEndBirthDay, self.edtFilterEndBirthDay)
        DispExchangeProfilacticPage.setTabOrder(self.edtFilterEndBirthDay, self.chkFilterAddressOrgStructure)
        DispExchangeProfilacticPage.setTabOrder(self.chkFilterAddressOrgStructure, self.cmbFilterAddressOrgStructure)
        DispExchangeProfilacticPage.setTabOrder(self.cmbFilterAddressOrgStructure, self.chkFilterSex)
        DispExchangeProfilacticPage.setTabOrder(self.chkFilterSex, self.cmbFilterSex)
        DispExchangeProfilacticPage.setTabOrder(self.cmbFilterSex, self.cmbBusyness)
        DispExchangeProfilacticPage.setTabOrder(self.cmbBusyness, self.chkSocStatuses)
        DispExchangeProfilacticPage.setTabOrder(self.chkSocStatuses, self.chkSocStatusesCondition)
        DispExchangeProfilacticPage.setTabOrder(self.chkSocStatusesCondition, self.edtFilterSocStatusesBegDate)
        DispExchangeProfilacticPage.setTabOrder(self.edtFilterSocStatusesBegDate, self.edtFilterSocStatusesEndDate)
        DispExchangeProfilacticPage.setTabOrder(self.edtFilterSocStatusesEndDate, self.cmbSocStatusesClass)
        DispExchangeProfilacticPage.setTabOrder(self.cmbSocStatusesClass, self.cmbSocStatusesType)
        DispExchangeProfilacticPage.setTabOrder(self.cmbSocStatusesType, self.chkForPlanning)
        DispExchangeProfilacticPage.setTabOrder(self.chkForPlanning, self.chkHideUDEvents)
        DispExchangeProfilacticPage.setTabOrder(self.chkHideUDEvents, self.chkNotPlanned)
        DispExchangeProfilacticPage.setTabOrder(self.chkNotPlanned, self.chkNotExported)
        DispExchangeProfilacticPage.setTabOrder(self.chkNotExported, self.chkExportedSuccessfully)
        DispExchangeProfilacticPage.setTabOrder(self.chkExportedSuccessfully, self.chkExportedWithErrors)
        DispExchangeProfilacticPage.setTabOrder(self.chkExportedWithErrors, self.cmbExportedWithErrors)
        DispExchangeProfilacticPage.setTabOrder(self.cmbExportedWithErrors, self.chkHideSuccess)
        DispExchangeProfilacticPage.setTabOrder(self.chkHideSuccess, self.cmbDispPassed)
        DispExchangeProfilacticPage.setTabOrder(self.cmbDispPassed, self.btnResetFilter)
        DispExchangeProfilacticPage.setTabOrder(self.btnResetFilter, self.btnApplyFilter)
        DispExchangeProfilacticPage.setTabOrder(self.btnApplyFilter, self.btnShowReport)
        DispExchangeProfilacticPage.setTabOrder(self.btnShowReport, self.btnPlanningProfilactic)
        DispExchangeProfilacticPage.setTabOrder(self.btnPlanningProfilactic, self.btnPutEvPlanList)
        DispExchangeProfilacticPage.setTabOrder(self.btnPutEvPlanList, self.btnGetEvFactInfos)
        DispExchangeProfilacticPage.setTabOrder(self.btnGetEvFactInfos, self.btnGetEvFactInvcs)
        DispExchangeProfilacticPage.setTabOrder(self.btnGetEvFactInvcs, self.btnGetEvPlanQtys)
        DispExchangeProfilacticPage.setTabOrder(self.btnGetEvPlanQtys, self.btnPutEvContacts)
        DispExchangeProfilacticPage.setTabOrder(self.btnPutEvContacts, self.btnPutEvPlanDates)
        DispExchangeProfilacticPage.setTabOrder(self.btnPutEvPlanDates, self.btnExportedPlan)

    def retranslateUi(self, DispExchangeProfilacticPage):
        DispExchangeProfilacticPage.setWindowTitle(_translate("DispExchangeProfilacticPage", "Проф. мероприятия", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPlanExportErrors), _translate("DispExchangeProfilacticPage", "Ошибки", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFactInfos), _translate("DispExchangeProfilacticPage", "Информирование", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFactInvcs), _translate("DispExchangeProfilacticPage", "Счета", None))
        self.lblClientsCount.setText(_translate("DispExchangeProfilacticPage", "Список пуст", None))
        self.groupBox.setTitle(_translate("DispExchangeProfilacticPage", "Фильтр", None))
        self.label_2.setText(_translate("DispExchangeProfilacticPage", "Месяц", None))
        self.cmbKind.setItemText(0, _translate("DispExchangeProfilacticPage", "все", None))
        self.cmbKind.setItemText(1, _translate("DispExchangeProfilacticPage", "диспансеризация раз в 3 года", None))
        self.cmbKind.setItemText(2, _translate("DispExchangeProfilacticPage", "диспансеризация раз в 2 года", None))
        self.cmbKind.setItemText(3, _translate("DispExchangeProfilacticPage", "профосмотр", None))
        self.cmbKind.setItemText(4, _translate("DispExchangeProfilacticPage", "диспансеризация ежегодная", None))
        self.cmbKind.setItemText(5, _translate("DispExchangeProfilacticPage", "диспансеризация углубленная (группа 1)", None))
        self.cmbKind.setItemText(6, _translate("DispExchangeProfilacticPage", "диспансеризация углубленная (группа 2)", None))
        self.label_3.setText(_translate("DispExchangeProfilacticPage", "Вид осмотра", None))
        self.label.setText(_translate("DispExchangeProfilacticPage", "Год", None))
        self.cmbMonth.setItemText(0, _translate("DispExchangeProfilacticPage", "все", None))
        self.cmbMonth.setItemText(1, _translate("DispExchangeProfilacticPage", "январь", None))
        self.cmbMonth.setItemText(2, _translate("DispExchangeProfilacticPage", "февраль", None))
        self.cmbMonth.setItemText(3, _translate("DispExchangeProfilacticPage", "март", None))
        self.cmbMonth.setItemText(4, _translate("DispExchangeProfilacticPage", "апрель", None))
        self.cmbMonth.setItemText(5, _translate("DispExchangeProfilacticPage", "май", None))
        self.cmbMonth.setItemText(6, _translate("DispExchangeProfilacticPage", "июнь", None))
        self.cmbMonth.setItemText(7, _translate("DispExchangeProfilacticPage", "июль", None))
        self.cmbMonth.setItemText(8, _translate("DispExchangeProfilacticPage", "август", None))
        self.cmbMonth.setItemText(9, _translate("DispExchangeProfilacticPage", "сентябрь", None))
        self.cmbMonth.setItemText(10, _translate("DispExchangeProfilacticPage", "октябрь", None))
        self.cmbMonth.setItemText(11, _translate("DispExchangeProfilacticPage", "ноябрь", None))
        self.cmbMonth.setItemText(12, _translate("DispExchangeProfilacticPage", "декабрь", None))
        self.chkFilterLastName.setText(_translate("DispExchangeProfilacticPage", "Фамилия", None))
        self.chkFilterFirstName.setText(_translate("DispExchangeProfilacticPage", "Имя", None))
        self.chkFilterPatrName.setText(_translate("DispExchangeProfilacticPage", "Отчество", None))
        self.chkFilterBirthDay.setText(_translate("DispExchangeProfilacticPage", "Дата рожд", None))
        self.chkFilterEndBirthDay.setText(_translate("DispExchangeProfilacticPage", "по", None))
        self.chkFilterAddressOrgStructure.setText(_translate("DispExchangeProfilacticPage", "По участку", None))
        self.chkFilterSex.setText(_translate("DispExchangeProfilacticPage", "Пол", None))
        self.cmbFilterSex.setItemText(1, _translate("DispExchangeProfilacticPage", "М", None))
        self.cmbFilterSex.setItemText(2, _translate("DispExchangeProfilacticPage", "Ж", None))
        self.lblBusyness.setText(_translate("DispExchangeProfilacticPage", "Занятость", None))
        self.cmbBusyness.setItemText(1, _translate("DispExchangeProfilacticPage", "работающие", None))
        self.cmbBusyness.setItemText(2, _translate("DispExchangeProfilacticPage", "неработающие", None))
        self.chkSocStatuses.setText(_translate("DispExchangeProfilacticPage", "Соц.статус", None))
        self.chkSocStatusesCondition.setText(_translate("DispExchangeProfilacticPage", "Не имеет соц.статуса", None))
        self.lblFilterSocStatusesBegDate.setText(_translate("DispExchangeProfilacticPage", "С", None))
        self.lblFilterSocStatusesEndDate.setText(_translate("DispExchangeProfilacticPage", "по", None))
        self.chkForPlanning.setText(_translate("DispExchangeProfilacticPage", "Подлежащие планированию", None))
        self.chkHideUDEvents.setText(_translate("DispExchangeProfilacticPage", "Скрыть прошедших УД", None))
        self.chkNotPlanned.setText(_translate("DispExchangeProfilacticPage", "Не запланированные", None))
        self.chkNotExported.setText(_translate("DispExchangeProfilacticPage", "Запланированные, не отправленные", None))
        self.chkExportedSuccessfully.setText(_translate("DispExchangeProfilacticPage", "Отправленные успешно", None))
        self.chkExportedWithErrors.setText(_translate("DispExchangeProfilacticPage", "Отправленные с ошибками", None))
        self.chkHideSuccess.setText(_translate("DispExchangeProfilacticPage", "Скрывать успешно отправленные", None))
        self.lblDispPassed.setText(_translate("DispExchangeProfilacticPage", "Прохождение дисп./проф.", None))
        self.cmbDispPassed.setItemText(0, _translate("DispExchangeProfilacticPage", "Все", None))
        self.cmbDispPassed.setItemText(1, _translate("DispExchangeProfilacticPage", "Прошедшие", None))
        self.cmbDispPassed.setItemText(2, _translate("DispExchangeProfilacticPage", "Непрошедшие", None))
        self.btnResetFilter.setText(_translate("DispExchangeProfilacticPage", "Сбросить", None))
        self.btnApplyFilter.setText(_translate("DispExchangeProfilacticPage", "Применить", None))
        self.btnShowReport.setText(_translate("DispExchangeProfilacticPage", "Печать списка", None))
        self.btnPlanningProfilactic.setText(_translate("DispExchangeProfilacticPage", "Планирование мероприятий", None))
        self.btnPutEvPlanList.setText(_translate("DispExchangeProfilacticPage", "Экспорт списка лиц", None))
        self.btnGetEvFactInfos.setText(_translate("DispExchangeProfilacticPage", "Импорт статуса информирования", None))
        self.btnGetEvFactInvcs.setText(_translate("DispExchangeProfilacticPage", "Импорт оплаченных счетов", None))
        self.btnGetEvPlanQtys.setText(_translate("DispExchangeProfilacticPage", "Плановые объемы", None))
        self.btnPutEvContacts.setText(_translate("DispExchangeProfilacticPage", "Список контактов", None))
        self.btnPutEvPlanDates.setText(_translate("DispExchangeProfilacticPage", "Даты планируемых мероприятий", None))
        self.btnExportedPlan.setText(_translate("DispExchangeProfilacticPage", "Список планирования ТФОМС", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Registry.SocStatusComboBox import CSocStatusComboBox
from library.DateEdit import CDateEdit
from library.MultivalueComboBox import CRecordMultivalueComboBox
from library.TableView import CTableView
from library.crbcombobox import CRBComboBox
