# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\Samson\UP_s11\client\Registry\DistantMonitoringEventEditDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DistantMonitoringEventEditDialog(object):
    def setupUi(self, DistantMonitoringEventEditDialog):
        DistantMonitoringEventEditDialog.setObjectName(_fromUtf8("DistantMonitoringEventEditDialog"))
        DistantMonitoringEventEditDialog.resize(508, 423)
        self.gridLayout = QtGui.QGridLayout(DistantMonitoringEventEditDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbEquipment = CRBComboBox(DistantMonitoringEventEditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEquipment.sizePolicy().hasHeightForWidth())
        self.cmbEquipment.setSizePolicy(sizePolicy)
        self.cmbEquipment.setObjectName(_fromUtf8("cmbEquipment"))
        self.gridLayout.addWidget(self.cmbEquipment, 5, 1, 1, 2)
        self.lblPerson = QtGui.QLabel(DistantMonitoringEventEditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPerson.sizePolicy().hasHeightForWidth())
        self.lblPerson.setSizePolicy(sizePolicy)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 2, 0, 1, 1)
        self.cmbObservationGroup = QtGui.QComboBox(DistantMonitoringEventEditDialog)
        self.cmbObservationGroup.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbObservationGroup.sizePolicy().hasHeightForWidth())
        self.cmbObservationGroup.setSizePolicy(sizePolicy)
        self.cmbObservationGroup.setObjectName(_fromUtf8("cmbObservationGroup"))
        self.gridLayout.addWidget(self.cmbObservationGroup, 6, 1, 1, 2)
        self.edtSetDate = CDateEdit(DistantMonitoringEventEditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSetDate.sizePolicy().hasHeightForWidth())
        self.edtSetDate.setSizePolicy(sizePolicy)
        self.edtSetDate.setCalendarPopup(True)
        self.edtSetDate.setObjectName(_fromUtf8("edtSetDate"))
        self.gridLayout.addWidget(self.edtSetDate, 3, 2, 1, 1)
        self.lblEquipment = QtGui.QLabel(DistantMonitoringEventEditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEquipment.sizePolicy().hasHeightForWidth())
        self.lblEquipment.setSizePolicy(sizePolicy)
        self.lblEquipment.setObjectName(_fromUtf8("lblEquipment"))
        self.gridLayout.addWidget(self.lblEquipment, 5, 0, 1, 1)
        self.lblObservationGroup = QtGui.QLabel(DistantMonitoringEventEditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblObservationGroup.sizePolicy().hasHeightForWidth())
        self.lblObservationGroup.setSizePolicy(sizePolicy)
        self.lblObservationGroup.setObjectName(_fromUtf8("lblObservationGroup"))
        self.gridLayout.addWidget(self.lblObservationGroup, 6, 0, 1, 1)
        self.lblClient = QtGui.QLabel(DistantMonitoringEventEditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClient.sizePolicy().hasHeightForWidth())
        self.lblClient.setSizePolicy(sizePolicy)
        self.lblClient.setObjectName(_fromUtf8("lblClient"))
        self.gridLayout.addWidget(self.lblClient, 1, 0, 1, 1)
        self.edtComment = QtGui.QPlainTextEdit(DistantMonitoringEventEditDialog)
        self.edtComment.setObjectName(_fromUtf8("edtComment"))
        self.gridLayout.addWidget(self.edtComment, 8, 0, 1, 3)
        self.cmbPerson = CPersonComboBox(DistantMonitoringEventEditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPerson.sizePolicy().hasHeightForWidth())
        self.cmbPerson.setSizePolicy(sizePolicy)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 2, 1, 1, 2)
        self.lblComment = QtGui.QLabel(DistantMonitoringEventEditDialog)
        self.lblComment.setObjectName(_fromUtf8("lblComment"))
        self.gridLayout.addWidget(self.lblComment, 7, 0, 1, 3)
        self.cmbClient = CClientComboBox(DistantMonitoringEventEditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbClient.sizePolicy().hasHeightForWidth())
        self.cmbClient.setSizePolicy(sizePolicy)
        self.cmbClient.setObjectName(_fromUtf8("cmbClient"))
        self.gridLayout.addWidget(self.cmbClient, 1, 1, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(DistantMonitoringEventEditDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 9, 0, 1, 3)
        self.lblSetDate = QtGui.QLabel(DistantMonitoringEventEditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSetDate.sizePolicy().hasHeightForWidth())
        self.lblSetDate.setSizePolicy(sizePolicy)
        self.lblSetDate.setObjectName(_fromUtf8("lblSetDate"))
        self.gridLayout.addWidget(self.lblSetDate, 3, 0, 1, 2)
        self.lblEquipmentStatus = QtGui.QLabel(DistantMonitoringEventEditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEquipmentStatus.sizePolicy().hasHeightForWidth())
        self.lblEquipmentStatus.setSizePolicy(sizePolicy)
        self.lblEquipmentStatus.setObjectName(_fromUtf8("lblEquipmentStatus"))
        self.gridLayout.addWidget(self.lblEquipmentStatus, 0, 0, 1, 2)
        self.lblEquipmentStatusText = QtGui.QLabel(DistantMonitoringEventEditDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblEquipmentStatusText.setFont(font)
        self.lblEquipmentStatusText.setText(_fromUtf8(""))
        self.lblEquipmentStatusText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblEquipmentStatusText.setObjectName(_fromUtf8("lblEquipmentStatusText"))
        self.gridLayout.addWidget(self.lblEquipmentStatusText, 0, 2, 1, 1)
        self.lblProgramType = QtGui.QLabel(DistantMonitoringEventEditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProgramType.sizePolicy().hasHeightForWidth())
        self.lblProgramType.setSizePolicy(sizePolicy)
        self.lblProgramType.setObjectName(_fromUtf8("lblProgramType"))
        self.gridLayout.addWidget(self.lblProgramType, 4, 0, 1, 1)
        self.lblProgramTypeText = QtGui.QLabel(DistantMonitoringEventEditDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblProgramTypeText.setFont(font)
        self.lblProgramTypeText.setText(_fromUtf8(""))
        self.lblProgramTypeText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblProgramTypeText.setObjectName(_fromUtf8("lblProgramTypeText"))
        self.gridLayout.addWidget(self.lblProgramTypeText, 4, 1, 1, 2)

        self.retranslateUi(DistantMonitoringEventEditDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DistantMonitoringEventEditDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DistantMonitoringEventEditDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DistantMonitoringEventEditDialog)

    def retranslateUi(self, DistantMonitoringEventEditDialog):
        DistantMonitoringEventEditDialog.setWindowTitle(_translate("DistantMonitoringEventEditDialog", "Программа ДН", None))
        self.lblPerson.setText(_translate("DistantMonitoringEventEditDialog", "Лечащий врач", None))
        self.edtSetDate.setDisplayFormat(_translate("DistantMonitoringEventEditDialog", "dd.MM.yyyy", None))
        self.lblEquipment.setText(_translate("DistantMonitoringEventEditDialog", "Модель прибора ДН", None))
        self.lblObservationGroup.setText(_translate("DistantMonitoringEventEditDialog", "Группа наблюдения", None))
        self.lblClient.setText(_translate("DistantMonitoringEventEditDialog", "Пациент", None))
        self.lblComment.setText(_translate("DistantMonitoringEventEditDialog", "Комментарий", None))
        self.lblSetDate.setText(_translate("DistantMonitoringEventEditDialog", "Дата начала программы ДН", None))
        self.lblEquipmentStatus.setText(_translate("DistantMonitoringEventEditDialog", "Действия с оборудованием", None))
        self.lblProgramType.setText(_translate("DistantMonitoringEventEditDialog", "Программа ДН", None))

from Orgs.PersonComboBox import CPersonComboBox
from library.ClientComboBox import CClientComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
