# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/Registry/FreeQueueDockContent.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(221, 741)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setContentsMargins(1, 2, 1, 2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblReservedOrder = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblReservedOrder.setFont(font)
        self.lblReservedOrder.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.lblReservedOrder.setText(_fromUtf8(""))
        self.lblReservedOrder.setObjectName(_fromUtf8("lblReservedOrder"))
        self.gridLayout.addWidget(self.lblReservedOrder, 9, 3, 1, 1)
        self.edtBegTime = QtGui.QTimeEdit(Form)
        self.edtBegTime.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegTime.sizePolicy().hasHeightForWidth())
        self.edtBegTime.setSizePolicy(sizePolicy)
        self.edtBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.edtBegTime.setTime(QtCore.QTime(0, 0, 0))
        self.edtBegTime.setCalendarPopup(False)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.gridLayout.addWidget(self.edtBegTime, 4, 1, 1, 1)
        self.grpBox = QtGui.QWidget(Form)
        self.grpBox.setObjectName(_fromUtf8("grpBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.grpBox)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(self.grpBox)
        self.splitter.setLineWidth(1)
        self.splitter.setMidLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeOrgStructure = CTreeView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.treeOrgStructure.sizePolicy().hasHeightForWidth())
        self.treeOrgStructure.setSizePolicy(sizePolicy)
        self.treeOrgStructure.setObjectName(_fromUtf8("treeOrgStructure"))
        self.treeOrgPersonnel = CTreeView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.treeOrgPersonnel.sizePolicy().hasHeightForWidth())
        self.treeOrgPersonnel.setSizePolicy(sizePolicy)
        self.treeOrgPersonnel.setObjectName(_fromUtf8("treeOrgPersonnel"))
        self.tblAmbQueue = CFreeQueueTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.tblAmbQueue.sizePolicy().hasHeightForWidth())
        self.tblAmbQueue.setSizePolicy(sizePolicy)
        self.tblAmbQueue.setObjectName(_fromUtf8("tblAmbQueue"))
        self.verticalLayout.addWidget(self.splitter)
        self.gridLayout.addWidget(self.grpBox, 8, 0, 1, 5)
        self.lblQueueItemsCount = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblQueueItemsCount.sizePolicy().hasHeightForWidth())
        self.lblQueueItemsCount.setSizePolicy(sizePolicy)
        self.lblQueueItemsCount.setScaledContents(False)
        self.lblQueueItemsCount.setObjectName(_fromUtf8("lblQueueItemsCount"))
        self.gridLayout.addWidget(self.lblQueueItemsCount, 9, 0, 1, 3)
        self.lblBegDate = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 2, 0, 1, 1)
        self.edtBegDate = CDateEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 2, 1, 1, 2)
        self.chkEnableTime = QtGui.QCheckBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkEnableTime.sizePolicy().hasHeightForWidth())
        self.chkEnableTime.setSizePolicy(sizePolicy)
        self.chkEnableTime.setObjectName(_fromUtf8("chkEnableTime"))
        self.gridLayout.addWidget(self.chkEnableTime, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 9, 4, 1, 1)
        self.lblCountTickets = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCountTickets.sizePolicy().hasHeightForWidth())
        self.lblCountTickets.setSizePolicy(sizePolicy)
        self.lblCountTickets.setObjectName(_fromUtf8("lblCountTickets"))
        self.gridLayout.addWidget(self.lblCountTickets, 7, 0, 1, 1)
        self.edtCountTickets = QtGui.QSpinBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCountTickets.sizePolicy().hasHeightForWidth())
        self.edtCountTickets.setSizePolicy(sizePolicy)
        self.edtCountTickets.setMinimum(1)
        self.edtCountTickets.setMaximum(9)
        self.edtCountTickets.setObjectName(_fromUtf8("edtCountTickets"))
        self.gridLayout.addWidget(self.edtCountTickets, 7, 1, 1, 1)
        self.btnSetToday = QtGui.QToolButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetToday.sizePolicy().hasHeightForWidth())
        self.btnSetToday.setSizePolicy(sizePolicy)
        self.btnSetToday.setArrowType(QtCore.Qt.NoArrow)
        self.btnSetToday.setObjectName(_fromUtf8("btnSetToday"))
        self.gridLayout.addWidget(self.btnSetToday, 2, 3, 1, 1)
        self.edtEndTime = QtGui.QTimeEdit(Form)
        self.edtEndTime.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndTime.sizePolicy().hasHeightForWidth())
        self.edtEndTime.setSizePolicy(sizePolicy)
        self.edtEndTime.setTime(QtCore.QTime(23, 59, 0))
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.gridLayout.addWidget(self.edtEndTime, 5, 1, 1, 1)
        self.lblEndTime = QtGui.QLabel(Form)
        self.lblEndTime.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndTime.sizePolicy().hasHeightForWidth())
        self.lblEndTime.setSizePolicy(sizePolicy)
        self.lblEndTime.setObjectName(_fromUtf8("lblEndTime"))
        self.gridLayout.addWidget(self.lblEndTime, 5, 0, 1, 1)
        self.chkEnableAppointmentPurpose = QtGui.QCheckBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkEnableAppointmentPurpose.sizePolicy().hasHeightForWidth())
        self.chkEnableAppointmentPurpose.setSizePolicy(sizePolicy)
        self.chkEnableAppointmentPurpose.setObjectName(_fromUtf8("chkEnableAppointmentPurpose"))
        self.gridLayout.addWidget(self.chkEnableAppointmentPurpose, 1, 0, 1, 1)
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cmbAppointmentPurpose = CRBComboBox(Form)
        self.cmbAppointmentPurpose.setEnabled(False)
        self.cmbAppointmentPurpose.setObjectName(_fromUtf8("cmbAppointmentPurpose"))
        self.gridLayout.addWidget(self.cmbAppointmentPurpose, 1, 1, 1, 4)
        self.cmbAppointmentType = CEnumComboBox(Form)
        self.cmbAppointmentType.setObjectName(_fromUtf8("cmbAppointmentType"))
        self.gridLayout.addWidget(self.cmbAppointmentType, 0, 1, 1, 4)
        self.btnUpdateItems = QtGui.QToolButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUpdateItems.sizePolicy().hasHeightForWidth())
        self.btnUpdateItems.setSizePolicy(sizePolicy)
        self.btnUpdateItems.setText(_fromUtf8(""))
        self.btnUpdateItems.setObjectName(_fromUtf8("btnUpdateItems"))
        self.gridLayout.addWidget(self.btnUpdateItems, 2, 4, 1, 1)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblCountTickets.setBuddy(self.edtCountTickets)
        self.lblEndTime.setBuddy(self.edtEndTime)
        self.label.setBuddy(self.cmbAppointmentType)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.chkEnableTime, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegTime.setEnabled)
        QtCore.QObject.connect(self.chkEnableTime, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndTime.setEnabled)
        QtCore.QObject.connect(self.chkEnableAppointmentPurpose, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbAppointmentPurpose.setEnabled)
        QtCore.QObject.connect(self.chkEnableTime, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblEndTime.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.cmbAppointmentType, self.chkEnableAppointmentPurpose)
        Form.setTabOrder(self.chkEnableAppointmentPurpose, self.cmbAppointmentPurpose)
        Form.setTabOrder(self.cmbAppointmentPurpose, self.edtBegDate)
        Form.setTabOrder(self.edtBegDate, self.btnSetToday)
        Form.setTabOrder(self.btnSetToday, self.chkEnableTime)
        Form.setTabOrder(self.chkEnableTime, self.edtBegTime)
        Form.setTabOrder(self.edtBegTime, self.edtEndTime)
        Form.setTabOrder(self.edtEndTime, self.edtCountTickets)
        Form.setTabOrder(self.edtCountTickets, self.treeOrgStructure)
        Form.setTabOrder(self.treeOrgStructure, self.treeOrgPersonnel)
        Form.setTabOrder(self.treeOrgPersonnel, self.tblAmbQueue)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.edtBegTime.setDisplayFormat(_translate("Form", "HH:mm", None))
        self.lblQueueItemsCount.setText(_translate("Form", "Список пуст", None))
        self.lblBegDate.setText(_translate("Form", "&Дата", None))
        self.chkEnableTime.setText(_translate("Form", "&Время с", None))
        self.lblCountTickets.setText(_translate("Form", "&Подряд", None))
        self.btnSetToday.setToolTip(_translate("Form", "<html><head/><body><p>сегодня</p></body></html>", None))
        self.btnSetToday.setText(_translate("Form", "⌫", None))
        self.edtEndTime.setDisplayFormat(_translate("Form", "HH:mm", None))
        self.lblEndTime.setText(_translate("Form", "&по", None))
        self.chkEnableAppointmentPurpose.setText(_translate("Form", "&Назначение", None))
        self.label.setText(_translate("Form", "&Тип приёма", None))
        self.btnUpdateItems.setToolTip(_translate("Form", "Обновить список номерков", None))

from FreeQueueTableView import CFreeQueueTableView
from library.TreeView import CTreeView
from library.ROComboBox import CEnumComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox