# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Projects\Samson\client_test\Registry\MyDoctorArea.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MyDoctorArea(object):
    def setupUi(self, MyDoctorArea):
        MyDoctorArea.setObjectName(_fromUtf8("MyDoctorArea"))
        MyDoctorArea.resize(982, 638)
        self.gridLayout_2 = QtGui.QGridLayout(MyDoctorArea)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblMyAreas = QtGui.QLabel(MyDoctorArea)
        self.lblMyAreas.setWordWrap(True)
        self.lblMyAreas.setObjectName(_fromUtf8("lblMyAreas"))
        self.horizontalLayout_3.addWidget(self.lblMyAreas)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblOrgStructure = QtGui.QLabel(MyDoctorArea)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.horizontalLayout.addWidget(self.lblOrgStructure)
        self.cmbOrgStructure = CAreaComboBox(MyDoctorArea)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructure.setSizePolicy(sizePolicy)
        self.cmbOrgStructure.setMinimumSize(QtCore.QSize(200, 0))
        self.cmbOrgStructure.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.horizontalLayout.addWidget(self.cmbOrgStructure)
        self.lblDate = QtGui.QLabel(MyDoctorArea)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.horizontalLayout.addWidget(self.lblDate)
        self.edtDate = CDateEdit(MyDoctorArea)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.horizontalLayout.addWidget(self.edtDate)
        self.btnApply = QtGui.QPushButton(MyDoctorArea)
        self.btnApply.setObjectName(_fromUtf8("btnApply"))
        self.horizontalLayout.addWidget(self.btnApply)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnNotifications = QtGui.QPushButton(MyDoctorArea)
        self.btnNotifications.setObjectName(_fromUtf8("btnNotifications"))
        self.horizontalLayout_2.addWidget(self.btnNotifications)
        self.btnDoctorPortal = QtGui.QPushButton(MyDoctorArea)
        self.btnDoctorPortal.setObjectName(_fromUtf8("btnDoctorPortal"))
        self.horizontalLayout_2.addWidget(self.btnDoctorPortal)
        self.btnAmbulatoryCard = QtGui.QPushButton(MyDoctorArea)
        self.btnAmbulatoryCard.setObjectName(_fromUtf8("btnAmbulatoryCard"))
        self.horizontalLayout_2.addWidget(self.btnAmbulatoryCard)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.setStretch(0, 2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.horizontalLayout_Radio = QtGui.QHBoxLayout()
        self.horizontalLayout_Radio.setObjectName(_fromUtf8("horizontalLayout_Radio"))
        self.groupBox_Observed = QtGui.QGroupBox(MyDoctorArea)
        self.groupBox_Observed.setObjectName(_fromUtf8("groupBox_Observed"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_Observed)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.chkMyObserved = QtGui.QRadioButton(self.groupBox_Observed)
        self.chkMyObserved.setObjectName(_fromUtf8("chkMyObserved"))
        self.horizontalLayout_4.addWidget(self.chkMyObserved)
        self.chkOrgStrObserved = QtGui.QRadioButton(self.groupBox_Observed)
        self.chkOrgStrObserved.setObjectName(_fromUtf8("chkOrgStrObserved"))
        self.horizontalLayout_4.addWidget(self.chkOrgStrObserved)
        self.chkSpecObserved = QtGui.QRadioButton(self.groupBox_Observed)
        self.chkSpecObserved.setObjectName(_fromUtf8("chkSpecObserved"))
        self.horizontalLayout_4.addWidget(self.chkSpecObserved)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_Radio.addWidget(self.groupBox_Observed)
        self.gridLayout_2.addLayout(self.horizontalLayout_Radio, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblEmergency = QtGui.QLabel(MyDoctorArea)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEmergency.sizePolicy().hasHeightForWidth())
        self.lblEmergency.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.lblEmergency.setFont(font)
        self.lblEmergency.setObjectName(_fromUtf8("lblEmergency"))
        self.gridLayout.addWidget(self.lblEmergency, 0, 0, 1, 1)
        self.tblEmergencyCalls = CInDocTableView(MyDoctorArea)
        self.tblEmergencyCalls.setObjectName(_fromUtf8("tblEmergencyCalls"))
        self.gridLayout.addWidget(self.tblEmergencyCalls, 2, 0, 1, 5)
        self.chkSMPColor = QtGui.QCheckBox(MyDoctorArea)
        self.chkSMPColor.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSMPColor.sizePolicy().hasHeightForWidth())
        self.chkSMPColor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chkSMPColor.setFont(font)
        self.chkSMPColor.setCheckable(False)
        self.chkSMPColor.setObjectName(_fromUtf8("chkSMPColor"))
        self.gridLayout.addWidget(self.chkSMPColor, 0, 3, 1, 1)
        self.chkNMPColor = QtGui.QCheckBox(MyDoctorArea)
        self.chkNMPColor.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkNMPColor.sizePolicy().hasHeightForWidth())
        self.chkNMPColor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chkNMPColor.setFont(font)
        self.chkNMPColor.setCheckable(False)
        self.chkNMPColor.setObjectName(_fromUtf8("chkNMPColor"))
        self.gridLayout.addWidget(self.chkNMPColor, 0, 2, 1, 1)
        self.chkSMPActiveColor = QtGui.QCheckBox(MyDoctorArea)
        self.chkSMPActiveColor.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSMPActiveColor.sizePolicy().hasHeightForWidth())
        self.chkSMPActiveColor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chkSMPActiveColor.setFont(font)
        self.chkSMPActiveColor.setCheckable(False)
        self.chkSMPActiveColor.setObjectName(_fromUtf8("chkSMPActiveColor"))
        self.gridLayout.addWidget(self.chkSMPActiveColor, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(MyDoctorArea)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(2)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lblOpenedTempInvalidDocuments = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.lblOpenedTempInvalidDocuments.setFont(font)
        self.lblOpenedTempInvalidDocuments.setObjectName(_fromUtf8("lblOpenedTempInvalidDocuments"))
        self.verticalLayout_3.addWidget(self.lblOpenedTempInvalidDocuments)
        self.tblOpenedTempInvalidDocuments = CInDocTableView(self.layoutWidget)
        self.tblOpenedTempInvalidDocuments.setObjectName(_fromUtf8("tblOpenedTempInvalidDocuments"))
        self.verticalLayout_3.addWidget(self.tblOpenedTempInvalidDocuments)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lblForCloseTempInvalidDocuments = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.lblForCloseTempInvalidDocuments.setFont(font)
        self.lblForCloseTempInvalidDocuments.setObjectName(_fromUtf8("lblForCloseTempInvalidDocuments"))
        self.verticalLayout_4.addWidget(self.lblForCloseTempInvalidDocuments)
        self.tblForCloseTempInvalidDocuments = CInDocTableView(self.layoutWidget1)
        self.tblForCloseTempInvalidDocuments.setObjectName(_fromUtf8("tblForCloseTempInvalidDocuments"))
        self.verticalLayout_4.addWidget(self.tblForCloseTempInvalidDocuments)
        self.gridLayout_2.addWidget(self.splitter_2, 3, 0, 1, 2)
        self.splitter_3 = QtGui.QSplitter(MyDoctorArea)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setHandleWidth(2)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.layoutWidget2 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lblDeaths = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.lblDeaths.setFont(font)
        self.lblDeaths.setObjectName(_fromUtf8("lblDeaths"))
        self.verticalLayout_5.addWidget(self.lblDeaths)
        self.tblDeaths = CInDocTableView(self.layoutWidget2)
        self.tblDeaths.setObjectName(_fromUtf8("tblDeaths"))
        self.verticalLayout_5.addWidget(self.tblDeaths)
        self.layoutWidget3 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lblLeavedStationary = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.lblLeavedStationary.setFont(font)
        self.lblLeavedStationary.setObjectName(_fromUtf8("lblLeavedStationary"))
        self.verticalLayout_6.addWidget(self.lblLeavedStationary)
        self.tblLeavedStationary = CInDocTableView(self.layoutWidget3)
        self.tblLeavedStationary.setObjectName(_fromUtf8("tblLeavedStationary"))
        self.verticalLayout_6.addWidget(self.tblLeavedStationary)
        self.gridLayout_2.addWidget(self.splitter_3, 4, 0, 1, 2)
        self.splitter_4 = QtGui.QSplitter(MyDoctorArea)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setHandleWidth(2)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.layoutWidget4 = QtGui.QWidget(self.splitter_4)
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lblDispansAbsent = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.lblDispansAbsent.setFont(font)
        self.lblDispansAbsent.setObjectName(_fromUtf8("lblDispansAbsent"))
        self.verticalLayout_7.addWidget(self.lblDispansAbsent)
        self.tblDispansAbsent = CInDocTableView(self.layoutWidget4)
        self.tblDispansAbsent.setObjectName(_fromUtf8("tblDispansAbsent"))
        self.verticalLayout_7.addWidget(self.tblDispansAbsent)
        self.layoutWidget5 = QtGui.QWidget(self.splitter_4)
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.lblBadTest = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.lblBadTest.setFont(font)
        self.lblBadTest.setObjectName(_fromUtf8("lblBadTest"))
        self.verticalLayout_8.addWidget(self.lblBadTest)
        self.tblBadTest = CInDocTableView(self.layoutWidget5)
        self.tblBadTest.setObjectName(_fromUtf8("tblBadTest"))
        self.verticalLayout_8.addWidget(self.tblBadTest)
        self.gridLayout_2.addWidget(self.splitter_4, 5, 0, 1, 2)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblEmergency.setBuddy(self.tblEmergencyCalls)
        self.lblOpenedTempInvalidDocuments.setBuddy(self.tblOpenedTempInvalidDocuments)
        self.lblForCloseTempInvalidDocuments.setBuddy(self.tblForCloseTempInvalidDocuments)
        self.lblDeaths.setBuddy(self.tblDeaths)
        self.lblLeavedStationary.setBuddy(self.tblLeavedStationary)
        self.lblDispansAbsent.setBuddy(self.tblDispansAbsent)
        self.lblBadTest.setBuddy(self.tblBadTest)

        self.retranslateUi(MyDoctorArea)
        QtCore.QMetaObject.connectSlotsByName(MyDoctorArea)

    def retranslateUi(self, MyDoctorArea):
        MyDoctorArea.setWindowTitle(_translate("MyDoctorArea", "Мой врачебный участок", None))
        self.lblMyAreas.setText(_translate("MyDoctorArea", "Мой участок:", None))
        self.lblOrgStructure.setText(_translate("MyDoctorArea", "Подразделение", None))
        self.lblDate.setText(_translate("MyDoctorArea", "дата", None))
        self.btnApply.setText(_translate("MyDoctorArea", "Применить", None))
        self.btnNotifications.setText(_translate("MyDoctorArea", "Уведомления", None))
        self.btnDoctorPortal.setText(_translate("MyDoctorArea", "Портал врача", None))
        self.btnAmbulatoryCard.setText(_translate("MyDoctorArea", "Амбулаторная карта", None))
        self.groupBox_Observed.setTitle(_translate("MyDoctorArea", "Взяты на ДН:", None))
        self.chkMyObserved.setText(_translate("MyDoctorArea", "Мной", None))
        self.chkOrgStrObserved.setText(_translate("MyDoctorArea", "Врачами моего подразделения", None))
        self.chkSpecObserved.setText(_translate("MyDoctorArea", "Врачами моей специальности", None))
        self.lblEmergency.setText(_translate("MyDoctorArea", "Вызовы СМП и НМП ", None))
        self.chkSMPColor.setText(_translate("MyDoctorArea", "вызовы СМП", None))
        self.chkNMPColor.setText(_translate("MyDoctorArea", "вызовы НМП", None))
        self.chkSMPActiveColor.setText(_translate("MyDoctorArea", "вызовы СМП-Актив", None))
        self.lblOpenedTempInvalidDocuments.setText(_translate("MyDoctorArea", "Открытые листы нетрудоспособности", None))
        self.lblForCloseTempInvalidDocuments.setText(_translate("MyDoctorArea", "Листы нетрудоспособности ожидают закрытия", None))
        self.lblDeaths.setText(_translate("MyDoctorArea", "Умершие", None))
        self.lblLeavedStationary.setText(_translate("MyDoctorArea", "Выписаны из стационара", None))
        self.lblDispansAbsent.setText(_translate("MyDoctorArea", "Д-учет, не явившиеся", None))
        self.lblBadTest.setText(_translate("MyDoctorArea", "Анализы с превышением", None))

from Orgs.OrgStructComboBoxes import CAreaComboBox
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
