# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Registry\PlanningProfilactic.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PlanningProfilactic(object):
    def setupUi(self, PlanningProfilactic):
        PlanningProfilactic.setObjectName(_fromUtf8("PlanningProfilactic"))
        PlanningProfilactic.resize(373, 303)
        self.gridLayout = QtGui.QGridLayout(PlanningProfilactic)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 13, 0, 1, 1)
        self.cmbOrgStructure = CDbComboBox(PlanningProfilactic)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 4, 1, 1, 4)
        self.sbYear = QtGui.QSpinBox(PlanningProfilactic)
        self.sbYear.setMinimum(2017)
        self.sbYear.setMaximum(2099)
        self.sbYear.setObjectName(_fromUtf8("sbYear"))
        self.gridLayout.addWidget(self.sbYear, 0, 3, 1, 2)
        self.label = QtGui.QLabel(PlanningProfilactic)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.chkAddProf = QtGui.QCheckBox(PlanningProfilactic)
        self.chkAddProf.setChecked(True)
        self.chkAddProf.setObjectName(_fromUtf8("chkAddProf"))
        self.gridLayout.addWidget(self.chkAddProf, 10, 0, 1, 5)
        self.chkAddDisp1 = QtGui.QCheckBox(PlanningProfilactic)
        self.chkAddDisp1.setChecked(True)
        self.chkAddDisp1.setObjectName(_fromUtf8("chkAddDisp1"))
        self.gridLayout.addWidget(self.chkAddDisp1, 9, 0, 1, 5)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 14, 2, 1, 3)
        self.chkAddDisp3 = QtGui.QCheckBox(PlanningProfilactic)
        self.chkAddDisp3.setChecked(True)
        self.chkAddDisp3.setObjectName(_fromUtf8("chkAddDisp3"))
        self.gridLayout.addWidget(self.chkAddDisp3, 6, 0, 1, 5)
        self.lblMonthFrom = QtGui.QLabel(PlanningProfilactic)
        self.lblMonthFrom.setObjectName(_fromUtf8("lblMonthFrom"))
        self.gridLayout.addWidget(self.lblMonthFrom, 2, 0, 1, 3)
        self.lblNewPlanning = QtGui.QLabel(PlanningProfilactic)
        self.lblNewPlanning.setObjectName(_fromUtf8("lblNewPlanning"))
        self.gridLayout.addWidget(self.lblNewPlanning, 5, 0, 1, 5)
        self.chkCovidPriority = QtGui.QCheckBox(PlanningProfilactic)
        self.chkCovidPriority.setObjectName(_fromUtf8("chkCovidPriority"))
        self.gridLayout.addWidget(self.chkCovidPriority, 12, 0, 1, 5)
        self.chkQuantityWorkAge = QtGui.QCheckBox(PlanningProfilactic)
        self.chkQuantityWorkAge.setObjectName(_fromUtf8("chkQuantityWorkAge"))
        self.gridLayout.addWidget(self.chkQuantityWorkAge, 11, 0, 1, 5)
        self.lblMonthTo = QtGui.QLabel(PlanningProfilactic)
        self.lblMonthTo.setObjectName(_fromUtf8("lblMonthTo"))
        self.gridLayout.addWidget(self.lblMonthTo, 3, 0, 1, 3)
        self.btnStart = QtGui.QPushButton(PlanningProfilactic)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.gridLayout.addWidget(self.btnStart, 14, 0, 1, 1)
        self.lblYear = QtGui.QLabel(PlanningProfilactic)
        self.lblYear.setObjectName(_fromUtf8("lblYear"))
        self.gridLayout.addWidget(self.lblYear, 0, 0, 1, 3)
        self.cmbMonthTo = QtGui.QComboBox(PlanningProfilactic)
        self.cmbMonthTo.setObjectName(_fromUtf8("cmbMonthTo"))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbMonthTo, 3, 3, 1, 2)
        self.btnClose = QtGui.QPushButton(PlanningProfilactic)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.gridLayout.addWidget(self.btnClose, 14, 1, 1, 1)
        self.cmbMonthFrom = QtGui.QComboBox(PlanningProfilactic)
        self.cmbMonthFrom.setObjectName(_fromUtf8("cmbMonthFrom"))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbMonthFrom, 2, 3, 1, 2)

        self.retranslateUi(PlanningProfilactic)
        self.cmbMonthTo.setCurrentIndex(11)
        QtCore.QMetaObject.connectSlotsByName(PlanningProfilactic)

    def retranslateUi(self, PlanningProfilactic):
        PlanningProfilactic.setWindowTitle(_translate("PlanningProfilactic", "Планирование профилактических мероприятий", None))
        self.label.setText(_translate("PlanningProfilactic", "Подразделение", None))
        self.chkAddProf.setText(_translate("PlanningProfilactic", "Профосмотров взрослого населения", None))
        self.chkAddDisp1.setText(_translate("PlanningProfilactic", "Диспансеризации взрослого населения ежегодной", None))
        self.chkAddDisp3.setText(_translate("PlanningProfilactic", "Диспансеризации взрослого населения раз в 3 года", None))
        self.lblMonthFrom.setText(_translate("PlanningProfilactic", "Месяц с", None))
        self.lblNewPlanning.setText(_translate("PlanningProfilactic", "Запланировать проведение мероприятий для", None))
        self.chkCovidPriority.setText(_translate("PlanningProfilactic", "Приоритет планирования переболевших COVID-19", None))
        self.chkQuantityWorkAge.setText(_translate("PlanningProfilactic", "Учитывать трудоспособное/нетрудоспособное население", None))
        self.lblMonthTo.setText(_translate("PlanningProfilactic", "Месяц по", None))
        self.btnStart.setText(_translate("PlanningProfilactic", "Начать", None))
        self.lblYear.setText(_translate("PlanningProfilactic", "Год проведения мероприятий", None))
        self.cmbMonthTo.setItemText(0, _translate("PlanningProfilactic", "январь", None))
        self.cmbMonthTo.setItemText(1, _translate("PlanningProfilactic", "февраль", None))
        self.cmbMonthTo.setItemText(2, _translate("PlanningProfilactic", "март", None))
        self.cmbMonthTo.setItemText(3, _translate("PlanningProfilactic", "апрель", None))
        self.cmbMonthTo.setItemText(4, _translate("PlanningProfilactic", "май", None))
        self.cmbMonthTo.setItemText(5, _translate("PlanningProfilactic", "июнь", None))
        self.cmbMonthTo.setItemText(6, _translate("PlanningProfilactic", "июль", None))
        self.cmbMonthTo.setItemText(7, _translate("PlanningProfilactic", "август", None))
        self.cmbMonthTo.setItemText(8, _translate("PlanningProfilactic", "сентябрь", None))
        self.cmbMonthTo.setItemText(9, _translate("PlanningProfilactic", "октябрь", None))
        self.cmbMonthTo.setItemText(10, _translate("PlanningProfilactic", "ноябрь", None))
        self.cmbMonthTo.setItemText(11, _translate("PlanningProfilactic", "декабрь", None))
        self.btnClose.setText(_translate("PlanningProfilactic", "Закрыть", None))
        self.cmbMonthFrom.setItemText(0, _translate("PlanningProfilactic", "январь", None))
        self.cmbMonthFrom.setItemText(1, _translate("PlanningProfilactic", "февраль", None))
        self.cmbMonthFrom.setItemText(2, _translate("PlanningProfilactic", "март", None))
        self.cmbMonthFrom.setItemText(3, _translate("PlanningProfilactic", "апрель", None))
        self.cmbMonthFrom.setItemText(4, _translate("PlanningProfilactic", "май", None))
        self.cmbMonthFrom.setItemText(5, _translate("PlanningProfilactic", "июнь", None))
        self.cmbMonthFrom.setItemText(6, _translate("PlanningProfilactic", "июль", None))
        self.cmbMonthFrom.setItemText(7, _translate("PlanningProfilactic", "август", None))
        self.cmbMonthFrom.setItemText(8, _translate("PlanningProfilactic", "сентябрь", None))
        self.cmbMonthFrom.setItemText(9, _translate("PlanningProfilactic", "октябрь", None))
        self.cmbMonthFrom.setItemText(10, _translate("PlanningProfilactic", "ноябрь", None))
        self.cmbMonthFrom.setItemText(11, _translate("PlanningProfilactic", "декабрь", None))

from library.DbComboBox import CDbComboBox
