# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/appendix/cashRegister/localPreferences/appPreferencesDialog.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_appPreferencesDialog(object):
    def setupUi(self, appPreferencesDialog):
        appPreferencesDialog.setObjectName(_fromUtf8("appPreferencesDialog"))
        appPreferencesDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        appPreferencesDialog.resize(375, 398)
        appPreferencesDialog.setAutoFillBackground(False)
        appPreferencesDialog.setSizeGripEnabled(False)
        appPreferencesDialog.setModal(True)
        self.verticalLayout_4 = QtGui.QVBoxLayout(appPreferencesDialog)
        self.verticalLayout_4.setMargin(4)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(appPreferencesDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabMain)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblAccountNumberMask = QtGui.QLabel(self.tabMain)
        self.lblAccountNumberMask.setObjectName(_fromUtf8("lblAccountNumberMask"))
        self.gridLayout_2.addWidget(self.lblAccountNumberMask, 6, 0, 1, 1)
        self.edtAccountNumberMask = QtGui.QLineEdit(self.tabMain)
        self.edtAccountNumberMask.setObjectName(_fromUtf8("edtAccountNumberMask"))
        self.gridLayout_2.addWidget(self.edtAccountNumberMask, 6, 1, 1, 2)
        self.edtContractResolutionMask = QtGui.QLineEdit(self.tabMain)
        self.edtContractResolutionMask.setObjectName(_fromUtf8("edtContractResolutionMask"))
        self.gridLayout_2.addWidget(self.edtContractResolutionMask, 4, 1, 1, 2)
        self.lblContractGroupingMask = QtGui.QLabel(self.tabMain)
        self.lblContractGroupingMask.setObjectName(_fromUtf8("lblContractGroupingMask"))
        self.gridLayout_2.addWidget(self.lblContractGroupingMask, 5, 0, 1, 1)
        self.edtCashBox = QtGui.QLineEdit(self.tabMain)
        self.edtCashBox.setObjectName(_fromUtf8("edtCashBox"))
        self.gridLayout_2.addWidget(self.edtCashBox, 11, 1, 1, 2)
        self.lblCashBox = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCashBox.sizePolicy().hasHeightForWidth())
        self.lblCashBox.setSizePolicy(sizePolicy)
        self.lblCashBox.setObjectName(_fromUtf8("lblCashBox"))
        self.gridLayout_2.addWidget(self.lblCashBox, 11, 0, 1, 1)
        self.lblVatTaxPayer = QtGui.QLabel(self.tabMain)
        self.lblVatTaxPayer.setObjectName(_fromUtf8("lblVatTaxPayer"))
        self.gridLayout_2.addWidget(self.lblVatTaxPayer, 12, 0, 1, 1)
        self.lblOrganisation = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrganisation.sizePolicy().hasHeightForWidth())
        self.lblOrganisation.setSizePolicy(sizePolicy)
        self.lblOrganisation.setMinimumSize(QtCore.QSize(130, 0))
        self.lblOrganisation.setObjectName(_fromUtf8("lblOrganisation"))
        self.gridLayout_2.addWidget(self.lblOrganisation, 0, 0, 1, 1)
        self.cmbOrganisation = CPolyclinicComboBox(self.tabMain)
        self.cmbOrganisation.setObjectName(_fromUtf8("cmbOrganisation"))
        self.gridLayout_2.addWidget(self.cmbOrganisation, 0, 1, 1, 1)
        self.btnSelectOrganisation = QtGui.QToolButton(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectOrganisation.sizePolicy().hasHeightForWidth())
        self.btnSelectOrganisation.setSizePolicy(sizePolicy)
        self.btnSelectOrganisation.setObjectName(_fromUtf8("btnSelectOrganisation"))
        self.gridLayout_2.addWidget(self.btnSelectOrganisation, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(61, 174, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 13, 0, 1, 1)
        self.lblPrintPayer = QtGui.QLabel(self.tabMain)
        self.lblPrintPayer.setObjectName(_fromUtf8("lblPrintPayer"))
        self.gridLayout_2.addWidget(self.lblPrintPayer, 8, 0, 1, 1)
        self.lblPrintAccountNumber = QtGui.QLabel(self.tabMain)
        self.lblPrintAccountNumber.setObjectName(_fromUtf8("lblPrintAccountNumber"))
        self.gridLayout_2.addWidget(self.lblPrintAccountNumber, 9, 0, 1, 1)
        self.lblPrintDuplicate = QtGui.QLabel(self.tabMain)
        self.lblPrintDuplicate.setObjectName(_fromUtf8("lblPrintDuplicate"))
        self.gridLayout_2.addWidget(self.lblPrintDuplicate, 10, 0, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblOrgStructure.setSizePolicy(sizePolicy)
        self.lblOrgStructure.setMinimumSize(QtCore.QSize(130, 0))
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout_2.addWidget(self.lblOrgStructure, 1, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(self.tabMain)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout_2.addWidget(self.cmbOrgStructure, 1, 1, 1, 2)
        self.chkPrintDuplicate = QtGui.QCheckBox(self.tabMain)
        self.chkPrintDuplicate.setText(_fromUtf8(""))
        self.chkPrintDuplicate.setObjectName(_fromUtf8("chkPrintDuplicate"))
        self.gridLayout_2.addWidget(self.chkPrintDuplicate, 10, 1, 1, 2)
        self.edtContractNumberMask = QtGui.QLineEdit(self.tabMain)
        self.edtContractNumberMask.setObjectName(_fromUtf8("edtContractNumberMask"))
        self.gridLayout_2.addWidget(self.edtContractNumberMask, 3, 1, 1, 2)
        self.edtContractGroupingMask = QtGui.QLineEdit(self.tabMain)
        self.edtContractGroupingMask.setObjectName(_fromUtf8("edtContractGroupingMask"))
        self.gridLayout_2.addWidget(self.edtContractGroupingMask, 5, 1, 1, 2)
        self.lblContractNumberMask = QtGui.QLabel(self.tabMain)
        self.lblContractNumberMask.setObjectName(_fromUtf8("lblContractNumberMask"))
        self.gridLayout_2.addWidget(self.lblContractNumberMask, 3, 0, 1, 1)
        self.lblContractResolutionMask = QtGui.QLabel(self.tabMain)
        self.lblContractResolutionMask.setObjectName(_fromUtf8("lblContractResolutionMask"))
        self.gridLayout_2.addWidget(self.lblContractResolutionMask, 4, 0, 1, 1)
        self.chkVatTaxPayer = QtGui.QCheckBox(self.tabMain)
        self.chkVatTaxPayer.setText(_fromUtf8(""))
        self.chkVatTaxPayer.setObjectName(_fromUtf8("chkVatTaxPayer"))
        self.gridLayout_2.addWidget(self.chkVatTaxPayer, 12, 1, 1, 2)
        self.chkPrintPayer = QtGui.QCheckBox(self.tabMain)
        self.chkPrintPayer.setText(_fromUtf8(""))
        self.chkPrintPayer.setObjectName(_fromUtf8("chkPrintPayer"))
        self.gridLayout_2.addWidget(self.chkPrintPayer, 8, 1, 1, 2)
        self.chkPrintAccountNumber = QtGui.QCheckBox(self.tabMain)
        self.chkPrintAccountNumber.setText(_fromUtf8(""))
        self.chkPrintAccountNumber.setObjectName(_fromUtf8("chkPrintAccountNumber"))
        self.gridLayout_2.addWidget(self.chkPrintAccountNumber, 9, 1, 1, 2)
        self.chkUseCurrentUser = QtGui.QCheckBox(self.tabMain)
        self.chkUseCurrentUser.setText(_fromUtf8(""))
        self.chkUseCurrentUser.setObjectName(_fromUtf8("chkUseCurrentUser"))
        self.gridLayout_2.addWidget(self.chkUseCurrentUser, 2, 1, 1, 2)
        self.lblUseCurrentUser = QtGui.QLabel(self.tabMain)
        self.lblUseCurrentUser.setObjectName(_fromUtf8("lblUseCurrentUser"))
        self.gridLayout_2.addWidget(self.lblUseCurrentUser, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabECR = QtGui.QWidget()
        self.tabECR.setObjectName(_fromUtf8("tabECR"))
        self.gridLayout = QtGui.QGridLayout(self.tabECR)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblUsbPort = QtGui.QLabel(self.tabECR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUsbPort.sizePolicy().hasHeightForWidth())
        self.lblUsbPort.setSizePolicy(sizePolicy)
        self.lblUsbPort.setObjectName(_fromUtf8("lblUsbPort"))
        self.gridLayout.addWidget(self.lblUsbPort, 8, 0, 1, 1)
        self.edtTcpIpPort = QtGui.QSpinBox(self.tabECR)
        self.edtTcpIpPort.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTcpIpPort.sizePolicy().hasHeightForWidth())
        self.edtTcpIpPort.setSizePolicy(sizePolicy)
        self.edtTcpIpPort.setMinimum(1)
        self.edtTcpIpPort.setMaximum(65535)
        self.edtTcpIpPort.setProperty("value", 5555)
        self.edtTcpIpPort.setObjectName(_fromUtf8("edtTcpIpPort"))
        self.gridLayout.addWidget(self.edtTcpIpPort, 11, 1, 1, 2)
        self.lblTcpIpPort = QtGui.QLabel(self.tabECR)
        self.lblTcpIpPort.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTcpIpPort.sizePolicy().hasHeightForWidth())
        self.lblTcpIpPort.setSizePolicy(sizePolicy)
        self.lblTcpIpPort.setObjectName(_fromUtf8("lblTcpIpPort"))
        self.gridLayout.addWidget(self.lblTcpIpPort, 11, 0, 1, 1)
        self.lblTcpIpHost = QtGui.QLabel(self.tabECR)
        self.lblTcpIpHost.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTcpIpHost.sizePolicy().hasHeightForWidth())
        self.lblTcpIpHost.setSizePolicy(sizePolicy)
        self.lblTcpIpHost.setObjectName(_fromUtf8("lblTcpIpHost"))
        self.gridLayout.addWidget(self.lblTcpIpHost, 10, 0, 1, 1)
        self.rbBluetooth = QtGui.QRadioButton(self.tabECR)
        self.rbBluetooth.setObjectName(_fromUtf8("rbBluetooth"))
        self.gridLayout.addWidget(self.rbBluetooth, 12, 0, 1, 3)
        self.lblBluetoothMacAddress = QtGui.QLabel(self.tabECR)
        self.lblBluetoothMacAddress.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBluetoothMacAddress.sizePolicy().hasHeightForWidth())
        self.lblBluetoothMacAddress.setSizePolicy(sizePolicy)
        self.lblBluetoothMacAddress.setObjectName(_fromUtf8("lblBluetoothMacAddress"))
        self.gridLayout.addWidget(self.lblBluetoothMacAddress, 13, 0, 1, 1)
        self.rbUsb = QtGui.QRadioButton(self.tabECR)
        self.rbUsb.setChecked(True)
        self.rbUsb.setObjectName(_fromUtf8("rbUsb"))
        self.gridLayout.addWidget(self.rbUsb, 7, 0, 1, 3)
        self.rbTcpIp = QtGui.QRadioButton(self.tabECR)
        self.rbTcpIp.setObjectName(_fromUtf8("rbTcpIp"))
        self.gridLayout.addWidget(self.rbTcpIp, 9, 0, 1, 3)
        self.rbSerialPort = QtGui.QRadioButton(self.tabECR)
        self.rbSerialPort.setObjectName(_fromUtf8("rbSerialPort"))
        self.gridLayout.addWidget(self.rbSerialPort, 4, 0, 1, 3)
        self.lblOperatorPassword = QtGui.QLabel(self.tabECR)
        self.lblOperatorPassword.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOperatorPassword.sizePolicy().hasHeightForWidth())
        self.lblOperatorPassword.setSizePolicy(sizePolicy)
        self.lblOperatorPassword.setObjectName(_fromUtf8("lblOperatorPassword"))
        self.gridLayout.addWidget(self.lblOperatorPassword, 2, 0, 1, 1)
        self.lblPassword = QtGui.QLabel(self.tabECR)
        self.lblPassword.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPassword.sizePolicy().hasHeightForWidth())
        self.lblPassword.setSizePolicy(sizePolicy)
        self.lblPassword.setObjectName(_fromUtf8("lblPassword"))
        self.gridLayout.addWidget(self.lblPassword, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 14, 0, 1, 1)
        self.edtTcpIpHost = QtGui.QLineEdit(self.tabECR)
        self.edtTcpIpHost.setEnabled(False)
        self.edtTcpIpHost.setText(_fromUtf8(""))
        self.edtTcpIpHost.setObjectName(_fromUtf8("edtTcpIpHost"))
        self.gridLayout.addWidget(self.edtTcpIpHost, 10, 1, 1, 2)
        self.edtUsbPort = QtGui.QLineEdit(self.tabECR)
        self.edtUsbPort.setReadOnly(True)
        self.edtUsbPort.setObjectName(_fromUtf8("edtUsbPort"))
        self.gridLayout.addWidget(self.edtUsbPort, 8, 1, 1, 2)
        self.edtPassword = QtGui.QLineEdit(self.tabECR)
        self.edtPassword.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPassword.sizePolicy().hasHeightForWidth())
        self.edtPassword.setSizePolicy(sizePolicy)
        self.edtPassword.setInputMask(_fromUtf8("99999999; "))
        self.edtPassword.setObjectName(_fromUtf8("edtPassword"))
        self.gridLayout.addWidget(self.edtPassword, 1, 1, 1, 2)
        self.edtOperatorPassword = QtGui.QLineEdit(self.tabECR)
        self.edtOperatorPassword.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOperatorPassword.sizePolicy().hasHeightForWidth())
        self.edtOperatorPassword.setSizePolicy(sizePolicy)
        self.edtOperatorPassword.setInputMask(_fromUtf8("99999999; "))
        self.edtOperatorPassword.setObjectName(_fromUtf8("edtOperatorPassword"))
        self.gridLayout.addWidget(self.edtOperatorPassword, 2, 1, 1, 2)
        self.edtSerialPort = QtGui.QLineEdit(self.tabECR)
        self.edtSerialPort.setEnabled(False)
        self.edtSerialPort.setObjectName(_fromUtf8("edtSerialPort"))
        self.gridLayout.addWidget(self.edtSerialPort, 5, 1, 1, 2)
        self.cmbSerialBaudrate = QtGui.QComboBox(self.tabECR)
        self.cmbSerialBaudrate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSerialBaudrate.sizePolicy().hasHeightForWidth())
        self.cmbSerialBaudrate.setSizePolicy(sizePolicy)
        self.cmbSerialBaudrate.setObjectName(_fromUtf8("cmbSerialBaudrate"))
        self.cmbSerialBaudrate.addItem(_fromUtf8(""))
        self.cmbSerialBaudrate.addItem(_fromUtf8(""))
        self.cmbSerialBaudrate.addItem(_fromUtf8(""))
        self.cmbSerialBaudrate.addItem(_fromUtf8(""))
        self.cmbSerialBaudrate.addItem(_fromUtf8(""))
        self.cmbSerialBaudrate.addItem(_fromUtf8(""))
        self.cmbSerialBaudrate.addItem(_fromUtf8(""))
        self.cmbSerialBaudrate.addItem(_fromUtf8(""))
        self.cmbSerialBaudrate.addItem(_fromUtf8(""))
        self.cmbSerialBaudrate.addItem(_fromUtf8(""))
        self.cmbSerialBaudrate.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSerialBaudrate, 6, 1, 1, 2)
        self.lblSerialPort = QtGui.QLabel(self.tabECR)
        self.lblSerialPort.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSerialPort.sizePolicy().hasHeightForWidth())
        self.lblSerialPort.setSizePolicy(sizePolicy)
        self.lblSerialPort.setObjectName(_fromUtf8("lblSerialPort"))
        self.gridLayout.addWidget(self.lblSerialPort, 5, 0, 1, 1)
        self.lblSerialBaudrate = QtGui.QLabel(self.tabECR)
        self.lblSerialBaudrate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSerialBaudrate.sizePolicy().hasHeightForWidth())
        self.lblSerialBaudrate.setSizePolicy(sizePolicy)
        self.lblSerialBaudrate.setObjectName(_fromUtf8("lblSerialBaudrate"))
        self.gridLayout.addWidget(self.lblSerialBaudrate, 6, 0, 1, 1)
        self.edtBluetoothMacAddress = QtGui.QLineEdit(self.tabECR)
        self.edtBluetoothMacAddress.setEnabled(False)
        self.edtBluetoothMacAddress.setObjectName(_fromUtf8("edtBluetoothMacAddress"))
        self.gridLayout.addWidget(self.edtBluetoothMacAddress, 13, 1, 1, 1)
        self.cmbDriver = QtGui.QComboBox(self.tabECR)
        self.cmbDriver.setObjectName(_fromUtf8("cmbDriver"))
        self.cmbDriver.addItem(_fromUtf8(""))
        self.cmbDriver.addItem(_fromUtf8(""))
        self.cmbDriver.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDriver, 0, 1, 1, 1)
        self.lblDriver = QtGui.QLabel(self.tabECR)
        self.lblDriver.setObjectName(_fromUtf8("lblDriver"))
        self.gridLayout.addWidget(self.lblDriver, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.lblSysAdminPassword = QtGui.QLabel(self.tabECR)
        self.lblSysAdminPassword.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSysAdminPassword.sizePolicy().hasHeightForWidth())
        self.lblSysAdminPassword.setSizePolicy(sizePolicy)
        self.lblSysAdminPassword.setObjectName(_fromUtf8("lblSysAdminPassword"))
        self.gridLayout.addWidget(self.lblSysAdminPassword, 3, 0, 1, 1)
        self.edtSysAdminPassword = QtGui.QLineEdit(self.tabECR)
        self.edtSysAdminPassword.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSysAdminPassword.sizePolicy().hasHeightForWidth())
        self.edtSysAdminPassword.setSizePolicy(sizePolicy)
        self.edtSysAdminPassword.setInputMask(_fromUtf8("99; "))
        self.edtSysAdminPassword.setObjectName(_fromUtf8("edtSysAdminPassword"))
        self.gridLayout.addWidget(self.edtSysAdminPassword, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tabECR, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(appPreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.lblAccountNumberMask.setBuddy(self.edtAccountNumberMask)
        self.lblContractGroupingMask.setBuddy(self.edtContractGroupingMask)
        self.lblCashBox.setBuddy(self.edtCashBox)
        self.lblOrganisation.setBuddy(self.cmbOrganisation)
        self.lblPrintPayer.setBuddy(self.chkPrintPayer)
        self.lblPrintAccountNumber.setBuddy(self.chkPrintAccountNumber)
        self.lblPrintDuplicate.setBuddy(self.chkPrintDuplicate)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblContractNumberMask.setBuddy(self.edtContractNumberMask)
        self.lblContractResolutionMask.setBuddy(self.edtContractResolutionMask)
        self.lblUseCurrentUser.setBuddy(self.chkUseCurrentUser)
        self.lblUsbPort.setBuddy(self.edtUsbPort)
        self.lblTcpIpPort.setBuddy(self.edtTcpIpPort)
        self.lblTcpIpHost.setBuddy(self.edtTcpIpHost)
        self.lblBluetoothMacAddress.setBuddy(self.edtBluetoothMacAddress)
        self.lblOperatorPassword.setBuddy(self.edtOperatorPassword)
        self.lblPassword.setBuddy(self.edtPassword)
        self.lblSerialPort.setBuddy(self.edtSerialPort)
        self.lblSerialBaudrate.setBuddy(self.cmbSerialBaudrate)
        self.lblDriver.setBuddy(self.cmbDriver)
        self.lblSysAdminPassword.setBuddy(self.edtSysAdminPassword)

        self.retranslateUi(appPreferencesDialog)
        self.tabWidget.setCurrentIndex(0)
        self.cmbSerialBaudrate.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), appPreferencesDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), appPreferencesDialog.reject)
        QtCore.QObject.connect(self.rbSerialPort, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblSerialPort.setEnabled)
        QtCore.QObject.connect(self.rbSerialPort, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblSerialBaudrate.setEnabled)
        QtCore.QObject.connect(self.rbSerialPort, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtSerialPort.setEnabled)
        QtCore.QObject.connect(self.rbSerialPort, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSerialBaudrate.setEnabled)
        QtCore.QObject.connect(self.rbUsb, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblUsbPort.setEnabled)
        QtCore.QObject.connect(self.rbUsb, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtUsbPort.setEnabled)
        QtCore.QObject.connect(self.rbTcpIp, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblTcpIpHost.setEnabled)
        QtCore.QObject.connect(self.rbTcpIp, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblTcpIpPort.setEnabled)
        QtCore.QObject.connect(self.rbTcpIp, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtTcpIpHost.setEnabled)
        QtCore.QObject.connect(self.rbTcpIp, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtTcpIpPort.setEnabled)
        QtCore.QObject.connect(self.rbBluetooth, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblBluetoothMacAddress.setEnabled)
        QtCore.QObject.connect(self.rbBluetooth, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBluetoothMacAddress.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(appPreferencesDialog)
        appPreferencesDialog.setTabOrder(self.tabWidget, self.cmbOrganisation)
        appPreferencesDialog.setTabOrder(self.cmbOrganisation, self.btnSelectOrganisation)
        appPreferencesDialog.setTabOrder(self.btnSelectOrganisation, self.cmbOrgStructure)
        appPreferencesDialog.setTabOrder(self.cmbOrgStructure, self.chkUseCurrentUser)
        appPreferencesDialog.setTabOrder(self.chkUseCurrentUser, self.edtContractNumberMask)
        appPreferencesDialog.setTabOrder(self.edtContractNumberMask, self.edtContractResolutionMask)
        appPreferencesDialog.setTabOrder(self.edtContractResolutionMask, self.edtContractGroupingMask)
        appPreferencesDialog.setTabOrder(self.edtContractGroupingMask, self.edtAccountNumberMask)
        appPreferencesDialog.setTabOrder(self.edtAccountNumberMask, self.chkPrintPayer)
        appPreferencesDialog.setTabOrder(self.chkPrintPayer, self.chkPrintAccountNumber)
        appPreferencesDialog.setTabOrder(self.chkPrintAccountNumber, self.chkPrintDuplicate)
        appPreferencesDialog.setTabOrder(self.chkPrintDuplicate, self.edtCashBox)
        appPreferencesDialog.setTabOrder(self.edtCashBox, self.chkVatTaxPayer)
        appPreferencesDialog.setTabOrder(self.chkVatTaxPayer, self.cmbDriver)
        appPreferencesDialog.setTabOrder(self.cmbDriver, self.edtPassword)
        appPreferencesDialog.setTabOrder(self.edtPassword, self.edtOperatorPassword)
        appPreferencesDialog.setTabOrder(self.edtOperatorPassword, self.edtSysAdminPassword)
        appPreferencesDialog.setTabOrder(self.edtSysAdminPassword, self.rbSerialPort)
        appPreferencesDialog.setTabOrder(self.rbSerialPort, self.edtSerialPort)
        appPreferencesDialog.setTabOrder(self.edtSerialPort, self.cmbSerialBaudrate)
        appPreferencesDialog.setTabOrder(self.cmbSerialBaudrate, self.rbUsb)
        appPreferencesDialog.setTabOrder(self.rbUsb, self.edtUsbPort)
        appPreferencesDialog.setTabOrder(self.edtUsbPort, self.rbTcpIp)
        appPreferencesDialog.setTabOrder(self.rbTcpIp, self.edtTcpIpHost)
        appPreferencesDialog.setTabOrder(self.edtTcpIpHost, self.edtTcpIpPort)
        appPreferencesDialog.setTabOrder(self.edtTcpIpPort, self.rbBluetooth)
        appPreferencesDialog.setTabOrder(self.rbBluetooth, self.edtBluetoothMacAddress)
        appPreferencesDialog.setTabOrder(self.edtBluetoothMacAddress, self.buttonBox)

    def retranslateUi(self, appPreferencesDialog):
        appPreferencesDialog.setWindowTitle(_translate("appPreferencesDialog", "Умолчания", None))
        self.lblAccountNumberMask.setText(_translate("appPreferencesDialog", "Маска номера &счёта", None))
        self.lblContractGroupingMask.setText(_translate("appPreferencesDialog", "Маска &группы договора", None))
        self.lblCashBox.setText(_translate("appPreferencesDialog", "&Касса", None))
        self.lblVatTaxPayer.setText(_translate("appPreferencesDialog", "Налогоплательщик НДС", None))
        self.lblOrganisation.setText(_translate("appPreferencesDialog", "&ЛПУ", None))
        self.btnSelectOrganisation.setText(_translate("appPreferencesDialog", "...", None))
        self.lblPrintPayer.setText(_translate("appPreferencesDialog", "Печатать ФИО плательщика", None))
        self.lblPrintAccountNumber.setText(_translate("appPreferencesDialog", "Печатать номер и дату счёта", None))
        self.lblPrintDuplicate.setText(_translate("appPreferencesDialog", "Печатать &дубликат", None))
        self.lblOrgStructure.setText(_translate("appPreferencesDialog", "&Подразделение", None))
        self.lblContractNumberMask.setText(_translate("appPreferencesDialog", "Маска &номера договора", None))
        self.lblContractResolutionMask.setText(_translate("appPreferencesDialog", "Маска о&снования договора", None))
        self.chkVatTaxPayer.setToolTip(_translate("appPreferencesDialog", "Налогоплательщики НДС в чеке печатают 0%,\n"
"Прочие - \"Без НДС\" ", None))
        self.lblUseCurrentUser.setText(_translate("appPreferencesDialog", "Подставлять пользователя в &фильтр", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("appPreferencesDialog", "&Основные настройки", None))
        self.lblUsbPort.setText(_translate("appPreferencesDialog", "&Устройство", None))
        self.edtTcpIpPort.setToolTip(_translate("appPreferencesDialog", "IP-порт ККТ", None))
        self.lblTcpIpPort.setText(_translate("appPreferencesDialog", "По&рт", None))
        self.lblTcpIpHost.setText(_translate("appPreferencesDialog", "&Адрес", None))
        self.rbBluetooth.setText(_translate("appPreferencesDialog", "&Bluetooth", None))
        self.lblBluetoothMacAddress.setText(_translate("appPreferencesDialog", "MAC &адрес", None))
        self.rbUsb.setText(_translate("appPreferencesDialog", "Порт &USB", None))
        self.rbTcpIp.setText(_translate("appPreferencesDialog", "&TCP/IP", None))
        self.rbSerialPort.setText(_translate("appPreferencesDialog", "Последовательный пор&т", None))
        self.lblOperatorPassword.setText(_translate("appPreferencesDialog", "Пароль опе&ратора", None))
        self.lblPassword.setText(_translate("appPreferencesDialog", "&Пароль доступа", None))
        self.edtTcpIpHost.setToolTip(_translate("appPreferencesDialog", "IP-адрес ККТ.\n"
"Может быть как ip-адресом, так и доменным именем", None))
        self.edtUsbPort.setToolTip(_translate("appPreferencesDialog", "Расположение USB-устройства в системе,\n"
"в Windows не применяется.\n"
"Для Linux auto - единственный понятный выбор :(", None))
        self.edtUsbPort.setText(_translate("appPreferencesDialog", "auto", None))
        self.edtPassword.setToolTip(_translate("appPreferencesDialog", "Пароль доступа ККТ.\n"
"Требуется для взаимодействия с ККТ.\n"
"Если не указан или пуст, используется стандартный пароль в зависимости от модели", None))
        self.edtOperatorPassword.setToolTip(_translate("appPreferencesDialog", "Пароль пользователя по умолчанию.\n"
"Требуется для доступа к специфичным командам и режимам ККТ.\n"
"Если не указан или пуст, используется пароль по умолчанию с максимальными правами в зависимости от модели.", None))
        self.edtSerialPort.setToolTip(_translate("appPreferencesDialog", "Идентификатор порта. \n"
"Для Windows - номер COM-порта (например, \"COM15\"),\n"
"Для Linux - путь к TTY-файлу (например, \"/dev/ttyS5\" или \"/dev/ttyUSB0\")", None))
        self.edtSerialPort.setText(_translate("appPreferencesDialog", "COM1", None))
        self.cmbSerialBaudrate.setItemText(0, _translate("appPreferencesDialog", "1200", None))
        self.cmbSerialBaudrate.setItemText(1, _translate("appPreferencesDialog", "2400", None))
        self.cmbSerialBaudrate.setItemText(2, _translate("appPreferencesDialog", "4800", None))
        self.cmbSerialBaudrate.setItemText(3, _translate("appPreferencesDialog", "9600", None))
        self.cmbSerialBaudrate.setItemText(4, _translate("appPreferencesDialog", "19200", None))
        self.cmbSerialBaudrate.setItemText(5, _translate("appPreferencesDialog", "38400", None))
        self.cmbSerialBaudrate.setItemText(6, _translate("appPreferencesDialog", "57600", None))
        self.cmbSerialBaudrate.setItemText(7, _translate("appPreferencesDialog", "115200", None))
        self.cmbSerialBaudrate.setItemText(8, _translate("appPreferencesDialog", "230400", None))
        self.cmbSerialBaudrate.setItemText(9, _translate("appPreferencesDialog", "460800", None))
        self.cmbSerialBaudrate.setItemText(10, _translate("appPreferencesDialog", "921600", None))
        self.lblSerialPort.setText(_translate("appPreferencesDialog", "&Устройство", None))
        self.lblSerialBaudrate.setText(_translate("appPreferencesDialog", "&Скорость, бод", None))
        self.edtBluetoothMacAddress.setToolTip(_translate("appPreferencesDialog", "Bluetooth MAC-адрес ККТ.\n"
"Устройство должно быть предварительно сопряжено с хостом средствами ОС", None))
        self.edtBluetoothMacAddress.setInputMask(_translate("appPreferencesDialog", "HH:HH:HH:HH:HH:HH;_", None))
        self.edtBluetoothMacAddress.setText(_translate("appPreferencesDialog", ":::::", None))
        self.cmbDriver.setItemText(0, _translate("appPreferencesDialog", "-", None))
        self.cmbDriver.setItemText(1, _translate("appPreferencesDialog", "АТОЛ", None))
        self.cmbDriver.setItemText(2, _translate("appPreferencesDialog", "Штрих-М", None))
        self.lblDriver.setText(_translate("appPreferencesDialog", "&Драйвер", None))
        self.lblSysAdminPassword.setText(_translate("appPreferencesDialog", "Пароль &администратора", None))
        self.edtSysAdminPassword.setToolTip(_translate("appPreferencesDialog", "Пароль пользователя по умолчанию.\n"
"Требуется для доступа к специфичным командам и режимам ККТ.\n"
"Если не указан или пуст, используется пароль по умолчанию с максимальными правами в зависимости от модели.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabECR), _translate("appPreferencesDialog", "Настройки КК&М", None))

from Orgs.OrgComboBox import CPolyclinicComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    appPreferencesDialog = QtGui.QDialog()
    ui = Ui_appPreferencesDialog()
    ui.setupUi(appPreferencesDialog)
    appPreferencesDialog.show()
    sys.exit(app.exec_())

