# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\RefBooks\ActionTypeGroup\RBActionTypeGroupList.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RBActionTypeGroupList(object):
    def setupUi(self, RBActionTypeGroupList):
        RBActionTypeGroupList.setObjectName(_fromUtf8("RBActionTypeGroupList"))
        RBActionTypeGroupList.resize(820, 427)
        self.gridLayout_2 = QtGui.QGridLayout(RBActionTypeGroupList)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.buttonBox = QtGui.QDialogButtonBox(RBActionTypeGroupList)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 2, 4, 1, 1)
        self.btnNewTemplate = QtGui.QPushButton(RBActionTypeGroupList)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewTemplate.sizePolicy().hasHeightForWidth())
        self.btnNewTemplate.setSizePolicy(sizePolicy)
        self.btnNewTemplate.setMinimumSize(QtCore.QSize(125, 0))
        self.btnNewTemplate.setObjectName(_fromUtf8("btnNewTemplate"))
        self.gridLayout_2.addWidget(self.btnNewTemplate, 2, 0, 1, 1)
        self.btnDelTemplate = QtGui.QPushButton(RBActionTypeGroupList)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelTemplate.sizePolicy().hasHeightForWidth())
        self.btnDelTemplate.setSizePolicy(sizePolicy)
        self.btnDelTemplate.setMinimumSize(QtCore.QSize(125, 0))
        self.btnDelTemplate.setObjectName(_fromUtf8("btnDelTemplate"))
        self.gridLayout_2.addWidget(self.btnDelTemplate, 2, 2, 1, 1)
        self.splitter = QtGui.QSplitter(RBActionTypeGroupList)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.pnlLeft = QtGui.QWidget(self.splitter)
        self.pnlLeft.setObjectName(_fromUtf8("pnlLeft"))
        self.gridLayout = QtGui.QGridLayout(self.pnlLeft)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblNameContains = QtGui.QLabel(self.pnlLeft)
        self.lblNameContains.setObjectName(_fromUtf8("lblNameContains"))
        self.gridLayout.addWidget(self.lblNameContains, 1, 0, 1, 1)
        self.edtNameContains = QtGui.QLineEdit(self.pnlLeft)
        self.edtNameContains.setObjectName(_fromUtf8("edtNameContains"))
        self.gridLayout.addWidget(self.edtNameContains, 1, 1, 1, 3)
        self.lblCreatePerson = QtGui.QLabel(self.pnlLeft)
        self.lblCreatePerson.setMinimumSize(QtCore.QSize(75, 18))
        self.lblCreatePerson.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblCreatePerson.setObjectName(_fromUtf8("lblCreatePerson"))
        self.gridLayout.addWidget(self.lblCreatePerson, 2, 0, 1, 1)
        self.lblSnils = QtGui.QLabel(self.pnlLeft)
        self.lblSnils.setMinimumSize(QtCore.QSize(75, 18))
        self.lblSnils.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblSnils.setObjectName(_fromUtf8("lblSnils"))
        self.gridLayout.addWidget(self.lblSnils, 3, 0, 1, 1)
        self.lblSpeciality = QtGui.QLabel(self.pnlLeft)
        self.lblSpeciality.setMinimumSize(QtCore.QSize(116, 18))
        self.lblSpeciality.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 4, 0, 1, 1)
        self.lblAccess = QtGui.QLabel(self.pnlLeft)
        self.lblAccess.setMinimumSize(QtCore.QSize(44, 18))
        self.lblAccess.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblAccess.setObjectName(_fromUtf8("lblAccess"))
        self.gridLayout.addWidget(self.lblAccess, 5, 0, 1, 1)
        self.cmbAccess = CComboBoxWithKeyEventHandler(self.pnlLeft)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAccess.sizePolicy().hasHeightForWidth())
        self.cmbAccess.setSizePolicy(sizePolicy)
        self.cmbAccess.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cmbAccess.setObjectName(_fromUtf8("cmbAccess"))
        self.cmbAccess.addItem(_fromUtf8(""))
        self.cmbAccess.addItem(_fromUtf8(""))
        self.cmbAccess.addItem(_fromUtf8(""))
        self.cmbAccess.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAccess, 5, 1, 1, 3)
        self.lblBegCreateDate = QtGui.QLabel(self.pnlLeft)
        self.lblBegCreateDate.setObjectName(_fromUtf8("lblBegCreateDate"))
        self.gridLayout.addWidget(self.lblBegCreateDate, 6, 0, 1, 1)
        self.edtBegCreateDate = CDateEdit(self.pnlLeft)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegCreateDate.sizePolicy().hasHeightForWidth())
        self.edtBegCreateDate.setSizePolicy(sizePolicy)
        self.edtBegCreateDate.setObjectName(_fromUtf8("edtBegCreateDate"))
        self.gridLayout.addWidget(self.edtBegCreateDate, 6, 1, 1, 1)
        self.lblEndCreateDate = QtGui.QLabel(self.pnlLeft)
        self.lblEndCreateDate.setObjectName(_fromUtf8("lblEndCreateDate"))
        self.gridLayout.addWidget(self.lblEndCreateDate, 6, 2, 1, 1)
        self.edtEndCreateDate = CDateEdit(self.pnlLeft)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndCreateDate.sizePolicy().hasHeightForWidth())
        self.edtEndCreateDate.setSizePolicy(sizePolicy)
        self.edtEndCreateDate.setObjectName(_fromUtf8("edtEndCreateDate"))
        self.gridLayout.addWidget(self.edtEndCreateDate, 6, 3, 1, 1)
        self.tblActionTypeGroups = CTableView(self.pnlLeft)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblActionTypeGroups.sizePolicy().hasHeightForWidth())
        self.tblActionTypeGroups.setSizePolicy(sizePolicy)
        self.tblActionTypeGroups.setObjectName(_fromUtf8("tblActionTypeGroups"))
        self.gridLayout.addWidget(self.tblActionTypeGroups, 0, 0, 1, 4)
        self.cmbCreatePerson = CPersonWithOrgListComboBoxEx(self.pnlLeft)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCreatePerson.sizePolicy().hasHeightForWidth())
        self.cmbCreatePerson.setSizePolicy(sizePolicy)
        self.cmbCreatePerson.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cmbCreatePerson.setObjectName(_fromUtf8("cmbCreatePerson"))
        self.gridLayout.addWidget(self.cmbCreatePerson, 2, 1, 1, 3)
        self.cmbSpeciality = CRBComboBox(self.pnlLeft)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSpeciality.sizePolicy().hasHeightForWidth())
        self.cmbSpeciality.setSizePolicy(sizePolicy)
        self.cmbSpeciality.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 4, 1, 1, 3)
        self.chkSnils = QtGui.QCheckBox(self.pnlLeft)
        self.chkSnils.setText(_fromUtf8(""))
        self.chkSnils.setObjectName(_fromUtf8("chkSnils"))
        self.gridLayout.addWidget(self.chkSnils, 3, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 3, 1, 1)
        self.tblActionTypeGroupItems = CTableView(self.splitter)
        self.tblActionTypeGroupItems.setObjectName(_fromUtf8("tblActionTypeGroupItems"))
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 2, 5)
        self.btnEditTemplate = QtGui.QPushButton(RBActionTypeGroupList)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditTemplate.sizePolicy().hasHeightForWidth())
        self.btnEditTemplate.setSizePolicy(sizePolicy)
        self.btnEditTemplate.setMinimumSize(QtCore.QSize(125, 0))
        self.btnEditTemplate.setObjectName(_fromUtf8("btnEditTemplate"))
        self.gridLayout_2.addWidget(self.btnEditTemplate, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 3, 1, 1)
        self.lblNameContains.setBuddy(self.edtNameContains)
        self.lblCreatePerson.setBuddy(self.cmbCreatePerson)
        self.lblSnils.setBuddy(self.chkSnils)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblAccess.setBuddy(self.cmbAccess)
        self.lblBegCreateDate.setBuddy(self.edtBegCreateDate)
        self.lblEndCreateDate.setBuddy(self.edtEndCreateDate)

        self.retranslateUi(RBActionTypeGroupList)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RBActionTypeGroupList.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RBActionTypeGroupList.reject)
        QtCore.QMetaObject.connectSlotsByName(RBActionTypeGroupList)
        RBActionTypeGroupList.setTabOrder(self.tblActionTypeGroups, self.edtNameContains)
        RBActionTypeGroupList.setTabOrder(self.edtNameContains, self.cmbCreatePerson)
        RBActionTypeGroupList.setTabOrder(self.cmbCreatePerson, self.chkSnils)
        RBActionTypeGroupList.setTabOrder(self.chkSnils, self.cmbSpeciality)
        RBActionTypeGroupList.setTabOrder(self.cmbSpeciality, self.cmbAccess)
        RBActionTypeGroupList.setTabOrder(self.cmbAccess, self.edtBegCreateDate)
        RBActionTypeGroupList.setTabOrder(self.edtBegCreateDate, self.edtEndCreateDate)
        RBActionTypeGroupList.setTabOrder(self.edtEndCreateDate, self.tblActionTypeGroupItems)
        RBActionTypeGroupList.setTabOrder(self.tblActionTypeGroupItems, self.btnNewTemplate)
        RBActionTypeGroupList.setTabOrder(self.btnNewTemplate, self.btnEditTemplate)
        RBActionTypeGroupList.setTabOrder(self.btnEditTemplate, self.btnDelTemplate)
        RBActionTypeGroupList.setTabOrder(self.btnDelTemplate, self.buttonBox)

    def retranslateUi(self, RBActionTypeGroupList):
        RBActionTypeGroupList.setWindowTitle(_translate("RBActionTypeGroupList", "Dialog", None))
        self.btnNewTemplate.setText(_translate("RBActionTypeGroupList", "Создать", None))
        self.btnDelTemplate.setText(_translate("RBActionTypeGroupList", "Удалить", None))
        self.lblNameContains.setText(_translate("RBActionTypeGroupList", "Наименование содержит", None))
        self.lblCreatePerson.setText(_translate("RBActionTypeGroupList", "Владелец", None))
        self.lblSnils.setText(_translate("RBActionTypeGroupList", "Показать с таким же СНИЛС", None))
        self.lblSpeciality.setText(_translate("RBActionTypeGroupList", "Специальность", None))
        self.lblAccess.setText(_translate("RBActionTypeGroupList", "Доступность", None))
        self.cmbAccess.setItemText(0, _translate("RBActionTypeGroupList", "не задано", None))
        self.cmbAccess.setItemText(1, _translate("RBActionTypeGroupList", "всем", None))
        self.cmbAccess.setItemText(2, _translate("RBActionTypeGroupList", "по специальности", None))
        self.cmbAccess.setItemText(3, _translate("RBActionTypeGroupList", "владельцу", None))
        self.lblBegCreateDate.setText(_translate("RBActionTypeGroupList", "Дата создания  с", None))
        self.lblEndCreateDate.setText(_translate("RBActionTypeGroupList", "по", None))
        self.btnEditTemplate.setText(_translate("RBActionTypeGroupList", "Редактировать", None))

from Orgs.PersonComboBoxEx import CPersonWithOrgListComboBoxEx
from RefBooks.ActionTypeGroup.ComboBoxWithEventHandler import CComboBoxWithKeyEventHandler
from library.DateEdit import CDateEdit
from library.TableView import CTableView
from library.crbcombobox import CRBComboBox
