# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client_test\RefBooks\Person\PersonsListDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PersonsListDialog(object):
    def setupUi(self, PersonsListDialog):
        PersonsListDialog.setObjectName(_fromUtf8("PersonsListDialog"))
        PersonsListDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PersonsListDialog.resize(906, 545)
        PersonsListDialog.setSizeGripEnabled(True)
        PersonsListDialog.setModal(True)
        self.gridLayout = QtGui.QGridLayout(PersonsListDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tblItems = CTableView(PersonsListDialog)
        self.tblItems.setTabKeyNavigation(False)
        self.tblItems.setAlternatingRowColors(True)
        self.tblItems.setObjectName(_fromUtf8("tblItems"))
        self.gridLayout.addWidget(self.tblItems, 10, 0, 1, 3)
        self.boxLPU = QtGui.QComboBox(PersonsListDialog)
        self.boxLPU.setObjectName(_fromUtf8("boxLPU"))
        self.gridLayout.addWidget(self.boxLPU, 4, 2, 1, 1)
        self.boxSpec = CRBComboBox(PersonsListDialog)
        self.boxSpec.setObjectName(_fromUtf8("boxSpec"))
        self.gridLayout.addWidget(self.boxSpec, 2, 2, 1, 1)
        self.boxStrPodr = COrgStructureComboBox(PersonsListDialog)
        self.boxStrPodr.setObjectName(_fromUtf8("boxStrPodr"))
        self.gridLayout.addWidget(self.boxStrPodr, 0, 2, 1, 1)
        self.chkUserLogin = QtGui.QCheckBox(PersonsListDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkUserLogin.sizePolicy().hasHeightForWidth())
        self.chkUserLogin.setSizePolicy(sizePolicy)
        self.chkUserLogin.setObjectName(_fromUtf8("chkUserLogin"))
        self.gridLayout.addWidget(self.chkUserLogin, 7, 0, 1, 1)
        self.chkUserRightsProfile = QtGui.QCheckBox(PersonsListDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkUserRightsProfile.sizePolicy().hasHeightForWidth())
        self.chkUserRightsProfile.setSizePolicy(sizePolicy)
        self.chkUserRightsProfile.setObjectName(_fromUtf8("chkUserRightsProfile"))
        self.gridLayout.addWidget(self.chkUserRightsProfile, 5, 0, 1, 1)
        self.chkStrPodr = QtGui.QCheckBox(PersonsListDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkStrPodr.sizePolicy().hasHeightForWidth())
        self.chkStrPodr.setSizePolicy(sizePolicy)
        self.chkStrPodr.setObjectName(_fromUtf8("chkStrPodr"))
        self.gridLayout.addWidget(self.chkStrPodr, 0, 0, 1, 1)
        self.cmbUserRightsProfile = CDbComboBox(PersonsListDialog)
        self.cmbUserRightsProfile.setObjectName(_fromUtf8("cmbUserRightsProfile"))
        self.gridLayout.addWidget(self.cmbUserRightsProfile, 5, 2, 1, 1)
        self.cmbActivity = QtGui.QComboBox(PersonsListDialog)
        self.cmbActivity.setObjectName(_fromUtf8("cmbActivity"))
        self.gridLayout.addWidget(self.cmbActivity, 3, 2, 1, 1)
        self.chkLPU = QtGui.QCheckBox(PersonsListDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkLPU.sizePolicy().hasHeightForWidth())
        self.chkLPU.setSizePolicy(sizePolicy)
        self.chkLPU.setObjectName(_fromUtf8("chkLPU"))
        self.gridLayout.addWidget(self.chkLPU, 4, 0, 1, 1)
        self.chkSurname = QtGui.QCheckBox(PersonsListDialog)
        self.chkSurname.setObjectName(_fromUtf8("chkSurname"))
        self.gridLayout.addWidget(self.chkSurname, 6, 0, 1, 1)
        self.chkSpec = QtGui.QCheckBox(PersonsListDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSpec.sizePolicy().hasHeightForWidth())
        self.chkSpec.setSizePolicy(sizePolicy)
        self.chkSpec.setObjectName(_fromUtf8("chkSpec"))
        self.gridLayout.addWidget(self.chkSpec, 2, 0, 1, 1)
        self.chkActivity = QtGui.QCheckBox(PersonsListDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkActivity.sizePolicy().hasHeightForWidth())
        self.chkActivity.setSizePolicy(sizePolicy)
        self.chkActivity.setObjectName(_fromUtf8("chkActivity"))
        self.gridLayout.addWidget(self.chkActivity, 3, 0, 1, 1)
        self.edtUserLogin = QtGui.QLineEdit(PersonsListDialog)
        self.edtUserLogin.setObjectName(_fromUtf8("edtUserLogin"))
        self.gridLayout.addWidget(self.edtUserLogin, 7, 2, 1, 1)
        self.cmbPost = CRBComboBox(PersonsListDialog)
        self.cmbPost.setObjectName(_fromUtf8("cmbPost"))
        self.gridLayout.addWidget(self.cmbPost, 1, 2, 1, 1)
        self.chkPost = QtGui.QCheckBox(PersonsListDialog)
        self.chkPost.setObjectName(_fromUtf8("chkPost"))
        self.gridLayout.addWidget(self.chkPost, 1, 0, 1, 1)
        self.edtSurname = QtGui.QLineEdit(PersonsListDialog)
        self.edtSurname.setObjectName(_fromUtf8("edtSurname"))
        self.gridLayout.addWidget(self.edtSurname, 6, 2, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.label = QtGui.QLabel(PersonsListDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.hboxlayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.chkOnlyOwn = QtGui.QCheckBox(PersonsListDialog)
        self.chkOnlyOwn.setChecked(True)
        self.chkOnlyOwn.setObjectName(_fromUtf8("chkOnlyOwn"))
        self.hboxlayout.addWidget(self.chkOnlyOwn)
        self.chkOnlyWorking = QtGui.QCheckBox(PersonsListDialog)
        self.chkOnlyWorking.setChecked(True)
        self.chkOnlyWorking.setObjectName(_fromUtf8("chkOnlyWorking"))
        self.hboxlayout.addWidget(self.chkOnlyWorking)
        self.chkOnlyRetired = QtGui.QCheckBox(PersonsListDialog)
        self.chkOnlyRetired.setObjectName(_fromUtf8("chkOnlyRetired"))
        self.hboxlayout.addWidget(self.chkOnlyRetired)
        self.chkChairPerson = QtGui.QCheckBox(PersonsListDialog)
        self.chkChairPerson.setObjectName(_fromUtf8("chkChairPerson"))
        self.hboxlayout.addWidget(self.chkChairPerson)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(PersonsListDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.hboxlayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.hboxlayout, 12, 0, 1, 3)
        self.chkSNILS = QtGui.QCheckBox(PersonsListDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSNILS.sizePolicy().hasHeightForWidth())
        self.chkSNILS.setSizePolicy(sizePolicy)
        self.chkSNILS.setObjectName(_fromUtf8("chkSNILS"))
        self.gridLayout.addWidget(self.chkSNILS, 8, 0, 1, 1)
        self.edtSNILS = QtGui.QLineEdit(PersonsListDialog)
        self.edtSNILS.setEnabled(True)
        self.edtSNILS.setObjectName(_fromUtf8("edtSNILS"))
        self.gridLayout.addWidget(self.edtSNILS, 8, 2, 1, 1)

        self.retranslateUi(PersonsListDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PersonsListDialog.close)
        QtCore.QMetaObject.connectSlotsByName(PersonsListDialog)
        PersonsListDialog.setTabOrder(self.buttonBox, self.chkStrPodr)
        PersonsListDialog.setTabOrder(self.chkStrPodr, self.boxStrPodr)
        PersonsListDialog.setTabOrder(self.boxStrPodr, self.chkSpec)
        PersonsListDialog.setTabOrder(self.chkSpec, self.boxSpec)
        PersonsListDialog.setTabOrder(self.boxSpec, self.chkActivity)
        PersonsListDialog.setTabOrder(self.chkActivity, self.cmbActivity)
        PersonsListDialog.setTabOrder(self.cmbActivity, self.chkLPU)
        PersonsListDialog.setTabOrder(self.chkLPU, self.boxLPU)
        PersonsListDialog.setTabOrder(self.boxLPU, self.chkUserRightsProfile)
        PersonsListDialog.setTabOrder(self.chkUserRightsProfile, self.cmbUserRightsProfile)
        PersonsListDialog.setTabOrder(self.cmbUserRightsProfile, self.chkOnlyOwn)
        PersonsListDialog.setTabOrder(self.chkOnlyOwn, self.chkOnlyWorking)
        PersonsListDialog.setTabOrder(self.chkOnlyWorking, self.chkChairPerson)
        PersonsListDialog.setTabOrder(self.chkChairPerson, self.chkUserLogin)
        PersonsListDialog.setTabOrder(self.chkUserLogin, self.edtUserLogin)

    def retranslateUi(self, PersonsListDialog):
        PersonsListDialog.setWindowTitle(_translate("PersonsListDialog", "Список записей", None))
        self.tblItems.setWhatsThis(_translate("PersonsListDialog", "список записей", "ура!"))
        self.chkUserLogin.setText(_translate("PersonsListDialog", "Регистрационное имя", None))
        self.chkUserRightsProfile.setText(_translate("PersonsListDialog", "Профиль прав", None))
        self.chkStrPodr.setText(_translate("PersonsListDialog", "Структурное подразделение", None))
        self.chkLPU.setText(_translate("PersonsListDialog", "Внешнее ЛПУ", None))
        self.chkSurname.setText(_translate("PersonsListDialog", "Фамилия", None))
        self.chkSpec.setText(_translate("PersonsListDialog", "Специальность", None))
        self.chkActivity.setText(_translate("PersonsListDialog", "Вид деятельности", None))
        self.chkPost.setText(_translate("PersonsListDialog", "Должность", None))
        self.label.setText(_translate("PersonsListDialog", "всего: ", None))
        self.chkOnlyOwn.setText(_translate("PersonsListDialog", "Только свои", None))
        self.chkOnlyWorking.setText(_translate("PersonsListDialog", "Только работающие", None))
        self.chkOnlyRetired.setText(_translate("PersonsListDialog", "Уволенные", None))
        self.chkChairPerson.setText(_translate("PersonsListDialog", "Председатель ВК", None))
        self.chkSNILS.setText(_translate("PersonsListDialog", "СНИЛС", None))
        self.edtSNILS.setInputMask(_translate("PersonsListDialog", "999-999-999 99; ", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.DbComboBox import CDbComboBox
from library.TableView import CTableView
from library.crbcombobox import CRBComboBox
