# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MedServiceProfileDialog(object):
    def setupUi(self, MedServiceProfileDialog):
        MedServiceProfileDialog.setObjectName(_fromUtf8("MedServiceProfileDialog"))
        MedServiceProfileDialog.resize(573, 348)
        self.gridLayout_6 = QtGui.QGridLayout(MedServiceProfileDialog)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblAddress = QtGui.QLabel(MedServiceProfileDialog)
        self.lblAddress.setObjectName(_fromUtf8("lblAddress"))
        self.horizontalLayout.addWidget(self.lblAddress)
        self.edtAddress = QtGui.QLineEdit(MedServiceProfileDialog)
        self.edtAddress.setObjectName(_fromUtf8("edtAddress"))
        self.horizontalLayout.addWidget(self.edtAddress)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblContactValue = QtGui.QLabel(MedServiceProfileDialog)
        self.lblContactValue.setObjectName(_fromUtf8("lblContactValue"))
        self.horizontalLayout_2.addWidget(self.lblContactValue)
        self.edtContactValue = QtGui.QLineEdit(MedServiceProfileDialog)
        self.edtContactValue.setObjectName(_fromUtf8("edtContactValue"))
        self.horizontalLayout_2.addWidget(self.edtContactValue)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblSite = QtGui.QLabel(MedServiceProfileDialog)
        self.lblSite.setObjectName(_fromUtf8("lblSite"))
        self.horizontalLayout_3.addWidget(self.lblSite)
        self.edtSite = QtGui.QLineEdit(MedServiceProfileDialog)
        self.edtSite.setObjectName(_fromUtf8("edtSite"))
        self.horizontalLayout_3.addWidget(self.edtSite)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblProfileMedService = QtGui.QLabel(MedServiceProfileDialog)
        self.lblProfileMedService.setObjectName(_fromUtf8("lblProfileMedService"))
        self.horizontalLayout_4.addWidget(self.lblProfileMedService)
        self.cmbProfileMedService = CRBComboBox(MedServiceProfileDialog)
        self.cmbProfileMedService.setObjectName(_fromUtf8("cmbProfileMedService"))
        self.horizontalLayout_4.addWidget(self.cmbProfileMedService)
        self.horizontalLayout_4.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblStartDate = QtGui.QLabel(MedServiceProfileDialog)
        self.lblStartDate.setObjectName(_fromUtf8("lblStartDate"))
        self.horizontalLayout_6.addWidget(self.lblStartDate)
        self.dteStartDate = CDateEdit(MedServiceProfileDialog)
        self.dteStartDate.setObjectName(_fromUtf8("dteStartDate"))
        self.horizontalLayout_6.addWidget(self.dteStartDate)
        self.horizontalLayout_6.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblEndDate = QtGui.QLabel(MedServiceProfileDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 0, 0, 1, 1)
        self.dteEndDate = CDateEdit(MedServiceProfileDialog)
        self.dteEndDate.setObjectName(_fromUtf8("dteEndDate"))
        self.gridLayout.addWidget(self.dteEndDate, 0, 1, 1, 1)
        self.lblIdlpu = QtGui.QLabel(MedServiceProfileDialog)
        self.lblIdlpu.setObjectName(_fromUtf8("lblIdlpu"))
        self.gridLayout.addWidget(self.lblIdlpu, 1, 0, 1, 1)
        self.cmbLpuId = COrgStructureComboBox(MedServiceProfileDialog)
        self.cmbLpuId.setObjectName(_fromUtf8("cmbLpuId"))
        self.gridLayout.addWidget(self.cmbLpuId, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 5, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 2, 1)
        self.lblComment = QtGui.QLabel(MedServiceProfileDialog)
        self.lblComment.setObjectName(_fromUtf8("lblComment"))
        self.gridLayout_3.addWidget(self.lblComment, 0, 1, 1, 1)
        self.editComment = QtGui.QPlainTextEdit(MedServiceProfileDialog)
        self.editComment.setObjectName(_fromUtf8("editComment"))
        self.gridLayout_3.addWidget(self.editComment, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 1)
        self.btnOk = QtGui.QPushButton(MedServiceProfileDialog)
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.gridLayout_5.addWidget(self.btnOk, 0, 1, 1, 1)
        self.btnCancel = QtGui.QPushButton(MedServiceProfileDialog)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.gridLayout_5.addWidget(self.btnCancel, 0, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.lblAddress.setBuddy(self.edtAddress)
        self.lblContactValue.setBuddy(self.edtContactValue)
        self.lblSite.setBuddy(self.edtSite)
        self.lblProfileMedService.setBuddy(self.cmbProfileMedService)
        self.lblStartDate.setBuddy(self.dteStartDate)
        self.lblEndDate.setBuddy(self.dteEndDate)
        self.lblComment.setBuddy(self.editComment)

        self.retranslateUi(MedServiceProfileDialog)
        QtCore.QObject.connect(self.btnCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), MedServiceProfileDialog.reject)
        QtCore.QObject.connect(self.btnOk, QtCore.SIGNAL(_fromUtf8("clicked()")), MedServiceProfileDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(MedServiceProfileDialog)
        MedServiceProfileDialog.setTabOrder(self.edtAddress, self.edtContactValue)
        MedServiceProfileDialog.setTabOrder(self.edtContactValue, self.edtSite)
        MedServiceProfileDialog.setTabOrder(self.edtSite, self.cmbProfileMedService)
        MedServiceProfileDialog.setTabOrder(self.cmbProfileMedService, self.dteStartDate)
        MedServiceProfileDialog.setTabOrder(self.dteStartDate, self.dteEndDate)
        MedServiceProfileDialog.setTabOrder(self.dteEndDate, self.editComment)
        MedServiceProfileDialog.setTabOrder(self.editComment, self.btnOk)
        MedServiceProfileDialog.setTabOrder(self.btnOk, self.btnCancel)

    def retranslateUi(self, MedServiceProfileDialog):
        MedServiceProfileDialog.setWindowTitle(_translate("MedServiceProfileDialog", "Dialog", None))
        self.lblAddress.setToolTip(_translate("MedServiceProfileDialog", "Адрес медицинской организации", None))
        self.lblAddress.setText(_translate("MedServiceProfileDialog", "Адрес", None))
        self.lblContactValue.setToolTip(_translate("MedServiceProfileDialog", "Телефон медицинской организации", None))
        self.lblContactValue.setText(_translate("MedServiceProfileDialog", "Телефон", None))
        self.lblSite.setText(_translate("MedServiceProfileDialog", "Сайт", None))
        self.lblProfileMedService.setToolTip(_translate("MedServiceProfileDialog", "Идентификатор составного профиля помощи", None))
        self.lblProfileMedService.setText(_translate("MedServiceProfileDialog", "Профиль помощи", None))
        self.lblStartDate.setToolTip(_translate("MedServiceProfileDialog", "Дата начала периода приема направлений по профилю в адрес целевой МО", None))
        self.lblStartDate.setText(_translate("MedServiceProfileDialog", "Дата начала", None))
        self.lblEndDate.setToolTip(_translate("MedServiceProfileDialog", "Дата окончания периода приема направлений по профилю в адрес целевой МО", None))
        self.lblEndDate.setText(_translate("MedServiceProfileDialog", "Дата окончания", None))
        self.lblIdlpu.setText(_translate("MedServiceProfileDialog", "Подразделение", None))
        self.lblComment.setToolTip(_translate("MedServiceProfileDialog", "Комментарий о режиме работы с направленными пациентами", None))
        self.lblComment.setText(_translate("MedServiceProfileDialog", "Комментарий", None))
        self.btnOk.setText(_translate("MedServiceProfileDialog", "Сохранить", None))
        self.btnCancel.setText(_translate("MedServiceProfileDialog", "Отмена", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
