# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\Stock\IncomingInvoice.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IncomingInvoiceDialog(object):
    def setupUi(self, IncomingInvoiceDialog):
        IncomingInvoiceDialog.setObjectName(_fromUtf8("IncomingInvoiceDialog"))
        IncomingInvoiceDialog.resize(617, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Icon2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        IncomingInvoiceDialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(IncomingInvoiceDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtInvoiceNumber = QtGui.QLineEdit(IncomingInvoiceDialog)
        self.edtInvoiceNumber.setObjectName(_fromUtf8("edtInvoiceNumber"))
        self.gridLayout.addWidget(self.edtInvoiceNumber, 10, 5, 1, 1)
        self.lblInvoiceNumber = QtGui.QLabel(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInvoiceNumber.sizePolicy().hasHeightForWidth())
        self.lblInvoiceNumber.setSizePolicy(sizePolicy)
        self.lblInvoiceNumber.setObjectName(_fromUtf8("lblInvoiceNumber"))
        self.gridLayout.addWidget(self.lblInvoiceNumber, 10, 4, 1, 1)
        self.lblNote = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout.addWidget(self.lblNote, 16, 0, 1, 1)
        self.lblReceiver = QtGui.QLabel(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblReceiver.sizePolicy().hasHeightForWidth())
        self.lblReceiver.setSizePolicy(sizePolicy)
        self.lblReceiver.setObjectName(_fromUtf8("lblReceiver"))
        self.gridLayout.addWidget(self.lblReceiver, 14, 0, 1, 1)
        self.lblFinance = QtGui.QLabel(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFinance.sizePolicy().hasHeightForWidth())
        self.lblFinance.setSizePolicy(sizePolicy)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 5, 0, 1, 1)
        self.lblReason = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblReason.setObjectName(_fromUtf8("lblReason"))
        self.gridLayout.addWidget(self.lblReason, 4, 0, 1, 1)
        self.edtDate = CDateEdit(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        self.edtDate.setCalendarPopup(True)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout.addWidget(self.edtDate, 10, 1, 1, 2)
        self.lblDate = QtGui.QLabel(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 10, 0, 1, 1)
        self.lblSupplierOrg = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblSupplierOrg.setObjectName(_fromUtf8("lblSupplierOrg"))
        self.gridLayout.addWidget(self.lblSupplierOrg, 1, 0, 1, 1)
        self.lblInvoiceDate = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblInvoiceDate.setObjectName(_fromUtf8("lblInvoiceDate"))
        self.gridLayout.addWidget(self.lblInvoiceDate, 10, 6, 1, 1)
        self.lblContractType = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblContractType.setObjectName(_fromUtf8("lblContractType"))
        self.gridLayout.addWidget(self.lblContractType, 6, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(IncomingInvoiceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 19, 0, 1, 9)
        self.cmbConfirmationOrder = QtGui.QComboBox(IncomingInvoiceDialog)
        self.cmbConfirmationOrder.setEnabled(False)
        self.cmbConfirmationOrder.setObjectName(_fromUtf8("cmbConfirmationOrder"))
        self.cmbConfirmationOrder.addItem(_fromUtf8(""))
        self.cmbConfirmationOrder.addItem(_fromUtf8(""))
        self.cmbConfirmationOrder.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbConfirmationOrder, 9, 1, 1, 8)
        self.cmbFinance = CRBComboBox(IncomingInvoiceDialog)
        self.cmbFinance.setEnabled(False)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 5, 1, 1, 8)
        self.lblDocDate = QtGui.QLabel(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDocDate.sizePolicy().hasHeightForWidth())
        self.lblDocDate.setSizePolicy(sizePolicy)
        self.lblDocDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDocDate.setObjectName(_fromUtf8("lblDocDate"))
        self.gridLayout.addWidget(self.lblDocDate, 0, 6, 1, 1)
        self.cmbSupplierOrg = COrgComboBox(IncomingInvoiceDialog)
        self.cmbSupplierOrg.setObjectName(_fromUtf8("cmbSupplierOrg"))
        self.gridLayout.addWidget(self.cmbSupplierOrg, 1, 1, 1, 7)
        self.cmbReceiver = CStorageComboBox(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReceiver.sizePolicy().hasHeightForWidth())
        self.cmbReceiver.setSizePolicy(sizePolicy)
        self.cmbReceiver.setObjectName(_fromUtf8("cmbReceiver"))
        self.gridLayout.addWidget(self.cmbReceiver, 14, 1, 1, 8)
        self.cmbReason = CStockPurchaseContractComboBox(IncomingInvoiceDialog)
        self.cmbReason.setObjectName(_fromUtf8("cmbReason"))
        self.gridLayout.addWidget(self.cmbReason, 4, 1, 1, 8)
        self.edtSupplierOrgPerson = QtGui.QLineEdit(IncomingInvoiceDialog)
        self.edtSupplierOrgPerson.setObjectName(_fromUtf8("edtSupplierOrgPerson"))
        self.gridLayout.addWidget(self.edtSupplierOrgPerson, 3, 1, 1, 8)
        self.lblReceiverPerson = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblReceiverPerson.setObjectName(_fromUtf8("lblReceiverPerson"))
        self.gridLayout.addWidget(self.lblReceiverPerson, 15, 0, 1, 1)
        self.edtInvoiceDate = CDateEdit(IncomingInvoiceDialog)
        self.edtInvoiceDate.setCalendarPopup(True)
        self.edtInvoiceDate.setObjectName(_fromUtf8("edtInvoiceDate"))
        self.gridLayout.addWidget(self.edtInvoiceDate, 10, 7, 1, 2)
        self.edtTime = QtGui.QTimeEdit(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTime.sizePolicy().hasHeightForWidth())
        self.edtTime.setSizePolicy(sizePolicy)
        self.edtTime.setObjectName(_fromUtf8("edtTime"))
        self.gridLayout.addWidget(self.edtTime, 10, 3, 1, 1)
        self.lblSupplierOrgPerson = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblSupplierOrgPerson.setObjectName(_fromUtf8("lblSupplierOrgPerson"))
        self.gridLayout.addWidget(self.lblSupplierOrgPerson, 3, 0, 1, 1)
        self.cmbReceiverPerson = CPersonComboBoxEx(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReceiverPerson.sizePolicy().hasHeightForWidth())
        self.cmbReceiverPerson.setSizePolicy(sizePolicy)
        self.cmbReceiverPerson.setObjectName(_fromUtf8("cmbReceiverPerson"))
        self.gridLayout.addWidget(self.cmbReceiverPerson, 15, 1, 1, 8)
        self.lblNumber = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.gridLayout.addWidget(self.lblNumber, 0, 0, 1, 1)
        self.cmbContractType = CContractTypeComboBox(IncomingInvoiceDialog)
        self.cmbContractType.setEnabled(False)
        self.cmbContractType.setObjectName(_fromUtf8("cmbContractType"))
        self.gridLayout.addWidget(self.cmbContractType, 6, 1, 1, 8)
        self.edtDocDate = CDateEdit(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDocDate.sizePolicy().hasHeightForWidth())
        self.edtDocDate.setSizePolicy(sizePolicy)
        self.edtDocDate.setCalendarPopup(True)
        self.edtDocDate.setObjectName(_fromUtf8("edtDocDate"))
        self.gridLayout.addWidget(self.edtDocDate, 0, 7, 1, 2)
        self.lblConfirmationOrder = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblConfirmationOrder.setObjectName(_fromUtf8("lblConfirmationOrder"))
        self.gridLayout.addWidget(self.lblConfirmationOrder, 9, 0, 1, 1)
        self.edtNote = QtGui.QLineEdit(IncomingInvoiceDialog)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 16, 1, 1, 8)
        self.edtNumber = QtGui.QLineEdit(IncomingInvoiceDialog)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout.addWidget(self.edtNumber, 0, 1, 1, 5)
        self.lblPlaceOfBusiness = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblPlaceOfBusiness.setObjectName(_fromUtf8("lblPlaceOfBusiness"))
        self.gridLayout.addWidget(self.lblPlaceOfBusiness, 2, 0, 1, 1)
        self.tblItems = CInDocTableView(IncomingInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblItems.sizePolicy().hasHeightForWidth())
        self.tblItems.setSizePolicy(sizePolicy)
        self.tblItems.setObjectName(_fromUtf8("tblItems"))
        self.gridLayout.addWidget(self.tblItems, 17, 0, 1, 9)
        self.cmbPlaceOfBusiness = CPlaceOfBusinessComboBox(IncomingInvoiceDialog)
        self.cmbPlaceOfBusiness.setObjectName(_fromUtf8("cmbPlaceOfBusiness"))
        self.gridLayout.addWidget(self.cmbPlaceOfBusiness, 2, 1, 1, 7)
        self.btnSelectOrganisation = QtGui.QToolButton(IncomingInvoiceDialog)
        self.btnSelectOrganisation.setObjectName(_fromUtf8("btnSelectOrganisation"))
        self.gridLayout.addWidget(self.btnSelectOrganisation, 1, 8, 1, 1)
        self.lblSummaryInfo = QtGui.QLabel(IncomingInvoiceDialog)
        self.lblSummaryInfo.setText(_fromUtf8(""))
        self.lblSummaryInfo.setObjectName(_fromUtf8("lblSummaryInfo"))
        self.gridLayout.addWidget(self.lblSummaryInfo, 18, 0, 1, 9)
        self.lblNote.setBuddy(self.edtNote)
        self.lblReceiver.setBuddy(self.cmbReceiver)
        self.lblReason.setBuddy(self.cmbReason)
        self.lblDate.setBuddy(self.edtDate)
        self.lblSupplierOrg.setBuddy(self.cmbSupplierOrg)
        self.lblDocDate.setBuddy(self.edtDocDate)
        self.lblReceiverPerson.setBuddy(self.cmbReceiverPerson)
        self.lblSupplierOrgPerson.setBuddy(self.edtSupplierOrgPerson)
        self.lblNumber.setBuddy(self.edtNumber)
        self.lblConfirmationOrder.setBuddy(self.cmbConfirmationOrder)

        self.retranslateUi(IncomingInvoiceDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), IncomingInvoiceDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), IncomingInvoiceDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(IncomingInvoiceDialog)
        IncomingInvoiceDialog.setTabOrder(self.edtNumber, self.cmbSupplierOrg)
        IncomingInvoiceDialog.setTabOrder(self.cmbSupplierOrg, self.edtSupplierOrgPerson)
        IncomingInvoiceDialog.setTabOrder(self.edtSupplierOrgPerson, self.cmbReason)
        IncomingInvoiceDialog.setTabOrder(self.cmbReason, self.cmbFinance)
        IncomingInvoiceDialog.setTabOrder(self.cmbFinance, self.cmbConfirmationOrder)
        IncomingInvoiceDialog.setTabOrder(self.cmbConfirmationOrder, self.edtDate)
        IncomingInvoiceDialog.setTabOrder(self.edtDate, self.edtTime)
        IncomingInvoiceDialog.setTabOrder(self.edtTime, self.edtInvoiceNumber)
        IncomingInvoiceDialog.setTabOrder(self.edtInvoiceNumber, self.edtInvoiceDate)
        IncomingInvoiceDialog.setTabOrder(self.edtInvoiceDate, self.cmbReceiver)
        IncomingInvoiceDialog.setTabOrder(self.cmbReceiver, self.cmbReceiverPerson)
        IncomingInvoiceDialog.setTabOrder(self.cmbReceiverPerson, self.edtNote)
        IncomingInvoiceDialog.setTabOrder(self.edtNote, self.tblItems)
        IncomingInvoiceDialog.setTabOrder(self.tblItems, self.buttonBox)

    def retranslateUi(self, IncomingInvoiceDialog):
        IncomingInvoiceDialog.setWindowTitle(_translate("IncomingInvoiceDialog", "Приходная накладная от внешнего поставщика", None))
        self.lblInvoiceNumber.setText(_translate("IncomingInvoiceDialog", "Счет-фактура", None))
        self.lblNote.setText(_translate("IncomingInvoiceDialog", "При&мечания", None))
        self.lblReceiver.setText(_translate("IncomingInvoiceDialog", "По&лучатель", None))
        self.lblFinance.setText(_translate("IncomingInvoiceDialog", "Тип финансирования", None))
        self.lblReason.setText(_translate("IncomingInvoiceDialog", "О&снование", None))
        self.lblDate.setText(_translate("IncomingInvoiceDialog", "Дата опри&ходования", None))
        self.lblSupplierOrg.setText(_translate("IncomingInvoiceDialog", "Внешний &поставщик", None))
        self.lblInvoiceDate.setText(_translate("IncomingInvoiceDialog", "Дата счета-фактуры", None))
        self.lblContractType.setText(_translate("IncomingInvoiceDialog", "Тип договора", None))
        self.cmbConfirmationOrder.setItemText(0, _translate("IncomingInvoiceDialog", "-", None))
        self.cmbConfirmationOrder.setItemText(1, _translate("IncomingInvoiceDialog", "Прямой", None))
        self.cmbConfirmationOrder.setItemText(2, _translate("IncomingInvoiceDialog", "Обратный", None))
        self.lblDocDate.setText(_translate("IncomingInvoiceDialog", "&Дата документа", None))
        self.lblReceiverPerson.setText(_translate("IncomingInvoiceDialog", "О&тветственный", None))
        self.edtTime.setDisplayFormat(_translate("IncomingInvoiceDialog", "HH:mm", None))
        self.lblSupplierOrgPerson.setText(_translate("IncomingInvoiceDialog", "&Ответственный", None))
        self.lblNumber.setText(_translate("IncomingInvoiceDialog", "&Номер", None))
        self.lblConfirmationOrder.setText(_translate("IncomingInvoiceDialog", "По&рядок подтверждения", None))
        self.lblPlaceOfBusiness.setText(_translate("IncomingInvoiceDialog", "МОД", None))
        self.btnSelectOrganisation.setText(_translate("IncomingInvoiceDialog", "...", None))

from Orgs.OrgComboBox import COrgComboBox
from Orgs.OrgStructComboBoxes import CStorageComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Stock.StockPurchaseContractComboBox import CStockPurchaseContractComboBox
from Stock.Utils import CContractTypeComboBox, CPlaceOfBusinessComboBox
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
import s11main_rc
