# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\Stock\Inventory.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_InventoryDialog(object):
    def setupUi(self, InventoryDialog):
        InventoryDialog.setObjectName(_fromUtf8("InventoryDialog"))
        InventoryDialog.resize(599, 500)
        self.gridLayout = QtGui.QGridLayout(InventoryDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblNumber = QtGui.QLabel(InventoryDialog)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.gridLayout.addWidget(self.lblNumber, 0, 0, 1, 1)
        self.edtNumber = QtGui.QLineEdit(InventoryDialog)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout.addWidget(self.edtNumber, 0, 1, 1, 1)
        self.lblDate = QtGui.QLabel(InventoryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 0, 2, 1, 1)
        self.edtDate = CDateEdit(InventoryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout.addWidget(self.edtDate, 0, 3, 1, 1)
        self.edtTime = QtGui.QTimeEdit(InventoryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTime.sizePolicy().hasHeightForWidth())
        self.edtTime.setSizePolicy(sizePolicy)
        self.edtTime.setObjectName(_fromUtf8("edtTime"))
        self.gridLayout.addWidget(self.edtTime, 0, 4, 1, 1)
        self.lblReason = QtGui.QLabel(InventoryDialog)
        self.lblReason.setObjectName(_fromUtf8("lblReason"))
        self.gridLayout.addWidget(self.lblReason, 1, 0, 1, 1)
        self.edtReason = QtGui.QLineEdit(InventoryDialog)
        self.edtReason.setObjectName(_fromUtf8("edtReason"))
        self.gridLayout.addWidget(self.edtReason, 1, 1, 1, 1)
        self.lblReasonDate = QtGui.QLabel(InventoryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblReasonDate.sizePolicy().hasHeightForWidth())
        self.lblReasonDate.setSizePolicy(sizePolicy)
        self.lblReasonDate.setObjectName(_fromUtf8("lblReasonDate"))
        self.gridLayout.addWidget(self.lblReasonDate, 1, 2, 1, 1)
        self.edtReasonDate = CDateEdit(InventoryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtReasonDate.sizePolicy().hasHeightForWidth())
        self.edtReasonDate.setSizePolicy(sizePolicy)
        self.edtReasonDate.setObjectName(_fromUtf8("edtReasonDate"))
        self.gridLayout.addWidget(self.edtReasonDate, 1, 3, 1, 1)
        self.lblSupplier = QtGui.QLabel(InventoryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSupplier.sizePolicy().hasHeightForWidth())
        self.lblSupplier.setSizePolicy(sizePolicy)
        self.lblSupplier.setObjectName(_fromUtf8("lblSupplier"))
        self.gridLayout.addWidget(self.lblSupplier, 2, 0, 1, 1)
        self.cmbSupplier = CStorageComboBox(InventoryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplier.sizePolicy().hasHeightForWidth())
        self.cmbSupplier.setSizePolicy(sizePolicy)
        self.cmbSupplier.setObjectName(_fromUtf8("cmbSupplier"))
        self.gridLayout.addWidget(self.cmbSupplier, 2, 1, 1, 4)
        self.lblSupplierPerson = QtGui.QLabel(InventoryDialog)
        self.lblSupplierPerson.setObjectName(_fromUtf8("lblSupplierPerson"))
        self.gridLayout.addWidget(self.lblSupplierPerson, 3, 0, 1, 1)
        self.cmbSupplierPerson = CPersonComboBoxEx(InventoryDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplierPerson.sizePolicy().hasHeightForWidth())
        self.cmbSupplierPerson.setSizePolicy(sizePolicy)
        self.cmbSupplierPerson.setObjectName(_fromUtf8("cmbSupplierPerson"))
        self.gridLayout.addWidget(self.cmbSupplierPerson, 3, 1, 1, 4)
        self.lblNote = QtGui.QLabel(InventoryDialog)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout.addWidget(self.lblNote, 4, 0, 1, 1)
        self.edtNote = QtGui.QLineEdit(InventoryDialog)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 4, 1, 1, 4)
        self.tabWidget = QtGui.QTabWidget(InventoryDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabItems = QtGui.QWidget()
        self.tabItems.setObjectName(_fromUtf8("tabItems"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabItems)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblItems = CInventoryInDocTableView(self.tabItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblItems.sizePolicy().hasHeightForWidth())
        self.tblItems.setSizePolicy(sizePolicy)
        self.tblItems.setObjectName(_fromUtf8("tblItems"))
        self.gridLayout_2.addWidget(self.tblItems, 0, 0, 1, 1)
        self.lblSummaryInfo = QtGui.QLabel(self.tabItems)
        self.lblSummaryInfo.setText(_fromUtf8(""))
        self.lblSummaryInfo.setObjectName(_fromUtf8("lblSummaryInfo"))
        self.gridLayout_2.addWidget(self.lblSummaryInfo, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabItems, _fromUtf8(""))
        self.tabCommission = QtGui.QWidget()
        self.tabCommission.setObjectName(_fromUtf8("tabCommission"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabCommission)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblCommission = CInDocTableView(self.tabCommission)
        self.tblCommission.setObjectName(_fromUtf8("tblCommission"))
        self.gridLayout_3.addWidget(self.tblCommission, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabCommission, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 5, 0, 1, 5)
        self.buttonBox = QtGui.QDialogButtonBox(InventoryDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 5)
        self.lblNumber.setBuddy(self.edtNumber)
        self.lblDate.setBuddy(self.edtDate)
        self.lblReason.setBuddy(self.edtReason)
        self.lblReasonDate.setBuddy(self.edtReasonDate)
        self.lblSupplier.setBuddy(self.cmbSupplier)
        self.lblSupplierPerson.setBuddy(self.cmbSupplierPerson)
        self.lblNote.setBuddy(self.edtNote)

        self.retranslateUi(InventoryDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), InventoryDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), InventoryDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(InventoryDialog)
        InventoryDialog.setTabOrder(self.edtNumber, self.edtDate)
        InventoryDialog.setTabOrder(self.edtDate, self.edtTime)
        InventoryDialog.setTabOrder(self.edtTime, self.edtReason)
        InventoryDialog.setTabOrder(self.edtReason, self.edtReasonDate)
        InventoryDialog.setTabOrder(self.edtReasonDate, self.cmbSupplier)
        InventoryDialog.setTabOrder(self.cmbSupplier, self.cmbSupplierPerson)
        InventoryDialog.setTabOrder(self.cmbSupplierPerson, self.edtNote)
        InventoryDialog.setTabOrder(self.edtNote, self.buttonBox)

    def retranslateUi(self, InventoryDialog):
        InventoryDialog.setWindowTitle(_translate("InventoryDialog", "Акт инвентаризации ЛСиИМН", None))
        self.lblNumber.setText(_translate("InventoryDialog", "Номер", None))
        self.lblDate.setText(_translate("InventoryDialog", "Дата", None))
        self.edtTime.setDisplayFormat(_translate("InventoryDialog", "HH:mm", None))
        self.lblReason.setText(_translate("InventoryDialog", "Основание", None))
        self.lblReasonDate.setText(_translate("InventoryDialog", "Дата основания", None))
        self.lblSupplier.setText(_translate("InventoryDialog", "Подразделение", None))
        self.lblSupplierPerson.setText(_translate("InventoryDialog", "Ответственный", None))
        self.lblNote.setText(_translate("InventoryDialog", "Примечания", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabItems), _translate("InventoryDialog", "ЛСиИМН", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCommission), _translate("InventoryDialog", "Состав комиссии", None))

from Orgs.OrgStructComboBoxes import CStorageComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Stock.InventoryInDocTableView import CInventoryInDocTableView
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
