# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\Stock\InternalInvoice.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_InternalInvoiceDialog(object):
    def setupUi(self, InternalInvoiceDialog):
        InternalInvoiceDialog.setObjectName(_fromUtf8("InternalInvoiceDialog"))
        InternalInvoiceDialog.resize(600, 500)
        self.gridLayout = QtGui.QGridLayout(InternalInvoiceDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtNote = QtGui.QLineEdit(InternalInvoiceDialog)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 8, 1, 1, 4)
        self.edtTime = QtGui.QTimeEdit(InternalInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTime.sizePolicy().hasHeightForWidth())
        self.edtTime.setSizePolicy(sizePolicy)
        self.edtTime.setObjectName(_fromUtf8("edtTime"))
        self.gridLayout.addWidget(self.edtTime, 0, 4, 1, 1)
        self.lblReceiver = QtGui.QLabel(InternalInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblReceiver.sizePolicy().hasHeightForWidth())
        self.lblReceiver.setSizePolicy(sizePolicy)
        self.lblReceiver.setObjectName(_fromUtf8("lblReceiver"))
        self.gridLayout.addWidget(self.lblReceiver, 5, 0, 1, 1)
        self.lblNote = QtGui.QLabel(InternalInvoiceDialog)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout.addWidget(self.lblNote, 8, 0, 1, 1)
        self.lblReceiverPerson = QtGui.QLabel(InternalInvoiceDialog)
        self.lblReceiverPerson.setObjectName(_fromUtf8("lblReceiverPerson"))
        self.gridLayout.addWidget(self.lblReceiverPerson, 7, 0, 1, 1)
        self.edtDate = CDateEdit(InternalInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout.addWidget(self.edtDate, 0, 3, 1, 1)
        self.lblSupplierPerson = QtGui.QLabel(InternalInvoiceDialog)
        self.lblSupplierPerson.setObjectName(_fromUtf8("lblSupplierPerson"))
        self.gridLayout.addWidget(self.lblSupplierPerson, 4, 0, 1, 1)
        self.cmbSupplierPerson = CPersonComboBoxEx(InternalInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplierPerson.sizePolicy().hasHeightForWidth())
        self.cmbSupplierPerson.setSizePolicy(sizePolicy)
        self.cmbSupplierPerson.setObjectName(_fromUtf8("cmbSupplierPerson"))
        self.gridLayout.addWidget(self.cmbSupplierPerson, 4, 1, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(InternalInvoiceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 11, 0, 1, 5)
        self.edtNumber = QtGui.QLineEdit(InternalInvoiceDialog)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout.addWidget(self.edtNumber, 0, 1, 1, 1)
        self.lblReasonDate = QtGui.QLabel(InternalInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblReasonDate.sizePolicy().hasHeightForWidth())
        self.lblReasonDate.setSizePolicy(sizePolicy)
        self.lblReasonDate.setObjectName(_fromUtf8("lblReasonDate"))
        self.gridLayout.addWidget(self.lblReasonDate, 1, 2, 1, 1)
        self.lblSupplier = QtGui.QLabel(InternalInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSupplier.sizePolicy().hasHeightForWidth())
        self.lblSupplier.setSizePolicy(sizePolicy)
        self.lblSupplier.setObjectName(_fromUtf8("lblSupplier"))
        self.gridLayout.addWidget(self.lblSupplier, 3, 0, 1, 1)
        self.edtReason = QtGui.QLineEdit(InternalInvoiceDialog)
        self.edtReason.setObjectName(_fromUtf8("edtReason"))
        self.gridLayout.addWidget(self.edtReason, 1, 1, 1, 1)
        self.lblReason = QtGui.QLabel(InternalInvoiceDialog)
        self.lblReason.setObjectName(_fromUtf8("lblReason"))
        self.gridLayout.addWidget(self.lblReason, 1, 0, 1, 1)
        self.tblItems = CInDocTableView(InternalInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblItems.sizePolicy().hasHeightForWidth())
        self.tblItems.setSizePolicy(sizePolicy)
        self.tblItems.setObjectName(_fromUtf8("tblItems"))
        self.gridLayout.addWidget(self.tblItems, 9, 0, 1, 5)
        self.cmbReceiverPerson = CPersonComboBoxEx(InternalInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReceiverPerson.sizePolicy().hasHeightForWidth())
        self.cmbReceiverPerson.setSizePolicy(sizePolicy)
        self.cmbReceiverPerson.setObjectName(_fromUtf8("cmbReceiverPerson"))
        self.gridLayout.addWidget(self.cmbReceiverPerson, 7, 1, 1, 4)
        self.lblDate = QtGui.QLabel(InternalInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 0, 2, 1, 1)
        self.lblNumber = QtGui.QLabel(InternalInvoiceDialog)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.gridLayout.addWidget(self.lblNumber, 0, 0, 1, 1)
        self.lblSummaryInfo = QtGui.QLabel(InternalInvoiceDialog)
        self.lblSummaryInfo.setText(_fromUtf8(""))
        self.lblSummaryInfo.setObjectName(_fromUtf8("lblSummaryInfo"))
        self.gridLayout.addWidget(self.lblSummaryInfo, 10, 0, 1, 5)
        self.cmbSupplier = CStorageComboBox(InternalInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplier.sizePolicy().hasHeightForWidth())
        self.cmbSupplier.setSizePolicy(sizePolicy)
        self.cmbSupplier.setObjectName(_fromUtf8("cmbSupplier"))
        self.gridLayout.addWidget(self.cmbSupplier, 3, 1, 1, 4)
        self.edtReasonDate = CDateEdit(InternalInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtReasonDate.sizePolicy().hasHeightForWidth())
        self.edtReasonDate.setSizePolicy(sizePolicy)
        self.edtReasonDate.setObjectName(_fromUtf8("edtReasonDate"))
        self.gridLayout.addWidget(self.edtReasonDate, 1, 3, 1, 1)
        self.cmbReceiver = CStorageComboBox(InternalInvoiceDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReceiver.sizePolicy().hasHeightForWidth())
        self.cmbReceiver.setSizePolicy(sizePolicy)
        self.cmbReceiver.setObjectName(_fromUtf8("cmbReceiver"))
        self.gridLayout.addWidget(self.cmbReceiver, 5, 1, 1, 4)
        self.chkOrgStructureQuarantineZone = QtGui.QCheckBox(InternalInvoiceDialog)
        self.chkOrgStructureQuarantineZone.setObjectName(_fromUtf8("chkOrgStructureQuarantineZone"))
        self.gridLayout.addWidget(self.chkOrgStructureQuarantineZone, 6, 1, 1, 2)
        self.lblReceiver.setBuddy(self.cmbReceiver)
        self.lblNote.setBuddy(self.edtNote)
        self.lblReceiverPerson.setBuddy(self.cmbReceiverPerson)
        self.lblSupplierPerson.setBuddy(self.cmbSupplierPerson)
        self.lblReasonDate.setBuddy(self.edtReasonDate)
        self.lblSupplier.setBuddy(self.cmbSupplier)
        self.lblReason.setBuddy(self.edtReason)
        self.lblDate.setBuddy(self.edtDate)
        self.lblNumber.setBuddy(self.edtNumber)

        self.retranslateUi(InternalInvoiceDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), InternalInvoiceDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), InternalInvoiceDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(InternalInvoiceDialog)
        InternalInvoiceDialog.setTabOrder(self.edtNumber, self.edtDate)
        InternalInvoiceDialog.setTabOrder(self.edtDate, self.edtTime)
        InternalInvoiceDialog.setTabOrder(self.edtTime, self.edtReason)
        InternalInvoiceDialog.setTabOrder(self.edtReason, self.edtReasonDate)
        InternalInvoiceDialog.setTabOrder(self.edtReasonDate, self.cmbSupplier)
        InternalInvoiceDialog.setTabOrder(self.cmbSupplier, self.cmbSupplierPerson)
        InternalInvoiceDialog.setTabOrder(self.cmbSupplierPerson, self.cmbReceiver)
        InternalInvoiceDialog.setTabOrder(self.cmbReceiver, self.cmbReceiverPerson)
        InternalInvoiceDialog.setTabOrder(self.cmbReceiverPerson, self.edtNote)
        InternalInvoiceDialog.setTabOrder(self.edtNote, self.tblItems)
        InternalInvoiceDialog.setTabOrder(self.tblItems, self.buttonBox)

    def retranslateUi(self, InternalInvoiceDialog):
        InternalInvoiceDialog.setWindowTitle(_translate("InternalInvoiceDialog", "Внутренняя накладная на передачу ЛСиИМН", None))
        self.edtTime.setDisplayFormat(_translate("InternalInvoiceDialog", "HH:mm", None))
        self.lblReceiver.setText(_translate("InternalInvoiceDialog", "Получатель", None))
        self.lblNote.setText(_translate("InternalInvoiceDialog", "Примечания", None))
        self.lblReceiverPerson.setText(_translate("InternalInvoiceDialog", "Ответственный", None))
        self.lblSupplierPerson.setText(_translate("InternalInvoiceDialog", "Ответственный", None))
        self.lblReasonDate.setText(_translate("InternalInvoiceDialog", "Дата основания", None))
        self.lblSupplier.setText(_translate("InternalInvoiceDialog", "Поставщик", None))
        self.lblReason.setText(_translate("InternalInvoiceDialog", "Основание", None))
        self.lblDate.setText(_translate("InternalInvoiceDialog", "Дата", None))
        self.lblNumber.setText(_translate("InternalInvoiceDialog", "Номер", None))
        self.chkOrgStructureQuarantineZone.setText(_translate("InternalInvoiceDialog", "Показать подразделения с признаком \"Карантинная зона\"", None))

from Orgs.OrgStructComboBoxes import CStorageComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
