# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\stock2\Stock\NomenclatureComboBoxPopup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NomenclatureComboBoxPopup(object):
    def setupUi(self, NomenclatureComboBoxPopup):
        NomenclatureComboBoxPopup.setObjectName(_fromUtf8("NomenclatureComboBoxPopup"))
        NomenclatureComboBoxPopup.resize(782, 498)
        self.gridLayout = QtGui.QGridLayout(NomenclatureComboBoxPopup)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(NomenclatureComboBoxPopup)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabNomenclature = QtGui.QWidget()
        self.tabNomenclature.setObjectName(_fromUtf8("tabNomenclature"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabNomenclature)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblNomenclature = CSortFilterProxyTableView(self.tabNomenclature)
        self.tblNomenclature.setObjectName(_fromUtf8("tblNomenclature"))
        self.gridLayout_4.addWidget(self.tblNomenclature, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tabNomenclature, _fromUtf8(""))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabSearch)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabSearchAttributes = QtGui.QTabWidget(self.tabSearch)
        self.tabSearchAttributes.setTabPosition(QtGui.QTabWidget.North)
        self.tabSearchAttributes.setObjectName(_fromUtf8("tabSearchAttributes"))
        self.tabMainCharacters = QtGui.QWidget()
        self.tabMainCharacters.setObjectName(_fromUtf8("tabMainCharacters"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabMainCharacters)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cmbKind = CRBComboBox(self.tabMainCharacters)
        self.cmbKind.setObjectName(_fromUtf8("cmbKind"))
        self.gridLayout_2.addWidget(self.cmbKind, 1, 1, 1, 1)
        self.cmbActiveSubstance = CActiveSubstanceComboBox(self.tabMainCharacters)
        self.cmbActiveSubstance.setEnabled(False)
        self.cmbActiveSubstance.setObjectName(_fromUtf8("cmbActiveSubstance"))
        self.gridLayout_2.addWidget(self.cmbActiveSubstance, 12, 1, 1, 1)
        self.lblMedicalAidKind = QtGui.QLabel(self.tabMainCharacters)
        self.lblMedicalAidKind.setEnabled(False)
        self.lblMedicalAidKind.setObjectName(_fromUtf8("lblMedicalAidKind"))
        self.gridLayout_2.addWidget(self.lblMedicalAidKind, 11, 0, 1, 1)
        self.chkOnlyMnnEsklpForm = QtGui.QCheckBox(self.tabMainCharacters)
        self.chkOnlyMnnEsklpForm.setObjectName(_fromUtf8("chkOnlyMnnEsklpForm"))
        self.gridLayout_2.addWidget(self.chkOnlyMnnEsklpForm, 13, 1, 1, 1)
        self.edtName = QtGui.QLineEdit(self.tabMainCharacters)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout_2.addWidget(self.edtName, 5, 1, 1, 1)
        self.lblCode = QtGui.QLabel(self.tabMainCharacters)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout_2.addWidget(self.lblCode, 3, 0, 1, 1)
        self.cmbMedicalAidKind = CRBComboBox(self.tabMainCharacters)
        self.cmbMedicalAidKind.setEnabled(False)
        self.cmbMedicalAidKind.setObjectName(_fromUtf8("cmbMedicalAidKind"))
        self.gridLayout_2.addWidget(self.cmbMedicalAidKind, 11, 1, 1, 1)
        self.chkActiveSubstance = QtGui.QCheckBox(self.tabMainCharacters)
        self.chkActiveSubstance.setObjectName(_fromUtf8("chkActiveSubstance"))
        self.gridLayout_2.addWidget(self.chkActiveSubstance, 12, 0, 1, 1)
        self.btnName = QtGui.QPushButton(self.tabMainCharacters)
        self.btnName.setObjectName(_fromUtf8("btnName"))
        self.gridLayout_2.addWidget(self.btnName, 5, 0, 1, 1)
        self.cmbClass = CRBComboBox(self.tabMainCharacters)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.gridLayout_2.addWidget(self.cmbClass, 0, 1, 1, 1)
        self.lblType = QtGui.QLabel(self.tabMainCharacters)
        self.lblType.setObjectName(_fromUtf8("lblType"))
        self.gridLayout_2.addWidget(self.lblType, 2, 0, 1, 1)
        self.chkIncludeAnalogies = QtGui.QCheckBox(self.tabMainCharacters)
        self.chkIncludeAnalogies.setObjectName(_fromUtf8("chkIncludeAnalogies"))
        self.gridLayout_2.addWidget(self.chkIncludeAnalogies, 14, 1, 1, 1)
        self.edtMnnFilter = QtGui.QLineEdit(self.tabMainCharacters)
        self.edtMnnFilter.setObjectName(_fromUtf8("edtMnnFilter"))
        self.gridLayout_2.addWidget(self.edtMnnFilter, 6, 1, 1, 1)
        self.lblProducer = QtGui.QLabel(self.tabMainCharacters)
        self.lblProducer.setObjectName(_fromUtf8("lblProducer"))
        self.gridLayout_2.addWidget(self.lblProducer, 7, 0, 1, 1)
        self.lblKind = QtGui.QLabel(self.tabMainCharacters)
        self.lblKind.setObjectName(_fromUtf8("lblKind"))
        self.gridLayout_2.addWidget(self.lblKind, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(17, 103, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 17, 0, 1, 1)
        self.cmbType = CRBComboBox(self.tabMainCharacters)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.gridLayout_2.addWidget(self.cmbType, 2, 1, 1, 1)
        self.lblLfForm = QtGui.QLabel(self.tabMainCharacters)
        self.lblLfForm.setObjectName(_fromUtf8("lblLfForm"))
        self.gridLayout_2.addWidget(self.lblLfForm, 9, 0, 1, 1)
        self.cmbFinance = CRBComboBox(self.tabMainCharacters)
        self.cmbFinance.setEnabled(False)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout_2.addWidget(self.cmbFinance, 10, 1, 1, 1)
        self.edtCode = QtGui.QLineEdit(self.tabMainCharacters)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout_2.addWidget(self.edtCode, 3, 1, 1, 1)
        self.lblATC = QtGui.QLabel(self.tabMainCharacters)
        self.lblATC.setObjectName(_fromUtf8("lblATC"))
        self.gridLayout_2.addWidget(self.lblATC, 8, 0, 1, 1)
        self.lblFinance = QtGui.QLabel(self.tabMainCharacters)
        self.lblFinance.setEnabled(False)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout_2.addWidget(self.lblFinance, 10, 0, 1, 1)
        self.lblClass = QtGui.QLabel(self.tabMainCharacters)
        self.lblClass.setObjectName(_fromUtf8("lblClass"))
        self.gridLayout_2.addWidget(self.lblClass, 0, 0, 1, 1)
        self.chkOnlyExists = QtGui.QCheckBox(self.tabMainCharacters)
        self.chkOnlyExists.setObjectName(_fromUtf8("chkOnlyExists"))
        self.gridLayout_2.addWidget(self.chkOnlyExists, 16, 1, 1, 1)
        self.edtProducer = QtGui.QLineEdit(self.tabMainCharacters)
        self.edtProducer.setObjectName(_fromUtf8("edtProducer"))
        self.gridLayout_2.addWidget(self.edtProducer, 7, 1, 1, 1)
        self.edtATC = QtGui.QLineEdit(self.tabMainCharacters)
        self.edtATC.setObjectName(_fromUtf8("edtATC"))
        self.gridLayout_2.addWidget(self.edtATC, 8, 1, 1, 1)
        self.lblMnnFilter = QtGui.QLabel(self.tabMainCharacters)
        self.lblMnnFilter.setObjectName(_fromUtf8("lblMnnFilter"))
        self.gridLayout_2.addWidget(self.lblMnnFilter, 6, 0, 1, 1)
        self.cmbLfForm = CRBComboBox(self.tabMainCharacters)
        self.cmbLfForm.setObjectName(_fromUtf8("cmbLfForm"))
        self.gridLayout_2.addWidget(self.cmbLfForm, 9, 1, 1, 1)
        self.chkOnlyLs = QtGui.QCheckBox(self.tabMainCharacters)
        self.chkOnlyLs.setEnabled(True)
        self.chkOnlyLs.setObjectName(_fromUtf8("chkOnlyLs"))
        self.gridLayout_2.addWidget(self.chkOnlyLs, 15, 1, 1, 1)
        self.lblVEN = QtGui.QLabel(self.tabMainCharacters)
        self.lblVEN.setObjectName(_fromUtf8("lblVEN"))
        self.gridLayout_2.addWidget(self.lblVEN, 4, 0, 1, 1)
        self.cmbVEN = QtGui.QComboBox(self.tabMainCharacters)
        self.cmbVEN.setObjectName(_fromUtf8("cmbVEN"))
        self.cmbVEN.addItem(_fromUtf8(""))
        self.cmbVEN.addItem(_fromUtf8(""))
        self.cmbVEN.addItem(_fromUtf8(""))
        self.cmbVEN.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbVEN, 4, 1, 1, 1)
        self.tabSearchAttributes.addTab(self.tabMainCharacters, _fromUtf8(""))
        self.tabFeatures = QtGui.QWidget()
        self.tabFeatures.setObjectName(_fromUtf8("tabFeatures"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabFeatures)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblFeatures = CInDocTableView(self.tabFeatures)
        self.tblFeatures.setObjectName(_fromUtf8("tblFeatures"))
        self.verticalLayout.addWidget(self.tblFeatures)
        self.tabSearchAttributes.addTab(self.tabFeatures, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabSearchAttributes, 0, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(253, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.tabAdd = QtGui.QWidget()
        self.tabAdd.setObjectName(_fromUtf8("tabAdd"))
        self.tabWidget.addTab(self.tabAdd, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.lblMedicalAidKind.setBuddy(self.cmbMedicalAidKind)
        self.lblCode.setBuddy(self.edtCode)
        self.lblType.setBuddy(self.cmbType)
        self.lblProducer.setBuddy(self.edtProducer)
        self.lblKind.setBuddy(self.cmbKind)
        self.lblLfForm.setBuddy(self.cmbLfForm)
        self.lblATC.setBuddy(self.edtATC)
        self.lblFinance.setBuddy(self.cmbFinance)
        self.lblClass.setBuddy(self.cmbClass)
        self.lblMnnFilter.setBuddy(self.edtMnnFilter)

        self.retranslateUi(NomenclatureComboBoxPopup)
        self.tabWidget.setCurrentIndex(1)
        self.tabSearchAttributes.setCurrentIndex(0)
        QtCore.QObject.connect(self.chkActiveSubstance, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbActiveSubstance.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(NomenclatureComboBoxPopup)
        NomenclatureComboBoxPopup.setTabOrder(self.tabWidget, self.tblNomenclature)
        NomenclatureComboBoxPopup.setTabOrder(self.tblNomenclature, self.tabSearchAttributes)
        NomenclatureComboBoxPopup.setTabOrder(self.tabSearchAttributes, self.cmbClass)
        NomenclatureComboBoxPopup.setTabOrder(self.cmbClass, self.cmbKind)
        NomenclatureComboBoxPopup.setTabOrder(self.cmbKind, self.cmbType)
        NomenclatureComboBoxPopup.setTabOrder(self.cmbType, self.edtCode)
        NomenclatureComboBoxPopup.setTabOrder(self.edtCode, self.btnName)
        NomenclatureComboBoxPopup.setTabOrder(self.btnName, self.edtName)
        NomenclatureComboBoxPopup.setTabOrder(self.edtName, self.edtMnnFilter)
        NomenclatureComboBoxPopup.setTabOrder(self.edtMnnFilter, self.edtProducer)
        NomenclatureComboBoxPopup.setTabOrder(self.edtProducer, self.edtATC)
        NomenclatureComboBoxPopup.setTabOrder(self.edtATC, self.cmbLfForm)
        NomenclatureComboBoxPopup.setTabOrder(self.cmbLfForm, self.cmbFinance)
        NomenclatureComboBoxPopup.setTabOrder(self.cmbFinance, self.cmbMedicalAidKind)
        NomenclatureComboBoxPopup.setTabOrder(self.cmbMedicalAidKind, self.chkActiveSubstance)
        NomenclatureComboBoxPopup.setTabOrder(self.chkActiveSubstance, self.cmbActiveSubstance)
        NomenclatureComboBoxPopup.setTabOrder(self.cmbActiveSubstance, self.chkOnlyMnnEsklpForm)
        NomenclatureComboBoxPopup.setTabOrder(self.chkOnlyMnnEsklpForm, self.chkIncludeAnalogies)
        NomenclatureComboBoxPopup.setTabOrder(self.chkIncludeAnalogies, self.chkOnlyExists)
        NomenclatureComboBoxPopup.setTabOrder(self.chkOnlyExists, self.tblFeatures)
        NomenclatureComboBoxPopup.setTabOrder(self.tblFeatures, self.buttonBox)

    def retranslateUi(self, NomenclatureComboBoxPopup):
        NomenclatureComboBoxPopup.setWindowTitle(_translate("NomenclatureComboBoxPopup", "Form", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNomenclature), _translate("NomenclatureComboBoxPopup", "&Номенклатура", None))
        self.lblMedicalAidKind.setText(_translate("NomenclatureComboBoxPopup", "Вид мед помощи", None))
        self.chkOnlyMnnEsklpForm.setText(_translate("NomenclatureComboBoxPopup", "Учитывать только наименования МНН и Формы выпуска по ЕСКЛП", None))
        self.lblCode.setText(_translate("NomenclatureComboBoxPopup", "&Код", None))
        self.chkActiveSubstance.setText(_translate("NomenclatureComboBoxPopup", "Действующее вещество", None))
        self.btnName.setText(_translate("NomenclatureComboBoxPopup", "На&именование cодержит", None))
        self.lblType.setText(_translate("NomenclatureComboBoxPopup", "&Тип", None))
        self.chkIncludeAnalogies.setText(_translate("NomenclatureComboBoxPopup", "Включая аналоги", None))
        self.lblProducer.setText(_translate("NomenclatureComboBoxPopup", "&Производитель", None))
        self.lblKind.setText(_translate("NomenclatureComboBoxPopup", "&Вид", None))
        self.lblLfForm.setText(_translate("NomenclatureComboBoxPopup", "&Форма выпуска", None))
        self.lblATC.setText(_translate("NomenclatureComboBoxPopup", "Код &АТХ", None))
        self.lblFinance.setText(_translate("NomenclatureComboBoxPopup", "Тип финансирования", None))
        self.lblClass.setText(_translate("NomenclatureComboBoxPopup", "&Класс", None))
        self.chkOnlyExists.setText(_translate("NomenclatureComboBoxPopup", "Только в наличии", None))
        self.lblMnnFilter.setText(_translate("NomenclatureComboBoxPopup", "&МНН содержит", None))
        self.chkOnlyLs.setText(_translate("NomenclatureComboBoxPopup", "Отображать только лс", None))
        self.lblVEN.setText(_translate("NomenclatureComboBoxPopup", "VEN-классификация", None))
        self.cmbVEN.setItemText(0, _translate("NomenclatureComboBoxPopup", "не задано", None))
        self.cmbVEN.setItemText(1, _translate("NomenclatureComboBoxPopup", "жизненно важные", None))
        self.cmbVEN.setItemText(2, _translate("NomenclatureComboBoxPopup", "необходимые", None))
        self.cmbVEN.setItemText(3, _translate("NomenclatureComboBoxPopup", "второстепенные", None))
        self.tabSearchAttributes.setTabText(self.tabSearchAttributes.indexOf(self.tabMainCharacters), _translate("NomenclatureComboBoxPopup", "&Описание", None))
        self.tabSearchAttributes.setTabText(self.tabSearchAttributes.indexOf(self.tabFeatures), _translate("NomenclatureComboBoxPopup", "&Характеристики", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), _translate("NomenclatureComboBoxPopup", "&Поиск", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdd), _translate("NomenclatureComboBoxPopup", "&Добавить", None))

from RefBooks.NomenclatureActiveSubstance.ActiveSubstanceComboBox import CActiveSubstanceComboBox
from library.InDocTable import CInDocTableView
from library.SortFilterProxyTableView import CSortFilterProxyTableView
from library.crbcombobox import CRBComboBox
