# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\Stock\PurchaseContractDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PurchaseContractDialog(object):
    def setupUi(self, PurchaseContractDialog):
        PurchaseContractDialog.setObjectName(_fromUtf8("PurchaseContractDialog"))
        PurchaseContractDialog.resize(643, 568)
        self.gridLayout = QtGui.QGridLayout(PurchaseContractDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtName = QtGui.QLineEdit(PurchaseContractDialog)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 1, 1, 1, 7)
        self.lblNumber = QtGui.QLabel(PurchaseContractDialog)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.gridLayout.addWidget(self.lblNumber, 0, 0, 1, 1)
        self.cmbFinance = CRBComboBox(PurchaseContractDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFinance.sizePolicy().hasHeightForWidth())
        self.cmbFinance.setSizePolicy(sizePolicy)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 5, 1, 1, 7)
        self.cmbConfirmationOrder = QtGui.QComboBox(PurchaseContractDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConfirmationOrder.sizePolicy().hasHeightForWidth())
        self.cmbConfirmationOrder.setSizePolicy(sizePolicy)
        self.cmbConfirmationOrder.setObjectName(_fromUtf8("cmbConfirmationOrder"))
        self.cmbConfirmationOrder.addItem(_fromUtf8(""))
        self.cmbConfirmationOrder.addItem(_fromUtf8(""))
        self.cmbConfirmationOrder.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbConfirmationOrder, 9, 1, 1, 5)
        self.lblFinanceSource = QtGui.QLabel(PurchaseContractDialog)
        self.lblFinanceSource.setObjectName(_fromUtf8("lblFinanceSource"))
        self.gridLayout.addWidget(self.lblFinanceSource, 7, 0, 1, 1)
        self.lblDate = QtGui.QLabel(PurchaseContractDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 0, 4, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(PurchaseContractDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 12, 1, 1, 7)
        self.lblConfirmationOrder = QtGui.QLabel(PurchaseContractDialog)
        self.lblConfirmationOrder.setObjectName(_fromUtf8("lblConfirmationOrder"))
        self.gridLayout.addWidget(self.lblConfirmationOrder, 9, 0, 1, 1)
        self.lblSummaryInfo = QtGui.QLabel(PurchaseContractDialog)
        self.lblSummaryInfo.setText(_fromUtf8(""))
        self.lblSummaryInfo.setObjectName(_fromUtf8("lblSummaryInfo"))
        self.gridLayout.addWidget(self.lblSummaryInfo, 11, 0, 1, 8)
        self.cmbSupplierOrg = COrgComboBox(PurchaseContractDialog)
        self.cmbSupplierOrg.setObjectName(_fromUtf8("cmbSupplierOrg"))
        self.gridLayout.addWidget(self.cmbSupplierOrg, 3, 1, 1, 6)
        self.btnSelectOrganisation = QtGui.QToolButton(PurchaseContractDialog)
        self.btnSelectOrganisation.setObjectName(_fromUtf8("btnSelectOrganisation"))
        self.gridLayout.addWidget(self.btnSelectOrganisation, 3, 7, 1, 1)
        self.lblSupplierOrg = QtGui.QLabel(PurchaseContractDialog)
        self.lblSupplierOrg.setObjectName(_fromUtf8("lblSupplierOrg"))
        self.gridLayout.addWidget(self.lblSupplierOrg, 3, 0, 1, 1)
        self.edtBegDate = CDateEdit(PurchaseContractDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 4, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 2)
        self.edtTitle = QtGui.QLineEdit(PurchaseContractDialog)
        self.edtTitle.setObjectName(_fromUtf8("edtTitle"))
        self.gridLayout.addWidget(self.edtTitle, 2, 1, 1, 7)
        self.lblFinance = QtGui.QLabel(PurchaseContractDialog)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 5, 0, 1, 1)
        self.cmbFinanceSource = CRBComboBox(PurchaseContractDialog)
        self.cmbFinanceSource.setObjectName(_fromUtf8("cmbFinanceSource"))
        self.gridLayout.addWidget(self.cmbFinanceSource, 7, 1, 1, 7)
        self.lblPeriodDate = QtGui.QLabel(PurchaseContractDialog)
        self.lblPeriodDate.setObjectName(_fromUtf8("lblPeriodDate"))
        self.gridLayout.addWidget(self.lblPeriodDate, 4, 0, 1, 1)
        self.edtNumber = QtGui.QLineEdit(PurchaseContractDialog)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout.addWidget(self.edtNumber, 0, 1, 1, 3)
        self.chkState = QtGui.QCheckBox(PurchaseContractDialog)
        self.chkState.setObjectName(_fromUtf8("chkState"))
        self.gridLayout.addWidget(self.chkState, 8, 1, 1, 7)
        self.lblTitle = QtGui.QLabel(PurchaseContractDialog)
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.gridLayout.addWidget(self.lblTitle, 2, 0, 1, 1)
        self.edtEndDate = CDateEdit(PurchaseContractDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 4, 3, 1, 1)
        self.edtDate = CDateEdit(PurchaseContractDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        self.edtDate.setCalendarPopup(True)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout.addWidget(self.edtDate, 0, 5, 1, 1)
        self.label = QtGui.QLabel(PurchaseContractDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 4, 2, 1, 1)
        self.lblName = QtGui.QLabel(PurchaseContractDialog)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 4, 1, 4)
        self.tabWidget = QtGui.QTabWidget(PurchaseContractDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSpecification = QtGui.QWidget()
        self.tabSpecification.setObjectName(_fromUtf8("tabSpecification"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabSpecification)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblItems = CInDocTableView(self.tabSpecification)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblItems.sizePolicy().hasHeightForWidth())
        self.tblItems.setSizePolicy(sizePolicy)
        self.tblItems.setObjectName(_fromUtf8("tblItems"))
        self.gridLayout_2.addWidget(self.tblItems, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSpecification, _fromUtf8(""))
        self.tabAdditionallyAgreement = QtGui.QWidget()
        self.tabAdditionallyAgreement.setObjectName(_fromUtf8("tabAdditionallyAgreement"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabAdditionallyAgreement)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblAdditionallyAgreement = CInDocTableView(self.tabAdditionallyAgreement)
        self.tblAdditionallyAgreement.setObjectName(_fromUtf8("tblAdditionallyAgreement"))
        self.gridLayout_3.addWidget(self.tblAdditionallyAgreement, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabAdditionallyAgreement, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 10, 0, 1, 8)
        self.lblContractType = QtGui.QLabel(PurchaseContractDialog)
        self.lblContractType.setObjectName(_fromUtf8("lblContractType"))
        self.gridLayout.addWidget(self.lblContractType, 6, 0, 1, 1)
        self.cmbContractType = CContractTypeComboBox(PurchaseContractDialog)
        self.cmbContractType.setObjectName(_fromUtf8("cmbContractType"))
        self.gridLayout.addWidget(self.cmbContractType, 6, 1, 1, 7)
        self.lblNumber.setBuddy(self.edtNumber)
        self.lblDate.setBuddy(self.edtDate)
        self.lblConfirmationOrder.setBuddy(self.cmbConfirmationOrder)
        self.lblSupplierOrg.setBuddy(self.cmbSupplierOrg)
        self.lblFinance.setBuddy(self.cmbFinance)
        self.lblPeriodDate.setBuddy(self.edtBegDate)
        self.lblTitle.setBuddy(self.edtTitle)
        self.lblName.setBuddy(self.edtName)

        self.retranslateUi(PurchaseContractDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PurchaseContractDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PurchaseContractDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PurchaseContractDialog)
        PurchaseContractDialog.setTabOrder(self.edtNumber, self.edtDate)
        PurchaseContractDialog.setTabOrder(self.edtDate, self.edtName)
        PurchaseContractDialog.setTabOrder(self.edtName, self.edtTitle)
        PurchaseContractDialog.setTabOrder(self.edtTitle, self.cmbSupplierOrg)
        PurchaseContractDialog.setTabOrder(self.cmbSupplierOrg, self.btnSelectOrganisation)
        PurchaseContractDialog.setTabOrder(self.btnSelectOrganisation, self.edtBegDate)
        PurchaseContractDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        PurchaseContractDialog.setTabOrder(self.edtEndDate, self.cmbFinance)
        PurchaseContractDialog.setTabOrder(self.cmbFinance, self.chkState)
        PurchaseContractDialog.setTabOrder(self.chkState, self.tabWidget)
        PurchaseContractDialog.setTabOrder(self.tabWidget, self.tblItems)
        PurchaseContractDialog.setTabOrder(self.tblItems, self.buttonBox)
        PurchaseContractDialog.setTabOrder(self.buttonBox, self.tblAdditionallyAgreement)

    def retranslateUi(self, PurchaseContractDialog):
        PurchaseContractDialog.setWindowTitle(_translate("PurchaseContractDialog", "Контракт на закупку", None))
        self.lblNumber.setText(_translate("PurchaseContractDialog", "Номер", None))
        self.cmbConfirmationOrder.setItemText(0, _translate("PurchaseContractDialog", "-", None))
        self.cmbConfirmationOrder.setItemText(1, _translate("PurchaseContractDialog", "Прямой", None))
        self.cmbConfirmationOrder.setItemText(2, _translate("PurchaseContractDialog", "Обратный", None))
        self.lblFinanceSource.setText(_translate("PurchaseContractDialog", "Источник финансирования", None))
        self.lblDate.setText(_translate("PurchaseContractDialog", "Дата", None))
        self.lblConfirmationOrder.setText(_translate("PurchaseContractDialog", "Порядок подтверждения", None))
        self.btnSelectOrganisation.setText(_translate("PurchaseContractDialog", "...", None))
        self.lblSupplierOrg.setText(_translate("PurchaseContractDialog", "Внешний поставщик", None))
        self.edtBegDate.setDisplayFormat(_translate("PurchaseContractDialog", "dd.MM.yyyy", None))
        self.lblFinance.setText(_translate("PurchaseContractDialog", "Тип финансирования", None))
        self.lblPeriodDate.setText(_translate("PurchaseContractDialog", "Период действия с", None))
        self.chkState.setText(_translate("PurchaseContractDialog", "Является государственным", None))
        self.lblTitle.setText(_translate("PurchaseContractDialog", "Наименование для печати", None))
        self.edtEndDate.setDisplayFormat(_translate("PurchaseContractDialog", "dd.MM.yyyy", None))
        self.edtDate.setDisplayFormat(_translate("PurchaseContractDialog", "dd.MM.yyyy", None))
        self.label.setText(_translate("PurchaseContractDialog", "по", None))
        self.lblName.setText(_translate("PurchaseContractDialog", "Наименование", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpecification), _translate("PurchaseContractDialog", "Спецификация", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdditionallyAgreement), _translate("PurchaseContractDialog", "Доп. соглашения", None))
        self.lblContractType.setText(_translate("PurchaseContractDialog", "Тип договора", None))

from Orgs.OrgComboBox import COrgComboBox
from Stock.Utils import CContractTypeComboBox
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
