# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\Stock\Production.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProductionDialog(object):
    def setupUi(self, ProductionDialog):
        ProductionDialog.setObjectName(_fromUtf8("ProductionDialog"))
        ProductionDialog.resize(600, 500)
        self.gridLayout = QtGui.QGridLayout(ProductionDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblDate = QtGui.QLabel(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 0, 3, 1, 1)
        self.edtDate = CDateEdit(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout.addWidget(self.edtDate, 0, 4, 1, 1)
        self.edtTime = CTimeEdit(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTime.sizePolicy().hasHeightForWidth())
        self.edtTime.setSizePolicy(sizePolicy)
        self.edtTime.setObjectName(_fromUtf8("edtTime"))
        self.gridLayout.addWidget(self.edtTime, 0, 5, 1, 1)
        self.lblReasonDate = QtGui.QLabel(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblReasonDate.sizePolicy().hasHeightForWidth())
        self.lblReasonDate.setSizePolicy(sizePolicy)
        self.lblReasonDate.setObjectName(_fromUtf8("lblReasonDate"))
        self.gridLayout.addWidget(self.lblReasonDate, 1, 3, 1, 1)
        self.edtReasonDate = CDateEdit(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtReasonDate.sizePolicy().hasHeightForWidth())
        self.edtReasonDate.setSizePolicy(sizePolicy)
        self.edtReasonDate.setObjectName(_fromUtf8("edtReasonDate"))
        self.gridLayout.addWidget(self.edtReasonDate, 1, 4, 1, 1)
        self.lblSupplier = QtGui.QLabel(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSupplier.sizePolicy().hasHeightForWidth())
        self.lblSupplier.setSizePolicy(sizePolicy)
        self.lblSupplier.setObjectName(_fromUtf8("lblSupplier"))
        self.gridLayout.addWidget(self.lblSupplier, 2, 0, 1, 1)
        self.lblSupplierPerson = QtGui.QLabel(ProductionDialog)
        self.lblSupplierPerson.setObjectName(_fromUtf8("lblSupplierPerson"))
        self.gridLayout.addWidget(self.lblSupplierPerson, 3, 0, 1, 1)
        self.cmbSupplierPerson = CPersonComboBoxEx(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplierPerson.sizePolicy().hasHeightForWidth())
        self.cmbSupplierPerson.setSizePolicy(sizePolicy)
        self.cmbSupplierPerson.setObjectName(_fromUtf8("cmbSupplierPerson"))
        self.gridLayout.addWidget(self.cmbSupplierPerson, 3, 1, 1, 5)
        self.lblNote = QtGui.QLabel(ProductionDialog)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout.addWidget(self.lblNote, 4, 0, 1, 1)
        self.edtNote = QtGui.QLineEdit(ProductionDialog)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 4, 1, 1, 5)
        self.splitter = QtGui.QSplitter(ProductionDialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBoxIn = QtGui.QGroupBox(self.splitter)
        self.groupBoxIn.setObjectName(_fromUtf8("groupBoxIn"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBoxIn)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tblInItems = CInDocTableView(self.groupBoxIn)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblInItems.sizePolicy().hasHeightForWidth())
        self.tblInItems.setSizePolicy(sizePolicy)
        self.tblInItems.setObjectName(_fromUtf8("tblInItems"))
        self.verticalLayout_2.addWidget(self.tblInItems)
        self.groupBoxOut = QtGui.QGroupBox(self.splitter)
        self.groupBoxOut.setObjectName(_fromUtf8("groupBoxOut"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBoxOut)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblOutItems = CInDocTableView(self.groupBoxOut)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblOutItems.sizePolicy().hasHeightForWidth())
        self.tblOutItems.setSizePolicy(sizePolicy)
        self.tblOutItems.setObjectName(_fromUtf8("tblOutItems"))
        self.verticalLayout.addWidget(self.tblOutItems)
        self.gridLayout.addWidget(self.splitter, 5, 0, 1, 6)
        self.buttonBox = QtGui.QDialogButtonBox(ProductionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 6)
        self.cmbSupplier = CStorageComboBox(ProductionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplier.sizePolicy().hasHeightForWidth())
        self.cmbSupplier.setSizePolicy(sizePolicy)
        self.cmbSupplier.setObjectName(_fromUtf8("cmbSupplier"))
        self.gridLayout.addWidget(self.cmbSupplier, 2, 1, 1, 5)
        self.lblReason = QtGui.QLabel(ProductionDialog)
        self.lblReason.setObjectName(_fromUtf8("lblReason"))
        self.gridLayout.addWidget(self.lblReason, 1, 0, 1, 1)
        self.lblNumber = QtGui.QLabel(ProductionDialog)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.gridLayout.addWidget(self.lblNumber, 0, 0, 1, 1)
        self.edtNumber = QtGui.QLineEdit(ProductionDialog)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout.addWidget(self.edtNumber, 0, 1, 1, 2)
        self.edtReason = QtGui.QLineEdit(ProductionDialog)
        self.edtReason.setObjectName(_fromUtf8("edtReason"))
        self.gridLayout.addWidget(self.edtReason, 1, 1, 1, 2)
        self.lblDate.setBuddy(self.edtDate)
        self.lblReasonDate.setBuddy(self.edtReasonDate)
        self.lblSupplier.setBuddy(self.cmbSupplier)
        self.lblSupplierPerson.setBuddy(self.cmbSupplierPerson)
        self.lblNote.setBuddy(self.edtNote)
        self.lblReason.setBuddy(self.edtReason)
        self.lblNumber.setBuddy(self.edtNumber)

        self.retranslateUi(ProductionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ProductionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ProductionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ProductionDialog)
        ProductionDialog.setTabOrder(self.edtNumber, self.edtDate)
        ProductionDialog.setTabOrder(self.edtDate, self.edtTime)
        ProductionDialog.setTabOrder(self.edtTime, self.edtReason)
        ProductionDialog.setTabOrder(self.edtReason, self.edtReasonDate)
        ProductionDialog.setTabOrder(self.edtReasonDate, self.cmbSupplier)
        ProductionDialog.setTabOrder(self.cmbSupplier, self.cmbSupplierPerson)
        ProductionDialog.setTabOrder(self.cmbSupplierPerson, self.edtNote)
        ProductionDialog.setTabOrder(self.edtNote, self.tblInItems)
        ProductionDialog.setTabOrder(self.tblInItems, self.tblOutItems)
        ProductionDialog.setTabOrder(self.tblOutItems, self.buttonBox)

    def retranslateUi(self, ProductionDialog):
        ProductionDialog.setWindowTitle(_translate("ProductionDialog", "Производство ЛСиИМН", None))
        self.lblDate.setText(_translate("ProductionDialog", "Дата", None))
        self.edtTime.setDisplayFormat(_translate("ProductionDialog", "HH:mm", None))
        self.lblReasonDate.setText(_translate("ProductionDialog", "Дата основания", None))
        self.lblSupplier.setText(_translate("ProductionDialog", "Подразделение", None))
        self.lblSupplierPerson.setText(_translate("ProductionDialog", "Ответственный", None))
        self.lblNote.setText(_translate("ProductionDialog", "Примечания", None))
        self.groupBoxIn.setTitle(_translate("ProductionDialog", "Исходные материалы", None))
        self.groupBoxOut.setTitle(_translate("ProductionDialog", "Результат ", None))
        self.lblReason.setText(_translate("ProductionDialog", "Основание", None))
        self.lblNumber.setText(_translate("ProductionDialog", "Номер", None))

from Orgs.OrgStructComboBoxes import CStorageComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.TimeEdit import CTimeEdit
