# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\Stock\StockTransUtilizationDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StockTransUtilizationDialog(object):
    def setupUi(self, StockTransUtilizationDialog):
        StockTransUtilizationDialog.setObjectName(_fromUtf8("StockTransUtilizationDialog"))
        StockTransUtilizationDialog.resize(748, 636)
        self.gridLayout = QtGui.QGridLayout(StockTransUtilizationDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblSummaryInfo = QtGui.QLabel(StockTransUtilizationDialog)
        self.lblSummaryInfo.setText(_fromUtf8(""))
        self.lblSummaryInfo.setObjectName(_fromUtf8("lblSummaryInfo"))
        self.gridLayout.addWidget(self.lblSummaryInfo, 12, 0, 1, 2)
        self.lblSupplier = QtGui.QLabel(StockTransUtilizationDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSupplier.sizePolicy().hasHeightForWidth())
        self.lblSupplier.setSizePolicy(sizePolicy)
        self.lblSupplier.setObjectName(_fromUtf8("lblSupplier"))
        self.gridLayout.addWidget(self.lblSupplier, 2, 0, 1, 1)
        self.lblNote = QtGui.QLabel(StockTransUtilizationDialog)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout.addWidget(self.lblNote, 9, 0, 1, 1)
        self.lblNumber = QtGui.QLabel(StockTransUtilizationDialog)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.gridLayout.addWidget(self.lblNumber, 0, 0, 1, 1)
        self.lblSupplierPerson = QtGui.QLabel(StockTransUtilizationDialog)
        self.lblSupplierPerson.setObjectName(_fromUtf8("lblSupplierPerson"))
        self.gridLayout.addWidget(self.lblSupplierPerson, 3, 0, 1, 1)
        self.lblDate = QtGui.QLabel(StockTransUtilizationDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 1, 0, 1, 1)
        self.lblContractDate = QtGui.QLabel(StockTransUtilizationDialog)
        self.lblContractDate.setObjectName(_fromUtf8("lblContractDate"))
        self.gridLayout.addWidget(self.lblContractDate, 5, 2, 1, 1)
        self.lblContractor = QtGui.QLabel(StockTransUtilizationDialog)
        self.lblContractor.setObjectName(_fromUtf8("lblContractor"))
        self.gridLayout.addWidget(self.lblContractor, 4, 0, 1, 1)
        self.lblActNumber = QtGui.QLabel(StockTransUtilizationDialog)
        self.lblActNumber.setObjectName(_fromUtf8("lblActNumber"))
        self.gridLayout.addWidget(self.lblActNumber, 7, 0, 1, 1)
        self.edtContractNumber = QtGui.QLineEdit(StockTransUtilizationDialog)
        self.edtContractNumber.setObjectName(_fromUtf8("edtContractNumber"))
        self.gridLayout.addWidget(self.edtContractNumber, 5, 1, 1, 1)
        self.cmbContractorOrg = COrgComboBox(StockTransUtilizationDialog)
        self.cmbContractorOrg.setObjectName(_fromUtf8("cmbContractorOrg"))
        self.gridLayout.addWidget(self.cmbContractorOrg, 4, 1, 1, 3)
        self.edtContractDate = CDateEdit(StockTransUtilizationDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtContractDate.sizePolicy().hasHeightForWidth())
        self.edtContractDate.setSizePolicy(sizePolicy)
        self.edtContractDate.setCalendarPopup(True)
        self.edtContractDate.setObjectName(_fromUtf8("edtContractDate"))
        self.gridLayout.addWidget(self.edtContractDate, 5, 3, 1, 1)
        self.lblContractNumber = QtGui.QLabel(StockTransUtilizationDialog)
        self.lblContractNumber.setObjectName(_fromUtf8("lblContractNumber"))
        self.gridLayout.addWidget(self.lblContractNumber, 5, 0, 1, 1)
        self.edtActNumber = QtGui.QLineEdit(StockTransUtilizationDialog)
        self.edtActNumber.setObjectName(_fromUtf8("edtActNumber"))
        self.gridLayout.addWidget(self.edtActNumber, 7, 1, 1, 1)
        self.edtActDate = CDateEdit(StockTransUtilizationDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtActDate.sizePolicy().hasHeightForWidth())
        self.edtActDate.setSizePolicy(sizePolicy)
        self.edtActDate.setCalendarPopup(True)
        self.edtActDate.setObjectName(_fromUtf8("edtActDate"))
        self.gridLayout.addWidget(self.edtActDate, 7, 3, 1, 1)
        self.tblItems = CInDocTableView(StockTransUtilizationDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblItems.sizePolicy().hasHeightForWidth())
        self.tblItems.setSizePolicy(sizePolicy)
        self.tblItems.setObjectName(_fromUtf8("tblItems"))
        self.gridLayout.addWidget(self.tblItems, 11, 0, 1, 4)
        self.lblActDate = QtGui.QLabel(StockTransUtilizationDialog)
        self.lblActDate.setObjectName(_fromUtf8("lblActDate"))
        self.gridLayout.addWidget(self.lblActDate, 7, 2, 1, 1)
        self.cmbSupplierPerson = CPersonComboBoxEx(StockTransUtilizationDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplierPerson.sizePolicy().hasHeightForWidth())
        self.cmbSupplierPerson.setSizePolicy(sizePolicy)
        self.cmbSupplierPerson.setObjectName(_fromUtf8("cmbSupplierPerson"))
        self.gridLayout.addWidget(self.cmbSupplierPerson, 3, 1, 1, 3)
        self.cmbSupplier = CStorageComboBox(StockTransUtilizationDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplier.sizePolicy().hasHeightForWidth())
        self.cmbSupplier.setSizePolicy(sizePolicy)
        self.cmbSupplier.setObjectName(_fromUtf8("cmbSupplier"))
        self.gridLayout.addWidget(self.cmbSupplier, 2, 1, 1, 3)
        self.edtNumber = QtGui.QLineEdit(StockTransUtilizationDialog)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout.addWidget(self.edtNumber, 0, 1, 1, 3)
        self.edtNote = QtGui.QLineEdit(StockTransUtilizationDialog)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 9, 1, 1, 3)
        self.widget = QtGui.QWidget(StockTransUtilizationDialog)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtDate = CDateEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.horizontalLayout.addWidget(self.edtDate)
        self.edtTime = QtGui.QTimeEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTime.sizePolicy().hasHeightForWidth())
        self.edtTime.setSizePolicy(sizePolicy)
        self.edtTime.setObjectName(_fromUtf8("edtTime"))
        self.horizontalLayout.addWidget(self.edtTime)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.widget, 1, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(StockTransUtilizationDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 13, 0, 1, 4)
        self.lblSupplier.setBuddy(self.cmbSupplier)
        self.lblNote.setBuddy(self.edtNote)
        self.lblSupplierPerson.setBuddy(self.cmbSupplierPerson)
        self.lblDate.setBuddy(self.edtDate)

        self.retranslateUi(StockTransUtilizationDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), StockTransUtilizationDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), StockTransUtilizationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(StockTransUtilizationDialog)
        StockTransUtilizationDialog.setTabOrder(self.edtNumber, self.edtDate)
        StockTransUtilizationDialog.setTabOrder(self.edtDate, self.edtTime)
        StockTransUtilizationDialog.setTabOrder(self.edtTime, self.cmbSupplier)
        StockTransUtilizationDialog.setTabOrder(self.cmbSupplier, self.cmbSupplierPerson)
        StockTransUtilizationDialog.setTabOrder(self.cmbSupplierPerson, self.cmbContractorOrg)
        StockTransUtilizationDialog.setTabOrder(self.cmbContractorOrg, self.edtContractNumber)
        StockTransUtilizationDialog.setTabOrder(self.edtContractNumber, self.edtContractDate)
        StockTransUtilizationDialog.setTabOrder(self.edtContractDate, self.edtActNumber)
        StockTransUtilizationDialog.setTabOrder(self.edtActNumber, self.edtActDate)
        StockTransUtilizationDialog.setTabOrder(self.edtActDate, self.edtNote)
        StockTransUtilizationDialog.setTabOrder(self.edtNote, self.tblItems)
        StockTransUtilizationDialog.setTabOrder(self.tblItems, self.buttonBox)

    def retranslateUi(self, StockTransUtilizationDialog):
        StockTransUtilizationDialog.setWindowTitle(_translate("StockTransUtilizationDialog", "Передача на утилизацию", None))
        self.lblSupplier.setText(_translate("StockTransUtilizationDialog", "Подразделение", None))
        self.lblNote.setText(_translate("StockTransUtilizationDialog", "Примечания", None))
        self.lblNumber.setText(_translate("StockTransUtilizationDialog", "Номер", None))
        self.lblSupplierPerson.setText(_translate("StockTransUtilizationDialog", "Ответственный", None))
        self.lblDate.setText(_translate("StockTransUtilizationDialog", "Дата", None))
        self.lblContractDate.setText(_translate("StockTransUtilizationDialog", "Дата договора", None))
        self.lblContractor.setText(_translate("StockTransUtilizationDialog", "Контрагент", None))
        self.lblActNumber.setText(_translate("StockTransUtilizationDialog", "Номер акта", None))
        self.lblContractNumber.setText(_translate("StockTransUtilizationDialog", "Номер договора", None))
        self.lblActDate.setText(_translate("StockTransUtilizationDialog", "Дата акта", None))
        self.edtTime.setDisplayFormat(_translate("StockTransUtilizationDialog", "HH:mm", None))

from Orgs.OrgComboBox import COrgComboBox
from Orgs.OrgStructComboBoxes import CStorageComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
