# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\Stock\StockRequisitionEditDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StockRequisitionDialog(object):
    def setupUi(self, StockRequisitionDialog):
        StockRequisitionDialog.setObjectName(_fromUtf8("StockRequisitionDialog"))
        StockRequisitionDialog.resize(637, 500)
        self.gridLayout = QtGui.QGridLayout(StockRequisitionDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblDeadline = QtGui.QLabel(StockRequisitionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDeadline.sizePolicy().hasHeightForWidth())
        self.lblDeadline.setSizePolicy(sizePolicy)
        self.lblDeadline.setObjectName(_fromUtf8("lblDeadline"))
        self.gridLayout.addWidget(self.lblDeadline, 0, 2, 1, 1)
        self.lblAgreementNote = QtGui.QLabel(StockRequisitionDialog)
        self.lblAgreementNote.setObjectName(_fromUtf8("lblAgreementNote"))
        self.gridLayout.addWidget(self.lblAgreementNote, 8, 0, 1, 1)
        self.edtAgreementDate = CDateEdit(StockRequisitionDialog)
        self.edtAgreementDate.setEnabled(False)
        self.edtAgreementDate.setCalendarPopup(True)
        self.edtAgreementDate.setObjectName(_fromUtf8("edtAgreementDate"))
        self.gridLayout.addWidget(self.edtAgreementDate, 7, 1, 1, 1)
        self.lblAgreement = QtGui.QLabel(StockRequisitionDialog)
        self.lblAgreement.setObjectName(_fromUtf8("lblAgreement"))
        self.gridLayout.addWidget(self.lblAgreement, 7, 0, 1, 1)
        self.edtDeadlineDate = CDateEdit(StockRequisitionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDeadlineDate.sizePolicy().hasHeightForWidth())
        self.edtDeadlineDate.setSizePolicy(sizePolicy)
        self.edtDeadlineDate.setCalendarPopup(True)
        self.edtDeadlineDate.setObjectName(_fromUtf8("edtDeadlineDate"))
        self.gridLayout.addWidget(self.edtDeadlineDate, 0, 3, 1, 1)
        self.lblSupplier = QtGui.QLabel(StockRequisitionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSupplier.sizePolicy().hasHeightForWidth())
        self.lblSupplier.setSizePolicy(sizePolicy)
        self.lblSupplier.setObjectName(_fromUtf8("lblSupplier"))
        self.gridLayout.addWidget(self.lblSupplier, 3, 0, 1, 1)
        self.lblNote = QtGui.QLabel(StockRequisitionDialog)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout.addWidget(self.lblNote, 9, 0, 1, 1)
        self.edtDeadlineTime = QtGui.QTimeEdit(StockRequisitionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDeadlineTime.sizePolicy().hasHeightForWidth())
        self.edtDeadlineTime.setSizePolicy(sizePolicy)
        self.edtDeadlineTime.setObjectName(_fromUtf8("edtDeadlineTime"))
        self.gridLayout.addWidget(self.edtDeadlineTime, 0, 4, 1, 1)
        self.edtAgreementNote = QtGui.QLineEdit(StockRequisitionDialog)
        self.edtAgreementNote.setEnabled(False)
        self.edtAgreementNote.setObjectName(_fromUtf8("edtAgreementNote"))
        self.gridLayout.addWidget(self.edtAgreementNote, 8, 1, 1, 5)
        self.edtNumber = QtGui.QLineEdit(StockRequisitionDialog)
        self.edtNumber.setObjectName(_fromUtf8("edtNumber"))
        self.gridLayout.addWidget(self.edtNumber, 2, 1, 1, 5)
        self.edtDate = CDateEdit(StockRequisitionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDate.sizePolicy().hasHeightForWidth())
        self.edtDate.setSizePolicy(sizePolicy)
        self.edtDate.setCalendarPopup(True)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout.addWidget(self.edtDate, 0, 1, 1, 1)
        self.cmbSupplier = CStorageComboBox(StockRequisitionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSupplier.sizePolicy().hasHeightForWidth())
        self.cmbSupplier.setSizePolicy(sizePolicy)
        self.cmbSupplier.setObjectName(_fromUtf8("cmbSupplier"))
        self.gridLayout.addWidget(self.cmbSupplier, 3, 1, 1, 5)
        self.lblNumber = QtGui.QLabel(StockRequisitionDialog)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.gridLayout.addWidget(self.lblNumber, 2, 0, 1, 1)
        self.tblItems = CInDocTableView(StockRequisitionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblItems.sizePolicy().hasHeightForWidth())
        self.tblItems.setSizePolicy(sizePolicy)
        self.tblItems.setObjectName(_fromUtf8("tblItems"))
        self.gridLayout.addWidget(self.tblItems, 10, 0, 1, 6)
        self.edtNote = QtGui.QLineEdit(StockRequisitionDialog)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 9, 1, 1, 5)
        self.chkRevoked = QtGui.QCheckBox(StockRequisitionDialog)
        self.chkRevoked.setObjectName(_fromUtf8("chkRevoked"))
        self.gridLayout.addWidget(self.chkRevoked, 0, 5, 1, 1)
        self.lblDate = QtGui.QLabel(StockRequisitionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDate.sizePolicy().hasHeightForWidth())
        self.lblDate.setSizePolicy(sizePolicy)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 0, 0, 1, 1)
        self.lblRecipient = QtGui.QLabel(StockRequisitionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRecipient.sizePolicy().hasHeightForWidth())
        self.lblRecipient.setSizePolicy(sizePolicy)
        self.lblRecipient.setObjectName(_fromUtf8("lblRecipient"))
        self.gridLayout.addWidget(self.lblRecipient, 4, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(StockRequisitionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 11, 0, 1, 6)
        self.cmbRecipient = CStorageComboBox(StockRequisitionDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRecipient.sizePolicy().hasHeightForWidth())
        self.cmbRecipient.setSizePolicy(sizePolicy)
        self.cmbRecipient.setObjectName(_fromUtf8("cmbRecipient"))
        self.gridLayout.addWidget(self.cmbRecipient, 4, 1, 1, 5)
        self.lblAgreementStatus = QtGui.QLabel(StockRequisitionDialog)
        self.lblAgreementStatus.setObjectName(_fromUtf8("lblAgreementStatus"))
        self.gridLayout.addWidget(self.lblAgreementStatus, 6, 0, 1, 1)
        self.cmbAgreementPerson = CPersonComboBoxEx(StockRequisitionDialog)
        self.cmbAgreementPerson.setEnabled(False)
        self.cmbAgreementPerson.setObjectName(_fromUtf8("cmbAgreementPerson"))
        self.gridLayout.addWidget(self.cmbAgreementPerson, 7, 2, 1, 4)
        self.cmbAgreementStatus = QtGui.QComboBox(StockRequisitionDialog)
        self.cmbAgreementStatus.setEnabled(False)
        self.cmbAgreementStatus.setObjectName(_fromUtf8("cmbAgreementStatus"))
        self.cmbAgreementStatus.addItem(_fromUtf8(""))
        self.cmbAgreementStatus.addItem(_fromUtf8(""))
        self.cmbAgreementStatus.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAgreementStatus, 6, 1, 1, 2)
        self.lblRecipientPerson = QtGui.QLabel(StockRequisitionDialog)
        self.lblRecipientPerson.setObjectName(_fromUtf8("lblRecipientPerson"))
        self.gridLayout.addWidget(self.lblRecipientPerson, 5, 0, 1, 1)
        self.cmbRecipientPerson = CPersonComboBoxEx(StockRequisitionDialog)
        self.cmbRecipientPerson.setObjectName(_fromUtf8("cmbRecipientPerson"))
        self.gridLayout.addWidget(self.cmbRecipientPerson, 5, 1, 1, 5)
        self.lblDeadline.setBuddy(self.edtDeadlineDate)
        self.lblSupplier.setBuddy(self.cmbSupplier)
        self.lblNote.setBuddy(self.edtNote)
        self.lblDate.setBuddy(self.edtDate)
        self.lblRecipient.setBuddy(self.cmbRecipient)

        self.retranslateUi(StockRequisitionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), StockRequisitionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), StockRequisitionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(StockRequisitionDialog)
        StockRequisitionDialog.setTabOrder(self.edtDate, self.edtDeadlineDate)
        StockRequisitionDialog.setTabOrder(self.edtDeadlineDate, self.edtDeadlineTime)
        StockRequisitionDialog.setTabOrder(self.edtDeadlineTime, self.chkRevoked)
        StockRequisitionDialog.setTabOrder(self.chkRevoked, self.edtNumber)
        StockRequisitionDialog.setTabOrder(self.edtNumber, self.cmbSupplier)
        StockRequisitionDialog.setTabOrder(self.cmbSupplier, self.cmbRecipient)
        StockRequisitionDialog.setTabOrder(self.cmbRecipient, self.cmbRecipientPerson)
        StockRequisitionDialog.setTabOrder(self.cmbRecipientPerson, self.cmbAgreementStatus)
        StockRequisitionDialog.setTabOrder(self.cmbAgreementStatus, self.edtAgreementDate)
        StockRequisitionDialog.setTabOrder(self.edtAgreementDate, self.cmbAgreementPerson)
        StockRequisitionDialog.setTabOrder(self.cmbAgreementPerson, self.edtAgreementNote)
        StockRequisitionDialog.setTabOrder(self.edtAgreementNote, self.edtNote)
        StockRequisitionDialog.setTabOrder(self.edtNote, self.tblItems)
        StockRequisitionDialog.setTabOrder(self.tblItems, self.buttonBox)

    def retranslateUi(self, StockRequisitionDialog):
        StockRequisitionDialog.setWindowTitle(_translate("StockRequisitionDialog", "Требование на поставку ЛСиИМН", None))
        self.lblDeadline.setText(_translate("StockRequisitionDialog", "Срок исполнения", None))
        self.lblAgreementNote.setText(_translate("StockRequisitionDialog", "Примечание к согласованию", None))
        self.edtAgreementDate.setDisplayFormat(_translate("StockRequisitionDialog", "dd.MM.yyyy", None))
        self.lblAgreement.setText(_translate("StockRequisitionDialog", "Согласование", None))
        self.edtDeadlineDate.setDisplayFormat(_translate("StockRequisitionDialog", "dd.MM.yyyy", None))
        self.lblSupplier.setText(_translate("StockRequisitionDialog", "Поставщик", None))
        self.lblNote.setText(_translate("StockRequisitionDialog", "Примечания", None))
        self.edtDeadlineTime.setDisplayFormat(_translate("StockRequisitionDialog", "HH:mm", None))
        self.edtDate.setDisplayFormat(_translate("StockRequisitionDialog", "dd.MM.yyyy", None))
        self.lblNumber.setText(_translate("StockRequisitionDialog", "Номер", None))
        self.chkRevoked.setText(_translate("StockRequisitionDialog", "Отменено", None))
        self.lblDate.setText(_translate("StockRequisitionDialog", "Дата", None))
        self.lblRecipient.setText(_translate("StockRequisitionDialog", "Заказчик", None))
        self.lblAgreementStatus.setText(_translate("StockRequisitionDialog", "Статус согласования", None))
        self.cmbAgreementStatus.setItemText(0, _translate("StockRequisitionDialog", "Не согласовано", None))
        self.cmbAgreementStatus.setItemText(1, _translate("StockRequisitionDialog", "Согласовано", None))
        self.cmbAgreementStatus.setItemText(2, _translate("StockRequisitionDialog", "Отклонено", None))
        self.lblRecipientPerson.setText(_translate("StockRequisitionDialog", "Ответственный", None))

from Orgs.OrgStructComboBoxes import CStorageComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
