# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client\F131\F131.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(728, 819)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter2 = QtGui.QSplitter(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.splitter2.sizePolicy().hasHeightForWidth())
        self.splitter2.setSizePolicy(sizePolicy)
        self.splitter2.setOrientation(QtCore.Qt.Vertical)
        self.splitter2.setObjectName(_fromUtf8("splitter2"))
        self.txtClientInfoBrowser = CTextBrowser(self.splitter2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.scrollArea = QtGui.QScrollArea(self.splitter2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.tabWidget = QtGui.QTabWidget()
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 718, 668))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabToken = QtGui.QWidget()
        self.tabToken.setObjectName(_fromUtf8("tabToken"))
        self.gridLayout = QtGui.QGridLayout(self.tabToken)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget = QtGui.QWidget(self.tabToken)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter_2 = QtGui.QSplitter(self.widget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.frame = QtGui.QFrame(self.splitter_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.grpBase = QtGui.QGroupBox(self.frame)
        self.grpBase.setObjectName(_fromUtf8("grpBase"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpBase)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblContract = QtGui.QLabel(self.grpBase)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.gridLayout_2.addWidget(self.lblContract, 0, 0, 1, 3)
        self.cmbContract = CContractComboBox(self.grpBase)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.cmbContract.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbContract, 1, 0, 1, 3)
        self.lblBegDate = QtGui.QLabel(self.grpBase)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout_2.addWidget(self.lblBegDate, 2, 0, 1, 1)
        self.frmBegDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmBegDateTime.sizePolicy().hasHeightForWidth())
        self.frmBegDateTime.setSizePolicy(sizePolicy)
        self.frmBegDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmBegDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmBegDateTime.setLineWidth(0)
        self.frmBegDateTime.setObjectName(_fromUtf8("frmBegDateTime"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frmBegDateTime)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtBegDate = CDateEdit(self.frmBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout.addWidget(self.edtBegDate)
        self.edtBegTime = QtGui.QTimeEdit(self.frmBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegTime.sizePolicy().hasHeightForWidth())
        self.edtBegTime.setSizePolicy(sizePolicy)
        self.edtBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.horizontalLayout.addWidget(self.edtBegTime)
        self.gridLayout_2.addWidget(self.frmBegDateTime, 2, 1, 1, 2)
        self.lblEndDate = QtGui.QLabel(self.grpBase)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout_2.addWidget(self.lblEndDate, 3, 0, 1, 1)
        self.frmEndDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmEndDateTime.setSizePolicy(sizePolicy)
        self.frmEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmEndDateTime.setLineWidth(0)
        self.frmEndDateTime.setObjectName(_fromUtf8("frmEndDateTime"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frmEndDateTime)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.edtEndDate = CDateEdit(self.frmEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout_2.addWidget(self.edtEndDate)
        self.edtEndTime = QtGui.QTimeEdit(self.frmEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndTime.sizePolicy().hasHeightForWidth())
        self.edtEndTime.setSizePolicy(sizePolicy)
        self.edtEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.horizontalLayout_2.addWidget(self.edtEndTime)
        self.gridLayout_2.addWidget(self.frmEndDateTime, 3, 1, 1, 2)
        self.lblNextDate = QtGui.QLabel(self.grpBase)
        self.lblNextDate.setObjectName(_fromUtf8("lblNextDate"))
        self.gridLayout_2.addWidget(self.lblNextDate, 4, 0, 1, 1)
        self.frmNextDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmNextDateTime.sizePolicy().hasHeightForWidth())
        self.frmNextDateTime.setSizePolicy(sizePolicy)
        self.frmNextDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmNextDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmNextDateTime.setLineWidth(0)
        self.frmNextDateTime.setObjectName(_fromUtf8("frmNextDateTime"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frmNextDateTime)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtNextDate = CDateEdit(self.frmNextDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtNextDate.sizePolicy().hasHeightForWidth())
        self.edtNextDate.setSizePolicy(sizePolicy)
        self.edtNextDate.setCalendarPopup(True)
        self.edtNextDate.setObjectName(_fromUtf8("edtNextDate"))
        self.horizontalLayout_3.addWidget(self.edtNextDate)
        self.gridLayout_2.addWidget(self.frmNextDateTime, 4, 1, 1, 2)
        self.lblPerson = QtGui.QLabel(self.grpBase)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout_2.addWidget(self.lblPerson, 5, 0, 1, 3)
        self.cmbPerson = CPersonComboBoxEx(self.grpBase)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbPerson, 6, 0, 1, 3)
        self.chkPrimary = QtGui.QCheckBox(self.grpBase)
        self.chkPrimary.setObjectName(_fromUtf8("chkPrimary"))
        self.gridLayout_2.addWidget(self.chkPrimary, 7, 0, 1, 2)
        self.lblResult = QtGui.QLabel(self.grpBase)
        self.lblResult.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblResult.setObjectName(_fromUtf8("lblResult"))
        self.gridLayout_2.addWidget(self.lblResult, 7, 2, 1, 1)
        self.cmbResult = CRBComboBox(self.grpBase)
        self.cmbResult.setObjectName(_fromUtf8("cmbResult"))
        self.cmbResult.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbResult, 8, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(16, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 9, 0, 1, 2)
        self.horizontalLayout_4.addWidget(self.grpBase)
        self.grpWork = QtGui.QGroupBox(self.frame)
        self.grpWork.setObjectName(_fromUtf8("grpWork"))
        self._3 = QtGui.QGridLayout(self.grpWork)
        self._3.setMargin(4)
        self._3.setSpacing(4)
        self._3.setObjectName(_fromUtf8("_3"))
        spacerItem1 = QtGui.QSpacerItem(111, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self._3.addItem(spacerItem1, 9, 0, 1, 2)
        self.btnSelectWorkOrganisation = QtGui.QToolButton(self.grpWork)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectWorkOrganisation.sizePolicy().hasHeightForWidth())
        self.btnSelectWorkOrganisation.setSizePolicy(sizePolicy)
        self.btnSelectWorkOrganisation.setObjectName(_fromUtf8("btnSelectWorkOrganisation"))
        self._3.addWidget(self.btnSelectWorkOrganisation, 0, 3, 1, 1)
        self.cmbWorkOKVED = COKVEDComboBox(self.grpWork)
        self.cmbWorkOKVED.setObjectName(_fromUtf8("cmbWorkOKVED"))
        self._3.addWidget(self.cmbWorkOKVED, 6, 1, 1, 3)
        self.edtPrevDate = CDateEdit(self.grpWork)
        self.edtPrevDate.setCalendarPopup(True)
        self.edtPrevDate.setObjectName(_fromUtf8("edtPrevDate"))
        self._3.addWidget(self.edtPrevDate, 8, 2, 1, 2)
        self.lblWorkOKVED = QtGui.QLabel(self.grpWork)
        self.lblWorkOKVED.setObjectName(_fromUtf8("lblWorkOKVED"))
        self._3.addWidget(self.lblWorkOKVED, 6, 0, 1, 1)
        self.lblWorkPost = QtGui.QLabel(self.grpWork)
        self.lblWorkPost.setObjectName(_fromUtf8("lblWorkPost"))
        self._3.addWidget(self.lblWorkPost, 5, 0, 1, 1)
        self.lblWorkStage = QtGui.QLabel(self.grpWork)
        self.lblWorkStage.setObjectName(_fromUtf8("lblWorkStage"))
        self._3.addWidget(self.lblWorkStage, 7, 0, 1, 1)
        self.edtWorkStage = QtGui.QSpinBox(self.grpWork)
        self.edtWorkStage.setObjectName(_fromUtf8("edtWorkStage"))
        self._3.addWidget(self.edtWorkStage, 7, 1, 1, 3)
        self.label_7 = QtGui.QLabel(self.grpWork)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self._3.addWidget(self.label_7, 8, 0, 1, 2)
        self.edtWorkPost = QtGui.QLineEdit(self.grpWork)
        self.edtWorkPost.setObjectName(_fromUtf8("edtWorkPost"))
        self._3.addWidget(self.edtWorkPost, 5, 1, 1, 3)
        self.cmbWorkOrganisation = COrgComboBox(self.grpWork)
        self.cmbWorkOrganisation.setObjectName(_fromUtf8("cmbWorkOrganisation"))
        self._3.addWidget(self.cmbWorkOrganisation, 0, 0, 1, 3)
        self.lblINN = QtGui.QLabel(self.grpWork)
        self.lblINN.setObjectName(_fromUtf8("lblINN"))
        self._3.addWidget(self.lblINN, 2, 0, 1, 4)
        self.lblKPP = QtGui.QLabel(self.grpWork)
        self.lblKPP.setObjectName(_fromUtf8("lblKPP"))
        self._3.addWidget(self.lblKPP, 3, 0, 1, 4)
        self.lblOGRN = QtGui.QLabel(self.grpWork)
        self.lblOGRN.setObjectName(_fromUtf8("lblOGRN"))
        self._3.addWidget(self.lblOGRN, 4, 0, 1, 4)
        self.edtWorkOrganisationFreeInput = QtGui.QLineEdit(self.grpWork)
        self.edtWorkOrganisationFreeInput.setObjectName(_fromUtf8("edtWorkOrganisationFreeInput"))
        self._3.addWidget(self.edtWorkOrganisationFreeInput, 1, 0, 1, 4)
        self.horizontalLayout_4.addWidget(self.grpWork)
        self.tblWorkHurt = QtGui.QGroupBox(self.frame)
        self.tblWorkHurt.setObjectName(_fromUtf8("tblWorkHurt"))
        self._4 = QtGui.QGridLayout(self.tblWorkHurt)
        self._4.setMargin(0)
        self._4.setSpacing(0)
        self._4.setObjectName(_fromUtf8("_4"))
        self.splitter = QtGui.QSplitter(self.tblWorkHurt)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tblWorkHurts = CWorkHurtTableView(self.splitter)
        self.tblWorkHurts.setObjectName(_fromUtf8("tblWorkHurts"))
        self.tblWorkHurtFactors = CInDocTableView(self.splitter)
        self.tblWorkHurtFactors.setObjectName(_fromUtf8("tblWorkHurtFactors"))
        self._4.addWidget(self.splitter, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.tblWorkHurt)
        self.grpInspections = QtGui.QGroupBox(self.splitter_2)
        self.grpInspections.setObjectName(_fromUtf8("grpInspections"))
        self.vboxlayout = QtGui.QVBoxLayout(self.grpInspections)
        self.vboxlayout.setMargin(4)
        self.vboxlayout.setSpacing(4)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.tblInspections = CInDocTableView(self.grpInspections)
        self.tblInspections.setObjectName(_fromUtf8("tblInspections"))
        self.vboxlayout.addWidget(self.tblInspections)
        self.grpActions = QtGui.QGroupBox(self.splitter_2)
        self.grpActions.setObjectName(_fromUtf8("grpActions"))
        self._2 = QtGui.QGridLayout(self.grpActions)
        self._2.setMargin(4)
        self._2.setSpacing(4)
        self._2.setObjectName(_fromUtf8("_2"))
        self.tblActions = CInDocTableView(self.grpActions)
        self.tblActions.setObjectName(_fromUtf8("tblActions"))
        self._2.addWidget(self.tblActions, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.splitter_2)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabToken, _fromUtf8(""))
        self.tabMedicalDiagnosis = CEventMedicalDiagnosisPage()
        self.tabMedicalDiagnosis.setObjectName(_fromUtf8("tabMedicalDiagnosis"))
        self.tabWidget.addTab(self.tabMedicalDiagnosis, _fromUtf8(""))
        self.tabMes = CEventMesPage()
        self.tabMes.setObjectName(_fromUtf8("tabMes"))
        self.tabWidget.addTab(self.tabMes, _fromUtf8(""))
        self.tabStatus = CActionsPage()
        self.tabStatus.setObjectName(_fromUtf8("tabStatus"))
        self.tabWidget.addTab(self.tabStatus, _fromUtf8(""))
        self.tabDiagnostic = CActionsPage()
        self.tabDiagnostic.setObjectName(_fromUtf8("tabDiagnostic"))
        self.tabWidget.addTab(self.tabDiagnostic, _fromUtf8(""))
        self.tabCure = CActionsPage()
        self.tabCure.setObjectName(_fromUtf8("tabCure"))
        self.tabWidget.addTab(self.tabCure, _fromUtf8(""))
        self.tabMisc = CActionsPage()
        self.tabMisc.setObjectName(_fromUtf8("tabMisc"))
        self.tabWidget.addTab(self.tabMisc, _fromUtf8(""))
        self.tabAmbCard = CAmbCardPage()
        self.tabAmbCard.setObjectName(_fromUtf8("tabAmbCard"))
        self.tabWidget.addTab(self.tabAmbCard, _fromUtf8(""))
        self.tabCash = CEventCashPage()
        self.tabCash.setObjectName(_fromUtf8("tabCash"))
        self.tabWidget.addTab(self.tabCash, _fromUtf8(""))
        self.tabExport = QtGui.QWidget()
        self.tabExport.setObjectName(_fromUtf8("tabExport"))
        self.gridLayout_55 = QtGui.QGridLayout(self.tabExport)
        self.gridLayout_55.setMargin(1)
        self.gridLayout_55.setSpacing(1)
        self.gridLayout_55.setObjectName(_fromUtf8("gridLayout_55"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tabExport)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tblExport = CInDocTableView(self.tab_3)
        self.tblExport.setObjectName(_fromUtf8("tblExport"))
        self.horizontalLayout_9.addWidget(self.tblExport)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.tblExport_FileAttach = CInDocExportTableView(self.tab)
        self.tblExport_FileAttach.setObjectName(_fromUtf8("tblExport_FileAttach"))
        self.horizontalLayout_8.addWidget(self.tblExport_FileAttach)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tblExport_VIMIS = CInDocExportTableView(self.tab_2)
        self.tblExport_VIMIS.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tblExport_VIMIS.setSizeIncrement(QtCore.QSize(0, -1))
        self.tblExport_VIMIS.setBaseSize(QtCore.QSize(0, -1))
        self.tblExport_VIMIS.setObjectName(_fromUtf8("tblExport_VIMIS"))
        self.horizontalLayout_7.addWidget(self.tblExport_VIMIS)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_55.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabExport, _fromUtf8(""))
        self.tabNotes = CEventNotesPage()
        self.tabNotes.setObjectName(_fromUtf8("tabNotes"))
        self.tabWidget.addTab(self.tabNotes, _fromUtf8(""))
        self.scrollArea.setWidget(self.tabWidget)
        self.gridLayout_3.addWidget(self.splitter2, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.statusBar = QtGui.QStatusBar(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.horizontalLayout_5.addWidget(self.statusBar)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.lblProlongateEvent = QtGui.QLabel(Dialog)
        self.lblProlongateEvent.setText(_fromUtf8(""))
        self.lblProlongateEvent.setObjectName(_fromUtf8("lblProlongateEvent"))
        self.horizontalLayout_5.addWidget(self.lblProlongateEvent)
        self.lblValueExternalId = QtGui.QLabel(Dialog)
        self.lblValueExternalId.setText(_fromUtf8(""))
        self.lblValueExternalId.setObjectName(_fromUtf8("lblValueExternalId"))
        self.horizontalLayout_5.addWidget(self.lblValueExternalId)
        self.lblValueMesCode = QtGui.QLabel(Dialog)
        self.lblValueMesCode.setText(_fromUtf8(""))
        self.lblValueMesCode.setObjectName(_fromUtf8("lblValueMesCode"))
        self.horizontalLayout_5.addWidget(self.lblValueMesCode)
        self.horizontalLayout_5.setStretch(0, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblNextDate.setBuddy(self.edtNextDate)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblResult.setBuddy(self.cmbResult)
        self.lblWorkOKVED.setBuddy(self.cmbWorkOKVED)
        self.lblWorkPost.setBuddy(self.edtWorkPost)
        self.lblWorkStage.setBuddy(self.edtWorkStage)
        self.label_7.setBuddy(self.edtPrevDate)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txtClientInfoBrowser, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.txtClientInfoBrowser.setWhatsThis(_translate("Dialog", "Описание пациента", None))
        self.txtClientInfoBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.grpBase.setTitle(_translate("Dialog", "&ф.131", None))
        self.lblContract.setText(_translate("Dialog", "Договор:", None))
        self.cmbContract.setWhatsThis(_translate("Dialog", "номер, дата и основание договора в рамках которого производится осмотр", None))
        self.cmbContract.setItemText(0, _translate("Dialog", "Договор", None))
        self.lblBegDate.setText(_translate("Dialog", "Назначено", None))
        self.edtBegDate.setWhatsThis(_translate("Dialog", "дата начала осмотра", None))
        self.edtBegTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.lblEndDate.setText(_translate("Dialog", "Выполнено", None))
        self.edtEndDate.setWhatsThis(_translate("Dialog", "дата окончания осмотра", None))
        self.edtEndTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.lblNextDate.setText(_translate("Dialog", "След.явка", None))
        self.lblPerson.setText(_translate("Dialog", "Ответственный", None))
        self.cmbPerson.setWhatsThis(_translate("Dialog", "врач отвечающий за осмотр (терапевт)", None))
        self.cmbPerson.setItemText(0, _translate("Dialog", "Врач", None))
        self.chkPrimary.setText(_translate("Dialog", "Пе&рвичный", None))
        self.lblResult.setText(_translate("Dialog", "Результа&т", None))
        self.cmbResult.setWhatsThis(_translate("Dialog", "результат осмотра", None))
        self.cmbResult.setItemText(0, _translate("Dialog", "Результат", None))
        self.grpWork.setTitle(_translate("Dialog", "&Занятость", None))
        self.btnSelectWorkOrganisation.setText(_translate("Dialog", "...", None))
        self.lblWorkOKVED.setText(_translate("Dialog", "ОКВЭД", None))
        self.lblWorkPost.setText(_translate("Dialog", "Должность", None))
        self.lblWorkStage.setText(_translate("Dialog", "стаж", None))
        self.label_7.setText(_translate("Dialog", "Дата период.осмотра", None))
        self.cmbWorkOrganisation.setWhatsThis(_translate("Dialog", "место работы пациента", None))
        self.lblINN.setText(_translate("Dialog", "ИНН", None))
        self.lblKPP.setText(_translate("Dialog", "КПП", None))
        self.lblOGRN.setText(_translate("Dialog", "ОГРН", None))
        self.tblWorkHurt.setTitle(_translate("Dialog", "&Вредность", None))
        self.tblWorkHurtFactors.setWhatsThis(_translate("Dialog", "вредные факторы работы пациента", None))
        self.grpInspections.setTitle(_translate("Dialog", "&Осмотр", None))
        self.grpActions.setTitle(_translate("Dialog", "&Мероприятия", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabToken), _translate("Dialog", "Стат.&учёт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMedicalDiagnosis), _translate("Dialog", "Диагно&з", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMes), _translate("Dialog", "Ст&андарт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatus), _translate("Dialog", "&Статус", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiagnostic), _translate("Dialog", "&Диагностика", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCure), _translate("Dialog", "&Лечение", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMisc), _translate("Dialog", "&Мероприятия", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAmbCard), _translate("Dialog", "Мед.&карта", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCash), _translate("Dialog", "&Оплата", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Dialog", "Событие", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("Dialog", "Документы", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Dialog", "ВИМИС", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExport), _translate("Dialog", "&Экспорт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNotes), _translate("Dialog", "Приме&чания", None))
        self.statusBar.setToolTip(_translate("Dialog", "A status bar", None))
        self.statusBar.setWhatsThis(_translate("Dialog", "A status bar.", None))

from Events.ActionsPage import CActionsPage
from Events.AmbCardPage import CAmbCardPage
from Events.EventCashPage import CEventCashPage
from Events.EventMedicalDiagnosisPage import CEventMedicalDiagnosisPage
from Events.EventMesPage import CEventMesPage
from Events.EventNotesPage import CEventNotesPage
from Orgs.OKVEDComboBox import COKVEDComboBox
from Orgs.OrgComboBox import CContractComboBox, COrgComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Registry.WorkHurtTableView import CWorkHurtTableView
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocExportTableView, CInDocTableView
from library.TextBrowser import CTextBrowser
from library.crbcombobox import CRBComboBox
