# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client\Exchange\ExportDispPlanDialog.ui'
#
# Created: Mon Jan 28 23:32:53 2019
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ExportDispPlanDialog(object):
    def setupUi(self, ExportDispPlanDialog):
        ExportDispPlanDialog.setObjectName(_fromUtf8("ExportDispPlanDialog"))
        ExportDispPlanDialog.resize(914, 681)
        self.gridLayout_2 = QtGui.QGridLayout(ExportDispPlanDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnExport = QtGui.QPushButton(ExportDispPlanDialog)
        self.btnExport.setEnabled(False)
        self.btnExport.setObjectName(_fromUtf8("btnExport"))
        self.horizontalLayout.addWidget(self.btnExport)
        self.btnClose = QtGui.QPushButton(ExportDispPlanDialog)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.horizontalLayout.addWidget(self.btnClose)
        self.gridLayout_2.addLayout(self.horizontalLayout, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(ExportDispPlanDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.sbYear = QtGui.QSpinBox(ExportDispPlanDialog)
        self.sbYear.setMinimum(2017)
        self.sbYear.setMaximum(9999)
        self.sbYear.setObjectName(_fromUtf8("sbYear"))
        self.horizontalLayout_2.addWidget(self.sbYear)
        self.label_2 = QtGui.QLabel(ExportDispPlanDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cmbMonthFrom = QtGui.QComboBox(ExportDispPlanDialog)
        self.cmbMonthFrom.setObjectName(_fromUtf8("cmbMonthFrom"))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.cmbMonthFrom.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmbMonthFrom)
        self.label_3 = QtGui.QLabel(ExportDispPlanDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.cmbMonthTo = QtGui.QComboBox(ExportDispPlanDialog)
        self.cmbMonthTo.setObjectName(_fromUtf8("cmbMonthTo"))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.cmbMonthTo.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmbMonthTo)
        self.label_5 = QtGui.QLabel(ExportDispPlanDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.cmbKind = QtGui.QComboBox(ExportDispPlanDialog)
        self.cmbKind.setObjectName(_fromUtf8("cmbKind"))
        self.horizontalLayout_2.addWidget(self.cmbKind)
        self.chkUseSocAttachments = QtGui.QCheckBox(ExportDispPlanDialog)
        self.chkUseSocAttachments.setEnabled(True)
        self.chkUseSocAttachments.setObjectName(_fromUtf8("chkUseSocAttachments"))
        self.horizontalLayout_2.addWidget(self.chkUseSocAttachments)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.pbExportProgress = QtGui.QProgressBar(ExportDispPlanDialog)
        self.pbExportProgress.setObjectName(_fromUtf8("pbExportProgress"))
        self.gridLayout_2.addWidget(self.pbExportProgress, 6, 0, 1, 1)
        self.lblPlanCount = QtGui.QLabel(ExportDispPlanDialog)
        self.lblPlanCount.setObjectName(_fromUtf8("lblPlanCount"))
        self.gridLayout_2.addWidget(self.lblPlanCount, 1, 0, 1, 1)
        self.tblDispPlan = CTableView(ExportDispPlanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.tblDispPlan.sizePolicy().hasHeightForWidth())
        self.tblDispPlan.setSizePolicy(sizePolicy)
        self.tblDispPlan.setObjectName(_fromUtf8("tblDispPlan"))
        self.gridLayout_2.addWidget(self.tblDispPlan, 2, 0, 1, 1)
        self.lblExportStatus = QtGui.QLabel(ExportDispPlanDialog)
        self.lblExportStatus.setObjectName(_fromUtf8("lblExportStatus"))
        self.gridLayout_2.addWidget(self.lblExportStatus, 5, 0, 1, 1)
        self.tblDispPlanErrors = CTableView(ExportDispPlanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tblDispPlanErrors.sizePolicy().hasHeightForWidth())
        self.tblDispPlanErrors.setSizePolicy(sizePolicy)
        self.tblDispPlanErrors.setObjectName(_fromUtf8("tblDispPlanErrors"))
        self.gridLayout_2.addWidget(self.tblDispPlanErrors, 4, 0, 1, 1)
        self.label_4 = QtGui.QLabel(ExportDispPlanDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)

        self.retranslateUi(ExportDispPlanDialog)
        self.cmbMonthFrom.setCurrentIndex(0)
        self.cmbMonthTo.setCurrentIndex(11)
        QtCore.QMetaObject.connectSlotsByName(ExportDispPlanDialog)

    def retranslateUi(self, ExportDispPlanDialog):
        ExportDispPlanDialog.setWindowTitle(_translate("ExportDispPlanDialog", "Экспорт списка лиц, запланированных для проведения профилактических мероприятий", None))
        self.btnExport.setText(_translate("ExportDispPlanDialog", "Экспорт", None))
        self.btnClose.setText(_translate("ExportDispPlanDialog", "Закрыть", None))
        self.label.setText(_translate("ExportDispPlanDialog", "Год", None))
        self.label_2.setText(_translate("ExportDispPlanDialog", "Месяцы: с", None))
        self.cmbMonthFrom.setItemText(0, _translate("ExportDispPlanDialog", "января", None))
        self.cmbMonthFrom.setItemText(1, _translate("ExportDispPlanDialog", "февраля", None))
        self.cmbMonthFrom.setItemText(2, _translate("ExportDispPlanDialog", "марта", None))
        self.cmbMonthFrom.setItemText(3, _translate("ExportDispPlanDialog", "апреля", None))
        self.cmbMonthFrom.setItemText(4, _translate("ExportDispPlanDialog", "мая", None))
        self.cmbMonthFrom.setItemText(5, _translate("ExportDispPlanDialog", "июня", None))
        self.cmbMonthFrom.setItemText(6, _translate("ExportDispPlanDialog", "июля", None))
        self.cmbMonthFrom.setItemText(7, _translate("ExportDispPlanDialog", "августа", None))
        self.cmbMonthFrom.setItemText(8, _translate("ExportDispPlanDialog", "сентября", None))
        self.cmbMonthFrom.setItemText(9, _translate("ExportDispPlanDialog", "октября", None))
        self.cmbMonthFrom.setItemText(10, _translate("ExportDispPlanDialog", "ноября", None))
        self.cmbMonthFrom.setItemText(11, _translate("ExportDispPlanDialog", "декабря", None))
        self.label_3.setText(_translate("ExportDispPlanDialog", "по", None))
        self.cmbMonthTo.setItemText(0, _translate("ExportDispPlanDialog", "январь", None))
        self.cmbMonthTo.setItemText(1, _translate("ExportDispPlanDialog", "февраль", None))
        self.cmbMonthTo.setItemText(2, _translate("ExportDispPlanDialog", "март", None))
        self.cmbMonthTo.setItemText(3, _translate("ExportDispPlanDialog", "апрель", None))
        self.cmbMonthTo.setItemText(4, _translate("ExportDispPlanDialog", "май", None))
        self.cmbMonthTo.setItemText(5, _translate("ExportDispPlanDialog", "июнь", None))
        self.cmbMonthTo.setItemText(6, _translate("ExportDispPlanDialog", "июль", None))
        self.cmbMonthTo.setItemText(7, _translate("ExportDispPlanDialog", "август", None))
        self.cmbMonthTo.setItemText(8, _translate("ExportDispPlanDialog", "сентябрь", None))
        self.cmbMonthTo.setItemText(9, _translate("ExportDispPlanDialog", "октябрь", None))
        self.cmbMonthTo.setItemText(10, _translate("ExportDispPlanDialog", "ноябрь", None))
        self.cmbMonthTo.setItemText(11, _translate("ExportDispPlanDialog", "декабрь", None))
        self.label_5.setText(_translate("ExportDispPlanDialog", "Вид мероприятия:", None))
        self.chkUseSocAttachments.setText(_translate("ExportDispPlanDialog", "Экспорт с персональными данными из ТФОМС", None))
        self.pbExportProgress.setFormat(_translate("ExportDispPlanDialog", "%v из %m", None))
        self.lblPlanCount.setText(_translate("ExportDispPlanDialog", "Запланировано: 0", None))
        self.lblExportStatus.setText(_translate("ExportDispPlanDialog", "Отправка пакетов...", None))
        self.label_4.setText(_translate("ExportDispPlanDialog", "Ошибки:", None))

from library.TableView import CTableView
