# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\kmivc\Samson\UP_s11\client\Exchange\ImportDispExportedPlanDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ImportDispExportedPlanDialog(object):
    def setupUi(self, ImportDispExportedPlanDialog):
        ImportDispExportedPlanDialog.setObjectName(_fromUtf8("ImportDispExportedPlanDialog"))
        ImportDispExportedPlanDialog.resize(821, 548)
        self.verticalLayout = QtGui.QVBoxLayout(ImportDispExportedPlanDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(ImportDispExportedPlanDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.sbYear = QtGui.QSpinBox(ImportDispExportedPlanDialog)
        self.sbYear.setMinimum(2017)
        self.sbYear.setMaximum(9999)
        self.sbYear.setObjectName(_fromUtf8("sbYear"))
        self.horizontalLayout.addWidget(self.sbYear)
        self.label_2 = QtGui.QLabel(ImportDispExportedPlanDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.cmbMonth = QtGui.QComboBox(ImportDispExportedPlanDialog)
        self.cmbMonth.setObjectName(_fromUtf8("cmbMonth"))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbMonth)
        self.label_3 = QtGui.QLabel(ImportDispExportedPlanDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.cmbKind = QtGui.QComboBox(ImportDispExportedPlanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbKind.sizePolicy().hasHeightForWidth())
        self.cmbKind.setSizePolicy(sizePolicy)
        self.cmbKind.setObjectName(_fromUtf8("cmbKind"))
        self.cmbKind.addItem(_fromUtf8(""))
        self.cmbKind.addItem(_fromUtf8(""))
        self.cmbKind.addItem(_fromUtf8(""))
        self.cmbKind.addItem(_fromUtf8(""))
        self.cmbKind.addItem(_fromUtf8(""))
        self.cmbKind.addItem(_fromUtf8(""))
        self.cmbKind.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbKind)
        self.btnSyncMIS = QtGui.QPushButton(ImportDispExportedPlanDialog)
        self.btnSyncMIS.setObjectName(_fromUtf8("btnSyncMIS"))
        self.horizontalLayout.addWidget(self.btnSyncMIS)
        self.btnRefresh = QtGui.QPushButton(ImportDispExportedPlanDialog)
        self.btnRefresh.setObjectName(_fromUtf8("btnRefresh"))
        self.horizontalLayout.addWidget(self.btnRefresh)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lblExpPlanCount = QtGui.QLabel(ImportDispExportedPlanDialog)
        self.lblExpPlanCount.setObjectName(_fromUtf8("lblExpPlanCount"))
        self.verticalLayout.addWidget(self.lblExpPlanCount)
        self.tblExportedPlan = CTableView(ImportDispExportedPlanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.tblExportedPlan.sizePolicy().hasHeightForWidth())
        self.tblExportedPlan.setSizePolicy(sizePolicy)
        self.tblExportedPlan.setObjectName(_fromUtf8("tblExportedPlan"))
        self.verticalLayout.addWidget(self.tblExportedPlan)
        self.label_4 = QtGui.QLabel(ImportDispExportedPlanDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.tblExportedPlanErrors = CTableView(ImportDispExportedPlanDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tblExportedPlanErrors.sizePolicy().hasHeightForWidth())
        self.tblExportedPlanErrors.setSizePolicy(sizePolicy)
        self.tblExportedPlanErrors.setObjectName(_fromUtf8("tblExportedPlanErrors"))
        self.verticalLayout.addWidget(self.tblExportedPlanErrors)
        self.lblDeleteStatus = QtGui.QLabel(ImportDispExportedPlanDialog)
        self.lblDeleteStatus.setObjectName(_fromUtf8("lblDeleteStatus"))
        self.verticalLayout.addWidget(self.lblDeleteStatus)
        self.pbDeleteProgress = QtGui.QProgressBar(ImportDispExportedPlanDialog)
        self.pbDeleteProgress.setObjectName(_fromUtf8("pbDeleteProgress"))
        self.verticalLayout.addWidget(self.pbDeleteProgress)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lbl_fio = QtGui.QLabel(ImportDispExportedPlanDialog)
        self.lbl_fio.setObjectName(_fromUtf8("lbl_fio"))
        self.horizontalLayout_2.addWidget(self.lbl_fio)
        self.edit_fio = QtGui.QLineEdit(ImportDispExportedPlanDialog)
        self.edit_fio.setObjectName(_fromUtf8("edit_fio"))
        self.horizontalLayout_2.addWidget(self.edit_fio)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnSelectNotFound = QtGui.QPushButton(ImportDispExportedPlanDialog)
        self.btnSelectNotFound.setObjectName(_fromUtf8("btnSelectNotFound"))
        self.horizontalLayout_2.addWidget(self.btnSelectNotFound)
        self.btnSelectAll = QtGui.QPushButton(ImportDispExportedPlanDialog)
        self.btnSelectAll.setObjectName(_fromUtf8("btnSelectAll"))
        self.horizontalLayout_2.addWidget(self.btnSelectAll)
        self.btnDeleteSelected = QtGui.QPushButton(ImportDispExportedPlanDialog)
        self.btnDeleteSelected.setObjectName(_fromUtf8("btnDeleteSelected"))
        self.horizontalLayout_2.addWidget(self.btnDeleteSelected)
        self.btnClose = QtGui.QPushButton(ImportDispExportedPlanDialog)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.horizontalLayout_2.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ImportDispExportedPlanDialog)
        self.cmbMonth.setCurrentIndex(11)
        self.cmbKind.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ImportDispExportedPlanDialog)

    def retranslateUi(self, ImportDispExportedPlanDialog):
        ImportDispExportedPlanDialog.setWindowTitle(_translate("ImportDispExportedPlanDialog", "Список планирования на сервисе ТФОМС", None))
        self.label.setText(_translate("ImportDispExportedPlanDialog", "Год:", None))
        self.label_2.setText(_translate("ImportDispExportedPlanDialog", "Месяц", None))
        self.cmbMonth.setItemText(0, _translate("ImportDispExportedPlanDialog", "январь", None))
        self.cmbMonth.setItemText(1, _translate("ImportDispExportedPlanDialog", "февраль", None))
        self.cmbMonth.setItemText(2, _translate("ImportDispExportedPlanDialog", "март", None))
        self.cmbMonth.setItemText(3, _translate("ImportDispExportedPlanDialog", "апрель", None))
        self.cmbMonth.setItemText(4, _translate("ImportDispExportedPlanDialog", "май", None))
        self.cmbMonth.setItemText(5, _translate("ImportDispExportedPlanDialog", "июнь", None))
        self.cmbMonth.setItemText(6, _translate("ImportDispExportedPlanDialog", "июль", None))
        self.cmbMonth.setItemText(7, _translate("ImportDispExportedPlanDialog", "август", None))
        self.cmbMonth.setItemText(8, _translate("ImportDispExportedPlanDialog", "сентябрь", None))
        self.cmbMonth.setItemText(9, _translate("ImportDispExportedPlanDialog", "октябрь", None))
        self.cmbMonth.setItemText(10, _translate("ImportDispExportedPlanDialog", "ноябрь", None))
        self.cmbMonth.setItemText(11, _translate("ImportDispExportedPlanDialog", "декабрь", None))
        self.label_3.setText(_translate("ImportDispExportedPlanDialog", "Вид мероприятия", None))
        self.cmbKind.setItemText(0, _translate("ImportDispExportedPlanDialog", "Все", None))
        self.cmbKind.setItemText(1, _translate("ImportDispExportedPlanDialog", "Дисп. раз в 3 г", None))
        self.cmbKind.setItemText(2, _translate("ImportDispExportedPlanDialog", "Дисп. раз в 2 г", None))
        self.cmbKind.setItemText(3, _translate("ImportDispExportedPlanDialog", "Проф. осмотр", None))
        self.cmbKind.setItemText(4, _translate("ImportDispExportedPlanDialog", "Дисп. ежегодная", None))
        self.cmbKind.setItemText(5, _translate("ImportDispExportedPlanDialog", "Дисп. углубленная (1 гр)", None))
        self.cmbKind.setItemText(6, _translate("ImportDispExportedPlanDialog", "Дисп. углубленная (2 гр)", None))
        self.btnSyncMIS.setText(_translate("ImportDispExportedPlanDialog", "Синхронизировать список", None))
        self.btnRefresh.setText(_translate("ImportDispExportedPlanDialog", "Загрузить список", None))
        self.lblExpPlanCount.setText(_translate("ImportDispExportedPlanDialog", "На сервисе: 0 записей", None))
        self.label_4.setText(_translate("ImportDispExportedPlanDialog", "Ошибки при удалении:", None))
        self.lblDeleteStatus.setText(_translate("ImportDispExportedPlanDialog", "Отправка пакетов...", None))
        self.pbDeleteProgress.setFormat(_translate("ImportDispExportedPlanDialog", "%v из %m", None))
        self.lbl_fio.setText(_translate("ImportDispExportedPlanDialog", "ФИО пациента", None))
        self.btnSelectNotFound.setText(_translate("ImportDispExportedPlanDialog", "Выбрать не найденных", None))
        self.btnSelectAll.setText(_translate("ImportDispExportedPlanDialog", "Выбрать всех", None))
        self.btnDeleteSelected.setText(_translate("ImportDispExportedPlanDialog", "Удалить выбранные", None))
        self.btnClose.setText(_translate("ImportDispExportedPlanDialog", "Закрыть", None))

from library.TableView import CTableView
