# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Samson\UP_s11\client_test\Accounting\AccountCheckDialog.ui'
#
# Created: Thu Apr 18 13:39:37 2024
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AccountCheckDialog(object):
    def setupUi(self, AccountCheckDialog):
        AccountCheckDialog.setObjectName(_fromUtf8("AccountCheckDialog"))
        AccountCheckDialog.setWindowModality(QtCore.Qt.WindowModal)
        AccountCheckDialog.resize(880, 631)
        self.gridLayout_4 = QtGui.QGridLayout(AccountCheckDialog)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget = QtGui.QTabWidget(AccountCheckDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabAccounts = QtGui.QWidget()
        self.tabAccounts.setObjectName(_fromUtf8("tabAccounts"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabAccounts)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.splitter = QtGui.QSplitter(self.tabAccounts)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkSelectAllCheckTypes = QtGui.QCheckBox(self.groupBox)
        self.chkSelectAllCheckTypes.setTristate(True)
        self.chkSelectAllCheckTypes.setObjectName(_fromUtf8("chkSelectAllCheckTypes"))
        self.gridLayout.addWidget(self.chkSelectAllCheckTypes, 0, 0, 1, 1)
        self.listCheckTypes = QtGui.QListWidget(self.groupBox)
        self.listCheckTypes.setObjectName(_fromUtf8("listCheckTypes"))
        self.gridLayout.addWidget(self.listCheckTypes, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.twAccounts = QtGui.QTabWidget(self.groupBox_2)
        self.twAccounts.setObjectName(_fromUtf8("twAccounts"))
        self.tabAccount = QtGui.QWidget()
        self.tabAccount.setObjectName(_fromUtf8("tabAccount"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabAccount)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblAccounts = CTableView(self.tabAccount)
        self.tblAccounts.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblAccounts.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblAccounts.setObjectName(_fromUtf8("tblAccounts"))
        self.gridLayout_5.addWidget(self.tblAccounts, 0, 0, 1, 1)
        self.twAccounts.addTab(self.tabAccount, _fromUtf8(""))
        self.tabPeriod = QtGui.QWidget()
        self.tabPeriod.setObjectName(_fromUtf8("tabPeriod"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabPeriod)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cmbOrgStructure = COrgStructureComboBox(self.tabPeriod)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout_6.addWidget(self.cmbOrgStructure, 4, 1, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(self.tabPeriod)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout_6.addWidget(self.lblOrgStructure, 4, 0, 1, 1)
        self.lblEventType = QtGui.QLabel(self.tabPeriod)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout_6.addWidget(self.lblEventType, 7, 0, 1, 1)
        self.cmbEventType = CRBComboBox(self.tabPeriod)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout_6.addWidget(self.cmbEventType, 7, 1, 1, 1)
        self.lblContract = QtGui.QLabel(self.tabPeriod)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.gridLayout_6.addWidget(self.lblContract, 6, 0, 1, 1)
        self.lblFinance = QtGui.QLabel(self.tabPeriod)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout_6.addWidget(self.lblFinance, 5, 0, 1, 1)
        self.cmbFinance = CRBComboBox(self.tabPeriod)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout_6.addWidget(self.cmbFinance, 5, 1, 1, 1)
        self.cmbContract = CDbComboBox(self.tabPeriod)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.gridLayout_6.addWidget(self.cmbContract, 6, 1, 1, 1)
        self.label = QtGui.QLabel(self.tabPeriod)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabPeriod)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 10, 0, 1, 2)
        self.dePeriodFrom = QtGui.QDateEdit(self.tabPeriod)
        self.dePeriodFrom.setCalendarPopup(True)
        self.dePeriodFrom.setObjectName(_fromUtf8("dePeriodFrom"))
        self.gridLayout_6.addWidget(self.dePeriodFrom, 0, 1, 1, 1)
        self.dePeriodTo = QtGui.QDateEdit(self.tabPeriod)
        self.dePeriodTo.setCalendarPopup(True)
        self.dePeriodTo.setObjectName(_fromUtf8("dePeriodTo"))
        self.gridLayout_6.addWidget(self.dePeriodTo, 1, 1, 1, 1)
        self.lblDoctor = QtGui.QLabel(self.tabPeriod)
        self.lblDoctor.setObjectName(_fromUtf8("lblDoctor"))
        self.gridLayout_6.addWidget(self.lblDoctor, 8, 0, 1, 1)
        self.cmbFilterEventPerson = CPersonComboBoxEx(self.tabPeriod)
        self.cmbFilterEventPerson.setEnabled(True)
        self.cmbFilterEventPerson.setObjectName(_fromUtf8("cmbFilterEventPerson"))
        self.gridLayout_6.addWidget(self.cmbFilterEventPerson, 8, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setColumnStretch(1, 3)
        self.twAccounts.addTab(self.tabPeriod, _fromUtf8(""))
        self.verticalLayout.addWidget(self.twAccounts)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnBeginCheck = QtGui.QPushButton(self.groupBox_2)
        self.btnBeginCheck.setObjectName(_fromUtf8("btnBeginCheck"))
        self.horizontalLayout_3.addWidget(self.btnBeginCheck)
        self.lblResultCount = QtGui.QLabel(self.groupBox_2)
        self.lblResultCount.setText(_fromUtf8(""))
        self.lblResultCount.setObjectName(_fromUtf8("lblResultCount"))
        self.horizontalLayout_3.addWidget(self.lblResultCount)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblAccountItems = CTableView(self.groupBox_3)
        self.tblAccountItems.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tblAccountItems.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblAccountItems.setObjectName(_fromUtf8("tblAccountItems"))
        self.gridLayout_2.addWidget(self.tblAccountItems, 4, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.splitter)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textErrorDescription = QtGui.QTextEdit(self.groupBox_4)
        self.textErrorDescription.setAcceptRichText(False)
        self.textErrorDescription.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textErrorDescription.setObjectName(_fromUtf8("textErrorDescription"))
        self.gridLayout_3.addWidget(self.textErrorDescription, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabAccounts, _fromUtf8(""))
        self.tabFLC = QtGui.QWidget()
        self.tabFLC.setObjectName(_fromUtf8("tabFLC"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabFLC)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tblAccountItemsFLC = CTableView(self.tabFLC)
        self.tblAccountItemsFLC.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblAccountItemsFLC.setObjectName(_fromUtf8("tblAccountItemsFLC"))
        self.gridLayout_8.addWidget(self.tblAccountItemsFLC, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnBeginCheckFLC = QtGui.QPushButton(self.tabFLC)
        self.btnBeginCheckFLC.setObjectName(_fromUtf8("btnBeginCheckFLC"))
        self.horizontalLayout_4.addWidget(self.btnBeginCheckFLC)
        self.btnPrint = QtGui.QPushButton(self.tabFLC)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.horizontalLayout_4.addWidget(self.btnPrint)
        self.lblResultCountFLC = QtGui.QLabel(self.tabFLC)
        self.lblResultCountFLC.setText(_fromUtf8(""))
        self.lblResultCountFLC.setObjectName(_fromUtf8("lblResultCountFLC"))
        self.horizontalLayout_4.addWidget(self.lblResultCountFLC)
        self.lblResultCount_2 = QtGui.QLabel(self.tabFLC)
        self.lblResultCount_2.setText(_fromUtf8(""))
        self.lblResultCount_2.setObjectName(_fromUtf8("lblResultCount_2"))
        self.horizontalLayout_4.addWidget(self.lblResultCount_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btnNext = QtGui.QPushButton(self.tabFLC)
        self.btnNext.setObjectName(_fromUtf8("btnNext"))
        self.horizontalLayout_4.addWidget(self.btnNext)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabFLC, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(AccountCheckDialog)
        self.tabWidget.setCurrentIndex(0)
        self.twAccounts.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AccountCheckDialog)

    def retranslateUi(self, AccountCheckDialog):
        AccountCheckDialog.setWindowTitle(_translate("AccountCheckDialog", "Проверка счетов", None))
        self.groupBox.setTitle(_translate("AccountCheckDialog", "Условия проверки", None))
        self.chkSelectAllCheckTypes.setText(_translate("AccountCheckDialog", "Выбрать все", None))
        self.groupBox_2.setTitle(_translate("AccountCheckDialog", "Счета", None))
        self.twAccounts.setTabText(self.twAccounts.indexOf(self.tabAccount), _translate("AccountCheckDialog", "Счет", None))
        self.lblOrgStructure.setText(_translate("AccountCheckDialog", "Подразделение", None))
        self.lblEventType.setText(_translate("AccountCheckDialog", "Тип события", None))
        self.lblContract.setText(_translate("AccountCheckDialog", "Договор", None))
        self.lblFinance.setText(_translate("AccountCheckDialog", "Тип финансирования", None))
        self.label.setText(_translate("AccountCheckDialog", "Начало периода", None))
        self.label_2.setText(_translate("AccountCheckDialog", "Конец периода", None))
        self.lblDoctor.setText(_translate("AccountCheckDialog", "Врач", None))
        self.twAccounts.setTabText(self.twAccounts.indexOf(self.tabPeriod), _translate("AccountCheckDialog", "Период", None))
        self.btnBeginCheck.setText(_translate("AccountCheckDialog", "Проверка", None))
        self.groupBox_3.setTitle(_translate("AccountCheckDialog", "Список обращений, не удовлетворяющих условиям проверки", None))
        self.groupBox_4.setTitle(_translate("AccountCheckDialog", "Описание ошибки", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAccounts), _translate("AccountCheckDialog", "Счета", None))
        self.btnBeginCheckFLC.setText(_translate("AccountCheckDialog", "Проверка", None))
        self.btnPrint.setText(_translate("AccountCheckDialog", "Печать", None))
        self.btnNext.setText(_translate("AccountCheckDialog", "Продолжить", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFLC), _translate("AccountCheckDialog", "ФЛК", None))

from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.crbcombobox import CRBComboBox
from library.DbComboBox import CDbComboBox
from library.TableView import CTableView
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
