# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Project\Samson\UP_s11\client_test\Accounting\AccountingDialog.ui'
#
# Created: Thu May 22 13:13:39 2025
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AccountingDialog(object):
    def setupUi(self, AccountingDialog):
        AccountingDialog.setObjectName(_fromUtf8("AccountingDialog"))
        AccountingDialog.resize(1147, 791)
        self.gridlayout = QtGui.QGridLayout(AccountingDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.splitter_3 = QtGui.QSplitter(AccountingDialog)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setChildrenCollapsible(False)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.layoutWidget = QtGui.QWidget(self.splitter_3)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.vboxlayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.vboxlayout.setSpacing(4)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.splitter = QtGui.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeContracts = CContractTreeView(self.splitter)
        self.treeContracts.setObjectName(_fromUtf8("treeContracts"))
        self.tblContragents = QtGui.QTableView(self.splitter)
        self.tblContragents.setEnabled(True)
        self.tblContragents.setObjectName(_fromUtf8("tblContragents"))
        self.vboxlayout.addWidget(self.splitter)
        self.tabWorkType = QtGui.QTabWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWorkType.sizePolicy().hasHeightForWidth())
        self.tabWorkType.setSizePolicy(sizePolicy)
        self.tabWorkType.setTabPosition(QtGui.QTabWidget.North)
        self.tabWorkType.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWorkType.setObjectName(_fromUtf8("tabWorkType"))
        self.tabCalc = QtGui.QWidget()
        self.tabCalc.setObjectName(_fromUtf8("tabCalc"))
        self.gridlayout1 = QtGui.QGridLayout(self.tabCalc)
        self.gridlayout1.setMargin(2)
        self.gridlayout1.setSpacing(2)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.cmbCalcOrgStructure = COrgStructureComboBox(self.tabCalc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCalcOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbCalcOrgStructure.setSizePolicy(sizePolicy)
        self.cmbCalcOrgStructure.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbCalcOrgStructure.setObjectName(_fromUtf8("cmbCalcOrgStructure"))
        self.gridlayout1.addWidget(self.cmbCalcOrgStructure, 0, 0, 1, 1)
        self.clnCalcCalendar = CCalendarWidget(self.tabCalc)
        self.clnCalcCalendar.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.clnCalcCalendar.setGridVisible(False)
        self.clnCalcCalendar.setVerticalHeaderFormat(QtGui.QCalendarWidget.ISOWeekNumbers)
        self.clnCalcCalendar.setObjectName(_fromUtf8("clnCalcCalendar"))
        self.gridlayout1.addWidget(self.clnCalcCalendar, 1, 0, 1, 1)
        self.tabWorkType.addTab(self.tabCalc, _fromUtf8(""))
        self.tabAnalysis = QtGui.QWidget()
        self.tabAnalysis.setObjectName(_fromUtf8("tabAnalysis"))
        self.gridlayout2 = QtGui.QGridLayout(self.tabAnalysis)
        self.gridlayout2.setMargin(2)
        self.gridlayout2.setSpacing(2)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        spacerItem = QtGui.QSpacerItem(46, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout2.addItem(spacerItem, 4, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tabAnalysis)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridlayout3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout3.setMargin(2)
        self.gridlayout3.setSpacing(2)
        self.gridlayout3.setObjectName(_fromUtf8("gridlayout3"))
        self.lblAnalysisNote = QtGui.QLabel(self.groupBox_2)
        self.lblAnalysisNote.setObjectName(_fromUtf8("lblAnalysisNote"))
        self.gridlayout3.addWidget(self.lblAnalysisNote, 3, 0, 1, 1)
        self.cmbAnalysisPayRefuseType = CRBComboBox(self.groupBox_2)
        self.cmbAnalysisPayRefuseType.setObjectName(_fromUtf8("cmbAnalysisPayRefuseType"))
        self.gridlayout3.addWidget(self.cmbAnalysisPayRefuseType, 2, 1, 1, 3)
        self.lblAnalysisPayRefuseType = QtGui.QLabel(self.groupBox_2)
        self.lblAnalysisPayRefuseType.setObjectName(_fromUtf8("lblAnalysisPayRefuseType"))
        self.gridlayout3.addWidget(self.lblAnalysisPayRefuseType, 2, 0, 1, 1)
        self.cmbAnalysisEventCodeType = QtGui.QComboBox(self.groupBox_2)
        self.cmbAnalysisEventCodeType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAnalysisEventCodeType.sizePolicy().hasHeightForWidth())
        self.cmbAnalysisEventCodeType.setSizePolicy(sizePolicy)
        self.cmbAnalysisEventCodeType.setObjectName(_fromUtf8("cmbAnalysisEventCodeType"))
        self.cmbAnalysisEventCodeType.addItem(_fromUtf8(""))
        self.cmbAnalysisEventCodeType.addItem(_fromUtf8(""))
        self.gridlayout3.addWidget(self.cmbAnalysisEventCodeType, 5, 3, 1, 1)
        self.edtAnalysisClientCode = QtGui.QLineEdit(self.groupBox_2)
        self.edtAnalysisClientCode.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAnalysisClientCode.sizePolicy().hasHeightForWidth())
        self.edtAnalysisClientCode.setSizePolicy(sizePolicy)
        self.edtAnalysisClientCode.setObjectName(_fromUtf8("edtAnalysisClientCode"))
        self.gridlayout3.addWidget(self.edtAnalysisClientCode, 4, 1, 1, 1)
        self.chkAnalysisEventCode = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAnalysisEventCode.sizePolicy().hasHeightForWidth())
        self.chkAnalysisEventCode.setSizePolicy(sizePolicy)
        self.chkAnalysisEventCode.setObjectName(_fromUtf8("chkAnalysisEventCode"))
        self.gridlayout3.addWidget(self.chkAnalysisEventCode, 5, 0, 1, 1)
        self.cmbAnalysisClientCodeType = CRBComboBox(self.groupBox_2)
        self.cmbAnalysisClientCodeType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAnalysisClientCodeType.sizePolicy().hasHeightForWidth())
        self.cmbAnalysisClientCodeType.setSizePolicy(sizePolicy)
        self.cmbAnalysisClientCodeType.setObjectName(_fromUtf8("cmbAnalysisClientCodeType"))
        self.gridlayout3.addWidget(self.cmbAnalysisClientCodeType, 4, 3, 1, 1)
        self.cmbAnalysisAccountItems = QtGui.QComboBox(self.groupBox_2)
        self.cmbAnalysisAccountItems.setObjectName(_fromUtf8("cmbAnalysisAccountItems"))
        self.cmbAnalysisAccountItems.addItem(_fromUtf8(""))
        self.cmbAnalysisAccountItems.addItem(_fromUtf8(""))
        self.cmbAnalysisAccountItems.addItem(_fromUtf8(""))
        self.cmbAnalysisAccountItems.addItem(_fromUtf8(""))
        self.cmbAnalysisAccountItems.addItem(_fromUtf8(""))
        self.cmbAnalysisAccountItems.addItem(_fromUtf8(""))
        self.cmbAnalysisAccountItems.addItem(_fromUtf8(""))
        self.gridlayout3.addWidget(self.cmbAnalysisAccountItems, 0, 0, 1, 4)
        self.edtAnalysisDocument = QtGui.QLineEdit(self.groupBox_2)
        self.edtAnalysisDocument.setObjectName(_fromUtf8("edtAnalysisDocument"))
        self.gridlayout3.addWidget(self.edtAnalysisDocument, 1, 1, 1, 3)
        self.edtAnalysisNote = QtGui.QLineEdit(self.groupBox_2)
        self.edtAnalysisNote.setObjectName(_fromUtf8("edtAnalysisNote"))
        self.gridlayout3.addWidget(self.edtAnalysisNote, 3, 1, 1, 3)
        self.edtAnalysisEventCode = QtGui.QLineEdit(self.groupBox_2)
        self.edtAnalysisEventCode.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAnalysisEventCode.sizePolicy().hasHeightForWidth())
        self.edtAnalysisEventCode.setSizePolicy(sizePolicy)
        self.edtAnalysisEventCode.setObjectName(_fromUtf8("edtAnalysisEventCode"))
        self.gridlayout3.addWidget(self.edtAnalysisEventCode, 5, 1, 1, 1)
        self.chkAnalysisClientCode = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAnalysisClientCode.sizePolicy().hasHeightForWidth())
        self.chkAnalysisClientCode.setSizePolicy(sizePolicy)
        self.chkAnalysisClientCode.setObjectName(_fromUtf8("chkAnalysisClientCode"))
        self.gridlayout3.addWidget(self.chkAnalysisClientCode, 4, 0, 1, 1)
        self.cmbAnalysisService = CRBComboBox(self.groupBox_2)
        self.cmbAnalysisService.setEnabled(False)
        self.cmbAnalysisService.setObjectName(_fromUtf8("cmbAnalysisService"))
        self.gridlayout3.addWidget(self.cmbAnalysisService, 6, 1, 1, 3)
        self.lblAnalysisDocument = QtGui.QLabel(self.groupBox_2)
        self.lblAnalysisDocument.setObjectName(_fromUtf8("lblAnalysisDocument"))
        self.gridlayout3.addWidget(self.lblAnalysisDocument, 1, 0, 1, 1)
        self.chkAnalysisService = QtGui.QCheckBox(self.groupBox_2)
        self.chkAnalysisService.setObjectName(_fromUtf8("chkAnalysisService"))
        self.gridlayout3.addWidget(self.chkAnalysisService, 6, 0, 1, 1)
        self.chkAnalysisCreateDate = QtGui.QCheckBox(self.groupBox_2)
        self.chkAnalysisCreateDate.setObjectName(_fromUtf8("chkAnalysisCreateDate"))
        self.gridlayout3.addWidget(self.chkAnalysisCreateDate, 7, 0, 1, 1)
        self.edtAnalysisCreateBegDate = CDateEdit(self.groupBox_2)
        self.edtAnalysisCreateBegDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAnalysisCreateBegDate.sizePolicy().hasHeightForWidth())
        self.edtAnalysisCreateBegDate.setSizePolicy(sizePolicy)
        self.edtAnalysisCreateBegDate.setReadOnly(False)
        self.edtAnalysisCreateBegDate.setObjectName(_fromUtf8("edtAnalysisCreateBegDate"))
        self.gridlayout3.addWidget(self.edtAnalysisCreateBegDate, 7, 1, 1, 1)
        self.lblAnalysisEndDate_2 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAnalysisEndDate_2.sizePolicy().hasHeightForWidth())
        self.lblAnalysisEndDate_2.setSizePolicy(sizePolicy)
        self.lblAnalysisEndDate_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAnalysisEndDate_2.setObjectName(_fromUtf8("lblAnalysisEndDate_2"))
        self.gridlayout3.addWidget(self.lblAnalysisEndDate_2, 7, 2, 1, 1)
        self.edtAnalysisCreateEndDate = CDateEdit(self.groupBox_2)
        self.edtAnalysisCreateEndDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAnalysisCreateEndDate.sizePolicy().hasHeightForWidth())
        self.edtAnalysisCreateEndDate.setSizePolicy(sizePolicy)
        self.edtAnalysisCreateEndDate.setReadOnly(False)
        self.edtAnalysisCreateEndDate.setObjectName(_fromUtf8("edtAnalysisCreateEndDate"))
        self.gridlayout3.addWidget(self.edtAnalysisCreateEndDate, 7, 3, 1, 1)
        self.gridlayout2.addWidget(self.groupBox_2, 2, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout2.addItem(spacerItem1, 5, 0, 1, 2)
        self.bbxAnalysis = CApplyResetDialogButtonBox(self.tabAnalysis)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bbxAnalysis.sizePolicy().hasHeightForWidth())
        self.bbxAnalysis.setSizePolicy(sizePolicy)
        self.bbxAnalysis.setOrientation(QtCore.Qt.Horizontal)
        self.bbxAnalysis.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.bbxAnalysis.setObjectName(_fromUtf8("bbxAnalysis"))
        self.gridlayout2.addWidget(self.bbxAnalysis, 5, 2, 1, 1)
        self.edtAnalysisAccountId = CAccountIdLineEdit(self.tabAnalysis)
        self.edtAnalysisAccountId.setEnabled(False)
        self.edtAnalysisAccountId.setObjectName(_fromUtf8("edtAnalysisAccountId"))
        self.gridlayout2.addWidget(self.edtAnalysisAccountId, 0, 1, 1, 2)
        self.chkAnalysisAccountId = QtGui.QCheckBox(self.tabAnalysis)
        self.chkAnalysisAccountId.setObjectName(_fromUtf8("chkAnalysisAccountId"))
        self.gridlayout2.addWidget(self.chkAnalysisAccountId, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tabAnalysis)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridlayout4 = QtGui.QGridLayout(self.groupBox)
        self.gridlayout4.setMargin(2)
        self.gridlayout4.setSpacing(2)
        self.gridlayout4.setObjectName(_fromUtf8("gridlayout4"))
        self.cmbAnalysisOrgStructure = COrgStructureComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAnalysisOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbAnalysisOrgStructure.setSizePolicy(sizePolicy)
        self.cmbAnalysisOrgStructure.setMinimumSize(QtCore.QSize(250, 0))
        self.cmbAnalysisOrgStructure.setObjectName(_fromUtf8("cmbAnalysisOrgStructure"))
        self.gridlayout4.addWidget(self.cmbAnalysisOrgStructure, 2, 0, 1, 12)
        self.edtAnalysisBegDate = CDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAnalysisBegDate.sizePolicy().hasHeightForWidth())
        self.edtAnalysisBegDate.setSizePolicy(sizePolicy)
        self.edtAnalysisBegDate.setObjectName(_fromUtf8("edtAnalysisBegDate"))
        self.gridlayout4.addWidget(self.edtAnalysisBegDate, 0, 1, 1, 3)
        self.lblAnalysisEndDate = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAnalysisEndDate.sizePolicy().hasHeightForWidth())
        self.lblAnalysisEndDate.setSizePolicy(sizePolicy)
        self.lblAnalysisEndDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAnalysisEndDate.setObjectName(_fromUtf8("lblAnalysisEndDate"))
        self.gridlayout4.addWidget(self.lblAnalysisEndDate, 0, 4, 1, 2)
        self.lblAnalysisBegDate = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAnalysisBegDate.sizePolicy().hasHeightForWidth())
        self.lblAnalysisBegDate.setSizePolicy(sizePolicy)
        self.lblAnalysisBegDate.setObjectName(_fromUtf8("lblAnalysisBegDate"))
        self.gridlayout4.addWidget(self.lblAnalysisBegDate, 0, 0, 1, 1)
        self.lblAnalysisNumber = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAnalysisNumber.sizePolicy().hasHeightForWidth())
        self.lblAnalysisNumber.setSizePolicy(sizePolicy)
        self.lblAnalysisNumber.setObjectName(_fromUtf8("lblAnalysisNumber"))
        self.gridlayout4.addWidget(self.lblAnalysisNumber, 1, 0, 1, 1)
        self.edtAnalysisNumber = QtGui.QLineEdit(self.groupBox)
        self.edtAnalysisNumber.setObjectName(_fromUtf8("edtAnalysisNumber"))
        self.gridlayout4.addWidget(self.edtAnalysisNumber, 1, 1, 1, 11)
        self.lblAnalysisPayer = QtGui.QLabel(self.groupBox)
        self.lblAnalysisPayer.setObjectName(_fromUtf8("lblAnalysisPayer"))
        self.gridlayout4.addWidget(self.lblAnalysisPayer, 3, 0, 1, 1)
        self.edtAnalysisEndDate = CDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAnalysisEndDate.sizePolicy().hasHeightForWidth())
        self.edtAnalysisEndDate.setSizePolicy(sizePolicy)
        self.edtAnalysisEndDate.setObjectName(_fromUtf8("edtAnalysisEndDate"))
        self.gridlayout4.addWidget(self.edtAnalysisEndDate, 0, 6, 1, 1)
        self.lblAnalysisAccountType = QtGui.QLabel(self.groupBox)
        self.lblAnalysisAccountType.setObjectName(_fromUtf8("lblAnalysisAccountType"))
        self.gridlayout4.addWidget(self.lblAnalysisAccountType, 4, 0, 1, 1)
        self.cmbAnalysisPayer = COrgIsPayer23ComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAnalysisPayer.sizePolicy().hasHeightForWidth())
        self.cmbAnalysisPayer.setSizePolicy(sizePolicy)
        self.cmbAnalysisPayer.setObjectName(_fromUtf8("cmbAnalysisPayer"))
        self.gridlayout4.addWidget(self.cmbAnalysisPayer, 3, 1, 1, 11)
        self.cmbAnalysisAccountType = CRBComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAnalysisAccountType.sizePolicy().hasHeightForWidth())
        self.cmbAnalysisAccountType.setSizePolicy(sizePolicy)
        self.cmbAnalysisAccountType.setObjectName(_fromUtf8("cmbAnalysisAccountType"))
        self.gridlayout4.addWidget(self.cmbAnalysisAccountType, 4, 1, 1, 11)
        self.lblGroupId = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGroupId.sizePolicy().hasHeightForWidth())
        self.lblGroupId.setSizePolicy(sizePolicy)
        self.lblGroupId.setObjectName(_fromUtf8("lblGroupId"))
        self.gridlayout4.addWidget(self.lblGroupId, 5, 0, 1, 1)
        self.cmbGroupId = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbGroupId.sizePolicy().hasHeightForWidth())
        self.cmbGroupId.setSizePolicy(sizePolicy)
        self.cmbGroupId.setObjectName(_fromUtf8("cmbGroupId"))
        self.gridlayout4.addWidget(self.cmbGroupId, 5, 1, 1, 11)
        self.gridlayout2.addWidget(self.groupBox, 1, 0, 1, 3)
        self.tabWorkType.addTab(self.tabAnalysis, _fromUtf8(""))
        self.tabHstory = QtGui.QWidget()
        self.tabHstory.setObjectName(_fromUtf8("tabHstory"))
        self.gridlayout5 = QtGui.QGridLayout(self.tabHstory)
        self.gridlayout5.setMargin(2)
        self.gridlayout5.setSpacing(2)
        self.gridlayout5.setObjectName(_fromUtf8("gridlayout5"))
        spacerItem2 = QtGui.QSpacerItem(46, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout5.addItem(spacerItem2, 5, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tabHstory)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridlayout6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridlayout6.setMargin(2)
        self.gridlayout6.setSpacing(2)
        self.gridlayout6.setObjectName(_fromUtf8("gridlayout6"))
        self.lblHistoryBegDate = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHistoryBegDate.sizePolicy().hasHeightForWidth())
        self.lblHistoryBegDate.setSizePolicy(sizePolicy)
        self.lblHistoryBegDate.setObjectName(_fromUtf8("lblHistoryBegDate"))
        self.gridlayout6.addWidget(self.lblHistoryBegDate, 0, 0, 1, 1)
        self.edtHistoryBegDate = CDateEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHistoryBegDate.sizePolicy().hasHeightForWidth())
        self.edtHistoryBegDate.setSizePolicy(sizePolicy)
        self.edtHistoryBegDate.setObjectName(_fromUtf8("edtHistoryBegDate"))
        self.gridlayout6.addWidget(self.edtHistoryBegDate, 0, 1, 1, 1)
        self.lblHistoryEndDate = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHistoryEndDate.sizePolicy().hasHeightForWidth())
        self.lblHistoryEndDate.setSizePolicy(sizePolicy)
        self.lblHistoryEndDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblHistoryEndDate.setObjectName(_fromUtf8("lblHistoryEndDate"))
        self.gridlayout6.addWidget(self.lblHistoryEndDate, 0, 2, 1, 1)
        self.edtHistoryEndDate = CDateEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtHistoryEndDate.sizePolicy().hasHeightForWidth())
        self.edtHistoryEndDate.setSizePolicy(sizePolicy)
        self.edtHistoryEndDate.setObjectName(_fromUtf8("edtHistoryEndDate"))
        self.gridlayout6.addWidget(self.edtHistoryEndDate, 0, 3, 1, 1)
        self.lblHistoryNumber = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHistoryNumber.sizePolicy().hasHeightForWidth())
        self.lblHistoryNumber.setSizePolicy(sizePolicy)
        self.lblHistoryNumber.setObjectName(_fromUtf8("lblHistoryNumber"))
        self.gridlayout6.addWidget(self.lblHistoryNumber, 1, 0, 1, 1)
        self.edtHistoryNumber = QtGui.QLineEdit(self.groupBox_4)
        self.edtHistoryNumber.setObjectName(_fromUtf8("edtHistoryNumber"))
        self.gridlayout6.addWidget(self.edtHistoryNumber, 1, 1, 1, 5)
        self.cmbHistoryOrgStructure = COrgStructureComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbHistoryOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbHistoryOrgStructure.setSizePolicy(sizePolicy)
        self.cmbHistoryOrgStructure.setObjectName(_fromUtf8("cmbHistoryOrgStructure"))
        self.gridlayout6.addWidget(self.cmbHistoryOrgStructure, 2, 0, 1, 6)
        self.lblHistoryPayer = QtGui.QLabel(self.groupBox_4)
        self.lblHistoryPayer.setObjectName(_fromUtf8("lblHistoryPayer"))
        self.gridlayout6.addWidget(self.lblHistoryPayer, 3, 0, 1, 6)
        self.btnHistorySelectPayer = QtGui.QToolButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHistorySelectPayer.sizePolicy().hasHeightForWidth())
        self.btnHistorySelectPayer.setSizePolicy(sizePolicy)
        self.btnHistorySelectPayer.setObjectName(_fromUtf8("btnHistorySelectPayer"))
        self.gridlayout6.addWidget(self.btnHistorySelectPayer, 4, 5, 1, 1)
        self.cmbHistoryPayer = COrgComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbHistoryPayer.sizePolicy().hasHeightForWidth())
        self.cmbHistoryPayer.setSizePolicy(sizePolicy)
        self.cmbHistoryPayer.setObjectName(_fromUtf8("cmbHistoryPayer"))
        self.gridlayout6.addWidget(self.cmbHistoryPayer, 4, 0, 1, 5)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem3, 0, 4, 1, 2)
        self.gridlayout5.addWidget(self.groupBox_4, 0, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.tabHstory)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridlayout7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridlayout7.setMargin(2)
        self.gridlayout7.setSpacing(2)
        self.gridlayout7.setObjectName(_fromUtf8("gridlayout7"))
        self.cmbHistoryAccountItems = QtGui.QComboBox(self.groupBox_3)
        self.cmbHistoryAccountItems.setObjectName(_fromUtf8("cmbHistoryAccountItems"))
        self.cmbHistoryAccountItems.addItem(_fromUtf8(""))
        self.cmbHistoryAccountItems.addItem(_fromUtf8(""))
        self.cmbHistoryAccountItems.addItem(_fromUtf8(""))
        self.cmbHistoryAccountItems.addItem(_fromUtf8(""))
        self.cmbHistoryAccountItems.addItem(_fromUtf8(""))
        self.cmbHistoryAccountItems.addItem(_fromUtf8(""))
        self.cmbHistoryAccountItems.addItem(_fromUtf8(""))
        self.gridlayout7.addWidget(self.cmbHistoryAccountItems, 0, 0, 1, 2)
        self.edtHistoryDocument = QtGui.QLineEdit(self.groupBox_3)
        self.edtHistoryDocument.setObjectName(_fromUtf8("edtHistoryDocument"))
        self.gridlayout7.addWidget(self.edtHistoryDocument, 1, 1, 1, 1)
        self.lblHistoryAccountDocument = QtGui.QLabel(self.groupBox_3)
        self.lblHistoryAccountDocument.setObjectName(_fromUtf8("lblHistoryAccountDocument"))
        self.gridlayout7.addWidget(self.lblHistoryAccountDocument, 1, 0, 1, 1)
        self.cmbHistoryPayRefuseType = CRBComboBox(self.groupBox_3)
        self.cmbHistoryPayRefuseType.setObjectName(_fromUtf8("cmbHistoryPayRefuseType"))
        self.gridlayout7.addWidget(self.cmbHistoryPayRefuseType, 2, 1, 1, 1)
        self.lblHistoryPayRefuseType = QtGui.QLabel(self.groupBox_3)
        self.lblHistoryPayRefuseType.setObjectName(_fromUtf8("lblHistoryPayRefuseType"))
        self.gridlayout7.addWidget(self.lblHistoryPayRefuseType, 2, 0, 1, 1)
        self.lblHistoryNote = QtGui.QLabel(self.groupBox_3)
        self.lblHistoryNote.setObjectName(_fromUtf8("lblHistoryNote"))
        self.gridlayout7.addWidget(self.lblHistoryNote, 3, 0, 1, 1)
        self.edtHistoryNote = QtGui.QLineEdit(self.groupBox_3)
        self.edtHistoryNote.setObjectName(_fromUtf8("edtHistoryNote"))
        self.gridlayout7.addWidget(self.edtHistoryNote, 3, 1, 1, 1)
        self.gridlayout5.addWidget(self.groupBox_3, 3, 0, 1, 2)
        self.chkHistoryOnlyCurrentService = QtGui.QCheckBox(self.tabHstory)
        self.chkHistoryOnlyCurrentService.setObjectName(_fromUtf8("chkHistoryOnlyCurrentService"))
        self.gridlayout5.addWidget(self.chkHistoryOnlyCurrentService, 4, 0, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout5.addItem(spacerItem4, 6, 0, 1, 1)
        self.bbxHistory = CApplyResetDialogButtonBox(self.tabHstory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bbxHistory.sizePolicy().hasHeightForWidth())
        self.bbxHistory.setSizePolicy(sizePolicy)
        self.bbxHistory.setOrientation(QtCore.Qt.Horizontal)
        self.bbxHistory.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.bbxHistory.setObjectName(_fromUtf8("bbxHistory"))
        self.gridlayout5.addWidget(self.bbxHistory, 6, 1, 1, 1)
        self.tabWorkType.addTab(self.tabHstory, _fromUtf8(""))
        self.vboxlayout.addWidget(self.tabWorkType)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.vboxlayout1.setSpacing(4)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.splitter_2 = QtGui.QSplitter(self.layoutWidget1)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setChildrenCollapsible(False)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget2 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.vboxlayout2.setSpacing(4)
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.groupTotal = QtGui.QGroupBox(self.layoutWidget2)
        self.groupTotal.setObjectName(_fromUtf8("groupTotal"))
        self.hboxlayout = QtGui.QHBoxLayout(self.groupTotal)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setMargin(4)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.lblTotalAccounts = QtGui.QLabel(self.groupTotal)
        self.lblTotalAccounts.setObjectName(_fromUtf8("lblTotalAccounts"))
        self.hboxlayout.addWidget(self.lblTotalAccounts)
        self.edtTotalAccounts = QtGui.QLineEdit(self.groupTotal)
        self.edtTotalAccounts.setAlignment(QtCore.Qt.AlignRight)
        self.edtTotalAccounts.setReadOnly(True)
        self.edtTotalAccounts.setObjectName(_fromUtf8("edtTotalAccounts"))
        self.hboxlayout.addWidget(self.edtTotalAccounts)
        self.lblTotalSum = QtGui.QLabel(self.groupTotal)
        self.lblTotalSum.setObjectName(_fromUtf8("lblTotalSum"))
        self.hboxlayout.addWidget(self.lblTotalSum)
        self.edtTotalSum = QtGui.QLineEdit(self.groupTotal)
        self.edtTotalSum.setAlignment(QtCore.Qt.AlignRight)
        self.edtTotalSum.setReadOnly(True)
        self.edtTotalSum.setObjectName(_fromUtf8("edtTotalSum"))
        self.hboxlayout.addWidget(self.edtTotalSum)
        self.lblTotalExposed = QtGui.QLabel(self.groupTotal)
        self.lblTotalExposed.setObjectName(_fromUtf8("lblTotalExposed"))
        self.hboxlayout.addWidget(self.lblTotalExposed)
        self.edtTotalExposed = QtGui.QLineEdit(self.groupTotal)
        self.edtTotalExposed.setAlignment(QtCore.Qt.AlignRight)
        self.edtTotalExposed.setReadOnly(True)
        self.edtTotalExposed.setObjectName(_fromUtf8("edtTotalExposed"))
        self.hboxlayout.addWidget(self.edtTotalExposed)
        self.lblTotalPayed = QtGui.QLabel(self.groupTotal)
        self.lblTotalPayed.setObjectName(_fromUtf8("lblTotalPayed"))
        self.hboxlayout.addWidget(self.lblTotalPayed)
        self.edtTotalPayed = QtGui.QLineEdit(self.groupTotal)
        self.edtTotalPayed.setAlignment(QtCore.Qt.AlignRight)
        self.edtTotalPayed.setReadOnly(True)
        self.edtTotalPayed.setObjectName(_fromUtf8("edtTotalPayed"))
        self.hboxlayout.addWidget(self.edtTotalPayed)
        self.lblTotalRejected = QtGui.QLabel(self.groupTotal)
        self.lblTotalRejected.setObjectName(_fromUtf8("lblTotalRejected"))
        self.hboxlayout.addWidget(self.lblTotalRejected)
        self.edtTotalRefused = QtGui.QLineEdit(self.groupTotal)
        self.edtTotalRefused.setAlignment(QtCore.Qt.AlignRight)
        self.edtTotalRefused.setReadOnly(True)
        self.edtTotalRefused.setObjectName(_fromUtf8("edtTotalRefused"))
        self.hboxlayout.addWidget(self.edtTotalRefused)
        self.vboxlayout2.addWidget(self.groupTotal)
        self.tblAccounts = CTableView(self.layoutWidget2)
        self.tblAccounts.setObjectName(_fromUtf8("tblAccounts"))
        self.vboxlayout2.addWidget(self.tblAccounts)
        self.layoutWidget3 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.vboxlayout3 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.vboxlayout3.setSpacing(4)
        self.vboxlayout3.setMargin(0)
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        self.tabWidget_2 = QtGui.QTabWidget(self.layoutWidget3)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridlayout8 = QtGui.QGridLayout(self.tab)
        self.gridlayout8.setMargin(4)
        self.gridlayout8.setSpacing(4)
        self.gridlayout8.setObjectName(_fromUtf8("gridlayout8"))
        self.tblAccountItems = CTableView(self.tab)
        self.tblAccountItems.setObjectName(_fromUtf8("tblAccountItems"))
        self.gridlayout8.addWidget(self.tblAccountItems, 2, 0, 1, 1)
        self.lblAccountItemInfo = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAccountItemInfo.sizePolicy().hasHeightForWidth())
        self.lblAccountItemInfo.setSizePolicy(sizePolicy)
        self.lblAccountItemInfo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblAccountItemInfo.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblAccountItemInfo.setLineWidth(1)
        self.lblAccountItemInfo.setMidLineWidth(0)
        self.lblAccountItemInfo.setText(_fromUtf8(""))
        self.lblAccountItemInfo.setWordWrap(True)
        self.lblAccountItemInfo.setObjectName(_fromUtf8("lblAccountItemInfo"))
        self.gridlayout8.addWidget(self.lblAccountItemInfo, 3, 0, 1, 1)
        self.filter = QtGui.QWidget(self.tab)
        self.filter.setObjectName(_fromUtf8("filter"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.filter)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblFioFilter = QtGui.QLabel(self.filter)
        self.lblFioFilter.setObjectName(_fromUtf8("lblFioFilter"))
        self.horizontalLayout.addWidget(self.lblFioFilter)
        self.edtFioFilter = QtGui.QLineEdit(self.filter)
        self.edtFioFilter.setObjectName(_fromUtf8("edtFioFilter"))
        self.horizontalLayout.addWidget(self.edtFioFilter)
        self.btnApplyFilter = QtGui.QPushButton(self.filter)
        self.btnApplyFilter.setObjectName(_fromUtf8("btnApplyFilter"))
        self.horizontalLayout.addWidget(self.btnApplyFilter)
        self.gridlayout8.addWidget(self.filter, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridlayout9 = QtGui.QGridLayout(self.tab_2)
        self.gridlayout9.setMargin(4)
        self.gridlayout9.setSpacing(4)
        self.gridlayout9.setObjectName(_fromUtf8("gridlayout9"))
        self.tblAccountContingent = CTableView(self.tab_2)
        self.tblAccountContingent.setObjectName(_fromUtf8("tblAccountContingent"))
        self.gridlayout9.addWidget(self.tblAccountContingent, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.vboxlayout3.addWidget(self.tabWidget_2)
        self.groupAccount = QtGui.QGroupBox(self.layoutWidget3)
        self.groupAccount.setObjectName(_fromUtf8("groupAccount"))
        self.gridLayout = QtGui.QGridLayout(self.groupAccount)
        self.gridLayout.setMargin(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblAccountRejected = QtGui.QLabel(self.groupAccount)
        self.lblAccountRejected.setObjectName(_fromUtf8("lblAccountRejected"))
        self.gridLayout.addWidget(self.lblAccountRejected, 0, 8, 1, 1)
        self.edtAccountItemsVisitsCount = QtGui.QLineEdit(self.groupAccount)
        self.edtAccountItemsVisitsCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtAccountItemsVisitsCount.setReadOnly(True)
        self.edtAccountItemsVisitsCount.setObjectName(_fromUtf8("edtAccountItemsVisitsCount"))
        self.gridLayout.addWidget(self.edtAccountItemsVisitsCount, 1, 9, 1, 1)
        self.edtAccountItemsRefused = QtGui.QLineEdit(self.groupAccount)
        self.edtAccountItemsRefused.setAlignment(QtCore.Qt.AlignRight)
        self.edtAccountItemsRefused.setReadOnly(True)
        self.edtAccountItemsRefused.setObjectName(_fromUtf8("edtAccountItemsRefused"))
        self.gridLayout.addWidget(self.edtAccountItemsRefused, 0, 9, 1, 1)
        self.edtAccountItemsClientsCount = QtGui.QLineEdit(self.groupAccount)
        self.edtAccountItemsClientsCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtAccountItemsClientsCount.setReadOnly(True)
        self.edtAccountItemsClientsCount.setObjectName(_fromUtf8("edtAccountItemsClientsCount"))
        self.gridLayout.addWidget(self.edtAccountItemsClientsCount, 1, 3, 1, 1)
        self.edtAccountItemsEventsCount = QtGui.QLineEdit(self.groupAccount)
        self.edtAccountItemsEventsCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtAccountItemsEventsCount.setReadOnly(True)
        self.edtAccountItemsEventsCount.setObjectName(_fromUtf8("edtAccountItemsEventsCount"))
        self.gridLayout.addWidget(self.edtAccountItemsEventsCount, 1, 5, 1, 1)
        self.lblAccountPayed = QtGui.QLabel(self.groupAccount)
        self.lblAccountPayed.setObjectName(_fromUtf8("lblAccountPayed"))
        self.gridLayout.addWidget(self.lblAccountPayed, 0, 6, 1, 1)
        self.edtAccountItemsPayed = QtGui.QLineEdit(self.groupAccount)
        self.edtAccountItemsPayed.setAlignment(QtCore.Qt.AlignRight)
        self.edtAccountItemsPayed.setReadOnly(True)
        self.edtAccountItemsPayed.setObjectName(_fromUtf8("edtAccountItemsPayed"))
        self.gridLayout.addWidget(self.edtAccountItemsPayed, 0, 7, 1, 1)
        self.lblAccountActionsCount = QtGui.QLabel(self.groupAccount)
        self.lblAccountActionsCount.setObjectName(_fromUtf8("lblAccountActionsCount"))
        self.gridLayout.addWidget(self.lblAccountActionsCount, 1, 6, 1, 1)
        self.lblAccountEventsCount = QtGui.QLabel(self.groupAccount)
        self.lblAccountEventsCount.setObjectName(_fromUtf8("lblAccountEventsCount"))
        self.gridLayout.addWidget(self.lblAccountEventsCount, 1, 4, 1, 1)
        self.edtAccountItemsActionsCount = QtGui.QLineEdit(self.groupAccount)
        self.edtAccountItemsActionsCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtAccountItemsActionsCount.setReadOnly(True)
        self.edtAccountItemsActionsCount.setObjectName(_fromUtf8("edtAccountItemsActionsCount"))
        self.gridLayout.addWidget(self.edtAccountItemsActionsCount, 1, 7, 1, 1)
        self.lblAccountVisitsCount = QtGui.QLabel(self.groupAccount)
        self.lblAccountVisitsCount.setObjectName(_fromUtf8("lblAccountVisitsCount"))
        self.gridLayout.addWidget(self.lblAccountVisitsCount, 1, 8, 1, 1)
        self.lblAccountClientsCount = QtGui.QLabel(self.groupAccount)
        self.lblAccountClientsCount.setObjectName(_fromUtf8("lblAccountClientsCount"))
        self.gridLayout.addWidget(self.lblAccountClientsCount, 1, 2, 1, 1)
        self.lblAccountItemsCount = QtGui.QLabel(self.groupAccount)
        self.lblAccountItemsCount.setObjectName(_fromUtf8("lblAccountItemsCount"))
        self.gridLayout.addWidget(self.lblAccountItemsCount, 1, 0, 1, 1)
        self.edtAccountItemsCount = QtGui.QLineEdit(self.groupAccount)
        self.edtAccountItemsCount.setAlignment(QtCore.Qt.AlignRight)
        self.edtAccountItemsCount.setReadOnly(True)
        self.edtAccountItemsCount.setObjectName(_fromUtf8("edtAccountItemsCount"))
        self.gridLayout.addWidget(self.edtAccountItemsCount, 1, 1, 1, 1)
        self.edtAccountItemsExposed = QtGui.QLineEdit(self.groupAccount)
        self.edtAccountItemsExposed.setAlignment(QtCore.Qt.AlignRight)
        self.edtAccountItemsExposed.setReadOnly(True)
        self.edtAccountItemsExposed.setObjectName(_fromUtf8("edtAccountItemsExposed"))
        self.gridLayout.addWidget(self.edtAccountItemsExposed, 0, 5, 1, 1)
        self.lblAccountExposed = QtGui.QLabel(self.groupAccount)
        self.lblAccountExposed.setObjectName(_fromUtf8("lblAccountExposed"))
        self.gridLayout.addWidget(self.lblAccountExposed, 0, 4, 1, 1)
        self.lblAccountSum = QtGui.QLabel(self.groupAccount)
        self.lblAccountSum.setObjectName(_fromUtf8("lblAccountSum"))
        self.gridLayout.addWidget(self.lblAccountSum, 0, 2, 1, 1)
        self.edtAccountItemsSum = QtGui.QLineEdit(self.groupAccount)
        self.edtAccountItemsSum.setAlignment(QtCore.Qt.AlignRight)
        self.edtAccountItemsSum.setReadOnly(True)
        self.edtAccountItemsSum.setObjectName(_fromUtf8("edtAccountItemsSum"))
        self.gridLayout.addWidget(self.edtAccountItemsSum, 0, 3, 1, 1)
        self.vboxlayout3.addWidget(self.groupAccount)
        self.vboxlayout1.addWidget(self.splitter_2)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setSpacing(4)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.btnForm = QtGui.QPushButton(self.layoutWidget1)
        self.btnForm.setObjectName(_fromUtf8("btnForm"))
        self.hboxlayout1.addWidget(self.btnForm)
        self.btnPrint = CPrintButton(self.layoutWidget1)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.hboxlayout1.addWidget(self.btnPrint)
        self.btnRefresh = QtGui.QPushButton(self.layoutWidget1)
        self.btnRefresh.setObjectName(_fromUtf8("btnRefresh"))
        self.hboxlayout1.addWidget(self.btnRefresh)
        self.btnExport = QtGui.QPushButton(self.layoutWidget1)
        self.btnExport.setObjectName(_fromUtf8("btnExport"))
        self.hboxlayout1.addWidget(self.btnExport)
        self.btnImport = QtGui.QPushButton(self.layoutWidget1)
        self.btnImport.setObjectName(_fromUtf8("btnImport"))
        self.hboxlayout1.addWidget(self.btnImport)
        self.btnCheck = QtGui.QPushButton(self.layoutWidget1)
        self.btnCheck.setObjectName(_fromUtf8("btnCheck"))
        self.hboxlayout1.addWidget(self.btnCheck)
        self.btnClose = QtGui.QPushButton(self.layoutWidget1)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.hboxlayout1.addWidget(self.btnClose)
        self.vboxlayout1.addLayout(self.hboxlayout1)
        self.gridlayout.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.lblAnalysisNote.setBuddy(self.edtAnalysisNote)
        self.lblAnalysisPayRefuseType.setBuddy(self.cmbAnalysisPayRefuseType)
        self.lblAnalysisDocument.setBuddy(self.edtAnalysisDocument)
        self.lblAnalysisEndDate_2.setBuddy(self.edtAnalysisEndDate)
        self.lblAnalysisEndDate.setBuddy(self.edtAnalysisEndDate)
        self.lblAnalysisBegDate.setBuddy(self.edtAnalysisBegDate)
        self.lblAnalysisNumber.setBuddy(self.edtAnalysisNumber)
        self.lblAnalysisPayer.setBuddy(self.edtAnalysisNumber)
        self.lblAnalysisAccountType.setBuddy(self.edtAnalysisNumber)
        self.lblHistoryBegDate.setBuddy(self.edtHistoryBegDate)
        self.lblHistoryEndDate.setBuddy(self.edtHistoryEndDate)
        self.lblHistoryNumber.setBuddy(self.edtHistoryNumber)
        self.lblHistoryAccountDocument.setBuddy(self.edtHistoryDocument)
        self.lblHistoryPayRefuseType.setBuddy(self.cmbHistoryPayRefuseType)
        self.lblHistoryNote.setBuddy(self.edtHistoryNote)
        self.lblTotalAccounts.setBuddy(self.edtTotalAccounts)
        self.lblTotalSum.setBuddy(self.edtTotalSum)
        self.lblTotalExposed.setBuddy(self.edtTotalExposed)
        self.lblTotalPayed.setBuddy(self.edtTotalPayed)
        self.lblTotalRejected.setBuddy(self.edtTotalRefused)
        self.lblFioFilter.setBuddy(self.edtFioFilter)
        self.lblAccountRejected.setBuddy(self.edtAccountItemsRefused)
        self.lblAccountPayed.setBuddy(self.edtAccountItemsPayed)
        self.lblAccountItemsCount.setBuddy(self.edtAccountItemsCount)
        self.lblAccountExposed.setBuddy(self.edtAccountItemsExposed)
        self.lblAccountSum.setBuddy(self.edtAccountItemsSum)

        self.retranslateUi(AccountingDialog)
        self.tabWorkType.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.btnClose, QtCore.SIGNAL(_fromUtf8("clicked()")), AccountingDialog.accept)
        QtCore.QObject.connect(self.chkAnalysisClientCode, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAnalysisClientCode.setEnabled)
        QtCore.QObject.connect(self.chkAnalysisClientCode, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbAnalysisClientCodeType.setEnabled)
        QtCore.QObject.connect(self.chkAnalysisAccountId, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAnalysisAccountId.setEnabled)
        QtCore.QObject.connect(self.chkAnalysisEventCode, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAnalysisEventCode.setEnabled)
        QtCore.QObject.connect(self.chkAnalysisEventCode, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbAnalysisEventCodeType.setEnabled)
        QtCore.QObject.connect(self.chkAnalysisService, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbAnalysisService.setEnabled)
        QtCore.QObject.connect(self.chkAnalysisCreateDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAnalysisCreateBegDate.setEnabled)
        QtCore.QObject.connect(self.chkAnalysisCreateDate, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtAnalysisCreateEndDate.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(AccountingDialog)
        AccountingDialog.setTabOrder(self.treeContracts, self.tblContragents)
        AccountingDialog.setTabOrder(self.tblContragents, self.tabWorkType)
        AccountingDialog.setTabOrder(self.tabWorkType, self.cmbCalcOrgStructure)
        AccountingDialog.setTabOrder(self.cmbCalcOrgStructure, self.clnCalcCalendar)
        AccountingDialog.setTabOrder(self.clnCalcCalendar, self.chkAnalysisAccountId)
        AccountingDialog.setTabOrder(self.chkAnalysisAccountId, self.edtAnalysisAccountId)
        AccountingDialog.setTabOrder(self.edtAnalysisAccountId, self.edtAnalysisBegDate)
        AccountingDialog.setTabOrder(self.edtAnalysisBegDate, self.edtAnalysisNumber)
        AccountingDialog.setTabOrder(self.edtAnalysisNumber, self.cmbAnalysisOrgStructure)
        AccountingDialog.setTabOrder(self.cmbAnalysisOrgStructure, self.cmbAnalysisPayer)
        AccountingDialog.setTabOrder(self.cmbAnalysisPayer, self.cmbAnalysisAccountItems)
        AccountingDialog.setTabOrder(self.cmbAnalysisAccountItems, self.edtAnalysisDocument)
        AccountingDialog.setTabOrder(self.edtAnalysisDocument, self.cmbAnalysisPayRefuseType)
        AccountingDialog.setTabOrder(self.cmbAnalysisPayRefuseType, self.edtAnalysisNote)
        AccountingDialog.setTabOrder(self.edtAnalysisNote, self.chkAnalysisClientCode)
        AccountingDialog.setTabOrder(self.chkAnalysisClientCode, self.edtAnalysisClientCode)
        AccountingDialog.setTabOrder(self.edtAnalysisClientCode, self.cmbAnalysisClientCodeType)
        AccountingDialog.setTabOrder(self.cmbAnalysisClientCodeType, self.chkAnalysisEventCode)
        AccountingDialog.setTabOrder(self.chkAnalysisEventCode, self.cmbAnalysisEventCodeType)
        AccountingDialog.setTabOrder(self.cmbAnalysisEventCodeType, self.edtAnalysisEventCode)
        AccountingDialog.setTabOrder(self.edtAnalysisEventCode, self.bbxAnalysis)
        AccountingDialog.setTabOrder(self.bbxAnalysis, self.edtHistoryBegDate)
        AccountingDialog.setTabOrder(self.edtHistoryBegDate, self.edtHistoryEndDate)
        AccountingDialog.setTabOrder(self.edtHistoryEndDate, self.edtHistoryNumber)
        AccountingDialog.setTabOrder(self.edtHistoryNumber, self.cmbHistoryOrgStructure)
        AccountingDialog.setTabOrder(self.cmbHistoryOrgStructure, self.cmbHistoryPayer)
        AccountingDialog.setTabOrder(self.cmbHistoryPayer, self.btnHistorySelectPayer)
        AccountingDialog.setTabOrder(self.btnHistorySelectPayer, self.cmbHistoryAccountItems)
        AccountingDialog.setTabOrder(self.cmbHistoryAccountItems, self.edtHistoryDocument)
        AccountingDialog.setTabOrder(self.edtHistoryDocument, self.cmbHistoryPayRefuseType)
        AccountingDialog.setTabOrder(self.cmbHistoryPayRefuseType, self.edtHistoryNote)
        AccountingDialog.setTabOrder(self.edtHistoryNote, self.chkHistoryOnlyCurrentService)
        AccountingDialog.setTabOrder(self.chkHistoryOnlyCurrentService, self.bbxHistory)
        AccountingDialog.setTabOrder(self.bbxHistory, self.edtTotalAccounts)
        AccountingDialog.setTabOrder(self.edtTotalAccounts, self.edtTotalExposed)
        AccountingDialog.setTabOrder(self.edtTotalExposed, self.edtTotalPayed)
        AccountingDialog.setTabOrder(self.edtTotalPayed, self.edtTotalRefused)
        AccountingDialog.setTabOrder(self.edtTotalRefused, self.tblAccounts)
        AccountingDialog.setTabOrder(self.tblAccounts, self.tabWidget_2)
        AccountingDialog.setTabOrder(self.tabWidget_2, self.tblAccountItems)
        AccountingDialog.setTabOrder(self.tblAccountItems, self.tblAccountContingent)
        AccountingDialog.setTabOrder(self.tblAccountContingent, self.edtAccountItemsExposed)
        AccountingDialog.setTabOrder(self.edtAccountItemsExposed, self.edtAccountItemsPayed)
        AccountingDialog.setTabOrder(self.edtAccountItemsPayed, self.edtAccountItemsRefused)
        AccountingDialog.setTabOrder(self.edtAccountItemsRefused, self.btnForm)
        AccountingDialog.setTabOrder(self.btnForm, self.btnPrint)
        AccountingDialog.setTabOrder(self.btnPrint, self.btnRefresh)
        AccountingDialog.setTabOrder(self.btnRefresh, self.btnExport)
        AccountingDialog.setTabOrder(self.btnExport, self.btnImport)
        AccountingDialog.setTabOrder(self.btnImport, self.btnClose)

    def retranslateUi(self, AccountingDialog):
        AccountingDialog.setWindowTitle(_translate("AccountingDialog", "Расчеты", None))
        self.tabWorkType.setTabText(self.tabWorkType.indexOf(self.tabCalc), _translate("AccountingDialog", "Расчет", None))
        self.groupBox_2.setTitle(_translate("AccountingDialog", "Реестр", None))
        self.lblAnalysisNote.setText(_translate("AccountingDialog", "примечание", None))
        self.lblAnalysisPayRefuseType.setText(_translate("AccountingDialog", "причина отказа", None))
        self.cmbAnalysisEventCodeType.setItemText(0, _translate("AccountingDialog", "Код карточки", None))
        self.cmbAnalysisEventCodeType.setItemText(1, _translate("AccountingDialog", "Номер документа", None))
        self.chkAnalysisEventCode.setText(_translate("AccountingDialog", "Код карточки", None))
        self.cmbAnalysisAccountItems.setItemText(0, _translate("AccountingDialog", "Все", None))
        self.cmbAnalysisAccountItems.setItemText(1, _translate("AccountingDialog", "Без подтверждения", None))
        self.cmbAnalysisAccountItems.setItemText(2, _translate("AccountingDialog", "Подтверждённые", None))
        self.cmbAnalysisAccountItems.setItemText(3, _translate("AccountingDialog", "Оплаченные", None))
        self.cmbAnalysisAccountItems.setItemText(4, _translate("AccountingDialog", "Отказанные", None))
        self.cmbAnalysisAccountItems.setItemText(5, _translate("AccountingDialog", "Перевыставляемые", None))
        self.cmbAnalysisAccountItems.setItemText(6, _translate("AccountingDialog", "Неперевыставляемые", None))
        self.chkAnalysisClientCode.setText(_translate("AccountingDialog", "Код пациента", None))
        self.lblAnalysisDocument.setText(_translate("AccountingDialog", "подтверждение", None))
        self.chkAnalysisService.setText(_translate("AccountingDialog", "Услуга", None))
        self.chkAnalysisCreateDate.setText(_translate("AccountingDialog", "Дата создания", None))
        self.lblAnalysisEndDate_2.setText(_translate("AccountingDialog", "По", None))
        self.chkAnalysisAccountId.setText(_translate("AccountingDialog", "Идентификатор", None))
        self.groupBox.setTitle(_translate("AccountingDialog", "Счета", None))
        self.lblAnalysisEndDate.setText(_translate("AccountingDialog", "По", None))
        self.lblAnalysisBegDate.setText(_translate("AccountingDialog", "C", None))
        self.lblAnalysisNumber.setText(_translate("AccountingDialog", "Номер", None))
        self.lblAnalysisPayer.setText(_translate("AccountingDialog", "Плательщик", None))
        self.lblAnalysisAccountType.setText(_translate("AccountingDialog", "Тип реестра счетов", None))
        self.lblGroupId.setText(_translate("AccountingDialog", "Единица МП", None))
        self.tabWorkType.setTabText(self.tabWorkType.indexOf(self.tabAnalysis), _translate("AccountingDialog", "Анализ", None))
        self.groupBox_4.setTitle(_translate("AccountingDialog", "Счета", None))
        self.lblHistoryBegDate.setText(_translate("AccountingDialog", "С", None))
        self.lblHistoryEndDate.setText(_translate("AccountingDialog", "По", None))
        self.lblHistoryNumber.setText(_translate("AccountingDialog", "Номер", None))
        self.lblHistoryPayer.setText(_translate("AccountingDialog", "Плательщик", None))
        self.btnHistorySelectPayer.setText(_translate("AccountingDialog", "...", None))
        self.groupBox_3.setTitle(_translate("AccountingDialog", "Реестр", None))
        self.cmbHistoryAccountItems.setItemText(0, _translate("AccountingDialog", "Все", None))
        self.cmbHistoryAccountItems.setItemText(1, _translate("AccountingDialog", "Без подтверждения", None))
        self.cmbHistoryAccountItems.setItemText(2, _translate("AccountingDialog", "Подтверждённые", None))
        self.cmbHistoryAccountItems.setItemText(3, _translate("AccountingDialog", "Оплаченные", None))
        self.cmbHistoryAccountItems.setItemText(4, _translate("AccountingDialog", "Отказанные", None))
        self.cmbHistoryAccountItems.setItemText(5, _translate("AccountingDialog", "Перевыставляемые", None))
        self.cmbHistoryAccountItems.setItemText(6, _translate("AccountingDialog", "Неперевыставляемые", None))
        self.lblHistoryAccountDocument.setText(_translate("AccountingDialog", "подтверждение", None))
        self.lblHistoryPayRefuseType.setText(_translate("AccountingDialog", "причина отказа", None))
        self.lblHistoryNote.setText(_translate("AccountingDialog", "примечание", None))
        self.chkHistoryOnlyCurrentService.setText(_translate("AccountingDialog", "Учитывать текущую услугу", None))
        self.tabWorkType.setTabText(self.tabWorkType.indexOf(self.tabHstory), _translate("AccountingDialog", "История", None))
        self.groupTotal.setTitle(_translate("AccountingDialog", "Итого", None))
        self.lblTotalAccounts.setText(_translate("AccountingDialog", "Счетов", None))
        self.lblTotalSum.setText(_translate("AccountingDialog", "Сумма", None))
        self.lblTotalExposed.setText(_translate("AccountingDialog", "Выставлено", None))
        self.lblTotalPayed.setText(_translate("AccountingDialog", "Оплата", None))
        self.lblTotalRejected.setText(_translate("AccountingDialog", "Отказ", None))
        self.lblFioFilter.setText(_translate("AccountingDialog", "Фильтр ФИО", None))
        self.btnApplyFilter.setText(_translate("AccountingDialog", "Применить", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("AccountingDialog", "Реестр", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("AccountingDialog", "Контингент", None))
        self.groupAccount.setTitle(_translate("AccountingDialog", "Итого по счету", None))
        self.lblAccountRejected.setText(_translate("AccountingDialog", "Отказ", None))
        self.lblAccountPayed.setText(_translate("AccountingDialog", "Оплата", None))
        self.lblAccountActionsCount.setText(_translate("AccountingDialog", "Услуг", None))
        self.lblAccountEventsCount.setText(_translate("AccountingDialog", "Обращений", None))
        self.lblAccountVisitsCount.setText(_translate("AccountingDialog", "Визитов", None))
        self.lblAccountClientsCount.setText(_translate("AccountingDialog", "Пациентов", None))
        self.lblAccountItemsCount.setText(_translate("AccountingDialog", "Позиций", None))
        self.lblAccountExposed.setText(_translate("AccountingDialog", "Выставлено", None))
        self.lblAccountSum.setText(_translate("AccountingDialog", "Сумма", None))
        self.btnForm.setText(_translate("AccountingDialog", "Формировать", None))
        self.btnPrint.setText(_translate("AccountingDialog", "Печать", None))
        self.btnRefresh.setText(_translate("AccountingDialog", "Обновить", None))
        self.btnExport.setText(_translate("AccountingDialog", "Экспорт", None))
        self.btnImport.setText(_translate("AccountingDialog", "Импорт", None))
        self.btnCheck.setText(_translate("AccountingDialog", "Проверка", None))
        self.btnClose.setText(_translate("AccountingDialog", "Закрыть", None))

from Orgs.OrgComboBox import COrgComboBox, COrgIsPayer23ComboBox
from library.crbcombobox import CRBComboBox
from library.CalendarWidget import CCalendarWidget
from Accounting.Utils import CAccountIdLineEdit, CContractTreeView
from library.DialogButtonBox import CApplyResetDialogButtonBox
from library.PrintTemplates import CPrintButton
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.TableView import CTableView
from library.DateEdit import CDateEdit
