# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client\F043\F043.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_F043Dialog(object):
    def setupUi(self, F043Dialog):
        F043Dialog.setObjectName(_fromUtf8("F043Dialog"))
        F043Dialog.resize(828, 846)
        self.gridLayout_2 = QtGui.QGridLayout(F043Dialog)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter_3 = QtGui.QSplitter(F043Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.txtClientInfoBrowser = CTextBrowser(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.scrollArea = QtGui.QScrollArea(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.tabWidget = QtGui.QTabWidget()
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 818, 693))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabToken = QtGui.QWidget()
        self.tabToken.setObjectName(_fromUtf8("tabToken"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabToken)
        self.gridLayout_9.setMargin(4)
        self.gridLayout_9.setSpacing(4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.splitter_2 = QtGui.QSplitter(self.tabToken)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.frame = QtGui.QFrame(self.splitter_2)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.grpBase = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpBase.sizePolicy().hasHeightForWidth())
        self.grpBase.setSizePolicy(sizePolicy)
        self.grpBase.setObjectName(_fromUtf8("grpBase"))
        self.gridLayout_4 = QtGui.QGridLayout(self.grpBase)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblBegDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout_4.addWidget(self.lblBegDate, 2, 0, 1, 1)
        self.lblResult = QtGui.QLabel(self.grpBase)
        self.lblResult.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblResult.setObjectName(_fromUtf8("lblResult"))
        self.gridLayout_4.addWidget(self.lblResult, 10, 0, 1, 3)
        self.lblNextDate = QtGui.QLabel(self.grpBase)
        self.lblNextDate.setObjectName(_fromUtf8("lblNextDate"))
        self.gridLayout_4.addWidget(self.lblNextDate, 4, 0, 1, 1)
        self.lblOrder = QtGui.QLabel(self.grpBase)
        self.lblOrder.setObjectName(_fromUtf8("lblOrder"))
        self.gridLayout_4.addWidget(self.lblOrder, 7, 2, 1, 1)
        self.cmbPrimary = CROComboBox(self.grpBase)
        self.cmbPrimary.setObjectName(_fromUtf8("cmbPrimary"))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbPrimary, 7, 0, 1, 2)
        self.frmEndDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmEndDateTime.setSizePolicy(sizePolicy)
        self.frmEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmEndDateTime.setLineWidth(0)
        self.frmEndDateTime.setObjectName(_fromUtf8("frmEndDateTime"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frmEndDateTime)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.edtEndDate = CDateEdit(self.frmEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout_4.addWidget(self.edtEndDate)
        self.edtEndTime = QtGui.QTimeEdit(self.frmEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndTime.sizePolicy().hasHeightForWidth())
        self.edtEndTime.setSizePolicy(sizePolicy)
        self.edtEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.horizontalLayout_4.addWidget(self.edtEndTime)
        self.gridLayout_4.addWidget(self.frmEndDateTime, 3, 1, 1, 2)
        self.lblContract = QtGui.QLabel(self.grpBase)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.gridLayout_4.addWidget(self.lblContract, 0, 0, 1, 3)
        self.cmbContract = CContractComboBox(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbContract.sizePolicy().hasHeightForWidth())
        self.cmbContract.setSizePolicy(sizePolicy)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.cmbContract.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbContract, 1, 0, 1, 3)
        self.cmbOrder = CROComboBox(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrder.sizePolicy().hasHeightForWidth())
        self.cmbOrder.setSizePolicy(sizePolicy)
        self.cmbOrder.setObjectName(_fromUtf8("cmbOrder"))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbOrder, 8, 0, 1, 3)
        self.edtPregnancyWeek = QtGui.QSpinBox(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPregnancyWeek.sizePolicy().hasHeightForWidth())
        self.edtPregnancyWeek.setSizePolicy(sizePolicy)
        self.edtPregnancyWeek.setMaximum(44)
        self.edtPregnancyWeek.setObjectName(_fromUtf8("edtPregnancyWeek"))
        self.gridLayout_4.addWidget(self.edtPregnancyWeek, 9, 2, 1, 1)
        self.frmBegDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmBegDateTime.sizePolicy().hasHeightForWidth())
        self.frmBegDateTime.setSizePolicy(sizePolicy)
        self.frmBegDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmBegDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmBegDateTime.setLineWidth(0)
        self.frmBegDateTime.setObjectName(_fromUtf8("frmBegDateTime"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frmBegDateTime)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtBegDate = CDateEdit(self.frmBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout_3.addWidget(self.edtBegDate)
        self.edtBegTime = QtGui.QTimeEdit(self.frmBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegTime.sizePolicy().hasHeightForWidth())
        self.edtBegTime.setSizePolicy(sizePolicy)
        self.edtBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.horizontalLayout_3.addWidget(self.edtBegTime)
        self.gridLayout_4.addWidget(self.frmBegDateTime, 2, 1, 1, 2)
        self.cmbResult = CRBComboBox(self.grpBase)
        self.cmbResult.setObjectName(_fromUtf8("cmbResult"))
        self.cmbResult.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbResult, 11, 0, 1, 3)
        self.edtNextDate = CDateEdit(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtNextDate.sizePolicy().hasHeightForWidth())
        self.edtNextDate.setSizePolicy(sizePolicy)
        self.edtNextDate.setObjectName(_fromUtf8("edtNextDate"))
        self.gridLayout_4.addWidget(self.edtNextDate, 4, 1, 1, 1)
        self.lblPregnancyWeek = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPregnancyWeek.sizePolicy().hasHeightForWidth())
        self.lblPregnancyWeek.setSizePolicy(sizePolicy)
        self.lblPregnancyWeek.setObjectName(_fromUtf8("lblPregnancyWeek"))
        self.gridLayout_4.addWidget(self.lblPregnancyWeek, 9, 0, 1, 2)
        self.lblPerson = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPerson.sizePolicy().hasHeightForWidth())
        self.lblPerson.setSizePolicy(sizePolicy)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout_4.addWidget(self.lblPerson, 5, 0, 1, 3)
        self.lblEndDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDate.sizePolicy().hasHeightForWidth())
        self.lblEndDate.setSizePolicy(sizePolicy)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout_4.addWidget(self.lblEndDate, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(16, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 12, 0, 1, 3)
        self.cmbPerson = CPersonComboBoxEx(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPerson.sizePolicy().hasHeightForWidth())
        self.cmbPerson.setSizePolicy(sizePolicy)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbPerson, 6, 0, 1, 3)
        self.lblCommonUET = QtGui.QLabel(self.grpBase)
        self.lblCommonUET.setObjectName(_fromUtf8("lblCommonUET"))
        self.gridLayout_4.addWidget(self.lblCommonUET, 13, 0, 1, 2)
        self.edtCommonUet = QtGui.QDoubleSpinBox(self.grpBase)
        self.edtCommonUet.setReadOnly(True)
        self.edtCommonUet.setMaximum(999.99)
        self.edtCommonUet.setObjectName(_fromUtf8("edtCommonUet"))
        self.gridLayout_4.addWidget(self.edtCommonUet, 13, 2, 1, 1)
        self.horizontalLayout.addWidget(self.grpBase)
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 4, 1, 1)
        self.tblVisits = CDentitionInDocTableView(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblVisits.sizePolicy().hasHeightForWidth())
        self.tblVisits.setSizePolicy(sizePolicy)
        self.tblVisits.setObjectName(_fromUtf8("tblVisits"))
        self.gridLayout_3.addWidget(self.tblVisits, 0, 0, 1, 5)
        self.lblVisitsCount = QtGui.QLabel(self.groupBox)
        self.lblVisitsCount.setObjectName(_fromUtf8("lblVisitsCount"))
        self.gridLayout_3.addWidget(self.lblVisitsCount, 1, 0, 1, 1)
        self.lblVisitsCountValue = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblVisitsCountValue.sizePolicy().hasHeightForWidth())
        self.lblVisitsCountValue.setSizePolicy(sizePolicy)
        self.lblVisitsCountValue.setMinimumSize(QtCore.QSize(40, 0))
        self.lblVisitsCountValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblVisitsCountValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblVisitsCountValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblVisitsCountValue.setObjectName(_fromUtf8("lblVisitsCountValue"))
        self.gridLayout_3.addWidget(self.lblVisitsCountValue, 1, 1, 1, 1)
        self.lblVisitsDuration = QtGui.QLabel(self.groupBox)
        self.lblVisitsDuration.setObjectName(_fromUtf8("lblVisitsDuration"))
        self.gridLayout_3.addWidget(self.lblVisitsDuration, 1, 2, 1, 1)
        self.lblVisitsDurationValue = QtGui.QLabel(self.groupBox)
        self.lblVisitsDurationValue.setMinimumSize(QtCore.QSize(40, 0))
        self.lblVisitsDurationValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblVisitsDurationValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblVisitsDurationValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblVisitsDurationValue.setObjectName(_fromUtf8("lblVisitsDurationValue"))
        self.gridLayout_3.addWidget(self.lblVisitsDurationValue, 1, 3, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.grpInspections = QtGui.QGroupBox(self.splitter_2)
        self.grpInspections.setObjectName(_fromUtf8("grpInspections"))
        self.gridLayout_5 = QtGui.QGridLayout(self.grpInspections)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblDiagnostics = CInDocTableView(self.grpInspections)
        self.tblDiagnostics.setObjectName(_fromUtf8("tblDiagnostics"))
        self.gridLayout_5.addWidget(self.tblDiagnostics, 0, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.dentitionTabWidget = QtGui.QTabWidget(self.splitter)
        self.dentitionTabWidget.setObjectName(_fromUtf8("dentitionTabWidget"))
        self.tabDentitionInspection = QtGui.QWidget()
        self.tabDentitionInspection.setObjectName(_fromUtf8("tabDentitionInspection"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabDentitionInspection)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tblDentition = CDentitionTableView(self.tabDentitionInspection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tblDentition.sizePolicy().hasHeightForWidth())
        self.tblDentition.setSizePolicy(sizePolicy)
        self.tblDentition.setObjectName(_fromUtf8("tblDentition"))
        self.gridLayout_7.addWidget(self.tblDentition, 0, 0, 1, 1)
        self.dentitionTabWidget.addTab(self.tabDentitionInspection, _fromUtf8(""))
        self.tabDentitionAdditional = QtGui.QWidget()
        self.tabDentitionAdditional.setObjectName(_fromUtf8("tabDentitionAdditional"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tabDentitionAdditional)
        self.gridLayout_10.setMargin(4)
        self.gridLayout_10.setSpacing(4)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.cmbDentitionProtezes = CStrComboBox(self.tabDentitionAdditional)
        self.cmbDentitionProtezes.setObjectName(_fromUtf8("cmbDentitionProtezes"))
        self.gridLayout_10.addWidget(self.cmbDentitionProtezes, 4, 3, 1, 2)
        self.lblDentitionMucosa = QtGui.QLabel(self.tabDentitionAdditional)
        self.lblDentitionMucosa.setObjectName(_fromUtf8("lblDentitionMucosa"))
        self.gridLayout_10.addWidget(self.lblDentitionMucosa, 0, 3, 1, 1)
        self.lblDentitionNote = QtGui.QLabel(self.tabDentitionAdditional)
        self.lblDentitionNote.setObjectName(_fromUtf8("lblDentitionNote"))
        self.gridLayout_10.addWidget(self.lblDentitionNote, 0, 4, 1, 1)
        self.edtDentitionObjectively = CThesaurusEditor(self.tabDentitionAdditional)
        self.edtDentitionObjectively.setObjectName(_fromUtf8("edtDentitionObjectively"))
        self.gridLayout_10.addWidget(self.edtDentitionObjectively, 1, 1, 1, 2)
        self.edtDentitionMucosa = CThesaurusEditor(self.tabDentitionAdditional)
        self.edtDentitionMucosa.setObjectName(_fromUtf8("edtDentitionMucosa"))
        self.gridLayout_10.addWidget(self.edtDentitionMucosa, 1, 3, 1, 1)
        self.edtDentitionNote = QtGui.QTextEdit(self.tabDentitionAdditional)
        self.edtDentitionNote.setObjectName(_fromUtf8("edtDentitionNote"))
        self.gridLayout_10.addWidget(self.edtDentitionNote, 1, 4, 1, 1)
        self.lblDentitionBite = QtGui.QLabel(self.tabDentitionAdditional)
        self.lblDentitionBite.setObjectName(_fromUtf8("lblDentitionBite"))
        self.gridLayout_10.addWidget(self.lblDentitionBite, 2, 1, 1, 2)
        self.cmbDentitionBite = CStrComboBox(self.tabDentitionAdditional)
        self.cmbDentitionBite.setObjectName(_fromUtf8("cmbDentitionBite"))
        self.gridLayout_10.addWidget(self.cmbDentitionBite, 2, 3, 1, 2)
        self.lblDentitionObjectively = QtGui.QLabel(self.tabDentitionAdditional)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDentitionObjectively.sizePolicy().hasHeightForWidth())
        self.lblDentitionObjectively.setSizePolicy(sizePolicy)
        self.lblDentitionObjectively.setObjectName(_fromUtf8("lblDentitionObjectively"))
        self.gridLayout_10.addWidget(self.lblDentitionObjectively, 0, 1, 1, 2)
        self.lblDentitionSanitation = QtGui.QLabel(self.tabDentitionAdditional)
        self.lblDentitionSanitation.setObjectName(_fromUtf8("lblDentitionSanitation"))
        self.gridLayout_10.addWidget(self.lblDentitionSanitation, 6, 1, 1, 2)
        self.cmbDentitionSanitation = CStrComboBox(self.tabDentitionAdditional)
        self.cmbDentitionSanitation.setObjectName(_fromUtf8("cmbDentitionSanitation"))
        self.gridLayout_10.addWidget(self.cmbDentitionSanitation, 6, 3, 1, 2)
        self.cmbDentitionApparat = CStrComboBox(self.tabDentitionAdditional)
        self.cmbDentitionApparat.setObjectName(_fromUtf8("cmbDentitionApparat"))
        self.gridLayout_10.addWidget(self.cmbDentitionApparat, 3, 3, 1, 2)
        self.lblDentitionApparat = QtGui.QLabel(self.tabDentitionAdditional)
        self.lblDentitionApparat.setObjectName(_fromUtf8("lblDentitionApparat"))
        self.gridLayout_10.addWidget(self.lblDentitionApparat, 3, 1, 1, 2)
        self.lblDentitionProtezes = QtGui.QLabel(self.tabDentitionAdditional)
        self.lblDentitionProtezes.setObjectName(_fromUtf8("lblDentitionProtezes"))
        self.gridLayout_10.addWidget(self.lblDentitionProtezes, 4, 1, 1, 2)
        self.lblDentitionOrtodontCure = QtGui.QLabel(self.tabDentitionAdditional)
        self.lblDentitionOrtodontCure.setObjectName(_fromUtf8("lblDentitionOrtodontCure"))
        self.gridLayout_10.addWidget(self.lblDentitionOrtodontCure, 5, 1, 1, 2)
        self.cmbDentitionOrtodontCure = CStrComboBox(self.tabDentitionAdditional)
        self.cmbDentitionOrtodontCure.setObjectName(_fromUtf8("cmbDentitionOrtodontCure"))
        self.gridLayout_10.addWidget(self.cmbDentitionOrtodontCure, 5, 3, 1, 2)
        self.dentitionTabWidget.addTab(self.tabDentitionAdditional, _fromUtf8(""))
        self.tabDentitionResult = QtGui.QWidget()
        self.tabDentitionResult.setObjectName(_fromUtf8("tabDentitionResult"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tabDentitionResult)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.tblParodentium = CParodentiumTableView(self.tabDentitionResult)
        self.tblParodentium.setObjectName(_fromUtf8("tblParodentium"))
        self.gridLayout_11.addWidget(self.tblParodentium, 0, 0, 1, 1)
        self.dentitionTabWidget.addTab(self.tabDentitionResult, _fromUtf8(""))
        self.tabActions = QtGui.QWidget()
        self.tabActions.setObjectName(_fromUtf8("tabActions"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabActions)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tblActions = CInDocTableView(self.tabActions)
        self.tblActions.setObjectName(_fromUtf8("tblActions"))
        self.gridLayout_6.addWidget(self.tblActions, 0, 0, 1, 1)
        self.dentitionTabWidget.addTab(self.tabActions, _fromUtf8(""))
        self.grpDentitionHistory = QtGui.QGroupBox(self.splitter)
        self.grpDentitionHistory.setObjectName(_fromUtf8("grpDentitionHistory"))
        self.gridLayout_8 = QtGui.QGridLayout(self.grpDentitionHistory)
        self.gridLayout_8.setContentsMargins(0, 4, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tblClientDentitionHistory = CClientDentitionHistoryTableView(self.grpDentitionHistory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblClientDentitionHistory.sizePolicy().hasHeightForWidth())
        self.tblClientDentitionHistory.setSizePolicy(sizePolicy)
        self.tblClientDentitionHistory.setObjectName(_fromUtf8("tblClientDentitionHistory"))
        self.gridLayout_8.addWidget(self.tblClientDentitionHistory, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabToken, _fromUtf8(""))
        self.tabMedicalDiagnosis = CEventMedicalDiagnosisPage()
        self.tabMedicalDiagnosis.setObjectName(_fromUtf8("tabMedicalDiagnosis"))
        self.tabWidget.addTab(self.tabMedicalDiagnosis, _fromUtf8(""))
        self.tabMes = CEventMesPage()
        self.tabMes.setObjectName(_fromUtf8("tabMes"))
        self.tabWidget.addTab(self.tabMes, _fromUtf8(""))
        self.tabStatus = CActionsPage()
        self.tabStatus.setObjectName(_fromUtf8("tabStatus"))
        self.tabWidget.addTab(self.tabStatus, _fromUtf8(""))
        self.tabDiagnostic = CActionsPage()
        self.tabDiagnostic.setObjectName(_fromUtf8("tabDiagnostic"))
        self.tabWidget.addTab(self.tabDiagnostic, _fromUtf8(""))
        self.tabCure = CActionsPage()
        self.tabCure.setObjectName(_fromUtf8("tabCure"))
        self.tabWidget.addTab(self.tabCure, _fromUtf8(""))
        self.tabMisc = CActionsPage()
        self.tabMisc.setObjectName(_fromUtf8("tabMisc"))
        self.tabWidget.addTab(self.tabMisc, _fromUtf8(""))
        self.tabAmbCard = CAmbCardPage()
        self.tabAmbCard.setObjectName(_fromUtf8("tabAmbCard"))
        self.tabWidget.addTab(self.tabAmbCard, _fromUtf8(""))
        self.tabTempInvalidEtc = QtGui.QWidget()
        self.tabTempInvalidEtc.setObjectName(_fromUtf8("tabTempInvalidEtc"))
        self.gridLayout = QtGui.QGridLayout(self.tabTempInvalidEtc)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabTempInvalidAndAegrotat = QtGui.QTabWidget(self.tabTempInvalidEtc)
        self.tabTempInvalidAndAegrotat.setObjectName(_fromUtf8("tabTempInvalidAndAegrotat"))
        self.tabTempInvalid = QtGui.QWidget()
        self.tabTempInvalid.setObjectName(_fromUtf8("tabTempInvalid"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabTempInvalid)
        self.verticalLayout_5.setMargin(4)
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.grpTempInvalid = CTempInvalid(self.tabTempInvalid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpTempInvalid.sizePolicy().hasHeightForWidth())
        self.grpTempInvalid.setSizePolicy(sizePolicy)
        self.grpTempInvalid.setChecked(False)
        self.grpTempInvalid.setObjectName(_fromUtf8("grpTempInvalid"))
        self.verticalLayout_5.addWidget(self.grpTempInvalid)
        self.tabTempInvalidAndAegrotat.addTab(self.tabTempInvalid, _fromUtf8(""))
        self.tabAegrotat = QtGui.QWidget()
        self.tabAegrotat.setObjectName(_fromUtf8("tabAegrotat"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabAegrotat)
        self.verticalLayout_4.setMargin(4)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.grpAegrotat = CTempInvalid(self.tabAegrotat)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpAegrotat.sizePolicy().hasHeightForWidth())
        self.grpAegrotat.setSizePolicy(sizePolicy)
        self.grpAegrotat.setChecked(False)
        self.grpAegrotat.setObjectName(_fromUtf8("grpAegrotat"))
        self.verticalLayout_4.addWidget(self.grpAegrotat)
        self.tabTempInvalidAndAegrotat.addTab(self.tabAegrotat, _fromUtf8(""))
        self.tabDisability = QtGui.QWidget()
        self.tabDisability.setObjectName(_fromUtf8("tabDisability"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabDisability)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.grpDisability = CTempInvalid(self.tabDisability)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpDisability.sizePolicy().hasHeightForWidth())
        self.grpDisability.setSizePolicy(sizePolicy)
        self.grpDisability.setChecked(False)
        self.grpDisability.setObjectName(_fromUtf8("grpDisability"))
        self.verticalLayout_2.addWidget(self.grpDisability)
        self.tabTempInvalidAndAegrotat.addTab(self.tabDisability, _fromUtf8(""))
        self.tabVitalRestriction = QtGui.QWidget()
        self.tabVitalRestriction.setObjectName(_fromUtf8("tabVitalRestriction"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabVitalRestriction)
        self.verticalLayout_6.setMargin(4)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.grpVitalRestriction = CTempInvalid(self.tabVitalRestriction)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpVitalRestriction.sizePolicy().hasHeightForWidth())
        self.grpVitalRestriction.setSizePolicy(sizePolicy)
        self.grpVitalRestriction.setChecked(False)
        self.grpVitalRestriction.setObjectName(_fromUtf8("grpVitalRestriction"))
        self.verticalLayout_6.addWidget(self.grpVitalRestriction)
        self.tabTempInvalidAndAegrotat.addTab(self.tabVitalRestriction, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabTempInvalidAndAegrotat, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabTempInvalidEtc, _fromUtf8(""))
        self.tabCash = CEventCashPage()
        self.tabCash.setObjectName(_fromUtf8("tabCash"))
        self.tabWidget.addTab(self.tabCash, _fromUtf8(""))
        self.tabExport = QtGui.QWidget()
        self.tabExport.setObjectName(_fromUtf8("tabExport"))
        self.gridLayout_55 = QtGui.QGridLayout(self.tabExport)
        self.gridLayout_55.setMargin(1)
        self.gridLayout_55.setSpacing(1)
        self.gridLayout_55.setObjectName(_fromUtf8("gridLayout_55"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tabExport)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tblExport = CInDocTableView(self.tab_3)
        self.tblExport.setObjectName(_fromUtf8("tblExport"))
        self.horizontalLayout_9.addWidget(self.tblExport)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.tblExport_FileAttach = CInDocExportTableView(self.tab)
        self.tblExport_FileAttach.setObjectName(_fromUtf8("tblExport_FileAttach"))
        self.horizontalLayout_8.addWidget(self.tblExport_FileAttach)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tblExport_VIMIS = CInDocExportTableView(self.tab_2)
        self.tblExport_VIMIS.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tblExport_VIMIS.setSizeIncrement(QtCore.QSize(0, -1))
        self.tblExport_VIMIS.setBaseSize(QtCore.QSize(0, -1))
        self.tblExport_VIMIS.setObjectName(_fromUtf8("tblExport_VIMIS"))
        self.horizontalLayout_7.addWidget(self.tblExport_VIMIS)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_55.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabExport, _fromUtf8(""))
        self.tabNotes = CEventNotesPage()
        self.tabNotes.setObjectName(_fromUtf8("tabNotes"))
        self.tabWidget.addTab(self.tabNotes, _fromUtf8(""))
        self.scrollArea.setWidget(self.tabWidget)
        self.gridLayout_2.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(F043Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.statusBar = QtGui.QStatusBar(F043Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.horizontalLayout_2.addWidget(self.statusBar)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.lblProlongateEvent = QtGui.QLabel(F043Dialog)
        self.lblProlongateEvent.setText(_fromUtf8(""))
        self.lblProlongateEvent.setObjectName(_fromUtf8("lblProlongateEvent"))
        self.horizontalLayout_2.addWidget(self.lblProlongateEvent)
        self.lblValueExternalId = QtGui.QLabel(F043Dialog)
        self.lblValueExternalId.setText(_fromUtf8(""))
        self.lblValueExternalId.setObjectName(_fromUtf8("lblValueExternalId"))
        self.horizontalLayout_2.addWidget(self.lblValueExternalId)
        self.lblValueMesCode = QtGui.QLabel(F043Dialog)
        self.lblValueMesCode.setText(_fromUtf8(""))
        self.lblValueMesCode.setObjectName(_fromUtf8("lblValueMesCode"))
        self.horizontalLayout_2.addWidget(self.lblValueMesCode)
        self.horizontalLayout_2.setStretch(0, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblResult.setBuddy(self.cmbResult)
        self.lblPregnancyWeek.setBuddy(self.edtPregnancyWeek)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblEndDate.setBuddy(self.edtEndDate)

        self.retranslateUi(F043Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.dentitionTabWidget.setCurrentIndex(0)
        self.tabTempInvalidAndAegrotat.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), F043Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), F043Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(F043Dialog)
        F043Dialog.setTabOrder(self.txtClientInfoBrowser, self.tabWidget)
        F043Dialog.setTabOrder(self.tabWidget, self.buttonBox)
        F043Dialog.setTabOrder(self.buttonBox, self.cmbContract)
        F043Dialog.setTabOrder(self.cmbContract, self.edtBegDate)
        F043Dialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        F043Dialog.setTabOrder(self.edtBegTime, self.edtEndDate)
        F043Dialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        F043Dialog.setTabOrder(self.edtEndTime, self.cmbPerson)
        F043Dialog.setTabOrder(self.cmbPerson, self.cmbOrder)
        F043Dialog.setTabOrder(self.cmbOrder, self.edtPregnancyWeek)
        F043Dialog.setTabOrder(self.edtPregnancyWeek, self.cmbResult)
        F043Dialog.setTabOrder(self.cmbResult, self.edtCommonUet)
        F043Dialog.setTabOrder(self.edtCommonUet, self.edtNextDate)
        F043Dialog.setTabOrder(self.edtNextDate, self.cmbPrimary)
        F043Dialog.setTabOrder(self.cmbPrimary, self.tblVisits)
        F043Dialog.setTabOrder(self.tblVisits, self.tblDiagnostics)
        F043Dialog.setTabOrder(self.tblDiagnostics, self.dentitionTabWidget)
        F043Dialog.setTabOrder(self.dentitionTabWidget, self.tblDentition)
        F043Dialog.setTabOrder(self.tblDentition, self.edtDentitionObjectively)
        F043Dialog.setTabOrder(self.edtDentitionObjectively, self.edtDentitionMucosa)
        F043Dialog.setTabOrder(self.edtDentitionMucosa, self.edtDentitionNote)
        F043Dialog.setTabOrder(self.edtDentitionNote, self.cmbDentitionBite)
        F043Dialog.setTabOrder(self.cmbDentitionBite, self.cmbDentitionApparat)
        F043Dialog.setTabOrder(self.cmbDentitionApparat, self.cmbDentitionProtezes)
        F043Dialog.setTabOrder(self.cmbDentitionProtezes, self.cmbDentitionOrtodontCure)
        F043Dialog.setTabOrder(self.cmbDentitionOrtodontCure, self.cmbDentitionSanitation)
        F043Dialog.setTabOrder(self.cmbDentitionSanitation, self.tblParodentium)
        F043Dialog.setTabOrder(self.tblParodentium, self.tblClientDentitionHistory)
        F043Dialog.setTabOrder(self.tblClientDentitionHistory, self.tabTempInvalidAndAegrotat)
        F043Dialog.setTabOrder(self.tabTempInvalidAndAegrotat, self.grpTempInvalid)
        F043Dialog.setTabOrder(self.grpTempInvalid, self.grpAegrotat)
        F043Dialog.setTabOrder(self.grpAegrotat, self.grpDisability)
        F043Dialog.setTabOrder(self.grpDisability, self.grpVitalRestriction)

    def retranslateUi(self, F043Dialog):
        F043Dialog.setWindowTitle(_translate("F043Dialog", "Dialog", None))
        self.grpBase.setTitle(_translate("F043Dialog", "&ф.043", None))
        self.lblBegDate.setText(_translate("F043Dialog", "Назначено", None))
        self.lblResult.setText(_translate("F043Dialog", "Результа&т", None))
        self.lblNextDate.setText(_translate("F043Dialog", "След.явка", None))
        self.lblOrder.setText(_translate("F043Dialog", "Порядок", None))
        self.cmbPrimary.setItemText(0, _translate("F043Dialog", "Первичный", None))
        self.cmbPrimary.setItemText(1, _translate("F043Dialog", "Повторный", None))
        self.cmbPrimary.setItemText(2, _translate("F043Dialog", "Актив", None))
        self.edtEndDate.setWhatsThis(_translate("F043Dialog", "дата окончания осмотра", None))
        self.edtEndTime.setDisplayFormat(_translate("F043Dialog", "HH:mm", None))
        self.lblContract.setText(_translate("F043Dialog", "Договор:", None))
        self.cmbContract.setWhatsThis(_translate("F043Dialog", "номер, дата и основание договора в рамках которого производится осмотр", None))
        self.cmbContract.setItemText(0, _translate("F043Dialog", "Договор", None))
        self.cmbOrder.setItemText(0, _translate("F043Dialog", "Плановый", None))
        self.cmbOrder.setItemText(1, _translate("F043Dialog", "Экстренный", None))
        self.cmbOrder.setItemText(2, _translate("F043Dialog", "Самотёком", None))
        self.cmbOrder.setItemText(3, _translate("F043Dialog", "Принудительный", None))
        self.cmbOrder.setItemText(4, _translate("F043Dialog", "Внутренний перевод", None))
        self.cmbOrder.setItemText(5, _translate("F043Dialog", "Неотложная", None))
        self.edtBegDate.setWhatsThis(_translate("F043Dialog", "дата начала осмотра", None))
        self.edtBegTime.setDisplayFormat(_translate("F043Dialog", "HH:mm", None))
        self.cmbResult.setWhatsThis(_translate("F043Dialog", "результат осмотра", None))
        self.cmbResult.setItemText(0, _translate("F043Dialog", "Результат", None))
        self.lblPregnancyWeek.setText(_translate("F043Dialog", "Неделя беременности", None))
        self.lblPerson.setText(_translate("F043Dialog", "Ответственный", None))
        self.lblEndDate.setText(_translate("F043Dialog", "Выполнено", None))
        self.cmbPerson.setWhatsThis(_translate("F043Dialog", "врач отвечающий за осмотр (терапевт)", None))
        self.cmbPerson.setItemText(0, _translate("F043Dialog", "Врач", None))
        self.lblCommonUET.setText(_translate("F043Dialog", "Общее кол-во УЕТ", None))
        self.groupBox.setTitle(_translate("F043Dialog", "&Посещения", None))
        self.lblVisitsCount.setText(_translate("F043Dialog", "Всего посещений:", None))
        self.lblVisitsCountValue.setText(_translate("F043Dialog", "0", None))
        self.lblVisitsDuration.setText(_translate("F043Dialog", "Общая длительность:", None))
        self.lblVisitsDurationValue.setText(_translate("F043Dialog", "0", None))
        self.grpInspections.setTitle(_translate("F043Dialog", "&Диагнозы", None))
        self.dentitionTabWidget.setTabText(self.dentitionTabWidget.indexOf(self.tabDentitionInspection), _translate("F043Dialog", "Стоматологическая зубная формула", None))
        self.lblDentitionMucosa.setText(_translate("F043Dialog", "Слизистая", None))
        self.lblDentitionNote.setText(_translate("F043Dialog", "Примечание", None))
        self.lblDentitionBite.setText(_translate("F043Dialog", "Прикус", None))
        self.lblDentitionObjectively.setText(_translate("F043Dialog", "Объективно", None))
        self.lblDentitionSanitation.setText(_translate("F043Dialog", "Санация", None))
        self.lblDentitionApparat.setText(_translate("F043Dialog", "Аппарат", None))
        self.lblDentitionProtezes.setText(_translate("F043Dialog", "Протезы", None))
        self.lblDentitionOrtodontCure.setText(_translate("F043Dialog", "Ортодонтическое лечение", None))
        self.dentitionTabWidget.setTabText(self.dentitionTabWidget.indexOf(self.tabDentitionAdditional), _translate("F043Dialog", "Дополнительно", None))
        self.dentitionTabWidget.setTabText(self.dentitionTabWidget.indexOf(self.tabDentitionResult), _translate("F043Dialog", "Пародонтологическая зубная формула", None))
        self.dentitionTabWidget.setTabText(self.dentitionTabWidget.indexOf(self.tabActions), _translate("F043Dialog", "Мероприятия", None))
        self.grpDentitionHistory.setTitle(_translate("F043Dialog", "История", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabToken), _translate("F043Dialog", "Стат.&талон", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMedicalDiagnosis), _translate("F043Dialog", "Диагно&з", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMes), _translate("F043Dialog", "Ст&андарт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatus), _translate("F043Dialog", "&Статус", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiagnostic), _translate("F043Dialog", "&Диагностика", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCure), _translate("F043Dialog", "&Лечение", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMisc), _translate("F043Dialog", "&Мероприятия", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAmbCard), _translate("F043Dialog", "Мед.&карта", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabTempInvalid), _translate("F043Dialog", "Листок &нетрудоспособности", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabAegrotat), _translate("F043Dialog", "С&правка", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabDisability), _translate("F043Dialog", "Инвалидность", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabVitalRestriction), _translate("F043Dialog", "О&граничения жизнедеятельности", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTempInvalidEtc), _translate("F043Dialog", "Т&рудоспособность", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCash), _translate("F043Dialog", "&Оплата", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("F043Dialog", "Событие", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("F043Dialog", "Документы", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("F043Dialog", "ВИМИС", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExport), _translate("F043Dialog", "&Экспорт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNotes), _translate("F043Dialog", "Приме&чания", None))
        self.statusBar.setToolTip(_translate("F043Dialog", "A status bar", None))
        self.statusBar.setWhatsThis(_translate("F043Dialog", "A status bar.", None))

from Events.ActionsPage import CActionsPage
from Events.AmbCardPage import CAmbCardPage
from Events.EventCashPage import CEventCashPage
from Events.EventMedicalDiagnosisPage import CEventMedicalDiagnosisPage
from Events.EventMesPage import CEventMesPage
from Events.EventNotesPage import CEventNotesPage
from Events.TempInvalid import CTempInvalid
from F043.DentitionTable import CClientDentitionHistoryTableView, CDentitionTableView, CParodentiumTableView
from Orgs.OrgComboBox import CContractComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.InDocTable import CDentitionInDocTableView, CInDocExportTableView, CInDocTableView
from library.ROComboBox import CROComboBox
from library.StrComboBox import CStrComboBox
from library.TextBrowser import CTextBrowser
from library.ThesaurusEdit import CThesaurusEditor
from library.crbcombobox import CRBComboBox
