# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Attach_SEMD_IEMK.ui'
#
# Created: Mon Feb 24 15:09:50 2025
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Attach_SEMD_IEMK_Dialog(object):
    def setupUi(self, Attach_SEMD_IEMK_Dialog):
        Attach_SEMD_IEMK_Dialog.setObjectName(_fromUtf8("Attach_SEMD_IEMK_Dialog"))
        Attach_SEMD_IEMK_Dialog.resize(1167, 945)
        self.gridLayout_3 = QtGui.QGridLayout(Attach_SEMD_IEMK_Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBoxFilters = QtGui.QGroupBox(Attach_SEMD_IEMK_Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxFilters.sizePolicy().hasHeightForWidth())
        self.groupBoxFilters.setSizePolicy(sizePolicy)
        self.groupBoxFilters.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBoxFilters.setObjectName(_fromUtf8("groupBoxFilters"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxFilters)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.groupBoxFilters)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 338, 875))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chkFilterLastName = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterLastName.setObjectName(_fromUtf8("chkFilterLastName"))
        self.verticalLayout.addWidget(self.chkFilterLastName)
        self.edtFilterLastName = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtFilterLastName.setObjectName(_fromUtf8("edtFilterLastName"))
        self.verticalLayout.addWidget(self.edtFilterLastName)
        self.chkFilterFirstName = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterFirstName.setObjectName(_fromUtf8("chkFilterFirstName"))
        self.verticalLayout.addWidget(self.chkFilterFirstName)
        self.edtFilterFirstName = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtFilterFirstName.setObjectName(_fromUtf8("edtFilterFirstName"))
        self.verticalLayout.addWidget(self.edtFilterFirstName)
        self.chkFilterPatrName = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterPatrName.setObjectName(_fromUtf8("chkFilterPatrName"))
        self.verticalLayout.addWidget(self.chkFilterPatrName)
        self.edtFilterPatrName = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtFilterPatrName.setObjectName(_fromUtf8("edtFilterPatrName"))
        self.verticalLayout.addWidget(self.edtFilterPatrName)
        self.chkFilterEventId = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterEventId.setObjectName(_fromUtf8("chkFilterEventId"))
        self.verticalLayout.addWidget(self.chkFilterEventId)
        self.edtFilterEventId = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtFilterEventId.setObjectName(_fromUtf8("edtFilterEventId"))
        self.verticalLayout.addWidget(self.edtFilterEventId)
        self.lblFilterSigned = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFilterSigned.setObjectName(_fromUtf8("lblFilterSigned"))
        self.verticalLayout.addWidget(self.lblFilterSigned)
        self.cmbFilterSigned = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbFilterSigned.setObjectName(_fromUtf8("cmbFilterSigned"))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.cmbFilterSigned.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.cmbFilterSigned)
        self.lblFilterPerson = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFilterPerson.setObjectName(_fromUtf8("lblFilterPerson"))
        self.verticalLayout.addWidget(self.lblFilterPerson)
        self.cmbFilterPerson = CPersonComboBoxEx(self.scrollAreaWidgetContents)
        self.cmbFilterPerson.setEnabled(True)
        self.cmbFilterPerson.setObjectName(_fromUtf8("cmbFilterPerson"))
        self.verticalLayout.addWidget(self.cmbFilterPerson)
        self.chkFilterSNILS = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterSNILS.setEnabled(False)
        self.chkFilterSNILS.setObjectName(_fromUtf8("chkFilterSNILS"))
        self.verticalLayout.addWidget(self.chkFilterSNILS)
        self.lblSpeciality = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.verticalLayout.addWidget(self.lblSpeciality)
        self.cmbSpeciality = CRBMultivalueComboBox(self.scrollAreaWidgetContents)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.verticalLayout.addWidget(self.cmbSpeciality)
        self.chkFilterOrgStructure = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterOrgStructure.setObjectName(_fromUtf8("chkFilterOrgStructure"))
        self.verticalLayout.addWidget(self.chkFilterOrgStructure)
        self.cmbFilterOrgStructure = COrgStructureComboBox(self.scrollAreaWidgetContents)
        self.cmbFilterOrgStructure.setObjectName(_fromUtf8("cmbFilterOrgStructure"))
        self.verticalLayout.addWidget(self.cmbFilterOrgStructure)
        self.chkFilterActionType = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterActionType.setObjectName(_fromUtf8("chkFilterActionType"))
        self.verticalLayout.addWidget(self.chkFilterActionType)
        self.cmbActionType = CActionTypeComboBoxEx(self.scrollAreaWidgetContents)
        self.cmbActionType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbActionType.sizePolicy().hasHeightForWidth())
        self.cmbActionType.setSizePolicy(sizePolicy)
        self.cmbActionType.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbActionType.setObjectName(_fromUtf8("cmbActionType"))
        self.verticalLayout.addWidget(self.cmbActionType)
        self.chkFilterEventType = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterEventType.setObjectName(_fromUtf8("chkFilterEventType"))
        self.verticalLayout.addWidget(self.chkFilterEventType)
        self.cmbEventType = CRBMultivalueComboBox(self.scrollAreaWidgetContents)
        self.cmbEventType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEventType.sizePolicy().hasHeightForWidth())
        self.cmbEventType.setSizePolicy(sizePolicy)
        self.cmbEventType.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.verticalLayout.addWidget(self.cmbEventType)
        self.lblFinance = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.verticalLayout.addWidget(self.lblFinance)
        self.cmbFinance = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.verticalLayout.addWidget(self.cmbFinance)
        self.lblFilterEventEndDate_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFilterEventEndDate_2.setObjectName(_fromUtf8("lblFilterEventEndDate_2"))
        self.verticalLayout.addWidget(self.lblFilterEventEndDate_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.chkFilterDateExecActionBegDate = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterDateExecActionBegDate.setObjectName(_fromUtf8("chkFilterDateExecActionBegDate"))
        self.horizontalLayout_6.addWidget(self.chkFilterDateExecActionBegDate)
        self.edtFilterDateExecActionBegDate = CDateEdit(self.scrollAreaWidgetContents)
        self.edtFilterDateExecActionBegDate.setCalendarPopup(True)
        self.edtFilterDateExecActionBegDate.setObjectName(_fromUtf8("edtFilterDateExecActionBegDate"))
        self.horizontalLayout_6.addWidget(self.edtFilterDateExecActionBegDate)
        self.chkFilterDateExecActionEndDate = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterDateExecActionEndDate.setObjectName(_fromUtf8("chkFilterDateExecActionEndDate"))
        self.horizontalLayout_6.addWidget(self.chkFilterDateExecActionEndDate)
        self.edtFilterDateExecActionEndDate = CDateEdit(self.scrollAreaWidgetContents)
        self.edtFilterDateExecActionEndDate.setCalendarPopup(True)
        self.edtFilterDateExecActionEndDate.setObjectName(_fromUtf8("edtFilterDateExecActionEndDate"))
        self.horizontalLayout_6.addWidget(self.edtFilterDateExecActionEndDate)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.lblFilterEventEndDate = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFilterEventEndDate.setObjectName(_fromUtf8("lblFilterEventEndDate"))
        self.verticalLayout.addWidget(self.lblFilterEventEndDate)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.chkFilterEventBegDate = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterEventBegDate.setObjectName(_fromUtf8("chkFilterEventBegDate"))
        self.horizontalLayout_5.addWidget(self.chkFilterEventBegDate)
        self.edtFilterEventBegDate = CDateEdit(self.scrollAreaWidgetContents)
        self.edtFilterEventBegDate.setCalendarPopup(True)
        self.edtFilterEventBegDate.setObjectName(_fromUtf8("edtFilterEventBegDate"))
        self.horizontalLayout_5.addWidget(self.edtFilterEventBegDate)
        self.chkFilterEventEndDate = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterEventEndDate.setObjectName(_fromUtf8("chkFilterEventEndDate"))
        self.horizontalLayout_5.addWidget(self.chkFilterEventEndDate)
        self.edtFilterEventEndDate = CDateEdit(self.scrollAreaWidgetContents)
        self.edtFilterEventEndDate.setCalendarPopup(True)
        self.edtFilterEventEndDate.setObjectName(_fromUtf8("edtFilterEventEndDate"))
        self.horizontalLayout_5.addWidget(self.edtFilterEventEndDate)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.lblFilterAttachFileDate = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFilterAttachFileDate.setObjectName(_fromUtf8("lblFilterAttachFileDate"))
        self.verticalLayout.addWidget(self.lblFilterAttachFileDate)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.chkFilterAttachFileBegDate = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterAttachFileBegDate.setObjectName(_fromUtf8("chkFilterAttachFileBegDate"))
        self.horizontalLayout_7.addWidget(self.chkFilterAttachFileBegDate)
        self.edtFilterAttachFileBegDate = CDateEdit(self.scrollAreaWidgetContents)
        self.edtFilterAttachFileBegDate.setCalendarPopup(True)
        self.edtFilterAttachFileBegDate.setObjectName(_fromUtf8("edtFilterAttachFileBegDate"))
        self.horizontalLayout_7.addWidget(self.edtFilterAttachFileBegDate)
        self.chkFilterAttachFileEndDate = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterAttachFileEndDate.setObjectName(_fromUtf8("chkFilterAttachFileEndDate"))
        self.horizontalLayout_7.addWidget(self.chkFilterAttachFileEndDate)
        self.edtFilterAttachFileEndDate = CDateEdit(self.scrollAreaWidgetContents)
        self.edtFilterAttachFileEndDate.setCalendarPopup(True)
        self.edtFilterAttachFileEndDate.setObjectName(_fromUtf8("edtFilterAttachFileEndDate"))
        self.horizontalLayout_7.addWidget(self.edtFilterAttachFileEndDate)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.chkFilterIdentify = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterIdentify.setObjectName(_fromUtf8("chkFilterIdentify"))
        self.verticalLayout.addWidget(self.chkFilterIdentify)
        self.cmbFilterIdentify = CRecordMultivalueComboBox(self.scrollAreaWidgetContents)
        self.cmbFilterIdentify.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterIdentify.sizePolicy().hasHeightForWidth())
        self.cmbFilterIdentify.setSizePolicy(sizePolicy)
        self.cmbFilterIdentify.setObjectName(_fromUtf8("cmbFilterIdentify"))
        self.verticalLayout.addWidget(self.cmbFilterIdentify)
        self.lblFilterIsFile = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFilterIsFile.setObjectName(_fromUtf8("lblFilterIsFile"))
        self.verticalLayout.addWidget(self.lblFilterIsFile)
        self.cmbFilterIsFile = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbFilterIsFile.setObjectName(_fromUtf8("cmbFilterIsFile"))
        self.cmbFilterIsFile.addItem(_fromUtf8(""))
        self.cmbFilterIsFile.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.cmbFilterIsFile)
        self.lblFilterFileType = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFilterFileType.setObjectName(_fromUtf8("lblFilterFileType"))
        self.verticalLayout.addWidget(self.lblFilterFileType)
        self.cmbFilterFileType = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbFilterFileType.setObjectName(_fromUtf8("cmbFilterFileType"))
        self.cmbFilterFileType.addItem(_fromUtf8(""))
        self.cmbFilterFileType.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.cmbFilterFileType)
        self.chkFilterExportErrors = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterExportErrors.setObjectName(_fromUtf8("chkFilterExportErrors"))
        self.verticalLayout.addWidget(self.chkFilterExportErrors)
        self.edtFilterExportErrors = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtFilterExportErrors.setObjectName(_fromUtf8("edtFilterExportErrors"))
        self.verticalLayout.addWidget(self.edtFilterExportErrors)
        self.chkFilterSchematronErrors = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkFilterSchematronErrors.setObjectName(_fromUtf8("chkFilterSchematronErrors"))
        self.verticalLayout.addWidget(self.chkFilterSchematronErrors)
        self.edtFilterSchematronErrors = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtFilterSchematronErrors.setObjectName(_fromUtf8("edtFilterSchematronErrors"))
        self.verticalLayout.addWidget(self.edtFilterSchematronErrors)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnFilterApply = QtGui.QPushButton(self.groupBoxFilters)
        self.btnFilterApply.setObjectName(_fromUtf8("btnFilterApply"))
        self.horizontalLayout_2.addWidget(self.btnFilterApply)
        self.btnFilterReset = QtGui.QPushButton(self.groupBoxFilters)
        self.btnFilterReset.setObjectName(_fromUtf8("btnFilterReset"))
        self.horizontalLayout_2.addWidget(self.btnFilterReset)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBoxFilters, 0, 1, 2, 1)
        self.tblActionFileAttach = CTableView(Attach_SEMD_IEMK_Dialog)
        self.tblActionFileAttach.setObjectName(_fromUtf8("tblActionFileAttach"))
        self.gridLayout_3.addWidget(self.tblActionFileAttach, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblCount = QtGui.QLabel(Attach_SEMD_IEMK_Dialog)
        self.lblCount.setObjectName(_fromUtf8("lblCount"))
        self.horizontalLayout_4.addWidget(self.lblCount)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnOpenFile = CAttachButton(Attach_SEMD_IEMK_Dialog)
        self.btnOpenFile.setObjectName(_fromUtf8("btnOpenFile"))
        self.horizontalLayout_3.addWidget(self.btnOpenFile)
        self.btnPrint = CPrintButton(Attach_SEMD_IEMK_Dialog)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.horizontalLayout_3.addWidget(self.btnPrint)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)

        self.retranslateUi(Attach_SEMD_IEMK_Dialog)
        self.cmbFilterSigned.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Attach_SEMD_IEMK_Dialog)

    def retranslateUi(self, Attach_SEMD_IEMK_Dialog):
        Attach_SEMD_IEMK_Dialog.setWindowTitle(_translate("Attach_SEMD_IEMK_Dialog", "Сводка о формировании структурированных электронных медицинских документов для РЭМД", None))
        self.groupBoxFilters.setTitle(_translate("Attach_SEMD_IEMK_Dialog", "Фильтры", None))
        self.chkFilterLastName.setText(_translate("Attach_SEMD_IEMK_Dialog", "Фамилия", None))
        self.chkFilterFirstName.setText(_translate("Attach_SEMD_IEMK_Dialog", "Имя", None))
        self.chkFilterPatrName.setText(_translate("Attach_SEMD_IEMK_Dialog", "Отчество", None))
        self.chkFilterEventId.setText(_translate("Attach_SEMD_IEMK_Dialog", "Код карточки", None))
        self.lblFilterSigned.setText(_translate("Attach_SEMD_IEMK_Dialog", "Показать", None))
        self.cmbFilterSigned.setItemText(0, _translate("Attach_SEMD_IEMK_Dialog", "все", None))
        self.cmbFilterSigned.setItemText(1, _translate("Attach_SEMD_IEMK_Dialog", "не подписанные врачом", None))
        self.cmbFilterSigned.setItemText(2, _translate("Attach_SEMD_IEMK_Dialog", "не подписанные МО", None))
        self.cmbFilterSigned.setItemText(3, _translate("Attach_SEMD_IEMK_Dialog", "подписанные МО", None))
        self.cmbFilterSigned.setItemText(4, _translate("Attach_SEMD_IEMK_Dialog", "подписанные врачом без подписи МО", None))
        self.cmbFilterSigned.setItemText(5, _translate("Attach_SEMD_IEMK_Dialog", "все не подписанные", None))
        self.cmbFilterSigned.setItemText(6, _translate("Attach_SEMD_IEMK_Dialog", "все подписанные врачом", None))
        self.lblFilterPerson.setText(_translate("Attach_SEMD_IEMK_Dialog", "Врач", None))
        self.chkFilterSNILS.setText(_translate("Attach_SEMD_IEMK_Dialog", "Искать по СНИЛС", None))
        self.lblSpeciality.setText(_translate("Attach_SEMD_IEMK_Dialog", "&Специальность", None))
        self.cmbSpeciality.setWhatsThis(_translate("Attach_SEMD_IEMK_Dialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.chkFilterOrgStructure.setText(_translate("Attach_SEMD_IEMK_Dialog", "Подразделение", None))
        self.chkFilterActionType.setText(_translate("Attach_SEMD_IEMK_Dialog", "Тип действия", None))
        self.chkFilterEventType.setText(_translate("Attach_SEMD_IEMK_Dialog", "Тип события", None))
        self.lblFinance.setText(_translate("Attach_SEMD_IEMK_Dialog", "Финансирование ", None))
        self.lblFilterEventEndDate_2.setText(_translate("Attach_SEMD_IEMK_Dialog", "Дата выполнения действия", None))
        self.chkFilterDateExecActionBegDate.setText(_translate("Attach_SEMD_IEMK_Dialog", "С", None))
        self.chkFilterDateExecActionEndDate.setText(_translate("Attach_SEMD_IEMK_Dialog", "по", None))
        self.lblFilterEventEndDate.setText(_translate("Attach_SEMD_IEMK_Dialog", "Дата окончания события", None))
        self.chkFilterEventBegDate.setText(_translate("Attach_SEMD_IEMK_Dialog", "С", None))
        self.chkFilterEventEndDate.setText(_translate("Attach_SEMD_IEMK_Dialog", "по", None))
        self.lblFilterAttachFileDate.setText(_translate("Attach_SEMD_IEMK_Dialog", "Дата прикрепления файла", None))
        self.chkFilterAttachFileBegDate.setText(_translate("Attach_SEMD_IEMK_Dialog", "С", None))
        self.chkFilterAttachFileEndDate.setText(_translate("Attach_SEMD_IEMK_Dialog", "по", None))
        self.chkFilterIdentify.setText(_translate("Attach_SEMD_IEMK_Dialog", "Идентификаторы", None))
        self.lblFilterIsFile.setText(_translate("Attach_SEMD_IEMK_Dialog", "Наличие файлов", None))
        self.cmbFilterIsFile.setItemText(0, _translate("Attach_SEMD_IEMK_Dialog", "Присутствуют", None))
        self.cmbFilterIsFile.setItemText(1, _translate("Attach_SEMD_IEMK_Dialog", "Отсутствуют", None))
        self.lblFilterFileType.setText(_translate("Attach_SEMD_IEMK_Dialog", "Тип файлов", None))
        self.cmbFilterFileType.setItemText(0, _translate("Attach_SEMD_IEMK_Dialog", "Есть xml", None))
        self.cmbFilterFileType.setItemText(1, _translate("Attach_SEMD_IEMK_Dialog", "Есть только pdf", None))
        self.chkFilterExportErrors.setText(_translate("Attach_SEMD_IEMK_Dialog", "Ошибки РЭМД", None))
        self.chkFilterSchematronErrors.setText(_translate("Attach_SEMD_IEMK_Dialog", "Ошибки по схематрону", None))
        self.btnFilterApply.setText(_translate("Attach_SEMD_IEMK_Dialog", "Применить", None))
        self.btnFilterReset.setText(_translate("Attach_SEMD_IEMK_Dialog", "Сбросить", None))
        self.lblCount.setText(_translate("Attach_SEMD_IEMK_Dialog", "Записей в списке: 0", None))
        self.btnOpenFile.setText(_translate("Attach_SEMD_IEMK_Dialog", "Просмотр", None))
        self.btnPrint.setText(_translate("Attach_SEMD_IEMK_Dialog", "Печать", None))

from library.crbcombobox import CRBComboBox
from Events.ActionTypeComboBoxEx import CActionTypeComboBoxEx
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.Attach.AttachButton import CAttachButton
from library.PrintTemplates import CPrintButton
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.TableView import CTableView
from library.MultivalueComboBox import CRBMultivalueComboBox, CRecordMultivalueComboBox
from library.DateEdit import CDateEdit

