# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\samson\UP_s11\client\Reports\DispObservationListSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DispObservationSetupDialog(object):
    def setupUi(self, DispObservationSetupDialog):
        DispObservationSetupDialog.setObjectName(_fromUtf8("DispObservationSetupDialog"))
        DispObservationSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        DispObservationSetupDialog.resize(432, 443)
        DispObservationSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(DispObservationSetupDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblSocStatusClass = QtGui.QLabel(DispObservationSetupDialog)
        self.lblSocStatusClass.setObjectName(_fromUtf8("lblSocStatusClass"))
        self.gridLayout.addWidget(self.lblSocStatusClass, 10, 0, 1, 1)
        self.cmbSocStatusClass = CSocStatusComboBox(DispObservationSetupDialog)
        self.cmbSocStatusClass.setObjectName(_fromUtf8("cmbSocStatusClass"))
        self.gridLayout.addWidget(self.cmbSocStatusClass, 10, 1, 1, 4)
        self.lblPerson = QtGui.QLabel(DispObservationSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 9, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(DispObservationSetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPerson, 9, 1, 1, 4)
        self.lblSocStatusType = QtGui.QLabel(DispObservationSetupDialog)
        self.lblSocStatusType.setObjectName(_fromUtf8("lblSocStatusType"))
        self.gridLayout.addWidget(self.lblSocStatusType, 11, 0, 1, 1)
        self.frmMKBEx = QtGui.QFrame(DispObservationSetupDialog)
        self.frmMKBEx.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMKBEx.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMKBEx.setObjectName(_fromUtf8("frmMKBEx"))
        self.gridlayout = QtGui.QGridLayout(self.frmMKBEx)
        self.gridlayout.setMargin(0)
        self.gridlayout.setHorizontalSpacing(4)
        self.gridlayout.setVerticalSpacing(0)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.gridLayout.addWidget(self.frmMKBEx, 13, 0, 1, 1)
        self.frmMKB = QtGui.QFrame(DispObservationSetupDialog)
        self.frmMKB.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMKB.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMKB.setObjectName(_fromUtf8("frmMKB"))
        self.gridlayout1 = QtGui.QGridLayout(self.frmMKB)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setHorizontalSpacing(4)
        self.gridlayout1.setVerticalSpacing(0)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.cmbMKBFilter = QtGui.QComboBox(self.frmMKB)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.gridlayout1.addWidget(self.cmbMKBFilter, 0, 0, 1, 1)
        self.edtMKBFrom = CICDCodeEdit(self.frmMKB)
        self.edtMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.gridlayout1.addWidget(self.edtMKBFrom, 0, 1, 1, 1)
        self.edtMKBTo = CICDCodeEdit(self.frmMKB)
        self.edtMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.gridlayout1.addWidget(self.edtMKBTo, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.frmMKB, 12, 2, 1, 3)
        self.frmAge = QtGui.QFrame(DispObservationSetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self.hboxlayout = QtGui.QHBoxLayout(self.frmAge)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.hboxlayout.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.hboxlayout.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.hboxlayout.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.hboxlayout.addWidget(self.lblAgeYears)
        spacerItem1 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frmAge, 3, 1, 1, 3)
        self.lblWorkOrganisation = QtGui.QLabel(DispObservationSetupDialog)
        self.lblWorkOrganisation.setObjectName(_fromUtf8("lblWorkOrganisation"))
        self.gridLayout.addWidget(self.lblWorkOrganisation, 1, 0, 1, 1)
        self.lblDate = QtGui.QLabel(DispObservationSetupDialog)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout.addWidget(self.lblDate, 0, 0, 1, 1)
        self.edtDate = CDateEdit(DispObservationSetupDialog)
        self.edtDate.setCalendarPopup(True)
        self.edtDate.setObjectName(_fromUtf8("edtDate"))
        self.gridLayout.addWidget(self.edtDate, 0, 1, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(160, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 2)
        self.cmbWorkOrganisation = COrgComboBox(DispObservationSetupDialog)
        self.cmbWorkOrganisation.setObjectName(_fromUtf8("cmbWorkOrganisation"))
        self.gridLayout.addWidget(self.cmbWorkOrganisation, 1, 1, 1, 3)
        self.btnSelectWorkOrganisation = QtGui.QToolButton(DispObservationSetupDialog)
        self.btnSelectWorkOrganisation.setArrowType(QtCore.Qt.NoArrow)
        self.btnSelectWorkOrganisation.setObjectName(_fromUtf8("btnSelectWorkOrganisation"))
        self.gridLayout.addWidget(self.btnSelectWorkOrganisation, 1, 4, 1, 1)
        self.lblSex = QtGui.QLabel(DispObservationSetupDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout.addWidget(self.lblSex, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(141, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 3, 1, 1)
        self.cmbSex = QtGui.QComboBox(DispObservationSetupDialog)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 2, 1, 1, 2)
        self.lblAge = QtGui.QLabel(DispObservationSetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 3, 0, 1, 1)
        self.chkFilterAddressType = QtGui.QCheckBox(DispObservationSetupDialog)
        self.chkFilterAddressType.setObjectName(_fromUtf8("chkFilterAddressType"))
        self.gridLayout.addWidget(self.chkFilterAddressType, 4, 0, 1, 1)
        self.cmbFilterAddressType = QtGui.QComboBox(DispObservationSetupDialog)
        self.cmbFilterAddressType.setEnabled(False)
        self.cmbFilterAddressType.setObjectName(_fromUtf8("cmbFilterAddressType"))
        self.cmbFilterAddressType.addItem(_fromUtf8(""))
        self.cmbFilterAddressType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbFilterAddressType, 4, 1, 1, 4)
        self.cmbArea = COrgStructureComboBox(DispObservationSetupDialog)
        self.cmbArea.setEnabled(False)
        self.cmbArea.setObjectName(_fromUtf8("cmbArea"))
        self.gridLayout.addWidget(self.cmbArea, 5, 1, 1, 4)
        self.lblOrgStructure = QtGui.QLabel(DispObservationSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 7, 0, 1, 1)
        self.chkArea = QtGui.QCheckBox(DispObservationSetupDialog)
        self.chkArea.setObjectName(_fromUtf8("chkArea"))
        self.gridLayout.addWidget(self.chkArea, 5, 0, 1, 1)
        self.lblSpeciality = QtGui.QLabel(DispObservationSetupDialog)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 8, 0, 1, 1)
        self.cmbSpeciality = CRBComboBox(DispObservationSetupDialog)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 8, 1, 1, 4)
        self.cmbOrgStructure = COrgStructureComboBox(DispObservationSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 7, 1, 1, 4)
        self.lblMKB = QtGui.QLabel(DispObservationSetupDialog)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.gridLayout.addWidget(self.lblMKB, 12, 0, 1, 1)
        self.cmbSocStatusType = CRBComboBox(DispObservationSetupDialog)
        self.cmbSocStatusType.setObjectName(_fromUtf8("cmbSocStatusType"))
        self.gridLayout.addWidget(self.cmbSocStatusType, 11, 1, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(DispObservationSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 16, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(129, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 15, 0, 1, 1)
        self.chkPrintOnlyFilledRows = QtGui.QCheckBox(DispObservationSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkPrintOnlyFilledRows.sizePolicy().hasHeightForWidth())
        self.chkPrintOnlyFilledRows.setSizePolicy(sizePolicy)
        self.chkPrintOnlyFilledRows.setObjectName(_fromUtf8("chkPrintOnlyFilledRows"))
        self.gridLayout.addWidget(self.chkPrintOnlyFilledRows, 14, 0, 1, 2)
        self.lblOrgStructureAttach = QtGui.QLabel(DispObservationSetupDialog)
        self.lblOrgStructureAttach.setObjectName(_fromUtf8("lblOrgStructureAttach"))
        self.gridLayout.addWidget(self.lblOrgStructureAttach, 6, 0, 1, 1)
        self.cmbOrgStructureAttach = CAreaComboBox(DispObservationSetupDialog)
        self.cmbOrgStructureAttach.setObjectName(_fromUtf8("cmbOrgStructureAttach"))
        self.gridLayout.addWidget(self.cmbOrgStructureAttach, 6, 1, 1, 4)
        self.lblSocStatusClass.setBuddy(self.cmbSocStatusClass)
        self.lblSocStatusType.setBuddy(self.cmbSocStatusType)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblWorkOrganisation.setBuddy(self.cmbWorkOrganisation)
        self.lblDate.setBuddy(self.edtDate)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblMKB.setBuddy(self.cmbMKBFilter)
        self.lblOrgStructureAttach.setBuddy(self.cmbOrgStructureAttach)

        self.retranslateUi(DispObservationSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DispObservationSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DispObservationSetupDialog.reject)
        QtCore.QObject.connect(self.chkFilterAddressType, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterAddressType.setEnabled)
        QtCore.QObject.connect(self.chkArea, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbArea.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DispObservationSetupDialog)
        DispObservationSetupDialog.setTabOrder(self.edtDate, self.cmbWorkOrganisation)
        DispObservationSetupDialog.setTabOrder(self.cmbWorkOrganisation, self.btnSelectWorkOrganisation)
        DispObservationSetupDialog.setTabOrder(self.btnSelectWorkOrganisation, self.cmbSex)
        DispObservationSetupDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        DispObservationSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        DispObservationSetupDialog.setTabOrder(self.edtAgeTo, self.chkFilterAddressType)
        DispObservationSetupDialog.setTabOrder(self.chkFilterAddressType, self.cmbFilterAddressType)
        DispObservationSetupDialog.setTabOrder(self.cmbFilterAddressType, self.chkArea)
        DispObservationSetupDialog.setTabOrder(self.chkArea, self.cmbArea)
        DispObservationSetupDialog.setTabOrder(self.cmbArea, self.cmbPerson)
        DispObservationSetupDialog.setTabOrder(self.cmbPerson, self.cmbMKBFilter)
        DispObservationSetupDialog.setTabOrder(self.cmbMKBFilter, self.edtMKBFrom)
        DispObservationSetupDialog.setTabOrder(self.edtMKBFrom, self.edtMKBTo)
        DispObservationSetupDialog.setTabOrder(self.edtMKBTo, self.buttonBox)

    def retranslateUi(self, DispObservationSetupDialog):
        DispObservationSetupDialog.setWindowTitle(_translate("DispObservationSetupDialog", "параметры отчёта", None))
        self.lblSocStatusClass.setText(_translate("DispObservationSetupDialog", "Класс соц.статуса", None))
        self.lblPerson.setText(_translate("DispObservationSetupDialog", "Врач", None))
        self.cmbPerson.setItemText(0, _translate("DispObservationSetupDialog", "Врач", None))
        self.lblSocStatusType.setText(_translate("DispObservationSetupDialog", "Тип соц.статуса", None))
        self.cmbMKBFilter.setItemText(0, _translate("DispObservationSetupDialog", "Игнор.", None))
        self.cmbMKBFilter.setItemText(1, _translate("DispObservationSetupDialog", "Интервал", None))
        self.edtMKBFrom.setInputMask(_translate("DispObservationSetupDialog", "a00.00; ", None))
        self.edtMKBFrom.setText(_translate("DispObservationSetupDialog", "A.", None))
        self.edtMKBTo.setInputMask(_translate("DispObservationSetupDialog", "a00.00; ", None))
        self.edtMKBTo.setText(_translate("DispObservationSetupDialog", "Z99.9", None))
        self.lblAgeTo.setText(_translate("DispObservationSetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("DispObservationSetupDialog", "лет", None))
        self.lblWorkOrganisation.setText(_translate("DispObservationSetupDialog", "Занятость", None))
        self.lblDate.setText(_translate("DispObservationSetupDialog", "На дату", None))
        self.btnSelectWorkOrganisation.setText(_translate("DispObservationSetupDialog", "...", None))
        self.lblSex.setText(_translate("DispObservationSetupDialog", "По&л", None))
        self.cmbSex.setItemText(1, _translate("DispObservationSetupDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("DispObservationSetupDialog", "Ж", None))
        self.lblAge.setText(_translate("DispObservationSetupDialog", "Во&зраст с", None))
        self.chkFilterAddressType.setText(_translate("DispObservationSetupDialog", "Учитывать адрес", None))
        self.cmbFilterAddressType.setItemText(0, _translate("DispObservationSetupDialog", "Регистрации", None))
        self.cmbFilterAddressType.setItemText(1, _translate("DispObservationSetupDialog", "Проживания", None))
        self.lblOrgStructure.setText(_translate("DispObservationSetupDialog", "&Подразделение врача", None))
        self.chkArea.setText(_translate("DispObservationSetupDialog", "Те&рритория", None))
        self.lblSpeciality.setText(_translate("DispObservationSetupDialog", "&Специальность", None))
        self.cmbSpeciality.setWhatsThis(_translate("DispObservationSetupDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.lblMKB.setText(_translate("DispObservationSetupDialog", "Коды диагнозов по &МКБ", None))
        self.chkPrintOnlyFilledRows.setText(_translate("DispObservationSetupDialog", "Не отображать пустые строки", None))
        self.lblOrgStructureAttach.setText(_translate("DispObservationSetupDialog", "Прикрепление к &участку", None))

from Orgs.OrgComboBox import COrgComboBox
from Orgs.OrgStructComboBoxes import CAreaComboBox, COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Registry.SocStatusComboBox import CSocStatusComboBox
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEdit
from library.crbcombobox import CRBComboBox
