# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Projects\Samson\client_test\Reports\DeathReportSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DeathReportSetupDialog(object):
    def setupUi(self, DeathReportSetupDialog):
        DeathReportSetupDialog.setObjectName(_fromUtf8("DeathReportSetupDialog"))
        DeathReportSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        DeathReportSetupDialog.resize(320, 314)
        DeathReportSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(DeathReportSetupDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblBegDate = QtGui.QLabel(DeathReportSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.edtBegDate = CDateEdit(DeathReportSetupDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.lblEndDate = QtGui.QLabel(DeathReportSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.edtEndDate = CDateEdit(DeathReportSetupDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.lblBusyness = QtGui.QLabel(DeathReportSetupDialog)
        self.lblBusyness.setObjectName(_fromUtf8("lblBusyness"))
        self.gridLayout.addWidget(self.lblBusyness, 2, 0, 1, 1)
        self.lblMKB = QtGui.QLabel(DeathReportSetupDialog)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.gridLayout.addWidget(self.lblMKB, 3, 0, 1, 1)
        self.frmMKB = QtGui.QFrame(DeathReportSetupDialog)
        self.frmMKB.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMKB.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMKB.setObjectName(_fromUtf8("frmMKB"))
        self._2 = QtGui.QGridLayout(self.frmMKB)
        self._2.setMargin(0)
        self._2.setHorizontalSpacing(4)
        self._2.setVerticalSpacing(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.cmbMKBFilter = QtGui.QComboBox(self.frmMKB)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self._2.addWidget(self.cmbMKBFilter, 0, 0, 1, 1)
        self.edtMKBFrom = CICDCodeEdit(self.frmMKB)
        self.edtMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self._2.addWidget(self.edtMKBFrom, 0, 1, 1, 1)
        self.edtMKBTo = CICDCodeEdit(self.frmMKB)
        self.edtMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self._2.addWidget(self.edtMKBTo, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem2, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.frmMKB, 3, 1, 1, 2)
        self.lblPlace = QtGui.QLabel(DeathReportSetupDialog)
        self.lblPlace.setObjectName(_fromUtf8("lblPlace"))
        self.gridLayout.addWidget(self.lblPlace, 4, 0, 1, 1)
        self.lblCause = QtGui.QLabel(DeathReportSetupDialog)
        self.lblCause.setObjectName(_fromUtf8("lblCause"))
        self.gridLayout.addWidget(self.lblCause, 5, 0, 1, 1)
        self.lblFoundBy = QtGui.QLabel(DeathReportSetupDialog)
        self.lblFoundBy.setObjectName(_fromUtf8("lblFoundBy"))
        self.gridLayout.addWidget(self.lblFoundBy, 6, 0, 1, 1)
        self.lblFoundation = QtGui.QLabel(DeathReportSetupDialog)
        self.lblFoundation.setObjectName(_fromUtf8("lblFoundation"))
        self.gridLayout.addWidget(self.lblFoundation, 7, 0, 1, 1)
        self.chkRelegateOrg = QtGui.QCheckBox(DeathReportSetupDialog)
        self.chkRelegateOrg.setObjectName(_fromUtf8("chkRelegateOrg"))
        self.gridLayout.addWidget(self.chkRelegateOrg, 8, 0, 1, 1)
        self.cmbRelegateOrg = COrgComboBoxEx(DeathReportSetupDialog)
        self.cmbRelegateOrg.setEnabled(False)
        self.cmbRelegateOrg.setObjectName(_fromUtf8("cmbRelegateOrg"))
        self.gridLayout.addWidget(self.cmbRelegateOrg, 8, 1, 1, 2)
        self.chkExcludeSelected = QtGui.QCheckBox(DeathReportSetupDialog)
        self.chkExcludeSelected.setEnabled(False)
        self.chkExcludeSelected.setObjectName(_fromUtf8("chkExcludeSelected"))
        self.gridLayout.addWidget(self.chkExcludeSelected, 9, 0, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(129, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 10, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(DeathReportSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 11, 0, 1, 2)
        self.cmbBusyness = QtGui.QComboBox(DeathReportSetupDialog)
        self.cmbBusyness.setObjectName(_fromUtf8("cmbBusyness"))
        self.cmbBusyness.addItem(_fromUtf8(""))
        self.cmbBusyness.addItem(_fromUtf8(""))
        self.cmbBusyness.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbBusyness, 2, 1, 1, 2)
        self.cmbPlace = CRBComboBox(DeathReportSetupDialog)
        self.cmbPlace.setObjectName(_fromUtf8("cmbPlace"))
        self.gridLayout.addWidget(self.cmbPlace, 4, 1, 1, 2)
        self.cmbCause = CRBComboBox(DeathReportSetupDialog)
        self.cmbCause.setObjectName(_fromUtf8("cmbCause"))
        self.gridLayout.addWidget(self.cmbCause, 5, 1, 1, 2)
        self.cmbFoundBy = CRBComboBox(DeathReportSetupDialog)
        self.cmbFoundBy.setObjectName(_fromUtf8("cmbFoundBy"))
        self.gridLayout.addWidget(self.cmbFoundBy, 6, 1, 1, 2)
        self.cmbFoundation = CRBComboBox(DeathReportSetupDialog)
        self.cmbFoundation.setObjectName(_fromUtf8("cmbFoundation"))
        self.gridLayout.addWidget(self.cmbFoundation, 7, 1, 1, 2)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblBusyness.setBuddy(self.cmbBusyness)
        self.lblMKB.setBuddy(self.cmbMKBFilter)
        self.lblPlace.setBuddy(self.cmbPlace)
        self.lblCause.setBuddy(self.cmbCause)
        self.lblFoundBy.setBuddy(self.cmbFoundBy)
        self.lblFoundation.setBuddy(self.cmbFoundation)

        self.retranslateUi(DeathReportSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DeathReportSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DeathReportSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DeathReportSetupDialog)
        DeathReportSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        DeathReportSetupDialog.setTabOrder(self.edtEndDate, self.cmbBusyness)
        DeathReportSetupDialog.setTabOrder(self.cmbBusyness, self.cmbMKBFilter)
        DeathReportSetupDialog.setTabOrder(self.cmbMKBFilter, self.edtMKBFrom)
        DeathReportSetupDialog.setTabOrder(self.edtMKBFrom, self.edtMKBTo)
        DeathReportSetupDialog.setTabOrder(self.edtMKBTo, self.cmbPlace)
        DeathReportSetupDialog.setTabOrder(self.cmbPlace, self.cmbCause)
        DeathReportSetupDialog.setTabOrder(self.cmbCause, self.cmbFoundBy)
        DeathReportSetupDialog.setTabOrder(self.cmbFoundBy, self.cmbFoundation)
        DeathReportSetupDialog.setTabOrder(self.cmbFoundation, self.buttonBox)

    def retranslateUi(self, DeathReportSetupDialog):
        DeathReportSetupDialog.setWindowTitle(_translate("DeathReportSetupDialog", "параметры отчёта", None))
        self.lblBegDate.setText(_translate("DeathReportSetupDialog", "Дата начала периода", None))
        self.lblEndDate.setText(_translate("DeathReportSetupDialog", "Дата окончания периода", None))
        self.lblBusyness.setText(_translate("DeathReportSetupDialog", "Занятость", None))
        self.lblMKB.setText(_translate("DeathReportSetupDialog", "Коды диагнозов по &МКБ", None))
        self.cmbMKBFilter.setItemText(0, _translate("DeathReportSetupDialog", "Игнор.", None))
        self.cmbMKBFilter.setItemText(1, _translate("DeathReportSetupDialog", "Интервал", None))
        self.edtMKBFrom.setInputMask(_translate("DeathReportSetupDialog", "a00.00", None))
        self.edtMKBFrom.setText(_translate("DeathReportSetupDialog", "A.", None))
        self.edtMKBTo.setInputMask(_translate("DeathReportSetupDialog", "a00.00", None))
        self.edtMKBTo.setText(_translate("DeathReportSetupDialog", "Z99.9", None))
        self.lblPlace.setText(_translate("DeathReportSetupDialog", "Смерть наступила ", None))
        self.lblCause.setText(_translate("DeathReportSetupDialog", "Смерть произошла", None))
        self.lblFoundBy.setText(_translate("DeathReportSetupDialog", "Причина установлена", None))
        self.lblFoundation.setText(_translate("DeathReportSetupDialog", "Основание", None))
        self.chkRelegateOrg.setText(_translate("DeathReportSetupDialog", "Направитель", None))
        self.chkExcludeSelected.setText(_translate("DeathReportSetupDialog", "любой кроме указанного", None))
        self.cmbBusyness.setItemText(0, _translate("DeathReportSetupDialog", "-", None))
        self.cmbBusyness.setItemText(1, _translate("DeathReportSetupDialog", "указана", None))
        self.cmbBusyness.setItemText(2, _translate("DeathReportSetupDialog", "не указана", None))

from Orgs.OrgComboBox import COrgComboBoxEx
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEdit
from library.crbcombobox import CRBComboBox
