# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Projects\Samson\client_test\Reports\EventResultListSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EventResultSetupDialog(object):
    def setupUi(self, EventResultSetupDialog):
        EventResultSetupDialog.setObjectName(_fromUtf8("EventResultSetupDialog"))
        EventResultSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        EventResultSetupDialog.resize(458, 794)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EventResultSetupDialog.sizePolicy().hasHeightForWidth())
        EventResultSetupDialog.setSizePolicy(sizePolicy)
        EventResultSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(EventResultSetupDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblBegDate = QtGui.QLabel(EventResultSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.edtBegDate = CDateEdit(EventResultSetupDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 2)
        self.lblEndDate = QtGui.QLabel(EventResultSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.edtEndDate = CDateEdit(EventResultSetupDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 2)
        self.lblEventPurpose = QtGui.QLabel(EventResultSetupDialog)
        self.lblEventPurpose.setObjectName(_fromUtf8("lblEventPurpose"))
        self.gridLayout.addWidget(self.lblEventPurpose, 2, 0, 1, 1)
        self.btnEventTypeList = QtGui.QPushButton(EventResultSetupDialog)
        self.btnEventTypeList.setObjectName(_fromUtf8("btnEventTypeList"))
        self.gridLayout.addWidget(self.btnEventTypeList, 3, 0, 1, 1)
        self.lblEventTypeList = QtGui.QLabel(EventResultSetupDialog)
        self.lblEventTypeList.setWordWrap(True)
        self.lblEventTypeList.setObjectName(_fromUtf8("lblEventTypeList"))
        self.gridLayout.addWidget(self.lblEventTypeList, 3, 1, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(EventResultSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 4, 0, 1, 1)
        self.btnSpecialityList = QtGui.QPushButton(EventResultSetupDialog)
        self.btnSpecialityList.setObjectName(_fromUtf8("btnSpecialityList"))
        self.gridLayout.addWidget(self.btnSpecialityList, 5, 0, 1, 1)
        self.lblSpecialityList = QtGui.QLabel(EventResultSetupDialog)
        self.lblSpecialityList.setWordWrap(True)
        self.lblSpecialityList.setObjectName(_fromUtf8("lblSpecialityList"))
        self.gridLayout.addWidget(self.lblSpecialityList, 5, 1, 1, 1)
        self.lblPerson = QtGui.QLabel(EventResultSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 6, 0, 1, 1)
        self.chkPersonDetail = QtGui.QCheckBox(EventResultSetupDialog)
        self.chkPersonDetail.setObjectName(_fromUtf8("chkPersonDetail"))
        self.gridLayout.addWidget(self.chkPersonDetail, 7, 1, 1, 2)
        self.lblWorkOrganisation = QtGui.QLabel(EventResultSetupDialog)
        self.lblWorkOrganisation.setObjectName(_fromUtf8("lblWorkOrganisation"))
        self.gridLayout.addWidget(self.lblWorkOrganisation, 8, 0, 1, 1)
        self.btnSelectWorkOrganisation = QtGui.QToolButton(EventResultSetupDialog)
        self.btnSelectWorkOrganisation.setArrowType(QtCore.Qt.NoArrow)
        self.btnSelectWorkOrganisation.setObjectName(_fromUtf8("btnSelectWorkOrganisation"))
        self.gridLayout.addWidget(self.btnSelectWorkOrganisation, 8, 4, 1, 1)
        self.lblResult = QtGui.QLabel(EventResultSetupDialog)
        self.lblResult.setObjectName(_fromUtf8("lblResult"))
        self.gridLayout.addWidget(self.lblResult, 9, 0, 1, 1)
        self.lblPrimary = QtGui.QLabel(EventResultSetupDialog)
        self.lblPrimary.setObjectName(_fromUtf8("lblPrimary"))
        self.gridLayout.addWidget(self.lblPrimary, 10, 0, 1, 1)
        self.lblOrder = QtGui.QLabel(EventResultSetupDialog)
        self.lblOrder.setObjectName(_fromUtf8("lblOrder"))
        self.gridLayout.addWidget(self.lblOrder, 11, 0, 1, 1)
        self.lblSex = QtGui.QLabel(EventResultSetupDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout.addWidget(self.lblSex, 12, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(EventResultSetupDialog)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 12, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(141, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 12, 2, 1, 2)
        self.lblAge = QtGui.QLabel(EventResultSetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 13, 0, 1, 1)
        self.frmAge = QtGui.QFrame(EventResultSetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self.hboxlayout = QtGui.QHBoxLayout(self.frmAge)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.hboxlayout.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.hboxlayout.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.hboxlayout.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.hboxlayout.addWidget(self.lblAgeYears)
        spacerItem3 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem3)
        self.gridLayout.addWidget(self.frmAge, 13, 1, 1, 2)
        self.lblSocStatusClass = QtGui.QLabel(EventResultSetupDialog)
        self.lblSocStatusClass.setObjectName(_fromUtf8("lblSocStatusClass"))
        self.gridLayout.addWidget(self.lblSocStatusClass, 14, 0, 1, 1)
        self.lblSocStatusType = QtGui.QLabel(EventResultSetupDialog)
        self.lblSocStatusType.setObjectName(_fromUtf8("lblSocStatusType"))
        self.gridLayout.addWidget(self.lblSocStatusType, 15, 0, 1, 1)
        self.chkAddress = QtGui.QCheckBox(EventResultSetupDialog)
        self.chkAddress.setObjectName(_fromUtf8("chkAddress"))
        self.gridLayout.addWidget(self.chkAddress, 16, 1, 1, 2)
        self.chkArea = QtGui.QCheckBox(EventResultSetupDialog)
        self.chkArea.setEnabled(False)
        self.chkArea.setObjectName(_fromUtf8("chkArea"))
        self.gridLayout.addWidget(self.chkArea, 17, 0, 1, 1)
        self.chkClientAddress = QtGui.QCheckBox(EventResultSetupDialog)
        self.chkClientAddress.setEnabled(False)
        self.chkClientAddress.setObjectName(_fromUtf8("chkClientAddress"))
        self.gridLayout.addWidget(self.chkClientAddress, 18, 0, 1, 1)
        self.cmbAddressType = QtGui.QComboBox(EventResultSetupDialog)
        self.cmbAddressType.setEnabled(False)
        self.cmbAddressType.setObjectName(_fromUtf8("cmbAddressType"))
        self.cmbAddressType.addItem(_fromUtf8(""))
        self.cmbAddressType.addItem(_fromUtf8(""))
        self.cmbAddressType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAddressType, 19, 0, 1, 1)
        self.pnlHomeAddress = QtGui.QWidget(EventResultSetupDialog)
        self.pnlHomeAddress.setEnabled(True)
        self.pnlHomeAddress.setObjectName(_fromUtf8("pnlHomeAddress"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.pnlHomeAddress)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblAddressHouse = QtGui.QLabel(self.pnlHomeAddress)
        self.lblAddressHouse.setEnabled(False)
        self.lblAddressHouse.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAddressHouse.setObjectName(_fromUtf8("lblAddressHouse"))
        self.horizontalLayout.addWidget(self.lblAddressHouse)
        self.edtAddressHouse = QtGui.QLineEdit(self.pnlHomeAddress)
        self.edtAddressHouse.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAddressHouse.sizePolicy().hasHeightForWidth())
        self.edtAddressHouse.setSizePolicy(sizePolicy)
        self.edtAddressHouse.setObjectName(_fromUtf8("edtAddressHouse"))
        self.horizontalLayout.addWidget(self.edtAddressHouse)
        self.lblAddressCorpus = QtGui.QLabel(self.pnlHomeAddress)
        self.lblAddressCorpus.setEnabled(False)
        self.lblAddressCorpus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAddressCorpus.setObjectName(_fromUtf8("lblAddressCorpus"))
        self.horizontalLayout.addWidget(self.lblAddressCorpus)
        self.edtAddressCorpus = QtGui.QLineEdit(self.pnlHomeAddress)
        self.edtAddressCorpus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAddressCorpus.sizePolicy().hasHeightForWidth())
        self.edtAddressCorpus.setSizePolicy(sizePolicy)
        self.edtAddressCorpus.setObjectName(_fromUtf8("edtAddressCorpus"))
        self.horizontalLayout.addWidget(self.edtAddressCorpus)
        self.lblAddressFlat = QtGui.QLabel(self.pnlHomeAddress)
        self.lblAddressFlat.setEnabled(False)
        self.lblAddressFlat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAddressFlat.setObjectName(_fromUtf8("lblAddressFlat"))
        self.horizontalLayout.addWidget(self.lblAddressFlat)
        self.edtAddressFlat = QtGui.QLineEdit(self.pnlHomeAddress)
        self.edtAddressFlat.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAddressFlat.sizePolicy().hasHeightForWidth())
        self.edtAddressFlat.setSizePolicy(sizePolicy)
        self.edtAddressFlat.setObjectName(_fromUtf8("edtAddressFlat"))
        self.horizontalLayout.addWidget(self.edtAddressFlat)
        self.gridLayout.addWidget(self.pnlHomeAddress, 21, 1, 1, 1)
        self.lblMKB = QtGui.QLabel(EventResultSetupDialog)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.gridLayout.addWidget(self.lblMKB, 22, 0, 1, 1)
        self.frmMKB = QtGui.QFrame(EventResultSetupDialog)
        self.frmMKB.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMKB.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMKB.setObjectName(_fromUtf8("frmMKB"))
        self.gridlayout = QtGui.QGridLayout(self.frmMKB)
        self.gridlayout.setMargin(0)
        self.gridlayout.setHorizontalSpacing(4)
        self.gridlayout.setVerticalSpacing(0)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.cmbMKBFilter = QtGui.QComboBox(self.frmMKB)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbMKBFilter, 0, 0, 1, 1)
        self.edtMKBFrom = CICDCodeEdit(self.frmMKB)
        self.edtMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.gridlayout.addWidget(self.edtMKBFrom, 0, 1, 1, 1)
        self.edtMKBTo = CICDCodeEdit(self.frmMKB)
        self.edtMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.gridlayout.addWidget(self.edtMKBTo, 0, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem4, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.frmMKB, 22, 1, 1, 3)
        self.lblMKBEx = QtGui.QLabel(EventResultSetupDialog)
        self.lblMKBEx.setObjectName(_fromUtf8("lblMKBEx"))
        self.gridLayout.addWidget(self.lblMKBEx, 23, 0, 1, 1)
        self.frmMKBEx = QtGui.QFrame(EventResultSetupDialog)
        self.frmMKBEx.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMKBEx.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMKBEx.setObjectName(_fromUtf8("frmMKBEx"))
        self.gridlayout1 = QtGui.QGridLayout(self.frmMKBEx)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setHorizontalSpacing(4)
        self.gridlayout1.setVerticalSpacing(0)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.cmbMKBExFilter = QtGui.QComboBox(self.frmMKBEx)
        self.cmbMKBExFilter.setObjectName(_fromUtf8("cmbMKBExFilter"))
        self.cmbMKBExFilter.addItem(_fromUtf8(""))
        self.cmbMKBExFilter.addItem(_fromUtf8(""))
        self.gridlayout1.addWidget(self.cmbMKBExFilter, 0, 0, 1, 1)
        self.edtMKBExFrom = CICDCodeEdit(self.frmMKBEx)
        self.edtMKBExFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBExFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBExFrom.setSizePolicy(sizePolicy)
        self.edtMKBExFrom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBExFrom.setMaxLength(6)
        self.edtMKBExFrom.setObjectName(_fromUtf8("edtMKBExFrom"))
        self.gridlayout1.addWidget(self.edtMKBExFrom, 0, 1, 1, 1)
        self.edtMKBExTo = CICDCodeEdit(self.frmMKBEx)
        self.edtMKBExTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBExTo.sizePolicy().hasHeightForWidth())
        self.edtMKBExTo.setSizePolicy(sizePolicy)
        self.edtMKBExTo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBExTo.setMaxLength(6)
        self.edtMKBExTo.setObjectName(_fromUtf8("edtMKBExTo"))
        self.gridlayout1.addWidget(self.edtMKBExTo, 0, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem5, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.frmMKBEx, 23, 1, 1, 3)
        self.chkVisitResult = QtGui.QCheckBox(EventResultSetupDialog)
        self.chkVisitResult.setObjectName(_fromUtf8("chkVisitResult"))
        self.gridLayout.addWidget(self.chkVisitResult, 24, 0, 1, 2)
        self.lblAdditionalGraphs = QtGui.QLabel(EventResultSetupDialog)
        self.lblAdditionalGraphs.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAdditionalGraphs.setObjectName(_fromUtf8("lblAdditionalGraphs"))
        self.gridLayout.addWidget(self.lblAdditionalGraphs, 25, 0, 1, 1)
        self.chkSocStatus = QtGui.QCheckBox(EventResultSetupDialog)
        self.chkSocStatus.setObjectName(_fromUtf8("chkSocStatus"))
        self.gridLayout.addWidget(self.chkSocStatus, 26, 0, 1, 1)
        self.chkPolicy = QtGui.QCheckBox(EventResultSetupDialog)
        self.chkPolicy.setObjectName(_fromUtf8("chkPolicy"))
        self.gridLayout.addWidget(self.chkPolicy, 26, 1, 1, 1)
        self.chkSnils = QtGui.QCheckBox(EventResultSetupDialog)
        self.chkSnils.setObjectName(_fromUtf8("chkSnils"))
        self.gridLayout.addWidget(self.chkSnils, 26, 2, 1, 1)
        self.chkWork = QtGui.QCheckBox(EventResultSetupDialog)
        self.chkWork.setObjectName(_fromUtf8("chkWork"))
        self.gridLayout.addWidget(self.chkWork, 27, 0, 1, 1)
        self.chkAddionalAddress = QtGui.QCheckBox(EventResultSetupDialog)
        self.chkAddionalAddress.setChecked(True)
        self.chkAddionalAddress.setObjectName(_fromUtf8("chkAddionalAddress"))
        self.gridLayout.addWidget(self.chkAddionalAddress, 27, 1, 1, 1)
        self.chkDocument = QtGui.QCheckBox(EventResultSetupDialog)
        self.chkDocument.setObjectName(_fromUtf8("chkDocument"))
        self.gridLayout.addWidget(self.chkDocument, 28, 0, 1, 2)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 29, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(EventResultSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 30, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(EventResultSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 4, 1, 1, 4)
        self.cmbPerson = CPersonComboBoxEx(EventResultSetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 6, 1, 1, 4)
        self.cmbWorkOrganisation = COrgComboBox(EventResultSetupDialog)
        self.cmbWorkOrganisation.setObjectName(_fromUtf8("cmbWorkOrganisation"))
        self.gridLayout.addWidget(self.cmbWorkOrganisation, 8, 1, 1, 3)
        self.cmbEventPurpose = CRBComboBox(EventResultSetupDialog)
        self.cmbEventPurpose.setObjectName(_fromUtf8("cmbEventPurpose"))
        self.gridLayout.addWidget(self.cmbEventPurpose, 2, 1, 1, 4)
        self.cmbResult = CResultComboBox(EventResultSetupDialog)
        self.cmbResult.setObjectName(_fromUtf8("cmbResult"))
        self.gridLayout.addWidget(self.cmbResult, 9, 1, 1, 4)
        self.cmbPrimary = QtGui.QComboBox(EventResultSetupDialog)
        self.cmbPrimary.setObjectName(_fromUtf8("cmbPrimary"))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.setItemText(0, _fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.cmbPrimary.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbPrimary, 10, 1, 1, 4)
        self.cmbOrder = QtGui.QComboBox(EventResultSetupDialog)
        self.cmbOrder.setObjectName(_fromUtf8("cmbOrder"))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.setItemText(0, _fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbOrder, 11, 1, 1, 4)
        self.cmbSocStatusClass = CRBComboBox(EventResultSetupDialog)
        self.cmbSocStatusClass.setObjectName(_fromUtf8("cmbSocStatusClass"))
        self.gridLayout.addWidget(self.cmbSocStatusClass, 14, 1, 1, 4)
        self.cmbSocStatusType = CRBComboBox(EventResultSetupDialog)
        self.cmbSocStatusType.setObjectName(_fromUtf8("cmbSocStatusType"))
        self.gridLayout.addWidget(self.cmbSocStatusType, 15, 1, 1, 4)
        self.cmbArea = COrgStructureComboBox(EventResultSetupDialog)
        self.cmbArea.setEnabled(False)
        self.cmbArea.setObjectName(_fromUtf8("cmbArea"))
        self.gridLayout.addWidget(self.cmbArea, 17, 1, 1, 4)
        self.cmbClientAddressType = QtGui.QComboBox(EventResultSetupDialog)
        self.cmbClientAddressType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbClientAddressType.sizePolicy().hasHeightForWidth())
        self.cmbClientAddressType.setSizePolicy(sizePolicy)
        self.cmbClientAddressType.setObjectName(_fromUtf8("cmbClientAddressType"))
        self.cmbClientAddressType.addItem(_fromUtf8(""))
        self.cmbClientAddressType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbClientAddressType, 18, 1, 1, 4)
        self.cmbClientAddressCity = CAllSelectableKLADRComboBox(EventResultSetupDialog)
        self.cmbClientAddressCity.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbClientAddressCity.sizePolicy().hasHeightForWidth())
        self.cmbClientAddressCity.setSizePolicy(sizePolicy)
        self.cmbClientAddressCity.setObjectName(_fromUtf8("cmbClientAddressCity"))
        self.gridLayout.addWidget(self.cmbClientAddressCity, 19, 1, 1, 4)
        self.cmbClientAddressStreet = CStreetComboBox(EventResultSetupDialog)
        self.cmbClientAddressStreet.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbClientAddressStreet.sizePolicy().hasHeightForWidth())
        self.cmbClientAddressStreet.setSizePolicy(sizePolicy)
        self.cmbClientAddressStreet.setObjectName(_fromUtf8("cmbClientAddressStreet"))
        self.gridLayout.addWidget(self.cmbClientAddressStreet, 20, 1, 1, 4)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblEventPurpose.setBuddy(self.cmbEventPurpose)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblWorkOrganisation.setBuddy(self.cmbWorkOrganisation)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblAddressHouse.setBuddy(self.edtAddressHouse)
        self.lblAddressCorpus.setBuddy(self.edtAddressCorpus)
        self.lblAddressFlat.setBuddy(self.edtAddressFlat)
        self.lblMKB.setBuddy(self.cmbMKBFilter)
        self.lblMKBEx.setBuddy(self.cmbMKBExFilter)

        self.retranslateUi(EventResultSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), EventResultSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), EventResultSetupDialog.reject)
        QtCore.QObject.connect(self.chkArea, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbArea.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(EventResultSetupDialog)
        EventResultSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        EventResultSetupDialog.setTabOrder(self.edtEndDate, self.cmbEventPurpose)
        EventResultSetupDialog.setTabOrder(self.cmbEventPurpose, self.cmbOrgStructure)
        EventResultSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbPerson)
        EventResultSetupDialog.setTabOrder(self.cmbPerson, self.chkPersonDetail)
        EventResultSetupDialog.setTabOrder(self.chkPersonDetail, self.cmbWorkOrganisation)
        EventResultSetupDialog.setTabOrder(self.cmbWorkOrganisation, self.btnSelectWorkOrganisation)
        EventResultSetupDialog.setTabOrder(self.btnSelectWorkOrganisation, self.cmbResult)
        EventResultSetupDialog.setTabOrder(self.cmbResult, self.cmbPrimary)
        EventResultSetupDialog.setTabOrder(self.cmbPrimary, self.cmbOrder)
        EventResultSetupDialog.setTabOrder(self.cmbOrder, self.cmbSex)
        EventResultSetupDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        EventResultSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        EventResultSetupDialog.setTabOrder(self.edtAgeTo, self.cmbSocStatusClass)
        EventResultSetupDialog.setTabOrder(self.cmbSocStatusClass, self.cmbSocStatusType)
        EventResultSetupDialog.setTabOrder(self.cmbSocStatusType, self.chkAddress)
        EventResultSetupDialog.setTabOrder(self.chkAddress, self.chkArea)
        EventResultSetupDialog.setTabOrder(self.chkArea, self.cmbArea)
        EventResultSetupDialog.setTabOrder(self.cmbArea, self.chkClientAddress)
        EventResultSetupDialog.setTabOrder(self.chkClientAddress, self.cmbClientAddressType)
        EventResultSetupDialog.setTabOrder(self.cmbClientAddressType, self.cmbAddressType)
        EventResultSetupDialog.setTabOrder(self.cmbAddressType, self.cmbClientAddressCity)
        EventResultSetupDialog.setTabOrder(self.cmbClientAddressCity, self.cmbClientAddressStreet)
        EventResultSetupDialog.setTabOrder(self.cmbClientAddressStreet, self.edtAddressHouse)
        EventResultSetupDialog.setTabOrder(self.edtAddressHouse, self.edtAddressCorpus)
        EventResultSetupDialog.setTabOrder(self.edtAddressCorpus, self.edtAddressFlat)
        EventResultSetupDialog.setTabOrder(self.edtAddressFlat, self.cmbMKBFilter)
        EventResultSetupDialog.setTabOrder(self.cmbMKBFilter, self.edtMKBFrom)
        EventResultSetupDialog.setTabOrder(self.edtMKBFrom, self.edtMKBTo)
        EventResultSetupDialog.setTabOrder(self.edtMKBTo, self.cmbMKBExFilter)
        EventResultSetupDialog.setTabOrder(self.cmbMKBExFilter, self.edtMKBExFrom)
        EventResultSetupDialog.setTabOrder(self.edtMKBExFrom, self.edtMKBExTo)
        EventResultSetupDialog.setTabOrder(self.edtMKBExTo, self.chkVisitResult)
        EventResultSetupDialog.setTabOrder(self.chkVisitResult, self.chkSocStatus)
        EventResultSetupDialog.setTabOrder(self.chkSocStatus, self.chkPolicy)
        EventResultSetupDialog.setTabOrder(self.chkPolicy, self.chkWork)
        EventResultSetupDialog.setTabOrder(self.chkWork, self.chkAddionalAddress)
        EventResultSetupDialog.setTabOrder(self.chkAddionalAddress, self.chkDocument)
        EventResultSetupDialog.setTabOrder(self.chkDocument, self.buttonBox)

    def retranslateUi(self, EventResultSetupDialog):
        EventResultSetupDialog.setWindowTitle(_translate("EventResultSetupDialog", "параметры отчёта", None))
        self.lblBegDate.setText(_translate("EventResultSetupDialog", "Дата &начала периода", None))
        self.lblEndDate.setText(_translate("EventResultSetupDialog", "Дата &окончания периода", None))
        self.lblEventPurpose.setText(_translate("EventResultSetupDialog", "&Назначение обращения", None))
        self.btnEventTypeList.setText(_translate("EventResultSetupDialog", "Тип обращения", None))
        self.lblEventTypeList.setText(_translate("EventResultSetupDialog", "не задано", None))
        self.lblOrgStructure.setText(_translate("EventResultSetupDialog", "&Подразделение", None))
        self.btnSpecialityList.setText(_translate("EventResultSetupDialog", "Специальность", None))
        self.lblSpecialityList.setText(_translate("EventResultSetupDialog", "не задано", None))
        self.lblPerson.setText(_translate("EventResultSetupDialog", "&Врач", None))
        self.chkPersonDetail.setText(_translate("EventResultSetupDialog", "Детализировать по врачам", None))
        self.lblWorkOrganisation.setText(_translate("EventResultSetupDialog", "Занятость", None))
        self.btnSelectWorkOrganisation.setText(_translate("EventResultSetupDialog", "...", None))
        self.lblResult.setText(_translate("EventResultSetupDialog", "Результат", None))
        self.lblPrimary.setText(_translate("EventResultSetupDialog", "Первичность", None))
        self.lblOrder.setText(_translate("EventResultSetupDialog", "Порядок", None))
        self.lblSex.setText(_translate("EventResultSetupDialog", "По&л", None))
        self.cmbSex.setItemText(1, _translate("EventResultSetupDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("EventResultSetupDialog", "Ж", None))
        self.lblAge.setText(_translate("EventResultSetupDialog", "Во&зраст с", None))
        self.lblAgeTo.setText(_translate("EventResultSetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("EventResultSetupDialog", "лет", None))
        self.lblSocStatusClass.setText(_translate("EventResultSetupDialog", "Соц.статус класс", None))
        self.lblSocStatusType.setText(_translate("EventResultSetupDialog", "Соц.статус тип", None))
        self.chkAddress.setText(_translate("EventResultSetupDialog", "Учитывать адрес", None))
        self.chkArea.setText(_translate("EventResultSetupDialog", "Те&рритории обслуживания", None))
        self.chkClientAddress.setText(_translate("EventResultSetupDialog", "Пациента", None))
        self.cmbAddressType.setItemText(0, _translate("EventResultSetupDialog", "Точный адрес", None))
        self.cmbAddressType.setItemText(1, _translate("EventResultSetupDialog", "Иногородний", None))
        self.cmbAddressType.setItemText(2, _translate("EventResultSetupDialog", "Иностранец", None))
        self.lblAddressHouse.setText(_translate("EventResultSetupDialog", "Дом", None))
        self.lblAddressCorpus.setText(_translate("EventResultSetupDialog", "Корп", None))
        self.lblAddressFlat.setText(_translate("EventResultSetupDialog", "Кв", None))
        self.lblMKB.setText(_translate("EventResultSetupDialog", "Коды диагнозов по &МКБ", None))
        self.cmbMKBFilter.setItemText(0, _translate("EventResultSetupDialog", "Игнор.", None))
        self.cmbMKBFilter.setItemText(1, _translate("EventResultSetupDialog", "Интервал", None))
        self.edtMKBFrom.setInputMask(_translate("EventResultSetupDialog", "a00.00", None))
        self.edtMKBFrom.setText(_translate("EventResultSetupDialog", "A.", None))
        self.edtMKBTo.setInputMask(_translate("EventResultSetupDialog", "a00.00", None))
        self.edtMKBTo.setText(_translate("EventResultSetupDialog", "Z99.9", None))
        self.lblMKBEx.setText(_translate("EventResultSetupDialog", "В сочетании с", None))
        self.cmbMKBExFilter.setItemText(0, _translate("EventResultSetupDialog", "Игнор.", None))
        self.cmbMKBExFilter.setItemText(1, _translate("EventResultSetupDialog", "Интервал", None))
        self.edtMKBExFrom.setInputMask(_translate("EventResultSetupDialog", "a00.00", None))
        self.edtMKBExFrom.setText(_translate("EventResultSetupDialog", "A.", None))
        self.edtMKBExTo.setInputMask(_translate("EventResultSetupDialog", "a00.00", None))
        self.edtMKBExTo.setText(_translate("EventResultSetupDialog", "Z99.9", None))
        self.chkVisitResult.setText(_translate("EventResultSetupDialog", "Детализировать по результатам осмотров", None))
        self.lblAdditionalGraphs.setText(_translate("EventResultSetupDialog", "Дополнительные графы", None))
        self.chkSocStatus.setText(_translate("EventResultSetupDialog", "Социальный статус", None))
        self.chkPolicy.setText(_translate("EventResultSetupDialog", "Полис", None))
        self.chkSnils.setText(_translate("EventResultSetupDialog", "Снилс", None))
        self.chkWork.setText(_translate("EventResultSetupDialog", "Занятость", None))
        self.chkAddionalAddress.setText(_translate("EventResultSetupDialog", "Адрес", None))
        self.chkDocument.setText(_translate("EventResultSetupDialog", "Документ удостоверяющий личность", None))
        self.cmbPrimary.setItemText(1, _translate("EventResultSetupDialog", "Первичный", None))
        self.cmbPrimary.setItemText(2, _translate("EventResultSetupDialog", "Повторный", None))
        self.cmbPrimary.setItemText(3, _translate("EventResultSetupDialog", "Актив", None))
        self.cmbOrder.setItemText(1, _translate("EventResultSetupDialog", "Плановый", None))
        self.cmbOrder.setItemText(2, _translate("EventResultSetupDialog", "Экстренный", None))
        self.cmbOrder.setItemText(3, _translate("EventResultSetupDialog", "Самотёком", None))
        self.cmbOrder.setItemText(4, _translate("EventResultSetupDialog", "Принудительный", None))
        self.cmbOrder.setItemText(5, _translate("EventResultSetupDialog", "Внутренний перевод", None))
        self.cmbOrder.setItemText(6, _translate("EventResultSetupDialog", "Неотложная", None))
        self.cmbClientAddressType.setItemText(0, _translate("EventResultSetupDialog", "Регистрации", None))
        self.cmbClientAddressType.setItemText(1, _translate("EventResultSetupDialog", "Проживания", None))

from KLADR.kladrComboxes import CAllSelectableKLADRComboBox, CStreetComboBox
from Orgs.OrgComboBox import COrgComboBox, CResultComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEdit
from library.crbcombobox import CRBComboBox
