# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\Reports\EconomicAnalisysSetupDialogEx.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EconomicAnalisysSetupDialogEx(object):
    def setupUi(self, EconomicAnalisysSetupDialogEx):
        EconomicAnalisysSetupDialogEx.setObjectName(_fromUtf8("EconomicAnalisysSetupDialogEx"))
        EconomicAnalisysSetupDialogEx.setWindowModality(QtCore.Qt.ApplicationModal)
        EconomicAnalisysSetupDialogEx.resize(550, 675)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EconomicAnalisysSetupDialogEx.sizePolicy().hasHeightForWidth())
        EconomicAnalisysSetupDialogEx.setSizePolicy(sizePolicy)
        EconomicAnalisysSetupDialogEx.setMinimumSize(QtCore.QSize(475, 675))
        EconomicAnalisysSetupDialogEx.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(EconomicAnalisysSetupDialogEx)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(EconomicAnalisysSetupDialogEx)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 33, 2, 1, 2)
        self.scrollArea = QtGui.QScrollArea(EconomicAnalisysSetupDialogEx)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Sunken)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 525, 937))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 37, 1, 1, 1)
        self.lblSpeciality = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout_4.addWidget(self.lblSpeciality, 7, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout_4.addWidget(self.lblPerson, 8, 0, 1, 1)
        self.lblFinance = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout_4.addWidget(self.lblFinance, 10, 0, 1, 1)
        self.edtFilterClientId = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterClientId.sizePolicy().hasHeightForWidth())
        self.edtFilterClientId.setSizePolicy(sizePolicy)
        self.edtFilterClientId.setObjectName(_fromUtf8("edtFilterClientId"))
        self.gridLayout_4.addWidget(self.edtFilterClientId, 28, 1, 1, 4)
        self.lblOrgStructure = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout_4.addWidget(self.lblOrgStructure, 6, 0, 1, 1)
        self.lblBegDate = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout_4.addWidget(self.lblBegDate, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(86, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 29, 5, 1, 1)
        self.chkDetail = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkDetail.setObjectName(_fromUtf8("chkDetail"))
        self.gridLayout_4.addWidget(self.chkDetail, 33, 1, 1, 5)
        self.cbCashPayments = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.cbCashPayments.setObjectName(_fromUtf8("cbCashPayments"))
        self.gridLayout_4.addWidget(self.cbCashPayments, 35, 1, 1, 5)
        self.chkMedicalTypeTotals = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkMedicalTypeTotals.setObjectName(_fromUtf8("chkMedicalTypeTotals"))
        self.gridLayout_4.addWidget(self.chkMedicalTypeTotals, 36, 1, 1, 5)
        self.btnFindClientInfo = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.btnFindClientInfo.setObjectName(_fromUtf8("btnFindClientInfo"))
        self.gridLayout_4.addWidget(self.btnFindClientInfo, 28, 5, 1, 1)
        self.iswomencheckedage = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.iswomencheckedage.setObjectName(_fromUtf8("iswomencheckedage"))
        self.gridLayout_4.addWidget(self.iswomencheckedage, 22, 0, 1, 1)
        self.cmbContract = CARMSIndependentContractTreeFindComboBox(self.scrollAreaWidgetContents)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.gridLayout_4.addWidget(self.cmbContract, 11, 1, 1, 5)
        self.cmbRazrNas = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbRazrNas.setObjectName(_fromUtf8("cmbRazrNas"))
        self.cmbRazrNas.addItem(_fromUtf8(""))
        self.cmbRazrNas.addItem(_fromUtf8(""))
        self.cmbRazrNas.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbRazrNas, 13, 1, 1, 5)
        self.cmbOrgStructure = COrgStructureComboBox(self.scrollAreaWidgetContents)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout_4.addWidget(self.cmbOrgStructure, 6, 1, 1, 5)
        self.cmbStepECO = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbStepECO.setObjectName(_fromUtf8("cmbStepECO"))
        self.gridLayout_4.addWidget(self.cmbStepECO, 19, 1, 1, 5)
        self.cmbSpeciality = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout_4.addWidget(self.cmbSpeciality, 7, 1, 1, 5)
        self.cmbtypePay = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbtypePay.setObjectName(_fromUtf8("cmbtypePay"))
        self.cmbtypePay.addItem(_fromUtf8(""))
        self.cmbtypePay.addItem(_fromUtf8(""))
        self.cmbtypePay.addItem(_fromUtf8(""))
        self.cmbtypePay.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbtypePay, 14, 1, 1, 5)
        self.cmbVidPom = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbVidPom.setObjectName(_fromUtf8("cmbVidPom"))
        self.gridLayout_4.addWidget(self.cmbVidPom, 12, 1, 1, 5)
        self.cmbPurpose = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbPurpose.setObjectName(_fromUtf8("cmbPurpose"))
        self.gridLayout_4.addWidget(self.cmbPurpose, 17, 1, 1, 5)
        self.chkPersonBySnils = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkPersonBySnils.setEnabled(False)
        self.chkPersonBySnils.setObjectName(_fromUtf8("chkPersonBySnils"))
        self.gridLayout_4.addWidget(self.chkPersonBySnils, 9, 1, 1, 5)
        self.cmbEventType = CRBMultivalueComboBox(self.scrollAreaWidgetContents)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout_4.addWidget(self.cmbEventType, 18, 1, 1, 5)
        self.ageHolder = QtGui.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ageHolder.sizePolicy().hasHeightForWidth())
        self.ageHolder.setSizePolicy(sizePolicy)
        self.ageHolder.setMinimumSize(QtCore.QSize(0, 20))
        self.ageHolder.setObjectName(_fromUtf8("ageHolder"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.ageHolder)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.ageHolder)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.spnManAgeBeg = QtGui.QSpinBox(self.ageHolder)
        self.spnManAgeBeg.setMinimumSize(QtCore.QSize(50, 0))
        self.spnManAgeBeg.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spnManAgeBeg.setObjectName(_fromUtf8("spnManAgeBeg"))
        self.horizontalLayout.addWidget(self.spnManAgeBeg)
        self.cmbMenBegAgeUnit = QtGui.QComboBox(self.ageHolder)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMenBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbMenBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbMenBegAgeUnit.setObjectName(_fromUtf8("cmbMenBegAgeUnit"))
        self.cmbMenBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbMenBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbMenBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbMenBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbMenBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbMenBegAgeUnit.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbMenBegAgeUnit)
        self.lblAge2 = QtGui.QLabel(self.ageHolder)
        self.lblAge2.setStyleSheet(_fromUtf8(""))
        self.lblAge2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAge2.setObjectName(_fromUtf8("lblAge2"))
        self.horizontalLayout.addWidget(self.lblAge2)
        self.spnManAgeEnd = QtGui.QSpinBox(self.ageHolder)
        self.spnManAgeEnd.setMinimumSize(QtCore.QSize(50, 0))
        self.spnManAgeEnd.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spnManAgeEnd.setMaximum(150)
        self.spnManAgeEnd.setProperty("value", 150)
        self.spnManAgeEnd.setObjectName(_fromUtf8("spnManAgeEnd"))
        self.horizontalLayout.addWidget(self.spnManAgeEnd)
        self.cmbMenEndAgeUnit = QtGui.QComboBox(self.ageHolder)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMenEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbMenEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbMenEndAgeUnit.setObjectName(_fromUtf8("cmbMenEndAgeUnit"))
        self.cmbMenEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbMenEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbMenEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbMenEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbMenEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbMenEndAgeUnit.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbMenEndAgeUnit)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_4.addWidget(self.ageHolder, 21, 1, 1, 5)
        self.widget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget.setMinimumSize(QtCore.QSize(0, 20))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spnWomanAgeBeg = QtGui.QSpinBox(self.widget)
        self.spnWomanAgeBeg.setMinimumSize(QtCore.QSize(50, 0))
        self.spnWomanAgeBeg.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spnWomanAgeBeg.setObjectName(_fromUtf8("spnWomanAgeBeg"))
        self.horizontalLayout_2.addWidget(self.spnWomanAgeBeg)
        self.cmbWomenBegAgeUnit = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbWomenBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbWomenBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbWomenBegAgeUnit.setObjectName(_fromUtf8("cmbWomenBegAgeUnit"))
        self.cmbWomenBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbWomenBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbWomenBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbWomenBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbWomenBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbWomenBegAgeUnit.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmbWomenBegAgeUnit)
        self.lblAge2_2 = QtGui.QLabel(self.widget)
        self.lblAge2_2.setStyleSheet(_fromUtf8(""))
        self.lblAge2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAge2_2.setObjectName(_fromUtf8("lblAge2_2"))
        self.horizontalLayout_2.addWidget(self.lblAge2_2)
        self.spnWomanAgeEnd = QtGui.QSpinBox(self.widget)
        self.spnWomanAgeEnd.setMinimumSize(QtCore.QSize(50, 0))
        self.spnWomanAgeEnd.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spnWomanAgeEnd.setMaximum(150)
        self.spnWomanAgeEnd.setProperty("value", 150)
        self.spnWomanAgeEnd.setObjectName(_fromUtf8("spnWomanAgeEnd"))
        self.horizontalLayout_2.addWidget(self.spnWomanAgeEnd)
        self.cmbWomenEndAgeUnit = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbWomenEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbWomenEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbWomenEndAgeUnit.setObjectName(_fromUtf8("cmbWomenEndAgeUnit"))
        self.cmbWomenEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbWomenEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbWomenEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbWomenEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbWomenEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbWomenEndAgeUnit.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmbWomenEndAgeUnit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout_4.addWidget(self.widget, 22, 1, 1, 5)
        self.grpdatetype = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpdatetype.sizePolicy().hasHeightForWidth())
        self.grpdatetype.setSizePolicy(sizePolicy)
        self.grpdatetype.setFlat(False)
        self.grpdatetype.setObjectName(_fromUtf8("grpdatetype"))
        self.verticalLayout = QtGui.QVBoxLayout(self.grpdatetype)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rbDatalech = QtGui.QRadioButton(self.grpdatetype)
        self.rbDatalech.setChecked(True)
        self.rbDatalech.setObjectName(_fromUtf8("rbDatalech"))
        self.verticalLayout.addWidget(self.rbDatalech)
        self.rbSchetf = QtGui.QRadioButton(self.grpdatetype)
        self.rbSchetf.setObjectName(_fromUtf8("rbSchetf"))
        self.verticalLayout.addWidget(self.rbSchetf)
        self.rbNomer = QtGui.QRadioButton(self.grpdatetype)
        self.rbNomer.setObjectName(_fromUtf8("rbNomer"))
        self.verticalLayout.addWidget(self.rbNomer)
        self.rbNomer.raise_()
        self.rbDatalech.raise_()
        self.rbSchetf.raise_()
        self.gridLayout_4.addWidget(self.grpdatetype, 5, 0, 1, 6)
        self.cmbScheta = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbScheta.setObjectName(_fromUtf8("cmbScheta"))
        self.cmbScheta.addItem(_fromUtf8(""))
        self.cmbScheta.addItem(_fromUtf8(""))
        self.cmbScheta.addItem(_fromUtf8(""))
        self.cmbScheta.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbScheta, 4, 1, 1, 5)
        self.ismancheckedage = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.ismancheckedage.setObjectName(_fromUtf8("ismancheckedage"))
        self.gridLayout_4.addWidget(self.ismancheckedage, 21, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 5, 1, 1)
        self.edtBegTime = QtGui.QTimeEdit(self.scrollAreaWidgetContents)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.gridLayout_4.addWidget(self.edtBegTime, 0, 3, 1, 2)
        self.lblPayer = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblPayer.setObjectName(_fromUtf8("lblPayer"))
        self.gridLayout_4.addWidget(self.lblPayer, 15, 0, 1, 1)
        self.lblStepECO = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblStepECO.setObjectName(_fromUtf8("lblStepECO"))
        self.gridLayout_4.addWidget(self.lblStepECO, 19, 0, 1, 1)
        self.lblPurpose = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblPurpose.setObjectName(_fromUtf8("lblPurpose"))
        self.gridLayout_4.addWidget(self.lblPurpose, 17, 0, 1, 1)
        self.lbltypePay = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lbltypePay.setObjectName(_fromUtf8("lbltypePay"))
        self.gridLayout_4.addWidget(self.lbltypePay, 14, 0, 1, 1)
        self.cmbNoscheta = CAccountComboBox(self.scrollAreaWidgetContents)
        self.cmbNoscheta.setObjectName(_fromUtf8("cmbNoscheta"))
        self.gridLayout_4.addWidget(self.cmbNoscheta, 2, 1, 1, 5)
        self.lblEndDate = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout_4.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.edtMKBTo = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtMKBTo.setEnabled(False)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.gridLayout_4.addWidget(self.edtMKBTo, 29, 2, 1, 3)
        self.edtEndTime = QtGui.QTimeEdit(self.scrollAreaWidgetContents)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.gridLayout_4.addWidget(self.edtEndTime, 1, 3, 1, 2)
        self.cmbAccountType = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbAccountType.setObjectName(_fromUtf8("cmbAccountType"))
        self.cmbAccountType.addItem(_fromUtf8(""))
        self.cmbAccountType.addItem(_fromUtf8(""))
        self.cmbAccountType.addItem(_fromUtf8(""))
        self.cmbAccountType.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cmbAccountType, 3, 1, 1, 5)
        self.lblEventType = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout_4.addWidget(self.lblEventType, 18, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 1, 5, 1, 1)
        self.lblScheta = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblScheta.setObjectName(_fromUtf8("lblScheta"))
        self.gridLayout_4.addWidget(self.lblScheta, 4, 0, 1, 1)
        self.lblVidPom = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblVidPom.setObjectName(_fromUtf8("lblVidPom"))
        self.gridLayout_4.addWidget(self.lblVidPom, 12, 0, 1, 1)
        self.lblContract = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.gridLayout_4.addWidget(self.lblContract, 11, 0, 1, 1)
        self.lblRazrNas = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblRazrNas.setObjectName(_fromUtf8("lblRazrNas"))
        self.gridLayout_4.addWidget(self.lblRazrNas, 13, 0, 1, 1)
        self.lblNoscheta = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblNoscheta.setObjectName(_fromUtf8("lblNoscheta"))
        self.gridLayout_4.addWidget(self.lblNoscheta, 2, 0, 1, 1)
        self.edtEndDate = CDateEdit(self.scrollAreaWidgetContents)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout_4.addWidget(self.edtEndDate, 1, 1, 1, 2)
        self.cmbDetailTo = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbDetailTo.setObjectName(_fromUtf8("cmbDetailTo"))
        self.gridLayout_4.addWidget(self.cmbDetailTo, 26, 1, 1, 5)
        self.cmbProfileBed = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbProfileBed.setObjectName(_fromUtf8("cmbProfileBed"))
        self.gridLayout_4.addWidget(self.cmbProfileBed, 25, 1, 1, 5)
        self.edtBegDate = CDateEdit(self.scrollAreaWidgetContents)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout_4.addWidget(self.edtBegDate, 0, 1, 1, 2)
        self.lblProfileBed = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblProfileBed.setObjectName(_fromUtf8("lblProfileBed"))
        self.gridLayout_4.addWidget(self.lblProfileBed, 25, 0, 1, 1)
        self.lblAccountType = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblAccountType.setObjectName(_fromUtf8("lblAccountType"))
        self.gridLayout_4.addWidget(self.lblAccountType, 3, 0, 1, 1)
        self.lblDetailTo = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblDetailTo.setObjectName(_fromUtf8("lblDetailTo"))
        self.gridLayout_4.addWidget(self.lblDetailTo, 26, 0, 1, 1)
        self.chkGroupByPersonSnils = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkGroupByPersonSnils.setObjectName(_fromUtf8("chkGroupByPersonSnils"))
        self.gridLayout_4.addWidget(self.chkGroupByPersonSnils, 27, 1, 1, 5)
        self.chkMKBFilter = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkMKBFilter.setObjectName(_fromUtf8("chkMKBFilter"))
        self.gridLayout_4.addWidget(self.chkMKBFilter, 29, 0, 1, 1)
        self.lblClient = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblClient.setObjectName(_fromUtf8("lblClient"))
        self.gridLayout_4.addWidget(self.lblClient, 28, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(self.scrollAreaWidgetContents)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout_4.addWidget(self.cmbPerson, 8, 1, 1, 5)
        self.edtMKBFrom = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.edtMKBFrom.setEnabled(False)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(90, 16777215))
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.gridLayout_4.addWidget(self.edtMKBFrom, 29, 1, 1, 1)
        self.cmbPayer = COrgIsPayer23ComboBox(self.scrollAreaWidgetContents)
        self.cmbPayer.setObjectName(_fromUtf8("cmbPayer"))
        self.gridLayout_4.addWidget(self.cmbPayer, 15, 1, 1, 5)
        self.cmbFinance = CRBComboBox(self.scrollAreaWidgetContents)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout_4.addWidget(self.cmbFinance, 10, 1, 1, 5)
        self.cbPrice = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.cbPrice.setObjectName(_fromUtf8("cbPrice"))
        self.gridLayout_4.addWidget(self.cbPrice, 30, 1, 1, 5)
        self.chkPrintAccNumber = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.chkPrintAccNumber.setObjectName(_fromUtf8("chkPrintAccNumber"))
        self.gridLayout_4.addWidget(self.chkPrintAccNumber, 34, 1, 1, 5)
        self.cbOnlyNotExposed = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.cbOnlyNotExposed.setObjectName(_fromUtf8("cbOnlyNotExposed"))
        self.gridLayout_4.addWidget(self.cbOnlyNotExposed, 31, 1, 1, 5)
        self.cbusl = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.cbusl.setObjectName(_fromUtf8("cbusl"))
        self.gridLayout_4.addWidget(self.cbusl, 32, 1, 1, 5)
        self.lblEventRelegateOrg = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblEventRelegateOrg.setObjectName(_fromUtf8("lblEventRelegateOrg"))
        self.gridLayout_4.addWidget(self.lblEventRelegateOrg, 16, 0, 1, 1)
        self.cmbEventRelegateOrg = COrgComboBoxEx(self.scrollAreaWidgetContents)
        self.cmbEventRelegateOrg.setObjectName(_fromUtf8("cmbEventRelegateOrg"))
        self.gridLayout_4.addWidget(self.cmbEventRelegateOrg, 16, 1, 1, 5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 19, 0, 7, 4)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblPayer.setBuddy(self.cmbPayer)
        self.lblPurpose.setBuddy(self.cmbPurpose)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblEventType.setBuddy(self.cmbEventType)
        self.lblScheta.setBuddy(self.cmbScheta)
        self.lblVidPom.setBuddy(self.cmbVidPom)
        self.lblContract.setBuddy(self.cmbOrgStructure)
        self.lblRazrNas.setBuddy(self.cmbRazrNas)
        self.lblNoscheta.setBuddy(self.cmbNoscheta)
        self.lblAccountType.setBuddy(self.cmbAccountType)

        self.retranslateUi(EconomicAnalisysSetupDialogEx)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), EconomicAnalisysSetupDialogEx.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), EconomicAnalisysSetupDialogEx.reject)
        QtCore.QObject.connect(self.rbDatalech, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cbOnlyNotExposed.setVisible)
        QtCore.QObject.connect(self.chkMKBFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtMKBFrom.setEnabled)
        QtCore.QObject.connect(self.chkMKBFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtMKBTo.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(EconomicAnalisysSetupDialogEx)
        EconomicAnalisysSetupDialogEx.setTabOrder(self.rbDatalech, self.rbSchetf)
        EconomicAnalisysSetupDialogEx.setTabOrder(self.rbSchetf, self.rbNomer)
        EconomicAnalisysSetupDialogEx.setTabOrder(self.rbNomer, self.buttonBox)

    def retranslateUi(self, EconomicAnalisysSetupDialogEx):
        EconomicAnalisysSetupDialogEx.setWindowTitle(_translate("EconomicAnalisysSetupDialogEx", "параметры отчёта", None))
        self.lblSpeciality.setText(_translate("EconomicAnalisysSetupDialogEx", "&Специальность", None))
        self.lblPerson.setText(_translate("EconomicAnalisysSetupDialogEx", "&Врач", None))
        self.lblFinance.setText(_translate("EconomicAnalisysSetupDialogEx", "Тип финансирования", None))
        self.lblOrgStructure.setText(_translate("EconomicAnalisysSetupDialogEx", "&Подразделение", None))
        self.lblBegDate.setText(_translate("EconomicAnalisysSetupDialogEx", "Дата &начала периода", None))
        self.chkDetail.setText(_translate("EconomicAnalisysSetupDialogEx", "&Детализировать по плательщикам", None))
        self.cbCashPayments.setText(_translate("EconomicAnalisysSetupDialogEx", "Оплата по кассовому аппарату", None))
        self.chkMedicalTypeTotals.setText(_translate("EconomicAnalisysSetupDialogEx", "С разбивкой по видам медицинской помощи", None))
        self.btnFindClientInfo.setText(_translate("EconomicAnalisysSetupDialogEx", "...", None))
        self.iswomencheckedage.setText(_translate("EconomicAnalisysSetupDialogEx", "Женщины", None))
        self.cmbRazrNas.setItemText(0, _translate("EconomicAnalisysSetupDialogEx", "Все", None))
        self.cmbRazrNas.setItemText(1, _translate("EconomicAnalisysSetupDialogEx", "Краевые", None))
        self.cmbRazrNas.setItemText(2, _translate("EconomicAnalisysSetupDialogEx", "Инокраевые", None))
        self.cmbSpeciality.setWhatsThis(_translate("EconomicAnalisysSetupDialogEx", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.cmbtypePay.setItemText(0, _translate("EconomicAnalisysSetupDialogEx", "Не задано", None))
        self.cmbtypePay.setItemText(1, _translate("EconomicAnalisysSetupDialogEx", "Наличная оплата", None))
        self.cmbtypePay.setItemText(2, _translate("EconomicAnalisysSetupDialogEx", "Электронная оплата", None))
        self.cmbtypePay.setItemText(3, _translate("EconomicAnalisysSetupDialogEx", "Не учитывать факт оплаты", None))
        self.chkPersonBySnils.setText(_translate("EconomicAnalisysSetupDialogEx", "искать по СНИЛС", None))
        self.label.setText(_translate("EconomicAnalisysSetupDialogEx", "с", None))
        self.cmbMenBegAgeUnit.setItemText(1, _translate("EconomicAnalisysSetupDialogEx", "Д", None))
        self.cmbMenBegAgeUnit.setItemText(2, _translate("EconomicAnalisysSetupDialogEx", "Н", None))
        self.cmbMenBegAgeUnit.setItemText(3, _translate("EconomicAnalisysSetupDialogEx", "М", None))
        self.cmbMenBegAgeUnit.setItemText(4, _translate("EconomicAnalisysSetupDialogEx", "Г", None))
        self.lblAge2.setText(_translate("EconomicAnalisysSetupDialogEx", "по", None))
        self.cmbMenEndAgeUnit.setItemText(1, _translate("EconomicAnalisysSetupDialogEx", "Д", None))
        self.cmbMenEndAgeUnit.setItemText(2, _translate("EconomicAnalisysSetupDialogEx", "Н", None))
        self.cmbMenEndAgeUnit.setItemText(3, _translate("EconomicAnalisysSetupDialogEx", "М", None))
        self.cmbMenEndAgeUnit.setItemText(4, _translate("EconomicAnalisysSetupDialogEx", "Г", None))
        self.label_2.setText(_translate("EconomicAnalisysSetupDialogEx", "с", None))
        self.cmbWomenBegAgeUnit.setItemText(1, _translate("EconomicAnalisysSetupDialogEx", "Д", None))
        self.cmbWomenBegAgeUnit.setItemText(2, _translate("EconomicAnalisysSetupDialogEx", "Н", None))
        self.cmbWomenBegAgeUnit.setItemText(3, _translate("EconomicAnalisysSetupDialogEx", "М", None))
        self.cmbWomenBegAgeUnit.setItemText(4, _translate("EconomicAnalisysSetupDialogEx", "Г", None))
        self.lblAge2_2.setText(_translate("EconomicAnalisysSetupDialogEx", "по", None))
        self.cmbWomenEndAgeUnit.setItemText(1, _translate("EconomicAnalisysSetupDialogEx", "Д", None))
        self.cmbWomenEndAgeUnit.setItemText(2, _translate("EconomicAnalisysSetupDialogEx", "Н", None))
        self.cmbWomenEndAgeUnit.setItemText(3, _translate("EconomicAnalisysSetupDialogEx", "М", None))
        self.cmbWomenEndAgeUnit.setItemText(4, _translate("EconomicAnalisysSetupDialogEx", "Г", None))
        self.grpdatetype.setTitle(_translate("EconomicAnalisysSetupDialogEx", "Формировать отчет по", None))
        self.rbDatalech.setText(_translate("EconomicAnalisysSetupDialogEx", "Дате окончания лечения", None))
        self.rbSchetf.setText(_translate("EconomicAnalisysSetupDialogEx", "Дате счет-фактуры", None))
        self.rbNomer.setText(_translate("EconomicAnalisysSetupDialogEx", "Номеру счета", None))
        self.cmbScheta.setItemText(0, _translate("EconomicAnalisysSetupDialogEx", "Все", None))
        self.cmbScheta.setItemText(1, _translate("EconomicAnalisysSetupDialogEx", "Представленные к оплате", None))
        self.cmbScheta.setItemText(2, _translate("EconomicAnalisysSetupDialogEx", "Подлежащие к оплате", None))
        self.cmbScheta.setItemText(3, _translate("EconomicAnalisysSetupDialogEx", "Возвращенные из СМО", None))
        self.ismancheckedage.setText(_translate("EconomicAnalisysSetupDialogEx", "Мужчины", None))
        self.lblPayer.setText(_translate("EconomicAnalisysSetupDialogEx", "Плательщик", None))
        self.lblStepECO.setText(_translate("EconomicAnalisysSetupDialogEx", "Этап ЭКО", None))
        self.lblPurpose.setText(_translate("EconomicAnalisysSetupDialogEx", "Назначение", None))
        self.lbltypePay.setText(_translate("EconomicAnalisysSetupDialogEx", "Тип оплаты", None))
        self.lblEndDate.setText(_translate("EconomicAnalisysSetupDialogEx", "Дата &окончания периода", None))
        self.edtMKBTo.setInputMask(_translate("EconomicAnalisysSetupDialogEx", ">A<00.00", None))
        self.edtMKBTo.setText(_translate("EconomicAnalisysSetupDialogEx", "Z99.99", None))
        self.cmbAccountType.setItemText(0, _translate("EconomicAnalisysSetupDialogEx", "не задано", None))
        self.cmbAccountType.setItemText(1, _translate("EconomicAnalisysSetupDialogEx", "Только Основные", None))
        self.cmbAccountType.setItemText(2, _translate("EconomicAnalisysSetupDialogEx", "Основные + Дополнительные", None))
        self.cmbAccountType.setItemText(3, _translate("EconomicAnalisysSetupDialogEx", "Только Повторные", None))
        self.lblEventType.setText(_translate("EconomicAnalisysSetupDialogEx", "Тип события", None))
        self.lblScheta.setText(_translate("EconomicAnalisysSetupDialogEx", "Признак оплаты", None))
        self.lblVidPom.setText(_translate("EconomicAnalisysSetupDialogEx", "Вид помощи", None))
        self.lblContract.setText(_translate("EconomicAnalisysSetupDialogEx", "&Договор", None))
        self.lblRazrNas.setText(_translate("EconomicAnalisysSetupDialogEx", "В разрезе населения", None))
        self.lblNoscheta.setText(_translate("EconomicAnalisysSetupDialogEx", "Номер счета", None))
        self.lblProfileBed.setText(_translate("EconomicAnalisysSetupDialogEx", "Профиль", None))
        self.lblAccountType.setText(_translate("EconomicAnalisysSetupDialogEx", "Типы реестров", None))
        self.lblDetailTo.setText(_translate("EconomicAnalisysSetupDialogEx", "Детализировать по", None))
        self.chkGroupByPersonSnils.setText(_translate("EconomicAnalisysSetupDialogEx", "Группировать по СНИЛС", None))
        self.chkMKBFilter.setText(_translate("EconomicAnalisysSetupDialogEx", "Диапазон диагнозов", None))
        self.lblClient.setText(_translate("EconomicAnalisysSetupDialogEx", "Пациент", None))
        self.edtMKBFrom.setInputMask(_translate("EconomicAnalisysSetupDialogEx", ">A<00.00", None))
        self.edtMKBFrom.setText(_translate("EconomicAnalisysSetupDialogEx", "A00.00", None))
        self.cbPrice.setText(_translate("EconomicAnalisysSetupDialogEx", "Не учитывать услуги с нулевой ценой", None))
        self.chkPrintAccNumber.setText(_translate("EconomicAnalisysSetupDialogEx", "&Вывод номера счета", None))
        self.cbOnlyNotExposed.setText(_translate("EconomicAnalisysSetupDialogEx", "Только невыставленные счета", None))
        self.cbusl.setText(_translate("EconomicAnalisysSetupDialogEx", "вывод услуг", None))
        self.lblEventRelegateOrg.setText(_translate("EconomicAnalisysSetupDialogEx", "Направитель", None))

from Accounting.AccountComboBox import CAccountComboBox
from Orgs.ContractFindComboBox import CARMSIndependentContractTreeFindComboBox
from Orgs.OrgComboBox import COrgComboBoxEx, COrgIsPayer23ComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.MultivalueComboBox import CRBMultivalueComboBox
from library.crbcombobox import CRBComboBox
