# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Reports\NoProfsChildSetupDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NoProfsChildSetupDialog(object):
    def setupUi(self, NoProfsChildSetupDialog):
        NoProfsChildSetupDialog.setObjectName(_fromUtf8("NoProfsChildSetupDialog"))
        NoProfsChildSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        NoProfsChildSetupDialog.resize(423, 207)
        NoProfsChildSetupDialog.setWindowTitle(_fromUtf8(""))
        NoProfsChildSetupDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(NoProfsChildSetupDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbOrgStructure = COrgStructureComboBox(NoProfsChildSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructure.setSizePolicy(sizePolicy)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 2, 2, 1, 2)
        self.edtEndDate = CDateEdit(NoProfsChildSetupDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(129, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.lblEndDate = QtGui.QLabel(NoProfsChildSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 1, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(NoProfsChildSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 2, 1, 1, 1)
        self.lblBegDate = QtGui.QLabel(NoProfsChildSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        self.edtBegDate = CDateEdit(NoProfsChildSetupDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 2, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(NoProfsChildSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 8, 3, 1, 1)
        self.chkGroupByAttach = QtGui.QCheckBox(NoProfsChildSetupDialog)
        self.chkGroupByAttach.setChecked(True)
        self.chkGroupByAttach.setObjectName(_fromUtf8("chkGroupByAttach"))
        self.gridLayout.addWidget(self.chkGroupByAttach, 6, 1, 1, 1)
        self.frmAge = QtGui.QFrame(NoProfsChildSetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self._2 = QtGui.QHBoxLayout(self.frmAge)
        self._2.setMargin(0)
        self._2.setSpacing(4)
        self._2.setObjectName(_fromUtf8("_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cmbAgeEndUnit = QtGui.QComboBox(self.frmAge)
        self.cmbAgeEndUnit.setObjectName(_fromUtf8("cmbAgeEndUnit"))
        self.cmbAgeEndUnit.addItem(_fromUtf8(""))
        self.cmbAgeEndUnit.addItem(_fromUtf8(""))
        self.cmbAgeEndUnit.addItem(_fromUtf8(""))
        self.cmbAgeEndUnit.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbAgeEndUnit, 1, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.frmAge)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 3, 1, 1)
        self.cmbAgeBegUnit = QtGui.QComboBox(self.frmAge)
        self.cmbAgeBegUnit.setObjectName(_fromUtf8("cmbAgeBegUnit"))
        self.cmbAgeBegUnit.addItem(_fromUtf8(""))
        self.cmbAgeBegUnit.addItem(_fromUtf8(""))
        self.cmbAgeBegUnit.addItem(_fromUtf8(""))
        self.cmbAgeBegUnit.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbAgeBegUnit, 1, 2, 1, 1)
        self.spnAgeEnd = QtGui.QSpinBox(self.frmAge)
        self.spnAgeEnd.setMaximum(17)
        self.spnAgeEnd.setProperty("value", 17)
        self.spnAgeEnd.setObjectName(_fromUtf8("spnAgeEnd"))
        self.gridLayout_2.addWidget(self.spnAgeEnd, 1, 4, 1, 1)
        self.spnAgeBeg = QtGui.QSpinBox(self.frmAge)
        self.spnAgeBeg.setMaximum(17)
        self.spnAgeBeg.setObjectName(_fromUtf8("spnAgeBeg"))
        self.gridLayout_2.addWidget(self.spnAgeBeg, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 6, 1, 1)
        self._2.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.frmAge, 5, 2, 1, 2)
        self.chkAge = QtGui.QCheckBox(NoProfsChildSetupDialog)
        self.chkAge.setObjectName(_fromUtf8("chkAge"))
        self.gridLayout.addWidget(self.chkAge, 5, 1, 1, 1)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblBegDate.setBuddy(self.edtBegDate)

        self.retranslateUi(NoProfsChildSetupDialog)
        self.cmbAgeEndUnit.setCurrentIndex(3)
        self.cmbAgeBegUnit.setCurrentIndex(3)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), NoProfsChildSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), NoProfsChildSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NoProfsChildSetupDialog)
        NoProfsChildSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        NoProfsChildSetupDialog.setTabOrder(self.edtEndDate, self.cmbOrgStructure)
        NoProfsChildSetupDialog.setTabOrder(self.cmbOrgStructure, self.chkAge)
        NoProfsChildSetupDialog.setTabOrder(self.chkAge, self.spnAgeBeg)
        NoProfsChildSetupDialog.setTabOrder(self.spnAgeBeg, self.cmbAgeBegUnit)
        NoProfsChildSetupDialog.setTabOrder(self.cmbAgeBegUnit, self.spnAgeEnd)
        NoProfsChildSetupDialog.setTabOrder(self.spnAgeEnd, self.cmbAgeEndUnit)
        NoProfsChildSetupDialog.setTabOrder(self.cmbAgeEndUnit, self.chkGroupByAttach)
        NoProfsChildSetupDialog.setTabOrder(self.chkGroupByAttach, self.buttonBox)

    def retranslateUi(self, NoProfsChildSetupDialog):
        self.lblEndDate.setText(_translate("NoProfsChildSetupDialog", "Дата &окончания периода", None))
        self.lblOrgStructure.setText(_translate("NoProfsChildSetupDialog", "&Подразделение", None))
        self.lblBegDate.setText(_translate("NoProfsChildSetupDialog", "Дата &начала периода", None))
        self.chkGroupByAttach.setText(_translate("NoProfsChildSetupDialog", "Группировать по участку", None))
        self.cmbAgeEndUnit.setItemText(0, _translate("NoProfsChildSetupDialog", "Д", None))
        self.cmbAgeEndUnit.setItemText(1, _translate("NoProfsChildSetupDialog", "Н", None))
        self.cmbAgeEndUnit.setItemText(2, _translate("NoProfsChildSetupDialog", "М", None))
        self.cmbAgeEndUnit.setItemText(3, _translate("NoProfsChildSetupDialog", "Г", None))
        self.label_3.setText(_translate("NoProfsChildSetupDialog", "по", None))
        self.cmbAgeBegUnit.setItemText(0, _translate("NoProfsChildSetupDialog", "Д", None))
        self.cmbAgeBegUnit.setItemText(1, _translate("NoProfsChildSetupDialog", "Н", None))
        self.cmbAgeBegUnit.setItemText(2, _translate("NoProfsChildSetupDialog", "М", None))
        self.cmbAgeBegUnit.setItemText(3, _translate("NoProfsChildSetupDialog", "Г", None))
        self.label_2.setText(_translate("NoProfsChildSetupDialog", "с", None))
        self.chkAge.setText(_translate("NoProfsChildSetupDialog", "Возраст", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.DateEdit import CDateEdit
