# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\Samson\UP_s11\client\Reports\PreRecordDoctorsDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PreRecordDoctorsDialog(object):
    def setupUi(self, PreRecordDoctorsDialog):
        PreRecordDoctorsDialog.setObjectName(_fromUtf8("PreRecordDoctorsDialog"))
        PreRecordDoctorsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PreRecordDoctorsDialog.resize(561, 286)
        PreRecordDoctorsDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(PreRecordDoctorsDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblOrgStructure = QtGui.QLabel(PreRecordDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblOrgStructure.setSizePolicy(sizePolicy)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 2, 0, 1, 1)
        self.cmbSpeciality = CRBSearchComboBox(PreRecordDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSpeciality.sizePolicy().hasHeightForWidth())
        self.cmbSpeciality.setSizePolicy(sizePolicy)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 3, 1, 1, 5)
        self.cmbPerson = CPersonComboBoxEx(PreRecordDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPerson.sizePolicy().hasHeightForWidth())
        self.cmbPerson.setSizePolicy(sizePolicy)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 4, 1, 1, 5)
        self.chkGroupByOrgStructure = QtGui.QCheckBox(PreRecordDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkGroupByOrgStructure.sizePolicy().hasHeightForWidth())
        self.chkGroupByOrgStructure.setSizePolicy(sizePolicy)
        self.chkGroupByOrgStructure.setObjectName(_fromUtf8("chkGroupByOrgStructure"))
        self.gridLayout.addWidget(self.chkGroupByOrgStructure, 8, 1, 1, 5)
        self.buttonBox = QtGui.QDialogButtonBox(PreRecordDoctorsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 12, 0, 1, 6)
        self.chkSchedulePeriod = QtGui.QCheckBox(PreRecordDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSchedulePeriod.sizePolicy().hasHeightForWidth())
        self.chkSchedulePeriod.setSizePolicy(sizePolicy)
        self.chkSchedulePeriod.setChecked(False)
        self.chkSchedulePeriod.setObjectName(_fromUtf8("chkSchedulePeriod"))
        self.gridLayout.addWidget(self.chkSchedulePeriod, 1, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(PreRecordDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructure.setSizePolicy(sizePolicy)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 2, 1, 1, 5)
        self.lblEndScheduleDate = QtGui.QLabel(PreRecordDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndScheduleDate.sizePolicy().hasHeightForWidth())
        self.lblEndScheduleDate.setSizePolicy(sizePolicy)
        self.lblEndScheduleDate.setObjectName(_fromUtf8("lblEndScheduleDate"))
        self.gridLayout.addWidget(self.lblEndScheduleDate, 1, 2, 1, 1)
        self.edtBegRecordDate = CDateEdit(PreRecordDoctorsDialog)
        self.edtBegRecordDate.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegRecordDate.sizePolicy().hasHeightForWidth())
        self.edtBegRecordDate.setSizePolicy(sizePolicy)
        self.edtBegRecordDate.setCalendarPopup(True)
        self.edtBegRecordDate.setObjectName(_fromUtf8("edtBegRecordDate"))
        self.gridLayout.addWidget(self.edtBegRecordDate, 0, 1, 1, 1)
        self.chkRecordPeriod = QtGui.QCheckBox(PreRecordDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkRecordPeriod.sizePolicy().hasHeightForWidth())
        self.chkRecordPeriod.setSizePolicy(sizePolicy)
        self.chkRecordPeriod.setChecked(True)
        self.chkRecordPeriod.setObjectName(_fromUtf8("chkRecordPeriod"))
        self.gridLayout.addWidget(self.chkRecordPeriod, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 5, 1, 1)
        self.lblPerson = QtGui.QLabel(PreRecordDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPerson.sizePolicy().hasHeightForWidth())
        self.lblPerson.setSizePolicy(sizePolicy)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 4, 0, 1, 1)
        self.edtEndScheduleDate = CDateEdit(PreRecordDoctorsDialog)
        self.edtEndScheduleDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndScheduleDate.sizePolicy().hasHeightForWidth())
        self.edtEndScheduleDate.setSizePolicy(sizePolicy)
        self.edtEndScheduleDate.setCalendarPopup(True)
        self.edtEndScheduleDate.setObjectName(_fromUtf8("edtEndScheduleDate"))
        self.gridLayout.addWidget(self.edtEndScheduleDate, 1, 3, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 0, 1, 1)
        self.chkOvertime = QtGui.QCheckBox(PreRecordDoctorsDialog)
        self.chkOvertime.setObjectName(_fromUtf8("chkOvertime"))
        self.gridLayout.addWidget(self.chkOvertime, 7, 1, 1, 5)
        self.lblSpeciality = QtGui.QLabel(PreRecordDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSpeciality.sizePolicy().hasHeightForWidth())
        self.lblSpeciality.setSizePolicy(sizePolicy)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 3, 0, 1, 1)
        self.lblEndRecordDate = QtGui.QLabel(PreRecordDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndRecordDate.sizePolicy().hasHeightForWidth())
        self.lblEndRecordDate.setSizePolicy(sizePolicy)
        self.lblEndRecordDate.setObjectName(_fromUtf8("lblEndRecordDate"))
        self.gridLayout.addWidget(self.lblEndRecordDate, 0, 2, 1, 1)
        self.edtBegScheduleDate = CDateEdit(PreRecordDoctorsDialog)
        self.edtBegScheduleDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegScheduleDate.sizePolicy().hasHeightForWidth())
        self.edtBegScheduleDate.setSizePolicy(sizePolicy)
        self.edtBegScheduleDate.setCalendarPopup(True)
        self.edtBegScheduleDate.setObjectName(_fromUtf8("edtBegScheduleDate"))
        self.gridLayout.addWidget(self.edtBegScheduleDate, 1, 1, 1, 1)
        self.chkShowDeleted = QtGui.QCheckBox(PreRecordDoctorsDialog)
        self.chkShowDeleted.setObjectName(_fromUtf8("chkShowDeleted"))
        self.gridLayout.addWidget(self.chkShowDeleted, 10, 1, 1, 5)
        self.chkJoinPersonBySNILS = QtGui.QCheckBox(PreRecordDoctorsDialog)
        self.chkJoinPersonBySNILS.setObjectName(_fromUtf8("chkJoinPersonBySNILS"))
        self.gridLayout.addWidget(self.chkJoinPersonBySNILS, 5, 1, 1, 1)
        self.edtEndRecordDate = CDateEdit(PreRecordDoctorsDialog)
        self.edtEndRecordDate.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndRecordDate.sizePolicy().hasHeightForWidth())
        self.edtEndRecordDate.setSizePolicy(sizePolicy)
        self.edtEndRecordDate.setCalendarPopup(True)
        self.edtEndRecordDate.setObjectName(_fromUtf8("edtEndRecordDate"))
        self.gridLayout.addWidget(self.edtEndRecordDate, 0, 3, 1, 2)
        self.chkHidePersons = QtGui.QCheckBox(PreRecordDoctorsDialog)
        self.chkHidePersons.setObjectName(_fromUtf8("chkHidePersons"))
        self.gridLayout.addWidget(self.chkHidePersons, 6, 1, 1, 1)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblEndScheduleDate.setBuddy(self.edtEndScheduleDate)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblEndRecordDate.setBuddy(self.edtEndRecordDate)

        self.retranslateUi(PreRecordDoctorsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PreRecordDoctorsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PreRecordDoctorsDialog.reject)
        QtCore.QObject.connect(self.chkRecordPeriod, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegRecordDate.setEnabled)
        QtCore.QObject.connect(self.chkRecordPeriod, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndRecordDate.setEnabled)
        QtCore.QObject.connect(self.chkSchedulePeriod, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegScheduleDate.setEnabled)
        QtCore.QObject.connect(self.chkSchedulePeriod, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndScheduleDate.setEnabled)
        QtCore.QObject.connect(self.chkRecordPeriod, QtCore.SIGNAL(_fromUtf8("clicked()")), self.edtBegRecordDate.setFocus)
        QtCore.QObject.connect(self.chkSchedulePeriod, QtCore.SIGNAL(_fromUtf8("clicked()")), self.edtBegScheduleDate.setFocus)
        QtCore.QMetaObject.connectSlotsByName(PreRecordDoctorsDialog)
        PreRecordDoctorsDialog.setTabOrder(self.chkRecordPeriod, self.edtBegRecordDate)
        PreRecordDoctorsDialog.setTabOrder(self.edtBegRecordDate, self.edtEndRecordDate)
        PreRecordDoctorsDialog.setTabOrder(self.edtEndRecordDate, self.chkSchedulePeriod)
        PreRecordDoctorsDialog.setTabOrder(self.chkSchedulePeriod, self.edtBegScheduleDate)
        PreRecordDoctorsDialog.setTabOrder(self.edtBegScheduleDate, self.edtEndScheduleDate)
        PreRecordDoctorsDialog.setTabOrder(self.edtEndScheduleDate, self.cmbOrgStructure)
        PreRecordDoctorsDialog.setTabOrder(self.cmbOrgStructure, self.cmbSpeciality)
        PreRecordDoctorsDialog.setTabOrder(self.cmbSpeciality, self.cmbPerson)
        PreRecordDoctorsDialog.setTabOrder(self.cmbPerson, self.chkOvertime)
        PreRecordDoctorsDialog.setTabOrder(self.chkOvertime, self.chkGroupByOrgStructure)
        PreRecordDoctorsDialog.setTabOrder(self.chkGroupByOrgStructure, self.buttonBox)

    def retranslateUi(self, PreRecordDoctorsDialog):
        PreRecordDoctorsDialog.setWindowTitle(_translate("PreRecordDoctorsDialog", "параметры отчёта", None))
        self.lblOrgStructure.setText(_translate("PreRecordDoctorsDialog", "&Подразделение", None))
        self.cmbSpeciality.setWhatsThis(_translate("PreRecordDoctorsDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.chkGroupByOrgStructure.setText(_translate("PreRecordDoctorsDialog", "Группировать по подразделениям", None))
        self.chkSchedulePeriod.setText(_translate("PreRecordDoctorsDialog", "Период планируемого приёма с", None))
        self.lblEndScheduleDate.setText(_translate("PreRecordDoctorsDialog", "по", None))
        self.edtBegRecordDate.setDisplayFormat(_translate("PreRecordDoctorsDialog", "dd.MM.yyyy", None))
        self.chkRecordPeriod.setText(_translate("PreRecordDoctorsDialog", "Период постановки в очередь с", None))
        self.lblPerson.setText(_translate("PreRecordDoctorsDialog", "&Врач", None))
        self.edtEndScheduleDate.setDisplayFormat(_translate("PreRecordDoctorsDialog", "dd.MM.yyyy", None))
        self.chkOvertime.setText(_translate("PreRecordDoctorsDialog", "Отдельно поставленные в очередь сверх времени", None))
        self.lblSpeciality.setText(_translate("PreRecordDoctorsDialog", "&Специальность", None))
        self.lblEndRecordDate.setText(_translate("PreRecordDoctorsDialog", "по", None))
        self.edtBegScheduleDate.setDisplayFormat(_translate("PreRecordDoctorsDialog", "dd.MM.yyyy", None))
        self.chkShowDeleted.setText(_translate("PreRecordDoctorsDialog", "Учитывать удаленные записи", None))
        self.chkJoinPersonBySNILS.setText(_translate("PreRecordDoctorsDialog", "Искать по СНИЛС врача", None))
        self.edtEndRecordDate.setDisplayFormat(_translate("PreRecordDoctorsDialog", "dd.MM.yyyy", None))
        self.chkHidePersons.setText(_translate("PreRecordDoctorsDialog", "Скрывать детализацию по врачам", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.CRBSearchComboBox import CRBSearchComboBox
from library.DateEdit import CDateEdit
