# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\samson\UP_s11\client\Reports\PreRecordPlanExecutionByDoctorsDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PreRecordPlanExecutionByDoctorsDialog(object):
    def setupUi(self, PreRecordPlanExecutionByDoctorsDialog):
        PreRecordPlanExecutionByDoctorsDialog.setObjectName(_fromUtf8("PreRecordPlanExecutionByDoctorsDialog"))
        PreRecordPlanExecutionByDoctorsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PreRecordPlanExecutionByDoctorsDialog.resize(550, 348)
        PreRecordPlanExecutionByDoctorsDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(PreRecordPlanExecutionByDoctorsDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkOvertime = QtGui.QCheckBox(PreRecordPlanExecutionByDoctorsDialog)
        self.chkOvertime.setObjectName(_fromUtf8("chkOvertime"))
        self.gridLayout.addWidget(self.chkOvertime, 7, 1, 1, 5)
        self.cmbSpeciality = CRBComboBox(PreRecordPlanExecutionByDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSpeciality.sizePolicy().hasHeightForWidth())
        self.cmbSpeciality.setSizePolicy(sizePolicy)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridLayout.addWidget(self.cmbSpeciality, 4, 1, 1, 5)
        self.lblPerson = QtGui.QLabel(PreRecordPlanExecutionByDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPerson.sizePolicy().hasHeightForWidth())
        self.lblPerson.setSizePolicy(sizePolicy)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout.addWidget(self.lblPerson, 5, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(PreRecordPlanExecutionByDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructure.setSizePolicy(sizePolicy)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 3, 1, 1, 5)
        self.cmbPerson = CPersonComboBoxEx(PreRecordPlanExecutionByDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPerson.sizePolicy().hasHeightForWidth())
        self.cmbPerson.setSizePolicy(sizePolicy)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.gridLayout.addWidget(self.cmbPerson, 5, 1, 1, 5)
        self.lblEndRecordDate = QtGui.QLabel(PreRecordPlanExecutionByDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndRecordDate.sizePolicy().hasHeightForWidth())
        self.lblEndRecordDate.setSizePolicy(sizePolicy)
        self.lblEndRecordDate.setObjectName(_fromUtf8("lblEndRecordDate"))
        self.gridLayout.addWidget(self.lblEndRecordDate, 0, 2, 1, 1)
        self.chkGroupByOrgStructure = QtGui.QCheckBox(PreRecordPlanExecutionByDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkGroupByOrgStructure.sizePolicy().hasHeightForWidth())
        self.chkGroupByOrgStructure.setSizePolicy(sizePolicy)
        self.chkGroupByOrgStructure.setObjectName(_fromUtf8("chkGroupByOrgStructure"))
        self.gridLayout.addWidget(self.chkGroupByOrgStructure, 8, 1, 1, 5)
        self.lblEndScheduleDate = QtGui.QLabel(PreRecordPlanExecutionByDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndScheduleDate.sizePolicy().hasHeightForWidth())
        self.lblEndScheduleDate.setSizePolicy(sizePolicy)
        self.lblEndScheduleDate.setObjectName(_fromUtf8("lblEndScheduleDate"))
        self.gridLayout.addWidget(self.lblEndScheduleDate, 1, 2, 1, 1)
        self.chkSchedulePeriod = QtGui.QCheckBox(PreRecordPlanExecutionByDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSchedulePeriod.sizePolicy().hasHeightForWidth())
        self.chkSchedulePeriod.setSizePolicy(sizePolicy)
        self.chkSchedulePeriod.setChecked(False)
        self.chkSchedulePeriod.setObjectName(_fromUtf8("chkSchedulePeriod"))
        self.gridLayout.addWidget(self.chkSchedulePeriod, 1, 0, 1, 1)
        self.edtBegRecordDate = CDateEdit(PreRecordPlanExecutionByDoctorsDialog)
        self.edtBegRecordDate.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegRecordDate.sizePolicy().hasHeightForWidth())
        self.edtBegRecordDate.setSizePolicy(sizePolicy)
        self.edtBegRecordDate.setCalendarPopup(True)
        self.edtBegRecordDate.setObjectName(_fromUtf8("edtBegRecordDate"))
        self.gridLayout.addWidget(self.edtBegRecordDate, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 0, 1, 1)
        self.chkRecordPeriod = QtGui.QCheckBox(PreRecordPlanExecutionByDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkRecordPeriod.sizePolicy().hasHeightForWidth())
        self.chkRecordPeriod.setSizePolicy(sizePolicy)
        self.chkRecordPeriod.setChecked(True)
        self.chkRecordPeriod.setObjectName(_fromUtf8("chkRecordPeriod"))
        self.gridLayout.addWidget(self.chkRecordPeriod, 0, 0, 1, 1)
        self.chkHidePersons = QtGui.QCheckBox(PreRecordPlanExecutionByDoctorsDialog)
        self.chkHidePersons.setObjectName(_fromUtf8("chkHidePersons"))
        self.gridLayout.addWidget(self.chkHidePersons, 9, 1, 1, 5)
        self.edtEndRecordDate = CDateEdit(PreRecordPlanExecutionByDoctorsDialog)
        self.edtEndRecordDate.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndRecordDate.sizePolicy().hasHeightForWidth())
        self.edtEndRecordDate.setSizePolicy(sizePolicy)
        self.edtEndRecordDate.setCalendarPopup(True)
        self.edtEndRecordDate.setObjectName(_fromUtf8("edtEndRecordDate"))
        self.gridLayout.addWidget(self.edtEndRecordDate, 0, 3, 1, 2)
        self.edtBegScheduleDate = CDateEdit(PreRecordPlanExecutionByDoctorsDialog)
        self.edtBegScheduleDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegScheduleDate.sizePolicy().hasHeightForWidth())
        self.edtBegScheduleDate.setSizePolicy(sizePolicy)
        self.edtBegScheduleDate.setCalendarPopup(True)
        self.edtBegScheduleDate.setObjectName(_fromUtf8("edtBegScheduleDate"))
        self.gridLayout.addWidget(self.edtBegScheduleDate, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.lblSpeciality = QtGui.QLabel(PreRecordPlanExecutionByDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSpeciality.sizePolicy().hasHeightForWidth())
        self.lblSpeciality.setSizePolicy(sizePolicy)
        self.lblSpeciality.setObjectName(_fromUtf8("lblSpeciality"))
        self.gridLayout.addWidget(self.lblSpeciality, 4, 0, 1, 1)
        self.edtEndScheduleDate = CDateEdit(PreRecordPlanExecutionByDoctorsDialog)
        self.edtEndScheduleDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndScheduleDate.sizePolicy().hasHeightForWidth())
        self.edtEndScheduleDate.setSizePolicy(sizePolicy)
        self.edtEndScheduleDate.setCalendarPopup(True)
        self.edtEndScheduleDate.setObjectName(_fromUtf8("edtEndScheduleDate"))
        self.gridLayout.addWidget(self.edtEndScheduleDate, 1, 3, 1, 2)
        self.lblOrgStructure = QtGui.QLabel(PreRecordPlanExecutionByDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblOrgStructure.setSizePolicy(sizePolicy)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 3, 0, 1, 1)
        self.lblAppointmentType = QtGui.QLabel(PreRecordPlanExecutionByDoctorsDialog)
        self.lblAppointmentType.setObjectName(_fromUtf8("lblAppointmentType"))
        self.gridLayout.addWidget(self.lblAppointmentType, 6, 0, 1, 1)
        self.cmbAppointmentType = QtGui.QComboBox(PreRecordPlanExecutionByDoctorsDialog)
        self.cmbAppointmentType.setObjectName(_fromUtf8("cmbAppointmentType"))
        self.gridLayout.addWidget(self.cmbAppointmentType, 6, 1, 1, 5)
        self.buttonBox = QtGui.QDialogButtonBox(PreRecordPlanExecutionByDoctorsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 12, 0, 1, 6)
        self.lblOrgStructureType = QtGui.QLabel(PreRecordPlanExecutionByDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructureType.sizePolicy().hasHeightForWidth())
        self.lblOrgStructureType.setSizePolicy(sizePolicy)
        self.lblOrgStructureType.setObjectName(_fromUtf8("lblOrgStructureType"))
        self.gridLayout.addWidget(self.lblOrgStructureType, 2, 0, 1, 1)
        self.cmbOrgStructureType = QtGui.QComboBox(PreRecordPlanExecutionByDoctorsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructureType.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructureType.setSizePolicy(sizePolicy)
        self.cmbOrgStructureType.setObjectName(_fromUtf8("cmbOrgStructureType"))
        self.cmbOrgStructureType.addItem(_fromUtf8(""))
        self.cmbOrgStructureType.addItem(_fromUtf8(""))
        self.cmbOrgStructureType.addItem(_fromUtf8(""))
        self.cmbOrgStructureType.addItem(_fromUtf8(""))
        self.cmbOrgStructureType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbOrgStructureType, 2, 1, 1, 5)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblEndRecordDate.setBuddy(self.edtEndRecordDate)
        self.lblEndScheduleDate.setBuddy(self.edtEndScheduleDate)
        self.lblSpeciality.setBuddy(self.cmbSpeciality)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblOrgStructureType.setBuddy(self.cmbOrgStructureType)

        self.retranslateUi(PreRecordPlanExecutionByDoctorsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PreRecordPlanExecutionByDoctorsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PreRecordPlanExecutionByDoctorsDialog.reject)
        QtCore.QObject.connect(self.chkRecordPeriod, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegRecordDate.setEnabled)
        QtCore.QObject.connect(self.chkRecordPeriod, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndRecordDate.setEnabled)
        QtCore.QObject.connect(self.chkSchedulePeriod, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBegScheduleDate.setEnabled)
        QtCore.QObject.connect(self.chkSchedulePeriod, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtEndScheduleDate.setEnabled)
        QtCore.QObject.connect(self.chkRecordPeriod, QtCore.SIGNAL(_fromUtf8("clicked()")), self.edtBegRecordDate.setFocus)
        QtCore.QObject.connect(self.chkSchedulePeriod, QtCore.SIGNAL(_fromUtf8("clicked()")), self.edtBegScheduleDate.setFocus)
        QtCore.QMetaObject.connectSlotsByName(PreRecordPlanExecutionByDoctorsDialog)
        PreRecordPlanExecutionByDoctorsDialog.setTabOrder(self.chkRecordPeriod, self.edtBegRecordDate)
        PreRecordPlanExecutionByDoctorsDialog.setTabOrder(self.edtBegRecordDate, self.edtEndRecordDate)
        PreRecordPlanExecutionByDoctorsDialog.setTabOrder(self.edtEndRecordDate, self.chkSchedulePeriod)
        PreRecordPlanExecutionByDoctorsDialog.setTabOrder(self.chkSchedulePeriod, self.edtBegScheduleDate)
        PreRecordPlanExecutionByDoctorsDialog.setTabOrder(self.edtBegScheduleDate, self.edtEndScheduleDate)
        PreRecordPlanExecutionByDoctorsDialog.setTabOrder(self.edtEndScheduleDate, self.cmbOrgStructure)
        PreRecordPlanExecutionByDoctorsDialog.setTabOrder(self.cmbOrgStructure, self.cmbSpeciality)
        PreRecordPlanExecutionByDoctorsDialog.setTabOrder(self.cmbSpeciality, self.cmbPerson)
        PreRecordPlanExecutionByDoctorsDialog.setTabOrder(self.cmbPerson, self.cmbAppointmentType)
        PreRecordPlanExecutionByDoctorsDialog.setTabOrder(self.cmbAppointmentType, self.chkOvertime)
        PreRecordPlanExecutionByDoctorsDialog.setTabOrder(self.chkOvertime, self.chkGroupByOrgStructure)
        PreRecordPlanExecutionByDoctorsDialog.setTabOrder(self.chkGroupByOrgStructure, self.chkHidePersons)
        PreRecordPlanExecutionByDoctorsDialog.setTabOrder(self.chkHidePersons, self.buttonBox)

    def retranslateUi(self, PreRecordPlanExecutionByDoctorsDialog):
        PreRecordPlanExecutionByDoctorsDialog.setWindowTitle(_translate("PreRecordPlanExecutionByDoctorsDialog", "параметры отчёта", None))
        self.chkOvertime.setText(_translate("PreRecordPlanExecutionByDoctorsDialog", "Отдельно поставленные в очередь сверх времени", None))
        self.cmbSpeciality.setWhatsThis(_translate("PreRecordPlanExecutionByDoctorsDialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None))
        self.lblPerson.setText(_translate("PreRecordPlanExecutionByDoctorsDialog", "&Врач", None))
        self.lblEndRecordDate.setText(_translate("PreRecordPlanExecutionByDoctorsDialog", "по", None))
        self.chkGroupByOrgStructure.setText(_translate("PreRecordPlanExecutionByDoctorsDialog", "Группировать по подразделениям", None))
        self.lblEndScheduleDate.setText(_translate("PreRecordPlanExecutionByDoctorsDialog", "по", None))
        self.chkSchedulePeriod.setText(_translate("PreRecordPlanExecutionByDoctorsDialog", "Период планируемого приёма с", None))
        self.edtBegRecordDate.setDisplayFormat(_translate("PreRecordPlanExecutionByDoctorsDialog", "dd.MM.yyyy", None))
        self.chkRecordPeriod.setText(_translate("PreRecordPlanExecutionByDoctorsDialog", "Период постановки в очередь с", None))
        self.chkHidePersons.setText(_translate("PreRecordPlanExecutionByDoctorsDialog", "Скрывать детализацию по врачам", None))
        self.edtEndRecordDate.setDisplayFormat(_translate("PreRecordPlanExecutionByDoctorsDialog", "dd.MM.yyyy", None))
        self.edtBegScheduleDate.setDisplayFormat(_translate("PreRecordPlanExecutionByDoctorsDialog", "dd.MM.yyyy", None))
        self.lblSpeciality.setText(_translate("PreRecordPlanExecutionByDoctorsDialog", "&Специальность", None))
        self.edtEndScheduleDate.setDisplayFormat(_translate("PreRecordPlanExecutionByDoctorsDialog", "dd.MM.yyyy", None))
        self.lblOrgStructure.setText(_translate("PreRecordPlanExecutionByDoctorsDialog", "&Подразделение", None))
        self.lblAppointmentType.setText(_translate("PreRecordPlanExecutionByDoctorsDialog", "Тип приема", None))
        self.lblOrgStructureType.setText(_translate("PreRecordPlanExecutionByDoctorsDialog", "Тип подразделения", None))
        self.cmbOrgStructureType.setItemText(0, _translate("PreRecordPlanExecutionByDoctorsDialog", "Амбулатория", None))
        self.cmbOrgStructureType.setItemText(1, _translate("PreRecordPlanExecutionByDoctorsDialog", "Стационар", None))
        self.cmbOrgStructureType.setItemText(2, _translate("PreRecordPlanExecutionByDoctorsDialog", "Скорая помощь", None))
        self.cmbOrgStructureType.setItemText(3, _translate("PreRecordPlanExecutionByDoctorsDialog", "Мобильная станция", None))
        self.cmbOrgStructureType.setItemText(4, _translate("PreRecordPlanExecutionByDoctorsDialog", "Приемное отделение стационара", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
