# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\Samson\UP_s11\client\Reports\ReportPreventiveMinorsSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportPreventiveMinorsSetupDialog(object):
    def setupUi(self, ReportPreventiveMinorsSetupDialog):
        ReportPreventiveMinorsSetupDialog.setObjectName(_fromUtf8("ReportPreventiveMinorsSetupDialog"))
        ReportPreventiveMinorsSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportPreventiveMinorsSetupDialog.resize(475, 316)
        ReportPreventiveMinorsSetupDialog.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(ReportPreventiveMinorsSetupDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        spacerItem = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 0, 2, 1, 1)
        self.lblEventPurpose = QtGui.QLabel(ReportPreventiveMinorsSetupDialog)
        self.lblEventPurpose.setObjectName(_fromUtf8("lblEventPurpose"))
        self.gridlayout.addWidget(self.lblEventPurpose, 6, 0, 1, 1)
        self.cmbEventPurpose = CRBComboBox(ReportPreventiveMinorsSetupDialog)
        self.cmbEventPurpose.setObjectName(_fromUtf8("cmbEventPurpose"))
        self.gridlayout.addWidget(self.cmbEventPurpose, 6, 1, 1, 2)
        self.cmbOrgStructure = COrgStructureComboBox(ReportPreventiveMinorsSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridlayout.addWidget(self.cmbOrgStructure, 9, 1, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ReportPreventiveMinorsSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 15, 0, 1, 3)
        self.lblSex = QtGui.QLabel(ReportPreventiveMinorsSetupDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridlayout.addWidget(self.lblSex, 11, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(ReportPreventiveMinorsSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridlayout.addWidget(self.lblPerson, 10, 0, 1, 1)
        self.lblEndDate = QtGui.QLabel(ReportPreventiveMinorsSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridlayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.line_2 = QtGui.QFrame(ReportPreventiveMinorsSetupDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridlayout.addWidget(self.line_2, 5, 0, 1, 3)
        self.cmbPerson = CPersonComboBoxEx(ReportPreventiveMinorsSetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbPerson, 10, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(129, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem1, 13, 0, 1, 1)
        self.lblEventTypeList = QtGui.QLabel(ReportPreventiveMinorsSetupDialog)
        self.lblEventTypeList.setWordWrap(True)
        self.lblEventTypeList.setObjectName(_fromUtf8("lblEventTypeList"))
        self.gridlayout.addWidget(self.lblEventTypeList, 7, 1, 1, 2)
        self.lblPrevBegDate = QtGui.QLabel(ReportPreventiveMinorsSetupDialog)
        self.lblPrevBegDate.setObjectName(_fromUtf8("lblPrevBegDate"))
        self.gridlayout.addWidget(self.lblPrevBegDate, 3, 0, 1, 1)
        self.line = QtGui.QFrame(ReportPreventiveMinorsSetupDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridlayout.addWidget(self.line, 2, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem2, 4, 2, 1, 1)
        self.btnEventTypeList = QtGui.QPushButton(ReportPreventiveMinorsSetupDialog)
        self.btnEventTypeList.setObjectName(_fromUtf8("btnEventTypeList"))
        self.gridlayout.addWidget(self.btnEventTypeList, 7, 0, 1, 1)
        self.edtPrevEndDate = CDateEdit(ReportPreventiveMinorsSetupDialog)
        self.edtPrevEndDate.setCalendarPopup(True)
        self.edtPrevEndDate.setObjectName(_fromUtf8("edtPrevEndDate"))
        self.gridlayout.addWidget(self.edtPrevEndDate, 4, 1, 1, 1)
        self.edtBegDate = CDateEdit(ReportPreventiveMinorsSetupDialog)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridlayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.lblBegDate = QtGui.QLabel(ReportPreventiveMinorsSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridlayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.lblAge = QtGui.QLabel(ReportPreventiveMinorsSetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridlayout.addWidget(self.lblAge, 12, 0, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(ReportPreventiveMinorsSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridlayout.addWidget(self.lblOrgStructure, 9, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem3, 3, 2, 1, 1)
        self.lblPrevEndDate = QtGui.QLabel(ReportPreventiveMinorsSetupDialog)
        self.lblPrevEndDate.setObjectName(_fromUtf8("lblPrevEndDate"))
        self.gridlayout.addWidget(self.lblPrevEndDate, 4, 0, 1, 1)
        self.edtEndDate = CDateEdit(ReportPreventiveMinorsSetupDialog)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridlayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.edtPrevBegDate = CDateEdit(ReportPreventiveMinorsSetupDialog)
        self.edtPrevBegDate.setCalendarPopup(True)
        self.edtPrevBegDate.setObjectName(_fromUtf8("edtPrevBegDate"))
        self.gridlayout.addWidget(self.edtPrevBegDate, 3, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem4, 14, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(ReportPreventiveMinorsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbSex, 11, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem5, 1, 2, 1, 1)
        self.frmAge = QtGui.QFrame(ReportPreventiveMinorsSetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self._2 = QtGui.QHBoxLayout(self.frmAge)
        self._2.setMargin(0)
        self._2.setSpacing(4)
        self._2.setObjectName(_fromUtf8("_2"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self._2.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self._2.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(17)
        self.edtAgeTo.setProperty("value", 17)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self._2.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self._2.addWidget(self.lblAgeYears)
        spacerItem6 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem6)
        self.gridlayout.addWidget(self.frmAge, 12, 1, 1, 2)
        self.lblEventPurpose.setBuddy(self.cmbEventPurpose)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)

        self.retranslateUi(ReportPreventiveMinorsSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportPreventiveMinorsSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportPreventiveMinorsSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportPreventiveMinorsSetupDialog)
        ReportPreventiveMinorsSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportPreventiveMinorsSetupDialog.setTabOrder(self.edtEndDate, self.edtPrevBegDate)
        ReportPreventiveMinorsSetupDialog.setTabOrder(self.edtPrevBegDate, self.edtPrevEndDate)
        ReportPreventiveMinorsSetupDialog.setTabOrder(self.edtPrevEndDate, self.cmbEventPurpose)
        ReportPreventiveMinorsSetupDialog.setTabOrder(self.cmbEventPurpose, self.btnEventTypeList)
        ReportPreventiveMinorsSetupDialog.setTabOrder(self.btnEventTypeList, self.cmbOrgStructure)
        ReportPreventiveMinorsSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbPerson)
        ReportPreventiveMinorsSetupDialog.setTabOrder(self.cmbPerson, self.cmbSex)
        ReportPreventiveMinorsSetupDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        ReportPreventiveMinorsSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        ReportPreventiveMinorsSetupDialog.setTabOrder(self.edtAgeTo, self.buttonBox)

    def retranslateUi(self, ReportPreventiveMinorsSetupDialog):
        ReportPreventiveMinorsSetupDialog.setWindowTitle(_translate("ReportPreventiveMinorsSetupDialog", "параметры отчёта", None))
        self.lblEventPurpose.setText(_translate("ReportPreventiveMinorsSetupDialog", "&Назначение обращения", None))
        self.lblSex.setText(_translate("ReportPreventiveMinorsSetupDialog", "По&л", None))
        self.lblPerson.setText(_translate("ReportPreventiveMinorsSetupDialog", "&Врач", None))
        self.lblEndDate.setText(_translate("ReportPreventiveMinorsSetupDialog", "Дата &окончания периода", None))
        self.cmbPerson.setItemText(0, _translate("ReportPreventiveMinorsSetupDialog", "Врач", None))
        self.lblEventTypeList.setText(_translate("ReportPreventiveMinorsSetupDialog", "Не задано", None))
        self.lblPrevBegDate.setText(_translate("ReportPreventiveMinorsSetupDialog", "Дата начала предыдущего периода", None))
        self.btnEventTypeList.setText(_translate("ReportPreventiveMinorsSetupDialog", "Тип обращения", None))
        self.lblBegDate.setText(_translate("ReportPreventiveMinorsSetupDialog", "Дата &начала периода", None))
        self.lblAge.setText(_translate("ReportPreventiveMinorsSetupDialog", "Во&зраст с", None))
        self.lblOrgStructure.setText(_translate("ReportPreventiveMinorsSetupDialog", "&Подразделение", None))
        self.lblPrevEndDate.setText(_translate("ReportPreventiveMinorsSetupDialog", "Дата окончания предыдущего периода", None))
        self.cmbSex.setItemText(1, _translate("ReportPreventiveMinorsSetupDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ReportPreventiveMinorsSetupDialog", "Ж", None))
        self.lblAgeTo.setText(_translate("ReportPreventiveMinorsSetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("ReportPreventiveMinorsSetupDialog", "лет", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
