# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dev1\PycharmProjects\client_kortis\Reports\ReportSummaryClientNotApply.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportSummaryClientNotApply(object):
    def setupUi(self, ReportSummaryClientNotApply):
        ReportSummaryClientNotApply.setObjectName(_fromUtf8("ReportSummaryClientNotApply"))
        ReportSummaryClientNotApply.setWindowModality(QtCore.Qt.ApplicationModal)
        ReportSummaryClientNotApply.resize(497, 484)
        ReportSummaryClientNotApply.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(ReportSummaryClientNotApply)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.frmAge = QtGui.QFrame(ReportSummaryClientNotApply)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self._2 = QtGui.QHBoxLayout(self.frmAge)
        self._2.setMargin(0)
        self._2.setSpacing(4)
        self._2.setObjectName(_fromUtf8("_2"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self._2.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self._2.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self._2.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self._2.addWidget(self.lblAgeYears)
        spacerItem = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem)
        self.gridlayout.addWidget(self.frmAge, 11, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.lblEndDate = QtGui.QLabel(ReportSummaryClientNotApply)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridlayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(ReportSummaryClientNotApply)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridlayout.addWidget(self.lblOrgStructure, 4, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(ReportSummaryClientNotApply)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructure.setSizePolicy(sizePolicy)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridlayout.addWidget(self.cmbOrgStructure, 4, 1, 1, 2)
        self.lblScene = QtGui.QLabel(ReportSummaryClientNotApply)
        self.lblScene.setObjectName(_fromUtf8("lblScene"))
        self.gridlayout.addWidget(self.lblScene, 5, 0, 1, 1)
        self.edtEndDate = CDateEdit(ReportSummaryClientNotApply)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridlayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.edtBegDate = CDateEdit(ReportSummaryClientNotApply)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridlayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(91, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.lblBegDate = QtGui.QLabel(ReportSummaryClientNotApply)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridlayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(ReportSummaryClientNotApply)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSex.sizePolicy().hasHeightForWidth())
        self.cmbSex.setSizePolicy(sizePolicy)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbSex, 10, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(129, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem3, 12, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ReportSummaryClientNotApply)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 13, 0, 1, 3)
        self.lblPerson = QtGui.QLabel(ReportSummaryClientNotApply)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridlayout.addWidget(self.lblPerson, 7, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(ReportSummaryClientNotApply)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbPerson, 7, 1, 1, 2)
        self.lblSex = QtGui.QLabel(ReportSummaryClientNotApply)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridlayout.addWidget(self.lblSex, 10, 0, 1, 1)
        self.lblAge = QtGui.QLabel(ReportSummaryClientNotApply)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridlayout.addWidget(self.lblAge, 11, 0, 1, 1)
        self.label = QtGui.QLabel(ReportSummaryClientNotApply)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridlayout.addWidget(self.label, 8, 0, 1, 1)
        self.cmbSpeciality = CRBComboBox(ReportSummaryClientNotApply)
        self.cmbSpeciality.setObjectName(_fromUtf8("cmbSpeciality"))
        self.gridlayout.addWidget(self.cmbSpeciality, 5, 1, 1, 2)
        self.label_2 = QtGui.QLabel(ReportSummaryClientNotApply)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout.addWidget(self.label_2, 9, 0, 1, 1)
        self.cmbattached = QtGui.QComboBox(ReportSummaryClientNotApply)
        self.cmbattached.setFrame(True)
        self.cmbattached.setObjectName(_fromUtf8("cmbattached"))
        self.cmbattached.addItem(_fromUtf8(""))
        self.cmbattached.addItem(_fromUtf8(""))
        self.cmbattached.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbattached, 8, 1, 1, 2)
        self.cmbdn = CRBComboBox(ReportSummaryClientNotApply)
        self.cmbdn.setObjectName(_fromUtf8("cmbdn"))
        self.gridlayout.addWidget(self.cmbdn, 9, 1, 1, 2)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblAge.setBuddy(self.edtAgeFrom)

        self.retranslateUi(ReportSummaryClientNotApply)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ReportSummaryClientNotApply.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ReportSummaryClientNotApply.reject)
        QtCore.QMetaObject.connectSlotsByName(ReportSummaryClientNotApply)
        ReportSummaryClientNotApply.setTabOrder(self.edtBegDate, self.edtEndDate)
        ReportSummaryClientNotApply.setTabOrder(self.edtEndDate, self.cmbPerson)
        ReportSummaryClientNotApply.setTabOrder(self.cmbPerson, self.cmbSex)
        ReportSummaryClientNotApply.setTabOrder(self.cmbSex, self.edtAgeFrom)
        ReportSummaryClientNotApply.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        ReportSummaryClientNotApply.setTabOrder(self.edtAgeTo, self.buttonBox)

    def retranslateUi(self, ReportSummaryClientNotApply):
        ReportSummaryClientNotApply.setWindowTitle(_translate("ReportSummaryClientNotApply", "Сводка попациентам (не обращавшиеся в МО)", None))
        self.lblAgeTo.setText(_translate("ReportSummaryClientNotApply", "по", None))
        self.lblAgeYears.setText(_translate("ReportSummaryClientNotApply", "лет", None))
        self.lblEndDate.setText(_translate("ReportSummaryClientNotApply", "Дата &окончания периода", None))
        self.lblOrgStructure.setText(_translate("ReportSummaryClientNotApply", "&Подразделение", None))
        self.lblScene.setText(_translate("ReportSummaryClientNotApply", "Специальность", None))
        self.lblBegDate.setText(_translate("ReportSummaryClientNotApply", "Дата &начала периода", None))
        self.cmbSex.setItemText(1, _translate("ReportSummaryClientNotApply", "М", None))
        self.cmbSex.setItemText(2, _translate("ReportSummaryClientNotApply", "Ж", None))
        self.lblPerson.setText(_translate("ReportSummaryClientNotApply", "&Врач", None))
        self.cmbPerson.setItemText(0, _translate("ReportSummaryClientNotApply", "Врач", None))
        self.lblSex.setText(_translate("ReportSummaryClientNotApply", "По&л", None))
        self.lblAge.setText(_translate("ReportSummaryClientNotApply", "Во&зраст с", None))
        self.label.setText(_translate("ReportSummaryClientNotApply", "Прикреплен", None))
        self.label_2.setText(_translate("ReportSummaryClientNotApply", "ДН-учет", None))
        self.cmbattached.setItemText(0, _translate("ReportSummaryClientNotApply", "Все", None))
        self.cmbattached.setItemText(1, _translate("ReportSummaryClientNotApply", "Прикрепленные", None))
        self.cmbattached.setItemText(2, _translate("ReportSummaryClientNotApply", "Не прикрепленные", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox
