# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\Documents\svn\Reports\StationaryAnalyticsSetup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StationaryAnalyticsSetupDialog(object):
    def setupUi(self, StationaryAnalyticsSetupDialog):
        StationaryAnalyticsSetupDialog.setObjectName(_fromUtf8("StationaryAnalyticsSetupDialog"))
        StationaryAnalyticsSetupDialog.resize(586, 580)
        self.gridLayout = QtGui.QGridLayout(StationaryAnalyticsSetupDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkFilterAdditionalOptions = QtGui.QCheckBox(StationaryAnalyticsSetupDialog)
        self.chkFilterAdditionalOptions.setObjectName(_fromUtf8("chkFilterAdditionalOptions"))
        self.gridLayout.addWidget(self.chkFilterAdditionalOptions, 21, 0, 1, 1)
        self.cmbQuotaClass = QtGui.QComboBox(StationaryAnalyticsSetupDialog)
        self.cmbQuotaClass.setEnabled(False)
        self.cmbQuotaClass.setObjectName(_fromUtf8("cmbQuotaClass"))
        self.cmbQuotaClass.addItem(_fromUtf8(""))
        self.cmbQuotaClass.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbQuotaClass, 9, 1, 1, 3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblFilterSex = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblFilterSex.setObjectName(_fromUtf8("lblFilterSex"))
        self.horizontalLayout_2.addWidget(self.lblFilterSex)
        self.cmbFilterSex = QtGui.QComboBox(StationaryAnalyticsSetupDialog)
        self.cmbFilterSex.setEnabled(False)
        self.cmbFilterSex.setObjectName(_fromUtf8("cmbFilterSex"))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.cmbFilterSex.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmbFilterSex)
        self.lblFilterAge = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblFilterAge.setObjectName(_fromUtf8("lblFilterAge"))
        self.horizontalLayout_2.addWidget(self.lblFilterAge)
        self.edtFilterToAge = QtGui.QSpinBox(StationaryAnalyticsSetupDialog)
        self.edtFilterToAge.setEnabled(False)
        self.edtFilterToAge.setMaximum(150)
        self.edtFilterToAge.setObjectName(_fromUtf8("edtFilterToAge"))
        self.horizontalLayout_2.addWidget(self.edtFilterToAge)
        self.label_4 = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.edtFilterFromAge = QtGui.QSpinBox(StationaryAnalyticsSetupDialog)
        self.edtFilterFromAge.setEnabled(False)
        self.edtFilterFromAge.setMaximum(150)
        self.edtFilterFromAge.setObjectName(_fromUtf8("edtFilterFromAge"))
        self.horizontalLayout_2.addWidget(self.edtFilterFromAge)
        spacerItem = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 21, 1, 1, 3)
        self.cmbDiagType = QtGui.QComboBox(StationaryAnalyticsSetupDialog)
        self.cmbDiagType.setObjectName(_fromUtf8("cmbDiagType"))
        self.cmbDiagType.addItem(_fromUtf8(""))
        self.cmbDiagType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDiagType, 8, 1, 1, 3)
        self.edtEndDate = CDateEdit(StationaryAnalyticsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridLayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.lblFinance = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblFinance.setObjectName(_fromUtf8("lblFinance"))
        self.gridLayout.addWidget(self.lblFinance, 4, 0, 1, 1)
        self.lblMedicalHistory = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblMedicalHistory.setObjectName(_fromUtf8("lblMedicalHistory"))
        self.gridLayout.addWidget(self.lblMedicalHistory, 7, 0, 1, 1)
        self.chkQuotaClass = QtGui.QCheckBox(StationaryAnalyticsSetupDialog)
        self.chkQuotaClass.setObjectName(_fromUtf8("chkQuotaClass"))
        self.gridLayout.addWidget(self.chkQuotaClass, 9, 0, 1, 1)
        self.lblDiagType = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblDiagType.setObjectName(_fromUtf8("lblDiagType"))
        self.gridLayout.addWidget(self.lblDiagType, 8, 0, 1, 1)
        self.cmbAmbCardType = CRBComboBox(StationaryAnalyticsSetupDialog)
        self.cmbAmbCardType.setObjectName(_fromUtf8("cmbAmbCardType"))
        self.cmbAmbCardType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAmbCardType, 6, 1, 1, 3)
        self.lblEndDate = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.cmbFilterAddressType = QtGui.QComboBox(StationaryAnalyticsSetupDialog)
        self.cmbFilterAddressType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressType.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressType.setSizePolicy(sizePolicy)
        self.cmbFilterAddressType.setObjectName(_fromUtf8("cmbFilterAddressType"))
        self.cmbFilterAddressType.addItem(_fromUtf8(""))
        self.cmbFilterAddressType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbFilterAddressType, 16, 3, 1, 1)
        self.edtBegDate = CDateEdit(StationaryAnalyticsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridLayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.cmbContract = CIndependentContractComboBox(StationaryAnalyticsSetupDialog)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.gridLayout.addWidget(self.cmbContract, 5, 1, 1, 3)
        self.lblBegDate = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.cmbQuotaType = CRBComboBox(StationaryAnalyticsSetupDialog)
        self.cmbQuotaType.setObjectName(_fromUtf8("cmbQuotaType"))
        self.gridLayout.addWidget(self.cmbQuotaType, 10, 1, 1, 3)
        self.lblEventTypePurpose = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblEventTypePurpose.setObjectName(_fromUtf8("lblEventTypePurpose"))
        self.gridLayout.addWidget(self.lblEventTypePurpose, 2, 0, 1, 1)
        self.lblAmbCardType = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblAmbCardType.setObjectName(_fromUtf8("lblAmbCardType"))
        self.gridLayout.addWidget(self.lblAmbCardType, 6, 0, 1, 1)
        self.chkDetailClients = QtGui.QCheckBox(StationaryAnalyticsSetupDialog)
        self.chkDetailClients.setObjectName(_fromUtf8("chkDetailClients"))
        self.gridLayout.addWidget(self.chkDetailClients, 13, 0, 1, 4)
        self.cmbMedicalHistoryType = QtGui.QComboBox(StationaryAnalyticsSetupDialog)
        self.cmbMedicalHistoryType.setObjectName(_fromUtf8("cmbMedicalHistoryType"))
        self.cmbMedicalHistoryType.addItem(_fromUtf8(""))
        self.cmbMedicalHistoryType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbMedicalHistoryType, 7, 1, 1, 3)
        self.lblContract = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.gridLayout.addWidget(self.lblContract, 5, 0, 1, 1)
        self.cmbFilterAddressCity = CKLADRComboBox(StationaryAnalyticsSetupDialog)
        self.cmbFilterAddressCity.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressCity.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressCity.setSizePolicy(sizePolicy)
        self.cmbFilterAddressCity.setObjectName(_fromUtf8("cmbFilterAddressCity"))
        self.gridLayout.addWidget(self.cmbFilterAddressCity, 17, 0, 1, 4)
        self.cmbFilterAddressOkato = CKladrOkatoComboBox(StationaryAnalyticsSetupDialog)
        self.cmbFilterAddressOkato.setEnabled(False)
        self.cmbFilterAddressOkato.setObjectName(_fromUtf8("cmbFilterAddressOkato"))
        self.gridLayout.addWidget(self.cmbFilterAddressOkato, 18, 0, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(StationaryAnalyticsSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 24, 0, 1, 4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblFilterAddressHouse = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblFilterAddressHouse.setEnabled(False)
        self.lblFilterAddressHouse.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFilterAddressHouse.setObjectName(_fromUtf8("lblFilterAddressHouse"))
        self.horizontalLayout.addWidget(self.lblFilterAddressHouse)
        self.edtFilterAddressHouse = QtGui.QLineEdit(StationaryAnalyticsSetupDialog)
        self.edtFilterAddressHouse.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterAddressHouse.sizePolicy().hasHeightForWidth())
        self.edtFilterAddressHouse.setSizePolicy(sizePolicy)
        self.edtFilterAddressHouse.setObjectName(_fromUtf8("edtFilterAddressHouse"))
        self.horizontalLayout.addWidget(self.edtFilterAddressHouse)
        self.lblFilterAddressCorpus = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblFilterAddressCorpus.setEnabled(False)
        self.lblFilterAddressCorpus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFilterAddressCorpus.setObjectName(_fromUtf8("lblFilterAddressCorpus"))
        self.horizontalLayout.addWidget(self.lblFilterAddressCorpus)
        self.edtFilterAddressCorpus = QtGui.QLineEdit(StationaryAnalyticsSetupDialog)
        self.edtFilterAddressCorpus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterAddressCorpus.sizePolicy().hasHeightForWidth())
        self.edtFilterAddressCorpus.setSizePolicy(sizePolicy)
        self.edtFilterAddressCorpus.setObjectName(_fromUtf8("edtFilterAddressCorpus"))
        self.horizontalLayout.addWidget(self.edtFilterAddressCorpus)
        self.lblFilterAddressFlat = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblFilterAddressFlat.setEnabled(False)
        self.lblFilterAddressFlat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFilterAddressFlat.setObjectName(_fromUtf8("lblFilterAddressFlat"))
        self.horizontalLayout.addWidget(self.lblFilterAddressFlat)
        self.edtFilterAddressFlat = QtGui.QLineEdit(StationaryAnalyticsSetupDialog)
        self.edtFilterAddressFlat.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterAddressFlat.sizePolicy().hasHeightForWidth())
        self.edtFilterAddressFlat.setSizePolicy(sizePolicy)
        self.edtFilterAddressFlat.setObjectName(_fromUtf8("edtFilterAddressFlat"))
        self.horizontalLayout.addWidget(self.edtFilterAddressFlat)
        self.gridLayout.addLayout(self.horizontalLayout, 20, 0, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 23, 1, 1, 3)
        self.chkFilterAddress = QtGui.QCheckBox(StationaryAnalyticsSetupDialog)
        self.chkFilterAddress.setObjectName(_fromUtf8("chkFilterAddress"))
        self.gridLayout.addWidget(self.chkFilterAddress, 16, 0, 1, 1)
        self.lblQuotaType = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblQuotaType.setObjectName(_fromUtf8("lblQuotaType"))
        self.gridLayout.addWidget(self.lblQuotaType, 10, 0, 1, 1)
        self.cmbFilterAddressStreet = CStreetComboBox(StationaryAnalyticsSetupDialog)
        self.cmbFilterAddressStreet.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressStreet.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressStreet.setSizePolicy(sizePolicy)
        self.cmbFilterAddressStreet.setObjectName(_fromUtf8("cmbFilterAddressStreet"))
        self.gridLayout.addWidget(self.cmbFilterAddressStreet, 19, 0, 1, 4)
        self.cmbFinance = CRBComboBox(StationaryAnalyticsSetupDialog)
        self.cmbFinance.setObjectName(_fromUtf8("cmbFinance"))
        self.gridLayout.addWidget(self.cmbFinance, 4, 1, 1, 3)
        self.lblEventType = QtGui.QLabel(StationaryAnalyticsSetupDialog)
        self.lblEventType.setObjectName(_fromUtf8("lblEventType"))
        self.gridLayout.addWidget(self.lblEventType, 3, 0, 1, 1)
        self.cmbEventTypePurpose = CRBComboBox(StationaryAnalyticsSetupDialog)
        self.cmbEventTypePurpose.setObjectName(_fromUtf8("cmbEventTypePurpose"))
        self.gridLayout.addWidget(self.cmbEventTypePurpose, 2, 1, 1, 3)
        self.cmbEventType = CRBComboBox(StationaryAnalyticsSetupDialog)
        self.cmbEventType.setObjectName(_fromUtf8("cmbEventType"))
        self.gridLayout.addWidget(self.cmbEventType, 3, 1, 1, 3)
        self.chkDetailFinance = QtGui.QCheckBox(StationaryAnalyticsSetupDialog)
        self.chkDetailFinance.setObjectName(_fromUtf8("chkDetailFinance"))
        self.gridLayout.addWidget(self.chkDetailFinance, 11, 0, 1, 4)
        self.chkDetailHospitalBedProfile = QtGui.QCheckBox(StationaryAnalyticsSetupDialog)
        self.chkDetailHospitalBedProfile.setObjectName(_fromUtf8("chkDetailHospitalBedProfile"))
        self.gridLayout.addWidget(self.chkDetailHospitalBedProfile, 12, 0, 1, 4)
        self.edtBegTime = QtGui.QTimeEdit(StationaryAnalyticsSetupDialog)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.gridLayout.addWidget(self.edtBegTime, 0, 2, 1, 1)
        self.edtEndTime = QtGui.QTimeEdit(StationaryAnalyticsSetupDialog)
        self.edtEndTime.setTime(QtCore.QTime(23, 59, 59))
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.gridLayout.addWidget(self.edtEndTime, 1, 2, 1, 1)
        self.chkFilterNoRegion = QtGui.QCheckBox(StationaryAnalyticsSetupDialog)
        self.chkFilterNoRegion.setEnabled(False)
        self.chkFilterNoRegion.setObjectName(_fromUtf8("chkFilterNoRegion"))
        self.gridLayout.addWidget(self.chkFilterNoRegion, 16, 1, 1, 2)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblFilterAddressHouse.setBuddy(self.edtFilterAddressHouse)
        self.lblFilterAddressCorpus.setBuddy(self.edtFilterAddressCorpus)
        self.lblFilterAddressFlat.setBuddy(self.edtFilterAddressFlat)

        self.retranslateUi(StationaryAnalyticsSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), StationaryAnalyticsSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), StationaryAnalyticsSetupDialog.reject)
        QtCore.QObject.connect(self.chkQuotaClass, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbQuotaClass.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(StationaryAnalyticsSetupDialog)
        StationaryAnalyticsSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        StationaryAnalyticsSetupDialog.setTabOrder(self.edtEndDate, self.cmbEventTypePurpose)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbEventTypePurpose, self.cmbEventType)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbEventType, self.cmbFinance)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbFinance, self.cmbContract)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbContract, self.cmbAmbCardType)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbAmbCardType, self.cmbMedicalHistoryType)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbMedicalHistoryType, self.cmbDiagType)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbDiagType, self.chkQuotaClass)
        StationaryAnalyticsSetupDialog.setTabOrder(self.chkQuotaClass, self.cmbQuotaClass)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbQuotaClass, self.cmbQuotaType)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbQuotaType, self.chkDetailClients)
        StationaryAnalyticsSetupDialog.setTabOrder(self.chkDetailClients, self.chkFilterAddress)
        StationaryAnalyticsSetupDialog.setTabOrder(self.chkFilterAddress, self.chkFilterNoRegion)
        StationaryAnalyticsSetupDialog.setTabOrder(self.chkFilterNoRegion, self.cmbFilterAddressType)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbFilterAddressType, self.cmbFilterAddressCity)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbFilterAddressCity, self.cmbFilterAddressOkato)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbFilterAddressOkato, self.cmbFilterAddressStreet)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbFilterAddressStreet, self.edtFilterAddressHouse)
        StationaryAnalyticsSetupDialog.setTabOrder(self.edtFilterAddressHouse, self.edtFilterAddressCorpus)
        StationaryAnalyticsSetupDialog.setTabOrder(self.edtFilterAddressCorpus, self.edtFilterAddressFlat)
        StationaryAnalyticsSetupDialog.setTabOrder(self.edtFilterAddressFlat, self.chkFilterAdditionalOptions)
        StationaryAnalyticsSetupDialog.setTabOrder(self.chkFilterAdditionalOptions, self.cmbFilterSex)
        StationaryAnalyticsSetupDialog.setTabOrder(self.cmbFilterSex, self.edtFilterToAge)
        StationaryAnalyticsSetupDialog.setTabOrder(self.edtFilterToAge, self.edtFilterFromAge)
        StationaryAnalyticsSetupDialog.setTabOrder(self.edtFilterFromAge, self.buttonBox)

    def retranslateUi(self, StationaryAnalyticsSetupDialog):
        StationaryAnalyticsSetupDialog.setWindowTitle(_translate("StationaryAnalyticsSetupDialog", "Dialog", None))
        self.chkFilterAdditionalOptions.setText(_translate("StationaryAnalyticsSetupDialog", "Выводить доп.данные о пациенте", None))
        self.cmbQuotaClass.setItemText(0, _translate("StationaryAnalyticsSetupDialog", "ВТМП", None))
        self.cmbQuotaClass.setItemText(1, _translate("StationaryAnalyticsSetupDialog", "СМП", None))
        self.lblFilterSex.setText(_translate("StationaryAnalyticsSetupDialog", "Пол", None))
        self.cmbFilterSex.setItemText(0, _translate("StationaryAnalyticsSetupDialog", "не определен", None))
        self.cmbFilterSex.setItemText(1, _translate("StationaryAnalyticsSetupDialog", "мужской", None))
        self.cmbFilterSex.setItemText(2, _translate("StationaryAnalyticsSetupDialog", "женский", None))
        self.lblFilterAge.setText(_translate("StationaryAnalyticsSetupDialog", "Возраст с", None))
        self.label_4.setText(_translate("StationaryAnalyticsSetupDialog", "по", None))
        self.cmbDiagType.setItemText(0, _translate("StationaryAnalyticsSetupDialog", "предварительный", None))
        self.cmbDiagType.setItemText(1, _translate("StationaryAnalyticsSetupDialog", "заключительный", None))
        self.lblFinance.setText(_translate("StationaryAnalyticsSetupDialog", "Тип финансирования", None))
        self.lblMedicalHistory.setText(_translate("StationaryAnalyticsSetupDialog", "История болезни", None))
        self.chkQuotaClass.setText(_translate("StationaryAnalyticsSetupDialog", "Класс квоты", None))
        self.lblDiagType.setText(_translate("StationaryAnalyticsSetupDialog", "Диагноз", None))
        self.cmbAmbCardType.setItemText(0, _translate("StationaryAnalyticsSetupDialog", "идентификаторы пациента", None))
        self.lblEndDate.setText(_translate("StationaryAnalyticsSetupDialog", "Дата &окончания периода", None))
        self.cmbFilterAddressType.setItemText(0, _translate("StationaryAnalyticsSetupDialog", "Регистрации", None))
        self.cmbFilterAddressType.setItemText(1, _translate("StationaryAnalyticsSetupDialog", "Проживания", None))
        self.lblBegDate.setText(_translate("StationaryAnalyticsSetupDialog", "Дата &начала периода", None))
        self.lblEventTypePurpose.setText(_translate("StationaryAnalyticsSetupDialog", "Назначение Типа события ", None))
        self.lblAmbCardType.setText(_translate("StationaryAnalyticsSetupDialog", "Карта амбулаторного больного", None))
        self.chkDetailClients.setText(_translate("StationaryAnalyticsSetupDialog", "Детализировать по пациентам", None))
        self.cmbMedicalHistoryType.setItemText(0, _translate("StationaryAnalyticsSetupDialog", "идентификатор события", None))
        self.cmbMedicalHistoryType.setItemText(1, _translate("StationaryAnalyticsSetupDialog", "внешний идентификатор события", None))
        self.lblContract.setText(_translate("StationaryAnalyticsSetupDialog", "Контракт", None))
        self.lblFilterAddressHouse.setText(_translate("StationaryAnalyticsSetupDialog", "Дом", None))
        self.lblFilterAddressCorpus.setText(_translate("StationaryAnalyticsSetupDialog", "Корп", None))
        self.lblFilterAddressFlat.setText(_translate("StationaryAnalyticsSetupDialog", "Кв", None))
        self.chkFilterAddress.setText(_translate("StationaryAnalyticsSetupDialog", "Адрес", None))
        self.lblQuotaType.setText(_translate("StationaryAnalyticsSetupDialog", "Тип квоты", None))
        self.lblEventType.setText(_translate("StationaryAnalyticsSetupDialog", "Тип События", None))
        self.chkDetailFinance.setText(_translate("StationaryAnalyticsSetupDialog", "Детализировать по типам финансирования", None))
        self.chkDetailHospitalBedProfile.setText(_translate("StationaryAnalyticsSetupDialog", "Детализировать по профилям коек", None))
        self.edtBegTime.setDisplayFormat(_translate("StationaryAnalyticsSetupDialog", "HH:mm", None))
        self.edtEndTime.setDisplayFormat(_translate("StationaryAnalyticsSetupDialog", "HH:mm", None))
        self.chkFilterNoRegion.setText(_translate("StationaryAnalyticsSetupDialog", "Другие регионы", None))

from KLADR.kladrComboxes import CKLADRComboBox, CKladrOkatoComboBox, CStreetComboBox
from Orgs.OrgComboBox import CIndependentContractComboBox
from library.DateEdit import CDateEdit
from library.crbcombobox import CRBComboBox

