# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\Reports\TempInvalidF036Setup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TempInvalidF036SetupDialog(object):
    def setupUi(self, TempInvalidF036SetupDialog):
        TempInvalidF036SetupDialog.setObjectName(_fromUtf8("TempInvalidF036SetupDialog"))
        TempInvalidF036SetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        TempInvalidF036SetupDialog.resize(490, 925)
        TempInvalidF036SetupDialog.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(TempInvalidF036SetupDialog)
        self.gridlayout.setMargin(4)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.frmSex = QtGui.QFrame(TempInvalidF036SetupDialog)
        self.frmSex.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmSex.setFrameShadow(QtGui.QFrame.Raised)
        self.frmSex.setObjectName(_fromUtf8("frmSex"))
        self.hboxlayout = QtGui.QHBoxLayout(self.frmSex)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.cmbSex = QtGui.QComboBox(self.frmSex)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.hboxlayout.addWidget(self.cmbSex)
        spacerItem = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.gridlayout.addWidget(self.frmSex, 9, 1, 2, 2)
        self.frmDuration = QtGui.QFrame(TempInvalidF036SetupDialog)
        self.frmDuration.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmDuration.setFrameShadow(QtGui.QFrame.Raised)
        self.frmDuration.setObjectName(_fromUtf8("frmDuration"))
        self.hboxlayout1 = QtGui.QHBoxLayout(self.frmDuration)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(4)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.edtDurationFrom = CSpinBox(self.frmDuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDurationFrom.sizePolicy().hasHeightForWidth())
        self.edtDurationFrom.setSizePolicy(sizePolicy)
        self.edtDurationFrom.setMaximum(366)
        self.edtDurationFrom.setObjectName(_fromUtf8("edtDurationFrom"))
        self.hboxlayout1.addWidget(self.edtDurationFrom)
        self.lblDurationTo = QtGui.QLabel(self.frmDuration)
        self.lblDurationTo.setObjectName(_fromUtf8("lblDurationTo"))
        self.hboxlayout1.addWidget(self.lblDurationTo)
        self.edtDurationTo = CSpinBox(self.frmDuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDurationTo.sizePolicy().hasHeightForWidth())
        self.edtDurationTo.setSizePolicy(sizePolicy)
        self.edtDurationTo.setMaximum(366)
        self.edtDurationTo.setObjectName(_fromUtf8("edtDurationTo"))
        self.hboxlayout1.addWidget(self.edtDurationTo)
        self.lblDurationDays = QtGui.QLabel(self.frmDuration)
        self.lblDurationDays.setObjectName(_fromUtf8("lblDurationDays"))
        self.hboxlayout1.addWidget(self.lblDurationDays)
        spacerItem1 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.gridlayout.addWidget(self.frmDuration, 8, 1, 1, 2)
        self.frmAge = QtGui.QFrame(TempInvalidF036SetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self.hboxlayout2 = QtGui.QHBoxLayout(self.frmAge)
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setSpacing(4)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.edtAgeFrom = CSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.hboxlayout2.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.hboxlayout2.addWidget(self.lblAgeTo)
        self.edtAgeTo = CSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.hboxlayout2.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.hboxlayout2.addWidget(self.lblAgeYears)
        spacerItem2 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem2)
        self.gridlayout.addWidget(self.frmAge, 11, 1, 1, 2)
        self.frmMKB = QtGui.QFrame(TempInvalidF036SetupDialog)
        self.frmMKB.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMKB.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMKB.setObjectName(_fromUtf8("frmMKB"))
        self.gridlayout1 = QtGui.QGridLayout(self.frmMKB)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setHorizontalSpacing(4)
        self.gridlayout1.setVerticalSpacing(0)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.cmbMKBFilter = QtGui.QComboBox(self.frmMKB)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.gridlayout1.addWidget(self.cmbMKBFilter, 0, 0, 1, 1)
        self.edtMKBFrom = CICDCodeEdit(self.frmMKB)
        self.edtMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.gridlayout1.addWidget(self.edtMKBFrom, 0, 1, 1, 1)
        self.edtMKBTo = CICDCodeEdit(self.frmMKB)
        self.edtMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.gridlayout1.addWidget(self.edtMKBTo, 0, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem3, 0, 3, 1, 1)
        self.gridlayout.addWidget(self.frmMKB, 15, 1, 1, 2)
        self.lblMKB = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.gridlayout.addWidget(self.lblMKB, 15, 0, 1, 1)
        self.lblDuration = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblDuration.setObjectName(_fromUtf8("lblDuration"))
        self.gridlayout.addWidget(self.lblDuration, 8, 0, 2, 1)
        self.chkTempInvalidNoExternal = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkTempInvalidNoExternal.setChecked(True)
        self.chkTempInvalidNoExternal.setObjectName(_fromUtf8("chkTempInvalidNoExternal"))
        self.gridlayout.addWidget(self.chkTempInvalidNoExternal, 31, 1, 1, 2)
        self.chkTempInvalidDuplicate = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkTempInvalidDuplicate.setObjectName(_fromUtf8("chkTempInvalidDuplicate"))
        self.gridlayout.addWidget(self.chkTempInvalidDuplicate, 29, 1, 1, 2)
        self.edtBegDate = CDateEdit(TempInvalidF036SetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridlayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.lblTempInvalidReason = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblTempInvalidReason.setObjectName(_fromUtf8("lblTempInvalidReason"))
        self.gridlayout.addWidget(self.lblTempInvalidReason, 4, 0, 1, 1)
        self.lblBegDate = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridlayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(TempInvalidF036SetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 40, 0, 1, 3)
        self.lblOrgStructure = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridlayout.addWidget(self.lblOrgStructure, 6, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridlayout.addWidget(self.lblPerson, 7, 0, 1, 1)
        self.lblDocType = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblDocType.setObjectName(_fromUtf8("lblDocType"))
        self.gridlayout.addWidget(self.lblDocType, 3, 0, 1, 1)
        self.chkBeginPerson = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkBeginPerson.setObjectName(_fromUtf8("chkBeginPerson"))
        self.gridlayout.addWidget(self.chkBeginPerson, 26, 1, 1, 2)
        self.lblSocStatusType = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblSocStatusType.setObjectName(_fromUtf8("lblSocStatusType"))
        self.gridlayout.addWidget(self.lblSocStatusType, 14, 0, 1, 1)
        self.chkRegAddress = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkRegAddress.setChecked(True)
        self.chkRegAddress.setObjectName(_fromUtf8("chkRegAddress"))
        self.gridlayout.addWidget(self.chkRegAddress, 23, 1, 1, 2)
        self.cmbOrgStructure = COrgStructureComboBox(TempInvalidF036SetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridlayout.addWidget(self.cmbOrgStructure, 6, 1, 1, 2)
        self.lblDataSort = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblDataSort.setObjectName(_fromUtf8("lblDataSort"))
        self.gridlayout.addWidget(self.lblDataSort, 35, 0, 1, 1)
        self.cmbPeriodIssueDate = QtGui.QComboBox(TempInvalidF036SetupDialog)
        self.cmbPeriodIssueDate.setObjectName(_fromUtf8("cmbPeriodIssueDate"))
        self.cmbPeriodIssueDate.addItem(_fromUtf8(""))
        self.cmbPeriodIssueDate.addItem(_fromUtf8(""))
        self.cmbPeriodIssueDate.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbPeriodIssueDate, 2, 1, 1, 2)
        self.lblSex = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridlayout.addWidget(self.lblSex, 10, 0, 1, 1)
        self.lblPeriodIssueDate = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblPeriodIssueDate.setObjectName(_fromUtf8("lblPeriodIssueDate"))
        self.gridlayout.addWidget(self.lblPeriodIssueDate, 2, 0, 1, 1)
        self.chkDateSort = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkDateSort.setChecked(True)
        self.chkDateSort.setObjectName(_fromUtf8("chkDateSort"))
        self.gridlayout.addWidget(self.chkDateSort, 35, 1, 1, 1)
        self.lblSocStatusClass = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblSocStatusClass.setObjectName(_fromUtf8("lblSocStatusClass"))
        self.gridlayout.addWidget(self.lblSocStatusClass, 12, 0, 1, 1)
        self.chkShowMKBDescription = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkShowMKBDescription.setChecked(True)
        self.chkShowMKBDescription.setObjectName(_fromUtf8("chkShowMKBDescription"))
        self.gridlayout.addWidget(self.chkShowMKBDescription, 32, 1, 1, 2)
        self.lblEndDate = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridlayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.cmbDoctype = CRBComboBox(TempInvalidF036SetupDialog)
        self.cmbDoctype.setObjectName(_fromUtf8("cmbDoctype"))
        self.gridlayout.addWidget(self.cmbDoctype, 3, 1, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem4, 18, 2, 1, 1)
        self.cmbSocStatusClass = CSocStatusComboBox(TempInvalidF036SetupDialog)
        self.cmbSocStatusClass.setObjectName(_fromUtf8("cmbSocStatusClass"))
        self.gridlayout.addWidget(self.cmbSocStatusClass, 12, 1, 1, 2)
        self.edtEndDate = CDateEdit(TempInvalidF036SetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridlayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.lblAge = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridlayout.addWidget(self.lblAge, 11, 0, 1, 1)
        self.chkOnlyClosed = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkOnlyClosed.setChecked(True)
        self.chkOnlyClosed.setObjectName(_fromUtf8("chkOnlyClosed"))
        self.gridlayout.addWidget(self.chkOnlyClosed, 5, 1, 1, 2)
        self.chkAverageDuration = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkAverageDuration.setObjectName(_fromUtf8("chkAverageDuration"))
        self.gridlayout.addWidget(self.chkAverageDuration, 20, 1, 1, 2)
        self.chkLocAddress = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkLocAddress.setChecked(True)
        self.chkLocAddress.setObjectName(_fromUtf8("chkLocAddress"))
        self.gridlayout.addWidget(self.chkLocAddress, 25, 1, 1, 2)
        self.chkResultsForGroups = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkResultsForGroups.setObjectName(_fromUtf8("chkResultsForGroups"))
        self.gridlayout.addWidget(self.chkResultsForGroups, 22, 1, 1, 2)
        self.chkShowPersonSpeciality = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkShowPersonSpeciality.setChecked(True)
        self.chkShowPersonSpeciality.setObjectName(_fromUtf8("chkShowPersonSpeciality"))
        self.gridlayout.addWidget(self.chkShowPersonSpeciality, 33, 1, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem5, 0, 2, 1, 1)
        self.chkPlaceWork = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkPlaceWork.setObjectName(_fromUtf8("chkPlaceWork"))
        self.gridlayout.addWidget(self.chkPlaceWork, 28, 1, 1, 2)
        self.cmbInsuranceOfficeMark = QtGui.QComboBox(TempInvalidF036SetupDialog)
        self.cmbInsuranceOfficeMark.setObjectName(_fromUtf8("cmbInsuranceOfficeMark"))
        self.cmbInsuranceOfficeMark.addItem(_fromUtf8(""))
        self.cmbInsuranceOfficeMark.setItemText(0, _fromUtf8(""))
        self.cmbInsuranceOfficeMark.addItem(_fromUtf8(""))
        self.cmbInsuranceOfficeMark.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbInsuranceOfficeMark, 17, 1, 1, 2)
        self.cmbReason = CRBComboBox(TempInvalidF036SetupDialog)
        self.cmbReason.setObjectName(_fromUtf8("cmbReason"))
        self.gridlayout.addWidget(self.cmbReason, 4, 1, 1, 2)
        self.cmbPerson = CPersonComboBoxEx(TempInvalidF036SetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbPerson, 7, 1, 1, 2)
        self.edtCntUser = CSpinBox(TempInvalidF036SetupDialog)
        self.edtCntUser.setMinimum(1)
        self.edtCntUser.setMaximum(999999999)
        self.edtCntUser.setObjectName(_fromUtf8("edtCntUser"))
        self.gridlayout.addWidget(self.edtCntUser, 18, 1, 1, 1)
        self.cmbDateSort = QtGui.QComboBox(TempInvalidF036SetupDialog)
        self.cmbDateSort.setObjectName(_fromUtf8("cmbDateSort"))
        self.cmbDateSort.addItem(_fromUtf8(""))
        self.cmbDateSort.addItem(_fromUtf8(""))
        self.cmbDateSort.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbDateSort, 35, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(21, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem6, 39, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem7, 1, 2, 1, 1)
        self.lblInsuranceOfficeMark = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblInsuranceOfficeMark.setObjectName(_fromUtf8("lblInsuranceOfficeMark"))
        self.gridlayout.addWidget(self.lblInsuranceOfficeMark, 17, 0, 1, 1)
        self.cmbSocStatusType = CRBComboBox(TempInvalidF036SetupDialog)
        self.cmbSocStatusType.setObjectName(_fromUtf8("cmbSocStatusType"))
        self.gridlayout.addWidget(self.cmbSocStatusType, 14, 1, 1, 2)
        self.chkNumberSort = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkNumberSort.setObjectName(_fromUtf8("chkNumberSort"))
        self.gridlayout.addWidget(self.chkNumberSort, 38, 1, 1, 2)
        self.chkEndPerson = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkEndPerson.setObjectName(_fromUtf8("chkEndPerson"))
        self.gridlayout.addWidget(self.chkEndPerson, 27, 1, 1, 2)
        self.chkClientNameSort = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkClientNameSort.setObjectName(_fromUtf8("chkClientNameSort"))
        self.gridlayout.addWidget(self.chkClientNameSort, 37, 1, 1, 2)
        self.chkTempInvalidDuplicateWork = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkTempInvalidDuplicateWork.setObjectName(_fromUtf8("chkTempInvalidDuplicateWork"))
        self.gridlayout.addWidget(self.chkTempInvalidDuplicateWork, 30, 1, 1, 2)
        self.lblCntUser = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblCntUser.setObjectName(_fromUtf8("lblCntUser"))
        self.gridlayout.addWidget(self.lblCntUser, 18, 0, 1, 1)
        self.chkShowTempInvalidStatus = QtGui.QCheckBox(TempInvalidF036SetupDialog)
        self.chkShowTempInvalidStatus.setObjectName(_fromUtf8("chkShowTempInvalidStatus"))
        self.gridlayout.addWidget(self.chkShowTempInvalidStatus, 34, 1, 1, 2)
        self.lblShow = QtGui.QLabel(TempInvalidF036SetupDialog)
        self.lblShow.setObjectName(_fromUtf8("lblShow"))
        self.gridlayout.addWidget(self.lblShow, 19, 0, 1, 1)
        self.cmbShowTempInvalidReceiver = QtGui.QComboBox(TempInvalidF036SetupDialog)
        self.cmbShowTempInvalidReceiver.setObjectName(_fromUtf8("cmbShowTempInvalidReceiver"))
        self.cmbShowTempInvalidReceiver.addItem(_fromUtf8(""))
        self.cmbShowTempInvalidReceiver.setItemText(0, _fromUtf8(""))
        self.cmbShowTempInvalidReceiver.addItem(_fromUtf8(""))
        self.cmbShowTempInvalidReceiver.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbShowTempInvalidReceiver, 19, 1, 1, 2)
        self.lblDurationTo.setBuddy(self.edtDurationTo)
        self.lblDurationDays.setBuddy(self.edtDurationTo)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblMKB.setBuddy(self.cmbMKBFilter)
        self.lblDuration.setBuddy(self.edtDurationFrom)
        self.lblTempInvalidReason.setBuddy(self.cmbReason)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblDocType.setBuddy(self.cmbDoctype)
        self.lblSocStatusType.setBuddy(self.cmbSocStatusType)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblSocStatusClass.setBuddy(self.cmbSocStatusClass)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblInsuranceOfficeMark.setBuddy(self.cmbInsuranceOfficeMark)

        self.retranslateUi(TempInvalidF036SetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TempInvalidF036SetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TempInvalidF036SetupDialog.reject)
        QtCore.QObject.connect(self.chkDateSort, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbDateSort.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TempInvalidF036SetupDialog)
        TempInvalidF036SetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        TempInvalidF036SetupDialog.setTabOrder(self.edtEndDate, self.cmbPeriodIssueDate)
        TempInvalidF036SetupDialog.setTabOrder(self.cmbPeriodIssueDate, self.cmbDoctype)
        TempInvalidF036SetupDialog.setTabOrder(self.cmbDoctype, self.cmbReason)
        TempInvalidF036SetupDialog.setTabOrder(self.cmbReason, self.chkOnlyClosed)
        TempInvalidF036SetupDialog.setTabOrder(self.chkOnlyClosed, self.cmbOrgStructure)
        TempInvalidF036SetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbPerson)
        TempInvalidF036SetupDialog.setTabOrder(self.cmbPerson, self.edtDurationFrom)
        TempInvalidF036SetupDialog.setTabOrder(self.edtDurationFrom, self.edtDurationTo)
        TempInvalidF036SetupDialog.setTabOrder(self.edtDurationTo, self.cmbSex)
        TempInvalidF036SetupDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        TempInvalidF036SetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        TempInvalidF036SetupDialog.setTabOrder(self.edtAgeTo, self.cmbSocStatusClass)
        TempInvalidF036SetupDialog.setTabOrder(self.cmbSocStatusClass, self.cmbSocStatusType)
        TempInvalidF036SetupDialog.setTabOrder(self.cmbSocStatusType, self.cmbMKBFilter)
        TempInvalidF036SetupDialog.setTabOrder(self.cmbMKBFilter, self.edtMKBFrom)
        TempInvalidF036SetupDialog.setTabOrder(self.edtMKBFrom, self.edtMKBTo)
        TempInvalidF036SetupDialog.setTabOrder(self.edtMKBTo, self.cmbInsuranceOfficeMark)
        TempInvalidF036SetupDialog.setTabOrder(self.cmbInsuranceOfficeMark, self.edtCntUser)
        TempInvalidF036SetupDialog.setTabOrder(self.edtCntUser, self.chkAverageDuration)
        TempInvalidF036SetupDialog.setTabOrder(self.chkAverageDuration, self.chkBeginPerson)
        TempInvalidF036SetupDialog.setTabOrder(self.chkBeginPerson, self.chkResultsForGroups)
        TempInvalidF036SetupDialog.setTabOrder(self.chkResultsForGroups, self.chkLocAddress)
        TempInvalidF036SetupDialog.setTabOrder(self.chkLocAddress, self.chkEndPerson)
        TempInvalidF036SetupDialog.setTabOrder(self.chkEndPerson, self.chkPlaceWork)
        TempInvalidF036SetupDialog.setTabOrder(self.chkPlaceWork, self.chkTempInvalidDuplicate)
        TempInvalidF036SetupDialog.setTabOrder(self.chkTempInvalidDuplicate, self.chkTempInvalidDuplicateWork)
        TempInvalidF036SetupDialog.setTabOrder(self.chkTempInvalidDuplicateWork, self.chkTempInvalidNoExternal)
        TempInvalidF036SetupDialog.setTabOrder(self.chkTempInvalidNoExternal, self.chkDateSort)
        TempInvalidF036SetupDialog.setTabOrder(self.chkDateSort, self.cmbDateSort)
        TempInvalidF036SetupDialog.setTabOrder(self.cmbDateSort, self.chkClientNameSort)
        TempInvalidF036SetupDialog.setTabOrder(self.chkClientNameSort, self.chkNumberSort)
        TempInvalidF036SetupDialog.setTabOrder(self.chkNumberSort, self.buttonBox)
        TempInvalidF036SetupDialog.setTabOrder(self.buttonBox, self.chkRegAddress)
        TempInvalidF036SetupDialog.setTabOrder(self.chkRegAddress, self.chkShowMKBDescription)
        TempInvalidF036SetupDialog.setTabOrder(self.chkShowMKBDescription, self.chkShowPersonSpeciality)

    def retranslateUi(self, TempInvalidF036SetupDialog):
        TempInvalidF036SetupDialog.setWindowTitle(_translate("TempInvalidF036SetupDialog", "параметры отчёта", None))
        self.cmbSex.setItemText(1, _translate("TempInvalidF036SetupDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("TempInvalidF036SetupDialog", "Ж", None))
        self.lblDurationTo.setText(_translate("TempInvalidF036SetupDialog", "по", None))
        self.lblDurationDays.setText(_translate("TempInvalidF036SetupDialog", "дней", None))
        self.lblAgeTo.setText(_translate("TempInvalidF036SetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("TempInvalidF036SetupDialog", "лет", None))
        self.cmbMKBFilter.setItemText(0, _translate("TempInvalidF036SetupDialog", "Игнор.", None))
        self.cmbMKBFilter.setItemText(1, _translate("TempInvalidF036SetupDialog", "Интервал", None))
        self.cmbMKBFilter.setItemText(2, _translate("TempInvalidF036SetupDialog", "Без диагноза", None))
        self.edtMKBFrom.setInputMask(_translate("TempInvalidF036SetupDialog", "a00.00; ", None))
        self.edtMKBFrom.setText(_translate("TempInvalidF036SetupDialog", "A.", None))
        self.edtMKBTo.setInputMask(_translate("TempInvalidF036SetupDialog", "a00.00; ", None))
        self.edtMKBTo.setText(_translate("TempInvalidF036SetupDialog", "Z99.9", None))
        self.lblMKB.setText(_translate("TempInvalidF036SetupDialog", "Коды диагнозов по &МКБ", None))
        self.lblDuration.setText(_translate("TempInvalidF036SetupDialog", "&Длительность с", None))
        self.chkTempInvalidNoExternal.setText(_translate("TempInvalidF036SetupDialog", "Не отображать строки внешних ЛН", None))
        self.chkTempInvalidDuplicate.setText(_translate("TempInvalidF036SetupDialog", "Выводить листы по совместительству", None))
        self.edtBegDate.setDisplayFormat(_translate("TempInvalidF036SetupDialog", "dd.MM.yyyy", None))
        self.lblTempInvalidReason.setText(_translate("TempInvalidF036SetupDialog", "При&чина", None))
        self.lblBegDate.setText(_translate("TempInvalidF036SetupDialog", "Дата &начала периода", None))
        self.lblOrgStructure.setText(_translate("TempInvalidF036SetupDialog", "&Подразделение", None))
        self.lblPerson.setText(_translate("TempInvalidF036SetupDialog", "&Врач", None))
        self.lblDocType.setText(_translate("TempInvalidF036SetupDialog", "Тип &документа", None))
        self.chkBeginPerson.setText(_translate("TempInvalidF036SetupDialog", "Начавший ЛН", None))
        self.lblSocStatusType.setText(_translate("TempInvalidF036SetupDialog", "Тип соц.статуса", None))
        self.chkRegAddress.setText(_translate("TempInvalidF036SetupDialog", "Адрес регистрации", None))
        self.lblDataSort.setText(_translate("TempInvalidF036SetupDialog", "Сортировать", None))
        self.cmbPeriodIssueDate.setItemText(0, _translate("TempInvalidF036SetupDialog", "дате окончания случая", None))
        self.cmbPeriodIssueDate.setItemText(1, _translate("TempInvalidF036SetupDialog", "периоду случая", None))
        self.cmbPeriodIssueDate.setItemText(2, _translate("TempInvalidF036SetupDialog", "дате выдаче ЛН", None))
        self.lblSex.setText(_translate("TempInvalidF036SetupDialog", "По&л", None))
        self.lblPeriodIssueDate.setText(_translate("TempInvalidF036SetupDialog", "Отчёт по", None))
        self.chkDateSort.setText(_translate("TempInvalidF036SetupDialog", "по дате", None))
        self.lblSocStatusClass.setText(_translate("TempInvalidF036SetupDialog", "Класс соц.статуса", None))
        self.chkShowMKBDescription.setText(_translate("TempInvalidF036SetupDialog", "Отображать описание диагноза", None))
        self.lblEndDate.setText(_translate("TempInvalidF036SetupDialog", "Дата &окончания периода", None))
        self.edtEndDate.setDisplayFormat(_translate("TempInvalidF036SetupDialog", "dd.MM.yyyy", None))
        self.lblAge.setText(_translate("TempInvalidF036SetupDialog", "Во&зраст с", None))
        self.chkOnlyClosed.setText(_translate("TempInvalidF036SetupDialog", "&Только &закрытые", None))
        self.chkAverageDuration.setText(_translate("TempInvalidF036SetupDialog", "Средняя длительность", None))
        self.chkLocAddress.setText(_translate("TempInvalidF036SetupDialog", "Адрес проживания", None))
        self.chkResultsForGroups.setText(_translate("TempInvalidF036SetupDialog", "Выводить итоги для групп", None))
        self.chkShowPersonSpeciality.setText(_translate("TempInvalidF036SetupDialog", "Отображать специальность врача", None))
        self.chkPlaceWork.setText(_translate("TempInvalidF036SetupDialog", "Место работы", None))
        self.cmbInsuranceOfficeMark.setItemText(1, _translate("TempInvalidF036SetupDialog", "без отметки", None))
        self.cmbInsuranceOfficeMark.setItemText(2, _translate("TempInvalidF036SetupDialog", "с отметкой", None))
        self.cmbPerson.setItemText(0, _translate("TempInvalidF036SetupDialog", "Врач", None))
        self.cmbDateSort.setItemText(0, _translate("TempInvalidF036SetupDialog", "начала случая", None))
        self.cmbDateSort.setItemText(1, _translate("TempInvalidF036SetupDialog", "начала ЛН", None))
        self.cmbDateSort.setItemText(2, _translate("TempInvalidF036SetupDialog", "дате выдачи", None))
        self.lblInsuranceOfficeMark.setText(_translate("TempInvalidF036SetupDialog", "&Отметка страхового стола", None))
        self.chkNumberSort.setText(_translate("TempInvalidF036SetupDialog", "по номеру ЛН", None))
        self.chkEndPerson.setText(_translate("TempInvalidF036SetupDialog", "Закончивший ЛН", None))
        self.chkClientNameSort.setText(_translate("TempInvalidF036SetupDialog", "по ФИО пациента ", None))
        self.chkTempInvalidDuplicateWork.setText(_translate("TempInvalidF036SetupDialog", "Включать дубликаты ЛН", None))
        self.lblCntUser.setText(_translate("TempInvalidF036SetupDialog", "Номер строки с", None))
        self.chkShowTempInvalidStatus.setText(_translate("TempInvalidF036SetupDialog", "Вывести результат ЛН", None))
        self.lblShow.setText(_translate("TempInvalidF036SetupDialog", "Отображать", None))
        self.cmbShowTempInvalidReceiver.setItemText(1, _translate("TempInvalidF036SetupDialog", "данные Лица по уходу", None))
        self.cmbShowTempInvalidReceiver.setItemText(2, _translate("TempInvalidF036SetupDialog", "адрес получателя", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Registry.SocStatusComboBox import CSocStatusComboBox
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEdit
from library.SpinBox import CSpinBox
from library.crbcombobox import CRBComboBox
