# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './TempInvalidSetup.ui'
#
# Created: Tue Jun 10 12:18:48 2025
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TempInvalidSetupDialog(object):
    def setupUi(self, TempInvalidSetupDialog):
        TempInvalidSetupDialog.setObjectName(_fromUtf8("TempInvalidSetupDialog"))
        TempInvalidSetupDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        TempInvalidSetupDialog.resize(416, 798)
        TempInvalidSetupDialog.setSizeGripEnabled(True)
        self.gridlayout = QtGui.QGridLayout(TempInvalidSetupDialog)
        self.gridlayout.setSpacing(4)
        self.gridlayout.setMargin(4)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.chkTempInvalidDuplicate = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkTempInvalidDuplicate.setObjectName(_fromUtf8("chkTempInvalidDuplicate"))
        self.gridlayout.addWidget(self.chkTempInvalidDuplicate, 33, 1, 1, 2)
        self.cmbDateSort = QtGui.QComboBox(TempInvalidSetupDialog)
        self.cmbDateSort.setObjectName(_fromUtf8("cmbDateSort"))
        self.cmbDateSort.addItem(_fromUtf8(""))
        self.cmbDateSort.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbDateSort, 37, 1, 1, 2)
        self.chkTempInvalidReceiver = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkTempInvalidReceiver.setObjectName(_fromUtf8("chkTempInvalidReceiver"))
        self.gridlayout.addWidget(self.chkTempInvalidReceiver, 31, 1, 1, 2)
        self.lblDateSort = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblDateSort.setObjectName(_fromUtf8("lblDateSort"))
        self.gridlayout.addWidget(self.lblDateSort, 37, 0, 1, 1)
        self.lblTempInvalidReason = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblTempInvalidReason.setObjectName(_fromUtf8("lblTempInvalidReason"))
        self.gridlayout.addWidget(self.lblTempInvalidReason, 5, 0, 1, 1)
        self.chkByPeriod = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkByPeriod.setObjectName(_fromUtf8("chkByPeriod"))
        self.gridlayout.addWidget(self.chkByPeriod, 2, 1, 1, 2)
        self.edtBegDate = CDateEdit(TempInvalidSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.gridlayout.addWidget(self.edtBegDate, 0, 1, 1, 1)
        self.lblAge = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridlayout.addWidget(self.lblAge, 12, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridlayout.addWidget(self.lblPerson, 8, 0, 1, 1)
        self.cmbDoctype = CRBComboBox(TempInvalidSetupDialog)
        self.cmbDoctype.setObjectName(_fromUtf8("cmbDoctype"))
        self.gridlayout.addWidget(self.cmbDoctype, 3, 1, 1, 2)
        self.lblInsuranceOfficeMark = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblInsuranceOfficeMark.setObjectName(_fromUtf8("lblInsuranceOfficeMark"))
        self.gridlayout.addWidget(self.lblInsuranceOfficeMark, 17, 0, 1, 1)
        self.cmbInsuranceOfficeMark = QtGui.QComboBox(TempInvalidSetupDialog)
        self.cmbInsuranceOfficeMark.setObjectName(_fromUtf8("cmbInsuranceOfficeMark"))
        self.cmbInsuranceOfficeMark.addItem(_fromUtf8(""))
        self.cmbInsuranceOfficeMark.setItemText(0, _fromUtf8(""))
        self.cmbInsuranceOfficeMark.addItem(_fromUtf8(""))
        self.cmbInsuranceOfficeMark.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbInsuranceOfficeMark, 17, 1, 1, 2)
        self.lblSex = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridlayout.addWidget(self.lblSex, 11, 0, 1, 1)
        self.cmbSocStatusClass = CSocStatusComboBox(TempInvalidSetupDialog)
        self.cmbSocStatusClass.setObjectName(_fromUtf8("cmbSocStatusClass"))
        self.gridlayout.addWidget(self.cmbSocStatusClass, 13, 1, 1, 2)
        self.lblMKB = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.gridlayout.addWidget(self.lblMKB, 16, 0, 1, 1)
        self.frmDuration = QtGui.QFrame(TempInvalidSetupDialog)
        self.frmDuration.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmDuration.setFrameShadow(QtGui.QFrame.Raised)
        self.frmDuration.setObjectName(_fromUtf8("frmDuration"))
        self.hboxlayout = QtGui.QHBoxLayout(self.frmDuration)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.edtDurationFrom = QtGui.QSpinBox(self.frmDuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDurationFrom.sizePolicy().hasHeightForWidth())
        self.edtDurationFrom.setSizePolicy(sizePolicy)
        self.edtDurationFrom.setMaximum(366)
        self.edtDurationFrom.setObjectName(_fromUtf8("edtDurationFrom"))
        self.hboxlayout.addWidget(self.edtDurationFrom)
        self.lblDurationTo = QtGui.QLabel(self.frmDuration)
        self.lblDurationTo.setObjectName(_fromUtf8("lblDurationTo"))
        self.hboxlayout.addWidget(self.lblDurationTo)
        self.edtDurationTo = QtGui.QSpinBox(self.frmDuration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDurationTo.sizePolicy().hasHeightForWidth())
        self.edtDurationTo.setSizePolicy(sizePolicy)
        self.edtDurationTo.setMaximum(366)
        self.edtDurationTo.setObjectName(_fromUtf8("edtDurationTo"))
        self.hboxlayout.addWidget(self.edtDurationTo)
        self.lblDurationDays = QtGui.QLabel(self.frmDuration)
        self.lblDurationDays.setObjectName(_fromUtf8("lblDurationDays"))
        self.hboxlayout.addWidget(self.lblDurationDays)
        spacerItem = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.gridlayout.addWidget(self.frmDuration, 9, 1, 1, 2)
        self.frmAge = QtGui.QFrame(TempInvalidSetupDialog)
        self.frmAge.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAge.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAge.setObjectName(_fromUtf8("frmAge"))
        self.hboxlayout1 = QtGui.QHBoxLayout(self.frmAge)
        self.hboxlayout1.setSpacing(4)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.edtAgeFrom = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeFrom.sizePolicy().hasHeightForWidth())
        self.edtAgeFrom.setSizePolicy(sizePolicy)
        self.edtAgeFrom.setMaximum(150)
        self.edtAgeFrom.setObjectName(_fromUtf8("edtAgeFrom"))
        self.hboxlayout1.addWidget(self.edtAgeFrom)
        self.lblAgeTo = QtGui.QLabel(self.frmAge)
        self.lblAgeTo.setObjectName(_fromUtf8("lblAgeTo"))
        self.hboxlayout1.addWidget(self.lblAgeTo)
        self.edtAgeTo = QtGui.QSpinBox(self.frmAge)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAgeTo.sizePolicy().hasHeightForWidth())
        self.edtAgeTo.setSizePolicy(sizePolicy)
        self.edtAgeTo.setMaximum(150)
        self.edtAgeTo.setObjectName(_fromUtf8("edtAgeTo"))
        self.hboxlayout1.addWidget(self.edtAgeTo)
        self.lblAgeYears = QtGui.QLabel(self.frmAge)
        self.lblAgeYears.setObjectName(_fromUtf8("lblAgeYears"))
        self.hboxlayout1.addWidget(self.lblAgeYears)
        spacerItem1 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.gridlayout.addWidget(self.frmAge, 12, 1, 1, 2)
        self.frmMKB = QtGui.QFrame(TempInvalidSetupDialog)
        self.frmMKB.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMKB.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMKB.setObjectName(_fromUtf8("frmMKB"))
        self.gridlayout1 = QtGui.QGridLayout(self.frmMKB)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setHorizontalSpacing(4)
        self.gridlayout1.setVerticalSpacing(0)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.cmbMKBFilter = QtGui.QComboBox(self.frmMKB)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.gridlayout1.addWidget(self.cmbMKBFilter, 0, 0, 1, 1)
        self.edtMKBFrom = CICDCodeEdit(self.frmMKB)
        self.edtMKBFrom.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.gridlayout1.addWidget(self.edtMKBFrom, 0, 1, 1, 1)
        self.edtMKBTo = CICDCodeEdit(self.frmMKB)
        self.edtMKBTo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.gridlayout1.addWidget(self.edtMKBTo, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem2, 0, 3, 1, 1)
        self.gridlayout.addWidget(self.frmMKB, 16, 1, 1, 2)
        self.frmSex = QtGui.QFrame(TempInvalidSetupDialog)
        self.frmSex.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmSex.setFrameShadow(QtGui.QFrame.Raised)
        self.frmSex.setObjectName(_fromUtf8("frmSex"))
        self.hboxlayout2 = QtGui.QHBoxLayout(self.frmSex)
        self.hboxlayout2.setSpacing(4)
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.cmbSex = QtGui.QComboBox(self.frmSex)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.hboxlayout2.addWidget(self.cmbSex)
        spacerItem3 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem3)
        self.gridlayout.addWidget(self.frmSex, 10, 1, 2, 2)
        self.edtEndDate = CDateEdit(TempInvalidSetupDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.gridlayout.addWidget(self.edtEndDate, 1, 1, 1, 1)
        self.chkOnlyClosed = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkOnlyClosed.setChecked(True)
        self.chkOnlyClosed.setObjectName(_fromUtf8("chkOnlyClosed"))
        self.gridlayout.addWidget(self.chkOnlyClosed, 6, 1, 1, 2)
        self.lblEndDate = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridlayout.addWidget(self.lblEndDate, 1, 0, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridlayout.addWidget(self.lblOrgStructure, 7, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(21, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem4, 24, 0, 1, 1)
        self.lblBegDate = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridlayout.addWidget(self.lblBegDate, 0, 0, 1, 1)
        self.lblDocType = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblDocType.setObjectName(_fromUtf8("lblDocType"))
        self.gridlayout.addWidget(self.lblDocType, 3, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(TempInvalidSetupDialog)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbPerson, 8, 1, 1, 2)
        self.chkLocAddress = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkLocAddress.setChecked(True)
        self.chkLocAddress.setObjectName(_fromUtf8("chkLocAddress"))
        self.gridlayout.addWidget(self.chkLocAddress, 26, 1, 1, 2)
        self.lblSocStatusType = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblSocStatusType.setObjectName(_fromUtf8("lblSocStatusType"))
        self.gridlayout.addWidget(self.lblSocStatusType, 15, 0, 1, 1)
        self.chkResultsForGroups = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkResultsForGroups.setObjectName(_fromUtf8("chkResultsForGroups"))
        self.gridlayout.addWidget(self.chkResultsForGroups, 21, 1, 1, 2)
        self.chkRegAddress = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkRegAddress.setChecked(True)
        self.chkRegAddress.setObjectName(_fromUtf8("chkRegAddress"))
        self.gridlayout.addWidget(self.chkRegAddress, 25, 1, 1, 2)
        self.cmbSocStatusType = CRBComboBox(TempInvalidSetupDialog)
        self.cmbSocStatusType.setObjectName(_fromUtf8("cmbSocStatusType"))
        self.gridlayout.addWidget(self.cmbSocStatusType, 15, 1, 1, 2)
        self.chkClientNameSort = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkClientNameSort.setObjectName(_fromUtf8("chkClientNameSort"))
        self.gridlayout.addWidget(self.chkClientNameSort, 38, 1, 1, 2)
        self.edtCntUser = QtGui.QSpinBox(TempInvalidSetupDialog)
        self.edtCntUser.setMinimum(1)
        self.edtCntUser.setMaximum(999999999)
        self.edtCntUser.setObjectName(_fromUtf8("edtCntUser"))
        self.gridlayout.addWidget(self.edtCntUser, 18, 1, 1, 1)
        self.chkPlaceWork = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkPlaceWork.setObjectName(_fromUtf8("chkPlaceWork"))
        self.gridlayout.addWidget(self.chkPlaceWork, 29, 1, 1, 2)
        self.chkEndPerson = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkEndPerson.setObjectName(_fromUtf8("chkEndPerson"))
        self.gridlayout.addWidget(self.chkEndPerson, 28, 1, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem5, 18, 2, 1, 1)
        self.lblCntUser = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblCntUser.setObjectName(_fromUtf8("lblCntUser"))
        self.gridlayout.addWidget(self.lblCntUser, 18, 0, 1, 1)
        self.cmbElectronic = QtGui.QComboBox(TempInvalidSetupDialog)
        self.cmbElectronic.setObjectName(_fromUtf8("cmbElectronic"))
        self.cmbElectronic.addItem(_fromUtf8(""))
        self.cmbElectronic.addItem(_fromUtf8(""))
        self.cmbElectronic.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbElectronic, 4, 1, 1, 2)
        self.chkTempInvalidDuplicateWork = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkTempInvalidDuplicateWork.setObjectName(_fromUtf8("chkTempInvalidDuplicateWork"))
        self.gridlayout.addWidget(self.chkTempInvalidDuplicateWork, 34, 1, 1, 1)
        self.lblElectronic = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblElectronic.setObjectName(_fromUtf8("lblElectronic"))
        self.gridlayout.addWidget(self.lblElectronic, 4, 0, 1, 1)
        self.chkTempInvalidCOVID19 = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkTempInvalidCOVID19.setObjectName(_fromUtf8("chkTempInvalidCOVID19"))
        self.gridlayout.addWidget(self.chkTempInvalidCOVID19, 35, 1, 1, 1)
        self.lblSocStatusClass = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblSocStatusClass.setObjectName(_fromUtf8("lblSocStatusClass"))
        self.gridlayout.addWidget(self.lblSocStatusClass, 13, 0, 1, 1)
        self.lblOrderBy = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblOrderBy.setObjectName(_fromUtf8("lblOrderBy"))
        self.gridlayout.addWidget(self.lblOrderBy, 23, 0, 1, 1)
        self.lblClientArea = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblClientArea.setObjectName(_fromUtf8("lblClientArea"))
        self.gridlayout.addWidget(self.lblClientArea, 22, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(101, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem7, 1, 2, 1, 1)
        self.cmbReason = CRBMultivalueComboBox(TempInvalidSetupDialog)
        self.cmbReason.setObjectName(_fromUtf8("cmbReason"))
        self.gridlayout.addWidget(self.cmbReason, 5, 1, 1, 2)
        self.chkAverageDuration = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkAverageDuration.setObjectName(_fromUtf8("chkAverageDuration"))
        self.gridlayout.addWidget(self.chkAverageDuration, 19, 1, 1, 2)
        self.cmbOrgStructure = COrgStructureComboBox(TempInvalidSetupDialog)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridlayout.addWidget(self.cmbOrgStructure, 7, 1, 1, 2)
        self.lblDuration = QtGui.QLabel(TempInvalidSetupDialog)
        self.lblDuration.setObjectName(_fromUtf8("lblDuration"))
        self.gridlayout.addWidget(self.lblDuration, 9, 0, 2, 1)
        self.chkBeginPerson = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkBeginPerson.setObjectName(_fromUtf8("chkBeginPerson"))
        self.gridlayout.addWidget(self.chkBeginPerson, 27, 1, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(TempInvalidSetupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout.addWidget(self.buttonBox, 39, 0, 1, 3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chkOrderBy = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkOrderBy.setMaximumSize(QtCore.QSize(20, 16777215))
        self.chkOrderBy.setText(_fromUtf8(""))
        self.chkOrderBy.setObjectName(_fromUtf8("chkOrderBy"))
        self.horizontalLayout_2.addWidget(self.chkOrderBy)
        self.cmbOrderBy = QtGui.QComboBox(TempInvalidSetupDialog)
        self.cmbOrderBy.setEnabled(False)
        self.cmbOrderBy.setObjectName(_fromUtf8("cmbOrderBy"))
        self.cmbOrderBy.addItem(_fromUtf8(""))
        self.cmbOrderBy.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmbOrderBy)
        self.gridlayout.addLayout(self.horizontalLayout_2, 23, 1, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkClientArea = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkClientArea.setMaximumSize(QtCore.QSize(20, 16777215))
        self.chkClientArea.setText(_fromUtf8(""))
        self.chkClientArea.setObjectName(_fromUtf8("chkClientArea"))
        self.horizontalLayout.addWidget(self.chkClientArea)
        self.cmbClientArea = CAreaComboBox(TempInvalidSetupDialog)
        self.cmbClientArea.setEnabled(False)
        self.cmbClientArea.setObjectName(_fromUtf8("cmbClientArea"))
        self.horizontalLayout.addWidget(self.cmbClientArea)
        self.gridlayout.addLayout(self.horizontalLayout, 22, 1, 1, 2)
        self.chkIsExternal = QtGui.QCheckBox(TempInvalidSetupDialog)
        self.chkIsExternal.setChecked(True)
        self.chkIsExternal.setObjectName(_fromUtf8("chkIsExternal"))
        self.gridlayout.addWidget(self.chkIsExternal, 30, 1, 1, 1)
        self.lblTempInvalidReason.setBuddy(self.cmbReason)
        self.lblAge.setBuddy(self.edtAgeFrom)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblInsuranceOfficeMark.setBuddy(self.cmbInsuranceOfficeMark)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblMKB.setBuddy(self.cmbMKBFilter)
        self.lblDurationTo.setBuddy(self.edtDurationTo)
        self.lblDurationDays.setBuddy(self.edtDurationTo)
        self.lblAgeTo.setBuddy(self.edtAgeTo)
        self.lblAgeYears.setBuddy(self.edtAgeTo)
        self.lblEndDate.setBuddy(self.edtEndDate)
        self.lblOrgStructure.setBuddy(self.cmbOrgStructure)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblDocType.setBuddy(self.cmbDoctype)
        self.lblSocStatusType.setBuddy(self.cmbSocStatusType)
        self.lblSocStatusClass.setBuddy(self.cmbSocStatusClass)
        self.lblDuration.setBuddy(self.edtDurationFrom)

        self.retranslateUi(TempInvalidSetupDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TempInvalidSetupDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TempInvalidSetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TempInvalidSetupDialog)
        TempInvalidSetupDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        TempInvalidSetupDialog.setTabOrder(self.edtEndDate, self.chkByPeriod)
        TempInvalidSetupDialog.setTabOrder(self.chkByPeriod, self.cmbDoctype)
        TempInvalidSetupDialog.setTabOrder(self.cmbDoctype, self.cmbReason)
        TempInvalidSetupDialog.setTabOrder(self.cmbReason, self.chkOnlyClosed)
        TempInvalidSetupDialog.setTabOrder(self.chkOnlyClosed, self.cmbOrgStructure)
        TempInvalidSetupDialog.setTabOrder(self.cmbOrgStructure, self.cmbPerson)
        TempInvalidSetupDialog.setTabOrder(self.cmbPerson, self.edtDurationFrom)
        TempInvalidSetupDialog.setTabOrder(self.edtDurationFrom, self.edtDurationTo)
        TempInvalidSetupDialog.setTabOrder(self.edtDurationTo, self.cmbSex)
        TempInvalidSetupDialog.setTabOrder(self.cmbSex, self.edtAgeFrom)
        TempInvalidSetupDialog.setTabOrder(self.edtAgeFrom, self.edtAgeTo)
        TempInvalidSetupDialog.setTabOrder(self.edtAgeTo, self.cmbSocStatusClass)
        TempInvalidSetupDialog.setTabOrder(self.cmbSocStatusClass, self.cmbSocStatusType)
        TempInvalidSetupDialog.setTabOrder(self.cmbSocStatusType, self.cmbMKBFilter)
        TempInvalidSetupDialog.setTabOrder(self.cmbMKBFilter, self.edtMKBFrom)
        TempInvalidSetupDialog.setTabOrder(self.edtMKBFrom, self.edtMKBTo)
        TempInvalidSetupDialog.setTabOrder(self.edtMKBTo, self.cmbInsuranceOfficeMark)
        TempInvalidSetupDialog.setTabOrder(self.cmbInsuranceOfficeMark, self.edtCntUser)
        TempInvalidSetupDialog.setTabOrder(self.edtCntUser, self.buttonBox)
        TempInvalidSetupDialog.setTabOrder(self.buttonBox, self.chkAverageDuration)
        TempInvalidSetupDialog.setTabOrder(self.chkAverageDuration, self.chkBeginPerson)
        TempInvalidSetupDialog.setTabOrder(self.chkBeginPerson, self.chkResultsForGroups)
        TempInvalidSetupDialog.setTabOrder(self.chkResultsForGroups, self.chkRegAddress)
        TempInvalidSetupDialog.setTabOrder(self.chkRegAddress, self.chkLocAddress)
        TempInvalidSetupDialog.setTabOrder(self.chkLocAddress, self.chkEndPerson)
        TempInvalidSetupDialog.setTabOrder(self.chkEndPerson, self.chkPlaceWork)
        TempInvalidSetupDialog.setTabOrder(self.chkPlaceWork, self.chkTempInvalidReceiver)
        TempInvalidSetupDialog.setTabOrder(self.chkTempInvalidReceiver, self.chkTempInvalidDuplicate)
        TempInvalidSetupDialog.setTabOrder(self.chkTempInvalidDuplicate, self.cmbDateSort)
        TempInvalidSetupDialog.setTabOrder(self.cmbDateSort, self.chkClientNameSort)

    def retranslateUi(self, TempInvalidSetupDialog):
        TempInvalidSetupDialog.setWindowTitle(_translate("TempInvalidSetupDialog", "параметры отчёта", None))
        self.chkTempInvalidDuplicate.setText(_translate("TempInvalidSetupDialog", "Выводить листы по совместительству", None))
        self.cmbDateSort.setItemText(0, _translate("TempInvalidSetupDialog", "по дате начала случая", None))
        self.cmbDateSort.setItemText(1, _translate("TempInvalidSetupDialog", "по дате начала ЛН", None))
        self.chkTempInvalidReceiver.setText(_translate("TempInvalidSetupDialog", "Отображать данные Лица по уходу", None))
        self.lblDateSort.setText(_translate("TempInvalidSetupDialog", "Сортировать", None))
        self.lblTempInvalidReason.setText(_translate("TempInvalidSetupDialog", "При&чина", None))
        self.chkByPeriod.setToolTip(_translate("TempInvalidSetupDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Если отметка <span style=\" font-weight:600;\">стоит</span>, то для отчёта <br />выбираются документы ВУТ с <span style=\" font-weight:600;\">периодом, </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\">пересекающимя с периодом отчёта</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">Если отметка <span style=\" font-weight:600;\">снята</span>, то для отчёта </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\">выбираются документы ВУТ </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><span style=\" font-weight:600;\">закрытые в периоде отчёта</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p></body></html>", None))
        self.chkByPeriod.setText(_translate("TempInvalidSetupDialog", "Отчёт по периоду случая", None))
        self.edtBegDate.setDisplayFormat(_translate("TempInvalidSetupDialog", "dd.MM.yyyy", None))
        self.lblAge.setText(_translate("TempInvalidSetupDialog", "Во&зраст с", None))
        self.lblPerson.setText(_translate("TempInvalidSetupDialog", "&Врач", None))
        self.lblInsuranceOfficeMark.setText(_translate("TempInvalidSetupDialog", "&Отметка страхового стола", None))
        self.cmbInsuranceOfficeMark.setItemText(1, _translate("TempInvalidSetupDialog", "без отметки", None))
        self.cmbInsuranceOfficeMark.setItemText(2, _translate("TempInvalidSetupDialog", "с отметкой", None))
        self.lblSex.setText(_translate("TempInvalidSetupDialog", "По&л", None))
        self.lblMKB.setText(_translate("TempInvalidSetupDialog", "Коды диагнозов по &МКБ", None))
        self.lblDurationTo.setText(_translate("TempInvalidSetupDialog", "по", None))
        self.lblDurationDays.setText(_translate("TempInvalidSetupDialog", "дней", None))
        self.lblAgeTo.setText(_translate("TempInvalidSetupDialog", "по", None))
        self.lblAgeYears.setText(_translate("TempInvalidSetupDialog", "лет", None))
        self.cmbMKBFilter.setItemText(0, _translate("TempInvalidSetupDialog", "Игнор.", None))
        self.cmbMKBFilter.setItemText(1, _translate("TempInvalidSetupDialog", "Интервал", None))
        self.cmbMKBFilter.setItemText(2, _translate("TempInvalidSetupDialog", "Без диагноза", None))
        self.edtMKBFrom.setInputMask(_translate("TempInvalidSetupDialog", "a00.00", None))
        self.edtMKBFrom.setText(_translate("TempInvalidSetupDialog", "A.", None))
        self.edtMKBTo.setInputMask(_translate("TempInvalidSetupDialog", "a00.00", None))
        self.edtMKBTo.setText(_translate("TempInvalidSetupDialog", "Z99.9", None))
        self.cmbSex.setItemText(1, _translate("TempInvalidSetupDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("TempInvalidSetupDialog", "Ж", None))
        self.edtEndDate.setDisplayFormat(_translate("TempInvalidSetupDialog", "dd.MM.yyyy", None))
        self.chkOnlyClosed.setText(_translate("TempInvalidSetupDialog", "&Только &закрытые", None))
        self.lblEndDate.setText(_translate("TempInvalidSetupDialog", "Дата &окончания периода", None))
        self.lblOrgStructure.setText(_translate("TempInvalidSetupDialog", "&Подразделение", None))
        self.lblBegDate.setText(_translate("TempInvalidSetupDialog", "Дата &начала периода", None))
        self.lblDocType.setText(_translate("TempInvalidSetupDialog", "Тип &документа", None))
        self.cmbPerson.setItemText(0, _translate("TempInvalidSetupDialog", "Врач", None))
        self.chkLocAddress.setText(_translate("TempInvalidSetupDialog", "Адрес проживания", None))
        self.lblSocStatusType.setText(_translate("TempInvalidSetupDialog", "Тип соц.статуса", None))
        self.chkResultsForGroups.setText(_translate("TempInvalidSetupDialog", "Выводить итоги для групп", None))
        self.chkRegAddress.setText(_translate("TempInvalidSetupDialog", "Адрес регистрации", None))
        self.chkClientNameSort.setText(_translate("TempInvalidSetupDialog", "по ФИО пациента ", None))
        self.chkPlaceWork.setText(_translate("TempInvalidSetupDialog", "Место работы", None))
        self.chkEndPerson.setText(_translate("TempInvalidSetupDialog", "Закончивший БЛ", None))
        self.lblCntUser.setText(_translate("TempInvalidSetupDialog", "Номер строки с", None))
        self.cmbElectronic.setItemText(0, _translate("TempInvalidSetupDialog", "не задано", None))
        self.cmbElectronic.setItemText(1, _translate("TempInvalidSetupDialog", "Электронный", None))
        self.cmbElectronic.setItemText(2, _translate("TempInvalidSetupDialog", "Бумажный", None))
        self.chkTempInvalidDuplicateWork.setText(_translate("TempInvalidSetupDialog", "Включать дубликаты ЛВН", None))
        self.lblElectronic.setText(_translate("TempInvalidSetupDialog", "Электронный", None))
        self.chkTempInvalidCOVID19.setText(_translate("TempInvalidSetupDialog", "Детализировать по COVID19", None))
        self.lblSocStatusClass.setText(_translate("TempInvalidSetupDialog", "Класс соц.статуса", None))
        self.lblOrderBy.setText(_translate("TempInvalidSetupDialog", "Сортировать по", None))
        self.lblClientArea.setText(_translate("TempInvalidSetupDialog", "Участок", None))
        self.chkAverageDuration.setText(_translate("TempInvalidSetupDialog", "Средняя длительность", None))
        self.lblDuration.setText(_translate("TempInvalidSetupDialog", "&Длительность с", None))
        self.chkBeginPerson.setText(_translate("TempInvalidSetupDialog", "Начавший БЛ", None))
        self.cmbOrderBy.setItemText(0, _translate("TempInvalidSetupDialog", "ФИО", None))
        self.cmbOrderBy.setItemText(1, _translate("TempInvalidSetupDialog", "Дате начала периода", None))
        self.chkIsExternal.setText(_translate("TempInvalidSetupDialog", "Отображать внешние БЛ", None))

from library.crbcombobox import CRBComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Orgs.OrgStructComboBoxes import COrgStructureComboBox, CAreaComboBox
from library.ICDCodeEdit import CICDCodeEdit
from Registry.SocStatusComboBox import CSocStatusComboBox
from library.MultivalueComboBox import CRBMultivalueComboBox
from library.DateEdit import CDateEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TempInvalidSetupDialog = QtGui.QDialog()
    ui = Ui_TempInvalidSetupDialog()
    ui.setupUi(TempInvalidSetupDialog)
    TempInvalidSetupDialog.show()
    sys.exit(app.exec_())

