# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/work/kmivc-arch/Samson/client_test/Resources/JobTicketEditor.ui'
#
# Created by: PyQt4 UI code generator 4.12.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_JobTicketEditorDialog(object):
    def setupUi(self, JobTicketEditorDialog):
        JobTicketEditorDialog.setObjectName(_fromUtf8("JobTicketEditorDialog"))
        JobTicketEditorDialog.resize(1474, 801)
        JobTicketEditorDialog.setMinimumSize(QtCore.QSize(600, 600))
        JobTicketEditorDialog.setSizeGripEnabled(False)
        self.gridLayout_5 = QtGui.QGridLayout(JobTicketEditorDialog)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.scrollArea = QtGui.QScrollArea(JobTicketEditorDialog)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1454, 781))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter_2 = QtGui.QSplitter(self.scrollAreaWidgetContents)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.txtClientInfoBrowser = CTextBrowser(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setReadOnly(True)
        self.txtClientInfoBrowser.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.tblActions = CTableView(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblActions.sizePolicy().hasHeightForWidth())
        self.tblActions.setSizePolicy(sizePolicy)
        self.tblActions.setObjectName(_fromUtf8("tblActions"))
        self.widget_5 = QtGui.QWidget(self.splitter_2)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.splitter = QtGui.QSplitter(self.widget_5)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frmCommon = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmCommon.sizePolicy().hasHeightForWidth())
        self.frmCommon.setSizePolicy(sizePolicy)
        self.frmCommon.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmCommon.setFrameShadow(QtGui.QFrame.Plain)
        self.frmCommon.setLineWidth(0)
        self.frmCommon.setObjectName(_fromUtf8("frmCommon"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frmCommon)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.grpTissue = QtGui.QGroupBox(self.frmCommon)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpTissue.sizePolicy().hasHeightForWidth())
        self.grpTissue.setSizePolicy(sizePolicy)
        self.grpTissue.setObjectName(_fromUtf8("grpTissue"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpTissue)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cmbTissueUnit = CRBComboBox(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTissueUnit.sizePolicy().hasHeightForWidth())
        self.cmbTissueUnit.setSizePolicy(sizePolicy)
        self.cmbTissueUnit.setObjectName(_fromUtf8("cmbTissueUnit"))
        self.gridLayout_3.addWidget(self.cmbTissueUnit, 3, 1, 1, 2)
        self.lblTissueNote = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueNote.sizePolicy().hasHeightForWidth())
        self.lblTissueNote.setSizePolicy(sizePolicy)
        self.lblTissueNote.setObjectName(_fromUtf8("lblTissueNote"))
        self.gridLayout_3.addWidget(self.lblTissueNote, 5, 0, 1, 1)
        self.lblTissueDateTime = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueDateTime.sizePolicy().hasHeightForWidth())
        self.lblTissueDateTime.setSizePolicy(sizePolicy)
        self.lblTissueDateTime.setObjectName(_fromUtf8("lblTissueDateTime"))
        self.gridLayout_3.addWidget(self.lblTissueDateTime, 6, 0, 1, 1)
        self.edtTissueNote = QtGui.QLineEdit(self.grpTissue)
        self.edtTissueNote.setObjectName(_fromUtf8("edtTissueNote"))
        self.gridLayout_3.addWidget(self.edtTissueNote, 5, 1, 1, 2)
        self.widget_2 = QtGui.QWidget(self.grpTissue)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtTissueExternalId = QtGui.QLineEdit(self.widget_2)
        self.edtTissueExternalId.setReadOnly(True)
        self.edtTissueExternalId.setObjectName(_fromUtf8("edtTissueExternalId"))
        self.horizontalLayout.addWidget(self.edtTissueExternalId)
        self.lblTissueNumber = QtGui.QLabel(self.widget_2)
        self.lblTissueNumber.setObjectName(_fromUtf8("lblTissueNumber"))
        self.horizontalLayout.addWidget(self.lblTissueNumber)
        self.edtTissueNumber = QtGui.QLineEdit(self.widget_2)
        self.edtTissueNumber.setReadOnly(True)
        self.edtTissueNumber.setObjectName(_fromUtf8("edtTissueNumber"))
        self.horizontalLayout.addWidget(self.edtTissueNumber)
        self.gridLayout_3.addWidget(self.widget_2, 9, 1, 1, 2)
        self.cmbTissueType = CRBComboBox(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTissueType.sizePolicy().hasHeightForWidth())
        self.cmbTissueType.setSizePolicy(sizePolicy)
        self.cmbTissueType.setObjectName(_fromUtf8("cmbTissueType"))
        self.gridLayout_3.addWidget(self.cmbTissueType, 1, 1, 1, 2)
        self.edtTissueAmount = QtGui.QSpinBox(self.grpTissue)
        self.edtTissueAmount.setMaximum(999999)
        self.edtTissueAmount.setObjectName(_fromUtf8("edtTissueAmount"))
        self.gridLayout_3.addWidget(self.edtTissueAmount, 7, 1, 1, 1)
        self.line = QtGui.QFrame(self.grpTissue)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 10, 0, 1, 3)
        self.lblTissueAmount = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueAmount.sizePolicy().hasHeightForWidth())
        self.lblTissueAmount.setSizePolicy(sizePolicy)
        self.lblTissueAmount.setObjectName(_fromUtf8("lblTissueAmount"))
        self.gridLayout_3.addWidget(self.lblTissueAmount, 7, 0, 1, 1)
        self.lblTissueType = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueType.sizePolicy().hasHeightForWidth())
        self.lblTissueType.setSizePolicy(sizePolicy)
        self.lblTissueType.setObjectName(_fromUtf8("lblTissueType"))
        self.gridLayout_3.addWidget(self.lblTissueType, 1, 0, 1, 1)
        self.btnProbes = QtGui.QPushButton(self.grpTissue)
        self.btnProbes.setObjectName(_fromUtf8("btnProbes"))
        self.gridLayout_3.addWidget(self.btnProbes, 11, 0, 1, 1)
        self.lblTissyeExecPerson = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissyeExecPerson.sizePolicy().hasHeightForWidth())
        self.lblTissyeExecPerson.setSizePolicy(sizePolicy)
        self.lblTissyeExecPerson.setObjectName(_fromUtf8("lblTissyeExecPerson"))
        self.gridLayout_3.addWidget(self.lblTissyeExecPerson, 2, 0, 1, 1)
        self.cmbTissueExecPerson = CPersonComboBoxEx(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTissueExecPerson.sizePolicy().hasHeightForWidth())
        self.cmbTissueExecPerson.setSizePolicy(sizePolicy)
        self.cmbTissueExecPerson.setObjectName(_fromUtf8("cmbTissueExecPerson"))
        self.gridLayout_3.addWidget(self.cmbTissueExecPerson, 2, 1, 1, 2)
        self.gridLayout_51 = QtGui.QGridLayout()
        self.gridLayout_51.setObjectName(_fromUtf8("gridLayout_51"))
        self.edtTissueMenstrualDay = QtGui.QSpinBox(self.grpTissue)
        self.edtTissueMenstrualDay.setEnabled(False)
        self.edtTissueMenstrualDay.setMinimum(1)
        self.edtTissueMenstrualDay.setMaximum(99)
        self.edtTissueMenstrualDay.setObjectName(_fromUtf8("edtTissueMenstrualDay"))
        self.gridLayout_51.addWidget(self.edtTissueMenstrualDay, 0, 1, 1, 1)
        self.chkTissueMenstrualDay = QtGui.QCheckBox(self.grpTissue)
        self.chkTissueMenstrualDay.setEnabled(True)
        self.chkTissueMenstrualDay.setObjectName(_fromUtf8("chkTissueMenstrualDay"))
        self.gridLayout_51.addWidget(self.chkTissueMenstrualDay, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_51, 7, 2, 1, 1)
        self.lblTissueExternalId = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueExternalId.sizePolicy().hasHeightForWidth())
        self.lblTissueExternalId.setSizePolicy(sizePolicy)
        self.lblTissueExternalId.setObjectName(_fromUtf8("lblTissueExternalId"))
        self.gridLayout_3.addWidget(self.lblTissueExternalId, 9, 0, 1, 1)
        self.lblTissueUnit = QtGui.QLabel(self.grpTissue)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTissueUnit.sizePolicy().hasHeightForWidth())
        self.lblTissueUnit.setSizePolicy(sizePolicy)
        self.lblTissueUnit.setObjectName(_fromUtf8("lblTissueUnit"))
        self.gridLayout_3.addWidget(self.lblTissueUnit, 3, 0, 1, 1)
        self.edtTissueDate = CDateEdit(self.grpTissue)
        self.edtTissueDate.setCalendarPopup(True)
        self.edtTissueDate.setObjectName(_fromUtf8("edtTissueDate"))
        self.gridLayout_3.addWidget(self.edtTissueDate, 6, 1, 1, 1)
        self.edtTissueTime = QtGui.QTimeEdit(self.grpTissue)
        self.edtTissueTime.setObjectName(_fromUtf8("edtTissueTime"))
        self.gridLayout_3.addWidget(self.edtTissueTime, 6, 2, 1, 1)
        self.lblEquipment = QtGui.QLabel(self.grpTissue)
        self.lblEquipment.setObjectName(_fromUtf8("lblEquipment"))
        self.gridLayout_3.addWidget(self.lblEquipment, 8, 0, 1, 1)
        self.cmbEquipment = CRBComboBox(self.grpTissue)
        self.cmbEquipment.setObjectName(_fromUtf8("cmbEquipment"))
        self.gridLayout_3.addWidget(self.cmbEquipment, 8, 1, 1, 2)
        self.verticalLayout_3.addWidget(self.grpTissue)
        self.grpMain = QtGui.QGroupBox(self.frmCommon)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpMain.sizePolicy().hasHeightForWidth())
        self.grpMain.setSizePolicy(sizePolicy)
        self.grpMain.setObjectName(_fromUtf8("grpMain"))
        self.gridLayout = QtGui.QGridLayout(self.grpMain)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblEndDatetime = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDatetime.sizePolicy().hasHeightForWidth())
        self.lblEndDatetime.setSizePolicy(sizePolicy)
        self.lblEndDatetime.setObjectName(_fromUtf8("lblEndDatetime"))
        self.gridLayout.addWidget(self.lblEndDatetime, 6, 0, 1, 1)
        self.lblDatetime = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDatetime.sizePolicy().hasHeightForWidth())
        self.lblDatetime.setSizePolicy(sizePolicy)
        self.lblDatetime.setObjectName(_fromUtf8("lblDatetime"))
        self.gridLayout.addWidget(self.lblDatetime, 0, 0, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblOrgStructure.setSizePolicy(sizePolicy)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 1, 0, 1, 1)
        self.lblLabel = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLabel.sizePolicy().hasHeightForWidth())
        self.lblLabel.setSizePolicy(sizePolicy)
        self.lblLabel.setObjectName(_fromUtf8("lblLabel"))
        self.gridLayout.addWidget(self.lblLabel, 7, 0, 1, 1)
        self.lblDatetimeValue = QtGui.QLabel(self.grpMain)
        self.lblDatetimeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblDatetimeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblDatetimeValue.setObjectName(_fromUtf8("lblDatetimeValue"))
        self.gridLayout.addWidget(self.lblDatetimeValue, 0, 1, 1, 1)
        self.edtNote = QtGui.QLineEdit(self.grpMain)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 9, 1, 1, 5)
        self.lblNote = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNote.sizePolicy().hasHeightForWidth())
        self.lblNote.setSizePolicy(sizePolicy)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout.addWidget(self.lblNote, 9, 0, 1, 1)
        self.widget_4 = QtGui.QWidget(self.grpMain)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtEndDate = CDateEdit(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout_3.addWidget(self.edtEndDate)
        self.edtEndTime = QtGui.QTimeEdit(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndTime.sizePolicy().hasHeightForWidth())
        self.edtEndTime.setSizePolicy(sizePolicy)
        self.edtEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEndTime.setCurrentSectionIndex(0)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.horizontalLayout_3.addWidget(self.edtEndTime)
        self.btnSetEndDateTime = QtGui.QToolButton(self.widget_4)
        self.btnSetEndDateTime.setArrowType(QtCore.Qt.LeftArrow)
        self.btnSetEndDateTime.setObjectName(_fromUtf8("btnSetEndDateTime"))
        self.horizontalLayout_3.addWidget(self.btnSetEndDateTime)
        self.gridLayout.addWidget(self.widget_4, 6, 1, 1, 1)
        self.lblJobType = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblJobType.sizePolicy().hasHeightForWidth())
        self.lblJobType.setSizePolicy(sizePolicy)
        self.lblJobType.setObjectName(_fromUtf8("lblJobType"))
        self.gridLayout.addWidget(self.lblJobType, 2, 0, 1, 1)
        self.lblStatus = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.gridLayout.addWidget(self.lblStatus, 3, 0, 1, 1)
        self.widget_3 = QtGui.QWidget(self.grpMain)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.edtBegDate = CDateEdit(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout_2.addWidget(self.edtBegDate)
        self.edtBegTime = QtGui.QTimeEdit(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegTime.sizePolicy().hasHeightForWidth())
        self.edtBegTime.setSizePolicy(sizePolicy)
        self.edtBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtBegTime.setCurrentSectionIndex(0)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.horizontalLayout_2.addWidget(self.edtBegTime)
        self.btnSetBegDateTime = QtGui.QToolButton(self.widget_3)
        self.btnSetBegDateTime.setArrowType(QtCore.Qt.LeftArrow)
        self.btnSetBegDateTime.setObjectName(_fromUtf8("btnSetBegDateTime"))
        self.horizontalLayout_2.addWidget(self.btnSetBegDateTime)
        self.gridLayout.addWidget(self.widget_3, 5, 1, 1, 1)
        self.lblBegDateTime = QtGui.QLabel(self.grpMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDateTime.sizePolicy().hasHeightForWidth())
        self.lblBegDateTime.setSizePolicy(sizePolicy)
        self.lblBegDateTime.setObjectName(_fromUtf8("lblBegDateTime"))
        self.gridLayout.addWidget(self.lblBegDateTime, 5, 0, 1, 1)
        self.edtLabel = QtGui.QLineEdit(self.grpMain)
        self.edtLabel.setObjectName(_fromUtf8("edtLabel"))
        self.gridLayout.addWidget(self.edtLabel, 7, 1, 1, 5)
        self.chkIsAssigned = QtGui.QCheckBox(self.grpMain)
        self.chkIsAssigned.setObjectName(_fromUtf8("chkIsAssigned"))
        self.gridLayout.addWidget(self.chkIsAssigned, 4, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(self.grpMain)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 8, 1, 1, 5)
        self.lblExecOrgStructure = QtGui.QLabel(self.grpMain)
        self.lblExecOrgStructure.setObjectName(_fromUtf8("lblExecOrgStructure"))
        self.gridLayout.addWidget(self.lblExecOrgStructure, 8, 0, 1, 1)
        self.lblOrgStructureValue = QtGui.QLabel(self.grpMain)
        self.lblOrgStructureValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblOrgStructureValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblOrgStructureValue.setObjectName(_fromUtf8("lblOrgStructureValue"))
        self.gridLayout.addWidget(self.lblOrgStructureValue, 1, 1, 1, 5)
        self.lblJobTypeValue = QtGui.QLabel(self.grpMain)
        self.lblJobTypeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblJobTypeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblJobTypeValue.setObjectName(_fromUtf8("lblJobTypeValue"))
        self.gridLayout.addWidget(self.lblJobTypeValue, 2, 1, 1, 5)
        self.cmbStatus = CJobTicketStatusComboBox(self.grpMain)
        self.cmbStatus.setObjectName(_fromUtf8("cmbStatus"))
        self.gridLayout.addWidget(self.cmbStatus, 3, 1, 1, 5)
        self.verticalLayout_3.addWidget(self.grpMain)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.widget = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnFillPropertiesValue = QtGui.QPushButton(self.widget)
        self.btnFillPropertiesValue.setObjectName(_fromUtf8("btnFillPropertiesValue"))
        self.gridLayout_2.addWidget(self.btnFillPropertiesValue, 1, 5, 1, 1)
        self.btnCloneValues = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCloneValues.sizePolicy().hasHeightForWidth())
        self.btnCloneValues.setSizePolicy(sizePolicy)
        self.btnCloneValues.setObjectName(_fromUtf8("btnCloneValues"))
        self.gridLayout_2.addWidget(self.btnCloneValues, 1, 4, 1, 1)
        self.btnSaveAsTemplate = QtGui.QPushButton(self.widget)
        self.btnSaveAsTemplate.setObjectName(_fromUtf8("btnSaveAsTemplate"))
        self.gridLayout_2.addWidget(self.btnSaveAsTemplate, 1, 2, 1, 1)
        self.btnLoadTemplate = CActionTemplateSelectButton(self.widget)
        self.btnLoadTemplate.setObjectName(_fromUtf8("btnLoadTemplate"))
        self.gridLayout_2.addWidget(self.btnLoadTemplate, 1, 1, 1, 1)
        self.btnAmbCard = QtGui.QPushButton(self.widget)
        self.btnAmbCard.setObjectName(_fromUtf8("btnAmbCard"))
        self.gridLayout_2.addWidget(self.btnAmbCard, 1, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(96, 23, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 8, 1, 1)
        self.tblProps = CActionPropertiesTableView(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblProps.sizePolicy().hasHeightForWidth())
        self.tblProps.setSizePolicy(sizePolicy)
        self.tblProps.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblProps.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblProps.setObjectName(_fromUtf8("tblProps"))
        self.gridLayout_2.addWidget(self.tblProps, 0, 0, 1, 9)
        self.btnLoadPrevAction = QtGui.QPushButton(self.widget)
        self.btnLoadPrevAction.setEnabled(False)
        self.btnLoadPrevAction.setObjectName(_fromUtf8("btnLoadPrevAction"))
        self.gridLayout_2.addWidget(self.btnLoadPrevAction, 1, 3, 1, 1)
        self.btnAttachedFiles = CAttachButton(self.widget)
        self.btnAttachedFiles.setFlat(False)
        self.btnAttachedFiles.setObjectName(_fromUtf8("btnAttachedFiles"))
        self.gridLayout_2.addWidget(self.btnAttachedFiles, 1, 7, 1, 1)
        self.horizontalLayout_4.addWidget(self.splitter)
        self.gridLayout_4.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.scrollAreaWidgetContents)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.lblTissueNote.setBuddy(self.edtTissueNote)
        self.lblTissueDateTime.setBuddy(self.edtTissueDate)
        self.lblTissueAmount.setBuddy(self.edtTissueAmount)
        self.lblTissueType.setBuddy(self.cmbTissueType)
        self.lblTissyeExecPerson.setBuddy(self.cmbTissueExecPerson)
        self.lblTissueExternalId.setBuddy(self.edtTissueExternalId)
        self.lblTissueUnit.setBuddy(self.cmbTissueUnit)
        self.lblEquipment.setBuddy(self.cmbEquipment)
        self.lblEndDatetime.setBuddy(self.edtEndDate)
        self.lblLabel.setBuddy(self.edtLabel)
        self.lblNote.setBuddy(self.edtNote)
        self.lblStatus.setBuddy(self.cmbStatus)
        self.lblBegDateTime.setBuddy(self.edtBegDate)

        self.retranslateUi(JobTicketEditorDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), JobTicketEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), JobTicketEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(JobTicketEditorDialog)
        JobTicketEditorDialog.setTabOrder(self.tblActions, self.cmbTissueType)
        JobTicketEditorDialog.setTabOrder(self.cmbTissueType, self.cmbTissueExecPerson)
        JobTicketEditorDialog.setTabOrder(self.cmbTissueExecPerson, self.cmbTissueUnit)
        JobTicketEditorDialog.setTabOrder(self.cmbTissueUnit, self.edtTissueNote)
        JobTicketEditorDialog.setTabOrder(self.edtTissueNote, self.edtTissueDate)
        JobTicketEditorDialog.setTabOrder(self.edtTissueDate, self.edtTissueTime)
        JobTicketEditorDialog.setTabOrder(self.edtTissueTime, self.edtTissueAmount)
        JobTicketEditorDialog.setTabOrder(self.edtTissueAmount, self.cmbEquipment)
        JobTicketEditorDialog.setTabOrder(self.cmbEquipment, self.edtTissueExternalId)
        JobTicketEditorDialog.setTabOrder(self.edtTissueExternalId, self.edtTissueNumber)
        JobTicketEditorDialog.setTabOrder(self.edtTissueNumber, self.btnProbes)
        JobTicketEditorDialog.setTabOrder(self.btnProbes, self.cmbStatus)
        JobTicketEditorDialog.setTabOrder(self.cmbStatus, self.chkIsAssigned)
        JobTicketEditorDialog.setTabOrder(self.chkIsAssigned, self.edtBegDate)
        JobTicketEditorDialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        JobTicketEditorDialog.setTabOrder(self.edtBegTime, self.btnSetBegDateTime)
        JobTicketEditorDialog.setTabOrder(self.btnSetBegDateTime, self.edtEndDate)
        JobTicketEditorDialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        JobTicketEditorDialog.setTabOrder(self.edtEndTime, self.btnSetEndDateTime)
        JobTicketEditorDialog.setTabOrder(self.btnSetEndDateTime, self.edtLabel)
        JobTicketEditorDialog.setTabOrder(self.edtLabel, self.edtNote)
        JobTicketEditorDialog.setTabOrder(self.edtNote, self.tblProps)
        JobTicketEditorDialog.setTabOrder(self.tblProps, self.btnLoadTemplate)
        JobTicketEditorDialog.setTabOrder(self.btnLoadTemplate, self.btnSaveAsTemplate)
        JobTicketEditorDialog.setTabOrder(self.btnSaveAsTemplate, self.btnCloneValues)
        JobTicketEditorDialog.setTabOrder(self.btnCloneValues, self.btnFillPropertiesValue)
        JobTicketEditorDialog.setTabOrder(self.btnFillPropertiesValue, self.btnAmbCard)
        JobTicketEditorDialog.setTabOrder(self.btnAmbCard, self.btnAttachedFiles)
        JobTicketEditorDialog.setTabOrder(self.btnAttachedFiles, self.buttonBox)
        JobTicketEditorDialog.setTabOrder(self.buttonBox, self.btnLoadPrevAction)
        JobTicketEditorDialog.setTabOrder(self.btnLoadPrevAction, self.cmbOrgStructure)

    def retranslateUi(self, JobTicketEditorDialog):
        JobTicketEditorDialog.setWindowTitle(_translate("JobTicketEditorDialog", "ChangeMe!", None))
        self.txtClientInfoBrowser.setHtml(_translate("JobTicketEditorDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.grpTissue.setTitle(_translate("JobTicketEditorDialog", "Биоматериал", None))
        self.lblTissueNote.setText(_translate("JobTicketEditorDialog", "Примечание", None))
        self.lblTissueDateTime.setText(_translate("JobTicketEditorDialog", "Дата и время", None))
        self.lblTissueNumber.setText(_translate("JobTicketEditorDialog", "Номер", None))
        self.lblTissueAmount.setText(_translate("JobTicketEditorDialog", "Количество", None))
        self.lblTissueType.setText(_translate("JobTicketEditorDialog", "Тип биоматериала", None))
        self.btnProbes.setText(_translate("JobTicketEditorDialog", "Пробы", None))
        self.lblTissyeExecPerson.setText(_translate("JobTicketEditorDialog", "Исполнитель", None))
        self.edtTissueMenstrualDay.setToolTip(_translate("JobTicketEditorDialog", "День менструального цикла", None))
        self.chkTissueMenstrualDay.setToolTip(_translate("JobTicketEditorDialog", "Может заполняться только у женщин", None))
        self.chkTissueMenstrualDay.setText(_translate("JobTicketEditorDialog", "День цикла", None))
        self.lblTissueExternalId.setText(_translate("JobTicketEditorDialog", "&Идентификатор", None))
        self.lblTissueUnit.setText(_translate("JobTicketEditorDialog", "Ед. измерения", None))
        self.lblEquipment.setText(_translate("JobTicketEditorDialog", "Оборудование", None))
        self.grpMain.setTitle(_translate("JobTicketEditorDialog", "Основная информация", None))
        self.lblEndDatetime.setText(_translate("JobTicketEditorDialog", "Окончание выполнения", None))
        self.lblDatetime.setText(_translate("JobTicketEditorDialog", "Плановые дата и время", None))
        self.lblOrgStructure.setText(_translate("JobTicketEditorDialog", "Подразделение", None))
        self.lblLabel.setText(_translate("JobTicketEditorDialog", "Отметка", None))
        self.lblDatetimeValue.setText(_translate("JobTicketEditorDialog", "01.12.2009 19:30", None))
        self.lblNote.setText(_translate("JobTicketEditorDialog", "Примечание", None))
        self.edtEndTime.setDisplayFormat(_translate("JobTicketEditorDialog", "HH:mm", None))
        self.btnSetEndDateTime.setText(_translate("JobTicketEditorDialog", "...", None))
        self.lblJobType.setText(_translate("JobTicketEditorDialog", "Работа", None))
        self.lblStatus.setText(_translate("JobTicketEditorDialog", "Состояние", None))
        self.edtBegTime.setDisplayFormat(_translate("JobTicketEditorDialog", "HH:mm", None))
        self.btnSetBegDateTime.setText(_translate("JobTicketEditorDialog", "...", None))
        self.lblBegDateTime.setText(_translate("JobTicketEditorDialog", "Начало выполнения", None))
        self.chkIsAssigned.setText(_translate("JobTicketEditorDialog", "Назначенные", None))
        self.lblExecOrgStructure.setText(_translate("JobTicketEditorDialog", "Подразделение выполн.", None))
        self.lblOrgStructureValue.setText(_translate("JobTicketEditorDialog", "Лаборатория", None))
        self.lblJobTypeValue.setText(_translate("JobTicketEditorDialog", "анализ крови", None))
        self.btnFillPropertiesValue.setText(_translate("JobTicketEditorDialog", "Заполнить значения проб", None))
        self.btnCloneValues.setText(_translate("JobTicketEditorDialog", "Размножить значения свойств", None))
        self.btnSaveAsTemplate.setText(_translate("JobTicketEditorDialog", "Сохранить шаблон", None))
        self.btnLoadTemplate.setText(_translate("JobTicketEditorDialog", "Загрузить шаблон", None))
        self.btnAmbCard.setText(_translate("JobTicketEditorDialog", "Медицинская карта", None))
        self.btnLoadPrevAction.setText(_translate("JobTicketEditorDialog", "Копировать из предыдущего", None))
        self.btnAttachedFiles.setText(_translate("JobTicketEditorDialog", "Прикреплённые файлы", None))

from Events.ActionPropertiesTable import CActionPropertiesTableView
from Events.ActionTemplateChoose import CActionTemplateSelectButton
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Resources.JobTicketStatus import CJobTicketStatusComboBox
from library.Attach.AttachButton import CAttachButton
from library.DateEdit import CDateEdit
from library.TableView import CTableView
from library.TextBrowser import CTextBrowser
from library.crbcombobox import CRBComboBox
