# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Rabota\s11\Events\NomenclatureExpense\NomenclatureExpenseDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NomenclatureExpenseDialog(object):
    def setupUi(self, NomenclatureExpenseDialog):
        NomenclatureExpenseDialog.setObjectName(_fromUtf8("NomenclatureExpenseDialog"))
        NomenclatureExpenseDialog.resize(1080, 630)
        self.verticalLayout_2 = QtGui.QVBoxLayout(NomenclatureExpenseDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.wgtFilters = QtGui.QWidget(NomenclatureExpenseDialog)
        self.wgtFilters.setObjectName(_fromUtf8("wgtFilters"))
        self.gridLayout = QtGui.QGridLayout(self.wgtFilters)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.wgtMonth = QtGui.QWidget(self.wgtFilters)
        self.wgtMonth.setObjectName(_fromUtf8("wgtMonth"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.wgtMonth)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.lblMonth = QtGui.QLabel(self.wgtMonth)
        self.lblMonth.setObjectName(_fromUtf8("lblMonth"))
        self.horizontalLayout_6.addWidget(self.lblMonth)
        self.cmbMonth = QtGui.QComboBox(self.wgtMonth)
        self.cmbMonth.setObjectName(_fromUtf8("cmbMonth"))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.cmbMonth.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.cmbMonth)
        self.gridLayout.addWidget(self.wgtMonth, 7, 2, 1, 1)
        self.wgtYear = QtGui.QWidget(self.wgtFilters)
        self.wgtYear.setObjectName(_fromUtf8("wgtYear"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.wgtYear)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.lblYear = QtGui.QLabel(self.wgtYear)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblYear.sizePolicy().hasHeightForWidth())
        self.lblYear.setSizePolicy(sizePolicy)
        self.lblYear.setObjectName(_fromUtf8("lblYear"))
        self.horizontalLayout_5.addWidget(self.lblYear)
        self.edtYear = CSpinBox(self.wgtYear)
        self.edtYear.setMinimum(1970)
        self.edtYear.setMaximum(3000)
        self.edtYear.setObjectName(_fromUtf8("edtYear"))
        self.horizontalLayout_5.addWidget(self.edtYear)
        self.gridLayout.addWidget(self.wgtYear, 6, 2, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(self.wgtFilters)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout.addWidget(self.lblOrgStructure, 1, 0, 1, 1)
        self.lblNomenclature = QtGui.QLabel(self.wgtFilters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNomenclature.sizePolicy().hasHeightForWidth())
        self.lblNomenclature.setSizePolicy(sizePolicy)
        self.lblNomenclature.setObjectName(_fromUtf8("lblNomenclature"))
        self.gridLayout.addWidget(self.lblNomenclature, 3, 0, 1, 1)
        self.lblActionType = QtGui.QLabel(self.wgtFilters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblActionType.sizePolicy().hasHeightForWidth())
        self.lblActionType.setSizePolicy(sizePolicy)
        self.lblActionType.setObjectName(_fromUtf8("lblActionType"))
        self.gridLayout.addWidget(self.lblActionType, 0, 0, 1, 1)
        self.chkPeriod = QtGui.QCheckBox(self.wgtFilters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkPeriod.sizePolicy().hasHeightForWidth())
        self.chkPeriod.setSizePolicy(sizePolicy)
        self.chkPeriod.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkPeriod.setTristate(False)
        self.chkPeriod.setObjectName(_fromUtf8("chkPeriod"))
        self.gridLayout.addWidget(self.chkPeriod, 5, 0, 1, 1)
        self.cmbActionType = CActionTypeComboBox(self.wgtFilters)
        self.cmbActionType.setObjectName(_fromUtf8("cmbActionType"))
        self.gridLayout.addWidget(self.cmbActionType, 0, 2, 1, 1)
        self.cmbNomenclature = CNomenclatureComboBox(self.wgtFilters)
        self.cmbNomenclature.setObjectName(_fromUtf8("cmbNomenclature"))
        self.gridLayout.addWidget(self.cmbNomenclature, 3, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 9, 2, 1, 1)
        self.chkCurrentEvent = QtGui.QCheckBox(self.wgtFilters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkCurrentEvent.sizePolicy().hasHeightForWidth())
        self.chkCurrentEvent.setSizePolicy(sizePolicy)
        self.chkCurrentEvent.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkCurrentEvent.setAutoRepeat(False)
        self.chkCurrentEvent.setAutoExclusive(False)
        self.chkCurrentEvent.setObjectName(_fromUtf8("chkCurrentEvent"))
        self.gridLayout.addWidget(self.chkCurrentEvent, 9, 0, 1, 1)
        self.cmbOrgStructure = CStorageComboBox(self.wgtFilters)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout.addWidget(self.cmbOrgStructure, 1, 2, 1, 1)
        self.chkActual = QtGui.QCheckBox(self.wgtFilters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkActual.sizePolicy().hasHeightForWidth())
        self.chkActual.setSizePolicy(sizePolicy)
        self.chkActual.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkActual.setObjectName(_fromUtf8("chkActual"))
        self.gridLayout.addWidget(self.chkActual, 6, 0, 1, 1)
        self.chkIgnoreTime = QtGui.QCheckBox(self.wgtFilters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkIgnoreTime.sizePolicy().hasHeightForWidth())
        self.chkIgnoreTime.setSizePolicy(sizePolicy)
        self.chkIgnoreTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkIgnoreTime.setObjectName(_fromUtf8("chkIgnoreTime"))
        self.gridLayout.addWidget(self.chkIgnoreTime, 7, 0, 1, 1)
        self.chkRequiresFillingNomenclature = QtGui.QCheckBox(self.wgtFilters)
        self.chkRequiresFillingNomenclature.setObjectName(_fromUtf8("chkRequiresFillingNomenclature"))
        self.gridLayout.addWidget(self.chkRequiresFillingNomenclature, 8, 0, 1, 3)
        self.btnReset = QtGui.QPushButton(self.wgtFilters)
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.gridLayout.addWidget(self.btnReset, 10, 0, 1, 2)
        self.wgtPeriod = QtGui.QWidget(self.wgtFilters)
        self.wgtPeriod.setEnabled(False)
        self.wgtPeriod.setObjectName(_fromUtf8("wgtPeriod"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.wgtPeriod)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblBegDate = QtGui.QLabel(self.wgtPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.horizontalLayout.addWidget(self.lblBegDate)
        self.edtBegDate = CDateEdit(self.wgtPeriod)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout.addWidget(self.edtBegDate)
        self.lblEndDate = QtGui.QLabel(self.wgtPeriod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDate.sizePolicy().hasHeightForWidth())
        self.lblEndDate.setSizePolicy(sizePolicy)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.horizontalLayout.addWidget(self.lblEndDate)
        self.edtEndDate = CDateEdit(self.wgtPeriod)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout.addWidget(self.edtEndDate)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addWidget(self.wgtPeriod, 5, 2, 1, 1)
        self.cmbSchema = CRBComboBox(self.wgtFilters)
        self.cmbSchema.setObjectName(_fromUtf8("cmbSchema"))
        self.gridLayout.addWidget(self.cmbSchema, 2, 2, 1, 1)
        self.lblSchema = QtGui.QLabel(self.wgtFilters)
        self.lblSchema.setObjectName(_fromUtf8("lblSchema"))
        self.gridLayout.addWidget(self.lblSchema, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.wgtFilters)
        self.splNomenclatureExpence = QtGui.QSplitter(NomenclatureExpenseDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splNomenclatureExpence.sizePolicy().hasHeightForWidth())
        self.splNomenclatureExpence.setSizePolicy(sizePolicy)
        self.splNomenclatureExpence.setOrientation(QtCore.Qt.Horizontal)
        self.splNomenclatureExpence.setObjectName(_fromUtf8("splNomenclatureExpence"))
        self.pnlNomenclatureExpense = QtGui.QWidget(self.splNomenclatureExpence)
        self.pnlNomenclatureExpense.setObjectName(_fromUtf8("pnlNomenclatureExpense"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pnlNomenclatureExpense)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tblNomenclatureExpense = CNomenclatureExpenseView(self.pnlNomenclatureExpense)
        self.tblNomenclatureExpense.setObjectName(_fromUtf8("tblNomenclatureExpense"))
        self.verticalLayout_3.addWidget(self.tblNomenclatureExpense)
        self.pnlNomenclatureExpenseDays = QtGui.QWidget(self.splNomenclatureExpence)
        self.pnlNomenclatureExpenseDays.setObjectName(_fromUtf8("pnlNomenclatureExpenseDays"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pnlNomenclatureExpenseDays)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tblNomenclatureExpenseDays = CNomenclatureExpenseView(self.pnlNomenclatureExpenseDays)
        self.tblNomenclatureExpenseDays.setObjectName(_fromUtf8("tblNomenclatureExpenseDays"))
        self.verticalLayout_4.addWidget(self.tblNomenclatureExpenseDays)
        self.verticalLayout_2.addWidget(self.splNomenclatureExpence)
        self.buttonBox = QtGui.QDialogButtonBox(NomenclatureExpenseDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(NomenclatureExpenseDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), NomenclatureExpenseDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), NomenclatureExpenseDialog.reject)
        QtCore.QObject.connect(self.chkPeriod, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.wgtPeriod.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(NomenclatureExpenseDialog)
        NomenclatureExpenseDialog.setTabOrder(self.cmbActionType, self.cmbOrgStructure)
        NomenclatureExpenseDialog.setTabOrder(self.cmbOrgStructure, self.cmbSchema)
        NomenclatureExpenseDialog.setTabOrder(self.cmbSchema, self.cmbNomenclature)
        NomenclatureExpenseDialog.setTabOrder(self.cmbNomenclature, self.chkPeriod)
        NomenclatureExpenseDialog.setTabOrder(self.chkPeriod, self.edtBegDate)
        NomenclatureExpenseDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        NomenclatureExpenseDialog.setTabOrder(self.edtEndDate, self.chkActual)
        NomenclatureExpenseDialog.setTabOrder(self.chkActual, self.edtYear)
        NomenclatureExpenseDialog.setTabOrder(self.edtYear, self.chkIgnoreTime)
        NomenclatureExpenseDialog.setTabOrder(self.chkIgnoreTime, self.cmbMonth)
        NomenclatureExpenseDialog.setTabOrder(self.cmbMonth, self.chkRequiresFillingNomenclature)
        NomenclatureExpenseDialog.setTabOrder(self.chkRequiresFillingNomenclature, self.chkCurrentEvent)
        NomenclatureExpenseDialog.setTabOrder(self.chkCurrentEvent, self.btnReset)
        NomenclatureExpenseDialog.setTabOrder(self.btnReset, self.tblNomenclatureExpense)
        NomenclatureExpenseDialog.setTabOrder(self.tblNomenclatureExpense, self.tblNomenclatureExpenseDays)
        NomenclatureExpenseDialog.setTabOrder(self.tblNomenclatureExpenseDays, self.buttonBox)

    def retranslateUi(self, NomenclatureExpenseDialog):
        NomenclatureExpenseDialog.setWindowTitle(_translate("NomenclatureExpenseDialog", "Dialog", None))
        self.lblMonth.setText(_translate("NomenclatureExpenseDialog", "Месяц", None))
        self.cmbMonth.setItemText(0, _translate("NomenclatureExpenseDialog", "Январь", None))
        self.cmbMonth.setItemText(1, _translate("NomenclatureExpenseDialog", "Февраль", None))
        self.cmbMonth.setItemText(2, _translate("NomenclatureExpenseDialog", "Март", None))
        self.cmbMonth.setItemText(3, _translate("NomenclatureExpenseDialog", "Апрель", None))
        self.cmbMonth.setItemText(4, _translate("NomenclatureExpenseDialog", "Май", None))
        self.cmbMonth.setItemText(5, _translate("NomenclatureExpenseDialog", "Июнь", None))
        self.cmbMonth.setItemText(6, _translate("NomenclatureExpenseDialog", "Июль", None))
        self.cmbMonth.setItemText(7, _translate("NomenclatureExpenseDialog", "Август", None))
        self.cmbMonth.setItemText(8, _translate("NomenclatureExpenseDialog", "Сентябрь", None))
        self.cmbMonth.setItemText(9, _translate("NomenclatureExpenseDialog", "Октябрь", None))
        self.cmbMonth.setItemText(10, _translate("NomenclatureExpenseDialog", "Ноябрь", None))
        self.cmbMonth.setItemText(11, _translate("NomenclatureExpenseDialog", "Декабрь", None))
        self.lblYear.setText(_translate("NomenclatureExpenseDialog", "Год", None))
        self.lblOrgStructure.setText(_translate("NomenclatureExpenseDialog", "Подразделение", None))
        self.lblNomenclature.setText(_translate("NomenclatureExpenseDialog", "ЛС", None))
        self.lblActionType.setText(_translate("NomenclatureExpenseDialog", "Тип действия", None))
        self.chkPeriod.setText(_translate("NomenclatureExpenseDialog", "Период", None))
        self.chkCurrentEvent.setText(_translate("NomenclatureExpenseDialog", "Текущее событие", None))
        self.chkActual.setText(_translate("NomenclatureExpenseDialog", "Только актуальные", None))
        self.chkIgnoreTime.setText(_translate("NomenclatureExpenseDialog", "Игнорировать время", None))
        self.chkRequiresFillingNomenclature.setText(_translate("NomenclatureExpenseDialog", "Требует заполнения ЛС", None))
        self.btnReset.setText(_translate("NomenclatureExpenseDialog", "Сбросить", None))
        self.lblBegDate.setText(_translate("NomenclatureExpenseDialog", "С  ", None))
        self.lblEndDate.setText(_translate("NomenclatureExpenseDialog", "  По  ", None))
        self.lblSchema.setText(_translate("NomenclatureExpenseDialog", "Схема", None))
        self.tblNomenclatureExpenseDays.setToolTip(_translate("NomenclatureExpenseDialog", "Список ранее назначенных мероприятий", None))

from Events.ActionTypeComboBox import CActionTypeComboBox
from Events.NomenclatureExpense.NomenclatureExpenseView import CNomenclatureExpenseView
from Orgs.OrgStructComboBoxes import CStorageComboBox
from Stock.NomenclatureComboBox import CNomenclatureComboBox
from library.DateEdit import CDateEdit
from library.SpinBox import CSpinBox
from library.crbcombobox import CRBComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    NomenclatureExpenseDialog = QtGui.QDialog()
    ui = Ui_NomenclatureExpenseDialog()
    ui.setupUi(NomenclatureExpenseDialog)
    NomenclatureExpenseDialog.show()
    sys.exit(app.exec_())

