# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from Exchange.RISExchange.Protos import hl7server_pb2 as hl7server__pb2


class CommunicationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExecCommand = channel.unary_unary(
        '/hl7server.Communication/ExecCommand',
        request_serializer=hl7server__pb2.MessageRequest.SerializeToString,
        response_deserializer=hl7server__pb2.MessageReply.FromString,
        )


class CommunicationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ExecCommand(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CommunicationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExecCommand': grpc.unary_unary_rpc_method_handler(
          servicer.ExecCommand,
          request_deserializer=hl7server__pb2.MessageRequest.FromString,
          response_serializer=hl7server__pb2.MessageReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hl7server.Communication', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
