# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\Samson\UP_s11\client\preferences\ClientCardPage.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_clientCardPage(object):
    def setupUi(self, clientCardPage):
        clientCardPage.setObjectName(_fromUtf8("clientCardPage"))
        clientCardPage.resize(543, 364)
        self.gridLayout = QtGui.QGridLayout(clientCardPage)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.grpPassport = QtGui.QGroupBox(clientCardPage)
        self.grpPassport.setAlignment(QtCore.Qt.AlignCenter)
        self.grpPassport.setObjectName(_fromUtf8("grpPassport"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpPassport)
        self.gridLayout_2.setMargin(2)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.chkVoluntaryPolisName = QtGui.QCheckBox(self.grpPassport)
        self.chkVoluntaryPolisName.setCheckable(True)
        self.chkVoluntaryPolisName.setChecked(True)
        self.chkVoluntaryPolisName.setObjectName(_fromUtf8("chkVoluntaryPolisName"))
        self.gridLayout_2.addWidget(self.chkVoluntaryPolisName, 5, 2, 1, 1)
        self.chkVoluntaryPolisNote = QtGui.QCheckBox(self.grpPassport)
        self.chkVoluntaryPolisNote.setCheckable(True)
        self.chkVoluntaryPolisNote.setChecked(True)
        self.chkVoluntaryPolisNote.setObjectName(_fromUtf8("chkVoluntaryPolisNote"))
        self.gridLayout_2.addWidget(self.chkVoluntaryPolisNote, 6, 2, 1, 1)
        self.chkDocOrigin = QtGui.QCheckBox(self.grpPassport)
        self.chkDocOrigin.setChecked(True)
        self.chkDocOrigin.setObjectName(_fromUtf8("chkDocOrigin"))
        self.gridLayout_2.addWidget(self.chkDocOrigin, 1, 2, 1, 1)
        self.chkDeathDate = QtGui.QCheckBox(self.grpPassport)
        self.chkDeathDate.setChecked(True)
        self.chkDeathDate.setObjectName(_fromUtf8("chkDeathDate"))
        self.gridLayout_2.addWidget(self.chkDeathDate, 1, 1, 1, 1)
        self.chkSNILS = QtGui.QCheckBox(self.grpPassport)
        self.chkSNILS.setChecked(True)
        self.chkSNILS.setObjectName(_fromUtf8("chkSNILS"))
        self.gridLayout_2.addWidget(self.chkSNILS, 2, 1, 1, 1)
        self.chkVoluntaryPolicy = QtGui.QCheckBox(self.grpPassport)
        self.chkVoluntaryPolicy.setChecked(True)
        self.chkVoluntaryPolicy.setObjectName(_fromUtf8("chkVoluntaryPolicy"))
        self.gridLayout_2.addWidget(self.chkVoluntaryPolicy, 2, 2, 1, 1)
        self.chkCompulsoryPolisName = QtGui.QCheckBox(self.grpPassport)
        self.chkCompulsoryPolisName.setChecked(True)
        self.chkCompulsoryPolisName.setObjectName(_fromUtf8("chkCompulsoryPolisName"))
        self.gridLayout_2.addWidget(self.chkCompulsoryPolisName, 6, 1, 1, 1)
        self.chkCompulsoryPolisNote = QtGui.QCheckBox(self.grpPassport)
        self.chkCompulsoryPolisNote.setChecked(True)
        self.chkCompulsoryPolisNote.setObjectName(_fromUtf8("chkCompulsoryPolisNote"))
        self.gridLayout_2.addWidget(self.chkCompulsoryPolisNote, 7, 1, 1, 1)
        self.chkBirthTime = QtGui.QCheckBox(self.grpPassport)
        self.chkBirthTime.setChecked(True)
        self.chkBirthTime.setObjectName(_fromUtf8("chkBirthTime"))
        self.gridLayout_2.addWidget(self.chkBirthTime, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.grpPassport, 12, 0, 1, 2)
        self.grpTabWidgets = QtGui.QGroupBox(clientCardPage)
        self.grpTabWidgets.setAlignment(QtCore.Qt.AlignCenter)
        self.grpTabWidgets.setObjectName(_fromUtf8("grpTabWidgets"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpTabWidgets)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.chkTabAttach = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabAttach.setChecked(True)
        self.chkTabAttach.setObjectName(_fromUtf8("chkTabAttach"))
        self.gridLayout_3.addWidget(self.chkTabAttach, 5, 0, 1, 1)
        self.chkTabWork = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabWork.setChecked(True)
        self.chkTabWork.setObjectName(_fromUtf8("chkTabWork"))
        self.gridLayout_3.addWidget(self.chkTabWork, 6, 0, 1, 1)
        self.chkTabSocStatus = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabSocStatus.setChecked(True)
        self.chkTabSocStatus.setObjectName(_fromUtf8("chkTabSocStatus"))
        self.gridLayout_3.addWidget(self.chkTabSocStatus, 3, 0, 1, 1)
        self.chkTabDangerous = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabDangerous.setChecked(True)
        self.chkTabDangerous.setObjectName(_fromUtf8("chkTabDangerous"))
        self.gridLayout_3.addWidget(self.chkTabDangerous, 10, 0, 1, 1)
        self.chkTabResearch = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabResearch.setChecked(True)
        self.chkTabResearch.setObjectName(_fromUtf8("chkTabResearch"))
        self.gridLayout_3.addWidget(self.chkTabResearch, 9, 0, 1, 1)
        self.chkTabFeature = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabFeature.setChecked(True)
        self.chkTabFeature.setObjectName(_fromUtf8("chkTabFeature"))
        self.gridLayout_3.addWidget(self.chkTabFeature, 8, 0, 1, 1)
        self.chkTabChangeJournal = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabChangeJournal.setChecked(True)
        self.chkTabChangeJournal.setObjectName(_fromUtf8("chkTabChangeJournal"))
        self.gridLayout_3.addWidget(self.chkTabChangeJournal, 7, 0, 1, 1)
        self.chkTabContingentKind = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabContingentKind.setChecked(True)
        self.chkTabContingentKind.setObjectName(_fromUtf8("chkTabContingentKind"))
        self.gridLayout_3.addWidget(self.chkTabContingentKind, 11, 0, 1, 1)
        self.chkTabConsent = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabConsent.setChecked(True)
        self.chkTabConsent.setObjectName(_fromUtf8("chkTabConsent"))
        self.gridLayout_3.addWidget(self.chkTabConsent, 9, 1, 1, 1)
        self.chkTabDeposit = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabDeposit.setChecked(True)
        self.chkTabDeposit.setObjectName(_fromUtf8("chkTabDeposit"))
        self.gridLayout_3.addWidget(self.chkTabDeposit, 8, 1, 1, 1)
        self.chkTabQuoting = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabQuoting.setChecked(True)
        self.chkTabQuoting.setObjectName(_fromUtf8("chkTabQuoting"))
        self.gridLayout_3.addWidget(self.chkTabQuoting, 7, 1, 1, 1)
        self.chkTabContacts = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabContacts.setChecked(True)
        self.chkTabContacts.setObjectName(_fromUtf8("chkTabContacts"))
        self.gridLayout_3.addWidget(self.chkTabContacts, 6, 1, 1, 1)
        self.chkTabRelations = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabRelations.setChecked(True)
        self.chkTabRelations.setObjectName(_fromUtf8("chkTabRelations"))
        self.gridLayout_3.addWidget(self.chkTabRelations, 5, 1, 1, 1)
        self.chkTabIdentification = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabIdentification.setChecked(True)
        self.chkTabIdentification.setObjectName(_fromUtf8("chkTabIdentification"))
        self.gridLayout_3.addWidget(self.chkTabIdentification, 3, 1, 1, 1)
        self.chkTabMonitoring = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabMonitoring.setChecked(True)
        self.chkTabMonitoring.setObjectName(_fromUtf8("chkTabMonitoring"))
        self.gridLayout_3.addWidget(self.chkTabMonitoring, 10, 1, 1, 1)
        self.chkTabEpidCase = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabEpidCase.setChecked(True)
        self.chkTabEpidCase.setObjectName(_fromUtf8("chkTabEpidCase"))
        self.gridLayout_3.addWidget(self.chkTabEpidCase, 11, 1, 1, 1)
        self.chkTabHospitalization = QtGui.QCheckBox(self.grpTabWidgets)
        self.chkTabHospitalization.setChecked(True)
        self.chkTabHospitalization.setObjectName(_fromUtf8("chkTabHospitalization"))
        self.gridLayout_3.addWidget(self.chkTabHospitalization, 12, 0, 1, 1)
        self.gridLayout.addWidget(self.grpTabWidgets, 13, 0, 1, 2)
        self.lblCheckPolicyAffiliation = QtGui.QLabel(clientCardPage)
        self.lblCheckPolicyAffiliation.setObjectName(_fromUtf8("lblCheckPolicyAffiliation"))
        self.gridLayout.addWidget(self.lblCheckPolicyAffiliation, 0, 0, 1, 1)
        self.cmbCheckPolicyAffiliation = QtGui.QComboBox(clientCardPage)
        self.cmbCheckPolicyAffiliation.setObjectName(_fromUtf8("cmbCheckPolicyAffiliation"))
        self.cmbCheckPolicyAffiliation.addItem(_fromUtf8(""))
        self.cmbCheckPolicyAffiliation.addItem(_fromUtf8(""))
        self.cmbCheckPolicyAffiliation.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbCheckPolicyAffiliation, 0, 1, 1, 1)
        self.lblResident = QtGui.QLabel(clientCardPage)
        self.lblResident.setObjectName(_fromUtf8("lblResident"))
        self.gridLayout.addWidget(self.lblResident, 15, 0, 1, 1)
        self.cmbResident = QtGui.QComboBox(clientCardPage)
        self.cmbResident.setObjectName(_fromUtf8("cmbResident"))
        self.cmbResident.addItem(_fromUtf8(""))
        self.cmbResident.addItem(_fromUtf8(""))
        self.cmbResident.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbResident, 15, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 16, 0, 1, 1)

        self.retranslateUi(clientCardPage)
        QtCore.QObject.connect(self.chkVoluntaryPolicy, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkVoluntaryPolisName.setEnabled)
        QtCore.QObject.connect(self.chkVoluntaryPolicy, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkVoluntaryPolisNote.setEnabled)
        QtCore.QObject.connect(self.chkVoluntaryPolicy, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkVoluntaryPolisName.setChecked)
        QtCore.QObject.connect(self.chkVoluntaryPolicy, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkVoluntaryPolisNote.setChecked)
        QtCore.QMetaObject.connectSlotsByName(clientCardPage)
        clientCardPage.setTabOrder(self.cmbCheckPolicyAffiliation, self.chkDeathDate)
        clientCardPage.setTabOrder(self.chkDeathDate, self.chkBirthTime)
        clientCardPage.setTabOrder(self.chkBirthTime, self.chkSNILS)
        clientCardPage.setTabOrder(self.chkSNILS, self.chkCompulsoryPolisName)
        clientCardPage.setTabOrder(self.chkCompulsoryPolisName, self.chkCompulsoryPolisNote)
        clientCardPage.setTabOrder(self.chkCompulsoryPolisNote, self.chkDocOrigin)
        clientCardPage.setTabOrder(self.chkDocOrigin, self.chkVoluntaryPolicy)
        clientCardPage.setTabOrder(self.chkVoluntaryPolicy, self.chkVoluntaryPolisName)
        clientCardPage.setTabOrder(self.chkVoluntaryPolisName, self.chkVoluntaryPolisNote)
        clientCardPage.setTabOrder(self.chkVoluntaryPolisNote, self.chkTabSocStatus)
        clientCardPage.setTabOrder(self.chkTabSocStatus, self.chkTabAttach)
        clientCardPage.setTabOrder(self.chkTabAttach, self.chkTabWork)
        clientCardPage.setTabOrder(self.chkTabWork, self.chkTabFeature)
        clientCardPage.setTabOrder(self.chkTabFeature, self.chkTabChangeJournal)

    def retranslateUi(self, clientCardPage):
        clientCardPage.setWindowTitle(_translate("clientCardPage", "Регистрационная карта пациента", None))
        self.grpPassport.setTitle(_translate("clientCardPage", "Визуализация: Паспортные &данные", None))
        self.chkVoluntaryPolisName.setText(_translate("clientCardPage", "Название полиса ДМС", None))
        self.chkVoluntaryPolisNote.setText(_translate("clientCardPage", "Примечание полиса ДМС", None))
        self.chkDocOrigin.setText(_translate("clientCardPage", "Кем выдан документа, удостоверяющего личность", None))
        self.chkDeathDate.setText(_translate("clientCardPage", "Дата смерти", None))
        self.chkSNILS.setText(_translate("clientCardPage", "СНИЛС", None))
        self.chkVoluntaryPolicy.setText(_translate("clientCardPage", "Данные полиса ДМС", None))
        self.chkCompulsoryPolisName.setText(_translate("clientCardPage", "Название полиса ОМС", None))
        self.chkCompulsoryPolisNote.setText(_translate("clientCardPage", "Примечание полиса ОМС", None))
        self.chkBirthTime.setText(_translate("clientCardPage", "Время рождения", None))
        self.grpTabWidgets.setTitle(_translate("clientCardPage", "Визуализация: Вкладки", None))
        self.chkTabAttach.setText(_translate("clientCardPage", "Вкладка Прикрепление", None))
        self.chkTabWork.setText(_translate("clientCardPage", "Вкладка Занятость", None))
        self.chkTabSocStatus.setText(_translate("clientCardPage", "Вкладка Соц.статус", None))
        self.chkTabDangerous.setText(_translate("clientCardPage", "Вкладка Общ. опасность", None))
        self.chkTabResearch.setText(_translate("clientCardPage", "Вкладка Обследования", None))
        self.chkTabFeature.setText(_translate("clientCardPage", "Вкладка Особенности", None))
        self.chkTabChangeJournal.setText(_translate("clientCardPage", "Вкладка Журнал изменений", None))
        self.chkTabContingentKind.setText(_translate("clientCardPage", "Вкладка Контингент", None))
        self.chkTabConsent.setText(_translate("clientCardPage", "Вкладка Согласия", None))
        self.chkTabDeposit.setText(_translate("clientCardPage", "Вкладка Депозитная карта", None))
        self.chkTabQuoting.setText(_translate("clientCardPage", "Вкладка Квоты", None))
        self.chkTabContacts.setText(_translate("clientCardPage", "Вкладка Прочее", None))
        self.chkTabRelations.setText(_translate("clientCardPage", "Вкладка Связи", None))
        self.chkTabIdentification.setText(_translate("clientCardPage", "Вкладка Идентификаторы", None))
        self.chkTabMonitoring.setText(_translate("clientCardPage", "Вкладка Мониторинг", None))
        self.chkTabEpidCase.setText(_translate("clientCardPage", "Вкладка ЭпидНаблюдение", None))
        self.chkTabHospitalization.setText(_translate("clientCardPage", "Вкладка Сведения о госпитализациях", None))
        self.lblCheckPolicyAffiliation.setText(_translate("clientCardPage", "Контроль проверки страховой принадлежности", None))
        self.cmbCheckPolicyAffiliation.setItemText(0, _translate("clientCardPage", "Не выполнять", None))
        self.cmbCheckPolicyAffiliation.setItemText(1, _translate("clientCardPage", "Мягко", None))
        self.cmbCheckPolicyAffiliation.setItemText(2, _translate("clientCardPage", "Строго", None))
        self.lblResident.setText(_translate("clientCardPage", "Житель", None))
        self.cmbResident.setItemText(0, _translate("clientCardPage", "Не задано", None))
        self.cmbResident.setItemText(1, _translate("clientCardPage", "Городской", None))
        self.cmbResident.setItemText(2, _translate("clientCardPage", "Сельский", None))

