# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\preferences\ClientPlatePage.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_clientPlatePage(object):
    def setupUi(self, clientPlatePage):
        clientPlatePage.setObjectName(_fromUtf8("clientPlatePage"))
        clientPlatePage.resize(766, 541)
        self.gridLayout = QtGui.QGridLayout(clientPlatePage)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.chkResearch = QtGui.QCheckBox(clientPlatePage)
        self.chkResearch.setObjectName(_fromUtf8("chkResearch"))
        self.gridLayout.addWidget(self.chkResearch, 9, 1, 1, 1)
        self.chkIntoleranceMedicament = QtGui.QCheckBox(clientPlatePage)
        self.chkIntoleranceMedicament.setObjectName(_fromUtf8("chkIntoleranceMedicament"))
        self.gridLayout.addWidget(self.chkIntoleranceMedicament, 10, 1, 1, 1)
        self.chkLocAddress = QtGui.QCheckBox(clientPlatePage)
        self.chkLocAddress.setObjectName(_fromUtf8("chkLocAddress"))
        self.gridLayout.addWidget(self.chkLocAddress, 2, 1, 1, 1)
        self.cmbShowingInInfoBlockSocStatus = QtGui.QComboBox(clientPlatePage)
        self.cmbShowingInInfoBlockSocStatus.setObjectName(_fromUtf8("cmbShowingInInfoBlockSocStatus"))
        self.cmbShowingInInfoBlockSocStatus.addItem(_fromUtf8(""))
        self.cmbShowingInInfoBlockSocStatus.addItem(_fromUtf8(""))
        self.cmbShowingInInfoBlockSocStatus.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbShowingInInfoBlockSocStatus, 17, 1, 1, 1)
        self.chkObservationStatus = QtGui.QCheckBox(clientPlatePage)
        self.chkObservationStatus.setObjectName(_fromUtf8("chkObservationStatus"))
        self.gridLayout.addWidget(self.chkObservationStatus, 12, 0, 1, 1)
        self.lblEpidCase = QtGui.QLabel(clientPlatePage)
        self.lblEpidCase.setObjectName(_fromUtf8("lblEpidCase"))
        self.gridLayout.addWidget(self.lblEpidCase, 18, 0, 1, 1)
        self.cmbEpidCase = QtGui.QComboBox(clientPlatePage)
        self.cmbEpidCase.setObjectName(_fromUtf8("cmbEpidCase"))
        self.cmbEpidCase.addItem(_fromUtf8(""))
        self.cmbEpidCase.addItem(_fromUtf8(""))
        self.cmbEpidCase.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbEpidCase, 18, 1, 1, 1)
        self.chkObservationGroup = QtGui.QCheckBox(clientPlatePage)
        self.chkObservationGroup.setObjectName(_fromUtf8("chkObservationGroup"))
        self.gridLayout.addWidget(self.chkObservationGroup, 9, 0, 1, 1)
        self.chkDispanserySpecialities = QtGui.QCheckBox(clientPlatePage)
        self.chkDispanserySpecialities.setObjectName(_fromUtf8("chkDispanserySpecialities"))
        self.gridLayout.addWidget(self.chkDispanserySpecialities, 10, 0, 1, 1)
        self.chkPhones = QtGui.QCheckBox(clientPlatePage)
        self.chkPhones.setObjectName(_fromUtf8("chkPhones"))
        self.gridLayout.addWidget(self.chkPhones, 4, 1, 1, 1)
        self.chkNotes = QtGui.QCheckBox(clientPlatePage)
        self.chkNotes.setObjectName(_fromUtf8("chkNotes"))
        self.gridLayout.addWidget(self.chkNotes, 5, 1, 1, 1)
        self.chkAttaches = QtGui.QCheckBox(clientPlatePage)
        self.chkAttaches.setObjectName(_fromUtf8("chkAttaches"))
        self.gridLayout.addWidget(self.chkAttaches, 8, 0, 1, 1)
        self.chkVoluntaryPolicy = QtGui.QCheckBox(clientPlatePage)
        self.chkVoluntaryPolicy.setObjectName(_fromUtf8("chkVoluntaryPolicy"))
        self.gridLayout.addWidget(self.chkVoluntaryPolicy, 0, 1, 1, 1)
        self.chkWork = QtGui.QCheckBox(clientPlatePage)
        self.chkWork.setObjectName(_fromUtf8("chkWork"))
        self.gridLayout.addWidget(self.chkWork, 3, 1, 1, 1)
        self.chkBirthPlace = QtGui.QCheckBox(clientPlatePage)
        self.chkBirthPlace.setObjectName(_fromUtf8("chkBirthPlace"))
        self.gridLayout.addWidget(self.chkBirthPlace, 7, 1, 1, 1)
        self.chkAllergy = QtGui.QCheckBox(clientPlatePage)
        self.chkAllergy.setObjectName(_fromUtf8("chkAllergy"))
        self.gridLayout.addWidget(self.chkAllergy, 6, 1, 1, 1)
        self.chkNewLine = QtGui.QCheckBox(clientPlatePage)
        self.chkNewLine.setObjectName(_fromUtf8("chkNewLine"))
        self.gridLayout.addWidget(self.chkNewLine, 15, 0, 1, 1)
        self.lblShowingInInfoBlockSocStatus = QtGui.QLabel(clientPlatePage)
        self.lblShowingInInfoBlockSocStatus.setObjectName(_fromUtf8("lblShowingInInfoBlockSocStatus"))
        self.gridLayout.addWidget(self.lblShowingInInfoBlockSocStatus, 17, 0, 1, 1)
        self.chkIdentification = QtGui.QCheckBox(clientPlatePage)
        self.chkIdentification.setObjectName(_fromUtf8("chkIdentification"))
        self.gridLayout.addWidget(self.chkIdentification, 2, 0, 1, 1)
        self.cmbClientContingent = QtGui.QComboBox(clientPlatePage)
        self.cmbClientContingent.setObjectName(_fromUtf8("cmbClientContingent"))
        self.cmbClientContingent.addItem(_fromUtf8(""))
        self.cmbClientContingent.addItem(_fromUtf8(""))
        self.cmbClientContingent.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbClientContingent, 16, 1, 1, 1)
        self.chkDocument = QtGui.QCheckBox(clientPlatePage)
        self.chkDocument.setObjectName(_fromUtf8("chkDocument"))
        self.gridLayout.addWidget(self.chkDocument, 5, 0, 1, 1)
        self.chkQuoting = QtGui.QCheckBox(clientPlatePage)
        self.chkQuoting.setObjectName(_fromUtf8("chkQuoting"))
        self.gridLayout.addWidget(self.chkQuoting, 3, 0, 1, 1)
        self.chkHospitalBed = QtGui.QCheckBox(clientPlatePage)
        self.chkHospitalBed.setObjectName(_fromUtf8("chkHospitalBed"))
        self.gridLayout.addWidget(self.chkHospitalBed, 7, 0, 1, 1)
        self.chkSocStatuses = QtGui.QCheckBox(clientPlatePage)
        self.chkSocStatuses.setObjectName(_fromUtf8("chkSocStatuses"))
        self.gridLayout.addWidget(self.chkSocStatuses, 4, 0, 1, 1)
        self.chkCompulsoryPolicy = QtGui.QCheckBox(clientPlatePage)
        self.chkCompulsoryPolicy.setObjectName(_fromUtf8("chkCompulsoryPolicy"))
        self.gridLayout.addWidget(self.chkCompulsoryPolicy, 6, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 21, 0, 1, 2)
        self.chkFIO = QtGui.QCheckBox(clientPlatePage)
        self.chkFIO.setObjectName(_fromUtf8("chkFIO"))
        self.gridLayout.addWidget(self.chkFIO, 0, 0, 1, 1)
        self.chkConsents = QtGui.QCheckBox(clientPlatePage)
        self.chkConsents.setObjectName(_fromUtf8("chkConsents"))
        self.gridLayout.addWidget(self.chkConsents, 1, 0, 1, 1)
        self.chkRegAddress = QtGui.QCheckBox(clientPlatePage)
        self.chkRegAddress.setObjectName(_fromUtf8("chkRegAddress"))
        self.gridLayout.addWidget(self.chkRegAddress, 1, 1, 1, 1)
        self.lblClientContingent = QtGui.QLabel(clientPlatePage)
        self.lblClientContingent.setObjectName(_fromUtf8("lblClientContingent"))
        self.gridLayout.addWidget(self.lblClientContingent, 16, 0, 1, 1)
        self.lblTFAccountingSystemId = QtGui.QLabel(clientPlatePage)
        self.lblTFAccountingSystemId.setObjectName(_fromUtf8("lblTFAccountingSystemId"))
        self.gridLayout.addWidget(self.lblTFAccountingSystemId, 19, 0, 1, 1)
        self.cmbTFAccountingSystemId = CRBComboBox(clientPlatePage)
        self.cmbTFAccountingSystemId.setObjectName(_fromUtf8("cmbTFAccountingSystemId"))
        self.gridLayout.addWidget(self.cmbTFAccountingSystemId, 19, 1, 1, 1)
        self.chkRelations = QtGui.QCheckBox(clientPlatePage)
        self.chkRelations.setObjectName(_fromUtf8("chkRelations"))
        self.gridLayout.addWidget(self.chkRelations, 8, 1, 1, 1)
        self.chkTFOMS = QtGui.QCheckBox(clientPlatePage)
        self.chkTFOMS.setObjectName(_fromUtf8("chkTFOMS"))
        self.gridLayout.addWidget(self.chkTFOMS, 15, 1, 1, 1)
        self.chkProf = QtGui.QCheckBox(clientPlatePage)
        self.chkProf.setObjectName(_fromUtf8("chkProf"))
        self.gridLayout.addWidget(self.chkProf, 12, 1, 1, 1)
        self.lblShowingInInfoBlockSocStatus.setBuddy(self.cmbShowingInInfoBlockSocStatus)
        self.lblTFAccountingSystemId.setBuddy(self.cmbTFAccountingSystemId)

        self.retranslateUi(clientPlatePage)
        QtCore.QMetaObject.connectSlotsByName(clientPlatePage)

    def retranslateUi(self, clientPlatePage):
        clientPlatePage.setWindowTitle(_translate("clientPlatePage", "Сведения о пациенте", None))
        self.chkResearch.setText(_translate("clientPlatePage", "Обследования", None))
        self.chkIntoleranceMedicament.setText(_translate("clientPlatePage", "Медикаментозная непереносимость", None))
        self.chkLocAddress.setText(_translate("clientPlatePage", "Адрес проживания", None))
        self.cmbShowingInInfoBlockSocStatus.setItemText(0, _translate("clientPlatePage", "Код", None))
        self.cmbShowingInInfoBlockSocStatus.setItemText(1, _translate("clientPlatePage", "Наименование", None))
        self.cmbShowingInInfoBlockSocStatus.setItemText(2, _translate("clientPlatePage", "Наименование и код", None))
        self.chkObservationStatus.setText(_translate("clientPlatePage", "Статус наблюдения", None))
        self.lblEpidCase.setText(_translate("clientPlatePage", "ЭпидНаблюдение", None))
        self.cmbEpidCase.setItemText(0, _translate("clientPlatePage", "отображать последний", None))
        self.cmbEpidCase.setItemText(1, _translate("clientPlatePage", "отображать все", None))
        self.cmbEpidCase.setItemText(2, _translate("clientPlatePage", "не отображать", None))
        self.chkObservationGroup.setText(_translate("clientPlatePage", "Группа наблюдения", None))
        self.chkDispanserySpecialities.setText(_translate("clientPlatePage", "Д-учет", None))
        self.chkPhones.setText(_translate("clientPlatePage", "Контакты", None))
        self.chkNotes.setText(_translate("clientPlatePage", "Примечания", None))
        self.chkAttaches.setText(_translate("clientPlatePage", "Прикрепление", None))
        self.chkVoluntaryPolicy.setText(_translate("clientPlatePage", "Полис ДМС", None))
        self.chkWork.setText(_translate("clientPlatePage", "Занятость", None))
        self.chkBirthPlace.setText(_translate("clientPlatePage", "Место рождения", None))
        self.chkAllergy.setText(_translate("clientPlatePage", "Аллергия", None))
        self.chkNewLine.setText(_translate("clientPlatePage", "Каждый блок с новой строки", None))
        self.lblShowingInInfoBlockSocStatus.setText(_translate("clientPlatePage", "Отображать Социальный статус пациента как", None))
        self.chkIdentification.setText(_translate("clientPlatePage", "Идентификаторы", None))
        self.cmbClientContingent.setItemText(0, _translate("clientPlatePage", "отображать приоритетный", None))
        self.cmbClientContingent.setItemText(1, _translate("clientPlatePage", "отображать все", None))
        self.cmbClientContingent.setItemText(2, _translate("clientPlatePage", "не отображать", None))
        self.chkDocument.setText(_translate("clientPlatePage", "Документ", None))
        self.chkQuoting.setText(_translate("clientPlatePage", "Квоты", None))
        self.chkHospitalBed.setText(_translate("clientPlatePage", "Госпитализация", None))
        self.chkSocStatuses.setText(_translate("clientPlatePage", "Соц. Статус", None))
        self.chkCompulsoryPolicy.setText(_translate("clientPlatePage", "Полис ОМС", None))
        self.chkFIO.setText(_translate("clientPlatePage", "ФИО", None))
        self.chkConsents.setText(_translate("clientPlatePage", "Согласия", None))
        self.chkRegAddress.setText(_translate("clientPlatePage", "Адрес регистрации", None))
        self.lblClientContingent.setText(_translate("clientPlatePage", "Наблюдаемые контингенты", None))
        self.lblTFAccountingSystemId.setText(_translate("clientPlatePage", "Отображать идентификатор ТФОМС по справочнику", None))
        self.chkRelations.setText(_translate("clientPlatePage", "Связи", None))
        self.chkTFOMS.setText(_translate("clientPlatePage", "Дата подтверждения ТФОМС", None))
        self.chkProf.setText(_translate("clientPlatePage", "Профилактические мероприятия", None))

from library.crbcombobox import CRBComboBox
