# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Samson\UP_s11\client_test\preferences\EventPage.ui'
#
# Created: Mon Jul 10 09:58:00 2023
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_eventPage(object):
    def setupUi(self, eventPage):
        eventPage.setObjectName(_fromUtf8("eventPage"))
        eventPage.resize(669, 439)
        self.gridLayout = QtGui.QGridLayout(eventPage)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblAverageDuration = QtGui.QLabel(eventPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAverageDuration.sizePolicy().hasHeightForWidth())
        self.lblAverageDuration.setSizePolicy(sizePolicy)
        self.lblAverageDuration.setObjectName(_fromUtf8("lblAverageDuration"))
        self.gridLayout.addWidget(self.lblAverageDuration, 0, 0, 1, 1)
        self.edtAverageDuration = QtGui.QSpinBox(eventPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAverageDuration.sizePolicy().hasHeightForWidth())
        self.edtAverageDuration.setSizePolicy(sizePolicy)
        self.edtAverageDuration.setObjectName(_fromUtf8("edtAverageDuration"))
        self.gridLayout.addWidget(self.edtAverageDuration, 0, 1, 1, 1)
        self.cmbDiagnosisTypeAfterFinalForm043 = QtGui.QComboBox(eventPage)
        self.cmbDiagnosisTypeAfterFinalForm043.setObjectName(_fromUtf8("cmbDiagnosisTypeAfterFinalForm043"))
        self.cmbDiagnosisTypeAfterFinalForm043.addItem(_fromUtf8(""))
        self.cmbDiagnosisTypeAfterFinalForm043.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbDiagnosisTypeAfterFinalForm043, 2, 1, 1, 1)
        self.lblFillDiagnosticsEventsResults = QtGui.QLabel(eventPage)
        self.lblFillDiagnosticsEventsResults.setObjectName(_fromUtf8("lblFillDiagnosticsEventsResults"))
        self.gridLayout.addWidget(self.lblFillDiagnosticsEventsResults, 1, 0, 1, 1)
        self.lblDiagnosisTypeAfterFinalForm043 = QtGui.QLabel(eventPage)
        self.lblDiagnosisTypeAfterFinalForm043.setObjectName(_fromUtf8("lblDiagnosisTypeAfterFinalForm043"))
        self.gridLayout.addWidget(self.lblDiagnosisTypeAfterFinalForm043, 2, 0, 1, 1)
        self.chkCheckDispanserObservation = QtGui.QCheckBox(eventPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkCheckDispanserObservation.sizePolicy().hasHeightForWidth())
        self.chkCheckDispanserObservation.setSizePolicy(sizePolicy)
        self.chkCheckDispanserObservation.setText(_fromUtf8(""))
        self.chkCheckDispanserObservation.setObjectName(_fromUtf8("chkCheckDispanserObservation"))
        self.gridLayout.addWidget(self.chkCheckDispanserObservation, 5, 1, 1, 1)
        self.chkEventTypeActive = QtGui.QCheckBox(eventPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkEventTypeActive.sizePolicy().hasHeightForWidth())
        self.chkEventTypeActive.setSizePolicy(sizePolicy)
        self.chkEventTypeActive.setText(_fromUtf8(""))
        self.chkEventTypeActive.setObjectName(_fromUtf8("chkEventTypeActive"))
        self.gridLayout.addWidget(self.chkEventTypeActive, 3, 1, 1, 1)
        self.chkSurveillancePlanningDialog = QtGui.QCheckBox(eventPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkSurveillancePlanningDialog.sizePolicy().hasHeightForWidth())
        self.chkSurveillancePlanningDialog.setSizePolicy(sizePolicy)
        self.chkSurveillancePlanningDialog.setText(_fromUtf8(""))
        self.chkSurveillancePlanningDialog.setObjectName(_fromUtf8("chkSurveillancePlanningDialog"))
        self.gridLayout.addWidget(self.chkSurveillancePlanningDialog, 4, 1, 1, 1)
        self.lblEventTypeActive = QtGui.QLabel(eventPage)
        self.lblEventTypeActive.setObjectName(_fromUtf8("lblEventTypeActive"))
        self.gridLayout.addWidget(self.lblEventTypeActive, 3, 0, 1, 1)
        self.chkFillDiagnosticsEventsResults = QtGui.QCheckBox(eventPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFillDiagnosticsEventsResults.sizePolicy().hasHeightForWidth())
        self.chkFillDiagnosticsEventsResults.setSizePolicy(sizePolicy)
        self.chkFillDiagnosticsEventsResults.setText(_fromUtf8(""))
        self.chkFillDiagnosticsEventsResults.setChecked(True)
        self.chkFillDiagnosticsEventsResults.setObjectName(_fromUtf8("chkFillDiagnosticsEventsResults"))
        self.gridLayout.addWidget(self.chkFillDiagnosticsEventsResults, 1, 1, 1, 1)
        self.lblSurveillancePlanningDialog = QtGui.QLabel(eventPage)
        self.lblSurveillancePlanningDialog.setObjectName(_fromUtf8("lblSurveillancePlanningDialog"))
        self.gridLayout.addWidget(self.lblSurveillancePlanningDialog, 4, 0, 1, 1)
        self.chkPlanningParam = QtGui.QCheckBox(eventPage)
        self.chkPlanningParam.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkPlanningParam.setObjectName(_fromUtf8("chkPlanningParam"))
        self.gridLayout.addWidget(self.chkPlanningParam, 6, 0, 1, 1)
        self.lblCheckDispanserObservation = QtGui.QLabel(eventPage)
        self.lblCheckDispanserObservation.setObjectName(_fromUtf8("lblCheckDispanserObservation"))
        self.gridLayout.addWidget(self.lblCheckDispanserObservation, 5, 0, 1, 1)
        self.grbParam = QtGui.QGroupBox(eventPage)
        self.grbParam.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grbParam.sizePolicy().hasHeightForWidth())
        self.grbParam.setSizePolicy(sizePolicy)
        self.grbParam.setTitle(_fromUtf8(""))
        self.grbParam.setObjectName(_fromUtf8("grbParam"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grbParam)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblPlanningBegDate = QtGui.QLabel(self.grbParam)
        self.lblPlanningBegDate.setObjectName(_fromUtf8("lblPlanningBegDate"))
        self.gridLayout_2.addWidget(self.lblPlanningBegDate, 1, 0, 1, 1)
        self.cmbPlanningBegDate = QtGui.QComboBox(self.grbParam)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlanningBegDate.sizePolicy().hasHeightForWidth())
        self.cmbPlanningBegDate.setSizePolicy(sizePolicy)
        self.cmbPlanningBegDate.setObjectName(_fromUtf8("cmbPlanningBegDate"))
        self.cmbPlanningBegDate.addItem(_fromUtf8(""))
        self.cmbPlanningBegDate.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbPlanningBegDate, 1, 1, 1, 1)
        self.edtPlanningFreq = QtGui.QSpinBox(self.grbParam)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPlanningFreq.sizePolicy().hasHeightForWidth())
        self.edtPlanningFreq.setSizePolicy(sizePolicy)
        self.edtPlanningFreq.setMinimum(1)
        self.edtPlanningFreq.setMaximum(36)
        self.edtPlanningFreq.setSingleStep(1)
        self.edtPlanningFreq.setProperty("value", 6)
        self.edtPlanningFreq.setObjectName(_fromUtf8("edtPlanningFreq"))
        self.gridLayout_2.addWidget(self.edtPlanningFreq, 0, 1, 1, 1)
        self.lblPlanningFreq = QtGui.QLabel(self.grbParam)
        self.lblPlanningFreq.setObjectName(_fromUtf8("lblPlanningFreq"))
        self.gridLayout_2.addWidget(self.lblPlanningFreq, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.grbParam, 7, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 2)
        self.lblAverageDuration.setBuddy(self.edtAverageDuration)

        self.retranslateUi(eventPage)
        QtCore.QMetaObject.connectSlotsByName(eventPage)

    def retranslateUi(self, eventPage):
        eventPage.setWindowTitle(_translate("eventPage", "Ввод обращений", None))
        eventPage.setToolTip(_translate("eventPage", "Ввод обращений", None))
        self.lblAverageDuration.setText(_translate("eventPage", "Средняя продолжительность заболевания", None))
        self.cmbDiagnosisTypeAfterFinalForm043.setItemText(0, _translate("eventPage", "Сопутствующий", None))
        self.cmbDiagnosisTypeAfterFinalForm043.setItemText(1, _translate("eventPage", "Основной", None))
        self.lblFillDiagnosticsEventsResults.setText(_translate("eventPage", "Заполнять результаты осмотра и События в форме ввода", None))
        self.lblDiagnosisTypeAfterFinalForm043.setText(_translate("eventPage", "Предпочитаемый тип диагноза в форме ввода 043 после закл", None))
        self.lblEventTypeActive.setText(_translate("eventPage", "Учитывать актуальность типа События", None))
        self.lblSurveillancePlanningDialog.setText(_translate("eventPage", "Включить планирование профилактического наблюдения", None))
        self.chkPlanningParam.setText(_translate("eventPage", "Автоматическое заполнение даты следующей явки на ДН", None))
        self.lblCheckDispanserObservation.setText(_translate("eventPage", "Контроль заполнения ДН в событии", None))
        self.lblPlanningBegDate.setText(_translate("eventPage", "Дата планирования явки на ДН", None))
        self.cmbPlanningBegDate.setItemText(0, _translate("eventPage", "Первый день месяца", None))
        self.cmbPlanningBegDate.setItemText(1, _translate("eventPage", "От текущей даты", None))
        self.lblPlanningFreq.setText(_translate("eventPage", "Частота планирования явок на ДН (мес)", None))

