# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\SVN\Samson\UP_s11\client\preferences\SerialPortScannerPage.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_serialPortScannerPage(object):
    def setupUi(self, serialPortScannerPage):
        serialPortScannerPage.setObjectName(_fromUtf8("serialPortScannerPage"))
        serialPortScannerPage.resize(559, 328)
        self.gridLayout = QtGui.QGridLayout(serialPortScannerPage)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(84, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(84, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 11, 3, 1, 1)
        self.edtScanPromobotAddress = QtGui.QLineEdit(serialPortScannerPage)
        self.edtScanPromobotAddress.setEnabled(False)
        self.edtScanPromobotAddress.setObjectName(_fromUtf8("edtScanPromobotAddress"))
        self.gridLayout.addWidget(self.edtScanPromobotAddress, 11, 1, 1, 2)
        self.lblScanPromobotUrl = QtGui.QLabel(serialPortScannerPage)
        self.lblScanPromobotUrl.setEnabled(False)
        self.lblScanPromobotUrl.setMinimumSize(QtCore.QSize(130, 0))
        self.lblScanPromobotUrl.setObjectName(_fromUtf8("lblScanPromobotUrl"))
        self.gridLayout.addWidget(self.lblScanPromobotUrl, 11, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(84, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 3, 1, 1)
        self.lblScanParity = QtGui.QLabel(serialPortScannerPage)
        self.lblScanParity.setEnabled(False)
        self.lblScanParity.setMinimumSize(QtCore.QSize(130, 0))
        self.lblScanParity.setObjectName(_fromUtf8("lblScanParity"))
        self.gridLayout.addWidget(self.lblScanParity, 3, 0, 1, 1)
        self.cmbScanStopBits = QtGui.QComboBox(serialPortScannerPage)
        self.cmbScanStopBits.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbScanStopBits.sizePolicy().hasHeightForWidth())
        self.cmbScanStopBits.setSizePolicy(sizePolicy)
        self.cmbScanStopBits.setObjectName(_fromUtf8("cmbScanStopBits"))
        self.cmbScanStopBits.addItem(_fromUtf8(""))
        self.cmbScanStopBits.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbScanStopBits, 4, 1, 1, 1)
        self.lblScanStopBits = QtGui.QLabel(serialPortScannerPage)
        self.lblScanStopBits.setEnabled(False)
        self.lblScanStopBits.setMinimumSize(QtCore.QSize(130, 0))
        self.lblScanStopBits.setObjectName(_fromUtf8("lblScanStopBits"))
        self.gridLayout.addWidget(self.lblScanStopBits, 4, 0, 1, 1)
        self.cmbScanBaudrate = QtGui.QComboBox(serialPortScannerPage)
        self.cmbScanBaudrate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbScanBaudrate.sizePolicy().hasHeightForWidth())
        self.cmbScanBaudrate.setSizePolicy(sizePolicy)
        self.cmbScanBaudrate.setObjectName(_fromUtf8("cmbScanBaudrate"))
        self.cmbScanBaudrate.addItem(_fromUtf8(""))
        self.cmbScanBaudrate.addItem(_fromUtf8(""))
        self.cmbScanBaudrate.addItem(_fromUtf8(""))
        self.cmbScanBaudrate.addItem(_fromUtf8(""))
        self.cmbScanBaudrate.addItem(_fromUtf8(""))
        self.cmbScanBaudrate.addItem(_fromUtf8(""))
        self.cmbScanBaudrate.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbScanBaudrate, 2, 1, 1, 1)
        self.chkScanCorrectBackslashes = QtGui.QCheckBox(serialPortScannerPage)
        self.chkScanCorrectBackslashes.setEnabled(False)
        self.chkScanCorrectBackslashes.setObjectName(_fromUtf8("chkScanCorrectBackslashes"))
        self.gridLayout.addWidget(self.chkScanCorrectBackslashes, 6, 1, 1, 3)
        self.chkScanParseReport = QtGui.QCheckBox(serialPortScannerPage)
        self.chkScanParseReport.setEnabled(False)
        self.chkScanParseReport.setObjectName(_fromUtf8("chkScanParseReport"))
        self.gridLayout.addWidget(self.chkScanParseReport, 8, 1, 1, 3)
        self.chkScanPromobotEnable = QtGui.QCheckBox(serialPortScannerPage)
        self.chkScanPromobotEnable.setObjectName(_fromUtf8("chkScanPromobotEnable"))
        self.gridLayout.addWidget(self.chkScanPromobotEnable, 10, 0, 1, 4)
        self.btnScanTest = QtGui.QPushButton(serialPortScannerPage)
        self.btnScanTest.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnScanTest.sizePolicy().hasHeightForWidth())
        self.btnScanTest.setSizePolicy(sizePolicy)
        self.btnScanTest.setObjectName(_fromUtf8("btnScanTest"))
        self.gridLayout.addWidget(self.btnScanTest, 9, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 42, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 13, 0, 1, 1)
        self.lblScanPort = QtGui.QLabel(serialPortScannerPage)
        self.lblScanPort.setEnabled(False)
        self.lblScanPort.setMinimumSize(QtCore.QSize(130, 0))
        self.lblScanPort.setObjectName(_fromUtf8("lblScanPort"))
        self.gridLayout.addWidget(self.lblScanPort, 1, 0, 1, 1)
        self.lblScanBaudrate = QtGui.QLabel(serialPortScannerPage)
        self.lblScanBaudrate.setEnabled(False)
        self.lblScanBaudrate.setMinimumSize(QtCore.QSize(130, 0))
        self.lblScanBaudrate.setObjectName(_fromUtf8("lblScanBaudrate"))
        self.gridLayout.addWidget(self.lblScanBaudrate, 2, 0, 1, 1)
        self.edtScanPort = QtGui.QLineEdit(serialPortScannerPage)
        self.edtScanPort.setEnabled(False)
        self.edtScanPort.setObjectName(_fromUtf8("edtScanPort"))
        self.gridLayout.addWidget(self.edtScanPort, 1, 1, 1, 2)
        self.chkScanEnable = QtGui.QCheckBox(serialPortScannerPage)
        self.chkScanEnable.setObjectName(_fromUtf8("chkScanEnable"))
        self.gridLayout.addWidget(self.chkScanEnable, 0, 0, 1, 4)
        spacerItem4 = QtGui.QSpacerItem(84, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(84, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 3, 1, 1)
        self.cmbScanParity = QtGui.QComboBox(serialPortScannerPage)
        self.cmbScanParity.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbScanParity.sizePolicy().hasHeightForWidth())
        self.cmbScanParity.setSizePolicy(sizePolicy)
        self.cmbScanParity.setObjectName(_fromUtf8("cmbScanParity"))
        self.cmbScanParity.addItem(_fromUtf8(""))
        self.cmbScanParity.addItem(_fromUtf8(""))
        self.cmbScanParity.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbScanParity, 3, 1, 1, 1)
        self.lblScanFlowControl = QtGui.QLabel(serialPortScannerPage)
        self.lblScanFlowControl.setEnabled(False)
        self.lblScanFlowControl.setMinimumSize(QtCore.QSize(130, 0))
        self.lblScanFlowControl.setObjectName(_fromUtf8("lblScanFlowControl"))
        self.gridLayout.addWidget(self.lblScanFlowControl, 5, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(85, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 9, 2, 1, 1)
        self.cmbScanFlowControl = QtGui.QComboBox(serialPortScannerPage)
        self.cmbScanFlowControl.setEnabled(False)
        self.cmbScanFlowControl.setObjectName(_fromUtf8("cmbScanFlowControl"))
        self.cmbScanFlowControl.addItem(_fromUtf8(""))
        self.cmbScanFlowControl.addItem(_fromUtf8(""))
        self.cmbScanFlowControl.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbScanFlowControl, 5, 1, 1, 2)
        self.chkScanConnectionReport = QtGui.QCheckBox(serialPortScannerPage)
        self.chkScanConnectionReport.setEnabled(False)
        self.chkScanConnectionReport.setObjectName(_fromUtf8("chkScanConnectionReport"))
        self.gridLayout.addWidget(self.chkScanConnectionReport, 7, 1, 1, 3)
        self.chkTabletSignEnable = QtGui.QCheckBox(serialPortScannerPage)
        self.chkTabletSignEnable.setObjectName(_fromUtf8("chkTabletSignEnable"))
        self.gridLayout.addWidget(self.chkTabletSignEnable, 12, 0, 1, 3)
        self.lblScanParity.setBuddy(self.cmbScanParity)
        self.lblScanStopBits.setBuddy(self.cmbScanStopBits)
        self.lblScanPort.setBuddy(self.edtScanPort)
        self.lblScanBaudrate.setBuddy(self.cmbScanBaudrate)
        self.lblScanFlowControl.setBuddy(self.cmbScanFlowControl)

        self.retranslateUi(serialPortScannerPage)
        self.cmbScanBaudrate.setCurrentIndex(2)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblScanPort.setEnabled)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblScanBaudrate.setEnabled)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblScanParity.setEnabled)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblScanStopBits.setEnabled)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblScanFlowControl.setEnabled)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtScanPort.setEnabled)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbScanBaudrate.setEnabled)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbScanParity.setEnabled)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbScanStopBits.setEnabled)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbScanFlowControl.setEnabled)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkScanCorrectBackslashes.setEnabled)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkScanConnectionReport.setEnabled)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkScanParseReport.setEnabled)
        QtCore.QObject.connect(self.chkScanEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.btnScanTest.setEnabled)
        QtCore.QObject.connect(self.chkScanPromobotEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtScanPromobotAddress.setEnabled)
        QtCore.QObject.connect(self.chkScanPromobotEnable, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblScanPromobotUrl.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(serialPortScannerPage)
        serialPortScannerPage.setTabOrder(self.chkScanEnable, self.edtScanPort)
        serialPortScannerPage.setTabOrder(self.edtScanPort, self.cmbScanBaudrate)
        serialPortScannerPage.setTabOrder(self.cmbScanBaudrate, self.cmbScanParity)
        serialPortScannerPage.setTabOrder(self.cmbScanParity, self.cmbScanStopBits)
        serialPortScannerPage.setTabOrder(self.cmbScanStopBits, self.cmbScanFlowControl)
        serialPortScannerPage.setTabOrder(self.cmbScanFlowControl, self.chkScanConnectionReport)
        serialPortScannerPage.setTabOrder(self.chkScanConnectionReport, self.chkScanCorrectBackslashes)
        serialPortScannerPage.setTabOrder(self.chkScanCorrectBackslashes, self.chkScanParseReport)
        serialPortScannerPage.setTabOrder(self.chkScanParseReport, self.btnScanTest)

    def retranslateUi(self, serialPortScannerPage):
        serialPortScannerPage.setWindowTitle(_translate("serialPortScannerPage", "Подключение сканера", None))
        self.edtScanPromobotAddress.setToolTip(_translate("serialPortScannerPage", "<html><head/><body><p>для Windows:</p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">com</span><span style=\" font-weight:600; font-style:italic;\">{N}</span></li></ul><p>для linux (обычно):</p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">RS-232:<span style=\" font-weight:600;\">/dev/ttyS</span><span style=\" font-weight:600; font-style:italic;\">{N}</span> ,</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">USB: <span style=\" font-weight:600;\">/dev/ttyUSB</span><span style=\" font-weight:600; font-style:italic;\">{N}</span></li></ul></body></html>", None))
        self.lblScanPromobotUrl.setText(_translate("serialPortScannerPage", "Адрес сканера", None))
        self.lblScanParity.setText(_translate("serialPortScannerPage", "Бит &чётности", None))
        self.cmbScanStopBits.setItemText(0, _translate("serialPortScannerPage", "1", None))
        self.cmbScanStopBits.setItemText(1, _translate("serialPortScannerPage", "2", None))
        self.lblScanStopBits.setText(_translate("serialPortScannerPage", "С&топ-битов", None))
        self.cmbScanBaudrate.setItemText(0, _translate("serialPortScannerPage", "2400", None))
        self.cmbScanBaudrate.setItemText(1, _translate("serialPortScannerPage", "4800", None))
        self.cmbScanBaudrate.setItemText(2, _translate("serialPortScannerPage", "9600", None))
        self.cmbScanBaudrate.setItemText(3, _translate("serialPortScannerPage", "19200", None))
        self.cmbScanBaudrate.setItemText(4, _translate("serialPortScannerPage", "38400", None))
        self.cmbScanBaudrate.setItemText(5, _translate("serialPortScannerPage", "57600", None))
        self.cmbScanBaudrate.setItemText(6, _translate("serialPortScannerPage", "115200", None))
        self.chkScanCorrectBackslashes.setText(_translate("serialPortScannerPage", "Исправлять дублирование \'\\\'", None))
        self.chkScanParseReport.setText(_translate("serialPortScannerPage", "Сообщать о проблемах распознавания", None))
        self.chkScanPromobotEnable.setText(_translate("serialPortScannerPage", "&Включить поддержку сканера Promobot Scanner", None))
        self.btnScanTest.setText(_translate("serialPortScannerPage", "Проверить", None))
        self.lblScanPort.setText(_translate("serialPortScannerPage", "&Порт", None))
        self.lblScanBaudrate.setText(_translate("serialPortScannerPage", "&Скорость, бод", None))
        self.edtScanPort.setToolTip(_translate("serialPortScannerPage", "<html><head/><body><p>для Windows:</p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">com</span><span style=\" font-weight:600; font-style:italic;\">{N}</span></li></ul><p>для linux (обычно):</p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">RS-232:<span style=\" font-weight:600;\">/dev/ttyS</span><span style=\" font-weight:600; font-style:italic;\">{N}</span> ,</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">USB: <span style=\" font-weight:600;\">/dev/ttyUSB</span><span style=\" font-weight:600; font-style:italic;\">{N}</span></li></ul></body></html>", None))
        self.chkScanEnable.setText(_translate("serialPortScannerPage", "&Включить поддержку сканера", None))
        self.cmbScanParity.setItemText(0, _translate("serialPortScannerPage", "None", None))
        self.cmbScanParity.setItemText(1, _translate("serialPortScannerPage", "Odd", None))
        self.cmbScanParity.setItemText(2, _translate("serialPortScannerPage", "Even", None))
        self.lblScanFlowControl.setText(_translate("serialPortScannerPage", "&Управление потоком", None))
        self.cmbScanFlowControl.setItemText(0, _translate("serialPortScannerPage", "Не использовать", None))
        self.cmbScanFlowControl.setItemText(1, _translate("serialPortScannerPage", "Аппаратное", None))
        self.cmbScanFlowControl.setItemText(2, _translate("serialPortScannerPage", "Программное", None))
        self.chkScanConnectionReport.setText(_translate("serialPortScannerPage", "Сообщать о проблемах подключения", None))
        self.chkTabletSignEnable.setText(_translate("serialPortScannerPage", "&Включить отображение кнопки \"Планшет\"", None))

