# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client\RefBooks\Infection\RBInfectionEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RBInfectionEditor(object):
    def setupUi(self, RBInfectionEditor):
        RBInfectionEditor.setObjectName(_fromUtf8("RBInfectionEditor"))
        RBInfectionEditor.resize(562, 521)
        self.gridLayout_2 = QtGui.QGridLayout(RBInfectionEditor)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblCode = QtGui.QLabel(RBInfectionEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout_2.addWidget(self.lblCode, 0, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(RBInfectionEditor)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout_2.addWidget(self.edtCode, 0, 1, 1, 2)
        self.lblName = QtGui.QLabel(RBInfectionEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout_2.addWidget(self.lblName, 1, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(RBInfectionEditor)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout_2.addWidget(self.edtName, 1, 1, 1, 2)
        self.lblRegionalCode = QtGui.QLabel(RBInfectionEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRegionalCode.sizePolicy().hasHeightForWidth())
        self.lblRegionalCode.setSizePolicy(sizePolicy)
        self.lblRegionalCode.setObjectName(_fromUtf8("lblRegionalCode"))
        self.gridLayout_2.addWidget(self.lblRegionalCode, 2, 0, 1, 1)
        self.edtRegionalCode = QtGui.QLineEdit(RBInfectionEditor)
        self.edtRegionalCode.setObjectName(_fromUtf8("edtRegionalCode"))
        self.gridLayout_2.addWidget(self.edtRegionalCode, 2, 1, 1, 2)
        self.lblMinimumTerm = QtGui.QLabel(RBInfectionEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMinimumTerm.sizePolicy().hasHeightForWidth())
        self.lblMinimumTerm.setSizePolicy(sizePolicy)
        self.lblMinimumTerm.setObjectName(_fromUtf8("lblMinimumTerm"))
        self.gridLayout_2.addWidget(self.lblMinimumTerm, 3, 0, 1, 1)
        self.cmbMinimumTermUnit = QtGui.QComboBox(RBInfectionEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMinimumTermUnit.sizePolicy().hasHeightForWidth())
        self.cmbMinimumTermUnit.setSizePolicy(sizePolicy)
        self.cmbMinimumTermUnit.setObjectName(_fromUtf8("cmbMinimumTermUnit"))
        self.cmbMinimumTermUnit.addItem(_fromUtf8(""))
        self.cmbMinimumTermUnit.setItemText(0, _fromUtf8(""))
        self.cmbMinimumTermUnit.addItem(_fromUtf8(""))
        self.cmbMinimumTermUnit.addItem(_fromUtf8(""))
        self.cmbMinimumTermUnit.addItem(_fromUtf8(""))
        self.cmbMinimumTermUnit.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbMinimumTermUnit, 3, 1, 1, 1)
        self.edtMinimumTermCount = QtGui.QLineEdit(RBInfectionEditor)
        self.edtMinimumTermCount.setInputMask(_fromUtf8(""))
        self.edtMinimumTermCount.setMaxLength(32767)
        self.edtMinimumTermCount.setObjectName(_fromUtf8("edtMinimumTermCount"))
        self.gridLayout_2.addWidget(self.edtMinimumTermCount, 3, 2, 1, 1)
        self.chkAvailable = QtGui.QCheckBox(RBInfectionEditor)
        self.chkAvailable.setObjectName(_fromUtf8("chkAvailable"))
        self.gridLayout_2.addWidget(self.chkAvailable, 4, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(RBInfectionEditor)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabInfectionVaccines = QtGui.QWidget()
        self.tabInfectionVaccines.setObjectName(_fromUtf8("tabInfectionVaccines"))
        self.gridLayout = QtGui.QGridLayout(self.tabInfectionVaccines)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.tabInfectionVaccines)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tblInfectionVaccines = CInDocTableView(self.splitter)
        self.tblInfectionVaccines.setObjectName(_fromUtf8("tblInfectionVaccines"))
        self.tblInfectionMinimumTerms = CInDocTableView(self.splitter)
        self.tblInfectionMinimumTerms.setObjectName(_fromUtf8("tblInfectionMinimumTerms"))
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabInfectionVaccines, _fromUtf8(""))
        self.tabIdentification = QtGui.QWidget()
        self.tabIdentification.setObjectName(_fromUtf8("tabIdentification"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabIdentification)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblInfectionIdentification = CInDocTableView(self.tabIdentification)
        self.tblInfectionIdentification.setObjectName(_fromUtf8("tblInfectionIdentification"))
        self.gridLayout_3.addWidget(self.tblInfectionIdentification, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIdentification, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 5, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(RBInfectionEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 6, 0, 1, 3)
        self.lblCode.setBuddy(self.edtCode)
        self.lblName.setBuddy(self.edtName)
        self.lblRegionalCode.setBuddy(self.edtRegionalCode)
        self.lblMinimumTerm.setBuddy(self.cmbMinimumTermUnit)

        self.retranslateUi(RBInfectionEditor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RBInfectionEditor.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RBInfectionEditor.reject)
        QtCore.QMetaObject.connectSlotsByName(RBInfectionEditor)
        RBInfectionEditor.setTabOrder(self.edtCode, self.edtName)
        RBInfectionEditor.setTabOrder(self.edtName, self.edtRegionalCode)
        RBInfectionEditor.setTabOrder(self.edtRegionalCode, self.cmbMinimumTermUnit)
        RBInfectionEditor.setTabOrder(self.cmbMinimumTermUnit, self.edtMinimumTermCount)
        RBInfectionEditor.setTabOrder(self.edtMinimumTermCount, self.buttonBox)

    def retranslateUi(self, RBInfectionEditor):
        RBInfectionEditor.setWindowTitle(_translate("RBInfectionEditor", "Dialog", None))
        self.lblCode.setText(_translate("RBInfectionEditor", "&Код", None))
        self.lblName.setText(_translate("RBInfectionEditor", "&Наименование", None))
        self.lblRegionalCode.setText(_translate("RBInfectionEditor", "&Региональный код", None))
        self.lblMinimumTerm.setText(_translate("RBInfectionEditor", "&Минимальный срок", None))
        self.cmbMinimumTermUnit.setItemText(1, _translate("RBInfectionEditor", "Д", None))
        self.cmbMinimumTermUnit.setItemText(2, _translate("RBInfectionEditor", "Н", None))
        self.cmbMinimumTermUnit.setItemText(3, _translate("RBInfectionEditor", "М", None))
        self.cmbMinimumTermUnit.setItemText(4, _translate("RBInfectionEditor", "Г", None))
        self.chkAvailable.setText(_translate("RBInfectionEditor", "В наличии", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInfectionVaccines), _translate("RBInfectionEditor", "Вакцины и инфекции", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIdentification), _translate("RBInfectionEditor", "Идентификация", None))

from library.InDocTable import CInDocTableView
