# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\proj\Samson\UP_s11\client_test\F110\F110.ui'
#
# Created: Thu May 23 16:59:15 2024
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1065, 980)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout_6 = QtGui.QGridLayout(Dialog)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_6.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.statusBar = QtGui.QStatusBar(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.horizontalLayout_2.addWidget(self.statusBar)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lblValueExternalId = QtGui.QLabel(Dialog)
        self.lblValueExternalId.setText(_fromUtf8(""))
        self.lblValueExternalId.setObjectName(_fromUtf8("lblValueExternalId"))
        self.horizontalLayout_2.addWidget(self.lblValueExternalId)
        self.lblValueMesCode = QtGui.QLabel(Dialog)
        self.lblValueMesCode.setText(_fromUtf8(""))
        self.lblValueMesCode.setObjectName(_fromUtf8("lblValueMesCode"))
        self.horizontalLayout_2.addWidget(self.lblValueMesCode)
        self.horizontalLayout_2.setStretch(0, 1)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.txtClientInfoBrowser = CTextBrowser(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.txtClientInfoBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.scrollArea = QtGui.QScrollArea(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.tabWidget = QtGui.QTabWidget()
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1055, 812))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabToken = QtGui.QWidget()
        self.tabToken.setObjectName(_fromUtf8("tabToken"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabToken)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frameBaseAndDiagnosises = QtGui.QFrame(self.tabToken)
        self.frameBaseAndDiagnosises.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameBaseAndDiagnosises.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBaseAndDiagnosises.setObjectName(_fromUtf8("frameBaseAndDiagnosises"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frameBaseAndDiagnosises)
        self.gridLayout_10.setSpacing(2)
        self.gridLayout_10.setMargin(2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.splitter = QtGui.QSplitter(self.frameBaseAndDiagnosises)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.grplFinalDiagnostics = QtGui.QGroupBox(self.splitter)
        self.grplFinalDiagnostics.setObjectName(_fromUtf8("grplFinalDiagnostics"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grplFinalDiagnostics)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setMargin(1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblFinalDiagnostics = CInDocTableView(self.grplFinalDiagnostics)
        self.tblFinalDiagnostics.setObjectName(_fromUtf8("tblFinalDiagnostics"))
        self.gridLayout_3.addWidget(self.tblFinalDiagnostics, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setSpacing(1)
        self.gridLayout_5.setMargin(1)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblPersonnel = CInDocTableView(self.groupBox)
        self.tblPersonnel.setObjectName(_fromUtf8("tblPersonnel"))
        self.gridLayout_5.addWidget(self.tblPersonnel, 0, 0, 1, 1)
        self.grpRenunOfHospital = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpRenunOfHospital.sizePolicy().hasHeightForWidth())
        self.grpRenunOfHospital.setSizePolicy(sizePolicy)
        self.grpRenunOfHospital.setCheckable(True)
        self.grpRenunOfHospital.setChecked(False)
        self.grpRenunOfHospital.setObjectName(_fromUtf8("grpRenunOfHospital"))
        self.gridLayout_4 = QtGui.QGridLayout(self.grpRenunOfHospital)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setMargin(1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblFaceRenunOfHospital = QtGui.QLabel(self.grpRenunOfHospital)
        self.lblFaceRenunOfHospital.setEnabled(False)
        self.lblFaceRenunOfHospital.setObjectName(_fromUtf8("lblFaceRenunOfHospital"))
        self.gridLayout_4.addWidget(self.lblFaceRenunOfHospital, 0, 0, 1, 1)
        self.edtFaceRenunOfHospital = QtGui.QLineEdit(self.grpRenunOfHospital)
        self.edtFaceRenunOfHospital.setEnabled(False)
        self.edtFaceRenunOfHospital.setObjectName(_fromUtf8("edtFaceRenunOfHospital"))
        self.gridLayout_4.addWidget(self.edtFaceRenunOfHospital, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.splitter, 0, 1, 1, 1)
        self.grpBase = QtGui.QGroupBox(self.frameBaseAndDiagnosises)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpBase.sizePolicy().hasHeightForWidth())
        self.grpBase.setSizePolicy(sizePolicy)
        self.grpBase.setObjectName(_fromUtf8("grpBase"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpBase)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cmbOrderEvent = CROComboBox(self.grpBase)
        self.cmbOrderEvent.setObjectName(_fromUtf8("cmbOrderEvent"))
        self.cmbOrderEvent.addItem(_fromUtf8(""))
        self.cmbOrderEvent.addItem(_fromUtf8(""))
        self.cmbOrderEvent.addItem(_fromUtf8(""))
        self.cmbOrderEvent.addItem(_fromUtf8(""))
        self.cmbOrderEvent.addItem(_fromUtf8(""))
        self.cmbOrderEvent.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbOrderEvent, 21, 1, 1, 4)
        self.lblVisitsDurationValue = QtGui.QLabel(self.grpBase)
        self.lblVisitsDurationValue.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.lblVisitsDurationValue.setFont(font)
        self.lblVisitsDurationValue.setMouseTracking(False)
        self.lblVisitsDurationValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblVisitsDurationValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblVisitsDurationValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblVisitsDurationValue.setObjectName(_fromUtf8("lblVisitsDurationValue"))
        self.gridLayout_2.addWidget(self.lblVisitsDurationValue, 10, 4, 1, 1)
        self.lblCauseCall = QtGui.QLabel(self.grpBase)
        self.lblCauseCall.setObjectName(_fromUtf8("lblCauseCall"))
        self.gridLayout_2.addWidget(self.lblCauseCall, 3, 0, 1, 1)
        self.cmbCauseCall = CRBComboBox(self.grpBase)
        self.cmbCauseCall.setObjectName(_fromUtf8("cmbCauseCall"))
        self.cmbCauseCall.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbCauseCall, 3, 1, 1, 4)
        self.lblWhoCallOnPhone = QtGui.QLabel(self.grpBase)
        self.lblWhoCallOnPhone.setObjectName(_fromUtf8("lblWhoCallOnPhone"))
        self.gridLayout_2.addWidget(self.lblWhoCallOnPhone, 4, 0, 1, 1)
        self.edtWhoCallOnPhone = QtGui.QLineEdit(self.grpBase)
        self.edtWhoCallOnPhone.setObjectName(_fromUtf8("edtWhoCallOnPhone"))
        self.gridLayout_2.addWidget(self.edtWhoCallOnPhone, 4, 1, 1, 4)
        self.edtNumberCardCall = QtGui.QLineEdit(self.grpBase)
        self.edtNumberCardCall.setObjectName(_fromUtf8("edtNumberCardCall"))
        self.gridLayout_2.addWidget(self.edtNumberCardCall, 0, 1, 1, 4)
        self.edtNextTime = QtGui.QTimeEdit(self.grpBase)
        self.edtNextTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtNextTime.setObjectName(_fromUtf8("edtNextTime"))
        self.gridLayout_2.addWidget(self.edtNextTime, 27, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 28, 0, 1, 2)
        self.lblTimeToFinishServiceDate = QtGui.QLabel(self.grpBase)
        self.lblTimeToFinishServiceDate.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTimeToFinishServiceDate.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblTimeToFinishServiceDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTimeToFinishServiceDate.setObjectName(_fromUtf8("lblTimeToFinishServiceDate"))
        self.gridLayout_2.addWidget(self.lblTimeToFinishServiceDate, 14, 4, 1, 1)
        self.lblPassDate = QtGui.QLabel(self.grpBase)
        self.lblPassDate.setObjectName(_fromUtf8("lblPassDate"))
        self.gridLayout_2.addWidget(self.lblPassDate, 11, 0, 1, 1)
        self.edtEntrance = QtGui.QLineEdit(self.grpBase)
        self.edtEntrance.setObjectName(_fromUtf8("edtEntrance"))
        self.gridLayout_2.addWidget(self.edtEntrance, 7, 1, 1, 4)
        self.cmbNumberBrigade = CRBComboBox(self.grpBase)
        self.cmbNumberBrigade.setObjectName(_fromUtf8("cmbNumberBrigade"))
        self.cmbNumberBrigade.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbNumberBrigade, 2, 1, 1, 4)
        self.cmbContract = CContractComboBox(self.grpBase)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.cmbContract.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbContract, 1, 0, 1, 5)
        self.frmBegDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmBegDateTime.sizePolicy().hasHeightForWidth())
        self.frmBegDateTime.setSizePolicy(sizePolicy)
        self.frmBegDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmBegDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmBegDateTime.setLineWidth(0)
        self.frmBegDateTime.setObjectName(_fromUtf8("frmBegDateTime"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frmBegDateTime)
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.edtBegDate = CDateEdit(self.frmBegDateTime)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout_8.addWidget(self.edtBegDate)
        self.edtBegTime = QtGui.QTimeEdit(self.frmBegDateTime)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.horizontalLayout_8.addWidget(self.edtBegTime)
        self.gridLayout_2.addWidget(self.frmBegDateTime, 10, 1, 1, 3)
        self.lblNumberCardCall = QtGui.QLabel(self.grpBase)
        self.lblNumberCardCall.setObjectName(_fromUtf8("lblNumberCardCall"))
        self.gridLayout_2.addWidget(self.lblNumberCardCall, 0, 0, 1, 1)
        self.lblStorey = QtGui.QLabel(self.grpBase)
        self.lblStorey.setObjectName(_fromUtf8("lblStorey"))
        self.gridLayout_2.addWidget(self.lblStorey, 6, 0, 1, 1)
        self.frmPassDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmPassDateTime.sizePolicy().hasHeightForWidth())
        self.frmPassDateTime.setSizePolicy(sizePolicy)
        self.frmPassDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmPassDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmPassDateTime.setLineWidth(0)
        self.frmPassDateTime.setObjectName(_fromUtf8("frmPassDateTime"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frmPassDateTime)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.edtPassDate = CDateEdit(self.frmPassDateTime)
        self.edtPassDate.setCalendarPopup(True)
        self.edtPassDate.setObjectName(_fromUtf8("edtPassDate"))
        self.horizontalLayout_7.addWidget(self.edtPassDate)
        self.edtPassTime = QtGui.QTimeEdit(self.frmPassDateTime)
        self.edtPassTime.setObjectName(_fromUtf8("edtPassTime"))
        self.horizontalLayout_7.addWidget(self.edtPassTime)
        self.gridLayout_2.addWidget(self.frmPassDateTime, 11, 1, 1, 3)
        self.lblTimeToPassDate = QtGui.QLabel(self.grpBase)
        self.lblTimeToPassDate.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTimeToPassDate.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblTimeToPassDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTimeToPassDate.setObjectName(_fromUtf8("lblTimeToPassDate"))
        self.gridLayout_2.addWidget(self.lblTimeToPassDate, 11, 4, 1, 1)
        self.lblDepartureDate = QtGui.QLabel(self.grpBase)
        self.lblDepartureDate.setObjectName(_fromUtf8("lblDepartureDate"))
        self.gridLayout_2.addWidget(self.lblDepartureDate, 12, 0, 1, 1)
        self.lblNumberBrigade = QtGui.QLabel(self.grpBase)
        self.lblNumberBrigade.setObjectName(_fromUtf8("lblNumberBrigade"))
        self.gridLayout_2.addWidget(self.lblNumberBrigade, 2, 0, 1, 1)
        self.lblNumberPhone = QtGui.QLabel(self.grpBase)
        self.lblNumberPhone.setObjectName(_fromUtf8("lblNumberPhone"))
        self.gridLayout_2.addWidget(self.lblNumberPhone, 5, 0, 1, 1)
        self.edtNumberPhone = QtGui.QLineEdit(self.grpBase)
        self.edtNumberPhone.setObjectName(_fromUtf8("edtNumberPhone"))
        self.gridLayout_2.addWidget(self.edtNumberPhone, 5, 1, 1, 4)
        self.lblBegDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout_2.addWidget(self.lblBegDate, 10, 0, 1, 1)
        self.frmDepartureDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmDepartureDateTime.sizePolicy().hasHeightForWidth())
        self.frmDepartureDateTime.setSizePolicy(sizePolicy)
        self.frmDepartureDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmDepartureDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmDepartureDateTime.setLineWidth(0)
        self.frmDepartureDateTime.setObjectName(_fromUtf8("frmDepartureDateTime"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frmDepartureDateTime)
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.edtDepartureDate = CDateEdit(self.frmDepartureDateTime)
        self.edtDepartureDate.setCalendarPopup(True)
        self.edtDepartureDate.setObjectName(_fromUtf8("edtDepartureDate"))
        self.horizontalLayout_9.addWidget(self.edtDepartureDate)
        self.edtDepartureTime = QtGui.QTimeEdit(self.frmDepartureDateTime)
        self.edtDepartureTime.setObjectName(_fromUtf8("edtDepartureTime"))
        self.horizontalLayout_9.addWidget(self.edtDepartureTime)
        self.gridLayout_2.addWidget(self.frmDepartureDateTime, 12, 1, 1, 3)
        self.lblTimeToDepartureDate = QtGui.QLabel(self.grpBase)
        self.lblTimeToDepartureDate.setStatusTip(_fromUtf8(""))
        self.lblTimeToDepartureDate.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTimeToDepartureDate.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblTimeToDepartureDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTimeToDepartureDate.setObjectName(_fromUtf8("lblTimeToDepartureDate"))
        self.gridLayout_2.addWidget(self.lblTimeToDepartureDate, 12, 4, 1, 1)
        self.lblArrivalDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblArrivalDate.sizePolicy().hasHeightForWidth())
        self.lblArrivalDate.setSizePolicy(sizePolicy)
        self.lblArrivalDate.setObjectName(_fromUtf8("lblArrivalDate"))
        self.gridLayout_2.addWidget(self.lblArrivalDate, 13, 0, 1, 1)
        self.frmArrivalDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmArrivalDateTime.sizePolicy().hasHeightForWidth())
        self.frmArrivalDateTime.setSizePolicy(sizePolicy)
        self.frmArrivalDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmArrivalDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmArrivalDateTime.setLineWidth(0)
        self.frmArrivalDateTime.setObjectName(_fromUtf8("frmArrivalDateTime"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frmArrivalDateTime)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.edtArrivalDate = CDateEdit(self.frmArrivalDateTime)
        self.edtArrivalDate.setCalendarPopup(True)
        self.edtArrivalDate.setObjectName(_fromUtf8("edtArrivalDate"))
        self.horizontalLayout_6.addWidget(self.edtArrivalDate)
        self.edtArrivalTime = QtGui.QTimeEdit(self.frmArrivalDateTime)
        self.edtArrivalTime.setObjectName(_fromUtf8("edtArrivalTime"))
        self.horizontalLayout_6.addWidget(self.edtArrivalTime)
        self.gridLayout_2.addWidget(self.frmArrivalDateTime, 13, 1, 1, 3)
        self.lblTimeToArrivalDate = QtGui.QLabel(self.grpBase)
        self.lblTimeToArrivalDate.setWhatsThis(_fromUtf8(""))
        self.lblTimeToArrivalDate.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTimeToArrivalDate.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblTimeToArrivalDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTimeToArrivalDate.setObjectName(_fromUtf8("lblTimeToArrivalDate"))
        self.gridLayout_2.addWidget(self.lblTimeToArrivalDate, 13, 4, 1, 1)
        self.lblFinishServiceDate = QtGui.QLabel(self.grpBase)
        self.lblFinishServiceDate.setObjectName(_fromUtf8("lblFinishServiceDate"))
        self.gridLayout_2.addWidget(self.lblFinishServiceDate, 14, 0, 1, 1)
        self.frmFinishServiceDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmFinishServiceDateTime.sizePolicy().hasHeightForWidth())
        self.frmFinishServiceDateTime.setSizePolicy(sizePolicy)
        self.frmFinishServiceDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmFinishServiceDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmFinishServiceDateTime.setLineWidth(0)
        self.frmFinishServiceDateTime.setObjectName(_fromUtf8("frmFinishServiceDateTime"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frmFinishServiceDateTime)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.edtFinishServiceDate = CDateEdit(self.frmFinishServiceDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFinishServiceDate.sizePolicy().hasHeightForWidth())
        self.edtFinishServiceDate.setSizePolicy(sizePolicy)
        self.edtFinishServiceDate.setCalendarPopup(True)
        self.edtFinishServiceDate.setObjectName(_fromUtf8("edtFinishServiceDate"))
        self.horizontalLayout_4.addWidget(self.edtFinishServiceDate)
        self.edtFinishServiceTime = QtGui.QTimeEdit(self.frmFinishServiceDateTime)
        self.edtFinishServiceTime.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.edtFinishServiceTime.setObjectName(_fromUtf8("edtFinishServiceTime"))
        self.horizontalLayout_4.addWidget(self.edtFinishServiceTime)
        self.gridLayout_2.addWidget(self.frmFinishServiceDateTime, 14, 1, 1, 3)
        self.lblEndDateDate = QtGui.QLabel(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDateDate.sizePolicy().hasHeightForWidth())
        self.lblEndDateDate.setSizePolicy(sizePolicy)
        self.lblEndDateDate.setObjectName(_fromUtf8("lblEndDateDate"))
        self.gridLayout_2.addWidget(self.lblEndDateDate, 15, 0, 1, 1)
        self.frmEndDateTime = QtGui.QFrame(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmEndDateTime.setSizePolicy(sizePolicy)
        self.frmEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmEndDateTime.setLineWidth(0)
        self.frmEndDateTime.setObjectName(_fromUtf8("frmEndDateTime"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frmEndDateTime)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.edtEndDate = CDateEdit(self.frmEndDateTime)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout_5.addWidget(self.edtEndDate)
        self.edtEndTime = QtGui.QTimeEdit(self.frmEndDateTime)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.horizontalLayout_5.addWidget(self.edtEndTime)
        self.gridLayout_2.addWidget(self.frmEndDateTime, 15, 1, 1, 3)
        self.lblAdditional = QtGui.QLabel(self.grpBase)
        self.lblAdditional.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblAdditional.setObjectName(_fromUtf8("lblAdditional"))
        self.gridLayout_2.addWidget(self.lblAdditional, 9, 0, 1, 1)
        self.lblTimeToEndDate = QtGui.QLabel(self.grpBase)
        self.lblTimeToEndDate.setMouseTracking(False)
        self.lblTimeToEndDate.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblTimeToEndDate.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblTimeToEndDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTimeToEndDate.setObjectName(_fromUtf8("lblTimeToEndDate"))
        self.gridLayout_2.addWidget(self.lblTimeToEndDate, 15, 4, 1, 1)
        self.lblPerson = QtGui.QLabel(self.grpBase)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout_2.addWidget(self.lblPerson, 16, 0, 1, 1)
        self.cmbPerson = CPersonComboBoxEx(self.grpBase)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbPerson, 16, 1, 1, 4)
        self.lblDispatcher = QtGui.QLabel(self.grpBase)
        self.lblDispatcher.setObjectName(_fromUtf8("lblDispatcher"))
        self.gridLayout_2.addWidget(self.lblDispatcher, 17, 0, 1, 1)
        self.cmbDispatcher = CPersonComboBoxEx(self.grpBase)
        self.cmbDispatcher.setObjectName(_fromUtf8("cmbDispatcher"))
        self.cmbDispatcher.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbDispatcher, 17, 1, 1, 4)
        self.lblOrder = QtGui.QLabel(self.grpBase)
        self.lblOrder.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblOrder.setObjectName(_fromUtf8("lblOrder"))
        self.gridLayout_2.addWidget(self.lblOrder, 19, 0, 1, 1)
        self.cmbOrder = CROComboBox(self.grpBase)
        self.cmbOrder.setObjectName(_fromUtf8("cmbOrder"))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.cmbOrder.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbOrder, 19, 1, 1, 4)
        self.lblResult = QtGui.QLabel(self.grpBase)
        self.lblResult.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblResult.setObjectName(_fromUtf8("lblResult"))
        self.gridLayout_2.addWidget(self.lblResult, 20, 0, 1, 1)
        self.cmbResult = CRBComboBox(self.grpBase)
        self.cmbResult.setObjectName(_fromUtf8("cmbResult"))
        self.cmbResult.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbResult, 20, 1, 1, 4)
        self.lblTypeAsset = QtGui.QLabel(self.grpBase)
        self.lblTypeAsset.setObjectName(_fromUtf8("lblTypeAsset"))
        self.gridLayout_2.addWidget(self.lblTypeAsset, 25, 0, 1, 3)
        self.cmbTypeAsset = CRBComboBox(self.grpBase)
        self.cmbTypeAsset.setObjectName(_fromUtf8("cmbTypeAsset"))
        self.cmbTypeAsset.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbTypeAsset, 27, 0, 1, 3)
        self.edtNextDate = CDateEdit(self.grpBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtNextDate.sizePolicy().hasHeightForWidth())
        self.edtNextDate.setSizePolicy(sizePolicy)
        self.edtNextDate.setCalendarPopup(True)
        self.edtNextDate.setObjectName(_fromUtf8("edtNextDate"))
        self.gridLayout_2.addWidget(self.edtNextDate, 27, 3, 1, 1)
        self.lblOrderEvent = QtGui.QLabel(self.grpBase)
        self.lblOrderEvent.setObjectName(_fromUtf8("lblOrderEvent"))
        self.gridLayout_2.addWidget(self.lblOrderEvent, 21, 0, 1, 1)
        self.edtStorey = QtGui.QLineEdit(self.grpBase)
        self.edtStorey.setObjectName(_fromUtf8("edtStorey"))
        self.gridLayout_2.addWidget(self.edtStorey, 6, 1, 1, 4)
        self.edtAdditional = QtGui.QTextEdit(self.grpBase)
        self.edtAdditional.setObjectName(_fromUtf8("edtAdditional"))
        self.gridLayout_2.addWidget(self.edtAdditional, 9, 1, 1, 4)
        self.lblEntrance = QtGui.QLabel(self.grpBase)
        self.lblEntrance.setObjectName(_fromUtf8("lblEntrance"))
        self.gridLayout_2.addWidget(self.lblEntrance, 7, 0, 1, 1)
        self.lblGuidePerson = QtGui.QLabel(self.grpBase)
        self.lblGuidePerson.setObjectName(_fromUtf8("lblGuidePerson"))
        self.gridLayout_2.addWidget(self.lblGuidePerson, 18, 0, 1, 1)
        self.cmbGuidePerson = CPersonComboBoxEx(self.grpBase)
        self.cmbGuidePerson.setObjectName(_fromUtf8("cmbGuidePerson"))
        self.cmbGuidePerson.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbGuidePerson, 18, 1, 1, 4)
        self.lblNumberEpidemic = QtGui.QLabel(self.grpBase)
        self.lblNumberEpidemic.setObjectName(_fromUtf8("lblNumberEpidemic"))
        self.gridLayout_2.addWidget(self.lblNumberEpidemic, 22, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtNumberEpidemic = QtGui.QLineEdit(self.grpBase)
        self.edtNumberEpidemic.setObjectName(_fromUtf8("edtNumberEpidemic"))
        self.horizontalLayout.addWidget(self.edtNumberEpidemic)
        self.lblOrderNumber = QtGui.QLabel(self.grpBase)
        self.lblOrderNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOrderNumber.setObjectName(_fromUtf8("lblOrderNumber"))
        self.horizontalLayout.addWidget(self.lblOrderNumber)
        self.edtOrderNumber = QtGui.QLineEdit(self.grpBase)
        self.edtOrderNumber.setObjectName(_fromUtf8("edtOrderNumber"))
        self.horizontalLayout.addWidget(self.edtOrderNumber)
        self.gridLayout_2.addLayout(self.horizontalLayout, 22, 1, 1, 4)
        self.lblOrgStructure = QtGui.QLabel(self.grpBase)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout_2.addWidget(self.lblOrgStructure, 8, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(self.grpBase)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout_2.addWidget(self.cmbOrgStructure, 8, 1, 1, 4)
        self.gridLayout_10.addWidget(self.grpBase, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frameBaseAndDiagnosises)
        self.grpActions = QtGui.QGroupBox(self.tabToken)
        self.grpActions.setObjectName(_fromUtf8("grpActions"))
        self.gridLayout_7 = QtGui.QGridLayout(self.grpActions)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setMargin(1)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lblPlaceReceptionCall = QtGui.QLabel(self.grpActions)
        self.lblPlaceReceptionCall.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPlaceReceptionCall.setObjectName(_fromUtf8("lblPlaceReceptionCall"))
        self.gridLayout_7.addWidget(self.lblPlaceReceptionCall, 0, 0, 1, 1)
        self.cmbPlaceReceptionCall = CRBComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlaceReceptionCall.sizePolicy().hasHeightForWidth())
        self.cmbPlaceReceptionCall.setSizePolicy(sizePolicy)
        self.cmbPlaceReceptionCall.setObjectName(_fromUtf8("cmbPlaceReceptionCall"))
        self.cmbPlaceReceptionCall.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbPlaceReceptionCall, 0, 1, 1, 1)
        self.lblDisease = QtGui.QLabel(self.grpActions)
        self.lblDisease.setObjectName(_fromUtf8("lblDisease"))
        self.gridLayout_7.addWidget(self.lblDisease, 0, 2, 1, 1)
        self.chkDisease = QtGui.QCheckBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDisease.sizePolicy().hasHeightForWidth())
        self.chkDisease.setSizePolicy(sizePolicy)
        self.chkDisease.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkDisease.setText(_fromUtf8(""))
        self.chkDisease.setChecked(True)
        self.chkDisease.setObjectName(_fromUtf8("chkDisease"))
        self.gridLayout_7.addWidget(self.chkDisease, 0, 3, 1, 1)
        self.lblReceivedCall = QtGui.QLabel(self.grpActions)
        self.lblReceivedCall.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblReceivedCall.setObjectName(_fromUtf8("lblReceivedCall"))
        self.gridLayout_7.addWidget(self.lblReceivedCall, 1, 0, 1, 1)
        self.cmbReceivedCall = CRBComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReceivedCall.sizePolicy().hasHeightForWidth())
        self.cmbReceivedCall.setSizePolicy(sizePolicy)
        self.cmbReceivedCall.setObjectName(_fromUtf8("cmbReceivedCall"))
        self.cmbReceivedCall.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbReceivedCall, 1, 1, 1, 1)
        self.lblBirth = QtGui.QLabel(self.grpActions)
        self.lblBirth.setObjectName(_fromUtf8("lblBirth"))
        self.gridLayout_7.addWidget(self.lblBirth, 1, 2, 1, 1)
        self.chkBirth = QtGui.QCheckBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkBirth.sizePolicy().hasHeightForWidth())
        self.chkBirth.setSizePolicy(sizePolicy)
        self.chkBirth.setText(_fromUtf8(""))
        self.chkBirth.setObjectName(_fromUtf8("chkBirth"))
        self.gridLayout_7.addWidget(self.chkBirth, 1, 3, 1, 1)
        self.lblReasondDelays = QtGui.QLabel(self.grpActions)
        self.lblReasondDelays.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblReasondDelays.setObjectName(_fromUtf8("lblReasondDelays"))
        self.gridLayout_7.addWidget(self.lblReasondDelays, 3, 0, 1, 1)
        self.cmbReasondDelays = CRBComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReasondDelays.sizePolicy().hasHeightForWidth())
        self.cmbReasondDelays.setSizePolicy(sizePolicy)
        self.cmbReasondDelays.setObjectName(_fromUtf8("cmbReasondDelays"))
        self.cmbReasondDelays.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbReasondDelays, 3, 1, 1, 1)
        self.lblResultCircumstanceCall = QtGui.QLabel(self.grpActions)
        self.lblResultCircumstanceCall.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblResultCircumstanceCall.setObjectName(_fromUtf8("lblResultCircumstanceCall"))
        self.gridLayout_7.addWidget(self.lblResultCircumstanceCall, 4, 0, 1, 1)
        self.cmbResultCircumstanceCall = CRBComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResultCircumstanceCall.sizePolicy().hasHeightForWidth())
        self.cmbResultCircumstanceCall.setSizePolicy(sizePolicy)
        self.cmbResultCircumstanceCall.setObjectName(_fromUtf8("cmbResultCircumstanceCall"))
        self.cmbResultCircumstanceCall.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbResultCircumstanceCall, 4, 1, 1, 1)
        self.lblAddressCall = QtGui.QLabel(self.grpActions)
        self.lblAddressCall.setObjectName(_fromUtf8("lblAddressCall"))
        self.gridLayout_7.addWidget(self.lblAddressCall, 6, 0, 1, 1)
        self.cmbLocStreet = CStreetComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbLocStreet.sizePolicy().hasHeightForWidth())
        self.cmbLocStreet.setSizePolicy(sizePolicy)
        self.cmbLocStreet.setObjectName(_fromUtf8("cmbLocStreet"))
        self.cmbLocStreet.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbLocStreet, 6, 4, 1, 2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(4)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lblHouse = QtGui.QLabel(self.grpActions)
        self.lblHouse.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblHouse.setObjectName(_fromUtf8("lblHouse"))
        self.horizontalLayout_10.addWidget(self.lblHouse)
        self.edtLocHouse = QtGui.QLineEdit(self.grpActions)
        self.edtLocHouse.setMaxLength(10)
        self.edtLocHouse.setObjectName(_fromUtf8("edtLocHouse"))
        self.horizontalLayout_10.addWidget(self.edtLocHouse)
        self.lblBuilding = QtGui.QLabel(self.grpActions)
        self.lblBuilding.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblBuilding.setObjectName(_fromUtf8("lblBuilding"))
        self.horizontalLayout_10.addWidget(self.lblBuilding)
        self.edtLocCorpus = QtGui.QLineEdit(self.grpActions)
        self.edtLocCorpus.setMaxLength(10)
        self.edtLocCorpus.setObjectName(_fromUtf8("edtLocCorpus"))
        self.horizontalLayout_10.addWidget(self.edtLocCorpus)
        self.lblFlat = QtGui.QLabel(self.grpActions)
        self.lblFlat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFlat.setObjectName(_fromUtf8("lblFlat"))
        self.horizontalLayout_10.addWidget(self.lblFlat)
        self.edtLocFlat = QtGui.QLineEdit(self.grpActions)
        self.edtLocFlat.setMaxLength(10)
        self.edtLocFlat.setObjectName(_fromUtf8("edtLocFlat"))
        self.horizontalLayout_10.addWidget(self.edtLocFlat)
        self.btnLocHouseList = QtGui.QToolButton(self.grpActions)
        self.btnLocHouseList.setObjectName(_fromUtf8("btnLocHouseList"))
        self.horizontalLayout_10.addWidget(self.btnLocHouseList)
        self.gridLayout_7.addLayout(self.horizontalLayout_10, 6, 6, 1, 3)
        self.lblPregnancyFailure = QtGui.QLabel(self.grpActions)
        self.lblPregnancyFailure.setObjectName(_fromUtf8("lblPregnancyFailure"))
        self.gridLayout_7.addWidget(self.lblPregnancyFailure, 4, 2, 1, 1)
        self.chkPregnancyFailure = QtGui.QCheckBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkPregnancyFailure.sizePolicy().hasHeightForWidth())
        self.chkPregnancyFailure.setSizePolicy(sizePolicy)
        self.chkPregnancyFailure.setText(_fromUtf8(""))
        self.chkPregnancyFailure.setObjectName(_fromUtf8("chkPregnancyFailure"))
        self.gridLayout_7.addWidget(self.chkPregnancyFailure, 4, 3, 1, 1)
        self.chkPregnancy = QtGui.QCheckBox(self.grpActions)
        self.chkPregnancy.setText(_fromUtf8(""))
        self.chkPregnancy.setObjectName(_fromUtf8("chkPregnancy"))
        self.gridLayout_7.addWidget(self.chkPregnancy, 3, 3, 1, 1)
        self.lblPregnancy = QtGui.QLabel(self.grpActions)
        self.lblPregnancy.setObjectName(_fromUtf8("lblPregnancy"))
        self.gridLayout_7.addWidget(self.lblPregnancy, 3, 2, 1, 1)
        self.cmbOrgId = COrgComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgId.sizePolicy().hasHeightForWidth())
        self.cmbOrgId.setSizePolicy(sizePolicy)
        self.cmbOrgId.setObjectName(_fromUtf8("cmbOrgId"))
        self.gridLayout_7.addWidget(self.cmbOrgId, 4, 7, 1, 1)
        self.cmbTransferredTransportation = CRBComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTransferredTransportation.sizePolicy().hasHeightForWidth())
        self.cmbTransferredTransportation.setSizePolicy(sizePolicy)
        self.cmbTransferredTransportation.setObjectName(_fromUtf8("cmbTransferredTransportation"))
        self.cmbTransferredTransportation.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbTransferredTransportation, 3, 7, 1, 1)
        self.lblOrgId = QtGui.QLabel(self.grpActions)
        self.lblOrgId.setObjectName(_fromUtf8("lblOrgId"))
        self.gridLayout_7.addWidget(self.lblOrgId, 4, 6, 1, 1)
        self.lblTransferredTransportation = QtGui.QLabel(self.grpActions)
        self.lblTransferredTransportation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTransferredTransportation.setObjectName(_fromUtf8("lblTransferredTransportation"))
        self.gridLayout_7.addWidget(self.lblTransferredTransportation, 3, 6, 1, 1)
        self.lblMethodTransportation = QtGui.QLabel(self.grpActions)
        self.lblMethodTransportation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblMethodTransportation.setObjectName(_fromUtf8("lblMethodTransportation"))
        self.gridLayout_7.addWidget(self.lblMethodTransportation, 1, 6, 1, 1)
        self.cmbMethodTransportation = CRBComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMethodTransportation.sizePolicy().hasHeightForWidth())
        self.cmbMethodTransportation.setSizePolicy(sizePolicy)
        self.cmbMethodTransportation.setObjectName(_fromUtf8("cmbMethodTransportation"))
        self.cmbMethodTransportation.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbMethodTransportation, 1, 7, 1, 1)
        self.cmbPlaceCall = CRBComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPlaceCall.sizePolicy().hasHeightForWidth())
        self.cmbPlaceCall.setSizePolicy(sizePolicy)
        self.cmbPlaceCall.setObjectName(_fromUtf8("cmbPlaceCall"))
        self.cmbPlaceCall.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbPlaceCall, 0, 7, 1, 1)
        self.lblPlaceCall = QtGui.QLabel(self.grpActions)
        self.lblPlaceCall.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPlaceCall.setObjectName(_fromUtf8("lblPlaceCall"))
        self.gridLayout_7.addWidget(self.lblPlaceCall, 0, 6, 1, 1)
        self.cmbDiseased = CRBComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDiseased.sizePolicy().hasHeightForWidth())
        self.cmbDiseased.setSizePolicy(sizePolicy)
        self.cmbDiseased.setObjectName(_fromUtf8("cmbDiseased"))
        self.cmbDiseased.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbDiseased, 4, 5, 1, 1)
        self.cmbEbriety = CRBComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEbriety.sizePolicy().hasHeightForWidth())
        self.cmbEbriety.setSizePolicy(sizePolicy)
        self.cmbEbriety.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.cmbEbriety.setObjectName(_fromUtf8("cmbEbriety"))
        self.cmbEbriety.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbEbriety, 3, 5, 1, 1)
        self.cmbDeath = CRBComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDeath.sizePolicy().hasHeightForWidth())
        self.cmbDeath.setSizePolicy(sizePolicy)
        self.cmbDeath.setObjectName(_fromUtf8("cmbDeath"))
        self.cmbDeath.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbDeath, 1, 5, 1, 1)
        self.cmbAccident = CRBComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAccident.sizePolicy().hasHeightForWidth())
        self.cmbAccident.setSizePolicy(sizePolicy)
        self.cmbAccident.setObjectName(_fromUtf8("cmbAccident"))
        self.cmbAccident.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbAccident, 0, 5, 1, 1)
        self.lblDiseased = QtGui.QLabel(self.grpActions)
        self.lblDiseased.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDiseased.setObjectName(_fromUtf8("lblDiseased"))
        self.gridLayout_7.addWidget(self.lblDiseased, 4, 4, 1, 1)
        self.lblEbriety = QtGui.QLabel(self.grpActions)
        self.lblEbriety.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEbriety.setObjectName(_fromUtf8("lblEbriety"))
        self.gridLayout_7.addWidget(self.lblEbriety, 3, 4, 1, 1)
        self.lblDeath = QtGui.QLabel(self.grpActions)
        self.lblDeath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDeath.setObjectName(_fromUtf8("lblDeath"))
        self.gridLayout_7.addWidget(self.lblDeath, 1, 4, 1, 1)
        self.lblAccident = QtGui.QLabel(self.grpActions)
        self.lblAccident.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAccident.setObjectName(_fromUtf8("lblAccident"))
        self.gridLayout_7.addWidget(self.lblAccident, 0, 4, 1, 1)
        self.cmbLocCity = CKLADRComboBox(self.grpActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbLocCity.sizePolicy().hasHeightForWidth())
        self.cmbLocCity.setSizePolicy(sizePolicy)
        self.cmbLocCity.setObjectName(_fromUtf8("cmbLocCity"))
        self.cmbLocCity.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cmbLocCity, 6, 1, 1, 2)
        self.verticalLayout.addWidget(self.grpActions)
        self.tabWidget.addTab(self.tabToken, _fromUtf8(""))
        self.tabMedicalDiagnosis = CEventMedicalDiagnosisPage()
        self.tabMedicalDiagnosis.setObjectName(_fromUtf8("tabMedicalDiagnosis"))
        self.tabWidget.addTab(self.tabMedicalDiagnosis, _fromUtf8(""))
        self.tabMes = CEventMesPage()
        self.tabMes.setObjectName(_fromUtf8("tabMes"))
        self.tabWidget.addTab(self.tabMes, _fromUtf8(""))
        self.tabStatus = CActionsPage()
        self.tabStatus.setObjectName(_fromUtf8("tabStatus"))
        self.tabWidget.addTab(self.tabStatus, _fromUtf8(""))
        self.tabDiagnostic = CActionsPage()
        self.tabDiagnostic.setObjectName(_fromUtf8("tabDiagnostic"))
        self.tabWidget.addTab(self.tabDiagnostic, _fromUtf8(""))
        self.tabCure = CActionsPage()
        self.tabCure.setObjectName(_fromUtf8("tabCure"))
        self.tabWidget.addTab(self.tabCure, _fromUtf8(""))
        self.tabMisc = CActionsPage()
        self.tabMisc.setObjectName(_fromUtf8("tabMisc"))
        self.tabWidget.addTab(self.tabMisc, _fromUtf8(""))
        self.tabAmbCard = CAmbCardPage()
        self.tabAmbCard.setObjectName(_fromUtf8("tabAmbCard"))
        self.tabWidget.addTab(self.tabAmbCard, _fromUtf8(""))
        self.tabTempInvalidEtc = QtGui.QWidget()
        self.tabTempInvalidEtc.setObjectName(_fromUtf8("tabTempInvalidEtc"))
        self.gridLayout = QtGui.QGridLayout(self.tabTempInvalidEtc)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setMargin(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabTempInvalidAndAegrotat = QtGui.QTabWidget(self.tabTempInvalidEtc)
        self.tabTempInvalidAndAegrotat.setObjectName(_fromUtf8("tabTempInvalidAndAegrotat"))
        self.tabTempInvalid = QtGui.QWidget()
        self.tabTempInvalid.setObjectName(_fromUtf8("tabTempInvalid"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabTempInvalid)
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setMargin(4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.grpTempInvalid = CTempInvalid(self.tabTempInvalid)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpTempInvalid.sizePolicy().hasHeightForWidth())
        self.grpTempInvalid.setSizePolicy(sizePolicy)
        self.grpTempInvalid.setChecked(False)
        self.grpTempInvalid.setObjectName(_fromUtf8("grpTempInvalid"))
        self.verticalLayout_5.addWidget(self.grpTempInvalid)
        self.tabTempInvalidAndAegrotat.addTab(self.tabTempInvalid, _fromUtf8(""))
        self.tabAegrotat = QtGui.QWidget()
        self.tabAegrotat.setObjectName(_fromUtf8("tabAegrotat"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabAegrotat)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setMargin(4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.grpAegrotat = CTempInvalid(self.tabAegrotat)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpAegrotat.sizePolicy().hasHeightForWidth())
        self.grpAegrotat.setSizePolicy(sizePolicy)
        self.grpAegrotat.setChecked(False)
        self.grpAegrotat.setObjectName(_fromUtf8("grpAegrotat"))
        self.verticalLayout_4.addWidget(self.grpAegrotat)
        self.tabTempInvalidAndAegrotat.addTab(self.tabAegrotat, _fromUtf8(""))
        self.tabDisability = QtGui.QWidget()
        self.tabDisability.setObjectName(_fromUtf8("tabDisability"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabDisability)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setMargin(4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.grpDisability = CTempInvalid(self.tabDisability)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpDisability.sizePolicy().hasHeightForWidth())
        self.grpDisability.setSizePolicy(sizePolicy)
        self.grpDisability.setChecked(False)
        self.grpDisability.setObjectName(_fromUtf8("grpDisability"))
        self.verticalLayout_2.addWidget(self.grpDisability)
        self.tabTempInvalidAndAegrotat.addTab(self.tabDisability, _fromUtf8(""))
        self.tabVitalRestriction = QtGui.QWidget()
        self.tabVitalRestriction.setObjectName(_fromUtf8("tabVitalRestriction"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabVitalRestriction)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setMargin(4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.grpVitalRestriction = CTempInvalid(self.tabVitalRestriction)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpVitalRestriction.sizePolicy().hasHeightForWidth())
        self.grpVitalRestriction.setSizePolicy(sizePolicy)
        self.grpVitalRestriction.setChecked(False)
        self.grpVitalRestriction.setObjectName(_fromUtf8("grpVitalRestriction"))
        self.verticalLayout_6.addWidget(self.grpVitalRestriction)
        self.tabTempInvalidAndAegrotat.addTab(self.tabVitalRestriction, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabTempInvalidAndAegrotat, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabTempInvalidEtc, _fromUtf8(""))
        self.tabCash = CEventCashPage()
        self.tabCash.setObjectName(_fromUtf8("tabCash"))
        self.tabWidget.addTab(self.tabCash, _fromUtf8(""))
        self.tabNotes = CEventNotesPage()
        self.tabNotes.setObjectName(_fromUtf8("tabNotes"))
        self.tabWidget.addTab(self.tabNotes, _fromUtf8(""))
        self.scrollArea.setWidget(self.tabWidget)
        self.gridLayout_6.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.lblFaceRenunOfHospital.setBuddy(self.edtFaceRenunOfHospital)
        self.lblCauseCall.setBuddy(self.cmbCauseCall)
        self.lblWhoCallOnPhone.setBuddy(self.edtWhoCallOnPhone)
        self.lblPassDate.setBuddy(self.edtPassDate)
        self.lblNumberCardCall.setBuddy(self.edtNumberCardCall)
        self.lblDepartureDate.setBuddy(self.edtDepartureDate)
        self.lblNumberBrigade.setBuddy(self.cmbNumberBrigade)
        self.lblNumberPhone.setBuddy(self.edtNumberPhone)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lblArrivalDate.setBuddy(self.edtArrivalDate)
        self.lblFinishServiceDate.setBuddy(self.edtFinishServiceDate)
        self.lblEndDateDate.setBuddy(self.edtEndDate)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblDispatcher.setBuddy(self.cmbDispatcher)
        self.lblOrder.setBuddy(self.cmbOrder)
        self.lblResult.setBuddy(self.cmbResult)
        self.lblPlaceReceptionCall.setBuddy(self.cmbPlaceReceptionCall)
        self.lblDisease.setBuddy(self.chkDisease)
        self.lblReceivedCall.setBuddy(self.cmbReceivedCall)
        self.lblBirth.setBuddy(self.chkBirth)
        self.lblReasondDelays.setBuddy(self.cmbReasondDelays)
        self.lblResultCircumstanceCall.setBuddy(self.cmbResultCircumstanceCall)
        self.lblHouse.setBuddy(self.edtLocHouse)
        self.lblBuilding.setBuddy(self.edtLocCorpus)
        self.lblFlat.setBuddy(self.edtLocFlat)
        self.lblPregnancyFailure.setBuddy(self.chkPregnancyFailure)
        self.lblTransferredTransportation.setBuddy(self.cmbTransferredTransportation)
        self.lblMethodTransportation.setBuddy(self.cmbMethodTransportation)
        self.lblPlaceCall.setBuddy(self.cmbPlaceCall)
        self.lblDiseased.setBuddy(self.cmbDiseased)
        self.lblEbriety.setBuddy(self.cmbEbriety)
        self.lblDeath.setBuddy(self.cmbDeath)
        self.lblAccident.setBuddy(self.cmbAccident)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabTempInvalidAndAegrotat.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.grpRenunOfHospital, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFaceRenunOfHospital.setEnabled)
        QtCore.QObject.connect(self.grpRenunOfHospital, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblFaceRenunOfHospital.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.edtNumberCardCall)
        Dialog.setTabOrder(self.edtNumberCardCall, self.cmbContract)
        Dialog.setTabOrder(self.cmbContract, self.cmbNumberBrigade)
        Dialog.setTabOrder(self.cmbNumberBrigade, self.cmbCauseCall)
        Dialog.setTabOrder(self.cmbCauseCall, self.edtWhoCallOnPhone)
        Dialog.setTabOrder(self.edtWhoCallOnPhone, self.edtNumberPhone)
        Dialog.setTabOrder(self.edtNumberPhone, self.edtStorey)
        Dialog.setTabOrder(self.edtStorey, self.edtEntrance)
        Dialog.setTabOrder(self.edtEntrance, self.cmbOrgStructure)
        Dialog.setTabOrder(self.cmbOrgStructure, self.edtAdditional)
        Dialog.setTabOrder(self.edtAdditional, self.edtBegDate)
        Dialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        Dialog.setTabOrder(self.edtBegTime, self.edtPassDate)
        Dialog.setTabOrder(self.edtPassDate, self.edtPassTime)
        Dialog.setTabOrder(self.edtPassTime, self.edtDepartureDate)
        Dialog.setTabOrder(self.edtDepartureDate, self.edtDepartureTime)
        Dialog.setTabOrder(self.edtDepartureTime, self.edtArrivalDate)
        Dialog.setTabOrder(self.edtArrivalDate, self.edtArrivalTime)
        Dialog.setTabOrder(self.edtArrivalTime, self.edtFinishServiceDate)
        Dialog.setTabOrder(self.edtFinishServiceDate, self.edtFinishServiceTime)
        Dialog.setTabOrder(self.edtFinishServiceTime, self.edtEndDate)
        Dialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        Dialog.setTabOrder(self.edtEndTime, self.cmbPerson)
        Dialog.setTabOrder(self.cmbPerson, self.cmbDispatcher)
        Dialog.setTabOrder(self.cmbDispatcher, self.cmbGuidePerson)
        Dialog.setTabOrder(self.cmbGuidePerson, self.cmbOrder)
        Dialog.setTabOrder(self.cmbOrder, self.cmbResult)
        Dialog.setTabOrder(self.cmbResult, self.cmbOrderEvent)
        Dialog.setTabOrder(self.cmbOrderEvent, self.edtNumberEpidemic)
        Dialog.setTabOrder(self.edtNumberEpidemic, self.edtOrderNumber)
        Dialog.setTabOrder(self.edtOrderNumber, self.grpRenunOfHospital)
        Dialog.setTabOrder(self.grpRenunOfHospital, self.cmbTypeAsset)
        Dialog.setTabOrder(self.cmbTypeAsset, self.edtNextDate)
        Dialog.setTabOrder(self.edtNextDate, self.edtNextTime)
        Dialog.setTabOrder(self.edtNextTime, self.tblFinalDiagnostics)
        Dialog.setTabOrder(self.tblFinalDiagnostics, self.tblPersonnel)
        Dialog.setTabOrder(self.tblPersonnel, self.edtFaceRenunOfHospital)
        Dialog.setTabOrder(self.edtFaceRenunOfHospital, self.cmbPlaceReceptionCall)
        Dialog.setTabOrder(self.cmbPlaceReceptionCall, self.cmbReceivedCall)
        Dialog.setTabOrder(self.cmbReceivedCall, self.cmbReasondDelays)
        Dialog.setTabOrder(self.cmbReasondDelays, self.cmbResultCircumstanceCall)
        Dialog.setTabOrder(self.cmbResultCircumstanceCall, self.chkDisease)
        Dialog.setTabOrder(self.chkDisease, self.chkBirth)
        Dialog.setTabOrder(self.chkBirth, self.chkPregnancy)
        Dialog.setTabOrder(self.chkPregnancy, self.chkPregnancyFailure)
        Dialog.setTabOrder(self.chkPregnancyFailure, self.cmbLocCity)
        Dialog.setTabOrder(self.cmbLocCity, self.cmbLocStreet)
        Dialog.setTabOrder(self.cmbLocStreet, self.edtLocHouse)
        Dialog.setTabOrder(self.edtLocHouse, self.edtLocCorpus)
        Dialog.setTabOrder(self.edtLocCorpus, self.edtLocFlat)
        Dialog.setTabOrder(self.edtLocFlat, self.btnLocHouseList)
        Dialog.setTabOrder(self.btnLocHouseList, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.tabTempInvalidAndAegrotat)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.statusBar.setToolTip(_translate("Dialog", "A status bar", None))
        self.statusBar.setWhatsThis(_translate("Dialog", "A status bar.", None))
        self.txtClientInfoBrowser.setWhatsThis(_translate("Dialog", "Описание пациента", None))
        self.txtClientInfoBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.grplFinalDiagnostics.setTitle(_translate("Dialog", "&Диагнозы", None))
        self.groupBox.setTitle(_translate("Dialog", "&Состав бригады", None))
        self.grpRenunOfHospital.setTitle(_translate("Dialog", "Отказ от госпитализации", None))
        self.lblFaceRenunOfHospital.setText(_translate("Dialog", "Лицо отказа от госпитализации", None))
        self.grpBase.setTitle(_translate("Dialog", "&ф.110/У", None))
        self.cmbOrderEvent.setItemText(0, _translate("Dialog", "Плановый", None))
        self.cmbOrderEvent.setItemText(1, _translate("Dialog", "Экстренный", None))
        self.cmbOrderEvent.setItemText(2, _translate("Dialog", "Самотёком", None))
        self.cmbOrderEvent.setItemText(3, _translate("Dialog", "Принудительный", None))
        self.cmbOrderEvent.setItemText(4, _translate("Dialog", "Внутренний перевод", None))
        self.cmbOrderEvent.setItemText(5, _translate("Dialog", "Неотложная", None))
        self.lblVisitsDurationValue.setToolTip(_translate("Dialog", "Общее время вызова", None))
        self.lblVisitsDurationValue.setText(_translate("Dialog", "00:00", None))
        self.lblCauseCall.setText(_translate("Dialog", "Повод к вызову", None))
        self.cmbCauseCall.setItemText(0, _translate("Dialog", "Повод к вызову", None))
        self.lblWhoCallOnPhone.setText(_translate("Dialog", "Кто вызывал", None))
        self.edtNextTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.lblTimeToFinishServiceDate.setToolTip(_translate("Dialog", "Время до оконч. обслуж.", None))
        self.lblTimeToFinishServiceDate.setText(_translate("Dialog", "00:00", None))
        self.lblPassDate.setText(_translate("Dialog", "Передано", None))
        self.cmbNumberBrigade.setItemText(0, _translate("Dialog", "Номер бригады", None))
        self.cmbContract.setWhatsThis(_translate("Dialog", "номер, дата и основание договора в рамках которого производится осмотр", None))
        self.cmbContract.setItemText(0, _translate("Dialog", "Договор", None))
        self.edtBegDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.edtBegTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.lblNumberCardCall.setText(_translate("Dialog", "Карта вызова №", None))
        self.lblStorey.setText(_translate("Dialog", "Этаж", None))
        self.edtPassDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.edtPassTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.lblTimeToPassDate.setToolTip(_translate("Dialog", "Время до передачи бригаде", None))
        self.lblTimeToPassDate.setText(_translate("Dialog", "00:00", None))
        self.lblDepartureDate.setText(_translate("Dialog", "Выезд", None))
        self.lblNumberBrigade.setText(_translate("Dialog", "Номер бригады", None))
        self.lblNumberPhone.setText(_translate("Dialog", "С телефона", None))
        self.lblBegDate.setText(_translate("Dialog", "Принято", None))
        self.edtDepartureDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.edtDepartureTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.lblTimeToDepartureDate.setToolTip(_translate("Dialog", "Время до выезда", None))
        self.lblTimeToDepartureDate.setText(_translate("Dialog", "00:00", None))
        self.lblArrivalDate.setText(_translate("Dialog", "Прибытие", None))
        self.edtArrivalDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.edtArrivalTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.lblTimeToArrivalDate.setToolTip(_translate("Dialog", "Время до прибытия", None))
        self.lblTimeToArrivalDate.setText(_translate("Dialog", "00:00", None))
        self.lblFinishServiceDate.setText(_translate("Dialog", "Оконч. обслуж.", None))
        self.edtFinishServiceDate.setWhatsThis(_translate("Dialog", "дата окончания осмотра", None))
        self.edtFinishServiceDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.edtFinishServiceTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.lblEndDateDate.setText(_translate("Dialog", "Возвр. на станц.", None))
        self.edtEndDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.edtEndTime.setDisplayFormat(_translate("Dialog", "HH:mm", None))
        self.lblAdditional.setText(_translate("Dialog", "Дополнительно", None))
        self.lblTimeToEndDate.setToolTip(_translate("Dialog", "Время до возвр. на станц.", None))
        self.lblTimeToEndDate.setText(_translate("Dialog", "00:00", None))
        self.lblPerson.setText(_translate("Dialog", "Ответственный", None))
        self.cmbPerson.setWhatsThis(_translate("Dialog", "врач отвечающий за осмотр (терапевт)", None))
        self.cmbPerson.setItemText(0, _translate("Dialog", "Врач", None))
        self.lblDispatcher.setText(_translate("Dialog", "Диспетчер", None))
        self.cmbDispatcher.setItemText(0, _translate("Dialog", "Диспетчер", None))
        self.lblOrder.setText(_translate("Dialog", "В&ызов", None))
        self.cmbOrder.setItemText(0, _translate("Dialog", "Первичный", None))
        self.cmbOrder.setItemText(1, _translate("Dialog", "Повторный", None))
        self.cmbOrder.setItemText(2, _translate("Dialog", "Активное посещение", None))
        self.cmbOrder.setItemText(3, _translate("Dialog", "Перевозка", None))
        self.cmbOrder.setItemText(4, _translate("Dialog", "Амбулаторно", None))
        self.lblResult.setText(_translate("Dialog", "Результа&т", None))
        self.cmbResult.setWhatsThis(_translate("Dialog", "результат осмотра", None))
        self.cmbResult.setItemText(0, _translate("Dialog", "Результат", None))
        self.lblTypeAsset.setText(_translate("Dialog", "Активное посещение", None))
        self.cmbTypeAsset.setItemText(0, _translate("Dialog", "Активное посещение", None))
        self.edtNextDate.setWhatsThis(_translate("Dialog", "дата начала осмотра", None))
        self.edtNextDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy", None))
        self.lblOrderEvent.setText(_translate("Dialog", "Порядок", None))
        self.lblEntrance.setText(_translate("Dialog", "Вход", None))
        self.lblGuidePerson.setText(_translate("Dialog", "Направитель", None))
        self.cmbGuidePerson.setItemText(0, _translate("Dialog", "Направитель", None))
        self.lblNumberEpidemic.setText(_translate("Dialog", "Эпид.номер", None))
        self.lblOrderNumber.setText(_translate("Dialog", "Наряд", None))
        self.lblOrgStructure.setText(_translate("Dialog", "Зона обслуживания", None))
        self.grpActions.setTitle(_translate("Dialog", "&Обстоятельства вызова", None))
        self.lblPlaceReceptionCall.setText(_translate("Dialog", "Место получения вызова", None))
        self.cmbPlaceReceptionCall.setItemText(0, _translate("Dialog", "Место получения вызова", None))
        self.lblDisease.setText(_translate("Dialog", "Заболевание", None))
        self.lblReceivedCall.setText(_translate("Dialog", "Вызов получен", None))
        self.cmbReceivedCall.setItemText(0, _translate("Dialog", "Вызов получен", None))
        self.lblBirth.setText(_translate("Dialog", "Роды", None))
        self.lblReasondDelays.setText(_translate("Dialog", "Причина задержки", None))
        self.cmbReasondDelays.setItemText(0, _translate("Dialog", "Причина задержки", None))
        self.lblResultCircumstanceCall.setText(_translate("Dialog", "Результат", None))
        self.cmbResultCircumstanceCall.setItemText(0, _translate("Dialog", "Результат", None))
        self.lblAddressCall.setText(_translate("Dialog", "Адрес вызова", None))
        self.cmbLocStreet.setItemText(0, _translate("Dialog", "Улица", None))
        self.lblHouse.setText(_translate("Dialog", "Дом", None))
        self.lblBuilding.setText(_translate("Dialog", "Корп", None))
        self.lblFlat.setText(_translate("Dialog", "Кв", None))
        self.btnLocHouseList.setText(_translate("Dialog", "...", None))
        self.lblPregnancyFailure.setText(_translate("Dialog", "Патология берем.", None))
        self.lblPregnancy.setText(_translate("Dialog", "Беременность", None))
        self.cmbTransferredTransportation.setItemText(0, _translate("Dialog", "Транспортировку перенес", None))
        self.lblOrgId.setText(_translate("Dialog", "Больница", None))
        self.lblTransferredTransportation.setText(_translate("Dialog", "Транспортировку перенес", None))
        self.lblMethodTransportation.setText(_translate("Dialog", "Способ транспортировки", None))
        self.cmbMethodTransportation.setItemText(0, _translate("Dialog", "Способ транспортировки", None))
        self.cmbPlaceCall.setItemText(0, _translate("Dialog", "Место вызова", None))
        self.lblPlaceCall.setText(_translate("Dialog", "Место вызова", None))
        self.cmbDiseased.setItemText(0, _translate("Dialog", "Больной", None))
        self.cmbEbriety.setItemText(0, _translate("Dialog", "Опьянение", None))
        self.cmbDeath.setItemText(0, _translate("Dialog", "Смерть", None))
        self.cmbAccident.setItemText(0, _translate("Dialog", "Несчастный случай", None))
        self.lblDiseased.setText(_translate("Dialog", "Больной", None))
        self.lblEbriety.setText(_translate("Dialog", "Опьянение", None))
        self.lblDeath.setText(_translate("Dialog", "Смерть", None))
        self.lblAccident.setText(_translate("Dialog", "Несчастный случай", None))
        self.cmbLocCity.setItemText(0, _translate("Dialog", "Город", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabToken), _translate("Dialog", "Стат.&учёт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMedicalDiagnosis), _translate("Dialog", "Диагно&з", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMes), _translate("Dialog", "Ст&андарт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatus), _translate("Dialog", "&Статус", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiagnostic), _translate("Dialog", "&Диагностика", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCure), _translate("Dialog", "&Лечение", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMisc), _translate("Dialog", "&Мероприятия", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAmbCard), _translate("Dialog", "Мед.&карта", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabTempInvalid), _translate("Dialog", "Листок &нетрудоспособности", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabAegrotat), _translate("Dialog", "С&правка", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabDisability), _translate("Dialog", "Инвалидность", None))
        self.tabTempInvalidAndAegrotat.setTabText(self.tabTempInvalidAndAegrotat.indexOf(self.tabVitalRestriction), _translate("Dialog", "О&граничения жизнедеятельности", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTempInvalidEtc), _translate("Dialog", "Т&рудоспособность", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCash), _translate("Dialog", "&Оплата", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNotes), _translate("Dialog", "Приме&чания", None))

from Orgs.OrgComboBox import COrgComboBox, CContractComboBox
from Events.TempInvalid import CTempInvalid
from library.crbcombobox import CRBComboBox
from KLADR.kladrComboxes import CKLADRComboBox, CStreetComboBox
from library.InDocTable import CInDocTableView
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from library.ROComboBox import CROComboBox
from Events.ActionsPage import CActionsPage
from Events.EventMedicalDiagnosisPage import CEventMedicalDiagnosisPage
from library.TextBrowser import CTextBrowser
from Events.EventCashPage import CEventCashPage
from Events.EventNotesPage import CEventNotesPage
from Events.AmbCardPage import CAmbCardPage
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Events.EventMesPage import CEventMesPage
from library.DateEdit import CDateEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

