# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client\F090\F090.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_F090Dialog(object):
    def setupUi(self, F090Dialog):
        F090Dialog.setObjectName(_fromUtf8("F090Dialog"))
        F090Dialog.resize(1227, 597)
        self.gridLayout_3 = QtGui.QGridLayout(F090Dialog)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter_7 = QtGui.QSplitter(F090Dialog)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.txtClientInfoBrowser = CTextBrowser(self.splitter_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.txtClientInfoBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.scrollArea = QtGui.QScrollArea(self.splitter_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1412, 447))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_63 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_63.setMargin(1)
        self.gridLayout_63.setSpacing(1)
        self.gridLayout_63.setObjectName(_fromUtf8("gridLayout_63"))
        self.frameAP = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameAP.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAP.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameAP.setObjectName(_fromUtf8("frameAP"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frameAP)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frmMiddle = QtGui.QWidget(self.frameAP)
        self.frmMiddle.setObjectName(_fromUtf8("frmMiddle"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frmMiddle)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.cmbStatus = CActionStatusComboBox(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbStatus.sizePolicy().hasHeightForWidth())
        self.cmbStatus.setSizePolicy(sizePolicy)
        self.cmbStatus.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cmbStatus.setObjectName(_fromUtf8("cmbStatus"))
        self.horizontalLayout_8.addWidget(self.cmbStatus)
        self.frmAPBegDateTime = QtGui.QFrame(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPBegDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPBegDateTime.setSizePolicy(sizePolicy)
        self.frmAPBegDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPBegDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPBegDateTime.setLineWidth(0)
        self.frmAPBegDateTime.setObjectName(_fromUtf8("frmAPBegDateTime"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frmAPBegDateTime)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblBegDate = QtGui.QLabel(self.frmAPBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDate.sizePolicy().hasHeightForWidth())
        self.lblBegDate.setSizePolicy(sizePolicy)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.horizontalLayout_2.addWidget(self.lblBegDate)
        self.edtBegDate = CF090DateEdit(self.frmAPBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDate.sizePolicy().hasHeightForWidth())
        self.edtBegDate.setSizePolicy(sizePolicy)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout_2.addWidget(self.edtBegDate)
        self.edtBegTime = CTimeEdit(self.frmAPBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegTime.sizePolicy().hasHeightForWidth())
        self.edtBegTime.setSizePolicy(sizePolicy)
        self.edtBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.horizontalLayout_2.addWidget(self.edtBegTime)
        self.horizontalLayout_8.addWidget(self.frmAPBegDateTime)
        self.frmAPEndDateTime = QtGui.QFrame(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPEndDateTime.setSizePolicy(sizePolicy)
        self.frmAPEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPEndDateTime.setLineWidth(0)
        self.frmAPEndDateTime.setObjectName(_fromUtf8("frmAPEndDateTime"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frmAPEndDateTime)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lbEndDate = QtGui.QLabel(self.frmAPEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbEndDate.sizePolicy().hasHeightForWidth())
        self.lbEndDate.setSizePolicy(sizePolicy)
        self.lbEndDate.setObjectName(_fromUtf8("lbEndDate"))
        self.horizontalLayout_6.addWidget(self.lbEndDate)
        self.edtEndDate = CF090DateEdit(self.frmAPEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDate.sizePolicy().hasHeightForWidth())
        self.edtEndDate.setSizePolicy(sizePolicy)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout_6.addWidget(self.edtEndDate)
        self.edtEndTime = QtGui.QTimeEdit(self.frmAPEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndTime.sizePolicy().hasHeightForWidth())
        self.edtEndTime.setSizePolicy(sizePolicy)
        self.edtEndTime.setMaximumSize(QtCore.QSize(47, 16777215))
        self.edtEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.horizontalLayout_6.addWidget(self.edtEndTime)
        self.horizontalLayout_8.addWidget(self.frmAPEndDateTime)
        self.lblAmount = QtGui.QLabel(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAmount.sizePolicy().hasHeightForWidth())
        self.lblAmount.setSizePolicy(sizePolicy)
        self.lblAmount.setObjectName(_fromUtf8("lblAmount"))
        self.horizontalLayout_8.addWidget(self.lblAmount)
        self.edtAmount = QtGui.QDoubleSpinBox(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAmount.sizePolicy().hasHeightForWidth())
        self.edtAmount.setSizePolicy(sizePolicy)
        self.edtAmount.setMaximum(999.99)
        self.edtAmount.setObjectName(_fromUtf8("edtAmount"))
        self.horizontalLayout_8.addWidget(self.edtAmount)
        self.lblUet = QtGui.QLabel(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUet.sizePolicy().hasHeightForWidth())
        self.lblUet.setSizePolicy(sizePolicy)
        self.lblUet.setObjectName(_fromUtf8("lblUet"))
        self.horizontalLayout_8.addWidget(self.lblUet)
        self.edtUet = QtGui.QDoubleSpinBox(self.frmMiddle)
        self.edtUet.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtUet.sizePolicy().hasHeightForWidth())
        self.edtUet.setSizePolicy(sizePolicy)
        self.edtUet.setReadOnly(True)
        self.edtUet.setMaximum(1000.0)
        self.edtUet.setSingleStep(0.5)
        self.edtUet.setObjectName(_fromUtf8("edtUet"))
        self.horizontalLayout_8.addWidget(self.edtUet)
        self.lblOffice = QtGui.QLabel(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOffice.sizePolicy().hasHeightForWidth())
        self.lblOffice.setSizePolicy(sizePolicy)
        self.lblOffice.setObjectName(_fromUtf8("lblOffice"))
        self.horizontalLayout_8.addWidget(self.lblOffice)
        self.edtOffice = QtGui.QLineEdit(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOffice.sizePolicy().hasHeightForWidth())
        self.edtOffice.setSizePolicy(sizePolicy)
        self.edtOffice.setMaxLength(16)
        self.edtOffice.setObjectName(_fromUtf8("edtOffice"))
        self.horizontalLayout_8.addWidget(self.edtOffice)
        self.gridLayout_2.addWidget(self.frmMiddle, 3, 1, 1, 6)
        self.cmbOrg = CPolyclinicComboBox(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrg.sizePolicy().hasHeightForWidth())
        self.cmbOrg.setSizePolicy(sizePolicy)
        self.cmbOrg.setObjectName(_fromUtf8("cmbOrg"))
        self.cmbOrg.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbOrg, 2, 1, 1, 2)
        self.cmbPerson = CPersonWithOrgListComboBoxEx(self.frameAP)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbPerson, 6, 1, 1, 3)
        self.lblNote = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNote.sizePolicy().hasHeightForWidth())
        self.lblNote.setSizePolicy(sizePolicy)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout_2.addWidget(self.lblNote, 7, 0, 1, 1)
        self.lblStatus = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.gridLayout_2.addWidget(self.lblStatus, 3, 0, 1, 1)
        self.cmbAssistant = CPersonWithOrgListComboBoxEx(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAssistant.sizePolicy().hasHeightForWidth())
        self.cmbAssistant.setSizePolicy(sizePolicy)
        self.cmbAssistant.setObjectName(_fromUtf8("cmbAssistant"))
        self.cmbAssistant.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbAssistant, 6, 5, 1, 2)
        self.lblPerson = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPerson.sizePolicy().hasHeightForWidth())
        self.lblPerson.setSizePolicy(sizePolicy)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout_2.addWidget(self.lblPerson, 6, 0, 1, 1)
        self.lblOrg = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrg.sizePolicy().hasHeightForWidth())
        self.lblOrg.setSizePolicy(sizePolicy)
        self.lblOrg.setObjectName(_fromUtf8("lblOrg"))
        self.gridLayout_2.addWidget(self.lblOrg, 2, 0, 1, 1)
        self.lblAPDirectionDate = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPDirectionDate.sizePolicy().hasHeightForWidth())
        self.lblAPDirectionDate.setSizePolicy(sizePolicy)
        self.lblAPDirectionDate.setObjectName(_fromUtf8("lblAPDirectionDate"))
        self.gridLayout_2.addWidget(self.lblAPDirectionDate, 0, 0, 1, 1)
        self.btnSelectOrg = QtGui.QToolButton(self.frameAP)
        self.btnSelectOrg.setObjectName(_fromUtf8("btnSelectOrg"))
        self.gridLayout_2.addWidget(self.btnSelectOrg, 2, 3, 1, 1)
        self.edtNote = QtGui.QLineEdit(self.frameAP)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout_2.addWidget(self.edtNote, 7, 1, 1, 6)
        self.lblAssistant = QtGui.QLabel(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAssistant.sizePolicy().hasHeightForWidth())
        self.lblAssistant.setSizePolicy(sizePolicy)
        self.lblAssistant.setObjectName(_fromUtf8("lblAssistant"))
        self.gridLayout_2.addWidget(self.lblAssistant, 6, 4, 1, 1)
        self.frmAPButtonsBar = QtGui.QFrame(self.frameAP)
        self.frmAPButtonsBar.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPButtonsBar.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPButtonsBar.setLineWidth(0)
        self.frmAPButtonsBar.setObjectName(_fromUtf8("frmAPButtonsBar"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frmAPButtonsBar)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_2.addWidget(self.frmAPButtonsBar, 13, 0, 1, 7)
        self.frmTop = QtGui.QWidget(self.frameAP)
        self.frmTop.setObjectName(_fromUtf8("frmTop"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frmTop)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.frmAPDirectionDateTime = QtGui.QFrame(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPDirectionDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPDirectionDateTime.setSizePolicy(sizePolicy)
        self.frmAPDirectionDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPDirectionDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPDirectionDateTime.setObjectName(_fromUtf8("frmAPDirectionDateTime"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frmAPDirectionDateTime)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtDirectionDate = CF090DateEdit(self.frmAPDirectionDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDirectionDate.sizePolicy().hasHeightForWidth())
        self.edtDirectionDate.setSizePolicy(sizePolicy)
        self.edtDirectionDate.setCalendarPopup(True)
        self.edtDirectionDate.setObjectName(_fromUtf8("edtDirectionDate"))
        self.horizontalLayout.addWidget(self.edtDirectionDate)
        self.edtDirectionTime = CTimeEdit(self.frmAPDirectionDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDirectionTime.sizePolicy().hasHeightForWidth())
        self.edtDirectionTime.setSizePolicy(sizePolicy)
        self.edtDirectionTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtDirectionTime.setObjectName(_fromUtf8("edtDirectionTime"))
        self.horizontalLayout.addWidget(self.edtDirectionTime)
        self.horizontalLayout_7.addWidget(self.frmAPDirectionDateTime)
        self.chkIsUrgent = CROCheckBox(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkIsUrgent.sizePolicy().hasHeightForWidth())
        self.chkIsUrgent.setSizePolicy(sizePolicy)
        self.chkIsUrgent.setObjectName(_fromUtf8("chkIsUrgent"))
        self.horizontalLayout_7.addWidget(self.chkIsUrgent)
        self.lblSetPerson = QtGui.QLabel(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSetPerson.sizePolicy().hasHeightForWidth())
        self.lblSetPerson.setSizePolicy(sizePolicy)
        self.lblSetPerson.setObjectName(_fromUtf8("lblSetPerson"))
        self.horizontalLayout_7.addWidget(self.lblSetPerson)
        self.cmbSetPerson = CPersonWithOrgListComboBoxEx(self.frmTop)
        self.cmbSetPerson.setObjectName(_fromUtf8("cmbSetPerson"))
        self.cmbSetPerson.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.cmbSetPerson)
        self.lblPlannedEndDate = QtGui.QLabel(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPlannedEndDate.sizePolicy().hasHeightForWidth())
        self.lblPlannedEndDate.setSizePolicy(sizePolicy)
        self.lblPlannedEndDate.setObjectName(_fromUtf8("lblPlannedEndDate"))
        self.horizontalLayout_7.addWidget(self.lblPlannedEndDate)
        self.frmAPPlannedEndDateTime = QtGui.QFrame(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPPlannedEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPPlannedEndDateTime.setSizePolicy(sizePolicy)
        self.frmAPPlannedEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPPlannedEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPPlannedEndDateTime.setObjectName(_fromUtf8("frmAPPlannedEndDateTime"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frmAPPlannedEndDateTime)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.edtPlannedEndDate = CF090DateEdit(self.frmAPPlannedEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPlannedEndDate.sizePolicy().hasHeightForWidth())
        self.edtPlannedEndDate.setSizePolicy(sizePolicy)
        self.edtPlannedEndDate.setCalendarPopup(True)
        self.edtPlannedEndDate.setObjectName(_fromUtf8("edtPlannedEndDate"))
        self.horizontalLayout_5.addWidget(self.edtPlannedEndDate)
        self.edtPlannedEndTime = QtGui.QTimeEdit(self.frmAPPlannedEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPlannedEndTime.sizePolicy().hasHeightForWidth())
        self.edtPlannedEndTime.setSizePolicy(sizePolicy)
        self.edtPlannedEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtPlannedEndTime.setObjectName(_fromUtf8("edtPlannedEndTime"))
        self.horizontalLayout_5.addWidget(self.edtPlannedEndTime)
        self.horizontalLayout_7.addWidget(self.frmAPPlannedEndDateTime)
        self.gridLayout_2.addWidget(self.frmTop, 0, 1, 1, 6)
        self.pnlMainAPMKBWidgets = QtGui.QWidget(self.frameAP)
        self.pnlMainAPMKBWidgets.setObjectName(_fromUtf8("pnlMainAPMKBWidgets"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.pnlMainAPMKBWidgets)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pnlAPMKBWidgets = QtGui.QWidget(self.pnlMainAPMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnlAPMKBWidgets.sizePolicy().hasHeightForWidth())
        self.pnlAPMKBWidgets.setSizePolicy(sizePolicy)
        self.pnlAPMKBWidgets.setObjectName(_fromUtf8("pnlAPMKBWidgets"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.pnlAPMKBWidgets)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_10.addWidget(self.pnlAPMKBWidgets)
        self.gridLayout_2.addWidget(self.pnlMainAPMKBWidgets, 2, 4, 1, 3)
        self.gridLayout_63.addWidget(self.frameAP, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMainInformation = QtGui.QWidget()
        self.tabMainInformation.setObjectName(_fromUtf8("tabMainInformation"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabMainInformation)
        self.gridLayout_8.setContentsMargins(1, 6, 1, 6)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setMargin(6)
        self.gridLayout_4.setHorizontalSpacing(7)
        self.gridLayout_4.setVerticalSpacing(11)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblNameExecActions = QtGui.QLabel(self.tabMainInformation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNameExecActions.sizePolicy().hasHeightForWidth())
        self.lblNameExecActions.setSizePolicy(sizePolicy)
        self.lblNameExecActions.setObjectName(_fromUtf8("lblNameExecActions"))
        self.gridLayout_4.addWidget(self.lblNameExecActions, 0, 0, 1, 1)
        self.cmbHurtType = CF090RBComboBox(self.tabMainInformation)
        self.cmbHurtType.setObjectName(_fromUtf8("cmbHurtType"))
        self.gridLayout_4.addWidget(self.cmbHurtType, 0, 1, 1, 1)
        self.line = QtGui.QFrame(self.tabMainInformation)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 2)
        self.gridLayout_8.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setContentsMargins(6, 4, 6, 6)
        self.gridLayout_6.setHorizontalSpacing(7)
        self.gridLayout_6.setVerticalSpacing(11)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblElectronicMedicalBookNumber = QtGui.QLabel(self.tabMainInformation)
        self.lblElectronicMedicalBookNumber.setObjectName(_fromUtf8("lblElectronicMedicalBookNumber"))
        self.gridLayout_6.addWidget(self.lblElectronicMedicalBookNumber, 0, 0, 1, 2)
        self.line_3 = QtGui.QFrame(self.tabMainInformation)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_6.addWidget(self.line_3, 1, 0, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 3, 1, 1)
        self.edtElectronicMedicalBookNumber = QtGui.QLineEdit(self.tabMainInformation)
        self.edtElectronicMedicalBookNumber.setMinimumSize(QtCore.QSize(100, 0))
        self.edtElectronicMedicalBookNumber.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.edtElectronicMedicalBookNumber.setObjectName(_fromUtf8("edtElectronicMedicalBookNumber"))
        self.gridLayout_6.addWidget(self.edtElectronicMedicalBookNumber, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabMainInformation, _fromUtf8(""))
        self.tabInfectionDiseases = QtGui.QWidget()
        self.tabInfectionDiseases.setObjectName(_fromUtf8("tabInfectionDiseases"))
        self.gridLayout_30 = QtGui.QGridLayout(self.tabInfectionDiseases)
        self.gridLayout_30.setMargin(1)
        self.gridLayout_30.setSpacing(1)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.splitter_13 = QtGui.QSplitter(self.tabInfectionDiseases)
        self.splitter_13.setOrientation(QtCore.Qt.Vertical)
        self.splitter_13.setObjectName(_fromUtf8("splitter_13"))
        self.groupBox_5 = QtGui.QGroupBox(self.splitter_13)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_28 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_28.setMargin(1)
        self.gridLayout_28.setSpacing(1)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.splitter_14 = QtGui.QSplitter(self.groupBox_5)
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName(_fromUtf8("splitter_14"))
        self.splitter_15 = QtGui.QSplitter(self.splitter_14)
        self.splitter_15.setOrientation(QtCore.Qt.Vertical)
        self.splitter_15.setObjectName(_fromUtf8("splitter_15"))
        self.tblInfectionDiseases = CInDocTableView(self.splitter_15)
        self.tblInfectionDiseases.setObjectName(_fromUtf8("tblInfectionDiseases"))
        self.gridLayout_28.addWidget(self.splitter_14, 0, 0, 1, 1)
        self.tabClientDiseasesFilter = QtGui.QWidget(self.splitter_13)
        self.tabClientDiseasesFilter.setObjectName(_fromUtf8("tabClientDiseasesFilter"))
        self.gridLayout_29 = QtGui.QGridLayout(self.tabClientDiseasesFilter)
        self.gridLayout_29.setContentsMargins(4, 1, 4, 4)
        self.gridLayout_29.setSpacing(4)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.splitterClientDiseasesFilter = QtGui.QSplitter(self.tabClientDiseasesFilter)
        self.splitterClientDiseasesFilter.setOrientation(QtCore.Qt.Horizontal)
        self.splitterClientDiseasesFilter.setObjectName(_fromUtf8("splitterClientDiseasesFilter"))
        self.tblClientDiseases = CInDocTableView(self.splitterClientDiseasesFilter)
        self.tblClientDiseases.setObjectName(_fromUtf8("tblClientDiseases"))
        self.gridLayout_29.addWidget(self.splitterClientDiseasesFilter, 1, 0, 1, 1)
        self.frmClientDiseasesFilter = QtGui.QGroupBox(self.tabClientDiseasesFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmClientDiseasesFilter.sizePolicy().hasHeightForWidth())
        self.frmClientDiseasesFilter.setSizePolicy(sizePolicy)
        self.frmClientDiseasesFilter.setObjectName(_fromUtf8("frmClientDiseasesFilter"))
        self._14 = QtGui.QGridLayout(self.frmClientDiseasesFilter)
        self._14.setMargin(4)
        self._14.setHorizontalSpacing(11)
        self._14.setVerticalSpacing(4)
        self._14.setObjectName(_fromUtf8("_14"))
        self.chkExecActionsClientDiseasesFilter = QtGui.QCheckBox(self.frmClientDiseasesFilter)
        self.chkExecActionsClientDiseasesFilter.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkExecActionsClientDiseasesFilter.setChecked(True)
        self.chkExecActionsClientDiseasesFilter.setObjectName(_fromUtf8("chkExecActionsClientDiseasesFilter"))
        self._14.addWidget(self.chkExecActionsClientDiseasesFilter, 0, 4, 1, 1)
        self.lblMKBClientDiseasesFilter = QtGui.QLabel(self.frmClientDiseasesFilter)
        self.lblMKBClientDiseasesFilter.setObjectName(_fromUtf8("lblMKBClientDiseasesFilter"))
        self._14.addWidget(self.lblMKBClientDiseasesFilter, 0, 5, 1, 1)
        self.chkConcomitantClientDiseasesFilter = QtGui.QCheckBox(self.frmClientDiseasesFilter)
        self.chkConcomitantClientDiseasesFilter.setObjectName(_fromUtf8("chkConcomitantClientDiseasesFilter"))
        self._14.addWidget(self.chkConcomitantClientDiseasesFilter, 0, 10, 1, 1)
        self.chkPreliminaryClientDiseasesFilter = QtGui.QCheckBox(self.frmClientDiseasesFilter)
        self.chkPreliminaryClientDiseasesFilter.setObjectName(_fromUtf8("chkPreliminaryClientDiseasesFilter"))
        self._14.addWidget(self.chkPreliminaryClientDiseasesFilter, 0, 9, 1, 1)
        self.edtEndDateClientDiseasesFilter = CF090DateEdit(self.frmClientDiseasesFilter)
        self.edtEndDateClientDiseasesFilter.setCalendarPopup(True)
        self.edtEndDateClientDiseasesFilter.setObjectName(_fromUtf8("edtEndDateClientDiseasesFilter"))
        self._14.addWidget(self.edtEndDateClientDiseasesFilter, 0, 3, 1, 1)
        self.lblEndDateClientDiseasesFilter = QtGui.QLabel(self.frmClientDiseasesFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDateClientDiseasesFilter.sizePolicy().hasHeightForWidth())
        self.lblEndDateClientDiseasesFilter.setSizePolicy(sizePolicy)
        self.lblEndDateClientDiseasesFilter.setObjectName(_fromUtf8("lblEndDateClientDiseasesFilter"))
        self._14.addWidget(self.lblEndDateClientDiseasesFilter, 0, 2, 1, 1)
        self.lblBegDateClientDiseasesFilter = QtGui.QLabel(self.frmClientDiseasesFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDateClientDiseasesFilter.sizePolicy().hasHeightForWidth())
        self.lblBegDateClientDiseasesFilter.setSizePolicy(sizePolicy)
        self.lblBegDateClientDiseasesFilter.setObjectName(_fromUtf8("lblBegDateClientDiseasesFilter"))
        self._14.addWidget(self.lblBegDateClientDiseasesFilter, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.frmClientDiseasesFilter)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self._14.addWidget(self.label, 0, 8, 1, 1)
        self.edtBegDateClientDiseasesFilter = CF090DateEdit(self.frmClientDiseasesFilter)
        self.edtBegDateClientDiseasesFilter.setCalendarPopup(True)
        self.edtBegDateClientDiseasesFilter.setObjectName(_fromUtf8("edtBegDateClientDiseasesFilter"))
        self._14.addWidget(self.edtBegDateClientDiseasesFilter, 0, 1, 1, 1)
        self.btnButtonBoxClientDiseasesFilter = QtGui.QDialogButtonBox(self.frmClientDiseasesFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnButtonBoxClientDiseasesFilter.sizePolicy().hasHeightForWidth())
        self.btnButtonBoxClientDiseasesFilter.setSizePolicy(sizePolicy)
        self.btnButtonBoxClientDiseasesFilter.setOrientation(QtCore.Qt.Horizontal)
        self.btnButtonBoxClientDiseasesFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.btnButtonBoxClientDiseasesFilter.setObjectName(_fromUtf8("btnButtonBoxClientDiseasesFilter"))
        self._14.addWidget(self.btnButtonBoxClientDiseasesFilter, 0, 12, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._14.addItem(spacerItem2, 0, 11, 1, 1)
        self.cmbMKBToClientDiseasesFilter = CICDCodeEditFocusEvent(self.frmClientDiseasesFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMKBToClientDiseasesFilter.sizePolicy().hasHeightForWidth())
        self.cmbMKBToClientDiseasesFilter.setSizePolicy(sizePolicy)
        self.cmbMKBToClientDiseasesFilter.setObjectName(_fromUtf8("cmbMKBToClientDiseasesFilter"))
        self._14.addWidget(self.cmbMKBToClientDiseasesFilter, 0, 7, 1, 1)
        self.cmbMKBFromClientDiseasesFilter = CICDCodeEditFocusEvent(self.frmClientDiseasesFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMKBFromClientDiseasesFilter.sizePolicy().hasHeightForWidth())
        self.cmbMKBFromClientDiseasesFilter.setSizePolicy(sizePolicy)
        self.cmbMKBFromClientDiseasesFilter.setObjectName(_fromUtf8("cmbMKBFromClientDiseasesFilter"))
        self._14.addWidget(self.cmbMKBFromClientDiseasesFilter, 0, 6, 1, 1)
        self.gridLayout_29.addWidget(self.frmClientDiseasesFilter, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.splitter_13, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabInfectionDiseases, _fromUtf8(""))
        self.tabVaccinations = QtGui.QWidget()
        self.tabVaccinations.setObjectName(_fromUtf8("tabVaccinations"))
        self.gridLayout_31 = QtGui.QGridLayout(self.tabVaccinations)
        self.gridLayout_31.setMargin(1)
        self.gridLayout_31.setSpacing(1)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.splitter_10 = QtGui.QSplitter(self.tabVaccinations)
        self.splitter_10.setOrientation(QtCore.Qt.Vertical)
        self.splitter_10.setObjectName(_fromUtf8("splitter_10"))
        self.groupBox_4 = QtGui.QGroupBox(self.splitter_10)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_25 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_25.setMargin(1)
        self.gridLayout_25.setSpacing(1)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.splitter_11 = QtGui.QSplitter(self.groupBox_4)
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName(_fromUtf8("splitter_11"))
        self.splitter_12 = QtGui.QSplitter(self.splitter_11)
        self.splitter_12.setOrientation(QtCore.Qt.Vertical)
        self.splitter_12.setObjectName(_fromUtf8("splitter_12"))
        self.tblVaccinations = CInDocTableView(self.splitter_12)
        self.tblVaccinations.setObjectName(_fromUtf8("tblVaccinations"))
        self.gridLayout_25.addWidget(self.splitter_11, 0, 0, 1, 1)
        self.tabVaccinationsFilter = QtGui.QWidget(self.splitter_10)
        self.tabVaccinationsFilter.setObjectName(_fromUtf8("tabVaccinationsFilter"))
        self.gridLayout_27 = QtGui.QGridLayout(self.tabVaccinationsFilter)
        self.gridLayout_27.setMargin(1)
        self.gridLayout_27.setSpacing(1)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.splitterVaccinationsFilter = QtGui.QSplitter(self.tabVaccinationsFilter)
        self.splitterVaccinationsFilter.setOrientation(QtCore.Qt.Horizontal)
        self.splitterVaccinationsFilter.setObjectName(_fromUtf8("splitterVaccinationsFilter"))
        self.tblClientVaccinations = CInDocTableView(self.splitterVaccinationsFilter)
        self.tblClientVaccinations.setObjectName(_fromUtf8("tblClientVaccinations"))
        self.gridLayout_27.addWidget(self.splitterVaccinationsFilter, 1, 0, 1, 1)
        self.frmClientVaccinationsFilter = QtGui.QGroupBox(self.tabVaccinationsFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmClientVaccinationsFilter.sizePolicy().hasHeightForWidth())
        self.frmClientVaccinationsFilter.setSizePolicy(sizePolicy)
        self.frmClientVaccinationsFilter.setObjectName(_fromUtf8("frmClientVaccinationsFilter"))
        self._13 = QtGui.QGridLayout(self.frmClientVaccinationsFilter)
        self._13.setMargin(4)
        self._13.setHorizontalSpacing(11)
        self._13.setVerticalSpacing(4)
        self._13.setObjectName(_fromUtf8("_13"))
        self.lblBegDateVaccinationsFilter = QtGui.QLabel(self.frmClientVaccinationsFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDateVaccinationsFilter.sizePolicy().hasHeightForWidth())
        self.lblBegDateVaccinationsFilter.setSizePolicy(sizePolicy)
        self.lblBegDateVaccinationsFilter.setObjectName(_fromUtf8("lblBegDateVaccinationsFilter"))
        self._13.addWidget(self.lblBegDateVaccinationsFilter, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._13.addItem(spacerItem3, 0, 7, 1, 1)
        self.btnButtonBoxClientVaccinationsFilter = QtGui.QDialogButtonBox(self.frmClientVaccinationsFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnButtonBoxClientVaccinationsFilter.sizePolicy().hasHeightForWidth())
        self.btnButtonBoxClientVaccinationsFilter.setSizePolicy(sizePolicy)
        self.btnButtonBoxClientVaccinationsFilter.setOrientation(QtCore.Qt.Horizontal)
        self.btnButtonBoxClientVaccinationsFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.btnButtonBoxClientVaccinationsFilter.setObjectName(_fromUtf8("btnButtonBoxClientVaccinationsFilter"))
        self._13.addWidget(self.btnButtonBoxClientVaccinationsFilter, 0, 9, 1, 1)
        self.edtEndDateClientVaccinationsFilter = CF090DateEdit(self.frmClientVaccinationsFilter)
        self.edtEndDateClientVaccinationsFilter.setCalendarPopup(True)
        self.edtEndDateClientVaccinationsFilter.setObjectName(_fromUtf8("edtEndDateClientVaccinationsFilter"))
        self._13.addWidget(self.edtEndDateClientVaccinationsFilter, 0, 3, 1, 1)
        self.chkExecActionsClientVaccinationsFilter = QtGui.QCheckBox(self.frmClientVaccinationsFilter)
        self.chkExecActionsClientVaccinationsFilter.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkExecActionsClientVaccinationsFilter.setChecked(True)
        self.chkExecActionsClientVaccinationsFilter.setObjectName(_fromUtf8("chkExecActionsClientVaccinationsFilter"))
        self._13.addWidget(self.chkExecActionsClientVaccinationsFilter, 0, 4, 1, 1)
        self.lblEndDateVaccinationsFilter = QtGui.QLabel(self.frmClientVaccinationsFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDateVaccinationsFilter.sizePolicy().hasHeightForWidth())
        self.lblEndDateVaccinationsFilter.setSizePolicy(sizePolicy)
        self.lblEndDateVaccinationsFilter.setObjectName(_fromUtf8("lblEndDateVaccinationsFilter"))
        self._13.addWidget(self.lblEndDateVaccinationsFilter, 0, 2, 1, 1)
        self.edtBegDateClientVaccinationsFilter = CF090DateEdit(self.frmClientVaccinationsFilter)
        self.edtBegDateClientVaccinationsFilter.setCalendarPopup(True)
        self.edtBegDateClientVaccinationsFilter.setObjectName(_fromUtf8("edtBegDateClientVaccinationsFilter"))
        self._13.addWidget(self.edtBegDateClientVaccinationsFilter, 0, 1, 1, 1)
        self.btnInfectionsClientVaccinationsFilter = QtGui.QPushButton(self.frmClientVaccinationsFilter)
        self.btnInfectionsClientVaccinationsFilter.setEnabled(False)
        self.btnInfectionsClientVaccinationsFilter.setObjectName(_fromUtf8("btnInfectionsClientVaccinationsFilter"))
        self._13.addWidget(self.btnInfectionsClientVaccinationsFilter, 0, 5, 1, 1)
        self.lblInfectionList = QtGui.QLabel(self.frmClientVaccinationsFilter)
        self.lblInfectionList.setText(_fromUtf8(""))
        self.lblInfectionList.setObjectName(_fromUtf8("lblInfectionList"))
        self._13.addWidget(self.lblInfectionList, 0, 6, 1, 1)
        self.gridLayout_27.addWidget(self.frmClientVaccinationsFilter, 0, 0, 1, 1)
        self.gridLayout_31.addWidget(self.splitter_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabVaccinations, _fromUtf8(""))
        self.tabStatusActions = QtGui.QWidget()
        self.tabStatusActions.setObjectName(_fromUtf8("tabStatusActions"))
        self.gridLayout_32 = QtGui.QGridLayout(self.tabStatusActions)
        self.gridLayout_32.setMargin(1)
        self.gridLayout_32.setSpacing(1)
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.splitter_6 = QtGui.QSplitter(self.tabStatusActions)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.groupBox_3 = QtGui.QGroupBox(self.splitter_6)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_24 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_24.setMargin(1)
        self.gridLayout_24.setSpacing(1)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.splitter_8 = QtGui.QSplitter(self.groupBox_3)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName(_fromUtf8("splitter_8"))
        self.splitter_9 = QtGui.QSplitter(self.splitter_8)
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName(_fromUtf8("splitter_9"))
        self.tblStatusActions = CInDocTableView(self.splitter_9)
        self.tblStatusActions.setObjectName(_fromUtf8("tblStatusActions"))
        self.tblStatusActionProperties = CActionPropertiesTableView(self.splitter_8)
        self.tblStatusActionProperties.setObjectName(_fromUtf8("tblStatusActionProperties"))
        self.gridLayout_24.addWidget(self.splitter_8, 0, 0, 1, 1)
        self.tabStatusActionFilter = QtGui.QWidget(self.splitter_6)
        self.tabStatusActionFilter.setObjectName(_fromUtf8("tabStatusActionFilter"))
        self.gridLayout_26 = QtGui.QGridLayout(self.tabStatusActionFilter)
        self.gridLayout_26.setMargin(1)
        self.gridLayout_26.setSpacing(1)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.frmClientStatusActionsFilter = QtGui.QGroupBox(self.tabStatusActionFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmClientStatusActionsFilter.sizePolicy().hasHeightForWidth())
        self.frmClientStatusActionsFilter.setSizePolicy(sizePolicy)
        self.frmClientStatusActionsFilter.setObjectName(_fromUtf8("frmClientStatusActionsFilter"))
        self._12 = QtGui.QGridLayout(self.frmClientStatusActionsFilter)
        self._12.setMargin(4)
        self._12.setHorizontalSpacing(11)
        self._12.setVerticalSpacing(4)
        self._12.setObjectName(_fromUtf8("_12"))
        self.edtBegDateClientStatusActionsFilter = CF090DateEdit(self.frmClientStatusActionsFilter)
        self.edtBegDateClientStatusActionsFilter.setCalendarPopup(True)
        self.edtBegDateClientStatusActionsFilter.setObjectName(_fromUtf8("edtBegDateClientStatusActionsFilter"))
        self._12.addWidget(self.edtBegDateClientStatusActionsFilter, 0, 1, 1, 1)
        self.lblEndDateStatusActionFilter = QtGui.QLabel(self.frmClientStatusActionsFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDateStatusActionFilter.sizePolicy().hasHeightForWidth())
        self.lblEndDateStatusActionFilter.setSizePolicy(sizePolicy)
        self.lblEndDateStatusActionFilter.setObjectName(_fromUtf8("lblEndDateStatusActionFilter"))
        self._12.addWidget(self.lblEndDateStatusActionFilter, 0, 2, 1, 1)
        self.lblBegDateStatusActionFilter = QtGui.QLabel(self.frmClientStatusActionsFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDateStatusActionFilter.sizePolicy().hasHeightForWidth())
        self.lblBegDateStatusActionFilter.setSizePolicy(sizePolicy)
        self.lblBegDateStatusActionFilter.setObjectName(_fromUtf8("lblBegDateStatusActionFilter"))
        self._12.addWidget(self.lblBegDateStatusActionFilter, 0, 0, 1, 1)
        self.edtEndDateClientStatusActionsFilter = CF090DateEdit(self.frmClientStatusActionsFilter)
        self.edtEndDateClientStatusActionsFilter.setCalendarPopup(True)
        self.edtEndDateClientStatusActionsFilter.setObjectName(_fromUtf8("edtEndDateClientStatusActionsFilter"))
        self._12.addWidget(self.edtEndDateClientStatusActionsFilter, 0, 3, 1, 1)
        self.btnButtonBoxClientStatusActionsFilter = QtGui.QDialogButtonBox(self.frmClientStatusActionsFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnButtonBoxClientStatusActionsFilter.sizePolicy().hasHeightForWidth())
        self.btnButtonBoxClientStatusActionsFilter.setSizePolicy(sizePolicy)
        self.btnButtonBoxClientStatusActionsFilter.setOrientation(QtCore.Qt.Horizontal)
        self.btnButtonBoxClientStatusActionsFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.btnButtonBoxClientStatusActionsFilter.setObjectName(_fromUtf8("btnButtonBoxClientStatusActionsFilter"))
        self._12.addWidget(self.btnButtonBoxClientStatusActionsFilter, 0, 8, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(16, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._12.addItem(spacerItem4, 0, 5, 1, 1)
        self.chkExecActionsClientStatusActionsFilter = QtGui.QCheckBox(self.frmClientStatusActionsFilter)
        self.chkExecActionsClientStatusActionsFilter.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkExecActionsClientStatusActionsFilter.setChecked(True)
        self.chkExecActionsClientStatusActionsFilter.setObjectName(_fromUtf8("chkExecActionsClientStatusActionsFilter"))
        self._12.addWidget(self.chkExecActionsClientStatusActionsFilter, 0, 4, 1, 1)
        self.gridLayout_26.addWidget(self.frmClientStatusActionsFilter, 0, 0, 1, 1)
        self.splitterStatusActionFilter = QtGui.QSplitter(self.tabStatusActionFilter)
        self.splitterStatusActionFilter.setOrientation(QtCore.Qt.Horizontal)
        self.splitterStatusActionFilter.setObjectName(_fromUtf8("splitterStatusActionFilter"))
        self.tblClientStatusActions = CRegistryActionsTableView(self.splitterStatusActionFilter)
        self.tblClientStatusActions.setObjectName(_fromUtf8("tblClientStatusActions"))
        self.tblClientStatusActionProperties = CActionPropertiesTableView(self.splitterStatusActionFilter)
        self.tblClientStatusActionProperties.setObjectName(_fromUtf8("tblClientStatusActionProperties"))
        self.gridLayout_26.addWidget(self.splitterStatusActionFilter, 1, 0, 1, 1)
        self.gridLayout_32.addWidget(self.splitter_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabStatusActions, _fromUtf8(""))
        self.tabDiagnosticActions = QtGui.QWidget()
        self.tabDiagnosticActions.setObjectName(_fromUtf8("tabDiagnosticActions"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tabDiagnosticActions)
        self.gridLayout_23.setMargin(1)
        self.gridLayout_23.setSpacing(1)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.splitter_3 = QtGui.QSplitter(self.tabDiagnosticActions)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.groupBox = QtGui.QGroupBox(self.splitter_3)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_18.setMargin(1)
        self.gridLayout_18.setSpacing(1)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.splitter_2 = QtGui.QSplitter(self.groupBox)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tblLabDiagnosticActions = CInDocTableView(self.splitter)
        self.tblLabDiagnosticActions.setObjectName(_fromUtf8("tblLabDiagnosticActions"))
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_17.setMargin(1)
        self.gridLayout_17.setSpacing(1)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.tblToolDiagnosticActions = CInDocTableView(self.groupBox_2)
        self.tblToolDiagnosticActions.setObjectName(_fromUtf8("tblToolDiagnosticActions"))
        self.gridLayout_17.addWidget(self.tblToolDiagnosticActions, 0, 0, 1, 1)
        self.tblDiagnosticActionProperties = CActionPropertiesTableView(self.splitter_2)
        self.tblDiagnosticActionProperties.setObjectName(_fromUtf8("tblDiagnosticActionProperties"))
        self.gridLayout_18.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.tabDiagnosticActionFilter = QtGui.QWidget(self.splitter_3)
        self.tabDiagnosticActionFilter.setObjectName(_fromUtf8("tabDiagnosticActionFilter"))
        self.gridLayout_22 = QtGui.QGridLayout(self.tabDiagnosticActionFilter)
        self.gridLayout_22.setMargin(1)
        self.gridLayout_22.setSpacing(1)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.frmDiagnosticActionsFilter = QtGui.QGroupBox(self.tabDiagnosticActionFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmDiagnosticActionsFilter.sizePolicy().hasHeightForWidth())
        self.frmDiagnosticActionsFilter.setSizePolicy(sizePolicy)
        self.frmDiagnosticActionsFilter.setObjectName(_fromUtf8("frmDiagnosticActionsFilter"))
        self._11 = QtGui.QGridLayout(self.frmDiagnosticActionsFilter)
        self._11.setMargin(4)
        self._11.setHorizontalSpacing(11)
        self._11.setVerticalSpacing(4)
        self._11.setObjectName(_fromUtf8("_11"))
        self.lblBegDateDiagnosticActionFilter = QtGui.QLabel(self.frmDiagnosticActionsFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBegDateDiagnosticActionFilter.sizePolicy().hasHeightForWidth())
        self.lblBegDateDiagnosticActionFilter.setSizePolicy(sizePolicy)
        self.lblBegDateDiagnosticActionFilter.setObjectName(_fromUtf8("lblBegDateDiagnosticActionFilter"))
        self._11.addWidget(self.lblBegDateDiagnosticActionFilter, 0, 0, 1, 1)
        self.btnButtonBoxDiagnosticActionsFilter = QtGui.QDialogButtonBox(self.frmDiagnosticActionsFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnButtonBoxDiagnosticActionsFilter.sizePolicy().hasHeightForWidth())
        self.btnButtonBoxDiagnosticActionsFilter.setSizePolicy(sizePolicy)
        self.btnButtonBoxDiagnosticActionsFilter.setOrientation(QtCore.Qt.Horizontal)
        self.btnButtonBoxDiagnosticActionsFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.btnButtonBoxDiagnosticActionsFilter.setObjectName(_fromUtf8("btnButtonBoxDiagnosticActionsFilter"))
        self._11.addWidget(self.btnButtonBoxDiagnosticActionsFilter, 0, 8, 1, 1)
        self.lblEndDateDiagnosticActionFilter = QtGui.QLabel(self.frmDiagnosticActionsFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndDateDiagnosticActionFilter.sizePolicy().hasHeightForWidth())
        self.lblEndDateDiagnosticActionFilter.setSizePolicy(sizePolicy)
        self.lblEndDateDiagnosticActionFilter.setObjectName(_fromUtf8("lblEndDateDiagnosticActionFilter"))
        self._11.addWidget(self.lblEndDateDiagnosticActionFilter, 0, 2, 1, 1)
        self.edtEndDateDiagnosticActionsFilter = CF090DateEdit(self.frmDiagnosticActionsFilter)
        self.edtEndDateDiagnosticActionsFilter.setCalendarPopup(True)
        self.edtEndDateDiagnosticActionsFilter.setObjectName(_fromUtf8("edtEndDateDiagnosticActionsFilter"))
        self._11.addWidget(self.edtEndDateDiagnosticActionsFilter, 0, 3, 1, 1)
        self.edtBegDateDiagnosticActionsFilter = CF090DateEdit(self.frmDiagnosticActionsFilter)
        self.edtBegDateDiagnosticActionsFilter.setCalendarPopup(True)
        self.edtBegDateDiagnosticActionsFilter.setObjectName(_fromUtf8("edtBegDateDiagnosticActionsFilter"))
        self._11.addWidget(self.edtBegDateDiagnosticActionsFilter, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(16, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._11.addItem(spacerItem5, 0, 5, 1, 1)
        self.chkExecActionsDiagnosticActionsFilter = QtGui.QCheckBox(self.frmDiagnosticActionsFilter)
        self.chkExecActionsDiagnosticActionsFilter.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkExecActionsDiagnosticActionsFilter.setChecked(True)
        self.chkExecActionsDiagnosticActionsFilter.setObjectName(_fromUtf8("chkExecActionsDiagnosticActionsFilter"))
        self._11.addWidget(self.chkExecActionsDiagnosticActionsFilter, 0, 4, 1, 1)
        self.gridLayout_22.addWidget(self.frmDiagnosticActionsFilter, 0, 0, 1, 1)
        self.splitterDiagnosticActionFilter = QtGui.QSplitter(self.tabDiagnosticActionFilter)
        self.splitterDiagnosticActionFilter.setOrientation(QtCore.Qt.Horizontal)
        self.splitterDiagnosticActionFilter.setObjectName(_fromUtf8("splitterDiagnosticActionFilter"))
        self.tblClientDiagnosticActions = CRegistryActionsTableView(self.splitterDiagnosticActionFilter)
        self.tblClientDiagnosticActions.setObjectName(_fromUtf8("tblClientDiagnosticActions"))
        self.tblClientDiagnosticActionProperties = CActionPropertiesTableView(self.splitterDiagnosticActionFilter)
        self.tblClientDiagnosticActionProperties.setObjectName(_fromUtf8("tblClientDiagnosticActionProperties"))
        self.gridLayout_22.addWidget(self.splitterDiagnosticActionFilter, 1, 0, 1, 1)
        self.gridLayout_23.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabDiagnosticActions, _fromUtf8(""))
        self.tabCommission = QtGui.QWidget()
        self.tabCommission.setObjectName(_fromUtf8("tabCommission"))
        self.gridLayout_53 = QtGui.QGridLayout(self.tabCommission)
        self.gridLayout_53.setMargin(1)
        self.gridLayout_53.setSpacing(1)
        self.gridLayout_53.setObjectName(_fromUtf8("gridLayout_53"))
        self.tblMembersMSIPerson = CInDocTableView(self.tabCommission)
        self.tblMembersMSIPerson.setObjectName(_fromUtf8("tblMembersMSIPerson"))
        self.gridLayout_53.addWidget(self.tblMembersMSIPerson, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tabCommission, _fromUtf8(""))
        self.tabResult = QtGui.QWidget()
        self.tabResult.setObjectName(_fromUtf8("tabResult"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabResult)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.grpInspectionsResult = QtGui.QGroupBox(self.tabResult)
        self.grpInspectionsResult.setObjectName(_fromUtf8("grpInspectionsResult"))
        self._5 = QtGui.QVBoxLayout(self.grpInspectionsResult)
        self._5.setMargin(1)
        self._5.setSpacing(1)
        self._5.setObjectName(_fromUtf8("_5"))
        self.tblInspectionsResult = CInspectionsResultInDocTableView(self.grpInspectionsResult)
        self.tblInspectionsResult.setObjectName(_fromUtf8("tblInspectionsResult"))
        self._5.addWidget(self.tblInspectionsResult)
        self.gridLayout_7.addWidget(self.grpInspectionsResult, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem6, 8, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblInfoResult = QtGui.QLabel(self.tabResult)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInfoResult.sizePolicy().hasHeightForWidth())
        self.lblInfoResult.setSizePolicy(sizePolicy)
        self.lblInfoResult.setObjectName(_fromUtf8("lblInfoResult"))
        self.gridLayout.addWidget(self.lblInfoResult, 0, 0, 1, 1)
        self.cmbInfoResult = CStrComboBox(self.tabResult)
        self.cmbInfoResult.setObjectName(_fromUtf8("cmbInfoResult"))
        self.gridLayout.addWidget(self.cmbInfoResult, 0, 1, 1, 1)
        self.line_16 = QtGui.QFrame(self.tabResult)
        self.line_16.setFrameShadow(QtGui.QFrame.Plain)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.gridLayout.addWidget(self.line_16, 1, 0, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setMargin(4)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.lblVisitDateNextResult = QtGui.QLabel(self.tabResult)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblVisitDateNextResult.sizePolicy().hasHeightForWidth())
        self.lblVisitDateNextResult.setSizePolicy(sizePolicy)
        self.lblVisitDateNextResult.setObjectName(_fromUtf8("lblVisitDateNextResult"))
        self.gridLayout_15.addWidget(self.lblVisitDateNextResult, 0, 0, 1, 1)
        self.edtVisitDateNextResult = CDateEdit(self.tabResult)
        self.edtVisitDateNextResult.setCalendarPopup(True)
        self.edtVisitDateNextResult.setObjectName(_fromUtf8("edtVisitDateNextResult"))
        self.gridLayout_15.addWidget(self.edtVisitDateNextResult, 0, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(478, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem7, 0, 2, 1, 1)
        self.line_20 = QtGui.QFrame(self.tabResult)
        self.line_20.setFrameShadow(QtGui.QFrame.Plain)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.gridLayout_15.addWidget(self.line_20, 1, 0, 1, 3)
        self.gridLayout_7.addLayout(self.gridLayout_15, 5, 0, 1, 1)
        self.lblCommentResult = QtGui.QLabel(self.tabResult)
        self.lblCommentResult.setObjectName(_fromUtf8("lblCommentResult"))
        self.gridLayout_7.addWidget(self.lblCommentResult, 6, 0, 1, 1)
        self.edtCommentResult = QtGui.QTextEdit(self.tabResult)
        self.edtCommentResult.setObjectName(_fromUtf8("edtCommentResult"))
        self.gridLayout_7.addWidget(self.edtCommentResult, 7, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.tabResult)
        self.line_4.setFrameShadow(QtGui.QFrame.Plain)
        self.line_4.setLineWidth(1)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_7.addWidget(self.line_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabResult, _fromUtf8(""))
        self.tabExport = QtGui.QWidget()
        self.tabExport.setObjectName(_fromUtf8("tabExport"))
        self.gridLayout_55 = QtGui.QGridLayout(self.tabExport)
        self.gridLayout_55.setMargin(1)
        self.gridLayout_55.setSpacing(1)
        self.gridLayout_55.setObjectName(_fromUtf8("gridLayout_55"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tabExport)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.tblExport = CInDocExportTableView(self.tab_3)
        self.tblExport.setObjectName(_fromUtf8("tblExport"))
        self.horizontalLayout_12.addWidget(self.tblExport)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.tblExport_FileAttach = CInDocExportTableView(self.tab)
        self.tblExport_FileAttach.setObjectName(_fromUtf8("tblExport_FileAttach"))
        self.horizontalLayout_20.addWidget(self.tblExport_FileAttach)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.tblExport_VIMIS = CInDocExportTableView(self.tab_2)
        self.tblExport_VIMIS.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tblExport_VIMIS.setSizeIncrement(QtCore.QSize(0, -1))
        self.tblExport_VIMIS.setBaseSize(QtCore.QSize(0, -1))
        self.tblExport_VIMIS.setObjectName(_fromUtf8("tblExport_VIMIS"))
        self.horizontalLayout_21.addWidget(self.tblExport_VIMIS)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_55.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabExport, _fromUtf8(""))
        self.tabNotes = CEventNotesPageEx()
        self.tabNotes.setObjectName(_fromUtf8("tabNotes"))
        self.tabWidget.addTab(self.tabNotes, _fromUtf8(""))
        self.gridLayout_63.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.splitter_7, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(F090Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lbEndDate.setBuddy(self.edtEndDate)
        self.lblAmount.setBuddy(self.edtAmount)
        self.lblUet.setBuddy(self.edtUet)
        self.lblOffice.setBuddy(self.edtOffice)
        self.lblNote.setBuddy(self.edtNote)
        self.lblStatus.setBuddy(self.cmbStatus)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblAPDirectionDate.setBuddy(self.edtDirectionDate)
        self.lblAssistant.setBuddy(self.cmbAssistant)
        self.lblSetPerson.setBuddy(self.cmbSetPerson)
        self.lblPlannedEndDate.setBuddy(self.edtPlannedEndDate)

        self.retranslateUi(F090Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), F090Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), F090Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(F090Dialog)
        F090Dialog.setTabOrder(self.buttonBox, self.scrollArea)
        F090Dialog.setTabOrder(self.scrollArea, self.edtDirectionDate)
        F090Dialog.setTabOrder(self.edtDirectionDate, self.edtDirectionTime)
        F090Dialog.setTabOrder(self.edtDirectionTime, self.chkIsUrgent)
        F090Dialog.setTabOrder(self.chkIsUrgent, self.cmbSetPerson)
        F090Dialog.setTabOrder(self.cmbSetPerson, self.edtPlannedEndDate)
        F090Dialog.setTabOrder(self.edtPlannedEndDate, self.cmbOrg)
        F090Dialog.setTabOrder(self.cmbOrg, self.btnSelectOrg)
        F090Dialog.setTabOrder(self.btnSelectOrg, self.cmbStatus)
        F090Dialog.setTabOrder(self.cmbStatus, self.edtBegDate)
        F090Dialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        F090Dialog.setTabOrder(self.edtBegTime, self.edtAmount)
        F090Dialog.setTabOrder(self.edtAmount, self.edtUet)
        F090Dialog.setTabOrder(self.edtUet, self.cmbPerson)
        F090Dialog.setTabOrder(self.cmbPerson, self.cmbAssistant)
        F090Dialog.setTabOrder(self.cmbAssistant, self.edtNote)
        F090Dialog.setTabOrder(self.edtNote, self.tabWidget)
        F090Dialog.setTabOrder(self.tabWidget, self.cmbHurtType)
        F090Dialog.setTabOrder(self.cmbHurtType, self.edtElectronicMedicalBookNumber)
        F090Dialog.setTabOrder(self.edtElectronicMedicalBookNumber, self.tblInfectionDiseases)
        F090Dialog.setTabOrder(self.tblInfectionDiseases, self.edtBegDateClientDiseasesFilter)
        F090Dialog.setTabOrder(self.edtBegDateClientDiseasesFilter, self.edtEndDateClientDiseasesFilter)
        F090Dialog.setTabOrder(self.edtEndDateClientDiseasesFilter, self.chkExecActionsClientDiseasesFilter)
        F090Dialog.setTabOrder(self.chkExecActionsClientDiseasesFilter, self.cmbMKBFromClientDiseasesFilter)
        F090Dialog.setTabOrder(self.cmbMKBFromClientDiseasesFilter, self.cmbMKBToClientDiseasesFilter)
        F090Dialog.setTabOrder(self.cmbMKBToClientDiseasesFilter, self.chkPreliminaryClientDiseasesFilter)
        F090Dialog.setTabOrder(self.chkPreliminaryClientDiseasesFilter, self.chkConcomitantClientDiseasesFilter)
        F090Dialog.setTabOrder(self.chkConcomitantClientDiseasesFilter, self.btnButtonBoxClientDiseasesFilter)
        F090Dialog.setTabOrder(self.btnButtonBoxClientDiseasesFilter, self.tblClientDiseases)
        F090Dialog.setTabOrder(self.tblClientDiseases, self.tblVaccinations)
        F090Dialog.setTabOrder(self.tblVaccinations, self.edtBegDateClientVaccinationsFilter)
        F090Dialog.setTabOrder(self.edtBegDateClientVaccinationsFilter, self.edtEndDateClientVaccinationsFilter)
        F090Dialog.setTabOrder(self.edtEndDateClientVaccinationsFilter, self.chkExecActionsClientVaccinationsFilter)
        F090Dialog.setTabOrder(self.chkExecActionsClientVaccinationsFilter, self.btnButtonBoxClientVaccinationsFilter)
        F090Dialog.setTabOrder(self.btnButtonBoxClientVaccinationsFilter, self.tblClientVaccinations)
        F090Dialog.setTabOrder(self.tblClientVaccinations, self.tblStatusActions)
        F090Dialog.setTabOrder(self.tblStatusActions, self.tblStatusActionProperties)
        F090Dialog.setTabOrder(self.tblStatusActionProperties, self.edtBegDateClientStatusActionsFilter)
        F090Dialog.setTabOrder(self.edtBegDateClientStatusActionsFilter, self.edtEndDateClientStatusActionsFilter)
        F090Dialog.setTabOrder(self.edtEndDateClientStatusActionsFilter, self.btnButtonBoxClientStatusActionsFilter)
        F090Dialog.setTabOrder(self.btnButtonBoxClientStatusActionsFilter, self.tblClientStatusActions)
        F090Dialog.setTabOrder(self.tblClientStatusActions, self.tblClientStatusActionProperties)
        F090Dialog.setTabOrder(self.tblClientStatusActionProperties, self.tblLabDiagnosticActions)
        F090Dialog.setTabOrder(self.tblLabDiagnosticActions, self.tblDiagnosticActionProperties)
        F090Dialog.setTabOrder(self.tblDiagnosticActionProperties, self.tblToolDiagnosticActions)
        F090Dialog.setTabOrder(self.tblToolDiagnosticActions, self.edtBegDateDiagnosticActionsFilter)
        F090Dialog.setTabOrder(self.edtBegDateDiagnosticActionsFilter, self.edtEndDateDiagnosticActionsFilter)
        F090Dialog.setTabOrder(self.edtEndDateDiagnosticActionsFilter, self.btnButtonBoxDiagnosticActionsFilter)
        F090Dialog.setTabOrder(self.btnButtonBoxDiagnosticActionsFilter, self.tblClientDiagnosticActions)
        F090Dialog.setTabOrder(self.tblClientDiagnosticActions, self.tblClientDiagnosticActionProperties)
        F090Dialog.setTabOrder(self.tblClientDiagnosticActionProperties, self.tblMembersMSIPerson)
        F090Dialog.setTabOrder(self.tblMembersMSIPerson, self.cmbInfoResult)
        F090Dialog.setTabOrder(self.cmbInfoResult, self.edtVisitDateNextResult)
        F090Dialog.setTabOrder(self.edtVisitDateNextResult, self.edtCommentResult)
        F090Dialog.setTabOrder(self.edtCommentResult, self.edtOffice)
        F090Dialog.setTabOrder(self.edtOffice, self.edtPlannedEndTime)
        F090Dialog.setTabOrder(self.edtPlannedEndTime, self.edtEndDate)
        F090Dialog.setTabOrder(self.edtEndDate, self.edtEndTime)

    def retranslateUi(self, F090Dialog):
        F090Dialog.setWindowTitle(_translate("F090Dialog", "Dialog", None))
        self.txtClientInfoBrowser.setWhatsThis(_translate("F090Dialog", "Описание пациента", None))
        self.txtClientInfoBrowser.setHtml(_translate("F090Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>", None))
        self.lblBegDate.setText(_translate("F090Dialog", "Начато", None))
        self.edtBegDate.setWhatsThis(_translate("F090Dialog", "дата окончания осмотра", None))
        self.edtBegTime.setDisplayFormat(_translate("F090Dialog", "HH:mm", None))
        self.lbEndDate.setText(_translate("F090Dialog", "Выполнено", None))
        self.edtEndTime.setDisplayFormat(_translate("F090Dialog", "HH:mm", None))
        self.lblAmount.setText(_translate("F090Dialog", "Количество", None))
        self.lblUet.setText(_translate("F090Dialog", "УЕТ", None))
        self.lblOffice.setText(_translate("F090Dialog", "Кабинет", None))
        self.cmbOrg.setItemText(0, _translate("F090Dialog", "Организация", None))
        self.cmbPerson.setItemText(0, _translate("F090Dialog", "Врач", None))
        self.lblNote.setText(_translate("F090Dialog", "Примечания", None))
        self.lblStatus.setText(_translate("F090Dialog", "Состояние", None))
        self.cmbAssistant.setItemText(0, _translate("F090Dialog", "Врач", None))
        self.lblPerson.setText(_translate("F090Dialog", "Исполнитель", None))
        self.lblOrg.setText(_translate("F090Dialog", "Место выполнения", None))
        self.lblAPDirectionDate.setText(_translate("F090Dialog", "Назначено", None))
        self.btnSelectOrg.setText(_translate("F090Dialog", "...", None))
        self.lblAssistant.setText(_translate("F090Dialog", "Ассистент", None))
        self.edtDirectionDate.setWhatsThis(_translate("F090Dialog", "дата начала осмотра", None))
        self.edtDirectionTime.setDisplayFormat(_translate("F090Dialog", "HH:mm", None))
        self.chkIsUrgent.setText(_translate("F090Dialog", "Срочно", None))
        self.lblSetPerson.setText(_translate("F090Dialog", "Назначил", None))
        self.cmbSetPerson.setItemText(0, _translate("F090Dialog", "Врач", None))
        self.lblPlannedEndDate.setText(_translate("F090Dialog", "План", None))
        self.edtPlannedEndTime.setDisplayFormat(_translate("F090Dialog", "HH:mm", None))
        self.lblNameExecActions.setText(_translate("F090Dialog", "Наименование выполняемых работ", None))
        self.lblElectronicMedicalBookNumber.setText(_translate("F090Dialog", "Номер личной медицинской книжки", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMainInformation), _translate("F090Dialog", " Основная информация", None))
        self.groupBox_5.setTitle(_translate("F090Dialog", "Инфекционные заболевания", None))
        self.frmClientDiseasesFilter.setTitle(_translate("F090Dialog", "Фильтр", None))
        self.chkExecActionsClientDiseasesFilter.setText(_translate("F090Dialog", "Учитывать выполняемые работы", None))
        self.lblMKBClientDiseasesFilter.setText(_translate("F090Dialog", "Коды диагнозов по МКБ", None))
        self.chkConcomitantClientDiseasesFilter.setText(_translate("F090Dialog", "Сопутствующие", None))
        self.chkPreliminaryClientDiseasesFilter.setText(_translate("F090Dialog", "Предварительные", None))
        self.edtEndDateClientDiseasesFilter.setDisplayFormat(_translate("F090Dialog", "dd.MM.yyyy", None))
        self.lblEndDateClientDiseasesFilter.setText(_translate("F090Dialog", "По", None))
        self.lblBegDateClientDiseasesFilter.setText(_translate("F090Dialog", "С", None))
        self.edtBegDateClientDiseasesFilter.setDisplayFormat(_translate("F090Dialog", "dd.MM.yyyy", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInfectionDiseases), _translate("F090Dialog", "Инфекционные заболевания", None))
        self.groupBox_4.setTitle(_translate("F090Dialog", "Профилактические прививки", None))
        self.frmClientVaccinationsFilter.setTitle(_translate("F090Dialog", "Фильтр", None))
        self.lblBegDateVaccinationsFilter.setText(_translate("F090Dialog", "С", None))
        self.edtEndDateClientVaccinationsFilter.setDisplayFormat(_translate("F090Dialog", "dd.MM.yyyy", None))
        self.chkExecActionsClientVaccinationsFilter.setText(_translate("F090Dialog", "Учитывать выполняемые работы", None))
        self.lblEndDateVaccinationsFilter.setText(_translate("F090Dialog", "По", None))
        self.edtBegDateClientVaccinationsFilter.setDisplayFormat(_translate("F090Dialog", "dd.MM.yyyy", None))
        self.btnInfectionsClientVaccinationsFilter.setText(_translate("F090Dialog", "Инфекции", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVaccinations), _translate("F090Dialog", "Профилактические прививки", None))
        self.groupBox_3.setTitle(_translate("F090Dialog", "Осмотры врачей", None))
        self.frmClientStatusActionsFilter.setTitle(_translate("F090Dialog", "Фильтр", None))
        self.edtBegDateClientStatusActionsFilter.setDisplayFormat(_translate("F090Dialog", "dd.MM.yyyy", None))
        self.lblEndDateStatusActionFilter.setText(_translate("F090Dialog", "По", None))
        self.lblBegDateStatusActionFilter.setText(_translate("F090Dialog", "С", None))
        self.edtEndDateClientStatusActionsFilter.setDisplayFormat(_translate("F090Dialog", "dd.MM.yyyy", None))
        self.chkExecActionsClientStatusActionsFilter.setText(_translate("F090Dialog", "Учитывать выполняемые работы", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatusActions), _translate("F090Dialog", "Осмотры врачей", None))
        self.groupBox.setTitle(_translate("F090Dialog", "Лабораторные исследования", None))
        self.groupBox_2.setTitle(_translate("F090Dialog", "Инструментальные исследования", None))
        self.frmDiagnosticActionsFilter.setTitle(_translate("F090Dialog", "Фильтр", None))
        self.lblBegDateDiagnosticActionFilter.setText(_translate("F090Dialog", "С", None))
        self.lblEndDateDiagnosticActionFilter.setText(_translate("F090Dialog", "По", None))
        self.edtEndDateDiagnosticActionsFilter.setDisplayFormat(_translate("F090Dialog", "dd.MM.yyyy", None))
        self.edtBegDateDiagnosticActionsFilter.setDisplayFormat(_translate("F090Dialog", "dd.MM.yyyy", None))
        self.chkExecActionsDiagnosticActionsFilter.setText(_translate("F090Dialog", "Учитывать выполняемые работы", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDiagnosticActions), _translate("F090Dialog", "Исследования", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCommission), _translate("F090Dialog", "Комиссия", None))
        self.grpInspectionsResult.setTitle(_translate("F090Dialog", "&Осмотр", None))
        self.lblInfoResult.setText(_translate("F090Dialog", "Заключение по результатам медицинского осмотра", None))
        self.lblVisitDateNextResult.setText(_translate("F090Dialog", "Дата проведения очередного периодического медицинского осмотра", None))
        self.lblCommentResult.setText(_translate("F090Dialog", "Комментарий", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabResult), _translate("F090Dialog", "Заключение", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("F090Dialog", "Событие", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("F090Dialog", "Документы", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("F090Dialog", "ВИМИС", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExport), _translate("F090Dialog", "Экспорт", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNotes), _translate("F090Dialog", "Примечание", None))

from Events.ActionPropertiesTable import CActionPropertiesTableView
from Events.ActionStatus import CActionStatusComboBox
from Events.EventNotesPage import CEventNotesPageEx
from F090.F090DateEdit import CF090DateEdit
from F090.F090RBComboBox import CF090RBComboBox
from F090.InspectionsResultInDocTableView import CInspectionsResultInDocTableView
from Orgs.OrgComboBox import CPolyclinicComboBox
from Orgs.PersonComboBoxEx import CPersonWithOrgListComboBoxEx
from Registry.RegistryTable import CRegistryActionsTableView
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEditFocusEvent
from library.InDocTable import CInDocTableView, CInDocExportTableView
from library.ROCheckBox import CROCheckBox
from library.StrComboBox import CStrComboBox
from library.TextBrowser import CTextBrowser
from library.TimeEdit import CTimeEdit
