# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CashRegister.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CCashRegister(object):
    def setupUi(self, CCashRegister):
        CCashRegister.setObjectName(_fromUtf8("CCashRegister"))
        CCashRegister.resize(620, 532)
        self.gridLayout = QtGui.QGridLayout(CCashRegister)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.grpState = QtGui.QGroupBox(CCashRegister)
        self.grpState.setObjectName(_fromUtf8("grpState"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpState)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblModel = QtGui.QLabel(self.grpState)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblModel.sizePolicy().hasHeightForWidth())
        self.lblModel.setSizePolicy(sizePolicy)
        self.lblModel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lblModel.setObjectName(_fromUtf8("lblModel"))
        self.gridLayout_2.addWidget(self.lblModel, 0, 0, 1, 1)
        self.lblModelValue = QtGui.QLabel(self.grpState)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblModelValue.sizePolicy().hasHeightForWidth())
        self.lblModelValue.setSizePolicy(sizePolicy)
        self.lblModelValue.setMinimumSize(QtCore.QSize(100, 0))
        self.lblModelValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblModelValue.setObjectName(_fromUtf8("lblModelValue"))
        self.gridLayout_2.addWidget(self.lblModelValue, 0, 1, 1, 1)
        self.lblOfdExchange = QtGui.QLabel(self.grpState)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOfdExchange.sizePolicy().hasHeightForWidth())
        self.lblOfdExchange.setSizePolicy(sizePolicy)
        self.lblOfdExchange.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lblOfdExchange.setObjectName(_fromUtf8("lblOfdExchange"))
        self.gridLayout_2.addWidget(self.lblOfdExchange, 0, 2, 1, 1)
        self.lblOfdExchangeValue = QtGui.QLabel(self.grpState)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOfdExchangeValue.sizePolicy().hasHeightForWidth())
        self.lblOfdExchangeValue.setSizePolicy(sizePolicy)
        self.lblOfdExchangeValue.setMinimumSize(QtCore.QSize(100, 0))
        self.lblOfdExchangeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblOfdExchangeValue.setObjectName(_fromUtf8("lblOfdExchangeValue"))
        self.gridLayout_2.addWidget(self.lblOfdExchangeValue, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.grpState, 0, 0, 1, 1)
        self.grpSession = QtGui.QGroupBox(CCashRegister)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpSession.sizePolicy().hasHeightForWidth())
        self.grpSession.setSizePolicy(sizePolicy)
        self.grpSession.setObjectName(_fromUtf8("grpSession"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpSession)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnOpenSession = QtGui.QPushButton(self.grpSession)
        self.btnOpenSession.setEnabled(False)
        self.btnOpenSession.setObjectName(_fromUtf8("btnOpenSession"))
        self.gridLayout_3.addWidget(self.btnOpenSession, 0, 0, 1, 1)
        self.btnCloseSession = QtGui.QPushButton(self.grpSession)
        self.btnCloseSession.setEnabled(False)
        self.btnCloseSession.setObjectName(_fromUtf8("btnCloseSession"))
        self.gridLayout_3.addWidget(self.btnCloseSession, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.grpSession, 0, 1, 1, 1)
        self.grpDoc = QtGui.QGroupBox(CCashRegister)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpDoc.sizePolicy().hasHeightForWidth())
        self.grpDoc.setSizePolicy(sizePolicy)
        self.grpDoc.setObjectName(_fromUtf8("grpDoc"))
        self.gridLayout_9 = QtGui.QGridLayout(self.grpDoc)
        self.gridLayout_9.setMargin(4)
        self.gridLayout_9.setSpacing(4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.btnPrintDuplicate = QtGui.QPushButton(self.grpDoc)
        self.btnPrintDuplicate.setEnabled(False)
        self.btnPrintDuplicate.setObjectName(_fromUtf8("btnPrintDuplicate"))
        self.gridLayout_9.addWidget(self.btnPrintDuplicate, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.grpDoc, 0, 2, 1, 1)
        self.tabMain = QtGui.QTabWidget(CCashRegister)
        self.tabMain.setDocumentMode(False)
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tabAccounts = QtGui.QWidget()
        self.tabAccounts.setObjectName(_fromUtf8("tabAccounts"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabAccounts)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblAccounts = CInDocTableView(self.tabAccounts)
        self.tblAccounts.setObjectName(_fromUtf8("tblAccounts"))
        self.gridLayout_5.addWidget(self.tblAccounts, 0, 1, 1, 2)
        self.btnCashPayment = QtGui.QPushButton(self.tabAccounts)
        self.btnCashPayment.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCashPayment.sizePolicy().hasHeightForWidth())
        self.btnCashPayment.setSizePolicy(sizePolicy)
        self.btnCashPayment.setObjectName(_fromUtf8("btnCashPayment"))
        self.gridLayout_5.addWidget(self.btnCashPayment, 1, 1, 1, 1)
        self.btnCardPayment = QtGui.QPushButton(self.tabAccounts)
        self.btnCardPayment.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCardPayment.sizePolicy().hasHeightForWidth())
        self.btnCardPayment.setSizePolicy(sizePolicy)
        self.btnCardPayment.setObjectName(_fromUtf8("btnCardPayment"))
        self.gridLayout_5.addWidget(self.btnCardPayment, 1, 2, 1, 1)
        self.grpAccounts = QtGui.QGroupBox(self.tabAccounts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpAccounts.sizePolicy().hasHeightForWidth())
        self.grpAccounts.setSizePolicy(sizePolicy)
        self.grpAccounts.setObjectName(_fromUtf8("grpAccounts"))
        self.gridLayout_6 = QtGui.QGridLayout(self.grpAccounts)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblAccountContractNumber = QtGui.QLabel(self.grpAccounts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAccountContractNumber.sizePolicy().hasHeightForWidth())
        self.lblAccountContractNumber.setSizePolicy(sizePolicy)
        self.lblAccountContractNumber.setObjectName(_fromUtf8("lblAccountContractNumber"))
        self.gridLayout_6.addWidget(self.lblAccountContractNumber, 4, 0, 1, 2)
        self.buttonBoxAccounts = CApplyResetDialogButtonBox(self.grpAccounts)
        self.buttonBoxAccounts.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBoxAccounts.setObjectName(_fromUtf8("buttonBoxAccounts"))
        self.gridLayout_6.addWidget(self.buttonBoxAccounts, 20, 0, 1, 2)
        self.edtAccountNumber = QtGui.QLineEdit(self.grpAccounts)
        self.edtAccountNumber.setObjectName(_fromUtf8("edtAccountNumber"))
        self.gridLayout_6.addWidget(self.edtAccountNumber, 11, 0, 1, 2)
        self.edtAccountBegDate = CDateEdit(self.grpAccounts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAccountBegDate.sizePolicy().hasHeightForWidth())
        self.edtAccountBegDate.setSizePolicy(sizePolicy)
        self.edtAccountBegDate.setCalendarPopup(True)
        self.edtAccountBegDate.setObjectName(_fromUtf8("edtAccountBegDate"))
        self.gridLayout_6.addWidget(self.edtAccountBegDate, 12, 1, 1, 1)
        self.lblAccountNumber = QtGui.QLabel(self.grpAccounts)
        self.lblAccountNumber.setObjectName(_fromUtf8("lblAccountNumber"))
        self.gridLayout_6.addWidget(self.lblAccountNumber, 10, 0, 1, 2)
        self.lblAccountEndDate = QtGui.QLabel(self.grpAccounts)
        self.lblAccountEndDate.setObjectName(_fromUtf8("lblAccountEndDate"))
        self.gridLayout_6.addWidget(self.lblAccountEndDate, 13, 0, 1, 1)
        self.cmbAccountOrgStructure = COrgStructureComboBox(self.grpAccounts)
        self.cmbAccountOrgStructure.setObjectName(_fromUtf8("cmbAccountOrgStructure"))
        self.gridLayout_6.addWidget(self.cmbAccountOrgStructure, 1, 0, 1, 2)
        self.edtAccountContractResolution = QtGui.QLineEdit(self.grpAccounts)
        self.edtAccountContractResolution.setObjectName(_fromUtf8("edtAccountContractResolution"))
        self.gridLayout_6.addWidget(self.edtAccountContractResolution, 7, 0, 1, 2)
        self.edtAccountContractNumber = QtGui.QLineEdit(self.grpAccounts)
        self.edtAccountContractNumber.setObjectName(_fromUtf8("edtAccountContractNumber"))
        self.gridLayout_6.addWidget(self.edtAccountContractNumber, 5, 0, 1, 2)
        self.lblAccountContractGrouping = QtGui.QLabel(self.grpAccounts)
        self.lblAccountContractGrouping.setObjectName(_fromUtf8("lblAccountContractGrouping"))
        self.gridLayout_6.addWidget(self.lblAccountContractGrouping, 8, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 18, 0, 1, 2)
        self.edtAccountEndDate = CDateEdit(self.grpAccounts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAccountEndDate.sizePolicy().hasHeightForWidth())
        self.edtAccountEndDate.setSizePolicy(sizePolicy)
        self.edtAccountEndDate.setCalendarPopup(True)
        self.edtAccountEndDate.setObjectName(_fromUtf8("edtAccountEndDate"))
        self.gridLayout_6.addWidget(self.edtAccountEndDate, 13, 1, 1, 1)
        self.lblAccountContractResolution = QtGui.QLabel(self.grpAccounts)
        self.lblAccountContractResolution.setObjectName(_fromUtf8("lblAccountContractResolution"))
        self.gridLayout_6.addWidget(self.lblAccountContractResolution, 6, 0, 1, 2)
        self.edtAccountContractGrouping = QtGui.QLineEdit(self.grpAccounts)
        self.edtAccountContractGrouping.setObjectName(_fromUtf8("edtAccountContractGrouping"))
        self.gridLayout_6.addWidget(self.edtAccountContractGrouping, 9, 0, 1, 2)
        self.lblAccountBegDate = QtGui.QLabel(self.grpAccounts)
        self.lblAccountBegDate.setObjectName(_fromUtf8("lblAccountBegDate"))
        self.gridLayout_6.addWidget(self.lblAccountBegDate, 12, 0, 1, 1)
        self.cmbAccountAuthor = CPersonComboBox(self.grpAccounts, False)
        self.cmbAccountAuthor.setObjectName(_fromUtf8("cmbAccountAuthor"))
        self.gridLayout_6.addWidget(self.cmbAccountAuthor, 3, 0, 1, 2)
        self.lblAccountOrgStructure = QtGui.QLabel(self.grpAccounts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAccountOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblAccountOrgStructure.setSizePolicy(sizePolicy)
        self.lblAccountOrgStructure.setMinimumSize(QtCore.QSize(130, 0))
        self.lblAccountOrgStructure.setObjectName(_fromUtf8("lblAccountOrgStructure"))
        self.gridLayout_6.addWidget(self.lblAccountOrgStructure, 0, 0, 1, 2)
        self.lblAccountAuthor = QtGui.QLabel(self.grpAccounts)
        self.lblAccountAuthor.setObjectName(_fromUtf8("lblAccountAuthor"))
        self.gridLayout_6.addWidget(self.lblAccountAuthor, 2, 0, 1, 2)
        self.gridLayout_5.addWidget(self.grpAccounts, 0, 0, 2, 1)
        self.tabMain.addTab(self.tabAccounts, _fromUtf8(""))
        self.tabPayedAccounts = QtGui.QWidget()
        self.tabPayedAccounts.setObjectName(_fromUtf8("tabPayedAccounts"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabPayedAccounts)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btnCashRefund = QtGui.QPushButton(self.tabPayedAccounts)
        self.btnCashRefund.setEnabled(False)
        self.btnCashRefund.setObjectName(_fromUtf8("btnCashRefund"))
        self.gridLayout_4.addWidget(self.btnCashRefund, 1, 1, 1, 1)
        self.grpPayedAccounts = QtGui.QGroupBox(self.tabPayedAccounts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpPayedAccounts.sizePolicy().hasHeightForWidth())
        self.grpPayedAccounts.setSizePolicy(sizePolicy)
        self.grpPayedAccounts.setObjectName(_fromUtf8("grpPayedAccounts"))
        self.gridLayout_7 = QtGui.QGridLayout(self.grpPayedAccounts)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lblPayedAccountEndDate = QtGui.QLabel(self.grpPayedAccounts)
        self.lblPayedAccountEndDate.setObjectName(_fromUtf8("lblPayedAccountEndDate"))
        self.gridLayout_7.addWidget(self.lblPayedAccountEndDate, 13, 0, 1, 1)
        self.edtPayedAccountEndDate = CDateEdit(self.grpPayedAccounts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPayedAccountEndDate.sizePolicy().hasHeightForWidth())
        self.edtPayedAccountEndDate.setSizePolicy(sizePolicy)
        self.edtPayedAccountEndDate.setCalendarPopup(True)
        self.edtPayedAccountEndDate.setObjectName(_fromUtf8("edtPayedAccountEndDate"))
        self.gridLayout_7.addWidget(self.edtPayedAccountEndDate, 13, 1, 1, 1)
        self.lblPayedAccountContractNumber = QtGui.QLabel(self.grpPayedAccounts)
        self.lblPayedAccountContractNumber.setObjectName(_fromUtf8("lblPayedAccountContractNumber"))
        self.gridLayout_7.addWidget(self.lblPayedAccountContractNumber, 4, 0, 1, 2)
        self.edtPayedAccountContractNumber = QtGui.QLineEdit(self.grpPayedAccounts)
        self.edtPayedAccountContractNumber.setObjectName(_fromUtf8("edtPayedAccountContractNumber"))
        self.gridLayout_7.addWidget(self.edtPayedAccountContractNumber, 5, 0, 1, 2)
        self.lblPayedAccountContractResolution = QtGui.QLabel(self.grpPayedAccounts)
        self.lblPayedAccountContractResolution.setObjectName(_fromUtf8("lblPayedAccountContractResolution"))
        self.gridLayout_7.addWidget(self.lblPayedAccountContractResolution, 6, 0, 1, 2)
        self.edtPayedAccountContractGrouping = QtGui.QLineEdit(self.grpPayedAccounts)
        self.edtPayedAccountContractGrouping.setObjectName(_fromUtf8("edtPayedAccountContractGrouping"))
        self.gridLayout_7.addWidget(self.edtPayedAccountContractGrouping, 9, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 18, 0, 1, 2)
        self.lblPayedAccountBegDate = QtGui.QLabel(self.grpPayedAccounts)
        self.lblPayedAccountBegDate.setObjectName(_fromUtf8("lblPayedAccountBegDate"))
        self.gridLayout_7.addWidget(self.lblPayedAccountBegDate, 12, 0, 1, 1)
        self.edtPayedAccountBegDate = CDateEdit(self.grpPayedAccounts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPayedAccountBegDate.sizePolicy().hasHeightForWidth())
        self.edtPayedAccountBegDate.setSizePolicy(sizePolicy)
        self.edtPayedAccountBegDate.setCalendarPopup(True)
        self.edtPayedAccountBegDate.setObjectName(_fromUtf8("edtPayedAccountBegDate"))
        self.gridLayout_7.addWidget(self.edtPayedAccountBegDate, 12, 1, 1, 1)
        self.edtPayedAccountContractResolution = QtGui.QLineEdit(self.grpPayedAccounts)
        self.edtPayedAccountContractResolution.setObjectName(_fromUtf8("edtPayedAccountContractResolution"))
        self.gridLayout_7.addWidget(self.edtPayedAccountContractResolution, 7, 0, 1, 2)
        self.lblPayedAccountContractGrouping = QtGui.QLabel(self.grpPayedAccounts)
        self.lblPayedAccountContractGrouping.setObjectName(_fromUtf8("lblPayedAccountContractGrouping"))
        self.gridLayout_7.addWidget(self.lblPayedAccountContractGrouping, 8, 0, 1, 2)
        self.lblPayedAccountNumber = QtGui.QLabel(self.grpPayedAccounts)
        self.lblPayedAccountNumber.setObjectName(_fromUtf8("lblPayedAccountNumber"))
        self.gridLayout_7.addWidget(self.lblPayedAccountNumber, 10, 0, 1, 2)
        self.edtPayedAccountNumber = QtGui.QLineEdit(self.grpPayedAccounts)
        self.edtPayedAccountNumber.setObjectName(_fromUtf8("edtPayedAccountNumber"))
        self.gridLayout_7.addWidget(self.edtPayedAccountNumber, 11, 0, 1, 2)
        self.buttonBoxPayedAccounts = CApplyResetDialogButtonBox(self.grpPayedAccounts)
        self.buttonBoxPayedAccounts.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBoxPayedAccounts.setObjectName(_fromUtf8("buttonBoxPayedAccounts"))
        self.gridLayout_7.addWidget(self.buttonBoxPayedAccounts, 19, 0, 1, 2)
        self.cmbPayedAccountOrgStructure = COrgStructureComboBox(self.grpPayedAccounts)
        self.cmbPayedAccountOrgStructure.setObjectName(_fromUtf8("cmbPayedAccountOrgStructure"))
        self.gridLayout_7.addWidget(self.cmbPayedAccountOrgStructure, 1, 0, 1, 2)
        self.cmbPayedAccountAuthor = CPersonComboBox(self.grpPayedAccounts, False)
        self.cmbPayedAccountAuthor.setObjectName(_fromUtf8("cmbPayedAccountAuthor"))
        self.gridLayout_7.addWidget(self.cmbPayedAccountAuthor, 3, 0, 1, 2)
        self.label = QtGui.QLabel(self.grpPayedAccounts)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 2, 0, 1, 2)
        self.lblPayedAccountOrgStructure = QtGui.QLabel(self.grpPayedAccounts)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPayedAccountOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblPayedAccountOrgStructure.setSizePolicy(sizePolicy)
        self.lblPayedAccountOrgStructure.setMinimumSize(QtCore.QSize(130, 0))
        self.lblPayedAccountOrgStructure.setObjectName(_fromUtf8("lblPayedAccountOrgStructure"))
        self.gridLayout_7.addWidget(self.lblPayedAccountOrgStructure, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.grpPayedAccounts, 0, 0, 2, 1)
        self.btnCardRefund = QtGui.QPushButton(self.tabPayedAccounts)
        self.btnCardRefund.setEnabled(False)
        self.btnCardRefund.setObjectName(_fromUtf8("btnCardRefund"))
        self.gridLayout_4.addWidget(self.btnCardRefund, 1, 2, 1, 1)
        self.tblPayedAccounts = CInDocTableView(self.tabPayedAccounts)
        self.tblPayedAccounts.setObjectName(_fromUtf8("tblPayedAccounts"))
        self.gridLayout_4.addWidget(self.tblPayedAccounts, 0, 1, 1, 2)
        self.tabMain.addTab(self.tabPayedAccounts, _fromUtf8(""))
        self.tabCash = QtGui.QWidget()
        self.tabCash.setEnabled(True)
        self.tabCash.setObjectName(_fromUtf8("tabCash"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabCash)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.btnPutToCash = QtGui.QPushButton(self.tabCash)
        self.btnPutToCash.setObjectName(_fromUtf8("btnPutToCash"))
        self.gridLayout_8.addWidget(self.btnPutToCash, 1, 0, 1, 2)
        self.edtCashSum = QtGui.QDoubleSpinBox(self.tabCash)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCashSum.sizePolicy().hasHeightForWidth())
        self.edtCashSum.setSizePolicy(sizePolicy)
        self.edtCashSum.setFocusPolicy(QtCore.Qt.NoFocus)
        self.edtCashSum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtCashSum.setReadOnly(True)
        self.edtCashSum.setPrefix(_fromUtf8(""))
        self.edtCashSum.setDecimals(2)
        self.edtCashSum.setMaximum(99999999.99)
        self.edtCashSum.setObjectName(_fromUtf8("edtCashSum"))
        self.gridLayout_8.addWidget(self.edtCashSum, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 4, 1, 1, 1)
        self.lblCashSum = QtGui.QLabel(self.tabCash)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCashSum.sizePolicy().hasHeightForWidth())
        self.lblCashSum.setSizePolicy(sizePolicy)
        self.lblCashSum.setObjectName(_fromUtf8("lblCashSum"))
        self.gridLayout_8.addWidget(self.lblCashSum, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 0, 4, 1, 1)
        self.btnTakeFromCash = QtGui.QPushButton(self.tabCash)
        self.btnTakeFromCash.setObjectName(_fromUtf8("btnTakeFromCash"))
        self.gridLayout_8.addWidget(self.btnTakeFromCash, 2, 0, 1, 2)
        self.tabMain.addTab(self.tabCash, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabMain, 1, 0, 1, 3)
        self.lblAccountContractNumber.setBuddy(self.edtAccountContractNumber)
        self.lblAccountNumber.setBuddy(self.edtAccountNumber)
        self.lblAccountEndDate.setBuddy(self.edtAccountEndDate)
        self.lblAccountContractGrouping.setBuddy(self.edtAccountContractGrouping)
        self.lblAccountContractResolution.setBuddy(self.edtAccountContractResolution)
        self.lblAccountBegDate.setBuddy(self.edtAccountBegDate)
        self.lblAccountOrgStructure.setBuddy(self.cmbAccountOrgStructure)
        self.lblAccountAuthor.setBuddy(self.cmbAccountAuthor)
        self.lblPayedAccountEndDate.setBuddy(self.edtPayedAccountEndDate)
        self.lblPayedAccountContractNumber.setBuddy(self.edtPayedAccountContractNumber)
        self.lblPayedAccountContractResolution.setBuddy(self.edtPayedAccountContractResolution)
        self.lblPayedAccountBegDate.setBuddy(self.edtPayedAccountBegDate)
        self.lblPayedAccountContractGrouping.setBuddy(self.edtPayedAccountContractGrouping)
        self.lblPayedAccountNumber.setBuddy(self.edtPayedAccountNumber)
        self.label.setBuddy(self.cmbPayedAccountAuthor)
        self.lblPayedAccountOrgStructure.setBuddy(self.cmbPayedAccountOrgStructure)

        self.retranslateUi(CCashRegister)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CCashRegister)
        CCashRegister.setTabOrder(self.btnOpenSession, self.btnCloseSession)
        CCashRegister.setTabOrder(self.btnCloseSession, self.btnPrintDuplicate)
        CCashRegister.setTabOrder(self.btnPrintDuplicate, self.tabMain)
        CCashRegister.setTabOrder(self.tabMain, self.tblAccounts)
        CCashRegister.setTabOrder(self.tblAccounts, self.btnCashPayment)
        CCashRegister.setTabOrder(self.btnCashPayment, self.btnCardPayment)
        CCashRegister.setTabOrder(self.btnCardPayment, self.cmbAccountOrgStructure)
        CCashRegister.setTabOrder(self.cmbAccountOrgStructure, self.cmbAccountAuthor)
        CCashRegister.setTabOrder(self.cmbAccountAuthor, self.edtAccountContractNumber)
        CCashRegister.setTabOrder(self.edtAccountContractNumber, self.edtAccountContractResolution)
        CCashRegister.setTabOrder(self.edtAccountContractResolution, self.edtAccountContractGrouping)
        CCashRegister.setTabOrder(self.edtAccountContractGrouping, self.edtAccountNumber)
        CCashRegister.setTabOrder(self.edtAccountNumber, self.edtAccountBegDate)
        CCashRegister.setTabOrder(self.edtAccountBegDate, self.edtAccountEndDate)
        CCashRegister.setTabOrder(self.edtAccountEndDate, self.buttonBoxAccounts)
        CCashRegister.setTabOrder(self.buttonBoxAccounts, self.tblPayedAccounts)
        CCashRegister.setTabOrder(self.tblPayedAccounts, self.cmbPayedAccountOrgStructure)
        CCashRegister.setTabOrder(self.cmbPayedAccountOrgStructure, self.cmbPayedAccountAuthor)
        CCashRegister.setTabOrder(self.cmbPayedAccountAuthor, self.edtPayedAccountContractNumber)
        CCashRegister.setTabOrder(self.edtPayedAccountContractNumber, self.edtPayedAccountContractResolution)
        CCashRegister.setTabOrder(self.edtPayedAccountContractResolution, self.edtPayedAccountContractGrouping)
        CCashRegister.setTabOrder(self.edtPayedAccountContractGrouping, self.edtPayedAccountNumber)
        CCashRegister.setTabOrder(self.edtPayedAccountNumber, self.edtPayedAccountBegDate)
        CCashRegister.setTabOrder(self.edtPayedAccountBegDate, self.edtPayedAccountEndDate)
        CCashRegister.setTabOrder(self.edtPayedAccountEndDate, self.buttonBoxPayedAccounts)
        CCashRegister.setTabOrder(self.buttonBoxPayedAccounts, self.btnPutToCash)
        CCashRegister.setTabOrder(self.btnPutToCash, self.btnTakeFromCash)
        CCashRegister.setTabOrder(self.btnTakeFromCash, self.btnCashRefund)
        CCashRegister.setTabOrder(self.btnCashRefund, self.btnCardRefund)

    def retranslateUi(self, CCashRegister):
        CCashRegister.setWindowTitle(_translate("CCashRegister", "Dialog", None))
        self.grpState.setTitle(_translate("CCashRegister", "Состояние", None))
        self.lblModel.setText(_translate("CCashRegister", "ККМ:", None))
        self.lblModelValue.setText(_translate("CCashRegister", "АТОЛ 30Ф", None))
        self.lblOfdExchange.setText(_translate("CCashRegister", "ОФД:", None))
        self.lblOfdExchangeValue.setText(_translate("CCashRegister", "ok", None))
        self.grpSession.setTitle(_translate("CCashRegister", "Смена", None))
        self.btnOpenSession.setText(_translate("CCashRegister", "Открыть", None))
        self.btnCloseSession.setText(_translate("CCashRegister", "Закрыть", None))
        self.grpDoc.setTitle(_translate("CCashRegister", "Документ", None))
        self.btnPrintDuplicate.setText(_translate("CCashRegister", "Печатать дубликат", None))
        self.btnCashPayment.setText(_translate("CCashRegister", "&Наличная оплата", None))
        self.btnCardPayment.setText(_translate("CCashRegister", "&Электронная оплата", None))
        self.grpAccounts.setTitle(_translate("CCashRegister", "Фильтр", None))
        self.lblAccountContractNumber.setText(_translate("CCashRegister", "&Номер договора", None))
        self.edtAccountBegDate.setDisplayFormat(_translate("CCashRegister", "dd.MM.yyyy", None))
        self.lblAccountNumber.setText(_translate("CCashRegister", "Номер &счёта", None))
        self.lblAccountEndDate.setText(_translate("CCashRegister", "&по", None))
        self.lblAccountContractGrouping.setText(_translate("CCashRegister", "&Группа договора", None))
        self.edtAccountEndDate.setDisplayFormat(_translate("CCashRegister", "dd.MM.yyyy", None))
        self.lblAccountContractResolution.setText(_translate("CCashRegister", "&Основание договора", None))
        self.lblAccountBegDate.setText(_translate("CCashRegister", "&Дата счёта c", None))
        self.lblAccountOrgStructure.setText(_translate("CCashRegister", "Под&разделение", None))
        self.lblAccountAuthor.setText(_translate("CCashRegister", "&Автор счёта", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabAccounts), _translate("CCashRegister", "&Счета", None))
        self.btnCashRefund.setText(_translate("CCashRegister", "&Наличный возврат", None))
        self.grpPayedAccounts.setTitle(_translate("CCashRegister", "Фильтр", None))
        self.lblPayedAccountEndDate.setText(_translate("CCashRegister", "&по", None))
        self.edtPayedAccountEndDate.setDisplayFormat(_translate("CCashRegister", "dd.MM.yyyy", None))
        self.lblPayedAccountContractNumber.setText(_translate("CCashRegister", "&Номер договора", None))
        self.lblPayedAccountContractResolution.setText(_translate("CCashRegister", "&Основание договора", None))
        self.lblPayedAccountBegDate.setText(_translate("CCashRegister", "&Дата счёта c", None))
        self.edtPayedAccountBegDate.setDisplayFormat(_translate("CCashRegister", "dd.MM.yyyy", None))
        self.lblPayedAccountContractGrouping.setText(_translate("CCashRegister", "&Группа договора", None))
        self.lblPayedAccountNumber.setText(_translate("CCashRegister", "Номер &счёта", None))
        self.label.setText(_translate("CCashRegister", "&Автор счёта", None))
        self.lblPayedAccountOrgStructure.setText(_translate("CCashRegister", "Под&разделение", None))
        self.btnCardRefund.setText(_translate("CCashRegister", "&Электронный возврат", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabPayedAccounts), _translate("CCashRegister", "&Оплаченные счета", None))
        self.btnPutToCash.setText(_translate("CCashRegister", "Внести", None))
        self.lblCashSum.setText(_translate("CCashRegister", "Сумма в кассе ", None))
        self.btnTakeFromCash.setText(_translate("CCashRegister", "Изъять", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabCash), _translate("CCashRegister", "На&личность", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBox import CPersonComboBox
from library.DateEdit import CDateEdit
from library.DialogButtonBox import CApplyResetDialogButtonBox
from library.InDocTable import CInDocTableView

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CCashRegister = QtGui.QDialog()
    ui = Ui_CCashRegister()
    ui.setupUi(CCashRegister)
    CCashRegister.show()
    sys.exit(app.exec_())

