# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/green/s11_trunk/appendix/cashRegister/app/RetAccountItems.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CRetAccountItems(object):
    def setupUi(self, CRetAccountItems):
        CRetAccountItems.setObjectName(_fromUtf8("CRetAccountItems"))
        CRetAccountItems.resize(407, 378)
        self.gridLayout = QtGui.QGridLayout(CRetAccountItems)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblAccountNumber = QtGui.QLabel(CRetAccountItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAccountNumber.sizePolicy().hasHeightForWidth())
        self.lblAccountNumber.setSizePolicy(sizePolicy)
        self.lblAccountNumber.setObjectName(_fromUtf8("lblAccountNumber"))
        self.gridLayout.addWidget(self.lblAccountNumber, 0, 0, 1, 1)
        self.lblAccountDate = QtGui.QLabel(CRetAccountItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAccountDate.sizePolicy().hasHeightForWidth())
        self.lblAccountDate.setSizePolicy(sizePolicy)
        self.lblAccountDate.setObjectName(_fromUtf8("lblAccountDate"))
        self.gridLayout.addWidget(self.lblAccountDate, 1, 0, 1, 1)
        self.lblClientName = QtGui.QLabel(CRetAccountItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClientName.sizePolicy().hasHeightForWidth())
        self.lblClientName.setSizePolicy(sizePolicy)
        self.lblClientName.setObjectName(_fromUtf8("lblClientName"))
        self.gridLayout.addWidget(self.lblClientName, 2, 0, 1, 1)
        self.lblPayerName = QtGui.QLabel(CRetAccountItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPayerName.sizePolicy().hasHeightForWidth())
        self.lblPayerName.setSizePolicy(sizePolicy)
        self.lblPayerName.setObjectName(_fromUtf8("lblPayerName"))
        self.gridLayout.addWidget(self.lblPayerName, 3, 0, 1, 1)
        self.lblPayerNameText = QtGui.QLabel(CRetAccountItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPayerNameText.sizePolicy().hasHeightForWidth())
        self.lblPayerNameText.setSizePolicy(sizePolicy)
        self.lblPayerNameText.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblPayerNameText.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblPayerNameText.setText(_fromUtf8(""))
        self.lblPayerNameText.setTextFormat(QtCore.Qt.PlainText)
        self.lblPayerNameText.setScaledContents(False)
        self.lblPayerNameText.setIndent(2)
        self.lblPayerNameText.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.lblPayerNameText.setObjectName(_fromUtf8("lblPayerNameText"))
        self.gridLayout.addWidget(self.lblPayerNameText, 3, 2, 1, 1)
        self.lblRetAmountText = QtGui.QLabel(CRetAccountItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRetAmountText.sizePolicy().hasHeightForWidth())
        self.lblRetAmountText.setSizePolicy(sizePolicy)
        self.lblRetAmountText.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblRetAmountText.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblRetAmountText.setText(_fromUtf8(""))
        self.lblRetAmountText.setTextFormat(QtCore.Qt.PlainText)
        self.lblRetAmountText.setScaledContents(False)
        self.lblRetAmountText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRetAmountText.setIndent(2)
        self.lblRetAmountText.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.lblRetAmountText.setObjectName(_fromUtf8("lblRetAmountText"))
        self.gridLayout.addWidget(self.lblRetAmountText, 5, 1, 1, 2)
        self.lblRetAmount = QtGui.QLabel(CRetAccountItems)
        self.lblRetAmount.setObjectName(_fromUtf8("lblRetAmount"))
        self.gridLayout.addWidget(self.lblRetAmount, 5, 0, 1, 1)
        self.lblAccountDateText = QtGui.QLabel(CRetAccountItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAccountDateText.sizePolicy().hasHeightForWidth())
        self.lblAccountDateText.setSizePolicy(sizePolicy)
        self.lblAccountDateText.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblAccountDateText.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblAccountDateText.setText(_fromUtf8(""))
        self.lblAccountDateText.setTextFormat(QtCore.Qt.PlainText)
        self.lblAccountDateText.setScaledContents(False)
        self.lblAccountDateText.setIndent(2)
        self.lblAccountDateText.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.lblAccountDateText.setObjectName(_fromUtf8("lblAccountDateText"))
        self.gridLayout.addWidget(self.lblAccountDateText, 1, 2, 1, 1)
        self.tblAccountItems = CInDocTableView(CRetAccountItems)
        self.tblAccountItems.setObjectName(_fromUtf8("tblAccountItems"))
        self.gridLayout.addWidget(self.tblAccountItems, 4, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(CRetAccountItems)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 8, 0, 1, 3)
        self.lblAccountNumberText = QtGui.QLabel(CRetAccountItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAccountNumberText.sizePolicy().hasHeightForWidth())
        self.lblAccountNumberText.setSizePolicy(sizePolicy)
        self.lblAccountNumberText.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblAccountNumberText.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblAccountNumberText.setText(_fromUtf8(""))
        self.lblAccountNumberText.setTextFormat(QtCore.Qt.PlainText)
        self.lblAccountNumberText.setScaledContents(False)
        self.lblAccountNumberText.setIndent(2)
        self.lblAccountNumberText.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.lblAccountNumberText.setObjectName(_fromUtf8("lblAccountNumberText"))
        self.gridLayout.addWidget(self.lblAccountNumberText, 0, 2, 1, 1)
        self.lblClientNameText = QtGui.QLabel(CRetAccountItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClientNameText.sizePolicy().hasHeightForWidth())
        self.lblClientNameText.setSizePolicy(sizePolicy)
        self.lblClientNameText.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblClientNameText.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblClientNameText.setText(_fromUtf8(""))
        self.lblClientNameText.setTextFormat(QtCore.Qt.PlainText)
        self.lblClientNameText.setScaledContents(False)
        self.lblClientNameText.setIndent(2)
        self.lblClientNameText.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.lblClientNameText.setObjectName(_fromUtf8("lblClientNameText"))
        self.gridLayout.addWidget(self.lblClientNameText, 2, 2, 1, 1)
        self.lblRetSumText = QtGui.QLabel(CRetAccountItems)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRetSumText.sizePolicy().hasHeightForWidth())
        self.lblRetSumText.setSizePolicy(sizePolicy)
        self.lblRetSumText.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblRetSumText.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblRetSumText.setText(_fromUtf8(""))
        self.lblRetSumText.setTextFormat(QtCore.Qt.PlainText)
        self.lblRetSumText.setScaledContents(False)
        self.lblRetSumText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRetSumText.setIndent(2)
        self.lblRetSumText.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.lblRetSumText.setObjectName(_fromUtf8("lblRetSumText"))
        self.gridLayout.addWidget(self.lblRetSumText, 6, 1, 1, 2)
        self.lblRetSum = QtGui.QLabel(CRetAccountItems)
        self.lblRetSum.setObjectName(_fromUtf8("lblRetSum"))
        self.gridLayout.addWidget(self.lblRetSum, 6, 0, 1, 1)

        self.retranslateUi(CRetAccountItems)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CRetAccountItems.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CRetAccountItems.reject)
        QtCore.QMetaObject.connectSlotsByName(CRetAccountItems)

    def retranslateUi(self, CRetAccountItems):
        CRetAccountItems.setWindowTitle(_translate("CRetAccountItems", "Выбор возврата", None))
        self.lblAccountNumber.setText(_translate("CRetAccountItems", "Номер счёта", None))
        self.lblAccountDate.setText(_translate("CRetAccountItems", "Дата счёта", None))
        self.lblClientName.setText(_translate("CRetAccountItems", "Пациент", None))
        self.lblPayerName.setText(_translate("CRetAccountItems", "Плательщик", None))
        self.lblRetAmount.setText(_translate("CRetAccountItems", "Возврат", None))
        self.lblRetSum.setText(_translate("CRetAccountItems", "Сумма", None))

from library.InDocTable import CInDocTableView

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CRetAccountItems = QtGui.QDialog()
    ui = Ui_CRetAccountItems()
    ui.setupUi(CRetAccountItems)
    CRetAccountItems.show()
    sys.exit(app.exec_())

