# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\Samson\UP_s11\client\RefBooks\Speciality\RBSpecialityEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(485, 513)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.gridLayout_2 = QtGui.QGridLayout(ItemEditorDialog)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(ItemEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.gridLayout = QtGui.QGridLayout(self.tabMain)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtUsishCode = QtGui.QLineEdit(self.tabMain)
        self.edtUsishCode.setObjectName(_fromUtf8("edtUsishCode"))
        self.gridLayout.addWidget(self.edtUsishCode, 8, 1, 1, 3)
        self.cmbAltProvinceService = CRBComboBox(self.tabMain)
        self.cmbAltProvinceService.setObjectName(_fromUtf8("cmbAltProvinceService"))
        self.gridLayout.addWidget(self.cmbAltProvinceService, 16, 1, 1, 2)
        self.edtOKSOName = QtGui.QLineEdit(self.tabMain)
        self.edtOKSOName.setObjectName(_fromUtf8("edtOKSOName"))
        self.gridLayout.addWidget(self.edtOKSOName, 5, 1, 1, 3)
        self.lblOtherService = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOtherService.sizePolicy().hasHeightForWidth())
        self.lblOtherService.setSizePolicy(sizePolicy)
        self.lblOtherService.setObjectName(_fromUtf8("lblOtherService"))
        self.gridLayout.addWidget(self.lblOtherService, 13, 0, 1, 1)
        self.edtRegionalCode = QtGui.QLineEdit(self.tabMain)
        self.edtRegionalCode.setObjectName(_fromUtf8("edtRegionalCode"))
        self.gridLayout.addWidget(self.edtRegionalCode, 9, 1, 1, 3)
        spacerItem = QtGui.QSpacerItem(141, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 18, 2, 1, 2)
        self.lblSex = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSex.sizePolicy().hasHeightForWidth())
        self.lblSex.setSizePolicy(sizePolicy)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridLayout.addWidget(self.lblSex, 18, 0, 1, 1)
        self.cmbSex = QtGui.QComboBox(self.tabMain)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.setItemText(0, _fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 18, 1, 1, 1)
        self.lblAge = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAge.sizePolicy().hasHeightForWidth())
        self.lblAge.setSizePolicy(sizePolicy)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridLayout.addWidget(self.lblAge, 19, 0, 1, 1)
        self.btnSelectLocalService = QtGui.QToolButton(self.tabMain)
        self.btnSelectLocalService.setObjectName(_fromUtf8("btnSelectLocalService"))
        self.gridLayout.addWidget(self.btnSelectLocalService, 11, 3, 1, 1)
        self.lblOKSOName = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOKSOName.sizePolicy().hasHeightForWidth())
        self.lblOKSOName.setSizePolicy(sizePolicy)
        self.lblOKSOName.setObjectName(_fromUtf8("lblOKSOName"))
        self.gridLayout.addWidget(self.lblOKSOName, 5, 0, 1, 1)
        self.btnSelectAltLocalService = QtGui.QToolButton(self.tabMain)
        self.btnSelectAltLocalService.setObjectName(_fromUtf8("btnSelectAltLocalService"))
        self.gridLayout.addWidget(self.btnSelectAltLocalService, 15, 3, 1, 1)
        self.lblFederalCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFederalCode.sizePolicy().hasHeightForWidth())
        self.lblFederalCode.setSizePolicy(sizePolicy)
        self.lblFederalCode.setObjectName(_fromUtf8("lblFederalCode"))
        self.gridLayout.addWidget(self.lblFederalCode, 7, 0, 1, 1)
        self.cmbOtherService = CRBComboBox(self.tabMain)
        self.cmbOtherService.setObjectName(_fromUtf8("cmbOtherService"))
        self.gridLayout.addWidget(self.cmbOtherService, 13, 1, 1, 2)
        self.cmbProvinceService = CRBComboBox(self.tabMain)
        self.cmbProvinceService.setObjectName(_fromUtf8("cmbProvinceService"))
        self.gridLayout.addWidget(self.cmbProvinceService, 12, 1, 1, 2)
        self.lblOKSOCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOKSOCode.sizePolicy().hasHeightForWidth())
        self.lblOKSOCode.setSizePolicy(sizePolicy)
        self.lblOKSOCode.setObjectName(_fromUtf8("lblOKSOCode"))
        self.gridLayout.addWidget(self.lblOKSOCode, 6, 0, 1, 1)
        self.lblProvinceService = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProvinceService.sizePolicy().hasHeightForWidth())
        self.lblProvinceService.setSizePolicy(sizePolicy)
        self.lblProvinceService.setObjectName(_fromUtf8("lblProvinceService"))
        self.gridLayout.addWidget(self.lblProvinceService, 12, 0, 1, 1)
        self.cmbLocalService = CRBComboBox(self.tabMain)
        self.cmbLocalService.setObjectName(_fromUtf8("cmbLocalService"))
        self.gridLayout.addWidget(self.cmbLocalService, 11, 1, 1, 2)
        self.lblLocalService = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLocalService.sizePolicy().hasHeightForWidth())
        self.lblLocalService.setSizePolicy(sizePolicy)
        self.lblLocalService.setObjectName(_fromUtf8("lblLocalService"))
        self.gridLayout.addWidget(self.lblLocalService, 11, 0, 1, 1)
        self.btnSelectAltProvinceService = QtGui.QToolButton(self.tabMain)
        self.btnSelectAltProvinceService.setObjectName(_fromUtf8("btnSelectAltProvinceService"))
        self.gridLayout.addWidget(self.btnSelectAltProvinceService, 16, 3, 1, 1)
        self.lblAltLocalService = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAltLocalService.sizePolicy().hasHeightForWidth())
        self.lblAltLocalService.setSizePolicy(sizePolicy)
        self.lblAltLocalService.setObjectName(_fromUtf8("lblAltLocalService"))
        self.gridLayout.addWidget(self.lblAltLocalService, 15, 0, 1, 1)
        self.lblRegionalCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRegionalCode.sizePolicy().hasHeightForWidth())
        self.lblRegionalCode.setSizePolicy(sizePolicy)
        self.lblRegionalCode.setObjectName(_fromUtf8("lblRegionalCode"))
        self.gridLayout.addWidget(self.lblRegionalCode, 9, 0, 1, 1)
        self.btnSelectOtherService = QtGui.QToolButton(self.tabMain)
        self.btnSelectOtherService.setObjectName(_fromUtf8("btnSelectOtherService"))
        self.gridLayout.addWidget(self.btnSelectOtherService, 13, 3, 1, 1)
        self.lblUsishCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUsishCode.sizePolicy().hasHeightForWidth())
        self.lblUsishCode.setSizePolicy(sizePolicy)
        self.lblUsishCode.setObjectName(_fromUtf8("lblUsishCode"))
        self.gridLayout.addWidget(self.lblUsishCode, 8, 0, 1, 1)
        self.lblAltOtherService = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAltOtherService.sizePolicy().hasHeightForWidth())
        self.lblAltOtherService.setSizePolicy(sizePolicy)
        self.lblAltOtherService.setObjectName(_fromUtf8("lblAltOtherService"))
        self.gridLayout.addWidget(self.lblAltOtherService, 17, 0, 1, 1)
        self.cmbAltOtherService = CRBComboBox(self.tabMain)
        self.cmbAltOtherService.setObjectName(_fromUtf8("cmbAltOtherService"))
        self.gridLayout.addWidget(self.cmbAltOtherService, 17, 1, 1, 2)
        self.btnSelectProvinceService = QtGui.QToolButton(self.tabMain)
        self.btnSelectProvinceService.setObjectName(_fromUtf8("btnSelectProvinceService"))
        self.gridLayout.addWidget(self.btnSelectProvinceService, 12, 3, 1, 1)
        self.btnAltSelectOtherService = QtGui.QToolButton(self.tabMain)
        self.btnAltSelectOtherService.setObjectName(_fromUtf8("btnAltSelectOtherService"))
        self.gridLayout.addWidget(self.btnAltSelectOtherService, 17, 3, 1, 1)
        self.cmbAltLocalService = CRBComboBox(self.tabMain)
        self.cmbAltLocalService.setObjectName(_fromUtf8("cmbAltLocalService"))
        self.gridLayout.addWidget(self.cmbAltLocalService, 15, 1, 1, 2)
        self.lblAltProvinceService = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAltProvinceService.sizePolicy().hasHeightForWidth())
        self.lblAltProvinceService.setSizePolicy(sizePolicy)
        self.lblAltProvinceService.setObjectName(_fromUtf8("lblAltProvinceService"))
        self.gridLayout.addWidget(self.lblAltProvinceService, 16, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(self.tabMain)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout.addWidget(self.edtCode, 2, 1, 1, 3)
        self.edtMKBFilter = QtGui.QLineEdit(self.tabMain)
        self.edtMKBFilter.setObjectName(_fromUtf8("edtMKBFilter"))
        self.gridLayout.addWidget(self.edtMKBFilter, 20, 1, 1, 3)
        self.edtOKSOCode = QtGui.QLineEdit(self.tabMain)
        self.edtOKSOCode.setObjectName(_fromUtf8("edtOKSOCode"))
        self.gridLayout.addWidget(self.edtOKSOCode, 6, 1, 1, 3)
        self.lblCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 2, 0, 1, 1)
        self.lblMKBFilter = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMKBFilter.sizePolicy().hasHeightForWidth())
        self.lblMKBFilter.setSizePolicy(sizePolicy)
        self.lblMKBFilter.setObjectName(_fromUtf8("lblMKBFilter"))
        self.gridLayout.addWidget(self.lblMKBFilter, 20, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(self.tabMain)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 4, 1, 1, 3)
        self.lblName = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(73, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 23, 0, 1, 1)
        self.cmbMedicalAidProfile = CRBComboBox(self.tabMain)
        self.cmbMedicalAidProfile.setObjectName(_fromUtf8("cmbMedicalAidProfile"))
        self.gridLayout.addWidget(self.cmbMedicalAidProfile, 10, 1, 1, 3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cmbBegAgeUnit = QtGui.QComboBox(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBegAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbBegAgeUnit.setSizePolicy(sizePolicy)
        self.cmbBegAgeUnit.setObjectName(_fromUtf8("cmbBegAgeUnit"))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.cmbBegAgeUnit.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbBegAgeUnit)
        self.edtBegAgeCount = QtGui.QLineEdit(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegAgeCount.sizePolicy().hasHeightForWidth())
        self.edtBegAgeCount.setSizePolicy(sizePolicy)
        self.edtBegAgeCount.setMaxLength(3)
        self.edtBegAgeCount.setObjectName(_fromUtf8("edtBegAgeCount"))
        self.horizontalLayout.addWidget(self.edtBegAgeCount)
        self.lblAgeSep = QtGui.QLabel(self.tabMain)
        self.lblAgeSep.setObjectName(_fromUtf8("lblAgeSep"))
        self.horizontalLayout.addWidget(self.lblAgeSep)
        self.cmbEndAgeUnit = QtGui.QComboBox(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEndAgeUnit.sizePolicy().hasHeightForWidth())
        self.cmbEndAgeUnit.setSizePolicy(sizePolicy)
        self.cmbEndAgeUnit.setObjectName(_fromUtf8("cmbEndAgeUnit"))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.setItemText(0, _fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.cmbEndAgeUnit.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbEndAgeUnit)
        self.edtEndAgeCount = QtGui.QLineEdit(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndAgeCount.sizePolicy().hasHeightForWidth())
        self.edtEndAgeCount.setSizePolicy(sizePolicy)
        self.edtEndAgeCount.setMaxLength(3)
        self.edtEndAgeCount.setObjectName(_fromUtf8("edtEndAgeCount"))
        self.horizontalLayout.addWidget(self.edtEndAgeCount)
        self.gridLayout.addLayout(self.horizontalLayout, 19, 1, 1, 3)
        self.edtFederalCode = QtGui.QLineEdit(self.tabMain)
        self.edtFederalCode.setObjectName(_fromUtf8("edtFederalCode"))
        self.gridLayout.addWidget(self.edtFederalCode, 7, 1, 1, 3)
        self.chkIsHigh = QtGui.QCheckBox(self.tabMain)
        self.chkIsHigh.setObjectName(_fromUtf8("chkIsHigh"))
        self.gridLayout.addWidget(self.chkIsHigh, 22, 0, 1, 4)
        self.lblMedicalAidProfile = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMedicalAidProfile.sizePolicy().hasHeightForWidth())
        self.lblMedicalAidProfile.setSizePolicy(sizePolicy)
        self.lblMedicalAidProfile.setObjectName(_fromUtf8("lblMedicalAidProfile"))
        self.gridLayout.addWidget(self.lblMedicalAidProfile, 10, 0, 1, 1)
        self.cmbAmbAppointmentService = CRBComboBox(self.tabMain)
        self.cmbAmbAppointmentService.setObjectName(_fromUtf8("cmbAmbAppointmentService"))
        self.gridLayout.addWidget(self.cmbAmbAppointmentService, 14, 1, 1, 2)
        self.btnSelectAmbAppointmentService = QtGui.QToolButton(self.tabMain)
        self.btnSelectAmbAppointmentService.setObjectName(_fromUtf8("btnSelectAmbAppointmentService"))
        self.gridLayout.addWidget(self.btnSelectAmbAppointmentService, 14, 3, 1, 1)
        self.lblAmbAppointmentService = QtGui.QLabel(self.tabMain)
        self.lblAmbAppointmentService.setObjectName(_fromUtf8("lblAmbAppointmentService"))
        self.gridLayout.addWidget(self.lblAmbAppointmentService, 14, 0, 1, 1)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabMedicalAidProfiles = QtGui.QWidget()
        self.tabMedicalAidProfiles.setObjectName(_fromUtf8("tabMedicalAidProfiles"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabMedicalAidProfiles)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblMedicalAidProfiles = CInDocTableView(self.tabMedicalAidProfiles)
        self.tblMedicalAidProfiles.setObjectName(_fromUtf8("tblMedicalAidProfiles"))
        self.gridLayout_4.addWidget(self.tblMedicalAidProfiles, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabMedicalAidProfiles, _fromUtf8(""))
        self.tabIdentification = QtGui.QWidget()
        self.tabIdentification.setObjectName(_fromUtf8("tabIdentification"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabIdentification)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblIdentification = CInDocTableView(self.tabIdentification)
        self.tblIdentification.setObjectName(_fromUtf8("tblIdentification"))
        self.gridLayout_3.addWidget(self.tblIdentification, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIdentification, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 2, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(ItemEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.lblOtherService.setBuddy(self.cmbOtherService)
        self.lblSex.setBuddy(self.cmbSex)
        self.lblAge.setBuddy(self.cmbBegAgeUnit)
        self.lblOKSOName.setBuddy(self.edtOKSOName)
        self.lblFederalCode.setBuddy(self.edtFederalCode)
        self.lblOKSOCode.setBuddy(self.edtOKSOCode)
        self.lblProvinceService.setBuddy(self.cmbProvinceService)
        self.lblLocalService.setBuddy(self.cmbLocalService)
        self.lblAltLocalService.setBuddy(self.cmbAltLocalService)
        self.lblRegionalCode.setBuddy(self.edtRegionalCode)
        self.lblUsishCode.setBuddy(self.edtFederalCode)
        self.lblAltOtherService.setBuddy(self.cmbAltOtherService)
        self.lblAltProvinceService.setBuddy(self.cmbAltProvinceService)
        self.lblCode.setBuddy(self.edtCode)
        self.lblMKBFilter.setBuddy(self.edtMKBFilter)
        self.lblName.setBuddy(self.edtName)
        self.lblAgeSep.setBuddy(self.cmbEndAgeUnit)
        self.lblMedicalAidProfile.setBuddy(self.cmbMedicalAidProfile)

        self.retranslateUi(ItemEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)
        ItemEditorDialog.setTabOrder(self.tabWidget, self.edtCode)
        ItemEditorDialog.setTabOrder(self.edtCode, self.edtName)
        ItemEditorDialog.setTabOrder(self.edtName, self.edtOKSOName)
        ItemEditorDialog.setTabOrder(self.edtOKSOName, self.edtOKSOCode)
        ItemEditorDialog.setTabOrder(self.edtOKSOCode, self.edtFederalCode)
        ItemEditorDialog.setTabOrder(self.edtFederalCode, self.edtUsishCode)
        ItemEditorDialog.setTabOrder(self.edtUsishCode, self.edtRegionalCode)
        ItemEditorDialog.setTabOrder(self.edtRegionalCode, self.cmbLocalService)
        ItemEditorDialog.setTabOrder(self.cmbLocalService, self.btnSelectLocalService)
        ItemEditorDialog.setTabOrder(self.btnSelectLocalService, self.cmbProvinceService)
        ItemEditorDialog.setTabOrder(self.cmbProvinceService, self.btnSelectProvinceService)
        ItemEditorDialog.setTabOrder(self.btnSelectProvinceService, self.cmbOtherService)
        ItemEditorDialog.setTabOrder(self.cmbOtherService, self.btnSelectOtherService)
        ItemEditorDialog.setTabOrder(self.btnSelectOtherService, self.cmbAltLocalService)
        ItemEditorDialog.setTabOrder(self.cmbAltLocalService, self.btnSelectAltLocalService)
        ItemEditorDialog.setTabOrder(self.btnSelectAltLocalService, self.cmbAltProvinceService)
        ItemEditorDialog.setTabOrder(self.cmbAltProvinceService, self.btnSelectAltProvinceService)
        ItemEditorDialog.setTabOrder(self.btnSelectAltProvinceService, self.cmbAltOtherService)
        ItemEditorDialog.setTabOrder(self.cmbAltOtherService, self.btnAltSelectOtherService)
        ItemEditorDialog.setTabOrder(self.btnAltSelectOtherService, self.cmbSex)
        ItemEditorDialog.setTabOrder(self.cmbSex, self.cmbBegAgeUnit)
        ItemEditorDialog.setTabOrder(self.cmbBegAgeUnit, self.edtBegAgeCount)
        ItemEditorDialog.setTabOrder(self.edtBegAgeCount, self.cmbEndAgeUnit)
        ItemEditorDialog.setTabOrder(self.cmbEndAgeUnit, self.edtEndAgeCount)
        ItemEditorDialog.setTabOrder(self.edtEndAgeCount, self.edtMKBFilter)
        ItemEditorDialog.setTabOrder(self.edtMKBFilter, self.tblMedicalAidProfiles)
        ItemEditorDialog.setTabOrder(self.tblMedicalAidProfiles, self.tblIdentification)
        ItemEditorDialog.setTabOrder(self.tblIdentification, self.buttonBox)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(_translate("ItemEditorDialog", "ChangeMe!", None))
        self.lblOtherService.setText(_translate("ItemEditorDialog", "Услуга для прочего населения", None))
        self.lblSex.setText(_translate("ItemEditorDialog", "&Пол", None))
        self.cmbSex.setItemText(1, _translate("ItemEditorDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("ItemEditorDialog", "Ж", None))
        self.lblAge.setText(_translate("ItemEditorDialog", "&Возраст", None))
        self.btnSelectLocalService.setText(_translate("ItemEditorDialog", "...", None))
        self.lblOKSOName.setText(_translate("ItemEditorDialog", "Наименование по ОКСО", None))
        self.btnSelectAltLocalService.setText(_translate("ItemEditorDialog", "...", None))
        self.lblFederalCode.setText(_translate("ItemEditorDialog", "&Федеральный код", None))
        self.lblOKSOCode.setText(_translate("ItemEditorDialog", "Код по &ОКСО", None))
        self.lblProvinceService.setText(_translate("ItemEditorDialog", "Услуга для областного населения", None))
        self.lblLocalService.setText(_translate("ItemEditorDialog", "&Услуга для местного населения", None))
        self.btnSelectAltProvinceService.setText(_translate("ItemEditorDialog", "...", None))
        self.lblAltLocalService.setText(_translate("ItemEditorDialog", "Альтернативная услуга для местного населения", None))
        self.lblRegionalCode.setText(_translate("ItemEditorDialog", "&Региональный код", None))
        self.btnSelectOtherService.setText(_translate("ItemEditorDialog", "...", None))
        self.lblUsishCode.setText(_translate("ItemEditorDialog", "Код &ЕГИСЗ", None))
        self.lblAltOtherService.setText(_translate("ItemEditorDialog", "Альтернативная услуга для прочего населения", None))
        self.btnSelectProvinceService.setText(_translate("ItemEditorDialog", "...", None))
        self.btnAltSelectOtherService.setText(_translate("ItemEditorDialog", "...", None))
        self.lblAltProvinceService.setText(_translate("ItemEditorDialog", "Альтернативная услуга для областного населения", None))
        self.lblCode.setText(_translate("ItemEditorDialog", "&Код", None))
        self.lblMKBFilter.setText(_translate("ItemEditorDialog", "&Фильтр диагнозов по МКБ", None))
        self.lblName.setText(_translate("ItemEditorDialog", "&Наименование", None))
        self.cmbBegAgeUnit.setItemText(1, _translate("ItemEditorDialog", "Д", None))
        self.cmbBegAgeUnit.setItemText(2, _translate("ItemEditorDialog", "Н", None))
        self.cmbBegAgeUnit.setItemText(3, _translate("ItemEditorDialog", "М", None))
        self.cmbBegAgeUnit.setItemText(4, _translate("ItemEditorDialog", "Г", None))
        self.edtBegAgeCount.setInputMask(_translate("ItemEditorDialog", "000; ", None))
        self.lblAgeSep.setText(_translate("ItemEditorDialog", "по", None))
        self.cmbEndAgeUnit.setItemText(1, _translate("ItemEditorDialog", "Д", None))
        self.cmbEndAgeUnit.setItemText(2, _translate("ItemEditorDialog", "Н", None))
        self.cmbEndAgeUnit.setItemText(3, _translate("ItemEditorDialog", "М", None))
        self.cmbEndAgeUnit.setItemText(4, _translate("ItemEditorDialog", "Г", None))
        self.edtEndAgeCount.setInputMask(_translate("ItemEditorDialog", "000; ", None))
        self.chkIsHigh.setText(_translate("ItemEditorDialog", "Является врачебной специальностью", None))
        self.lblMedicalAidProfile.setText(_translate("ItemEditorDialog", "Профиль МП", None))
        self.btnSelectAmbAppointmentService.setText(_translate("ItemEditorDialog", "...", None))
        self.lblAmbAppointmentService.setText(_translate("ItemEditorDialog", "Услуга для сервиса записи на амбулаторный прием", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("ItemEditorDialog", "&Основная информация", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMedicalAidProfiles), _translate("ItemEditorDialog", "&Профили мед.помощи", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIdentification), _translate("ItemEditorDialog", "&Идентификация", None))

from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
