# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\Samson\UP_s11\client\RefBooks\Equipment\RBEquipmentEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RBEquipmentEditorDialog(object):
    def setupUi(self, RBEquipmentEditorDialog):
        RBEquipmentEditorDialog.setObjectName(_fromUtf8("RBEquipmentEditorDialog"))
        RBEquipmentEditorDialog.resize(912, 668)
        self.gridLayout_2 = QtGui.QGridLayout(RBEquipmentEditorDialog)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.buttonBox = QtGui.QDialogButtonBox(RBEquipmentEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(RBEquipmentEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabEquipment = QtGui.QWidget()
        self.tabEquipment.setObjectName(_fromUtf8("tabEquipment"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabEquipment)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.widget = QtGui.QWidget(self.tabEquipment)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edtMaintenancePeriod = QtGui.QSpinBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMaintenancePeriod.sizePolicy().hasHeightForWidth())
        self.edtMaintenancePeriod.setSizePolicy(sizePolicy)
        self.edtMaintenancePeriod.setObjectName(_fromUtf8("edtMaintenancePeriod"))
        self.gridLayout.addWidget(self.edtMaintenancePeriod, 0, 0, 1, 1)
        self.lblMaintenanceSingleInPeriod = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMaintenanceSingleInPeriod.sizePolicy().hasHeightForWidth())
        self.lblMaintenanceSingleInPeriod.setSizePolicy(sizePolicy)
        self.lblMaintenanceSingleInPeriod.setObjectName(_fromUtf8("lblMaintenanceSingleInPeriod"))
        self.gridLayout.addWidget(self.lblMaintenanceSingleInPeriod, 0, 1, 1, 1)
        self.cmbMaintenanceSingleInPeriod = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMaintenanceSingleInPeriod.sizePolicy().hasHeightForWidth())
        self.cmbMaintenanceSingleInPeriod.setSizePolicy(sizePolicy)
        self.cmbMaintenanceSingleInPeriod.setObjectName(_fromUtf8("cmbMaintenanceSingleInPeriod"))
        self.cmbMaintenanceSingleInPeriod.addItem(_fromUtf8(""))
        self.cmbMaintenanceSingleInPeriod.addItem(_fromUtf8(""))
        self.cmbMaintenanceSingleInPeriod.addItem(_fromUtf8(""))
        self.cmbMaintenanceSingleInPeriod.addItem(_fromUtf8(""))
        self.cmbMaintenanceSingleInPeriod.addItem(_fromUtf8(""))
        self.cmbMaintenanceSingleInPeriod.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbMaintenanceSingleInPeriod, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 15, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 18, 0, 1, 1)
        self.lblEquipmentClass = QtGui.QLabel(self.tabEquipment)
        self.lblEquipmentClass.setObjectName(_fromUtf8("lblEquipmentClass"))
        self.gridLayout_3.addWidget(self.lblEquipmentClass, 2, 0, 1, 1)
        self.edtManufacturer = QtGui.QLineEdit(self.tabEquipment)
        self.edtManufacturer.setObjectName(_fromUtf8("edtManufacturer"))
        self.gridLayout_3.addWidget(self.edtManufacturer, 16, 1, 1, 2)
        self.cmbSamplePreparation = QtGui.QComboBox(self.tabEquipment)
        self.cmbSamplePreparation.setObjectName(_fromUtf8("cmbSamplePreparation"))
        self.cmbSamplePreparation.addItem(_fromUtf8(""))
        self.cmbSamplePreparation.addItem(_fromUtf8(""))
        self.cmbSamplePreparation.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbSamplePreparation, 17, 1, 1, 2)
        self.lblManufacturer = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblManufacturer.sizePolicy().hasHeightForWidth())
        self.lblManufacturer.setSizePolicy(sizePolicy)
        self.lblManufacturer.setObjectName(_fromUtf8("lblManufacturer"))
        self.gridLayout_3.addWidget(self.lblManufacturer, 16, 0, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(self.tabEquipment)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout_3.addWidget(self.lblOrgStructure, 4, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(self.tabEquipment)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout_3.addWidget(self.cmbOrgStructure, 4, 1, 1, 2)
        self.lblCode = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout_3.addWidget(self.lblCode, 0, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(self.tabEquipment)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout_3.addWidget(self.edtName, 1, 1, 1, 2)
        self.edtCode = QtGui.QLineEdit(self.tabEquipment)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout_3.addWidget(self.edtCode, 0, 1, 1, 2)
        self.lblName = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout_3.addWidget(self.lblName, 1, 0, 1, 1)
        self.lblSamplePreparation = QtGui.QLabel(self.tabEquipment)
        self.lblSamplePreparation.setObjectName(_fromUtf8("lblSamplePreparation"))
        self.gridLayout_3.addWidget(self.lblSamplePreparation, 17, 0, 1, 1)
        self.cmbEquipmentType = CRBComboBox(self.tabEquipment)
        self.cmbEquipmentType.setObjectName(_fromUtf8("cmbEquipmentType"))
        self.gridLayout_3.addWidget(self.cmbEquipmentType, 3, 1, 1, 2)
        self.lblTripod = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTripod.sizePolicy().hasHeightForWidth())
        self.lblTripod.setSizePolicy(sizePolicy)
        self.lblTripod.setObjectName(_fromUtf8("lblTripod"))
        self.gridLayout_3.addWidget(self.lblTripod, 5, 0, 1, 1)
        self.edtTripod = QtGui.QSpinBox(self.tabEquipment)
        self.edtTripod.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTripod.sizePolicy().hasHeightForWidth())
        self.edtTripod.setSizePolicy(sizePolicy)
        self.edtTripod.setMaximum(100000)
        self.edtTripod.setObjectName(_fromUtf8("edtTripod"))
        self.gridLayout_3.addWidget(self.edtTripod, 5, 1, 1, 1)
        self.lblEquipmentType = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEquipmentType.sizePolicy().hasHeightForWidth())
        self.lblEquipmentType.setSizePolicy(sizePolicy)
        self.lblEquipmentType.setObjectName(_fromUtf8("lblEquipmentType"))
        self.gridLayout_3.addWidget(self.lblEquipmentType, 3, 0, 1, 1)
        self.edtTripodCapacity = QtGui.QSpinBox(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtTripodCapacity.sizePolicy().hasHeightForWidth())
        self.edtTripodCapacity.setSizePolicy(sizePolicy)
        self.edtTripodCapacity.setMaximum(100000)
        self.edtTripodCapacity.setObjectName(_fromUtf8("edtTripodCapacity"))
        self.gridLayout_3.addWidget(self.edtTripodCapacity, 6, 1, 1, 1)
        self.lblInventoryNumber = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInventoryNumber.sizePolicy().hasHeightForWidth())
        self.lblInventoryNumber.setSizePolicy(sizePolicy)
        self.lblInventoryNumber.setObjectName(_fromUtf8("lblInventoryNumber"))
        self.gridLayout_3.addWidget(self.lblInventoryNumber, 7, 0, 1, 1)
        self.edtModel = QtGui.QLineEdit(self.tabEquipment)
        self.edtModel.setObjectName(_fromUtf8("edtModel"))
        self.gridLayout_3.addWidget(self.edtModel, 8, 1, 1, 2)
        self.edtTripodIdentifiers = QtGui.QLineEdit(self.tabEquipment)
        self.edtTripodIdentifiers.setObjectName(_fromUtf8("edtTripodIdentifiers"))
        self.gridLayout_3.addWidget(self.edtTripodIdentifiers, 5, 2, 1, 1)
        self.lblTripodCapacity = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTripodCapacity.sizePolicy().hasHeightForWidth())
        self.lblTripodCapacity.setSizePolicy(sizePolicy)
        self.lblTripodCapacity.setObjectName(_fromUtf8("lblTripodCapacity"))
        self.gridLayout_3.addWidget(self.lblTripodCapacity, 6, 0, 1, 1)
        self.cmbEquipmentClass = CRBComboBox(self.tabEquipment)
        self.cmbEquipmentClass.setObjectName(_fromUtf8("cmbEquipmentClass"))
        self.gridLayout_3.addWidget(self.cmbEquipmentClass, 2, 1, 1, 2)
        self.lblReleaseDate = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblReleaseDate.sizePolicy().hasHeightForWidth())
        self.lblReleaseDate.setSizePolicy(sizePolicy)
        self.lblReleaseDate.setObjectName(_fromUtf8("lblReleaseDate"))
        self.gridLayout_3.addWidget(self.lblReleaseDate, 10, 0, 1, 1)
        self.edtReleaseDate = CDateEdit(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtReleaseDate.sizePolicy().hasHeightForWidth())
        self.edtReleaseDate.setSizePolicy(sizePolicy)
        self.edtReleaseDate.setObjectName(_fromUtf8("edtReleaseDate"))
        self.gridLayout_3.addWidget(self.edtReleaseDate, 10, 1, 1, 2)
        self.lblModel = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblModel.sizePolicy().hasHeightForWidth())
        self.lblModel.setSizePolicy(sizePolicy)
        self.lblModel.setObjectName(_fromUtf8("lblModel"))
        self.gridLayout_3.addWidget(self.lblModel, 8, 0, 1, 1)
        self.edtInventoryNumber = QtGui.QLineEdit(self.tabEquipment)
        self.edtInventoryNumber.setObjectName(_fromUtf8("edtInventoryNumber"))
        self.gridLayout_3.addWidget(self.edtInventoryNumber, 7, 1, 1, 2)
        self.edtStartupDate = CDateEdit(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtStartupDate.sizePolicy().hasHeightForWidth())
        self.edtStartupDate.setSizePolicy(sizePolicy)
        self.edtStartupDate.setObjectName(_fromUtf8("edtStartupDate"))
        self.gridLayout_3.addWidget(self.edtStartupDate, 11, 1, 1, 2)
        self.cmbStatus = QtGui.QComboBox(self.tabEquipment)
        self.cmbStatus.setObjectName(_fromUtf8("cmbStatus"))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.cmbStatus.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cmbStatus, 12, 1, 1, 2)
        self.lblStartupDate = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStartupDate.sizePolicy().hasHeightForWidth())
        self.lblStartupDate.setSizePolicy(sizePolicy)
        self.lblStartupDate.setObjectName(_fromUtf8("lblStartupDate"))
        self.gridLayout_3.addWidget(self.lblStartupDate, 11, 0, 1, 1)
        self.lblStatus = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.gridLayout_3.addWidget(self.lblStatus, 12, 0, 1, 1)
        self.lblWarrantyTerm = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblWarrantyTerm.sizePolicy().hasHeightForWidth())
        self.lblWarrantyTerm.setSizePolicy(sizePolicy)
        self.lblWarrantyTerm.setObjectName(_fromUtf8("lblWarrantyTerm"))
        self.gridLayout_3.addWidget(self.lblWarrantyTerm, 14, 0, 1, 1)
        self.edtEmploymentTerm = QtGui.QSpinBox(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEmploymentTerm.sizePolicy().hasHeightForWidth())
        self.edtEmploymentTerm.setSizePolicy(sizePolicy)
        self.edtEmploymentTerm.setObjectName(_fromUtf8("edtEmploymentTerm"))
        self.gridLayout_3.addWidget(self.edtEmploymentTerm, 13, 1, 1, 1)
        self.lblEmploymentTerm = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEmploymentTerm.sizePolicy().hasHeightForWidth())
        self.lblEmploymentTerm.setSizePolicy(sizePolicy)
        self.lblEmploymentTerm.setObjectName(_fromUtf8("lblEmploymentTerm"))
        self.gridLayout_3.addWidget(self.lblEmploymentTerm, 13, 0, 1, 1)
        self.edtWarrantyTerm = QtGui.QSpinBox(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtWarrantyTerm.sizePolicy().hasHeightForWidth())
        self.edtWarrantyTerm.setSizePolicy(sizePolicy)
        self.edtWarrantyTerm.setObjectName(_fromUtf8("edtWarrantyTerm"))
        self.gridLayout_3.addWidget(self.edtWarrantyTerm, 14, 1, 1, 1)
        self.lblMaintenancePeriod = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMaintenancePeriod.sizePolicy().hasHeightForWidth())
        self.lblMaintenancePeriod.setSizePolicy(sizePolicy)
        self.lblMaintenancePeriod.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblMaintenancePeriod.setFrameShadow(QtGui.QFrame.Plain)
        self.lblMaintenancePeriod.setLineWidth(1)
        self.lblMaintenancePeriod.setObjectName(_fromUtf8("lblMaintenancePeriod"))
        self.gridLayout_3.addWidget(self.lblMaintenancePeriod, 15, 0, 1, 1)
        self.lblSerialNumber = QtGui.QLabel(self.tabEquipment)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSerialNumber.sizePolicy().hasHeightForWidth())
        self.lblSerialNumber.setSizePolicy(sizePolicy)
        self.lblSerialNumber.setObjectName(_fromUtf8("lblSerialNumber"))
        self.gridLayout_3.addWidget(self.lblSerialNumber, 9, 0, 1, 1)
        self.edtSerialNumber = QtGui.QLineEdit(self.tabEquipment)
        self.edtSerialNumber.setObjectName(_fromUtf8("edtSerialNumber"))
        self.gridLayout_3.addWidget(self.edtSerialNumber, 9, 1, 1, 2)
        self.tabWidget.addTab(self.tabEquipment, _fromUtf8(""))
        self.tabInterface = QtGui.QWidget()
        self.tabInterface.setObjectName(_fromUtf8("tabInterface"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabInterface)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lblProtocol = QtGui.QLabel(self.tabInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProtocol.sizePolicy().hasHeightForWidth())
        self.lblProtocol.setSizePolicy(sizePolicy)
        self.lblProtocol.setObjectName(_fromUtf8("lblProtocol"))
        self.gridLayout_5.addWidget(self.lblProtocol, 1, 0, 1, 1)
        self.cmbProtocol = QtGui.QComboBox(self.tabInterface)
        self.cmbProtocol.setObjectName(_fromUtf8("cmbProtocol"))
        self.cmbProtocol.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cmbProtocol, 1, 1, 1, 1)
        self.lblAddress = QtGui.QLabel(self.tabInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAddress.sizePolicy().hasHeightForWidth())
        self.lblAddress.setSizePolicy(sizePolicy)
        self.lblAddress.setObjectName(_fromUtf8("lblAddress"))
        self.gridLayout_5.addWidget(self.lblAddress, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 141, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 4, 0, 1, 1)
        self.edtAddress = QtGui.QTextEdit(self.tabInterface)
        self.edtAddress.setObjectName(_fromUtf8("edtAddress"))
        self.gridLayout_5.addWidget(self.edtAddress, 3, 1, 2, 1)
        self.lblOwnName = QtGui.QLabel(self.tabInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOwnName.sizePolicy().hasHeightForWidth())
        self.lblOwnName.setSizePolicy(sizePolicy)
        self.lblOwnName.setObjectName(_fromUtf8("lblOwnName"))
        self.gridLayout_5.addWidget(self.lblOwnName, 5, 0, 1, 1)
        self.edtOwnName = QtGui.QLineEdit(self.tabInterface)
        self.edtOwnName.setObjectName(_fromUtf8("edtOwnName"))
        self.gridLayout_5.addWidget(self.edtOwnName, 5, 1, 1, 1)
        self.lblOwnCode = QtGui.QLabel(self.tabInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOwnCode.sizePolicy().hasHeightForWidth())
        self.lblOwnCode.setSizePolicy(sizePolicy)
        self.lblOwnCode.setObjectName(_fromUtf8("lblOwnCode"))
        self.gridLayout_5.addWidget(self.lblOwnCode, 6, 0, 1, 1)
        self.edtOwnCode = QtGui.QLineEdit(self.tabInterface)
        self.edtOwnCode.setMaxLength(16)
        self.edtOwnCode.setObjectName(_fromUtf8("edtOwnCode"))
        self.gridLayout_5.addWidget(self.edtOwnCode, 6, 1, 1, 1)
        self.lblLabName = QtGui.QLabel(self.tabInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLabName.sizePolicy().hasHeightForWidth())
        self.lblLabName.setSizePolicy(sizePolicy)
        self.lblLabName.setObjectName(_fromUtf8("lblLabName"))
        self.gridLayout_5.addWidget(self.lblLabName, 7, 0, 1, 1)
        self.edtLabName = QtGui.QLineEdit(self.tabInterface)
        self.edtLabName.setObjectName(_fromUtf8("edtLabName"))
        self.gridLayout_5.addWidget(self.edtLabName, 7, 1, 1, 1)
        self.lblLabCode = QtGui.QLabel(self.tabInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLabCode.sizePolicy().hasHeightForWidth())
        self.lblLabCode.setSizePolicy(sizePolicy)
        self.lblLabCode.setObjectName(_fromUtf8("lblLabCode"))
        self.gridLayout_5.addWidget(self.lblLabCode, 8, 0, 1, 1)
        self.edtLabCode = QtGui.QLineEdit(self.tabInterface)
        self.edtLabCode.setMaxLength(16)
        self.edtLabCode.setObjectName(_fromUtf8("edtLabCode"))
        self.gridLayout_5.addWidget(self.edtLabCode, 8, 1, 1, 1)
        self.lblSpecimenIdentifierMode = QtGui.QLabel(self.tabInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSpecimenIdentifierMode.sizePolicy().hasHeightForWidth())
        self.lblSpecimenIdentifierMode.setSizePolicy(sizePolicy)
        self.lblSpecimenIdentifierMode.setObjectName(_fromUtf8("lblSpecimenIdentifierMode"))
        self.gridLayout_5.addWidget(self.lblSpecimenIdentifierMode, 10, 0, 1, 1)
        self.cmbSpecimenIdentifierMode = QtGui.QComboBox(self.tabInterface)
        self.cmbSpecimenIdentifierMode.setObjectName(_fromUtf8("cmbSpecimenIdentifierMode"))
        self.cmbSpecimenIdentifierMode.addItem(_fromUtf8(""))
        self.cmbSpecimenIdentifierMode.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cmbSpecimenIdentifierMode, 10, 1, 1, 1)
        self.chkResultOnFact = QtGui.QCheckBox(self.tabInterface)
        self.chkResultOnFact.setText(_fromUtf8(""))
        self.chkResultOnFact.setObjectName(_fromUtf8("chkResultOnFact"))
        self.gridLayout_5.addWidget(self.chkResultOnFact, 13, 1, 1, 1)
        self.lblResultOnFact = QtGui.QLabel(self.tabInterface)
        self.lblResultOnFact.setObjectName(_fromUtf8("lblResultOnFact"))
        self.gridLayout_5.addWidget(self.lblResultOnFact, 13, 0, 1, 1)
        self.lblProtocolVersion = QtGui.QLabel(self.tabInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProtocolVersion.sizePolicy().hasHeightForWidth())
        self.lblProtocolVersion.setSizePolicy(sizePolicy)
        self.lblProtocolVersion.setObjectName(_fromUtf8("lblProtocolVersion"))
        self.gridLayout_5.addWidget(self.lblProtocolVersion, 2, 0, 1, 1)
        self.lblRoleInIntegration = QtGui.QLabel(self.tabInterface)
        self.lblRoleInIntegration.setObjectName(_fromUtf8("lblRoleInIntegration"))
        self.gridLayout_5.addWidget(self.lblRoleInIntegration, 14, 0, 1, 1)
        self.cmbRoleInIntegration = QtGui.QComboBox(self.tabInterface)
        self.cmbRoleInIntegration.setObjectName(_fromUtf8("cmbRoleInIntegration"))
        self.cmbRoleInIntegration.addItem(_fromUtf8(""))
        self.cmbRoleInIntegration.addItem(_fromUtf8(""))
        self.cmbRoleInIntegration.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cmbRoleInIntegration, 14, 1, 1, 1)
        self.edtProtocolVersion = QtGui.QLineEdit(self.tabInterface)
        self.edtProtocolVersion.setObjectName(_fromUtf8("edtProtocolVersion"))
        self.gridLayout_5.addWidget(self.edtProtocolVersion, 2, 1, 1, 1)
        self.lblEachTestDetached = QtGui.QLabel(self.tabInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEachTestDetached.sizePolicy().hasHeightForWidth())
        self.lblEachTestDetached.setSizePolicy(sizePolicy)
        self.lblEachTestDetached.setObjectName(_fromUtf8("lblEachTestDetached"))
        self.gridLayout_5.addWidget(self.lblEachTestDetached, 9, 0, 1, 1)
        self.chkEachTestDetached = QtGui.QCheckBox(self.tabInterface)
        self.chkEachTestDetached.setText(_fromUtf8(""))
        self.chkEachTestDetached.setObjectName(_fromUtf8("chkEachTestDetached"))
        self.gridLayout_5.addWidget(self.chkEachTestDetached, 9, 1, 1, 1)
        self.tabWidget.addTab(self.tabInterface, _fromUtf8(""))
        self.tabTests = QtGui.QWidget()
        self.tabTests.setObjectName(_fromUtf8("tabTests"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabTests)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblTests = CInDocTableView(self.tabTests)
        self.tblTests.setObjectName(_fromUtf8("tblTests"))
        self.gridLayout_4.addWidget(self.tblTests, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabTests, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.lblMaintenanceSingleInPeriod.setBuddy(self.cmbMaintenanceSingleInPeriod)
        self.lblManufacturer.setBuddy(self.edtManufacturer)
        self.lblCode.setBuddy(self.edtCode)
        self.lblName.setBuddy(self.edtName)
        self.lblTripod.setBuddy(self.edtTripod)
        self.lblEquipmentType.setBuddy(self.cmbEquipmentType)
        self.lblInventoryNumber.setBuddy(self.edtInventoryNumber)
        self.lblTripodCapacity.setBuddy(self.edtTripodCapacity)
        self.lblReleaseDate.setBuddy(self.edtReleaseDate)
        self.lblModel.setBuddy(self.edtModel)
        self.lblStartupDate.setBuddy(self.edtStartupDate)
        self.lblStatus.setBuddy(self.cmbStatus)
        self.lblWarrantyTerm.setBuddy(self.edtWarrantyTerm)
        self.lblEmploymentTerm.setBuddy(self.edtEmploymentTerm)
        self.lblMaintenancePeriod.setBuddy(self.edtMaintenancePeriod)
        self.lblSerialNumber.setBuddy(self.edtModel)
        self.lblProtocol.setBuddy(self.cmbProtocol)
        self.lblAddress.setBuddy(self.edtAddress)
        self.lblOwnName.setBuddy(self.edtOwnName)
        self.lblOwnCode.setBuddy(self.edtOwnCode)
        self.lblLabName.setBuddy(self.edtLabName)
        self.lblLabCode.setBuddy(self.edtLabCode)
        self.lblSpecimenIdentifierMode.setBuddy(self.cmbSpecimenIdentifierMode)
        self.lblResultOnFact.setBuddy(self.chkResultOnFact)
        self.lblProtocolVersion.setBuddy(self.edtProtocolVersion)
        self.lblRoleInIntegration.setBuddy(self.cmbRoleInIntegration)
        self.lblEachTestDetached.setBuddy(self.chkEachTestDetached)

        self.retranslateUi(RBEquipmentEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), RBEquipmentEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), RBEquipmentEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RBEquipmentEditorDialog)
        RBEquipmentEditorDialog.setTabOrder(self.tabWidget, self.edtCode)
        RBEquipmentEditorDialog.setTabOrder(self.edtCode, self.edtName)
        RBEquipmentEditorDialog.setTabOrder(self.edtName, self.cmbEquipmentClass)
        RBEquipmentEditorDialog.setTabOrder(self.cmbEquipmentClass, self.cmbEquipmentType)
        RBEquipmentEditorDialog.setTabOrder(self.cmbEquipmentType, self.cmbOrgStructure)
        RBEquipmentEditorDialog.setTabOrder(self.cmbOrgStructure, self.edtTripod)
        RBEquipmentEditorDialog.setTabOrder(self.edtTripod, self.edtTripodIdentifiers)
        RBEquipmentEditorDialog.setTabOrder(self.edtTripodIdentifiers, self.edtTripodCapacity)
        RBEquipmentEditorDialog.setTabOrder(self.edtTripodCapacity, self.edtInventoryNumber)
        RBEquipmentEditorDialog.setTabOrder(self.edtInventoryNumber, self.edtModel)
        RBEquipmentEditorDialog.setTabOrder(self.edtModel, self.edtReleaseDate)
        RBEquipmentEditorDialog.setTabOrder(self.edtReleaseDate, self.edtStartupDate)
        RBEquipmentEditorDialog.setTabOrder(self.edtStartupDate, self.cmbStatus)
        RBEquipmentEditorDialog.setTabOrder(self.cmbStatus, self.edtEmploymentTerm)
        RBEquipmentEditorDialog.setTabOrder(self.edtEmploymentTerm, self.edtWarrantyTerm)
        RBEquipmentEditorDialog.setTabOrder(self.edtWarrantyTerm, self.edtMaintenancePeriod)
        RBEquipmentEditorDialog.setTabOrder(self.edtMaintenancePeriod, self.cmbMaintenanceSingleInPeriod)
        RBEquipmentEditorDialog.setTabOrder(self.cmbMaintenanceSingleInPeriod, self.edtManufacturer)
        RBEquipmentEditorDialog.setTabOrder(self.edtManufacturer, self.cmbSamplePreparation)
        RBEquipmentEditorDialog.setTabOrder(self.cmbSamplePreparation, self.cmbProtocol)
        RBEquipmentEditorDialog.setTabOrder(self.cmbProtocol, self.edtProtocolVersion)
        RBEquipmentEditorDialog.setTabOrder(self.edtProtocolVersion, self.edtAddress)
        RBEquipmentEditorDialog.setTabOrder(self.edtAddress, self.edtOwnName)
        RBEquipmentEditorDialog.setTabOrder(self.edtOwnName, self.edtOwnCode)
        RBEquipmentEditorDialog.setTabOrder(self.edtOwnCode, self.edtLabName)
        RBEquipmentEditorDialog.setTabOrder(self.edtLabName, self.edtLabCode)
        RBEquipmentEditorDialog.setTabOrder(self.edtLabCode, self.chkEachTestDetached)
        RBEquipmentEditorDialog.setTabOrder(self.chkEachTestDetached, self.cmbSpecimenIdentifierMode)
        RBEquipmentEditorDialog.setTabOrder(self.cmbSpecimenIdentifierMode, self.chkResultOnFact)
        RBEquipmentEditorDialog.setTabOrder(self.chkResultOnFact, self.cmbRoleInIntegration)
        RBEquipmentEditorDialog.setTabOrder(self.cmbRoleInIntegration, self.tblTests)
        RBEquipmentEditorDialog.setTabOrder(self.tblTests, self.buttonBox)

    def retranslateUi(self, RBEquipmentEditorDialog):
        RBEquipmentEditorDialog.setWindowTitle(_translate("RBEquipmentEditorDialog", "Dialog", None))
        self.lblMaintenanceSingleInPeriod.setText(_translate("RBEquipmentEditorDialog", "или раз в", None))
        self.cmbMaintenanceSingleInPeriod.setItemText(0, _translate("RBEquipmentEditorDialog", "Нет", None))
        self.cmbMaintenanceSingleInPeriod.setItemText(1, _translate("RBEquipmentEditorDialog", "Неделя", None))
        self.cmbMaintenanceSingleInPeriod.setItemText(2, _translate("RBEquipmentEditorDialog", "Месяц", None))
        self.cmbMaintenanceSingleInPeriod.setItemText(3, _translate("RBEquipmentEditorDialog", "Квартал", None))
        self.cmbMaintenanceSingleInPeriod.setItemText(4, _translate("RBEquipmentEditorDialog", "Полугодие", None))
        self.cmbMaintenanceSingleInPeriod.setItemText(5, _translate("RBEquipmentEditorDialog", "Год", None))
        self.lblEquipmentClass.setText(_translate("RBEquipmentEditorDialog", "Класс оборудования", None))
        self.cmbSamplePreparation.setItemText(0, _translate("RBEquipmentEditorDialog", "ручная", None))
        self.cmbSamplePreparation.setItemText(1, _translate("RBEquipmentEditorDialog", "автоматическая", None))
        self.cmbSamplePreparation.setItemText(2, _translate("RBEquipmentEditorDialog", "не выполнять", None))
        self.lblManufacturer.setText(_translate("RBEquipmentEditorDialog", "Производитель", None))
        self.lblOrgStructure.setText(_translate("RBEquipmentEditorDialog", "Подразделение", None))
        self.lblCode.setText(_translate("RBEquipmentEditorDialog", "&Код", None))
        self.lblName.setText(_translate("RBEquipmentEditorDialog", "&Наименование", None))
        self.lblSamplePreparation.setText(_translate("RBEquipmentEditorDialog", "Пробоподготовка", None))
        self.lblTripod.setText(_translate("RBEquipmentEditorDialog", "Количество &штативов", None))
        self.lblEquipmentType.setText(_translate("RBEquipmentEditorDialog", "Т&ип оборудования", None))
        self.lblInventoryNumber.setText(_translate("RBEquipmentEditorDialog", "&Инвентаризационный номер", None))
        self.edtTripodIdentifiers.setToolTip(_translate("RBEquipmentEditorDialog", "Идентификаторы штативов, перечисленные через точку с запятой", None))
        self.lblTripodCapacity.setText(_translate("RBEquipmentEditorDialog", "Количество &мест в штативе", None))
        self.lblReleaseDate.setText(_translate("RBEquipmentEditorDialog", "Дата &выпуска", None))
        self.lblModel.setText(_translate("RBEquipmentEditorDialog", "Мо&дель", None))
        self.cmbStatus.setItemText(0, _translate("RBEquipmentEditorDialog", "Не работает", None))
        self.cmbStatus.setItemText(1, _translate("RBEquipmentEditorDialog", "Работает", None))
        self.lblStartupDate.setText(_translate("RBEquipmentEditorDialog", "Дата ввода в &эксплуатацию", None))
        self.lblStatus.setText(_translate("RBEquipmentEditorDialog", "&Статус", None))
        self.lblWarrantyTerm.setText(_translate("RBEquipmentEditorDialog", "Срок гарантии", None))
        self.lblEmploymentTerm.setText(_translate("RBEquipmentEditorDialog", "Срок службы", None))
        self.lblMaintenancePeriod.setText(_translate("RBEquipmentEditorDialog", "Период ТО (месяцев)", None))
        self.lblSerialNumber.setText(_translate("RBEquipmentEditorDialog", "Серийный номер", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEquipment), _translate("RBEquipmentEditorDialog", "&Оборудование", None))
        self.lblProtocol.setText(_translate("RBEquipmentEditorDialog", "&Протокол", None))
        self.cmbProtocol.setItemText(0, _translate("RBEquipmentEditorDialog", "сюда ничего не пишем!", None))
        self.lblAddress.setText(_translate("RBEquipmentEditorDialog", "&Адрес и другое специфическое для протокола", None))
        self.edtAddress.setToolTip(_translate("RBEquipmentEditorDialog", "<html><head/><body><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">URL для обмена базирующегося на SOAP;</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">JSON-описание параметров соединения,</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">например</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">{</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">outDir</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;/var/lab/exchange/out&quot;,</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">inDir</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;/var/lab/exchange/in&quot;,</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">outPrefix</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;req&quot;,</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">inPrefix</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;req&quot;,</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">outDataExt</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;.req&quot;,</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">inDataExt</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;.req&quot;,</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">outSignalExt</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;.ok&quot;, </span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">inSignalExt</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;.ok&quot;, </span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">encoding</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;cp1251&quot;,</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">uniTestId</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;1&quot;,</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">testCode</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;1&quot;,</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">uniTestName</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;1&quot;,</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">processingId</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;P&quot;,</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">extendedValues</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;0&quot;,</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;</span><span style=\" font-family:\'Tahoma\'; font-size:8pt; font-weight:600;\">appendIbmIntoFileName</span><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">&quot;:&quot;0&quot;</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">}</span></p><p><span style=\" font-family:\'Tahoma\'; font-size:8pt;\">для файлового обмена по протоколу ASTM E-1381</span></p></body></html>", None))
        self.lblOwnName.setText(_translate("RBEquipmentEditorDialog", "Наименование &своей стороны", None))
        self.edtOwnName.setToolTip(_translate("RBEquipmentEditorDialog", "Если про протоколу требуется \"представиться\"", None))
        self.lblOwnCode.setText(_translate("RBEquipmentEditorDialog", "Код своей стороны", None))
        self.lblLabName.setText(_translate("RBEquipmentEditorDialog", "Наименование стороны &ЛИС", None))
        self.edtLabName.setToolTip(_translate("RBEquipmentEditorDialog", "Если по протоколу требуется \"назвать\" другую сторону", None))
        self.lblLabCode.setText(_translate("RBEquipmentEditorDialog", "Код стороны ЛИС", None))
        self.lblSpecimenIdentifierMode.setText(_translate("RBEquipmentEditorDialog", "&Режим идентификации образца", None))
        self.cmbSpecimenIdentifierMode.setItemText(0, _translate("RBEquipmentEditorDialog", "Идентификационный", None))
        self.cmbSpecimenIdentifierMode.setItemText(1, _translate("RBEquipmentEditorDialog", "Позиционный", None))
        self.lblResultOnFact.setText(_translate("RBEquipmentEditorDialog", "Результат предоставляется по &выполнении всего Заказа", None))
        self.lblProtocolVersion.setText(_translate("RBEquipmentEditorDialog", "&Версия протокола", None))
        self.lblRoleInIntegration.setText(_translate("RBEquipmentEditorDialog", "Роль в интеграции", None))
        self.cmbRoleInIntegration.setItemText(0, _translate("RBEquipmentEditorDialog", "Связь с внешней КДЛ (результаты которой не нужно передавать в ОДЛИ)", None))
        self.cmbRoleInIntegration.setItemText(1, _translate("RBEquipmentEditorDialog", "Локальная КДЛ (результаты которой нужно передавать в ОДЛИ)", None))
        self.cmbRoleInIntegration.setItemText(2, _translate("RBEquipmentEditorDialog", "Шлюз в ОДЛИ (получатель результатов, источник заказов)", None))
        self.lblEachTestDetached.setText(_translate("RBEquipmentEditorDialog", "Формировать для каждого теста &отдельное задание", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInterface), _translate("RBEquipmentEditorDialog", "&Интерфейс", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTests), _translate("RBEquipmentEditorDialog", "&Тесты", None))

from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from library.DateEdit import CDateEdit
from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
