# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\Samson\UP_s11\client\Surveillance\SurveillanceDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SurveillanceDialog(object):
    def setupUi(self, SurveillanceDialog):
        SurveillanceDialog.setObjectName(_fromUtf8("SurveillanceDialog"))
        SurveillanceDialog.resize(1163, 1061)
        self.gridLayout_2 = QtGui.QGridLayout(SurveillanceDialog)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.buttonBox = QtGui.QDialogButtonBox(SurveillanceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(SurveillanceDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1153, 1022))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setMargin(4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.splitter_2 = QtGui.QSplitter(self.scrollAreaWidgetContents_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.tabFilter = QtGui.QWidget(self.splitter_2)
        self.tabFilter.setObjectName(_fromUtf8("tabFilter"))
        self.gridLayout = QtGui.QGridLayout(self.tabFilter)
        self.gridLayout.setMargin(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbSocStatusesClass = CSocStatusComboBox(self.tabFilter)
        self.cmbSocStatusesClass.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSocStatusesClass.sizePolicy().hasHeightForWidth())
        self.cmbSocStatusesClass.setSizePolicy(sizePolicy)
        self.cmbSocStatusesClass.setObjectName(_fromUtf8("cmbSocStatusesClass"))
        self.gridLayout.addWidget(self.cmbSocStatusesClass, 25, 2, 1, 4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.edtFilterDeathBegDate = CDateEdit(self.tabFilter)
        self.edtFilterDeathBegDate.setEnabled(False)
        self.edtFilterDeathBegDate.setCalendarPopup(True)
        self.edtFilterDeathBegDate.setObjectName(_fromUtf8("edtFilterDeathBegDate"))
        self.horizontalLayout_6.addWidget(self.edtFilterDeathBegDate)
        self.lblFilterDeathPeriod = QtGui.QLabel(self.tabFilter)
        self.lblFilterDeathPeriod.setObjectName(_fromUtf8("lblFilterDeathPeriod"))
        self.horizontalLayout_6.addWidget(self.lblFilterDeathPeriod)
        self.edtFilterDeathEndDate = CDateEdit(self.tabFilter)
        self.edtFilterDeathEndDate.setEnabled(False)
        self.edtFilterDeathEndDate.setCalendarPopup(True)
        self.edtFilterDeathEndDate.setObjectName(_fromUtf8("edtFilterDeathEndDate"))
        self.horizontalLayout_6.addWidget(self.edtFilterDeathEndDate)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_6, 14, 2, 1, 4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblFilterAddressHouse = QtGui.QLabel(self.tabFilter)
        self.lblFilterAddressHouse.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFilterAddressHouse.setObjectName(_fromUtf8("lblFilterAddressHouse"))
        self.horizontalLayout_2.addWidget(self.lblFilterAddressHouse)
        self.edtFilterAddressHouse = QtGui.QLineEdit(self.tabFilter)
        self.edtFilterAddressHouse.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterAddressHouse.sizePolicy().hasHeightForWidth())
        self.edtFilterAddressHouse.setSizePolicy(sizePolicy)
        self.edtFilterAddressHouse.setObjectName(_fromUtf8("edtFilterAddressHouse"))
        self.horizontalLayout_2.addWidget(self.edtFilterAddressHouse)
        self.lblFilterAddressCorpus = QtGui.QLabel(self.tabFilter)
        self.lblFilterAddressCorpus.setObjectName(_fromUtf8("lblFilterAddressCorpus"))
        self.horizontalLayout_2.addWidget(self.lblFilterAddressCorpus)
        self.edtFilterAddressCorpus = QtGui.QLineEdit(self.tabFilter)
        self.edtFilterAddressCorpus.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterAddressCorpus.sizePolicy().hasHeightForWidth())
        self.edtFilterAddressCorpus.setSizePolicy(sizePolicy)
        self.edtFilterAddressCorpus.setObjectName(_fromUtf8("edtFilterAddressCorpus"))
        self.horizontalLayout_2.addWidget(self.edtFilterAddressCorpus)
        self.lblFilterAddressFlat = QtGui.QLabel(self.tabFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFilterAddressFlat.sizePolicy().hasHeightForWidth())
        self.lblFilterAddressFlat.setSizePolicy(sizePolicy)
        self.lblFilterAddressFlat.setObjectName(_fromUtf8("lblFilterAddressFlat"))
        self.horizontalLayout_2.addWidget(self.lblFilterAddressFlat)
        self.edtFilterAddressFlat = QtGui.QLineEdit(self.tabFilter)
        self.edtFilterAddressFlat.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterAddressFlat.sizePolicy().hasHeightForWidth())
        self.edtFilterAddressFlat.setSizePolicy(sizePolicy)
        self.edtFilterAddressFlat.setObjectName(_fromUtf8("edtFilterAddressFlat"))
        self.horizontalLayout_2.addWidget(self.edtFilterAddressFlat)
        self.gridLayout.addLayout(self.horizontalLayout_2, 23, 2, 1, 4)
        self.edtFilterEventEndDate = CDateEdit(self.tabFilter)
        self.edtFilterEventEndDate.setDisplayFormat(_fromUtf8("dd.MM.yyyy"))
        self.edtFilterEventEndDate.setCalendarPopup(True)
        self.edtFilterEventEndDate.setObjectName(_fromUtf8("edtFilterEventEndDate"))
        self.gridLayout.addWidget(self.edtFilterEventEndDate, 1, 2, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(49, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 2)
        self.btnFindClientInfo = QtGui.QToolButton(self.tabFilter)
        self.btnFindClientInfo.setObjectName(_fromUtf8("btnFindClientInfo"))
        self.gridLayout.addWidget(self.btnFindClientInfo, 10, 5, 1, 1)
        self.cmbFilterDeath = QtGui.QComboBox(self.tabFilter)
        self.cmbFilterDeath.setObjectName(_fromUtf8("cmbFilterDeath"))
        self.cmbFilterDeath.addItem(_fromUtf8(""))
        self.cmbFilterDeath.addItem(_fromUtf8(""))
        self.cmbFilterDeath.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbFilterDeath, 13, 2, 1, 4)
        self.cmbFilterAttachOrganisation = CPolyclinicComboBox(self.tabFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAttachOrganisation.sizePolicy().hasHeightForWidth())
        self.cmbFilterAttachOrganisation.setSizePolicy(sizePolicy)
        self.cmbFilterAttachOrganisation.setObjectName(_fromUtf8("cmbFilterAttachOrganisation"))
        self.gridLayout.addWidget(self.cmbFilterAttachOrganisation, 15, 2, 1, 4)
        self.cmbSex = QtGui.QComboBox(self.tabFilter)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSex, 11, 2, 1, 1)
        self.lblEndDate = QtGui.QLabel(self.tabFilter)
        self.lblEndDate.setObjectName(_fromUtf8("lblEndDate"))
        self.gridLayout.addWidget(self.lblEndDate, 1, 0, 1, 2)
        self.cmbFilterAddressCity = CKLADRComboBox(self.tabFilter)
        self.cmbFilterAddressCity.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressCity.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressCity.setSizePolicy(sizePolicy)
        self.cmbFilterAddressCity.setObjectName(_fromUtf8("cmbFilterAddressCity"))
        self.gridLayout.addWidget(self.cmbFilterAddressCity, 20, 2, 1, 4)
        self.cmbFilterAccountingSystem = CRBComboBox(self.tabFilter)
        self.cmbFilterAccountingSystem.setObjectName(_fromUtf8("cmbFilterAccountingSystem"))
        self.gridLayout.addWidget(self.cmbFilterAccountingSystem, 9, 2, 1, 4)
        self.lblFilterAttach = QtGui.QLabel(self.tabFilter)
        self.lblFilterAttach.setObjectName(_fromUtf8("lblFilterAttach"))
        self.gridLayout.addWidget(self.lblFilterAttach, 15, 0, 1, 2)
        self.cmbSocStatusesType = CRBComboBox(self.tabFilter)
        self.cmbSocStatusesType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSocStatusesType.sizePolicy().hasHeightForWidth())
        self.cmbSocStatusesType.setSizePolicy(sizePolicy)
        self.cmbSocStatusesType.setObjectName(_fromUtf8("cmbSocStatusesType"))
        self.gridLayout.addWidget(self.cmbSocStatusesType, 26, 2, 1, 4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.tabFilter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.edtFilterBegDate = CDateEdit(self.tabFilter)
        self.edtFilterBegDate.setEnabled(False)
        self.edtFilterBegDate.setCalendarPopup(True)
        self.edtFilterBegDate.setObjectName(_fromUtf8("edtFilterBegDate"))
        self.horizontalLayout_8.addWidget(self.edtFilterBegDate)
        self.label_6 = QtGui.QLabel(self.tabFilter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.edtFilterEndDate = CDateEdit(self.tabFilter)
        self.edtFilterEndDate.setEnabled(False)
        self.edtFilterEndDate.setCalendarPopup(True)
        self.edtFilterEndDate.setObjectName(_fromUtf8("edtFilterEndDate"))
        self.horizontalLayout_8.addWidget(self.edtFilterEndDate)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_8, 32, 2, 1, 4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.tabFilter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.edtFilterSocStatusesBegDate = CDateEdit(self.tabFilter)
        self.edtFilterSocStatusesBegDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterSocStatusesBegDate.sizePolicy().hasHeightForWidth())
        self.edtFilterSocStatusesBegDate.setSizePolicy(sizePolicy)
        self.edtFilterSocStatusesBegDate.setDisplayFormat(_fromUtf8("dd.MM.yyyy"))
        self.edtFilterSocStatusesBegDate.setCalendarPopup(True)
        self.edtFilterSocStatusesBegDate.setObjectName(_fromUtf8("edtFilterSocStatusesBegDate"))
        self.horizontalLayout_4.addWidget(self.edtFilterSocStatusesBegDate)
        self.lblFilterSocStatusesBegDate_ = QtGui.QLabel(self.tabFilter)
        self.lblFilterSocStatusesBegDate_.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFilterSocStatusesBegDate_.setObjectName(_fromUtf8("lblFilterSocStatusesBegDate_"))
        self.horizontalLayout_4.addWidget(self.lblFilterSocStatusesBegDate_)
        self.edtFilterSocStatusesEndDate = CDateEdit(self.tabFilter)
        self.edtFilterSocStatusesEndDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterSocStatusesEndDate.sizePolicy().hasHeightForWidth())
        self.edtFilterSocStatusesEndDate.setSizePolicy(sizePolicy)
        self.edtFilterSocStatusesEndDate.setDisplayFormat(_fromUtf8("dd.MM.yyyy"))
        self.edtFilterSocStatusesEndDate.setCalendarPopup(True)
        self.edtFilterSocStatusesEndDate.setObjectName(_fromUtf8("edtFilterSocStatusesEndDate"))
        self.horizontalLayout_4.addWidget(self.edtFilterSocStatusesEndDate)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 24, 2, 1, 4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.spbAgeFor = QtGui.QSpinBox(self.tabFilter)
        self.spbAgeFor.setMaximum(150)
        self.spbAgeFor.setObjectName(_fromUtf8("spbAgeFor"))
        self.horizontalLayout_5.addWidget(self.spbAgeFor)
        self.label_2 = QtGui.QLabel(self.tabFilter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.spbAgeTo = QtGui.QSpinBox(self.tabFilter)
        self.spbAgeTo.setMinimum(0)
        self.spbAgeTo.setMaximum(150)
        self.spbAgeTo.setObjectName(_fromUtf8("spbAgeTo"))
        self.horizontalLayout_5.addWidget(self.spbAgeTo)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 12, 2, 1, 4)
        self.lblFilterEventOrgStructure = QtGui.QLabel(self.tabFilter)
        self.lblFilterEventOrgStructure.setObjectName(_fromUtf8("lblFilterEventOrgStructure"))
        self.gridLayout.addWidget(self.lblFilterEventOrgStructure, 2, 0, 1, 2)
        self.cmbFilterAddressStreet = CStreetComboBox(self.tabFilter)
        self.cmbFilterAddressStreet.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressStreet.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressStreet.setSizePolicy(sizePolicy)
        self.cmbFilterAddressStreet.setObjectName(_fromUtf8("cmbFilterAddressStreet"))
        self.gridLayout.addWidget(self.cmbFilterAddressStreet, 22, 2, 1, 4)
        self.chkEventVisitDiagnosis = QtGui.QCheckBox(self.tabFilter)
        self.chkEventVisitDiagnosis.setEnabled(False)
        self.chkEventVisitDiagnosis.setObjectName(_fromUtf8("chkEventVisitDiagnosis"))
        self.gridLayout.addWidget(self.chkEventVisitDiagnosis, 28, 2, 1, 3)
        self.cmbFilterEventVisitType = QtGui.QComboBox(self.tabFilter)
        self.cmbFilterEventVisitType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterEventVisitType.sizePolicy().hasHeightForWidth())
        self.cmbFilterEventVisitType.setSizePolicy(sizePolicy)
        self.cmbFilterEventVisitType.setObjectName(_fromUtf8("cmbFilterEventVisitType"))
        self.cmbFilterEventVisitType.addItem(_fromUtf8(""))
        self.cmbFilterEventVisitType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbFilterEventVisitType, 29, 2, 1, 4)
        self.chkFilterEvent = QtGui.QCheckBox(self.tabFilter)
        self.chkFilterEvent.setObjectName(_fromUtf8("chkFilterEvent"))
        self.gridLayout.addWidget(self.chkFilterEvent, 28, 0, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(49, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 4, 1, 2)
        self.cmbFilterAddressOkato = CKladrOkatoComboBox(self.tabFilter)
        self.cmbFilterAddressOkato.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressOkato.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressOkato.setSizePolicy(sizePolicy)
        self.cmbFilterAddressOkato.setObjectName(_fromUtf8("cmbFilterAddressOkato"))
        self.gridLayout.addWidget(self.cmbFilterAddressOkato, 21, 2, 1, 4)
        self.cmbFilterEventSpecialityType = QtGui.QComboBox(self.tabFilter)
        self.cmbFilterEventSpecialityType.setObjectName(_fromUtf8("cmbFilterEventSpecialityType"))
        self.cmbFilterEventSpecialityType.addItem(_fromUtf8(""))
        self.cmbFilterEventSpecialityType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbFilterEventSpecialityType, 3, 2, 1, 4)
        self.cmbFilterPersonDN = CPersonComboBoxEx(self.tabFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterPersonDN.sizePolicy().hasHeightForWidth())
        self.cmbFilterPersonDN.setSizePolicy(sizePolicy)
        self.cmbFilterPersonDN.setObjectName(_fromUtf8("cmbFilterPersonDN"))
        self.gridLayout.addWidget(self.cmbFilterPersonDN, 5, 2, 1, 4)
        self.chkFilterNotAttachOrganisation = QtGui.QCheckBox(self.tabFilter)
        self.chkFilterNotAttachOrganisation.setEnabled(False)
        self.chkFilterNotAttachOrganisation.setObjectName(_fromUtf8("chkFilterNotAttachOrganisation"))
        self.gridLayout.addWidget(self.chkFilterNotAttachOrganisation, 16, 2, 1, 4)
        spacerItem6 = QtGui.QSpacerItem(239, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 11, 3, 1, 3)
        self.line_2 = QtGui.QFrame(self.tabFilter)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 27, 0, 1, 6)
        self.edtFilterClientId = QtGui.QLineEdit(self.tabFilter)
        self.edtFilterClientId.setObjectName(_fromUtf8("edtFilterClientId"))
        self.gridLayout.addWidget(self.edtFilterClientId, 10, 2, 1, 3)
        self.cmbFilterPlanningType = QtGui.QComboBox(self.tabFilter)
        self.cmbFilterPlanningType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterPlanningType.sizePolicy().hasHeightForWidth())
        self.cmbFilterPlanningType.setSizePolicy(sizePolicy)
        self.cmbFilterPlanningType.setObjectName(_fromUtf8("cmbFilterPlanningType"))
        self.cmbFilterPlanningType.addItem(_fromUtf8(""))
        self.cmbFilterPlanningType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbFilterPlanningType, 31, 2, 1, 4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cmbMKBFilter = QtGui.QComboBox(self.tabFilter)
        self.cmbMKBFilter.setObjectName(_fromUtf8("cmbMKBFilter"))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.cmbMKBFilter.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbMKBFilter)
        self.edtMKBFrom = CICDCodeEdit(self.tabFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBFrom.sizePolicy().hasHeightForWidth())
        self.edtMKBFrom.setSizePolicy(sizePolicy)
        self.edtMKBFrom.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edtMKBFrom.setMaxLength(6)
        self.edtMKBFrom.setObjectName(_fromUtf8("edtMKBFrom"))
        self.horizontalLayout.addWidget(self.edtMKBFrom)
        self.edtMKBTo = CICDCodeEdit(self.tabFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMKBTo.sizePolicy().hasHeightForWidth())
        self.edtMKBTo.setSizePolicy(sizePolicy)
        self.edtMKBTo.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edtMKBTo.setMaxLength(6)
        self.edtMKBTo.setObjectName(_fromUtf8("edtMKBTo"))
        self.horizontalLayout.addWidget(self.edtMKBTo)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 2, 1, 4)
        self.edtFilterEventBegDate = CDateEdit(self.tabFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtFilterEventBegDate.sizePolicy().hasHeightForWidth())
        self.edtFilterEventBegDate.setSizePolicy(sizePolicy)
        self.edtFilterEventBegDate.setDisplayFormat(_fromUtf8("dd.MM.yyyy"))
        self.edtFilterEventBegDate.setCalendarPopup(True)
        self.edtFilterEventBegDate.setObjectName(_fromUtf8("edtFilterEventBegDate"))
        self.gridLayout.addWidget(self.edtFilterEventBegDate, 0, 2, 1, 2)
        self.lblBegDate = QtGui.QLabel(self.tabFilter)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.gridLayout.addWidget(self.lblBegDate, 0, 0, 1, 2)
        self.line = QtGui.QFrame(self.tabFilter)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 8, 0, 1, 6)
        self.cmbFilterAddressOrgStructureType = QtGui.QComboBox(self.tabFilter)
        self.cmbFilterAddressOrgStructureType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressOrgStructureType.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressOrgStructureType.setSizePolicy(sizePolicy)
        self.cmbFilterAddressOrgStructureType.setObjectName(_fromUtf8("cmbFilterAddressOrgStructureType"))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.cmbFilterAddressOrgStructureType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbFilterAddressOrgStructureType, 17, 2, 1, 4)
        self.cmbFilterEventSpeciality = CRBMultivalueComboBox(self.tabFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterEventSpeciality.sizePolicy().hasHeightForWidth())
        self.cmbFilterEventSpeciality.setSizePolicy(sizePolicy)
        self.cmbFilterEventSpeciality.setObjectName(_fromUtf8("cmbFilterEventSpeciality"))
        self.gridLayout.addWidget(self.cmbFilterEventSpeciality, 4, 2, 1, 4)
        self.cmbFilterEventOrgStructure = COrgStructureComboBox(self.tabFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterEventOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbFilterEventOrgStructure.setSizePolicy(sizePolicy)
        self.cmbFilterEventOrgStructure.setObjectName(_fromUtf8("cmbFilterEventOrgStructure"))
        self.gridLayout.addWidget(self.cmbFilterEventOrgStructure, 2, 2, 1, 4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.tabFilter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.edtFilterEventVisitBegDate = CDateEdit(self.tabFilter)
        self.edtFilterEventVisitBegDate.setEnabled(False)
        self.edtFilterEventVisitBegDate.setCalendarPopup(True)
        self.edtFilterEventVisitBegDate.setObjectName(_fromUtf8("edtFilterEventVisitBegDate"))
        self.horizontalLayout_3.addWidget(self.edtFilterEventVisitBegDate)
        self.label_3 = QtGui.QLabel(self.tabFilter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.edtFilterEventVisitEndDate = CDateEdit(self.tabFilter)
        self.edtFilterEventVisitEndDate.setEnabled(False)
        self.edtFilterEventVisitEndDate.setCalendarPopup(True)
        self.edtFilterEventVisitEndDate.setObjectName(_fromUtf8("edtFilterEventVisitEndDate"))
        self.horizontalLayout_3.addWidget(self.edtFilterEventVisitEndDate)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_3, 30, 2, 1, 4)
        self.lblFilterEventSpeciality = QtGui.QLabel(self.tabFilter)
        self.lblFilterEventSpeciality.setObjectName(_fromUtf8("lblFilterEventSpeciality"))
        self.gridLayout.addWidget(self.lblFilterEventSpeciality, 3, 0, 1, 2)
        self.cmbDiseaseCharacter = CRBComboBox(self.tabFilter)
        self.cmbDiseaseCharacter.setObjectName(_fromUtf8("cmbDiseaseCharacter"))
        self.gridLayout.addWidget(self.cmbDiseaseCharacter, 7, 2, 1, 4)
        self.cmbFilterAddressOrgStructure = COrgStructureComboBox(self.tabFilter)
        self.cmbFilterAddressOrgStructure.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressOrgStructure.setSizePolicy(sizePolicy)
        self.cmbFilterAddressOrgStructure.setObjectName(_fromUtf8("cmbFilterAddressOrgStructure"))
        self.gridLayout.addWidget(self.cmbFilterAddressOrgStructure, 18, 2, 1, 4)
        self.cmbFilterAddressType = QtGui.QComboBox(self.tabFilter)
        self.cmbFilterAddressType.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFilterAddressType.sizePolicy().hasHeightForWidth())
        self.cmbFilterAddressType.setSizePolicy(sizePolicy)
        self.cmbFilterAddressType.setObjectName(_fromUtf8("cmbFilterAddressType"))
        self.cmbFilterAddressType.addItem(_fromUtf8(""))
        self.cmbFilterAddressType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbFilterAddressType, 19, 2, 1, 4)
        self.lblMKB = QtGui.QLabel(self.tabFilter)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.gridLayout.addWidget(self.lblMKB, 6, 0, 1, 2)
        self.buttonBoxFilter = CApplyResetDialogButtonBox(self.tabFilter)
        self.buttonBoxFilter.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBoxFilter.setObjectName(_fromUtf8("buttonBoxFilter"))
        self.gridLayout.addWidget(self.buttonBoxFilter, 34, 0, 1, 6)
        self.chkSocStatuses = QtGui.QCheckBox(self.tabFilter)
        self.chkSocStatuses.setObjectName(_fromUtf8("chkSocStatuses"))
        self.gridLayout.addWidget(self.chkSocStatuses, 24, 0, 1, 2)
        self.chkFilterAddress = QtGui.QCheckBox(self.tabFilter)
        self.chkFilterAddress.setObjectName(_fromUtf8("chkFilterAddress"))
        self.gridLayout.addWidget(self.chkFilterAddress, 19, 0, 1, 2)
        self.chkFilterDateRange = QtGui.QCheckBox(self.tabFilter)
        self.chkFilterDateRange.setObjectName(_fromUtf8("chkFilterDateRange"))
        self.gridLayout.addWidget(self.chkFilterDateRange, 31, 0, 1, 2)
        spacerItem9 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 33, 0, 1, 2)
        self.lblFilterDeath = QtGui.QLabel(self.tabFilter)
        self.lblFilterDeath.setObjectName(_fromUtf8("lblFilterDeath"))
        self.gridLayout.addWidget(self.lblFilterDeath, 13, 0, 1, 2)
        self.chkFilterAddressOrgStructure = QtGui.QCheckBox(self.tabFilter)
        self.chkFilterAddressOrgStructure.setObjectName(_fromUtf8("chkFilterAddressOrgStructure"))
        self.gridLayout.addWidget(self.chkFilterAddressOrgStructure, 17, 0, 1, 2)
        self.lblDiseaseCharacter = QtGui.QLabel(self.tabFilter)
        self.lblDiseaseCharacter.setObjectName(_fromUtf8("lblDiseaseCharacter"))
        self.gridLayout.addWidget(self.lblDiseaseCharacter, 7, 0, 1, 2)
        self.lblClient = QtGui.QLabel(self.tabFilter)
        self.lblClient.setObjectName(_fromUtf8("lblClient"))
        self.gridLayout.addWidget(self.lblClient, 9, 0, 1, 2)
        self.lblSexPresence = QtGui.QLabel(self.tabFilter)
        self.lblSexPresence.setObjectName(_fromUtf8("lblSexPresence"))
        self.gridLayout.addWidget(self.lblSexPresence, 11, 0, 1, 2)
        self.lblFilterPersonDN = QtGui.QLabel(self.tabFilter)
        self.lblFilterPersonDN.setObjectName(_fromUtf8("lblFilterPersonDN"))
        self.gridLayout.addWidget(self.lblFilterPersonDN, 5, 0, 1, 2)
        self.lblAgePresence = QtGui.QLabel(self.tabFilter)
        self.lblAgePresence.setObjectName(_fromUtf8("lblAgePresence"))
        self.gridLayout.addWidget(self.lblAgePresence, 12, 0, 1, 2)
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabDispensaireClients = QtGui.QTabWidget(self.layoutWidget)
        self.tabDispensaireClients.setObjectName(_fromUtf8("tabDispensaireClients"))
        self.tabConsistsDispensaire = QtGui.QWidget()
        self.tabConsistsDispensaire.setObjectName(_fromUtf8("tabConsistsDispensaire"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabConsistsDispensaire)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitterConsist = QtGui.QSplitter(self.tabConsistsDispensaire)
        self.splitterConsist.setOrientation(QtCore.Qt.Vertical)
        self.splitterConsist.setOpaqueResize(True)
        self.splitterConsist.setHandleWidth(5)
        self.splitterConsist.setObjectName(_fromUtf8("splitterConsist"))
        self.txtConsistsClientInfoBrowser = CTextBrowser(self.splitterConsist)
        self.txtConsistsClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.txtConsistsClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtConsistsClientInfoBrowser.setReadOnly(True)
        self.txtConsistsClientInfoBrowser.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.txtConsistsClientInfoBrowser.setObjectName(_fromUtf8("txtConsistsClientInfoBrowser"))
        self.tblConsistsClients = CSurveillanceClientsTableView(self.splitterConsist)
        self.tblConsistsClients.setObjectName(_fromUtf8("tblConsistsClients"))
        self.tblConsistsDiagnosis = CSurveillanceClientDiagnosisTableView(self.splitterConsist)
        self.tblConsistsDiagnosis.setObjectName(_fromUtf8("tblConsistsDiagnosis"))
        self.tabWidgetConsist = QtGui.QTabWidget(self.splitterConsist)
        self.tabWidgetConsist.setObjectName(_fromUtf8("tabWidgetConsist"))
        self.tabConsistMonitoring = QtGui.QWidget()
        self.tabConsistMonitoring.setObjectName(_fromUtf8("tabConsistMonitoring"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabConsistMonitoring)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tblConsistsMonitoring = CSurveillanceMonitoringTableView(self.tabConsistMonitoring)
        self.tblConsistsMonitoring.setObjectName(_fromUtf8("tblConsistsMonitoring"))
        self.gridLayout_7.addWidget(self.tblConsistsMonitoring, 0, 0, 1, 1)
        self.tabWidgetConsist.addTab(self.tabConsistMonitoring, _fromUtf8(""))
        self.tabConsistPlanning = QtGui.QWidget()
        self.tabConsistPlanning.setObjectName(_fromUtf8("tabConsistPlanning"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabConsistPlanning)
        self.gridLayout_8.setMargin(4)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tblConsistsPlanning = CSurveillancePlanningTableView(self.tabConsistPlanning)
        self.tblConsistsPlanning.setObjectName(_fromUtf8("tblConsistsPlanning"))
        self.gridLayout_8.addWidget(self.tblConsistsPlanning, 0, 0, 1, 1)
        self.tabWidgetConsist.addTab(self.tabConsistPlanning, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.splitterConsist, 0, 0, 1, 1)
        self.tabDispensaireClients.addTab(self.tabConsistsDispensaire, _fromUtf8(""))
        self.tabTakenDispensaire = QtGui.QWidget()
        self.tabTakenDispensaire.setObjectName(_fromUtf8("tabTakenDispensaire"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabTakenDispensaire)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitterTaken = QtGui.QSplitter(self.tabTakenDispensaire)
        self.splitterTaken.setOrientation(QtCore.Qt.Vertical)
        self.splitterTaken.setObjectName(_fromUtf8("splitterTaken"))
        self.txtTakenClientInfoBrowser = CTextBrowser(self.splitterTaken)
        self.txtTakenClientInfoBrowser.setObjectName(_fromUtf8("txtTakenClientInfoBrowser"))
        self.tblTakenClients = CSurveillanceClientsTableView(self.splitterTaken)
        self.tblTakenClients.setObjectName(_fromUtf8("tblTakenClients"))
        self.tblTakenDiagnosis = CSurveillanceClientDiagnosisTableView(self.splitterTaken)
        self.tblTakenDiagnosis.setObjectName(_fromUtf8("tblTakenDiagnosis"))
        self.tabWidgetTaken = QtGui.QTabWidget(self.splitterTaken)
        self.tabWidgetTaken.setObjectName(_fromUtf8("tabWidgetTaken"))
        self.tabTakenMonitoring = QtGui.QWidget()
        self.tabTakenMonitoring.setObjectName(_fromUtf8("tabTakenMonitoring"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabTakenMonitoring)
        self.gridLayout_9.setMargin(4)
        self.gridLayout_9.setSpacing(4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tblTakenMonitoring = CSurveillanceMonitoringTableView(self.tabTakenMonitoring)
        self.tblTakenMonitoring.setObjectName(_fromUtf8("tblTakenMonitoring"))
        self.gridLayout_9.addWidget(self.tblTakenMonitoring, 0, 0, 1, 1)
        self.tabWidgetTaken.addTab(self.tabTakenMonitoring, _fromUtf8(""))
        self.TakenPlanning = QtGui.QWidget()
        self.TakenPlanning.setObjectName(_fromUtf8("TakenPlanning"))
        self.gridLayout_10 = QtGui.QGridLayout(self.TakenPlanning)
        self.gridLayout_10.setMargin(4)
        self.gridLayout_10.setSpacing(4)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tblTakenPlanning = CSurveillancePlanningTableView(self.TakenPlanning)
        self.tblTakenPlanning.setObjectName(_fromUtf8("tblTakenPlanning"))
        self.gridLayout_10.addWidget(self.tblTakenPlanning, 0, 0, 1, 1)
        self.tabWidgetTaken.addTab(self.TakenPlanning, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.splitterTaken, 0, 0, 1, 1)
        self.tabDispensaireClients.addTab(self.tabTakenDispensaire, _fromUtf8(""))
        self.tabRemoveDispensaire = QtGui.QWidget()
        self.tabRemoveDispensaire.setObjectName(_fromUtf8("tabRemoveDispensaire"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabRemoveDispensaire)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.splitterRemove = QtGui.QSplitter(self.tabRemoveDispensaire)
        self.splitterRemove.setOrientation(QtCore.Qt.Vertical)
        self.splitterRemove.setObjectName(_fromUtf8("splitterRemove"))
        self.txtRemoveClientInfoBrowser = CTextBrowser(self.splitterRemove)
        self.txtRemoveClientInfoBrowser.setObjectName(_fromUtf8("txtRemoveClientInfoBrowser"))
        self.tblRemoveClients = CSurveillanceClientsTableView(self.splitterRemove)
        self.tblRemoveClients.setObjectName(_fromUtf8("tblRemoveClients"))
        self.tblRemoveDiagnosis = CSurveillanceClientDiagnosisTableView(self.splitterRemove)
        self.tblRemoveDiagnosis.setObjectName(_fromUtf8("tblRemoveDiagnosis"))
        self.tabWidgetRemove = QtGui.QTabWidget(self.splitterRemove)
        self.tabWidgetRemove.setObjectName(_fromUtf8("tabWidgetRemove"))
        self.tabRemoveMonitoring = QtGui.QWidget()
        self.tabRemoveMonitoring.setObjectName(_fromUtf8("tabRemoveMonitoring"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tabRemoveMonitoring)
        self.gridLayout_11.setMargin(4)
        self.gridLayout_11.setSpacing(4)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.tblRemoveMonitoring = CSurveillanceMonitoringTableView(self.tabRemoveMonitoring)
        self.tblRemoveMonitoring.setObjectName(_fromUtf8("tblRemoveMonitoring"))
        self.gridLayout_11.addWidget(self.tblRemoveMonitoring, 0, 0, 1, 1)
        self.tabWidgetRemove.addTab(self.tabRemoveMonitoring, _fromUtf8(""))
        self.tabRemovePlanning = QtGui.QWidget()
        self.tabRemovePlanning.setObjectName(_fromUtf8("tabRemovePlanning"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tabRemovePlanning)
        self.gridLayout_12.setMargin(4)
        self.gridLayout_12.setSpacing(4)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.tblRemovePlanning = CSurveillancePlanningTableView(self.tabRemovePlanning)
        self.tblRemovePlanning.setObjectName(_fromUtf8("tblRemovePlanning"))
        self.gridLayout_12.addWidget(self.tblRemovePlanning, 0, 0, 1, 1)
        self.tabWidgetRemove.addTab(self.tabRemovePlanning, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.splitterRemove, 0, 0, 1, 1)
        self.tabDispensaireClients.addTab(self.tabRemoveDispensaire, _fromUtf8(""))
        self.tabSubjectToSurveillance = QtGui.QWidget()
        self.tabSubjectToSurveillance.setObjectName(_fromUtf8("tabSubjectToSurveillance"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tabSubjectToSurveillance)
        self.horizontalLayout_7.setMargin(4)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.splitterSubjectToSurveillance = QtGui.QSplitter(self.tabSubjectToSurveillance)
        self.splitterSubjectToSurveillance.setOrientation(QtCore.Qt.Vertical)
        self.splitterSubjectToSurveillance.setObjectName(_fromUtf8("splitterSubjectToSurveillance"))
        self.txtSubjectToSurveillanceClientInfoBrowser = CTextBrowser(self.splitterSubjectToSurveillance)
        self.txtSubjectToSurveillanceClientInfoBrowser.setObjectName(_fromUtf8("txtSubjectToSurveillanceClientInfoBrowser"))
        self.tblSubjectToSurveillanceClients = CSurveillanceClientsTableView(self.splitterSubjectToSurveillance)
        self.tblSubjectToSurveillanceClients.setObjectName(_fromUtf8("tblSubjectToSurveillanceClients"))
        self.tblSubjectToSurveillanceDiagnosis = CSurveillanceClientDiagnosisTableView(self.splitterSubjectToSurveillance)
        self.tblSubjectToSurveillanceDiagnosis.setObjectName(_fromUtf8("tblSubjectToSurveillanceDiagnosis"))
        self.tabWidgetSubjectToSurveillance = QtGui.QTabWidget(self.splitterSubjectToSurveillance)
        self.tabWidgetSubjectToSurveillance.setObjectName(_fromUtf8("tabWidgetSubjectToSurveillance"))
        self.tabSubjectToSurveillanceMonitoring = QtGui.QWidget()
        self.tabSubjectToSurveillanceMonitoring.setObjectName(_fromUtf8("tabSubjectToSurveillanceMonitoring"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tabSubjectToSurveillanceMonitoring)
        self.gridLayout_13.setMargin(4)
        self.gridLayout_13.setSpacing(4)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.tblSubjectToSurveillanceMonitoring = CSurveillanceMonitoringTableView(self.tabSubjectToSurveillanceMonitoring)
        self.tblSubjectToSurveillanceMonitoring.setObjectName(_fromUtf8("tblSubjectToSurveillanceMonitoring"))
        self.gridLayout_13.addWidget(self.tblSubjectToSurveillanceMonitoring, 0, 0, 1, 1)
        self.tabWidgetSubjectToSurveillance.addTab(self.tabSubjectToSurveillanceMonitoring, _fromUtf8(""))
        self.tabSubjectToSurveillancePlanning = QtGui.QWidget()
        self.tabSubjectToSurveillancePlanning.setObjectName(_fromUtf8("tabSubjectToSurveillancePlanning"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tabSubjectToSurveillancePlanning)
        self.gridLayout_14.setMargin(4)
        self.gridLayout_14.setSpacing(4)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.tblSubjectToSurveillancePlanning = CSurveillancePlanningTableView(self.tabSubjectToSurveillancePlanning)
        self.tblSubjectToSurveillancePlanning.setObjectName(_fromUtf8("tblSubjectToSurveillancePlanning"))
        self.gridLayout_14.addWidget(self.tblSubjectToSurveillancePlanning, 0, 0, 1, 1)
        self.tabWidgetSubjectToSurveillance.addTab(self.tabSubjectToSurveillancePlanning, _fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.splitterSubjectToSurveillance)
        self.tabDispensaireClients.addTab(self.tabSubjectToSurveillance, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabDispensaireClients)
        self.lblCountRecordList = QtGui.QLabel(self.layoutWidget)
        self.lblCountRecordList.setObjectName(_fromUtf8("lblCountRecordList"))
        self.verticalLayout.addWidget(self.lblCountRecordList)
        self.gridLayout_6.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.lblFilterAddressHouse.setBuddy(self.edtFilterAddressHouse)
        self.lblMKB.setBuddy(self.cmbMKBFilter)

        self.retranslateUi(SurveillanceDialog)
        self.tabDispensaireClients.setCurrentIndex(0)
        self.tabWidgetConsist.setCurrentIndex(0)
        self.tabWidgetTaken.setCurrentIndex(0)
        self.tabWidgetRemove.setCurrentIndex(0)
        self.tabWidgetSubjectToSurveillance.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SurveillanceDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SurveillanceDialog.reject)
        QtCore.QObject.connect(self.chkFilterAddressOrgStructure, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterAddressOrgStructureType.setEnabled)
        QtCore.QObject.connect(self.chkFilterAddressOrgStructure, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterAddressOrgStructure.setEnabled)
        QtCore.QObject.connect(self.chkFilterAddress, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterAddressCity.setEnabled)
        QtCore.QObject.connect(self.chkFilterAddress, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterAddressType.setEnabled)
        QtCore.QObject.connect(self.chkFilterAddress, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterAddressStreet.setEnabled)
        QtCore.QObject.connect(self.chkFilterAddress, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterAddressOkato.setEnabled)
        QtCore.QObject.connect(self.chkFilterAddress, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterAddressCorpus.setEnabled)
        QtCore.QObject.connect(self.chkFilterAddress, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterAddressFlat.setEnabled)
        QtCore.QObject.connect(self.chkFilterAddress, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterAddressHouse.setEnabled)
        QtCore.QObject.connect(self.chkSocStatuses, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSocStatusesClass.setEnabled)
        QtCore.QObject.connect(self.chkSocStatuses, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbSocStatusesType.setEnabled)
        QtCore.QObject.connect(self.chkSocStatuses, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterSocStatusesBegDate.setEnabled)
        QtCore.QObject.connect(self.chkSocStatuses, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterSocStatusesEndDate.setEnabled)
        QtCore.QObject.connect(self.chkFilterEvent, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkEventVisitDiagnosis.setEnabled)
        QtCore.QObject.connect(self.chkFilterEvent, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterEventVisitType.setEnabled)
        QtCore.QObject.connect(self.chkFilterEvent, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterEventVisitBegDate.setEnabled)
        QtCore.QObject.connect(self.chkFilterEvent, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterEventVisitEndDate.setEnabled)
        QtCore.QObject.connect(self.chkFilterDateRange, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterBegDate.setEnabled)
        QtCore.QObject.connect(self.chkFilterDateRange, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtFilterEndDate.setEnabled)
        QtCore.QObject.connect(self.chkFilterDateRange, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cmbFilterPlanningType.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SurveillanceDialog)

    def retranslateUi(self, SurveillanceDialog):
        SurveillanceDialog.setWindowTitle(_translate("SurveillanceDialog", "Диспансерное наблюдение", None))
        self.edtFilterDeathBegDate.setDisplayFormat(_translate("SurveillanceDialog", "dd.MM.yyyy", None))
        self.lblFilterDeathPeriod.setText(_translate("SurveillanceDialog", "по", None))
        self.edtFilterDeathEndDate.setDisplayFormat(_translate("SurveillanceDialog", "dd.MM.yyyy", None))
        self.lblFilterAddressHouse.setText(_translate("SurveillanceDialog", "Дом", None))
        self.lblFilterAddressCorpus.setText(_translate("SurveillanceDialog", "Корп", None))
        self.lblFilterAddressFlat.setText(_translate("SurveillanceDialog", "Кв", None))
        self.btnFindClientInfo.setText(_translate("SurveillanceDialog", "...", None))
        self.cmbFilterDeath.setItemText(0, _translate("SurveillanceDialog", "не учитывать", None))
        self.cmbFilterDeath.setItemText(1, _translate("SurveillanceDialog", "только живые", None))
        self.cmbFilterDeath.setItemText(2, _translate("SurveillanceDialog", "только умершие", None))
        self.cmbSex.setItemText(0, _translate("SurveillanceDialog", "нет", None))
        self.cmbSex.setItemText(1, _translate("SurveillanceDialog", "М", None))
        self.cmbSex.setItemText(2, _translate("SurveillanceDialog", "Ж", None))
        self.lblEndDate.setText(_translate("SurveillanceDialog", "Окончание периода", None))
        self.lblFilterAttach.setText(_translate("SurveillanceDialog", "Прикрепление к ЛПУ", None))
        self.label_5.setText(_translate("SurveillanceDialog", "С", None))
        self.edtFilterBegDate.setDisplayFormat(_translate("SurveillanceDialog", "dd.MM.yyyy", None))
        self.label_6.setText(_translate("SurveillanceDialog", "по", None))
        self.edtFilterEndDate.setDisplayFormat(_translate("SurveillanceDialog", "dd.MM.yyyy", None))
        self.label_4.setText(_translate("SurveillanceDialog", "С", None))
        self.lblFilterSocStatusesBegDate_.setText(_translate("SurveillanceDialog", "по", None))
        self.label_2.setText(_translate("SurveillanceDialog", "по", None))
        self.lblFilterEventOrgStructure.setText(_translate("SurveillanceDialog", "Подразделение врача", None))
        self.chkEventVisitDiagnosis.setText(_translate("SurveillanceDialog", "по Диспансерному наблюдению", None))
        self.cmbFilterEventVisitType.setItemText(0, _translate("SurveillanceDialog", "обращались", None))
        self.cmbFilterEventVisitType.setItemText(1, _translate("SurveillanceDialog", "не обращались", None))
        self.chkFilterEvent.setText(_translate("SurveillanceDialog", "Обращения", None))
        self.cmbFilterEventSpecialityType.setItemText(0, _translate("SurveillanceDialog", "Отбор по \"ИЛИ\"", None))
        self.cmbFilterEventSpecialityType.setItemText(1, _translate("SurveillanceDialog", "Отбор по \"И\"", None))
        self.chkFilterNotAttachOrganisation.setText(_translate("SurveillanceDialog", "Не имеет прикрепления к выбранному ЛПУ", None))
        self.cmbFilterPlanningType.setItemText(0, _translate("SurveillanceDialog", "запланированы", None))
        self.cmbFilterPlanningType.setItemText(1, _translate("SurveillanceDialog", "не запланированы", None))
        self.cmbMKBFilter.setItemText(0, _translate("SurveillanceDialog", "Игнор.", None))
        self.cmbMKBFilter.setItemText(1, _translate("SurveillanceDialog", "Интервал", None))
        self.edtMKBFrom.setInputMask(_translate("SurveillanceDialog", "a00.00", None))
        self.edtMKBFrom.setText(_translate("SurveillanceDialog", "A.", None))
        self.edtMKBTo.setInputMask(_translate("SurveillanceDialog", "a00.00", None))
        self.edtMKBTo.setText(_translate("SurveillanceDialog", "Z99.9", None))
        self.lblBegDate.setText(_translate("SurveillanceDialog", "Начало периода", None))
        self.cmbFilterAddressOrgStructureType.setItemText(0, _translate("SurveillanceDialog", "Регистрация", None))
        self.cmbFilterAddressOrgStructureType.setItemText(1, _translate("SurveillanceDialog", "Проживание", None))
        self.cmbFilterAddressOrgStructureType.setItemText(2, _translate("SurveillanceDialog", "Регистрация или проживание", None))
        self.cmbFilterAddressOrgStructureType.setItemText(3, _translate("SurveillanceDialog", "Прикрепление", None))
        self.cmbFilterAddressOrgStructureType.setItemText(4, _translate("SurveillanceDialog", "Регистрация или прикрепление", None))
        self.cmbFilterAddressOrgStructureType.setItemText(5, _translate("SurveillanceDialog", "Проживание или прикрепление", None))
        self.cmbFilterAddressOrgStructureType.setItemText(6, _translate("SurveillanceDialog", "Регистрация, проживание или прикрепление", None))
        self.label.setText(_translate("SurveillanceDialog", "С", None))
        self.edtFilterEventVisitBegDate.setDisplayFormat(_translate("SurveillanceDialog", "dd.MM.yyyy", None))
        self.label_3.setText(_translate("SurveillanceDialog", "по", None))
        self.edtFilterEventVisitEndDate.setDisplayFormat(_translate("SurveillanceDialog", "dd.MM.yyyy", None))
        self.lblFilterEventSpeciality.setText(_translate("SurveillanceDialog", "Специальность", None))
        self.cmbFilterAddressType.setItemText(0, _translate("SurveillanceDialog", "Регистрации", None))
        self.cmbFilterAddressType.setItemText(1, _translate("SurveillanceDialog", "Проживания", None))
        self.lblMKB.setText(_translate("SurveillanceDialog", "Коды диагнозов по &МКБ", None))
        self.chkSocStatuses.setText(_translate("SurveillanceDialog", "Соц.статус", None))
        self.chkFilterAddress.setText(_translate("SurveillanceDialog", "Адрес", None))
        self.chkFilterDateRange.setText(_translate("SurveillanceDialog", "Планирование ДН", None))
        self.lblFilterDeath.setText(_translate("SurveillanceDialog", "Летальность", None))
        self.chkFilterAddressOrgStructure.setText(_translate("SurveillanceDialog", "По участку", None))
        self.lblDiseaseCharacter.setText(_translate("SurveillanceDialog", "Характер заболевания", None))
        self.lblClient.setText(_translate("SurveillanceDialog", "Пациент", None))
        self.lblSexPresence.setText(_translate("SurveillanceDialog", "Пол", None))
        self.lblFilterPersonDN.setText(_translate("SurveillanceDialog", "Врач по ДН", None))
        self.lblAgePresence.setText(_translate("SurveillanceDialog", "Возраст с", None))
        self.txtConsistsClientInfoBrowser.setHtml(_translate("SurveillanceDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"><br /></span></p></body></html>", None))
        self.tabWidgetConsist.setTabText(self.tabWidgetConsist.indexOf(self.tabConsistMonitoring), _translate("SurveillanceDialog", "Явки по диагнозу", None))
        self.tabWidgetConsist.setTabText(self.tabWidgetConsist.indexOf(self.tabConsistPlanning), _translate("SurveillanceDialog", "Планирование для сервиса профмероприятий", None))
        self.tabDispensaireClients.setTabText(self.tabDispensaireClients.indexOf(self.tabConsistsDispensaire), _translate("SurveillanceDialog", "Состоят", None))
        self.tabWidgetTaken.setTabText(self.tabWidgetTaken.indexOf(self.tabTakenMonitoring), _translate("SurveillanceDialog", "Явки по диагнозу", None))
        self.tabWidgetTaken.setTabText(self.tabWidgetTaken.indexOf(self.TakenPlanning), _translate("SurveillanceDialog", "Планирование для сервиса профмероприятий", None))
        self.tabDispensaireClients.setTabText(self.tabDispensaireClients.indexOf(self.tabTakenDispensaire), _translate("SurveillanceDialog", "Взяты", None))
        self.tabWidgetRemove.setTabText(self.tabWidgetRemove.indexOf(self.tabRemoveMonitoring), _translate("SurveillanceDialog", "Явки по диагнозу", None))
        self.tabWidgetRemove.setTabText(self.tabWidgetRemove.indexOf(self.tabRemovePlanning), _translate("SurveillanceDialog", "Планирование для сервиса профмероприятий", None))
        self.tabDispensaireClients.setTabText(self.tabDispensaireClients.indexOf(self.tabRemoveDispensaire), _translate("SurveillanceDialog", "Сняты", None))
        self.tabWidgetSubjectToSurveillance.setTabText(self.tabWidgetSubjectToSurveillance.indexOf(self.tabSubjectToSurveillanceMonitoring), _translate("SurveillanceDialog", "Явки по диагнозу", None))
        self.tabWidgetSubjectToSurveillance.setTabText(self.tabWidgetSubjectToSurveillance.indexOf(self.tabSubjectToSurveillancePlanning), _translate("SurveillanceDialog", "Планирование для сервиса профмероприятий", None))
        self.tabDispensaireClients.setTabText(self.tabDispensaireClients.indexOf(self.tabSubjectToSurveillance), _translate("SurveillanceDialog", "Подлежат", None))
        self.lblCountRecordList.setText(_translate("SurveillanceDialog", "Количество записей        0", None))

from KLADR.kladrComboxes import CKLADRComboBox, CKladrOkatoComboBox, CStreetComboBox
from Orgs.OrgComboBox import CPolyclinicComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Registry.SocStatusComboBox import CSocStatusComboBox
from Surveillance.SurveillanceClientsTableView import CSurveillanceClientDiagnosisTableView, CSurveillanceClientsTableView, CSurveillanceMonitoringTableView, CSurveillancePlanningTableView
from library.DateEdit import CDateEdit
from library.DialogButtonBox import CApplyResetDialogButtonBox
from library.ICDCodeEdit import CICDCodeEdit
from library.MultivalueComboBox import CRBMultivalueComboBox
from library.TextBrowser import CTextBrowser
from library.crbcombobox import CRBComboBox
