# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client_test\RefBooks\Nomenclature\RBNomenclatureEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemEditorDialog(object):
    def setupUi(self, ItemEditorDialog):
        ItemEditorDialog.setObjectName(_fromUtf8("ItemEditorDialog"))
        ItemEditorDialog.resize(754, 775)
        ItemEditorDialog.setSizeGripEnabled(True)
        self.gridLayout_3 = QtGui.QGridLayout(ItemEditorDialog)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.formSplitter = QtGui.QSplitter(ItemEditorDialog)
        self.formSplitter.setOrientation(QtCore.Qt.Vertical)
        self.formSplitter.setObjectName(_fromUtf8("formSplitter"))
        self.tabWidget = QtGui.QTabWidget(self.formSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMain = QtGui.QWidget()
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabMain)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cmbESLKPName = CESKLPComboBox(self.tabMain)
        self.cmbESLKPName.setObjectName(_fromUtf8("cmbESLKPName"))
        self.gridLayout_2.addWidget(self.cmbESLKPName, 0, 1, 1, 2)
        self.lblCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout_2.addWidget(self.lblCode, 5, 0, 1, 1)
        self.btnESLKPFill = QtGui.QPushButton(self.tabMain)
        self.btnESLKPFill.setEnabled(False)
        self.btnESLKPFill.setObjectName(_fromUtf8("btnESLKPFill"))
        self.gridLayout_2.addWidget(self.btnESLKPFill, 0, 3, 1, 1)
        self.line = QtGui.QFrame(self.tabMain)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 4)
        self.edtName = QtGui.QLineEdit(self.tabMain)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout_2.addWidget(self.edtName, 6, 1, 1, 3)
        self.edtCode = QtGui.QLineEdit(self.tabMain)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout_2.addWidget(self.edtCode, 5, 1, 1, 3)
        self.edtOriginName = QtGui.QLineEdit(self.tabMain)
        self.edtOriginName.setObjectName(_fromUtf8("edtOriginName"))
        self.gridLayout_2.addWidget(self.edtOriginName, 7, 1, 1, 3)
        self.lblMnnLatin = QtGui.QLabel(self.tabMain)
        self.lblMnnLatin.setObjectName(_fromUtf8("lblMnnLatin"))
        self.gridLayout_2.addWidget(self.lblMnnLatin, 9, 0, 1, 1)
        self.cmbType = CRBComboBox(self.tabMain)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.gridLayout_2.addWidget(self.cmbType, 4, 1, 1, 3)
        self.lblType = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblType.sizePolicy().hasHeightForWidth())
        self.lblType.setSizePolicy(sizePolicy)
        self.lblType.setObjectName(_fromUtf8("lblType"))
        self.gridLayout_2.addWidget(self.lblType, 4, 0, 1, 1)
        self.lblName = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout_2.addWidget(self.lblName, 6, 0, 1, 1)
        self.edtMnnLatin = QtGui.QLineEdit(self.tabMain)
        self.edtMnnLatin.setObjectName(_fromUtf8("edtMnnLatin"))
        self.gridLayout_2.addWidget(self.edtMnnLatin, 9, 1, 1, 3)
        self.lblESLKPName = QtGui.QLabel(self.tabMain)
        self.lblESLKPName.setObjectName(_fromUtf8("lblESLKPName"))
        self.gridLayout_2.addWidget(self.lblESLKPName, 0, 0, 1, 1)
        self.lblKind = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblKind.sizePolicy().hasHeightForWidth())
        self.lblKind.setSizePolicy(sizePolicy)
        self.lblKind.setObjectName(_fromUtf8("lblKind"))
        self.gridLayout_2.addWidget(self.lblKind, 3, 0, 1, 1)
        self.lblInternationalNonproprietaryName = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInternationalNonproprietaryName.sizePolicy().hasHeightForWidth())
        self.lblInternationalNonproprietaryName.setSizePolicy(sizePolicy)
        self.lblInternationalNonproprietaryName.setObjectName(_fromUtf8("lblInternationalNonproprietaryName"))
        self.gridLayout_2.addWidget(self.lblInternationalNonproprietaryName, 8, 0, 1, 1)
        self.lblRegionalCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRegionalCode.sizePolicy().hasHeightForWidth())
        self.lblRegionalCode.setSizePolicy(sizePolicy)
        self.lblRegionalCode.setObjectName(_fromUtf8("lblRegionalCode"))
        self.gridLayout_2.addWidget(self.lblRegionalCode, 10, 0, 1, 1)
        self.cmbKind = CRBComboBox(self.tabMain)
        self.cmbKind.setObjectName(_fromUtf8("cmbKind"))
        self.gridLayout_2.addWidget(self.cmbKind, 3, 1, 1, 3)
        self.lblClass = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClass.sizePolicy().hasHeightForWidth())
        self.lblClass.setSizePolicy(sizePolicy)
        self.lblClass.setObjectName(_fromUtf8("lblClass"))
        self.gridLayout_2.addWidget(self.lblClass, 2, 0, 1, 1)
        self.lblOriginName = QtGui.QLabel(self.tabMain)
        self.lblOriginName.setObjectName(_fromUtf8("lblOriginName"))
        self.gridLayout_2.addWidget(self.lblOriginName, 7, 0, 1, 1)
        self.edtInternationalNonproprietaryName = QtGui.QLineEdit(self.tabMain)
        self.edtInternationalNonproprietaryName.setObjectName(_fromUtf8("edtInternationalNonproprietaryName"))
        self.gridLayout_2.addWidget(self.edtInternationalNonproprietaryName, 8, 1, 1, 3)
        self.cmbClass = CRBComboBox(self.tabMain)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.gridLayout_2.addWidget(self.cmbClass, 2, 1, 1, 3)
        self.cmbLfForm = CReleaseFormComboBox(self.tabMain)
        self.cmbLfForm.setObjectName(_fromUtf8("cmbLfForm"))
        self.gridLayout_2.addWidget(self.cmbLfForm, 26, 1, 1, 3)
        self.lblExDate = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExDate.sizePolicy().hasHeightForWidth())
        self.lblExDate.setSizePolicy(sizePolicy)
        self.lblExDate.setObjectName(_fromUtf8("lblExDate"))
        self.gridLayout_2.addWidget(self.lblExDate, 32, 0, 1, 1)
        self.lblDefaultClientUnit = QtGui.QLabel(self.tabMain)
        self.lblDefaultClientUnit.setObjectName(_fromUtf8("lblDefaultClientUnit"))
        self.gridLayout_2.addWidget(self.lblDefaultClientUnit, 39, 0, 1, 1)
        self.lbTrnCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbTrnCode.sizePolicy().hasHeightForWidth())
        self.lbTrnCode.setSizePolicy(sizePolicy)
        self.lbTrnCode.setObjectName(_fromUtf8("lbTrnCode"))
        self.gridLayout_2.addWidget(self.lbTrnCode, 15, 0, 1, 1)
        self.lbDosageValue = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbDosageValue.sizePolicy().hasHeightForWidth())
        self.lbDosageValue.setSizePolicy(sizePolicy)
        self.lbDosageValue.setObjectName(_fromUtf8("lbDosageValue"))
        self.gridLayout_2.addWidget(self.lbDosageValue, 19, 0, 1, 1)
        self.edtProducer = QtGui.QLineEdit(self.tabMain)
        self.edtProducer.setObjectName(_fromUtf8("edtProducer"))
        self.gridLayout_2.addWidget(self.edtProducer, 18, 1, 1, 3)
        self.cmbDefaultClientUnit = CRBComboBox(self.tabMain)
        self.cmbDefaultClientUnit.setObjectName(_fromUtf8("cmbDefaultClientUnit"))
        self.gridLayout_2.addWidget(self.cmbDefaultClientUnit, 39, 1, 1, 3)
        self.lblVEN = QtGui.QLabel(self.tabMain)
        self.lblVEN.setObjectName(_fromUtf8("lblVEN"))
        self.gridLayout_2.addWidget(self.lblVEN, 28, 0, 1, 1)
        self.edtDosageValue = QtGui.QLineEdit(self.tabMain)
        self.edtDosageValue.setObjectName(_fromUtf8("edtDosageValue"))
        self.gridLayout_2.addWidget(self.edtDosageValue, 19, 1, 1, 3)
        self.lbMnnCode = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbMnnCode.sizePolicy().hasHeightForWidth())
        self.lbMnnCode.setSizePolicy(sizePolicy)
        self.lbMnnCode.setObjectName(_fromUtf8("lbMnnCode"))
        self.gridLayout_2.addWidget(self.lbMnnCode, 14, 0, 1, 1)
        self.lblATC = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblATC.sizePolicy().hasHeightForWidth())
        self.lblATC.setSizePolicy(sizePolicy)
        self.lblATC.setObjectName(_fromUtf8("lblATC"))
        self.gridLayout_2.addWidget(self.lblATC, 16, 0, 1, 1)
        self.edtRegionalCode = QtGui.QLineEdit(self.tabMain)
        self.edtRegionalCode.setObjectName(_fromUtf8("edtRegionalCode"))
        self.gridLayout_2.addWidget(self.edtRegionalCode, 10, 1, 1, 3)
        self.lblInDate = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInDate.sizePolicy().hasHeightForWidth())
        self.lblInDate.setSizePolicy(sizePolicy)
        self.lblInDate.setObjectName(_fromUtf8("lblInDate"))
        self.gridLayout_2.addWidget(self.lblInDate, 31, 0, 1, 1)
        self.edtExDate = QtGui.QDateEdit(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtExDate.sizePolicy().hasHeightForWidth())
        self.edtExDate.setSizePolicy(sizePolicy)
        self.edtExDate.setDate(QtCore.QDate(2099, 1, 1))
        self.edtExDate.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.edtExDate.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.edtExDate.setObjectName(_fromUtf8("edtExDate"))
        self.gridLayout_2.addWidget(self.edtExDate, 32, 1, 1, 2)
        self.cmbUnit = CRBComboBox(self.tabMain)
        self.cmbUnit.setObjectName(_fromUtf8("cmbUnit"))
        self.gridLayout_2.addWidget(self.cmbUnit, 21, 1, 1, 3)
        self.edtMnnCode = QtGui.QLineEdit(self.tabMain)
        self.edtMnnCode.setObjectName(_fromUtf8("edtMnnCode"))
        self.gridLayout_2.addWidget(self.edtMnnCode, 14, 1, 1, 3)
        self.edtATC = QtGui.QLineEdit(self.tabMain)
        self.edtATC.setObjectName(_fromUtf8("edtATC"))
        self.gridLayout_2.addWidget(self.edtATC, 16, 1, 1, 3)
        self.lblProducer = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProducer.sizePolicy().hasHeightForWidth())
        self.lblProducer.setSizePolicy(sizePolicy)
        self.lblProducer.setObjectName(_fromUtf8("lblProducer"))
        self.gridLayout_2.addWidget(self.lblProducer, 18, 0, 1, 1)
        self.spnPackSize = CSpinBox(self.tabMain)
        self.spnPackSize.setMaximum(9999)
        self.spnPackSize.setObjectName(_fromUtf8("spnPackSize"))
        self.gridLayout_2.addWidget(self.spnPackSize, 34, 1, 1, 1)
        self.edtCompleteness = QtGui.QLineEdit(self.tabMain)
        self.edtCompleteness.setObjectName(_fromUtf8("edtCompleteness"))
        self.gridLayout_2.addWidget(self.edtCompleteness, 37, 1, 1, 3)
        spacerItem = QtGui.QSpacerItem(173, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 34, 2, 1, 2)
        self.cmbNarcoticSubstance = QtGui.QComboBox(self.tabMain)
        self.cmbNarcoticSubstance.setObjectName(_fromUtf8("cmbNarcoticSubstance"))
        self.cmbNarcoticSubstance.addItem(_fromUtf8(""))
        self.cmbNarcoticSubstance.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbNarcoticSubstance, 30, 1, 1, 1)
        self.lblPackSize = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPackSize.sizePolicy().hasHeightForWidth())
        self.lblPackSize.setSizePolicy(sizePolicy)
        self.lblPackSize.setObjectName(_fromUtf8("lblPackSize"))
        self.gridLayout_2.addWidget(self.lblPackSize, 34, 0, 1, 1)
        self.lblCompleteness = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCompleteness.sizePolicy().hasHeightForWidth())
        self.lblCompleteness.setSizePolicy(sizePolicy)
        self.lblCompleteness.setObjectName(_fromUtf8("lblCompleteness"))
        self.gridLayout_2.addWidget(self.lblCompleteness, 37, 0, 1, 1)
        self.lblNarcoticSubstance = QtGui.QLabel(self.tabMain)
        self.lblNarcoticSubstance.setObjectName(_fromUtf8("lblNarcoticSubstance"))
        self.gridLayout_2.addWidget(self.lblNarcoticSubstance, 30, 0, 1, 1)
        self.lblDefaultStockUnit = QtGui.QLabel(self.tabMain)
        self.lblDefaultStockUnit.setObjectName(_fromUtf8("lblDefaultStockUnit"))
        self.gridLayout_2.addWidget(self.lblDefaultStockUnit, 38, 0, 1, 1)
        self.edtTrnCode = QtGui.QLineEdit(self.tabMain)
        self.edtTrnCode.setObjectName(_fromUtf8("edtTrnCode"))
        self.gridLayout_2.addWidget(self.edtTrnCode, 15, 1, 1, 3)
        self.cmbDefaultStockUnit = CRBComboBox(self.tabMain)
        self.cmbDefaultStockUnit.setObjectName(_fromUtf8("cmbDefaultStockUnit"))
        self.gridLayout_2.addWidget(self.cmbDefaultStockUnit, 38, 1, 1, 3)
        self.cmbVEN = QtGui.QComboBox(self.tabMain)
        self.cmbVEN.setObjectName(_fromUtf8("cmbVEN"))
        self.cmbVEN.addItem(_fromUtf8(""))
        self.cmbVEN.addItem(_fromUtf8(""))
        self.cmbVEN.addItem(_fromUtf8(""))
        self.cmbVEN.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbVEN, 28, 1, 1, 3)
        self.edtInDate = QtGui.QDateEdit(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtInDate.sizePolicy().hasHeightForWidth())
        self.edtInDate.setSizePolicy(sizePolicy)
        self.edtInDate.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.edtInDate.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.edtInDate.setObjectName(_fromUtf8("edtInDate"))
        self.gridLayout_2.addWidget(self.edtInDate, 31, 1, 1, 2)
        self.lbLfForm = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbLfForm.sizePolicy().hasHeightForWidth())
        self.lbLfForm.setSizePolicy(sizePolicy)
        self.lbLfForm.setObjectName(_fromUtf8("lbLfForm"))
        self.gridLayout_2.addWidget(self.lbLfForm, 26, 0, 1, 1)
        self.lbDosageUnit = QtGui.QLabel(self.tabMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbDosageUnit.sizePolicy().hasHeightForWidth())
        self.lbDosageUnit.setSizePolicy(sizePolicy)
        self.lbDosageUnit.setObjectName(_fromUtf8("lbDosageUnit"))
        self.gridLayout_2.addWidget(self.lbDosageUnit, 21, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 23, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 40, 0, 1, 1)
        self.tabWidget.addTab(self.tabMain, _fromUtf8(""))
        self.tabComposition = QtGui.QWidget()
        self.tabComposition.setObjectName(_fromUtf8("tabComposition"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabComposition)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblComposition = CInDocTableView(self.tabComposition)
        self.tblComposition.setObjectName(_fromUtf8("tblComposition"))
        self.gridLayout_4.addWidget(self.tblComposition, 0, 0, 1, 1)
        self.btnFillMNN = QtGui.QPushButton(self.tabComposition)
        self.btnFillMNN.setObjectName(_fromUtf8("btnFillMNN"))
        self.gridLayout_4.addWidget(self.btnFillMNN, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabComposition, _fromUtf8(""))
        self.tabFeatures = QtGui.QWidget()
        self.tabFeatures.setObjectName(_fromUtf8("tabFeatures"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabFeatures)
        self.verticalLayout_4.setMargin(4)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tblFeatures = CInDocTableView(self.tabFeatures)
        self.tblFeatures.setObjectName(_fromUtf8("tblFeatures"))
        self.verticalLayout_4.addWidget(self.tblFeatures)
        self.tabWidget.addTab(self.tabFeatures, _fromUtf8(""))
        self.tabIngredients = QtGui.QWidget()
        self.tabIngredients.setObjectName(_fromUtf8("tabIngredients"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabIngredients)
        self.verticalLayout_3.setMargin(4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tblIngredients = CInDocTableView(self.tabIngredients)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblIngredients.sizePolicy().hasHeightForWidth())
        self.tblIngredients.setSizePolicy(sizePolicy)
        self.tblIngredients.setObjectName(_fromUtf8("tblIngredients"))
        self.verticalLayout_3.addWidget(self.tblIngredients)
        self.tabWidget.addTab(self.tabIngredients, _fromUtf8(""))
        self.tabAnalogs = QtGui.QWidget()
        self.tabAnalogs.setObjectName(_fromUtf8("tabAnalogs"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabAnalogs)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblAnalogs = CInDocTableView(self.tabAnalogs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblAnalogs.sizePolicy().hasHeightForWidth())
        self.tblAnalogs.setSizePolicy(sizePolicy)
        self.tblAnalogs.setObjectName(_fromUtf8("tblAnalogs"))
        self.verticalLayout.addWidget(self.tblAnalogs)
        self.tabWidget.addTab(self.tabAnalogs, _fromUtf8(""))
        self.tabUnitRatio = QtGui.QWidget()
        self.tabUnitRatio.setObjectName(_fromUtf8("tabUnitRatio"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabUnitRatio)
        self.verticalLayout_5.setMargin(4)
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tblUnitRatio = CInDocTableView(self.tabUnitRatio)
        self.tblUnitRatio.setObjectName(_fromUtf8("tblUnitRatio"))
        self.verticalLayout_5.addWidget(self.tblUnitRatio)
        self.tabWidget.addTab(self.tabUnitRatio, _fromUtf8(""))
        self.tabUsingTypes = QtGui.QWidget()
        self.tabUsingTypes.setObjectName(_fromUtf8("tabUsingTypes"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabUsingTypes)
        self.verticalLayout_6.setMargin(4)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tblUsingTypes = CInDocTableView(self.tabUsingTypes)
        self.tblUsingTypes.setObjectName(_fromUtf8("tblUsingTypes"))
        self.verticalLayout_6.addWidget(self.tblUsingTypes)
        self.tabWidget.addTab(self.tabUsingTypes, _fromUtf8(""))
        self.tabIdentification = QtGui.QWidget()
        self.tabIdentification.setObjectName(_fromUtf8("tabIdentification"))
        self.gridLayout = QtGui.QGridLayout(self.tabIdentification)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tblIdentification = CInDocTableView(self.tabIdentification)
        self.tblIdentification.setObjectName(_fromUtf8("tblIdentification"))
        self.gridLayout.addWidget(self.tblIdentification, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIdentification, _fromUtf8(""))
        self.btnSplitter = QtGui.QSplitter(self.formSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSplitter.sizePolicy().hasHeightForWidth())
        self.btnSplitter.setSizePolicy(sizePolicy)
        self.btnSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.btnSplitter.setObjectName(_fromUtf8("btnSplitter"))
        self.buttonBox = QtGui.QDialogButtonBox(self.btnSplitter)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.formSplitter, 0, 0, 1, 1)
        self.lblCode.setBuddy(self.edtCode)
        self.lblType.setBuddy(self.cmbType)
        self.lblName.setBuddy(self.edtName)
        self.lblKind.setBuddy(self.cmbKind)
        self.lblInternationalNonproprietaryName.setBuddy(self.edtInternationalNonproprietaryName)
        self.lblRegionalCode.setBuddy(self.edtRegionalCode)
        self.lblClass.setBuddy(self.cmbClass)
        self.lblATC.setBuddy(self.edtATC)
        self.lblProducer.setBuddy(self.edtProducer)
        self.lblPackSize.setBuddy(self.spnPackSize)

        self.retranslateUi(ItemEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ItemEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ItemEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ItemEditorDialog)
        ItemEditorDialog.setTabOrder(self.cmbESLKPName, self.btnESLKPFill)
        ItemEditorDialog.setTabOrder(self.btnESLKPFill, self.cmbClass)
        ItemEditorDialog.setTabOrder(self.cmbClass, self.cmbKind)
        ItemEditorDialog.setTabOrder(self.cmbKind, self.cmbType)
        ItemEditorDialog.setTabOrder(self.cmbType, self.edtCode)
        ItemEditorDialog.setTabOrder(self.edtCode, self.edtName)
        ItemEditorDialog.setTabOrder(self.edtName, self.edtOriginName)
        ItemEditorDialog.setTabOrder(self.edtOriginName, self.edtInternationalNonproprietaryName)
        ItemEditorDialog.setTabOrder(self.edtInternationalNonproprietaryName, self.edtMnnLatin)
        ItemEditorDialog.setTabOrder(self.edtMnnLatin, self.edtRegionalCode)
        ItemEditorDialog.setTabOrder(self.edtRegionalCode, self.edtMnnCode)
        ItemEditorDialog.setTabOrder(self.edtMnnCode, self.edtTrnCode)
        ItemEditorDialog.setTabOrder(self.edtTrnCode, self.edtATC)
        ItemEditorDialog.setTabOrder(self.edtATC, self.edtProducer)
        ItemEditorDialog.setTabOrder(self.edtProducer, self.edtDosageValue)
        ItemEditorDialog.setTabOrder(self.edtDosageValue, self.cmbUnit)
        ItemEditorDialog.setTabOrder(self.cmbUnit, self.cmbLfForm)
        ItemEditorDialog.setTabOrder(self.cmbLfForm, self.edtInDate)
        ItemEditorDialog.setTabOrder(self.edtInDate, self.edtExDate)
        ItemEditorDialog.setTabOrder(self.edtExDate, self.spnPackSize)
        ItemEditorDialog.setTabOrder(self.spnPackSize, self.edtCompleteness)
        ItemEditorDialog.setTabOrder(self.edtCompleteness, self.cmbDefaultStockUnit)
        ItemEditorDialog.setTabOrder(self.cmbDefaultStockUnit, self.cmbDefaultClientUnit)
        ItemEditorDialog.setTabOrder(self.cmbDefaultClientUnit, self.tabWidget)
        ItemEditorDialog.setTabOrder(self.tabWidget, self.tblFeatures)
        ItemEditorDialog.setTabOrder(self.tblFeatures, self.tblIngredients)
        ItemEditorDialog.setTabOrder(self.tblIngredients, self.tblAnalogs)
        ItemEditorDialog.setTabOrder(self.tblAnalogs, self.tblUnitRatio)
        ItemEditorDialog.setTabOrder(self.tblUnitRatio, self.buttonBox)
        ItemEditorDialog.setTabOrder(self.buttonBox, self.cmbVEN)
        ItemEditorDialog.setTabOrder(self.cmbVEN, self.tblComposition)
        ItemEditorDialog.setTabOrder(self.tblComposition, self.btnFillMNN)
        ItemEditorDialog.setTabOrder(self.btnFillMNN, self.tblUsingTypes)
        ItemEditorDialog.setTabOrder(self.tblUsingTypes, self.tblIdentification)

    def retranslateUi(self, ItemEditorDialog):
        ItemEditorDialog.setWindowTitle(_translate("ItemEditorDialog", "ChangeMe!", None))
        self.cmbESLKPName.setToolTip(_translate("ItemEditorDialog", "Единый структурированный справочник-каталог лекарственных препаратов", None))
        self.lblCode.setText(_translate("ItemEditorDialog", "Код", None))
        self.btnESLKPFill.setText(_translate("ItemEditorDialog", "Заполнить", None))
        self.lblMnnLatin.setText(_translate("ItemEditorDialog", "МНН на латинском", None))
        self.lblType.setText(_translate("ItemEditorDialog", "Тип", None))
        self.lblName.setText(_translate("ItemEditorDialog", "ТН на русском", None))
        self.lblESLKPName.setToolTip(_translate("ItemEditorDialog", "Единый структурированный справочник-каталог лекарственных препаратов", None))
        self.lblESLKPName.setText(_translate("ItemEditorDialog", "Название по ЕСКЛП", None))
        self.lblKind.setText(_translate("ItemEditorDialog", "Вид", None))
        self.lblInternationalNonproprietaryName.setText(_translate("ItemEditorDialog", "МНН на русском", None))
        self.lblRegionalCode.setText(_translate("ItemEditorDialog", "Региональный код", None))
        self.lblClass.setText(_translate("ItemEditorDialog", "Класс", None))
        self.lblOriginName.setText(_translate("ItemEditorDialog", "ТН на латинском", None))
        self.lblExDate.setText(_translate("ItemEditorDialog", "Дата исключения", None))
        self.lblDefaultClientUnit.setText(_translate("ItemEditorDialog", "Расходная единица по умолчанию", None))
        self.lbTrnCode.setText(_translate("ItemEditorDialog", "Код по ТРН", None))
        self.lbDosageValue.setText(_translate("ItemEditorDialog", "Дозировка", None))
        self.lblVEN.setText(_translate("ItemEditorDialog", "VEN-классификация", None))
        self.lbMnnCode.setText(_translate("ItemEditorDialog", "Код по  МНН", None))
        self.lblATC.setText(_translate("ItemEditorDialog", "Код АТХ", None))
        self.lblInDate.setText(_translate("ItemEditorDialog", "Дата включения", None))
        self.edtExDate.setDisplayFormat(_translate("ItemEditorDialog", "dd.MM.yyyy", None))
        self.lblProducer.setText(_translate("ItemEditorDialog", "Производитель", None))
        self.cmbNarcoticSubstance.setItemText(0, _translate("ItemEditorDialog", "Нет", None))
        self.cmbNarcoticSubstance.setItemText(1, _translate("ItemEditorDialog", "Да", None))
        self.lblPackSize.setText(_translate("ItemEditorDialog", "Объём упаковки", None))
        self.lblCompleteness.setText(_translate("ItemEditorDialog", "Комплектность", None))
        self.lblNarcoticSubstance.setText(_translate("ItemEditorDialog", "Наркот./психотроп. вещество", None))
        self.lblDefaultStockUnit.setText(_translate("ItemEditorDialog", "Упаковочная единица по умолчанию", None))
        self.cmbVEN.setItemText(0, _translate("ItemEditorDialog", "не задано", None))
        self.cmbVEN.setItemText(1, _translate("ItemEditorDialog", "жизненно важные", None))
        self.cmbVEN.setItemText(2, _translate("ItemEditorDialog", "необходимые", None))
        self.cmbVEN.setItemText(3, _translate("ItemEditorDialog", "второстепенные", None))
        self.edtInDate.setDisplayFormat(_translate("ItemEditorDialog", "dd.MM.yyyy", None))
        self.lbLfForm.setText(_translate("ItemEditorDialog", "Форма выпуска", None))
        self.lbDosageUnit.setText(_translate("ItemEditorDialog", "Ед. Дозировки", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMain), _translate("ItemEditorDialog", "Описание", None))
        self.btnFillMNN.setText(_translate("ItemEditorDialog", "Заполнить МНН", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabComposition), _translate("ItemEditorDialog", "Состав", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFeatures), _translate("ItemEditorDialog", "Характеристики", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIngredients), _translate("ItemEditorDialog", "Ингредиенты", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnalogs), _translate("ItemEditorDialog", "Аналоги", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUnitRatio), _translate("ItemEditorDialog", "Отношения Ед. учета", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUsingTypes), _translate("ItemEditorDialog", "Способы применения", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIdentification), _translate("ItemEditorDialog", "Идентификация", None))

from RefBooks.Nomenclature.ReleaseFormComboBox import CReleaseFormComboBox
from library.ESKLP.ESKLPComboBox import CESKLPComboBox
from library.InDocTable import CInDocTableView
from library.SpinBox import CSpinBox
from library.crbcombobox import CRBComboBox
