# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/work/kmivc-arch/Samson/client_test/Events/ActionEditDialog.ui'
#
# Created by: PyQt4 UI code generator 4.12.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActionDialog(object):
    def setupUi(self, ActionDialog):
        ActionDialog.setObjectName(_fromUtf8("ActionDialog"))
        ActionDialog.resize(1168, 617)
        self.gridLayout_3 = QtGui.QGridLayout(ActionDialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter = QtGui.QSplitter(ActionDialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.txtClientInfoBrowser = CTextBrowser(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtClientInfoBrowser.sizePolicy().hasHeightForWidth())
        self.txtClientInfoBrowser.setSizePolicy(sizePolicy)
        self.txtClientInfoBrowser.setMinimumSize(QtCore.QSize(0, 100))
        self.txtClientInfoBrowser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txtClientInfoBrowser.setReadOnly(True)
        self.txtClientInfoBrowser.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.txtClientInfoBrowser.setObjectName(_fromUtf8("txtClientInfoBrowser"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter1 = QtGui.QSplitter(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter1.sizePolicy().hasHeightForWidth())
        self.splitter1.setSizePolicy(sizePolicy)
        self.splitter1.setOrientation(QtCore.Qt.Horizontal)
        self.splitter1.setObjectName(_fromUtf8("splitter1"))
        self.tblProps = CActionPropertiesTableView(self.splitter1)
        self.tblProps.setEnabled(True)
        self.tblProps.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblProps.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblProps.setObjectName(_fromUtf8("tblProps"))
        self.wgtUserDictionary = QtGui.QWidget(self.splitter1)
        self.wgtUserDictionary.setObjectName(_fromUtf8("wgtUserDictionary"))
        self.gridLayout_31 = QtGui.QGridLayout(self.wgtUserDictionary)
        self.gridLayout_31.setMargin(0)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.btnEditUserDictionary = QtGui.QPushButton(self.wgtUserDictionary)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditUserDictionary.sizePolicy().hasHeightForWidth())
        self.btnEditUserDictionary.setSizePolicy(sizePolicy)
        self.btnEditUserDictionary.setObjectName(_fromUtf8("btnEditUserDictionary"))
        self.gridLayout_31.addWidget(self.btnEditUserDictionary, 0, 1, 1, 1)
        self.lvUserDictionary = CUserDictionaryListView(self.wgtUserDictionary)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvUserDictionary.sizePolicy().hasHeightForWidth())
        self.lvUserDictionary.setSizePolicy(sizePolicy)
        self.lvUserDictionary.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lvUserDictionary.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.lvUserDictionary.setAlternatingRowColors(True)
        self.lvUserDictionary.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.lvUserDictionary.setWordWrap(True)
        self.lvUserDictionary.setObjectName(_fromUtf8("lvUserDictionary"))
        self.gridLayout_31.addWidget(self.lvUserDictionary, 1, 0, 1, 2)
        self.edtUserDictionarySearch = QtGui.QLineEdit(self.wgtUserDictionary)
        self.edtUserDictionarySearch.setObjectName(_fromUtf8("edtUserDictionarySearch"))
        self.gridLayout_31.addWidget(self.edtUserDictionarySearch, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.splitter1, 3, 0, 1, 1)
        self.btnCloseWidgets = CActionWidgetVisibilityButton(self.layoutWidget)
        self.btnCloseWidgets.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.btnCloseWidgets.setArrowType(QtCore.Qt.NoArrow)
        self.btnCloseWidgets.setObjectName(_fromUtf8("btnCloseWidgets"))
        self.gridLayout.addWidget(self.btnCloseWidgets, 2, 0, 1, 1)
        self.frmWidgets = QtGui.QFrame(self.layoutWidget)
        self.frmWidgets.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmWidgets.setFrameShadow(QtGui.QFrame.Plain)
        self.frmWidgets.setLineWidth(0)
        self.frmWidgets.setObjectName(_fromUtf8("frmWidgets"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frmWidgets)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pnlMainMKBWidgets = QtGui.QWidget(self.frmWidgets)
        self.pnlMainMKBWidgets.setObjectName(_fromUtf8("pnlMainMKBWidgets"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.pnlMainMKBWidgets)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pnlMKBWidgets = QtGui.QWidget(self.pnlMainMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnlMKBWidgets.sizePolicy().hasHeightForWidth())
        self.pnlMKBWidgets.setSizePolicy(sizePolicy)
        self.pnlMKBWidgets.setObjectName(_fromUtf8("pnlMKBWidgets"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.pnlMKBWidgets)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.lblMorphologyMKB = QtGui.QLabel(self.pnlMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMorphologyMKB.sizePolicy().hasHeightForWidth())
        self.lblMorphologyMKB.setSizePolicy(sizePolicy)
        self.lblMorphologyMKB.setObjectName(_fromUtf8("lblMorphologyMKB"))
        self.horizontalLayout_8.addWidget(self.lblMorphologyMKB)
        self.cmbMorphologyMKB = CICDMorphologyCodeEditEx(self.pnlMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMorphologyMKB.sizePolicy().hasHeightForWidth())
        self.cmbMorphologyMKB.setSizePolicy(sizePolicy)
        self.cmbMorphologyMKB.setMinimumSize(QtCore.QSize(20, 0))
        self.cmbMorphologyMKB.setObjectName(_fromUtf8("cmbMorphologyMKB"))
        self.horizontalLayout_8.addWidget(self.cmbMorphologyMKB)
        self.horizontalLayout_9.addWidget(self.pnlMKBWidgets)
        self.lblMKB = QtGui.QLabel(self.pnlMainMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMKB.sizePolicy().hasHeightForWidth())
        self.lblMKB.setSizePolicy(sizePolicy)
        self.lblMKB.setObjectName(_fromUtf8("lblMKB"))
        self.horizontalLayout_9.addWidget(self.lblMKB)
        self.cmbMKB = CICDCodeEditEx(self.pnlMainMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbMKB.sizePolicy().hasHeightForWidth())
        self.cmbMKB.setSizePolicy(sizePolicy)
        self.cmbMKB.setObjectName(_fromUtf8("cmbMKB"))
        self.horizontalLayout_9.addWidget(self.cmbMKB)
        self.lblMKBText = QtGui.QLabel(self.pnlMainMKBWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMKBText.sizePolicy().hasHeightForWidth())
        self.lblMKBText.setSizePolicy(sizePolicy)
        self.lblMKBText.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblMKBText.setText(_fromUtf8(""))
        self.lblMKBText.setWordWrap(True)
        self.lblMKBText.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.lblMKBText.setObjectName(_fromUtf8("lblMKBText"))
        self.horizontalLayout_9.addWidget(self.lblMKBText)
        self.gridLayout_2.addWidget(self.pnlMainMKBWidgets, 1, 4, 1, 11)
        self.frmCoordDate = QtGui.QFrame(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmCoordDate.sizePolicy().hasHeightForWidth())
        self.frmCoordDate.setSizePolicy(sizePolicy)
        self.frmCoordDate.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmCoordDate.setFrameShadow(QtGui.QFrame.Plain)
        self.frmCoordDate.setLineWidth(0)
        self.frmCoordDate.setObjectName(_fromUtf8("frmCoordDate"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frmCoordDate)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.edtCoordDate = CDateEdit(self.frmCoordDate)
        self.edtCoordDate.setEnabled(False)
        self.edtCoordDate.setCalendarPopup(True)
        self.edtCoordDate.setObjectName(_fromUtf8("edtCoordDate"))
        self.horizontalLayout_4.addWidget(self.edtCoordDate)
        self.edtCoordTime = QtGui.QTimeEdit(self.frmCoordDate)
        self.edtCoordTime.setEnabled(False)
        self.edtCoordTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtCoordTime.setObjectName(_fromUtf8("edtCoordTime"))
        self.horizontalLayout_4.addWidget(self.edtCoordTime)
        self.gridLayout_2.addWidget(self.frmCoordDate, 8, 1, 1, 1)
        self.frmTop = QtGui.QWidget(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmTop.sizePolicy().hasHeightForWidth())
        self.frmTop.setSizePolicy(sizePolicy)
        self.frmTop.setObjectName(_fromUtf8("frmTop"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frmTop)
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.frmDirectionDate = QtGui.QFrame(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmDirectionDate.sizePolicy().hasHeightForWidth())
        self.frmDirectionDate.setSizePolicy(sizePolicy)
        self.frmDirectionDate.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmDirectionDate.setFrameShadow(QtGui.QFrame.Plain)
        self.frmDirectionDate.setLineWidth(0)
        self.frmDirectionDate.setObjectName(_fromUtf8("frmDirectionDate"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frmDirectionDate)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtDirectionDate = CDateEdit(self.frmDirectionDate)
        self.edtDirectionDate.setEnabled(False)
        self.edtDirectionDate.setCalendarPopup(True)
        self.edtDirectionDate.setObjectName(_fromUtf8("edtDirectionDate"))
        self.horizontalLayout.addWidget(self.edtDirectionDate)
        self.edtDirectionTime = CTimeEdit(self.frmDirectionDate)
        self.edtDirectionTime.setEnabled(False)
        self.edtDirectionTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtDirectionTime.setObjectName(_fromUtf8("edtDirectionTime"))
        self.horizontalLayout.addWidget(self.edtDirectionTime)
        self.chkIsUrgent = QtGui.QCheckBox(self.frmDirectionDate)
        self.chkIsUrgent.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkIsUrgent.sizePolicy().hasHeightForWidth())
        self.chkIsUrgent.setSizePolicy(sizePolicy)
        self.chkIsUrgent.setObjectName(_fromUtf8("chkIsUrgent"))
        self.horizontalLayout.addWidget(self.chkIsUrgent)
        self.horizontalLayout_5.addWidget(self.frmDirectionDate)
        self.lblSetPerson = QtGui.QLabel(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSetPerson.sizePolicy().hasHeightForWidth())
        self.lblSetPerson.setSizePolicy(sizePolicy)
        self.lblSetPerson.setObjectName(_fromUtf8("lblSetPerson"))
        self.horizontalLayout_5.addWidget(self.lblSetPerson)
        self.cmbSetPerson = CPersonWithOrgListComboBoxEx(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSetPerson.sizePolicy().hasHeightForWidth())
        self.cmbSetPerson.setSizePolicy(sizePolicy)
        self.cmbSetPerson.setObjectName(_fromUtf8("cmbSetPerson"))
        self.cmbSetPerson.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.cmbSetPerson)
        self.frmPlannedEndDateTime = QtGui.QFrame(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmPlannedEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmPlannedEndDateTime.setSizePolicy(sizePolicy)
        self.frmPlannedEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmPlannedEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmPlannedEndDateTime.setLineWidth(0)
        self.frmPlannedEndDateTime.setObjectName(_fromUtf8("frmPlannedEndDateTime"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frmPlannedEndDateTime)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lbPlannedEndDate = QtGui.QLabel(self.frmPlannedEndDateTime)
        self.lbPlannedEndDate.setObjectName(_fromUtf8("lbPlannedEndDate"))
        self.horizontalLayout_7.addWidget(self.lbPlannedEndDate)
        self.edtPlannedEndDate = CDateEdit(self.frmPlannedEndDateTime)
        self.edtPlannedEndDate.setCalendarPopup(True)
        self.edtPlannedEndDate.setObjectName(_fromUtf8("edtPlannedEndDate"))
        self.horizontalLayout_7.addWidget(self.edtPlannedEndDate)
        self.edtPlannedEndTime = QtGui.QTimeEdit(self.frmPlannedEndDateTime)
        self.edtPlannedEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtPlannedEndTime.setObjectName(_fromUtf8("edtPlannedEndTime"))
        self.horizontalLayout_7.addWidget(self.edtPlannedEndTime)
        self.horizontalLayout_5.addWidget(self.frmPlannedEndDateTime)
        self.gridLayout_2.addWidget(self.frmTop, 0, 1, 1, 14)
        self.frmMiddle = QtGui.QWidget(self.frmWidgets)
        self.frmMiddle.setObjectName(_fromUtf8("frmMiddle"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frmMiddle)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.cmbStatus = CActionStatusComboBox(self.frmMiddle)
        self.cmbStatus.setMinimumSize(QtCore.QSize(80, 0))
        self.cmbStatus.setObjectName(_fromUtf8("cmbStatus"))
        self.horizontalLayout_6.addWidget(self.cmbStatus)
        self.frmBegDateTime = QtGui.QFrame(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmBegDateTime.sizePolicy().hasHeightForWidth())
        self.frmBegDateTime.setSizePolicy(sizePolicy)
        self.frmBegDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmBegDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmBegDateTime.setLineWidth(0)
        self.frmBegDateTime.setObjectName(_fromUtf8("frmBegDateTime"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frmBegDateTime)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblBegDate = QtGui.QLabel(self.frmBegDateTime)
        self.lblBegDate.setObjectName(_fromUtf8("lblBegDate"))
        self.horizontalLayout_2.addWidget(self.lblBegDate)
        self.edtBegDate = CDateEdit(self.frmBegDateTime)
        self.edtBegDate.setCalendarPopup(True)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout_2.addWidget(self.edtBegDate)
        self.edtBegTime = CTimeEdit(self.frmBegDateTime)
        self.edtBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtBegTime.setObjectName(_fromUtf8("edtBegTime"))
        self.horizontalLayout_2.addWidget(self.edtBegTime)
        self.horizontalLayout_6.addWidget(self.frmBegDateTime)
        self.frmEndDateTime = QtGui.QFrame(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmEndDateTime.setSizePolicy(sizePolicy)
        self.frmEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmEndDateTime.setLineWidth(0)
        self.frmEndDateTime.setObjectName(_fromUtf8("frmEndDateTime"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frmEndDateTime)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lbEndDate = QtGui.QLabel(self.frmEndDateTime)
        self.lbEndDate.setObjectName(_fromUtf8("lbEndDate"))
        self.horizontalLayout_3.addWidget(self.lbEndDate)
        self.edtEndDate = CDateEdit(self.frmEndDateTime)
        self.edtEndDate.setCalendarPopup(True)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout_3.addWidget(self.edtEndDate)
        self.edtEndTime = CTimeEdit(self.frmEndDateTime)
        self.edtEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtEndTime.setObjectName(_fromUtf8("edtEndTime"))
        self.horizontalLayout_3.addWidget(self.edtEndTime)
        self.horizontalLayout_6.addWidget(self.frmEndDateTime)
        self.lblAmount = QtGui.QLabel(self.frmMiddle)
        self.lblAmount.setObjectName(_fromUtf8("lblAmount"))
        self.horizontalLayout_6.addWidget(self.lblAmount)
        self.edtAmount = QtGui.QDoubleSpinBox(self.frmMiddle)
        self.edtAmount.setMaximum(999.99)
        self.edtAmount.setObjectName(_fromUtf8("edtAmount"))
        self.horizontalLayout_6.addWidget(self.edtAmount)
        self.lblUet = QtGui.QLabel(self.frmMiddle)
        self.lblUet.setObjectName(_fromUtf8("lblUet"))
        self.horizontalLayout_6.addWidget(self.lblUet)
        self.edtUet = QtGui.QDoubleSpinBox(self.frmMiddle)
        self.edtUet.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtUet.sizePolicy().hasHeightForWidth())
        self.edtUet.setSizePolicy(sizePolicy)
        self.edtUet.setSingleStep(0.5)
        self.edtUet.setObjectName(_fromUtf8("edtUet"))
        self.horizontalLayout_6.addWidget(self.edtUet)
        self.lblOffice = QtGui.QLabel(self.frmMiddle)
        self.lblOffice.setObjectName(_fromUtf8("lblOffice"))
        self.horizontalLayout_6.addWidget(self.lblOffice)
        self.edtOffice = QtGui.QLineEdit(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOffice.sizePolicy().hasHeightForWidth())
        self.edtOffice.setSizePolicy(sizePolicy)
        self.edtOffice.setMaxLength(16)
        self.edtOffice.setObjectName(_fromUtf8("edtOffice"))
        self.horizontalLayout_6.addWidget(self.edtOffice)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.frmMiddle, 2, 1, 1, 14)
        self.lblDirectionDate = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDirectionDate.sizePolicy().hasHeightForWidth())
        self.lblDirectionDate.setSizePolicy(sizePolicy)
        self.lblDirectionDate.setObjectName(_fromUtf8("lblDirectionDate"))
        self.gridLayout_2.addWidget(self.lblDirectionDate, 0, 0, 1, 1)
        self.btnSelectOrg = QtGui.QToolButton(self.frmWidgets)
        self.btnSelectOrg.setObjectName(_fromUtf8("btnSelectOrg"))
        self.gridLayout_2.addWidget(self.btnSelectOrg, 1, 3, 1, 1)
        self.lblCoordText = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCoordText.sizePolicy().hasHeightForWidth())
        self.lblCoordText.setSizePolicy(sizePolicy)
        self.lblCoordText.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblCoordText.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblCoordText.setText(_fromUtf8(""))
        self.lblCoordText.setObjectName(_fromUtf8("lblCoordText"))
        self.gridLayout_2.addWidget(self.lblCoordText, 8, 2, 1, 13)
        self.lblNote = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNote.sizePolicy().hasHeightForWidth())
        self.lblNote.setSizePolicy(sizePolicy)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout_2.addWidget(self.lblNote, 7, 0, 1, 1)
        self.lblPerson = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPerson.sizePolicy().hasHeightForWidth())
        self.lblPerson.setSizePolicy(sizePolicy)
        self.lblPerson.setObjectName(_fromUtf8("lblPerson"))
        self.gridLayout_2.addWidget(self.lblPerson, 3, 0, 1, 1)
        self.lblStatus = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.gridLayout_2.addWidget(self.lblStatus, 2, 0, 1, 1)
        self.lblOrg = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrg.sizePolicy().hasHeightForWidth())
        self.lblOrg.setSizePolicy(sizePolicy)
        self.lblOrg.setObjectName(_fromUtf8("lblOrg"))
        self.gridLayout_2.addWidget(self.lblOrg, 1, 0, 1, 1)
        self.lblCoordDate = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCoordDate.sizePolicy().hasHeightForWidth())
        self.lblCoordDate.setSizePolicy(sizePolicy)
        self.lblCoordDate.setObjectName(_fromUtf8("lblCoordDate"))
        self.gridLayout_2.addWidget(self.lblCoordDate, 8, 0, 1, 1)
        self.lblActionSpecification = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblActionSpecification.sizePolicy().hasHeightForWidth())
        self.lblActionSpecification.setSizePolicy(sizePolicy)
        self.lblActionSpecification.setObjectName(_fromUtf8("lblActionSpecification"))
        self.gridLayout_2.addWidget(self.lblActionSpecification, 9, 0, 1, 3)
        self.cmbOrg = CPolyclinicComboBox(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrg.sizePolicy().hasHeightForWidth())
        self.cmbOrg.setSizePolicy(sizePolicy)
        self.cmbOrg.setObjectName(_fromUtf8("cmbOrg"))
        self.cmbOrg.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbOrg, 1, 1, 1, 2)
        self.lblOrgStructure = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblOrgStructure.setSizePolicy(sizePolicy)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridLayout_2.addWidget(self.lblOrgStructure, 4, 0, 1, 1)
        self.cmbPerson = CPersonWithOrgListComboBoxEx(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPerson.sizePolicy().hasHeightForWidth())
        self.cmbPerson.setSizePolicy(sizePolicy)
        self.cmbPerson.setObjectName(_fromUtf8("cmbPerson"))
        self.cmbPerson.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbPerson, 3, 1, 1, 14)
        self.cmbOrgStructure = COrgStructureComboBox(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOrgStructure.sizePolicy().hasHeightForWidth())
        self.cmbOrgStructure.setSizePolicy(sizePolicy)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridLayout_2.addWidget(self.cmbOrgStructure, 4, 1, 1, 1)
        self.cmbActionSpecification = CRBComboBox(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbActionSpecification.sizePolicy().hasHeightForWidth())
        self.cmbActionSpecification.setSizePolicy(sizePolicy)
        self.cmbActionSpecification.setObjectName(_fromUtf8("cmbActionSpecification"))
        self.gridLayout_2.addWidget(self.cmbActionSpecification, 9, 3, 1, 4)
        self.lblAssistant = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAssistant.sizePolicy().hasHeightForWidth())
        self.lblAssistant.setSizePolicy(sizePolicy)
        self.lblAssistant.setObjectName(_fromUtf8("lblAssistant"))
        self.gridLayout_2.addWidget(self.lblAssistant, 4, 2, 1, 1)
        self.edtAliquoticity = QtGui.QSpinBox(self.frmWidgets)
        self.edtAliquoticity.setObjectName(_fromUtf8("edtAliquoticity"))
        self.gridLayout_2.addWidget(self.edtAliquoticity, 4, 14, 1, 1)
        self.lblAliquoticity = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAliquoticity.sizePolicy().hasHeightForWidth())
        self.lblAliquoticity.setSizePolicy(sizePolicy)
        self.lblAliquoticity.setObjectName(_fromUtf8("lblAliquoticity"))
        self.gridLayout_2.addWidget(self.lblAliquoticity, 4, 13, 1, 1)
        self.btnAPNomenclatureExpense = QtGui.QPushButton(self.frmWidgets)
        self.btnAPNomenclatureExpense.setObjectName(_fromUtf8("btnAPNomenclatureExpense"))
        self.gridLayout_2.addWidget(self.btnAPNomenclatureExpense, 7, 12, 1, 1)
        self.btnPortal_Doctor = QtGui.QPushButton(self.frmWidgets)
        self.btnPortal_Doctor.setObjectName(_fromUtf8("btnPortal_Doctor"))
        self.gridLayout_2.addWidget(self.btnPortal_Doctor, 7, 10, 1, 1)
        self.lblPeriodicity = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPeriodicity.sizePolicy().hasHeightForWidth())
        self.lblPeriodicity.setSizePolicy(sizePolicy)
        self.lblPeriodicity.setObjectName(_fromUtf8("lblPeriodicity"))
        self.gridLayout_2.addWidget(self.lblPeriodicity, 4, 11, 1, 1)
        self.edtDuration = QtGui.QSpinBox(self.frmWidgets)
        self.edtDuration.setObjectName(_fromUtf8("edtDuration"))
        self.gridLayout_2.addWidget(self.edtDuration, 4, 10, 1, 1)
        self.lblDuration = QtGui.QLabel(self.frmWidgets)
        self.lblDuration.setObjectName(_fromUtf8("lblDuration"))
        self.gridLayout_2.addWidget(self.lblDuration, 4, 9, 1, 1)
        self.edtPeriodicity = QtGui.QSpinBox(self.frmWidgets)
        self.edtPeriodicity.setObjectName(_fromUtf8("edtPeriodicity"))
        self.gridLayout_2.addWidget(self.edtPeriodicity, 4, 12, 1, 1)
        self.btnPlanNextAction = QtGui.QToolButton(self.frmWidgets)
        self.btnPlanNextAction.setEnabled(False)
        self.btnPlanNextAction.setObjectName(_fromUtf8("btnPlanNextAction"))
        self.gridLayout_2.addWidget(self.btnPlanNextAction, 7, 9, 1, 1)
        self.btnAPQueueManagement = QtGui.QPushButton(self.frmWidgets)
        self.btnAPQueueManagement.setObjectName(_fromUtf8("btnAPQueueManagement"))
        self.gridLayout_2.addWidget(self.btnAPQueueManagement, 7, 8, 1, 1)
        self.btnNextAction = QtGui.QPushButton(self.frmWidgets)
        self.btnNextAction.setEnabled(False)
        self.btnNextAction.setObjectName(_fromUtf8("btnNextAction"))
        self.gridLayout_2.addWidget(self.btnNextAction, 7, 7, 1, 1)
        self.edtQuantity = QtGui.QSpinBox(self.frmWidgets)
        self.edtQuantity.setObjectName(_fromUtf8("edtQuantity"))
        self.gridLayout_2.addWidget(self.edtQuantity, 4, 8, 1, 1)
        self.lblQuantity = QtGui.QLabel(self.frmWidgets)
        self.lblQuantity.setObjectName(_fromUtf8("lblQuantity"))
        self.gridLayout_2.addWidget(self.lblQuantity, 4, 7, 1, 1)
        self.cmbAssistant = CPersonWithOrgListComboBoxEx(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAssistant.sizePolicy().hasHeightForWidth())
        self.cmbAssistant.setSizePolicy(sizePolicy)
        self.cmbAssistant.setObjectName(_fromUtf8("cmbAssistant"))
        self.cmbAssistant.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cmbAssistant, 4, 3, 1, 4)
        self.edtNote = QtGui.QLineEdit(self.frmWidgets)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout_2.addWidget(self.edtNote, 7, 1, 1, 6)
        self.gridLayout.addWidget(self.frmWidgets, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ActionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.lblSetPerson.setBuddy(self.cmbSetPerson)
        self.lbPlannedEndDate.setBuddy(self.edtPlannedEndDate)
        self.lblBegDate.setBuddy(self.edtBegDate)
        self.lbEndDate.setBuddy(self.edtEndDate)
        self.lblAmount.setBuddy(self.edtAmount)
        self.lblUet.setBuddy(self.edtUet)
        self.lblOffice.setBuddy(self.edtOffice)
        self.lblDirectionDate.setBuddy(self.edtDirectionDate)
        self.lblNote.setBuddy(self.edtNote)
        self.lblPerson.setBuddy(self.cmbPerson)
        self.lblStatus.setBuddy(self.cmbStatus)
        self.lblCoordDate.setBuddy(self.edtCoordDate)
        self.lblAssistant.setBuddy(self.cmbAssistant)

        self.retranslateUi(ActionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ActionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ActionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ActionDialog)
        ActionDialog.setTabOrder(self.txtClientInfoBrowser, self.edtDirectionDate)
        ActionDialog.setTabOrder(self.edtDirectionDate, self.edtDirectionTime)
        ActionDialog.setTabOrder(self.edtDirectionTime, self.chkIsUrgent)
        ActionDialog.setTabOrder(self.chkIsUrgent, self.cmbSetPerson)
        ActionDialog.setTabOrder(self.cmbSetPerson, self.edtPlannedEndDate)
        ActionDialog.setTabOrder(self.edtPlannedEndDate, self.edtPlannedEndTime)
        ActionDialog.setTabOrder(self.edtPlannedEndTime, self.cmbMorphologyMKB)
        ActionDialog.setTabOrder(self.cmbMorphologyMKB, self.cmbMKB)
        ActionDialog.setTabOrder(self.cmbMKB, self.cmbStatus)
        ActionDialog.setTabOrder(self.cmbStatus, self.edtBegDate)
        ActionDialog.setTabOrder(self.edtBegDate, self.edtBegTime)
        ActionDialog.setTabOrder(self.edtBegTime, self.edtEndDate)
        ActionDialog.setTabOrder(self.edtEndDate, self.edtEndTime)
        ActionDialog.setTabOrder(self.edtEndTime, self.edtAmount)
        ActionDialog.setTabOrder(self.edtAmount, self.edtUet)
        ActionDialog.setTabOrder(self.edtUet, self.edtOffice)
        ActionDialog.setTabOrder(self.edtOffice, self.edtCoordDate)
        ActionDialog.setTabOrder(self.edtCoordDate, self.edtCoordTime)
        ActionDialog.setTabOrder(self.edtCoordTime, self.tblProps)
        ActionDialog.setTabOrder(self.tblProps, self.buttonBox)

    def retranslateUi(self, ActionDialog):
        ActionDialog.setWindowTitle(_translate("ActionDialog", "Dialog", None))
        self.txtClientInfoBrowser.setHtml(_translate("ActionDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.btnEditUserDictionary.setText(_translate("ActionDialog", "Редактировать", None))
        self.edtUserDictionarySearch.setPlaceholderText(_translate("ActionDialog", "Поиск по словарю...", None))
        self.btnCloseWidgets.setText(_translate("ActionDialog", "...", None))
        self.lblMorphologyMKB.setText(_translate("ActionDialog", "Морфология МКБ", None))
        self.lblMKB.setText(_translate("ActionDialog", "Диагноз", None))
        self.edtCoordDate.setWhatsThis(_translate("ActionDialog", "дата начала осмотра", None))
        self.edtCoordTime.setDisplayFormat(_translate("ActionDialog", "HH:mm", None))
        self.edtDirectionDate.setWhatsThis(_translate("ActionDialog", "дата начала осмотра", None))
        self.edtDirectionTime.setDisplayFormat(_translate("ActionDialog", "HH:mm", None))
        self.chkIsUrgent.setText(_translate("ActionDialog", "Срочно", None))
        self.lblSetPerson.setText(_translate("ActionDialog", "Назначил", None))
        self.cmbSetPerson.setItemText(0, _translate("ActionDialog", "Врач", None))
        self.lbPlannedEndDate.setText(_translate("ActionDialog", "План", None))
        self.edtPlannedEndTime.setDisplayFormat(_translate("ActionDialog", "HH:mm", None))
        self.lblBegDate.setText(_translate("ActionDialog", "Начато", None))
        self.edtBegDate.setWhatsThis(_translate("ActionDialog", "дата окончания осмотра", None))
        self.edtBegTime.setDisplayFormat(_translate("ActionDialog", "HH:mm", None))
        self.lbEndDate.setText(_translate("ActionDialog", "Выполнено", None))
        self.edtEndTime.setDisplayFormat(_translate("ActionDialog", "HH:mm", None))
        self.lblAmount.setText(_translate("ActionDialog", "Количество", None))
        self.lblUet.setText(_translate("ActionDialog", "УЕТ", None))
        self.lblOffice.setText(_translate("ActionDialog", "Кабинет", None))
        self.lblDirectionDate.setText(_translate("ActionDialog", "Назначено", None))
        self.btnSelectOrg.setText(_translate("ActionDialog", "...", None))
        self.lblNote.setText(_translate("ActionDialog", "Примечания", None))
        self.lblPerson.setText(_translate("ActionDialog", "Исполнитель", None))
        self.lblStatus.setText(_translate("ActionDialog", "Состояние", None))
        self.lblOrg.setText(_translate("ActionDialog", "Место выполнения", None))
        self.lblCoordDate.setText(_translate("ActionDialog", "Согласовано", None))
        self.lblActionSpecification.setText(_translate("ActionDialog", "Особенности выполнения действия", None))
        self.cmbOrg.setItemText(0, _translate("ActionDialog", "Организация", None))
        self.lblOrgStructure.setText(_translate("ActionDialog", "Подразделение", None))
        self.cmbPerson.setItemText(0, _translate("ActionDialog", "Врач", None))
        self.lblAssistant.setText(_translate("ActionDialog", "Ассистент", None))
        self.edtAliquoticity.setToolTip(_translate("ActionDialog", "Сколько раз в сутки.", None))
        self.lblAliquoticity.setToolTip(_translate("ActionDialog", "Сколько раз в сутки.", None))
        self.lblAliquoticity.setText(_translate("ActionDialog", "Кратность", None))
        self.btnAPNomenclatureExpense.setText(_translate("ActionDialog", "Списание ЛСиИМН", None))
        self.btnPortal_Doctor.setText(_translate("ActionDialog", "Портал врача", None))
        self.lblPeriodicity.setToolTip(_translate("ActionDialog", "0 - каждый день,\n"
"1 - через 1 день,\n"
"2 - через 2 дня,\n"
"3 - через 3 дня,\n"
"и т.д.", None))
        self.lblPeriodicity.setText(_translate("ActionDialog", "Интервал", None))
        self.edtDuration.setToolTip(_translate("ActionDialog", "Длительность курса лечения в днях.", None))
        self.lblDuration.setToolTip(_translate("ActionDialog", "Длительность курса лечения в днях.", None))
        self.lblDuration.setText(_translate("ActionDialog", "Длительность", None))
        self.edtPeriodicity.setToolTip(_translate("ActionDialog", "0 - каждый день,\n"
"1 - через 1 день,\n"
"2 - через 2 дня,\n"
"3 - через 3 дня,\n"
"и т.д.", None))
        self.btnPlanNextAction.setText(_translate("ActionDialog", "...", None))
        self.btnAPQueueManagement.setText(_translate("ActionDialog", "УО", None))
        self.btnNextAction.setText(_translate("ActionDialog", "Выполнить", None))
        self.edtQuantity.setToolTip(_translate("ActionDialog", "Длительность курса лечения в днях.", None))
        self.lblQuantity.setToolTip(_translate("ActionDialog", "Длительность курса лечения в днях.", None))
        self.lblQuantity.setText(_translate("ActionDialog", "Кол-во процедур ", None))
        self.cmbAssistant.setItemText(0, _translate("ActionDialog", "Врач", None))

from Events.ActionPropertiesTable import CActionPropertiesTableView
from Events.ActionStatus import CActionStatusComboBox
from Events.UserDictionaryList import CUserDictionaryListView
from Events.Utils import CActionWidgetVisibilityButton
from Orgs.OrgComboBox import CPolyclinicComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonWithOrgListComboBoxEx
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEditEx
from library.ICDMorphologyCodeEdit import CICDMorphologyCodeEditEx
from library.TextBrowser import CTextBrowser
from library.TimeEdit import CTimeEdit
from library.crbcombobox import CRBComboBox
