# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Samson\UP_s11\client_test\Events\ActionTypeComboBoxExPopup.ui'
#
# Created: Wed Dec 06 09:41:39 2023
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActionTypeComboBoxExPopup(object):
    def setupUi(self, ActionTypeComboBoxExPopup):
        ActionTypeComboBoxExPopup.setObjectName(_fromUtf8("ActionTypeComboBoxExPopup"))
        ActionTypeComboBoxExPopup.resize(506, 326)
        self.gridlayout = QtGui.QGridLayout(ActionTypeComboBoxExPopup)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.tabWidget = QtGui.QTabWidget(ActionTypeComboBoxExPopup)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabClientRelation = QtGui.QWidget()
        self.tabClientRelation.setObjectName(_fromUtf8("tabClientRelation"))
        self.vboxlayout = QtGui.QVBoxLayout(self.tabClientRelation)
        self.vboxlayout.setSpacing(4)
        self.vboxlayout.setMargin(4)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.tblActionTypeFind = CTreeView(self.tabClientRelation)
        self.tblActionTypeFind.setObjectName(_fromUtf8("tblActionTypeFind"))
        self.vboxlayout.addWidget(self.tblActionTypeFind)
        self.tabWidget.addTab(self.tabClientRelation, _fromUtf8(""))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.gridlayout1 = QtGui.QGridLayout(self.tabSearch)
        self.gridlayout1.setMargin(4)
        self.gridlayout1.setSpacing(4)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.cmbServiceType = CActionServiceTypeComboBox(self.tabSearch)
        self.cmbServiceType.setObjectName(_fromUtf8("cmbServiceType"))
        self.gridlayout1.addWidget(self.cmbServiceType, 3, 1, 1, 4)
        self.cmbSex = QtGui.QComboBox(self.tabSearch)
        self.cmbSex.setObjectName(_fromUtf8("cmbSex"))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.cmbSex.addItem(_fromUtf8(""))
        self.gridlayout1.addWidget(self.cmbSex, 7, 1, 1, 4)
        self.spbAgeFor = QtGui.QSpinBox(self.tabSearch)
        self.spbAgeFor.setObjectName(_fromUtf8("spbAgeFor"))
        self.gridlayout1.addWidget(self.spbAgeFor, 9, 1, 1, 1)
        self.chkPreferable = QtGui.QCheckBox(self.tabSearch)
        self.chkPreferable.setObjectName(_fromUtf8("chkPreferable"))
        self.gridlayout1.addWidget(self.chkPreferable, 4, 1, 1, 4)
        self.label = QtGui.QLabel(self.tabSearch)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridlayout1.addWidget(self.label, 9, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem, 9, 4, 1, 1)
        self.spbAgeTo = QtGui.QSpinBox(self.tabSearch)
        self.spbAgeTo.setMaximum(150)
        self.spbAgeTo.setObjectName(_fromUtf8("spbAgeTo"))
        self.gridlayout1.addWidget(self.spbAgeTo, 9, 3, 1, 1)
        self.lblOrgStructure = QtGui.QLabel(self.tabSearch)
        self.lblOrgStructure.setObjectName(_fromUtf8("lblOrgStructure"))
        self.gridlayout1.addWidget(self.lblOrgStructure, 5, 0, 1, 1)
        self.cmbOrgStructure = COrgStructureComboBox(self.tabSearch)
        self.cmbOrgStructure.setObjectName(_fromUtf8("cmbOrgStructure"))
        self.gridlayout1.addWidget(self.cmbOrgStructure, 5, 1, 1, 4)
        self.buttonBox = QtGui.QDialogButtonBox(self.tabSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridlayout1.addWidget(self.buttonBox, 12, 4, 1, 1)
        self.edtNomenclatureCode = QtGui.QLineEdit(self.tabSearch)
        self.edtNomenclatureCode.setObjectName(_fromUtf8("edtNomenclatureCode"))
        self.gridlayout1.addWidget(self.edtNomenclatureCode, 2, 1, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(20, 141, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem1, 11, 0, 1, 1)
        self.lblName = QtGui.QLabel(self.tabSearch)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridlayout1.addWidget(self.lblName, 1, 0, 1, 1)
        self.lblCode = QtGui.QLabel(self.tabSearch)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridlayout1.addWidget(self.lblCode, 0, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(self.tabSearch)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridlayout1.addWidget(self.edtName, 1, 1, 1, 4)
        self.lblNomenclatureCode = QtGui.QLabel(self.tabSearch)
        self.lblNomenclatureCode.setObjectName(_fromUtf8("lblNomenclatureCode"))
        self.gridlayout1.addWidget(self.lblNomenclatureCode, 2, 0, 1, 1)
        self.lblServiceType = QtGui.QLabel(self.tabSearch)
        self.lblServiceType.setObjectName(_fromUtf8("lblServiceType"))
        self.gridlayout1.addWidget(self.lblServiceType, 3, 0, 1, 1)
        self.lblSex = QtGui.QLabel(self.tabSearch)
        self.lblSex.setObjectName(_fromUtf8("lblSex"))
        self.gridlayout1.addWidget(self.lblSex, 7, 0, 1, 1)
        self.lblAge = QtGui.QLabel(self.tabSearch)
        self.lblAge.setObjectName(_fromUtf8("lblAge"))
        self.gridlayout1.addWidget(self.lblAge, 9, 0, 1, 1)
        self.chkPreferableOrgStructure = QtGui.QCheckBox(self.tabSearch)
        self.chkPreferableOrgStructure.setChecked(True)
        self.chkPreferableOrgStructure.setObjectName(_fromUtf8("chkPreferableOrgStructure"))
        self.gridlayout1.addWidget(self.chkPreferableOrgStructure, 6, 1, 1, 4)
        self.edtCode = QtGui.QLineEdit(self.tabSearch)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridlayout1.addWidget(self.edtCode, 0, 1, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(231, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem2, 12, 0, 1, 2)
        self.chkShowInForm = QtGui.QCheckBox(self.tabSearch)
        self.chkShowInForm.setChecked(True)
        self.chkShowInForm.setObjectName(_fromUtf8("chkShowInForm"))
        self.gridlayout1.addWidget(self.chkShowInForm, 10, 1, 1, 4)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.gridlayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(ActionTypeComboBoxExPopup)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ActionTypeComboBoxExPopup)
        ActionTypeComboBoxExPopup.setTabOrder(self.tabWidget, self.edtCode)
        ActionTypeComboBoxExPopup.setTabOrder(self.edtCode, self.edtName)
        ActionTypeComboBoxExPopup.setTabOrder(self.edtName, self.edtNomenclatureCode)
        ActionTypeComboBoxExPopup.setTabOrder(self.edtNomenclatureCode, self.cmbServiceType)
        ActionTypeComboBoxExPopup.setTabOrder(self.cmbServiceType, self.chkPreferable)
        ActionTypeComboBoxExPopup.setTabOrder(self.chkPreferable, self.cmbOrgStructure)
        ActionTypeComboBoxExPopup.setTabOrder(self.cmbOrgStructure, self.chkPreferableOrgStructure)
        ActionTypeComboBoxExPopup.setTabOrder(self.chkPreferableOrgStructure, self.cmbSex)
        ActionTypeComboBoxExPopup.setTabOrder(self.cmbSex, self.spbAgeFor)
        ActionTypeComboBoxExPopup.setTabOrder(self.spbAgeFor, self.spbAgeTo)
        ActionTypeComboBoxExPopup.setTabOrder(self.spbAgeTo, self.buttonBox)
        ActionTypeComboBoxExPopup.setTabOrder(self.buttonBox, self.tblActionTypeFind)

    def retranslateUi(self, ActionTypeComboBoxExPopup):
        ActionTypeComboBoxExPopup.setWindowTitle(_translate("ActionTypeComboBoxExPopup", "Form", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabClientRelation), _translate("ActionTypeComboBoxExPopup", "Результат поиска", None))
        self.cmbSex.setItemText(0, _translate("ActionTypeComboBoxExPopup", "не задано", None))
        self.cmbSex.setItemText(1, _translate("ActionTypeComboBoxExPopup", "Мужской", None))
        self.cmbSex.setItemText(2, _translate("ActionTypeComboBoxExPopup", "Женский", None))
        self.chkPreferable.setText(_translate("ActionTypeComboBoxExPopup", "Признак \"является предпочитаемой\" для ЛПУ", None))
        self.label.setText(_translate("ActionTypeComboBoxExPopup", "по", None))
        self.lblOrgStructure.setText(_translate("ActionTypeComboBoxExPopup", "Подразделение", None))
        self.lblName.setText(_translate("ActionTypeComboBoxExPopup", "Наименование", None))
        self.lblCode.setText(_translate("ActionTypeComboBoxExPopup", "Код", None))
        self.lblNomenclatureCode.setText(_translate("ActionTypeComboBoxExPopup", "Номенклатурный код", None))
        self.lblServiceType.setText(_translate("ActionTypeComboBoxExPopup", "Вид услуги", None))
        self.lblSex.setText(_translate("ActionTypeComboBoxExPopup", "Пол", None))
        self.lblAge.setText(_translate("ActionTypeComboBoxExPopup", "Возраст с", None))
        self.chkPreferableOrgStructure.setText(_translate("ActionTypeComboBoxExPopup", "Признак \"является предпочитаемой\" для подразделения", None))
        self.chkShowInForm.setText(_translate("ActionTypeComboBoxExPopup", "Разрешается выбор в формах ввода событий", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), _translate("ActionTypeComboBoxExPopup", "&Поиск", None))

from library.TreeView import CTreeView
from Events.ActionServiceType import CActionServiceTypeComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
