# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/work/kmivc-arch/Samson/client_test/Events/ActionsPage.ui'
#
# Created by: PyQt4 UI code generator 4.12.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ActionsPageWidget(object):
    def setupUi(self, ActionsPageWidget):
        ActionsPageWidget.setObjectName(_fromUtf8("ActionsPageWidget"))
        ActionsPageWidget.resize(1306, 725)
        self.gridLayoutAP = QtGui.QGridLayout(ActionsPageWidget)
        self.gridLayoutAP.setMargin(0)
        self.gridLayoutAP.setSpacing(0)
        self.gridLayoutAP.setObjectName(_fromUtf8("gridLayoutAP"))
        self.splitterAP = QtGui.QSplitter(ActionsPageWidget)
        self.splitterAP.setOrientation(QtCore.Qt.Horizontal)
        self.splitterAP.setChildrenCollapsible(False)
        self.splitterAP.setObjectName(_fromUtf8("splitterAP"))
        self.tblAPActions = CActionsTableView(self.splitterAP)
        self.tblAPActions.setObjectName(_fromUtf8("tblAPActions"))
        self.frameAP = QtGui.QFrame(self.splitterAP)
        self.frameAP.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameAP.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameAP.setObjectName(_fromUtf8("frameAP"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frameAP)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frmWidgets = QtGui.QFrame(self.frameAP)
        self.frmWidgets.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmWidgets.setFrameShadow(QtGui.QFrame.Raised)
        self.frmWidgets.setObjectName(_fromUtf8("frmWidgets"))
        self.gridLayout = QtGui.QGridLayout(self.frmWidgets)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblAPDirectionDate = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPDirectionDate.sizePolicy().hasHeightForWidth())
        self.lblAPDirectionDate.setSizePolicy(sizePolicy)
        self.lblAPDirectionDate.setObjectName(_fromUtf8("lblAPDirectionDate"))
        self.gridLayout.addWidget(self.lblAPDirectionDate, 0, 0, 1, 1)
        self.frmTop = QtGui.QWidget(self.frmWidgets)
        self.frmTop.setObjectName(_fromUtf8("frmTop"))
        self.horizontalLayout_38 = QtGui.QHBoxLayout(self.frmTop)
        self.horizontalLayout_38.setMargin(0)
        self.horizontalLayout_38.setSpacing(6)
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.frmAPDirectionDateTime = QtGui.QFrame(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPDirectionDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPDirectionDateTime.setSizePolicy(sizePolicy)
        self.frmAPDirectionDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPDirectionDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPDirectionDateTime.setObjectName(_fromUtf8("frmAPDirectionDateTime"))
        self.horizontalLayout_39 = QtGui.QHBoxLayout(self.frmAPDirectionDateTime)
        self.horizontalLayout_39.setMargin(0)
        self.horizontalLayout_39.setSpacing(4)
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.edtAPDirectionDate = CDateEdit(self.frmAPDirectionDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPDirectionDate.sizePolicy().hasHeightForWidth())
        self.edtAPDirectionDate.setSizePolicy(sizePolicy)
        self.edtAPDirectionDate.setCalendarPopup(True)
        self.edtAPDirectionDate.setObjectName(_fromUtf8("edtAPDirectionDate"))
        self.horizontalLayout_39.addWidget(self.edtAPDirectionDate)
        self.edtAPDirectionTime = CTimeEdit(self.frmAPDirectionDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPDirectionTime.sizePolicy().hasHeightForWidth())
        self.edtAPDirectionTime.setSizePolicy(sizePolicy)
        self.edtAPDirectionTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPDirectionTime.setObjectName(_fromUtf8("edtAPDirectionTime"))
        self.horizontalLayout_39.addWidget(self.edtAPDirectionTime)
        self.horizontalLayout_38.addWidget(self.frmAPDirectionDateTime)
        self.chkAPIsUrgent = QtGui.QCheckBox(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkAPIsUrgent.sizePolicy().hasHeightForWidth())
        self.chkAPIsUrgent.setSizePolicy(sizePolicy)
        self.chkAPIsUrgent.setObjectName(_fromUtf8("chkAPIsUrgent"))
        self.horizontalLayout_38.addWidget(self.chkAPIsUrgent)
        self.lblAPSetPerson = QtGui.QLabel(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPSetPerson.sizePolicy().hasHeightForWidth())
        self.lblAPSetPerson.setSizePolicy(sizePolicy)
        self.lblAPSetPerson.setObjectName(_fromUtf8("lblAPSetPerson"))
        self.horizontalLayout_38.addWidget(self.lblAPSetPerson)
        self.cmbAPSetPerson = CPersonWithOrgListComboBoxEx(self.frmTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPSetPerson.sizePolicy().hasHeightForWidth())
        self.cmbAPSetPerson.setSizePolicy(sizePolicy)
        self.cmbAPSetPerson.setObjectName(_fromUtf8("cmbAPSetPerson"))
        self.cmbAPSetPerson.addItem(_fromUtf8(""))
        self.horizontalLayout_38.addWidget(self.cmbAPSetPerson)
        self.horizontalLayout_38.setStretch(3, 2)
        self.gridLayout.addWidget(self.frmTop, 0, 1, 1, 1)
        self.lblAPPlannedEndDate = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPPlannedEndDate.sizePolicy().hasHeightForWidth())
        self.lblAPPlannedEndDate.setSizePolicy(sizePolicy)
        self.lblAPPlannedEndDate.setObjectName(_fromUtf8("lblAPPlannedEndDate"))
        self.gridLayout.addWidget(self.lblAPPlannedEndDate, 0, 2, 1, 1)
        self.frmAPPlannedEndDateTime = QtGui.QFrame(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPPlannedEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPPlannedEndDateTime.setSizePolicy(sizePolicy)
        self.frmAPPlannedEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPPlannedEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPPlannedEndDateTime.setObjectName(_fromUtf8("frmAPPlannedEndDateTime"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout(self.frmAPPlannedEndDateTime)
        self.horizontalLayout_37.setMargin(0)
        self.horizontalLayout_37.setSpacing(4)
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.edtAPPlannedEndDate = CDateEdit(self.frmAPPlannedEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPPlannedEndDate.sizePolicy().hasHeightForWidth())
        self.edtAPPlannedEndDate.setSizePolicy(sizePolicy)
        self.edtAPPlannedEndDate.setCalendarPopup(True)
        self.edtAPPlannedEndDate.setObjectName(_fromUtf8("edtAPPlannedEndDate"))
        self.horizontalLayout_37.addWidget(self.edtAPPlannedEndDate)
        self.edtAPPlannedEndTime = QtGui.QTimeEdit(self.frmAPPlannedEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPPlannedEndTime.sizePolicy().hasHeightForWidth())
        self.edtAPPlannedEndTime.setSizePolicy(sizePolicy)
        self.edtAPPlannedEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPPlannedEndTime.setObjectName(_fromUtf8("edtAPPlannedEndTime"))
        self.horizontalLayout_37.addWidget(self.edtAPPlannedEndTime)
        self.gridLayout.addWidget(self.frmAPPlannedEndDateTime, 0, 3, 1, 1)
        self.lblAPOrg = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPOrg.sizePolicy().hasHeightForWidth())
        self.lblAPOrg.setSizePolicy(sizePolicy)
        self.lblAPOrg.setObjectName(_fromUtf8("lblAPOrg"))
        self.gridLayout.addWidget(self.lblAPOrg, 1, 0, 1, 1)
        self.lblAPStatus = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPStatus.sizePolicy().hasHeightForWidth())
        self.lblAPStatus.setSizePolicy(sizePolicy)
        self.lblAPStatus.setObjectName(_fromUtf8("lblAPStatus"))
        self.gridLayout.addWidget(self.lblAPStatus, 2, 0, 1, 1)
        self.frmMiddle = QtGui.QWidget(self.frmWidgets)
        self.frmMiddle.setObjectName(_fromUtf8("frmMiddle"))
        self.horizontalLayout_41 = QtGui.QHBoxLayout(self.frmMiddle)
        self.horizontalLayout_41.setMargin(0)
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.cmbAPStatus = CActionStatusComboBox(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPStatus.sizePolicy().hasHeightForWidth())
        self.cmbAPStatus.setSizePolicy(sizePolicy)
        self.cmbAPStatus.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cmbAPStatus.setObjectName(_fromUtf8("cmbAPStatus"))
        self.horizontalLayout_41.addWidget(self.cmbAPStatus)
        self.frmAPBegDateTime = QtGui.QFrame(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPBegDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPBegDateTime.setSizePolicy(sizePolicy)
        self.frmAPBegDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPBegDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPBegDateTime.setObjectName(_fromUtf8("frmAPBegDateTime"))
        self.horizontalLayout_42 = QtGui.QHBoxLayout(self.frmAPBegDateTime)
        self.horizontalLayout_42.setMargin(0)
        self.horizontalLayout_42.setSpacing(4)
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.lblAPBegDate = QtGui.QLabel(self.frmAPBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPBegDate.sizePolicy().hasHeightForWidth())
        self.lblAPBegDate.setSizePolicy(sizePolicy)
        self.lblAPBegDate.setObjectName(_fromUtf8("lblAPBegDate"))
        self.horizontalLayout_42.addWidget(self.lblAPBegDate)
        self.edtAPBegDate = CDateEdit(self.frmAPBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPBegDate.sizePolicy().hasHeightForWidth())
        self.edtAPBegDate.setSizePolicy(sizePolicy)
        self.edtAPBegDate.setCalendarPopup(True)
        self.edtAPBegDate.setObjectName(_fromUtf8("edtAPBegDate"))
        self.horizontalLayout_42.addWidget(self.edtAPBegDate)
        self.edtAPBegTime = CTimeEdit(self.frmAPBegDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPBegTime.sizePolicy().hasHeightForWidth())
        self.edtAPBegTime.setSizePolicy(sizePolicy)
        self.edtAPBegTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPBegTime.setObjectName(_fromUtf8("edtAPBegTime"))
        self.horizontalLayout_42.addWidget(self.edtAPBegTime)
        self.horizontalLayout_41.addWidget(self.frmAPBegDateTime)
        self.frmAPEndDateTime = QtGui.QFrame(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmAPEndDateTime.sizePolicy().hasHeightForWidth())
        self.frmAPEndDateTime.setSizePolicy(sizePolicy)
        self.frmAPEndDateTime.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPEndDateTime.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPEndDateTime.setObjectName(_fromUtf8("frmAPEndDateTime"))
        self.horizontalLayout_43 = QtGui.QHBoxLayout(self.frmAPEndDateTime)
        self.horizontalLayout_43.setMargin(0)
        self.horizontalLayout_43.setSpacing(4)
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.lblAPEndDate = QtGui.QLabel(self.frmAPEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPEndDate.sizePolicy().hasHeightForWidth())
        self.lblAPEndDate.setSizePolicy(sizePolicy)
        self.lblAPEndDate.setObjectName(_fromUtf8("lblAPEndDate"))
        self.horizontalLayout_43.addWidget(self.lblAPEndDate)
        self.edtAPEndDate = CDateEdit(self.frmAPEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPEndDate.sizePolicy().hasHeightForWidth())
        self.edtAPEndDate.setSizePolicy(sizePolicy)
        self.edtAPEndDate.setCalendarPopup(True)
        self.edtAPEndDate.setObjectName(_fromUtf8("edtAPEndDate"))
        self.horizontalLayout_43.addWidget(self.edtAPEndDate)
        self.edtAPEndTime = CTimeEdit(self.frmAPEndDateTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPEndTime.sizePolicy().hasHeightForWidth())
        self.edtAPEndTime.setSizePolicy(sizePolicy)
        self.edtAPEndTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPEndTime.setObjectName(_fromUtf8("edtAPEndTime"))
        self.horizontalLayout_43.addWidget(self.edtAPEndTime)
        self.horizontalLayout_41.addWidget(self.frmAPEndDateTime)
        self.lblAPAmount = QtGui.QLabel(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPAmount.sizePolicy().hasHeightForWidth())
        self.lblAPAmount.setSizePolicy(sizePolicy)
        self.lblAPAmount.setObjectName(_fromUtf8("lblAPAmount"))
        self.horizontalLayout_41.addWidget(self.lblAPAmount)
        self.edtAPAmount = QtGui.QDoubleSpinBox(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPAmount.sizePolicy().hasHeightForWidth())
        self.edtAPAmount.setSizePolicy(sizePolicy)
        self.edtAPAmount.setMaximum(999.99)
        self.edtAPAmount.setObjectName(_fromUtf8("edtAPAmount"))
        self.horizontalLayout_41.addWidget(self.edtAPAmount)
        self.lblAPUet = QtGui.QLabel(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPUet.sizePolicy().hasHeightForWidth())
        self.lblAPUet.setSizePolicy(sizePolicy)
        self.lblAPUet.setObjectName(_fromUtf8("lblAPUet"))
        self.horizontalLayout_41.addWidget(self.lblAPUet)
        self.edtAPUet = QtGui.QDoubleSpinBox(self.frmMiddle)
        self.edtAPUet.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPUet.sizePolicy().hasHeightForWidth())
        self.edtAPUet.setSizePolicy(sizePolicy)
        self.edtAPUet.setReadOnly(True)
        self.edtAPUet.setMaximum(1000.0)
        self.edtAPUet.setSingleStep(0.5)
        self.edtAPUet.setObjectName(_fromUtf8("edtAPUet"))
        self.horizontalLayout_41.addWidget(self.edtAPUet)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem)
        self.lblAPOffice = QtGui.QLabel(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPOffice.sizePolicy().hasHeightForWidth())
        self.lblAPOffice.setSizePolicy(sizePolicy)
        self.lblAPOffice.setObjectName(_fromUtf8("lblAPOffice"))
        self.horizontalLayout_41.addWidget(self.lblAPOffice)
        self.edtAPOffice = QtGui.QLineEdit(self.frmMiddle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPOffice.sizePolicy().hasHeightForWidth())
        self.edtAPOffice.setSizePolicy(sizePolicy)
        self.edtAPOffice.setMaxLength(16)
        self.edtAPOffice.setObjectName(_fromUtf8("edtAPOffice"))
        self.horizontalLayout_41.addWidget(self.edtAPOffice)
        self.gridLayout.addWidget(self.frmMiddle, 2, 1, 1, 3)
        self.lblAPPerson = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPPerson.sizePolicy().hasHeightForWidth())
        self.lblAPPerson.setSizePolicy(sizePolicy)
        self.lblAPPerson.setObjectName(_fromUtf8("lblAPPerson"))
        self.gridLayout.addWidget(self.lblAPPerson, 3, 0, 1, 1)
        self.lblAPOrgStructure = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPOrgStructure.sizePolicy().hasHeightForWidth())
        self.lblAPOrgStructure.setSizePolicy(sizePolicy)
        self.lblAPOrgStructure.setObjectName(_fromUtf8("lblAPOrgStructure"))
        self.gridLayout.addWidget(self.lblAPOrgStructure, 4, 0, 1, 1)
        self.lblAPNote = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPNote.sizePolicy().hasHeightForWidth())
        self.lblAPNote.setSizePolicy(sizePolicy)
        self.lblAPNote.setObjectName(_fromUtf8("lblAPNote"))
        self.gridLayout.addWidget(self.lblAPNote, 5, 0, 1, 1)
        self.lblAPCoordDate = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPCoordDate.sizePolicy().hasHeightForWidth())
        self.lblAPCoordDate.setSizePolicy(sizePolicy)
        self.lblAPCoordDate.setObjectName(_fromUtf8("lblAPCoordDate"))
        self.gridLayout.addWidget(self.lblAPCoordDate, 6, 0, 1, 1)
        self.horizontalLayout_53 = QtGui.QHBoxLayout()
        self.horizontalLayout_53.setSpacing(2)
        self.horizontalLayout_53.setObjectName(_fromUtf8("horizontalLayout_53"))
        self.lblActionSpecification = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblActionSpecification.sizePolicy().hasHeightForWidth())
        self.lblActionSpecification.setSizePolicy(sizePolicy)
        self.lblActionSpecification.setObjectName(_fromUtf8("lblActionSpecification"))
        self.horizontalLayout_53.addWidget(self.lblActionSpecification)
        self.cmbActionSpecification = CRBComboBox(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbActionSpecification.sizePolicy().hasHeightForWidth())
        self.cmbActionSpecification.setSizePolicy(sizePolicy)
        self.cmbActionSpecification.setObjectName(_fromUtf8("cmbActionSpecification"))
        self.horizontalLayout_53.addWidget(self.cmbActionSpecification)
        self.gridLayout.addLayout(self.horizontalLayout_53, 7, 0, 1, 4)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setSpacing(2)
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.cmbAPOrg = CPolyclinicComboBox(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPOrg.sizePolicy().hasHeightForWidth())
        self.cmbAPOrg.setSizePolicy(sizePolicy)
        self.cmbAPOrg.setObjectName(_fromUtf8("cmbAPOrg"))
        self.cmbAPOrg.addItem(_fromUtf8(""))
        self.horizontalLayout_40.addWidget(self.cmbAPOrg)
        self.btnAPSelectOrg = QtGui.QToolButton(self.frmWidgets)
        self.btnAPSelectOrg.setObjectName(_fromUtf8("btnAPSelectOrg"))
        self.horizontalLayout_40.addWidget(self.btnAPSelectOrg)
        self.lblAPMorphologyMKB = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPMorphologyMKB.sizePolicy().hasHeightForWidth())
        self.lblAPMorphologyMKB.setSizePolicy(sizePolicy)
        self.lblAPMorphologyMKB.setObjectName(_fromUtf8("lblAPMorphologyMKB"))
        self.horizontalLayout_40.addWidget(self.lblAPMorphologyMKB)
        self.cmbAPMorphologyMKB = CICDMorphologyCodeEditEx(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPMorphologyMKB.sizePolicy().hasHeightForWidth())
        self.cmbAPMorphologyMKB.setSizePolicy(sizePolicy)
        self.cmbAPMorphologyMKB.setMinimumSize(QtCore.QSize(0, 0))
        self.cmbAPMorphologyMKB.setObjectName(_fromUtf8("cmbAPMorphologyMKB"))
        self.horizontalLayout_40.addWidget(self.cmbAPMorphologyMKB)
        self.lblAPMKB = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPMKB.sizePolicy().hasHeightForWidth())
        self.lblAPMKB.setSizePolicy(sizePolicy)
        self.lblAPMKB.setObjectName(_fromUtf8("lblAPMKB"))
        self.horizontalLayout_40.addWidget(self.lblAPMKB)
        self.cmbAPMKB = CICDCodeEditEx(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPMKB.sizePolicy().hasHeightForWidth())
        self.cmbAPMKB.setSizePolicy(sizePolicy)
        self.cmbAPMKB.setObjectName(_fromUtf8("cmbAPMKB"))
        self.horizontalLayout_40.addWidget(self.cmbAPMKB)
        self.lblAPMKBExSubclass = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPMKBExSubclass.sizePolicy().hasHeightForWidth())
        self.lblAPMKBExSubclass.setSizePolicy(sizePolicy)
        self.lblAPMKBExSubclass.setObjectName(_fromUtf8("lblAPMKBExSubclass"))
        self.horizontalLayout_40.addWidget(self.lblAPMKBExSubclass)
        self.cmbAPMKBExSubclass = CMKBExSubclassComboBox(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPMKBExSubclass.sizePolicy().hasHeightForWidth())
        self.cmbAPMKBExSubclass.setSizePolicy(sizePolicy)
        self.cmbAPMKBExSubclass.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cmbAPMKBExSubclass.setObjectName(_fromUtf8("cmbAPMKBExSubclass"))
        self.horizontalLayout_40.addWidget(self.cmbAPMKBExSubclass)
        self.lblAPMKBText = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPMKBText.sizePolicy().hasHeightForWidth())
        self.lblAPMKBText.setSizePolicy(sizePolicy)
        self.lblAPMKBText.setMinimumSize(QtCore.QSize(0, 0))
        self.lblAPMKBText.setText(_fromUtf8(""))
        self.lblAPMKBText.setWordWrap(True)
        self.lblAPMKBText.setObjectName(_fromUtf8("lblAPMKBText"))
        self.horizontalLayout_40.addWidget(self.lblAPMKBText)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem1)
        self.horizontalLayout_40.setStretch(0, 3)
        self.horizontalLayout_40.setStretch(8, 5)
        self.gridLayout.addLayout(self.horizontalLayout_40, 1, 1, 1, 3)
        self.cmbAPPerson = CPersonWithOrgListComboBoxEx(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPPerson.sizePolicy().hasHeightForWidth())
        self.cmbAPPerson.setSizePolicy(sizePolicy)
        self.cmbAPPerson.setObjectName(_fromUtf8("cmbAPPerson"))
        self.cmbAPPerson.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbAPPerson, 3, 1, 1, 3)
        self.horizontalLayout_44 = QtGui.QHBoxLayout()
        self.horizontalLayout_44.setSpacing(2)
        self.horizontalLayout_44.setObjectName(_fromUtf8("horizontalLayout_44"))
        self.cmbAPOrgStructure = COrgStructureComboBox(self.frmWidgets)
        self.cmbAPOrgStructure.setObjectName(_fromUtf8("cmbAPOrgStructure"))
        self.horizontalLayout_44.addWidget(self.cmbAPOrgStructure)
        self.lblAPAssistant = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPAssistant.sizePolicy().hasHeightForWidth())
        self.lblAPAssistant.setSizePolicy(sizePolicy)
        self.lblAPAssistant.setObjectName(_fromUtf8("lblAPAssistant"))
        self.horizontalLayout_44.addWidget(self.lblAPAssistant)
        self.cmbAPAssistant = CPersonWithOrgListComboBoxEx(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAPAssistant.sizePolicy().hasHeightForWidth())
        self.cmbAPAssistant.setSizePolicy(sizePolicy)
        self.cmbAPAssistant.setMinimumSize(QtCore.QSize(0, 0))
        self.cmbAPAssistant.setObjectName(_fromUtf8("cmbAPAssistant"))
        self.cmbAPAssistant.addItem(_fromUtf8(""))
        self.horizontalLayout_44.addWidget(self.cmbAPAssistant)
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setSpacing(0)
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        self.lblAPQuantity = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPQuantity.sizePolicy().hasHeightForWidth())
        self.lblAPQuantity.setSizePolicy(sizePolicy)
        self.lblAPQuantity.setObjectName(_fromUtf8("lblAPQuantity"))
        self.horizontalLayout_45.addWidget(self.lblAPQuantity)
        self.edtAPQuantity = QtGui.QDoubleSpinBox(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPQuantity.sizePolicy().hasHeightForWidth())
        self.edtAPQuantity.setSizePolicy(sizePolicy)
        self.edtAPQuantity.setMaximum(999.99)
        self.edtAPQuantity.setObjectName(_fromUtf8("edtAPQuantity"))
        self.horizontalLayout_45.addWidget(self.edtAPQuantity)
        self.horizontalLayout_44.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setSpacing(0)
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        self.lblAPDuration = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPDuration.sizePolicy().hasHeightForWidth())
        self.lblAPDuration.setSizePolicy(sizePolicy)
        self.lblAPDuration.setObjectName(_fromUtf8("lblAPDuration"))
        self.horizontalLayout_46.addWidget(self.lblAPDuration)
        self.edtAPDuration = QtGui.QSpinBox(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPDuration.sizePolicy().hasHeightForWidth())
        self.edtAPDuration.setSizePolicy(sizePolicy)
        self.edtAPDuration.setObjectName(_fromUtf8("edtAPDuration"))
        self.horizontalLayout_46.addWidget(self.edtAPDuration)
        self.horizontalLayout_44.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setSpacing(0)
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        self.lblAPPeriodicity = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPPeriodicity.sizePolicy().hasHeightForWidth())
        self.lblAPPeriodicity.setSizePolicy(sizePolicy)
        self.lblAPPeriodicity.setObjectName(_fromUtf8("lblAPPeriodicity"))
        self.horizontalLayout_47.addWidget(self.lblAPPeriodicity)
        self.edtAPPeriodicity = QtGui.QSpinBox(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPPeriodicity.sizePolicy().hasHeightForWidth())
        self.edtAPPeriodicity.setSizePolicy(sizePolicy)
        self.edtAPPeriodicity.setObjectName(_fromUtf8("edtAPPeriodicity"))
        self.horizontalLayout_47.addWidget(self.edtAPPeriodicity)
        self.horizontalLayout_44.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtGui.QHBoxLayout()
        self.horizontalLayout_48.setSpacing(0)
        self.horizontalLayout_48.setObjectName(_fromUtf8("horizontalLayout_48"))
        self.lblAPAliquoticity = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPAliquoticity.sizePolicy().hasHeightForWidth())
        self.lblAPAliquoticity.setSizePolicy(sizePolicy)
        self.lblAPAliquoticity.setObjectName(_fromUtf8("lblAPAliquoticity"))
        self.horizontalLayout_48.addWidget(self.lblAPAliquoticity)
        self.edtAPAliquoticity = QtGui.QSpinBox(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtAPAliquoticity.sizePolicy().hasHeightForWidth())
        self.edtAPAliquoticity.setSizePolicy(sizePolicy)
        self.edtAPAliquoticity.setObjectName(_fromUtf8("edtAPAliquoticity"))
        self.horizontalLayout_48.addWidget(self.edtAPAliquoticity)
        self.horizontalLayout_44.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_44.setStretch(0, 20)
        self.horizontalLayout_44.setStretch(2, 40)
        self.gridLayout.addLayout(self.horizontalLayout_44, 4, 1, 1, 3)
        self.horizontalLayout_49 = QtGui.QHBoxLayout()
        self.horizontalLayout_49.setSpacing(2)
        self.horizontalLayout_49.setObjectName(_fromUtf8("horizontalLayout_49"))
        self.edtAPNote = QtGui.QLineEdit(self.frmWidgets)
        self.edtAPNote.setObjectName(_fromUtf8("edtAPNote"))
        self.horizontalLayout_49.addWidget(self.edtAPNote)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem2)
        self.btnNextAction = QtGui.QPushButton(self.frmWidgets)
        self.btnNextAction.setEnabled(False)
        self.btnNextAction.setObjectName(_fromUtf8("btnNextAction"))
        self.horizontalLayout_49.addWidget(self.btnNextAction)
        self.btnAPQueueManagement = QtGui.QPushButton(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAPQueueManagement.sizePolicy().hasHeightForWidth())
        self.btnAPQueueManagement.setSizePolicy(sizePolicy)
        self.btnAPQueueManagement.setObjectName(_fromUtf8("btnAPQueueManagement"))
        self.horizontalLayout_49.addWidget(self.btnAPQueueManagement)
        self.btnPlanNextAction = QtGui.QToolButton(self.frmWidgets)
        self.btnPlanNextAction.setEnabled(False)
        self.btnPlanNextAction.setObjectName(_fromUtf8("btnPlanNextAction"))
        self.horizontalLayout_49.addWidget(self.btnPlanNextAction)
        self.btnAPNomenclatureExpense = QtGui.QPushButton(self.frmWidgets)
        self.btnAPNomenclatureExpense.setObjectName(_fromUtf8("btnAPNomenclatureExpense"))
        self.horizontalLayout_49.addWidget(self.btnAPNomenclatureExpense)
        self.horizontalLayout_49.setStretch(0, 10)
        self.gridLayout.addLayout(self.horizontalLayout_49, 5, 1, 1, 3)
        self.horizontalLayout_50 = QtGui.QHBoxLayout()
        self.horizontalLayout_50.setSpacing(2)
        self.horizontalLayout_50.setObjectName(_fromUtf8("horizontalLayout_50"))
        self.horizontalLayout_51 = QtGui.QHBoxLayout()
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.edtAPCoordDate = CDateEdit(self.frmWidgets)
        self.edtAPCoordDate.setEnabled(False)
        self.edtAPCoordDate.setCalendarPopup(True)
        self.edtAPCoordDate.setObjectName(_fromUtf8("edtAPCoordDate"))
        self.horizontalLayout_51.addWidget(self.edtAPCoordDate)
        self.edtAPCoordTime = QtGui.QTimeEdit(self.frmWidgets)
        self.edtAPCoordTime.setEnabled(False)
        self.edtAPCoordTime.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAPCoordTime.setObjectName(_fromUtf8("edtAPCoordTime"))
        self.horizontalLayout_51.addWidget(self.edtAPCoordTime)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_51)
        self.lblAPCoordText = QtGui.QLabel(self.frmWidgets)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAPCoordText.sizePolicy().hasHeightForWidth())
        self.lblAPCoordText.setSizePolicy(sizePolicy)
        self.lblAPCoordText.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblAPCoordText.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblAPCoordText.setText(_fromUtf8(""))
        self.lblAPCoordText.setObjectName(_fromUtf8("lblAPCoordText"))
        self.horizontalLayout_50.addWidget(self.lblAPCoordText)
        self.horizontalLayout_52 = QtGui.QHBoxLayout()
        self.horizontalLayout_52.setObjectName(_fromUtf8("horizontalLayout_52"))
        self.lblCSG = QtGui.QLabel(self.frmWidgets)
        self.lblCSG.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCSG.sizePolicy().hasHeightForWidth())
        self.lblCSG.setSizePolicy(sizePolicy)
        self.lblCSG.setMinimumSize(QtCore.QSize(35, 0))
        self.lblCSG.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCSG.setObjectName(_fromUtf8("lblCSG"))
        self.horizontalLayout_52.addWidget(self.lblCSG)
        self.cmbCSG = CActionCSGComboBox(self.frmWidgets)
        self.cmbCSG.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCSG.sizePolicy().hasHeightForWidth())
        self.cmbCSG.setSizePolicy(sizePolicy)
        self.cmbCSG.setObjectName(_fromUtf8("cmbCSG"))
        self.horizontalLayout_52.addWidget(self.cmbCSG)
        self.horizontalLayout_50.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_50.setStretch(1, 60)
        self.horizontalLayout_50.setStretch(2, 20)
        self.gridLayout.addLayout(self.horizontalLayout_50, 6, 1, 1, 3)
        self.verticalLayout.addWidget(self.frmWidgets)
        self.btnCloseWidgets = CActionWidgetVisibilityButton(self.frameAP)
        self.btnCloseWidgets.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.btnCloseWidgets.setArrowType(QtCore.Qt.NoArrow)
        self.btnCloseWidgets.setObjectName(_fromUtf8("btnCloseWidgets"))
        self.verticalLayout.addWidget(self.btnCloseWidgets)
        self.splitter = QtGui.QSplitter(self.frameAP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tblAPProps = CActionPropertiesTableView(self.splitter)
        self.tblAPProps.setEnabled(False)
        self.tblAPProps.setAutoScroll(True)
        self.tblAPProps.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblAPProps.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblAPProps.setObjectName(_fromUtf8("tblAPProps"))
        self.wgtUserDictionary = QtGui.QWidget(self.splitter)
        self.wgtUserDictionary.setObjectName(_fromUtf8("wgtUserDictionary"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wgtUserDictionary)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnEditUserDictionary = QtGui.QPushButton(self.wgtUserDictionary)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditUserDictionary.sizePolicy().hasHeightForWidth())
        self.btnEditUserDictionary.setSizePolicy(sizePolicy)
        self.btnEditUserDictionary.setObjectName(_fromUtf8("btnEditUserDictionary"))
        self.gridLayout_3.addWidget(self.btnEditUserDictionary, 0, 1, 1, 1)
        self.lvUserDictionary = CUserDictionaryListView(self.wgtUserDictionary)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvUserDictionary.sizePolicy().hasHeightForWidth())
        self.lvUserDictionary.setSizePolicy(sizePolicy)
        self.lvUserDictionary.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lvUserDictionary.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.lvUserDictionary.setAlternatingRowColors(True)
        self.lvUserDictionary.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.lvUserDictionary.setWordWrap(True)
        self.lvUserDictionary.setObjectName(_fromUtf8("lvUserDictionary"))
        self.gridLayout_3.addWidget(self.lvUserDictionary, 1, 0, 1, 2)
        self.edtUserDictionarySearch = QtGui.QLineEdit(self.wgtUserDictionary)
        self.edtUserDictionarySearch.setObjectName(_fromUtf8("edtUserDictionarySearch"))
        self.gridLayout_3.addWidget(self.edtUserDictionarySearch, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.splitter)
        self.frmAPButtonsBar = QtGui.QFrame(self.frameAP)
        self.frmAPButtonsBar.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmAPButtonsBar.setFrameShadow(QtGui.QFrame.Plain)
        self.frmAPButtonsBar.setLineWidth(0)
        self.frmAPButtonsBar.setObjectName(_fromUtf8("frmAPButtonsBar"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frmAPButtonsBar)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnAPHospitalOrderSelect = QtGui.QPushButton(self.frmAPButtonsBar)
        self.btnAPHospitalOrderSelect.setObjectName(_fromUtf8("btnAPHospitalOrderSelect"))
        self.horizontalLayout_4.addWidget(self.btnAPHospitalOrderSelect)
        self.btnAPPrint = CPrintButton(self.frmAPButtonsBar)
        self.btnAPPrint.setObjectName(_fromUtf8("btnAPPrint"))
        self.horizontalLayout_4.addWidget(self.btnAPPrint)
        self.btnAPLoadTemplate = CActionTemplateSelectButton(self.frmAPButtonsBar)
        self.btnAPLoadTemplate.setObjectName(_fromUtf8("btnAPLoadTemplate"))
        self.horizontalLayout_4.addWidget(self.btnAPLoadTemplate)
        self.btnAPSaveAsTemplate = QtGui.QPushButton(self.frmAPButtonsBar)
        self.btnAPSaveAsTemplate.setObjectName(_fromUtf8("btnAPSaveAsTemplate"))
        self.horizontalLayout_4.addWidget(self.btnAPSaveAsTemplate)
        self.btnAPLoadPrevAction = QtGui.QPushButton(self.frmAPButtonsBar)
        self.btnAPLoadPrevAction.setEnabled(False)
        self.btnAPLoadPrevAction.setObjectName(_fromUtf8("btnAPLoadPrevAction"))
        self.horizontalLayout_4.addWidget(self.btnAPLoadPrevAction)
        self.btnAPAttachedFiles = CAttachButton(self.frmAPButtonsBar)
        self.btnAPAttachedFiles.setFlat(False)
        self.btnAPAttachedFiles.setObjectName(_fromUtf8("btnAPAttachedFiles"))
        self.horizontalLayout_4.addWidget(self.btnAPAttachedFiles)
        spacerItem3 = QtGui.QSpacerItem(145, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.frmAPButtonsBar)
        self.gridLayoutAP.addWidget(self.splitterAP, 0, 0, 1, 1)
        self.lblAPDirectionDate.setBuddy(self.edtAPDirectionDate)
        self.lblAPSetPerson.setBuddy(self.cmbAPSetPerson)
        self.lblAPPlannedEndDate.setBuddy(self.edtAPPlannedEndDate)
        self.lblAPStatus.setBuddy(self.cmbAPStatus)
        self.lblAPBegDate.setBuddy(self.edtAPBegDate)
        self.lblAPEndDate.setBuddy(self.edtAPEndDate)
        self.lblAPAmount.setBuddy(self.edtAPAmount)
        self.lblAPUet.setBuddy(self.edtAPUet)
        self.lblAPOffice.setBuddy(self.edtAPOffice)
        self.lblAPPerson.setBuddy(self.cmbAPPerson)
        self.lblAPNote.setBuddy(self.edtAPNote)
        self.lblAPCoordDate.setBuddy(self.edtAPCoordDate)
        self.lblActionSpecification.setBuddy(self.cmbActionSpecification)
        self.lblAPMKBExSubclass.setBuddy(self.cmbAPMKBExSubclass)
        self.lblAPAssistant.setBuddy(self.cmbAPAssistant)
        self.lblCSG.setBuddy(self.cmbCSG)

        self.retranslateUi(ActionsPageWidget)
        QtCore.QMetaObject.connectSlotsByName(ActionsPageWidget)
        ActionsPageWidget.setTabOrder(self.tblAPActions, self.tblAPProps)
        ActionsPageWidget.setTabOrder(self.tblAPProps, self.btnAPHospitalOrderSelect)
        ActionsPageWidget.setTabOrder(self.btnAPHospitalOrderSelect, self.btnAPPrint)
        ActionsPageWidget.setTabOrder(self.btnAPPrint, self.btnAPLoadTemplate)
        ActionsPageWidget.setTabOrder(self.btnAPLoadTemplate, self.btnAPSaveAsTemplate)
        ActionsPageWidget.setTabOrder(self.btnAPSaveAsTemplate, self.btnAPLoadPrevAction)
        ActionsPageWidget.setTabOrder(self.btnAPLoadPrevAction, self.btnAPAttachedFiles)

    def retranslateUi(self, ActionsPageWidget):
        ActionsPageWidget.setWindowTitle(_translate("ActionsPageWidget", "Form", None))
        self.lblAPDirectionDate.setText(_translate("ActionsPageWidget", "Назначено", None))
        self.edtAPDirectionDate.setWhatsThis(_translate("ActionsPageWidget", "дата начала осмотра", None))
        self.edtAPDirectionTime.setDisplayFormat(_translate("ActionsPageWidget", "HH:mm", None))
        self.chkAPIsUrgent.setText(_translate("ActionsPageWidget", "Срочно", None))
        self.lblAPSetPerson.setText(_translate("ActionsPageWidget", "Назначил", None))
        self.cmbAPSetPerson.setItemText(0, _translate("ActionsPageWidget", "Врач", None))
        self.lblAPPlannedEndDate.setText(_translate("ActionsPageWidget", "План", None))
        self.edtAPPlannedEndTime.setDisplayFormat(_translate("ActionsPageWidget", "HH:mm", None))
        self.lblAPOrg.setText(_translate("ActionsPageWidget", "Место выполнения", None))
        self.lblAPStatus.setText(_translate("ActionsPageWidget", "Состояние", None))
        self.lblAPBegDate.setText(_translate("ActionsPageWidget", "Начато", None))
        self.edtAPBegDate.setWhatsThis(_translate("ActionsPageWidget", "дата окончания осмотра", None))
        self.edtAPBegTime.setDisplayFormat(_translate("ActionsPageWidget", "HH:mm", None))
        self.lblAPEndDate.setText(_translate("ActionsPageWidget", "Выполнено", None))
        self.edtAPEndTime.setDisplayFormat(_translate("ActionsPageWidget", "HH:mm", None))
        self.lblAPAmount.setText(_translate("ActionsPageWidget", "Количество", None))
        self.lblAPUet.setText(_translate("ActionsPageWidget", "УЕТ", None))
        self.lblAPOffice.setText(_translate("ActionsPageWidget", "Кабинет", None))
        self.lblAPPerson.setText(_translate("ActionsPageWidget", "Исполнитель", None))
        self.lblAPOrgStructure.setText(_translate("ActionsPageWidget", "Подразделение", None))
        self.lblAPNote.setText(_translate("ActionsPageWidget", "Примечания", None))
        self.lblAPCoordDate.setText(_translate("ActionsPageWidget", "Согласовано", None))
        self.lblActionSpecification.setText(_translate("ActionsPageWidget", "Особенность выполнения действия", None))
        self.cmbAPOrg.setItemText(0, _translate("ActionsPageWidget", "Организация", None))
        self.btnAPSelectOrg.setText(_translate("ActionsPageWidget", "...", None))
        self.lblAPMorphologyMKB.setText(_translate("ActionsPageWidget", "Морфология МКБ", None))
        self.lblAPMKB.setText(_translate("ActionsPageWidget", "Диагноз", None))
        self.lblAPMKBExSubclass.setText(_translate("ActionsPageWidget", "РСК", None))
        self.cmbAPPerson.setItemText(0, _translate("ActionsPageWidget", "Врач", None))
        self.lblAPAssistant.setText(_translate("ActionsPageWidget", "Ассистент", None))
        self.cmbAPAssistant.setItemText(0, _translate("ActionsPageWidget", "Врач", None))
        self.lblAPQuantity.setText(_translate("ActionsPageWidget", "Кол-во процедур", None))
        self.lblAPDuration.setToolTip(_translate("ActionsPageWidget", "Длительность курса лечения в днях.", None))
        self.lblAPDuration.setText(_translate("ActionsPageWidget", "Длительность", None))
        self.edtAPDuration.setToolTip(_translate("ActionsPageWidget", "Длительность курса лечения в днях.", None))
        self.lblAPPeriodicity.setToolTip(_translate("ActionsPageWidget", "0 - каждый день,\n"
"1 - через 1 день,\n"
"2 - через 2 дня,\n"
"3 - через 3 дня,\n"
"и т.д.", None))
        self.lblAPPeriodicity.setText(_translate("ActionsPageWidget", "Интервал", None))
        self.edtAPPeriodicity.setToolTip(_translate("ActionsPageWidget", "0 - каждый день,\n"
"1 - через 1 день,\n"
"2 - через 2 дня,\n"
"3 - через 3 дня,\n"
"и т.д.", None))
        self.lblAPAliquoticity.setToolTip(_translate("ActionsPageWidget", "Сколько раз в сутки.", None))
        self.lblAPAliquoticity.setText(_translate("ActionsPageWidget", "Кратность", None))
        self.edtAPAliquoticity.setToolTip(_translate("ActionsPageWidget", "Сколько раз в сутки.", None))
        self.btnNextAction.setText(_translate("ActionsPageWidget", "Действие", None))
        self.btnAPQueueManagement.setText(_translate("ActionsPageWidget", "УО", None))
        self.btnPlanNextAction.setText(_translate("ActionsPageWidget", "...", None))
        self.btnAPNomenclatureExpense.setText(_translate("ActionsPageWidget", "Списание ЛСиИМН", None))
        self.edtAPCoordDate.setWhatsThis(_translate("ActionsPageWidget", "дата начала осмотра", None))
        self.edtAPCoordTime.setDisplayFormat(_translate("ActionsPageWidget", "HH:mm", None))
        self.lblCSG.setText(_translate("ActionsPageWidget", "КСГ", None))
        self.btnCloseWidgets.setText(_translate("ActionsPageWidget", "...", None))
        self.btnEditUserDictionary.setText(_translate("ActionsPageWidget", "Редактировать", None))
        self.edtUserDictionarySearch.setPlaceholderText(_translate("ActionsPageWidget", "Поиск по словарю...", None))
        self.btnAPHospitalOrderSelect.setText(_translate("ActionsPageWidget", "Госпитализация", None))
        self.btnAPPrint.setText(_translate("ActionsPageWidget", "Печать", None))
        self.btnAPLoadTemplate.setText(_translate("ActionsPageWidget", "Загрузить шаблон", None))
        self.btnAPSaveAsTemplate.setText(_translate("ActionsPageWidget", "Сохранить шаблон", None))
        self.btnAPLoadPrevAction.setText(_translate("ActionsPageWidget", "Копировать из предыдущего", None))
        self.btnAPAttachedFiles.setText(_translate("ActionsPageWidget", "Прикреплённые файлы", None))

from Events.ActionPropertiesTable import CActionPropertiesTableView
from Events.ActionStatus import CActionStatusComboBox
from Events.ActionTemplateChoose import CActionTemplateSelectButton
from Events.ActionsTable import CActionsTableView
from Events.UserDictionaryList import CUserDictionaryListView
from Events.Utils import CActionCSGComboBox, CActionWidgetVisibilityButton
from Orgs.OrgComboBox import CPolyclinicComboBox
from Orgs.OrgStructComboBoxes import COrgStructureComboBox
from Orgs.PersonComboBoxEx import CPersonWithOrgListComboBoxEx
from library.Attach.AttachButton import CAttachButton
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEditEx
from library.ICDMorphologyCodeEdit import CICDMorphologyCodeEditEx
from library.MKBExSubclassComboBox import CMKBExSubclassComboBox
from library.PrintTemplates import CPrintButton
from library.TimeEdit import CTimeEdit
from library.crbcombobox import CRBComboBox
