# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Samson\UP_s11\client\Events\EventNotesPageEx.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EventNotesPageExWidget(object):
    def setupUi(self, EventNotesPageExWidget):
        EventNotesPageExWidget.setObjectName(_fromUtf8("EventNotesPageExWidget"))
        EventNotesPageExWidget.resize(655, 580)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EventNotesPageExWidget.sizePolicy().hasHeightForWidth())
        EventNotesPageExWidget.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtGui.QGridLayout(EventNotesPageExWidget)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblEventModifyDateTime = QtGui.QLabel(EventNotesPageExWidget)
        self.lblEventModifyDateTime.setObjectName(_fromUtf8("lblEventModifyDateTime"))
        self.gridLayout_2.addWidget(self.lblEventModifyDateTime, 10, 0, 1, 1)
        self.edtEventSrcDate = CDateEdit(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEventSrcDate.sizePolicy().hasHeightForWidth())
        self.edtEventSrcDate.setSizePolicy(sizePolicy)
        self.edtEventSrcDate.setCalendarPopup(True)
        self.edtEventSrcDate.setObjectName(_fromUtf8("edtEventSrcDate"))
        self.gridLayout_2.addWidget(self.edtEventSrcDate, 5, 1, 1, 1)
        self.edtEventExternalIdValue = QtGui.QLineEdit(EventNotesPageExWidget)
        self.edtEventExternalIdValue.setEnabled(False)
        self.edtEventExternalIdValue.setObjectName(_fromUtf8("edtEventExternalIdValue"))
        self.gridLayout_2.addWidget(self.edtEventExternalIdValue, 2, 1, 1, 6)
        self.lblPatientModel = QtGui.QLabel(EventNotesPageExWidget)
        self.lblPatientModel.setObjectName(_fromUtf8("lblPatientModel"))
        self.gridLayout_2.addWidget(self.lblPatientModel, 12, 0, 1, 1)
        self.btnAttachedFiles = CAttachButton(EventNotesPageExWidget)
        self.btnAttachedFiles.setFlat(False)
        self.btnAttachedFiles.setObjectName(_fromUtf8("btnAttachedFiles"))
        self.gridLayout_2.addWidget(self.btnAttachedFiles, 21, 1, 1, 2)
        self.lblN = QtGui.QLabel(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblN.sizePolicy().hasHeightForWidth())
        self.lblN.setSizePolicy(sizePolicy)
        self.lblN.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblN.setObjectName(_fromUtf8("lblN"))
        self.gridLayout_2.addWidget(self.lblN, 5, 2, 1, 1)
        self.lblEventCreateDateTimeValue = QtGui.QLabel(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventCreateDateTimeValue.sizePolicy().hasHeightForWidth())
        self.lblEventCreateDateTimeValue.setSizePolicy(sizePolicy)
        self.lblEventCreateDateTimeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventCreateDateTimeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventCreateDateTimeValue.setText(_fromUtf8(""))
        self.lblEventCreateDateTimeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventCreateDateTimeValue.setObjectName(_fromUtf8("lblEventCreateDateTimeValue"))
        self.gridLayout_2.addWidget(self.lblEventCreateDateTimeValue, 8, 1, 1, 1)
        self.lblEventCreatePersonValue = QtGui.QLabel(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventCreatePersonValue.sizePolicy().hasHeightForWidth())
        self.lblEventCreatePersonValue.setSizePolicy(sizePolicy)
        self.lblEventCreatePersonValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventCreatePersonValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventCreatePersonValue.setText(_fromUtf8(""))
        self.lblEventCreatePersonValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventCreatePersonValue.setObjectName(_fromUtf8("lblEventCreatePersonValue"))
        self.gridLayout_2.addWidget(self.lblEventCreatePersonValue, 9, 1, 1, 6)
        self.btnSelectRelegateOrg = QtGui.QToolButton(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectRelegateOrg.sizePolicy().hasHeightForWidth())
        self.btnSelectRelegateOrg.setSizePolicy(sizePolicy)
        self.btnSelectRelegateOrg.setObjectName(_fromUtf8("btnSelectRelegateOrg"))
        self.gridLayout_2.addWidget(self.btnSelectRelegateOrg, 4, 6, 1, 1)
        self.lblEventId = QtGui.QLabel(EventNotesPageExWidget)
        self.lblEventId.setObjectName(_fromUtf8("lblEventId"))
        self.gridLayout_2.addWidget(self.lblEventId, 1, 0, 1, 1)
        self.lblPrevEvent = QtGui.QLabel(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPrevEvent.sizePolicy().hasHeightForWidth())
        self.lblPrevEvent.setSizePolicy(sizePolicy)
        self.lblPrevEvent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPrevEvent.setObjectName(_fromUtf8("lblPrevEvent"))
        self.gridLayout_2.addWidget(self.lblPrevEvent, 1, 2, 1, 3)
        self.lblEventExternalId = QtGui.QLabel(EventNotesPageExWidget)
        self.lblEventExternalId.setObjectName(_fromUtf8("lblEventExternalId"))
        self.gridLayout_2.addWidget(self.lblEventExternalId, 2, 0, 1, 1)
        self.lblEventCuratorIdValue = QtGui.QLabel(EventNotesPageExWidget)
        self.lblEventCuratorIdValue.setObjectName(_fromUtf8("lblEventCuratorIdValue"))
        self.gridLayout_2.addWidget(self.lblEventCuratorIdValue, 7, 0, 1, 1)
        self.edtPrevEventInfo = QtGui.QLineEdit(EventNotesPageExWidget)
        self.edtPrevEventInfo.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtPrevEventInfo.sizePolicy().hasHeightForWidth())
        self.edtPrevEventInfo.setSizePolicy(sizePolicy)
        self.edtPrevEventInfo.setObjectName(_fromUtf8("edtPrevEventInfo"))
        self.gridLayout_2.addWidget(self.edtPrevEventInfo, 1, 5, 1, 2)
        self.lblRelegateOrg = QtGui.QLabel(EventNotesPageExWidget)
        self.lblRelegateOrg.setObjectName(_fromUtf8("lblRelegateOrg"))
        self.gridLayout_2.addWidget(self.lblRelegateOrg, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(175, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 8, 2, 1, 2)
        self.lblEventModifyPerson = QtGui.QLabel(EventNotesPageExWidget)
        self.lblEventModifyPerson.setObjectName(_fromUtf8("lblEventModifyPerson"))
        self.gridLayout_2.addWidget(self.lblEventModifyPerson, 11, 0, 1, 1)
        self.lblEventModifyPersonValue = QtGui.QLabel(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventModifyPersonValue.sizePolicy().hasHeightForWidth())
        self.lblEventModifyPersonValue.setSizePolicy(sizePolicy)
        self.lblEventModifyPersonValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventModifyPersonValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventModifyPersonValue.setText(_fromUtf8(""))
        self.lblEventModifyPersonValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventModifyPersonValue.setObjectName(_fromUtf8("lblEventModifyPersonValue"))
        self.gridLayout_2.addWidget(self.lblEventModifyPersonValue, 11, 1, 1, 6)
        self.edtEventNote = QtGui.QTextEdit(EventNotesPageExWidget)
        self.edtEventNote.setObjectName(_fromUtf8("edtEventNote"))
        self.gridLayout_2.addWidget(self.edtEventNote, 19, 1, 2, 6)
        self.cmbClientRelationConsents = CClientRelationComboBoxPatron(EventNotesPageExWidget)
        self.cmbClientRelationConsents.setObjectName(_fromUtf8("cmbClientRelationConsents"))
        self.gridLayout_2.addWidget(self.cmbClientRelationConsents, 3, 1, 1, 6)
        self.cmbCureMethod = CRBComboBox(EventNotesPageExWidget)
        self.cmbCureMethod.setObjectName(_fromUtf8("cmbCureMethod"))
        self.gridLayout_2.addWidget(self.cmbCureMethod, 14, 1, 1, 6)
        self.cmbEventCurator = CPersonComboBoxEx(EventNotesPageExWidget)
        self.cmbEventCurator.setEnabled(False)
        self.cmbEventCurator.setObjectName(_fromUtf8("cmbEventCurator"))
        self.gridLayout_2.addWidget(self.cmbEventCurator, 7, 1, 1, 6)
        self.cmbRelegatePerson = CPersonComboBoxEx(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbRelegatePerson.sizePolicy().hasHeightForWidth())
        self.cmbRelegatePerson.setSizePolicy(sizePolicy)
        self.cmbRelegatePerson.setObjectName(_fromUtf8("cmbRelegatePerson"))
        self.gridLayout_2.addWidget(self.cmbRelegatePerson, 5, 5, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(175, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 10, 2, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 152, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 20, 0, 2, 1)
        self.cmbEventAssistant = CPersonComboBoxEx(EventNotesPageExWidget)
        self.cmbEventAssistant.setEnabled(False)
        self.cmbEventAssistant.setObjectName(_fromUtf8("cmbEventAssistant"))
        self.gridLayout_2.addWidget(self.cmbEventAssistant, 6, 1, 1, 6)
        self.lblEventIdValue = QtGui.QLabel(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventIdValue.sizePolicy().hasHeightForWidth())
        self.lblEventIdValue.setSizePolicy(sizePolicy)
        self.lblEventIdValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventIdValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventIdValue.setText(_fromUtf8(""))
        self.lblEventIdValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventIdValue.setObjectName(_fromUtf8("lblEventIdValue"))
        self.gridLayout_2.addWidget(self.lblEventIdValue, 1, 1, 1, 1)
        self.lblRelegate = QtGui.QLabel(EventNotesPageExWidget)
        self.lblRelegate.setObjectName(_fromUtf8("lblRelegate"))
        self.gridLayout_2.addWidget(self.lblRelegate, 5, 0, 1, 1)
        self.cmbRelegateOrg = CPolyclinicComboBox(EventNotesPageExWidget)
        self.cmbRelegateOrg.setEnabled(True)
        self.cmbRelegateOrg.setObjectName(_fromUtf8("cmbRelegateOrg"))
        self.gridLayout_2.addWidget(self.cmbRelegateOrg, 4, 1, 1, 5)
        self.lblEventAssistantIdValue = QtGui.QLabel(EventNotesPageExWidget)
        self.lblEventAssistantIdValue.setObjectName(_fromUtf8("lblEventAssistantIdValue"))
        self.gridLayout_2.addWidget(self.lblEventAssistantIdValue, 6, 0, 1, 1)
        self.lblEventCreateDateTime = QtGui.QLabel(EventNotesPageExWidget)
        self.lblEventCreateDateTime.setObjectName(_fromUtf8("lblEventCreateDateTime"))
        self.gridLayout_2.addWidget(self.lblEventCreateDateTime, 8, 0, 1, 1)
        self.lblIsClosed = QtGui.QLabel(EventNotesPageExWidget)
        self.lblIsClosed.setObjectName(_fromUtf8("lblIsClosed"))
        self.gridLayout_2.addWidget(self.lblIsClosed, 15, 0, 1, 1)
        self.lblExpertPerson = QtGui.QLabel(EventNotesPageExWidget)
        self.lblExpertPerson.setObjectName(_fromUtf8("lblExpertPerson"))
        self.gridLayout_2.addWidget(self.lblExpertPerson, 17, 0, 1, 1)
        self.lblEventNote = QtGui.QLabel(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventNote.sizePolicy().hasHeightForWidth())
        self.lblEventNote.setSizePolicy(sizePolicy)
        self.lblEventNote.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEventNote.setObjectName(_fromUtf8("lblEventNote"))
        self.gridLayout_2.addWidget(self.lblEventNote, 19, 0, 1, 1)
        self.lblExpertiseDate = QtGui.QLabel(EventNotesPageExWidget)
        self.lblExpertiseDate.setObjectName(_fromUtf8("lblExpertiseDate"))
        self.gridLayout_2.addWidget(self.lblExpertiseDate, 16, 0, 1, 1)
        self.lblEventModifyDateTimeValue = QtGui.QLabel(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEventModifyDateTimeValue.sizePolicy().hasHeightForWidth())
        self.lblEventModifyDateTimeValue.setSizePolicy(sizePolicy)
        self.lblEventModifyDateTimeValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblEventModifyDateTimeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblEventModifyDateTimeValue.setText(_fromUtf8(""))
        self.lblEventModifyDateTimeValue.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lblEventModifyDateTimeValue.setObjectName(_fromUtf8("lblEventModifyDateTimeValue"))
        self.gridLayout_2.addWidget(self.lblEventModifyDateTimeValue, 10, 1, 1, 1)
        self.lblEventCreatePerson = QtGui.QLabel(EventNotesPageExWidget)
        self.lblEventCreatePerson.setObjectName(_fromUtf8("lblEventCreatePerson"))
        self.gridLayout_2.addWidget(self.lblEventCreatePerson, 9, 0, 1, 1)
        self.lblRelegatePerson = QtGui.QLabel(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRelegatePerson.sizePolicy().hasHeightForWidth())
        self.lblRelegatePerson.setSizePolicy(sizePolicy)
        self.lblRelegatePerson.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRelegatePerson.setObjectName(_fromUtf8("lblRelegatePerson"))
        self.gridLayout_2.addWidget(self.lblRelegatePerson, 5, 4, 1, 1)
        self.lblCureType = QtGui.QLabel(EventNotesPageExWidget)
        self.lblCureType.setObjectName(_fromUtf8("lblCureType"))
        self.gridLayout_2.addWidget(self.lblCureType, 13, 0, 1, 1)
        self.lblClientRelationConsents = QtGui.QLabel(EventNotesPageExWidget)
        self.lblClientRelationConsents.setObjectName(_fromUtf8("lblClientRelationConsents"))
        self.gridLayout_2.addWidget(self.lblClientRelationConsents, 3, 0, 1, 1)
        self.edtExpertiseDate = CDateEdit(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtExpertiseDate.sizePolicy().hasHeightForWidth())
        self.edtExpertiseDate.setSizePolicy(sizePolicy)
        self.edtExpertiseDate.setCalendarPopup(True)
        self.edtExpertiseDate.setObjectName(_fromUtf8("edtExpertiseDate"))
        self.gridLayout_2.addWidget(self.edtExpertiseDate, 16, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(175, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 16, 2, 1, 2)
        self.cmbCureType = CRBComboBox(EventNotesPageExWidget)
        self.cmbCureType.setObjectName(_fromUtf8("cmbCureType"))
        self.gridLayout_2.addWidget(self.cmbCureType, 13, 1, 1, 6)
        self.cmbExpertPerson = CPersonComboBoxEx(EventNotesPageExWidget)
        self.cmbExpertPerson.setObjectName(_fromUtf8("cmbExpertPerson"))
        self.gridLayout_2.addWidget(self.cmbExpertPerson, 17, 1, 1, 6)
        self.chkIsClosed = CROCheckBox(EventNotesPageExWidget)
        self.chkIsClosed.setText(_fromUtf8(""))
        self.chkIsClosed.setObjectName(_fromUtf8("chkIsClosed"))
        self.gridLayout_2.addWidget(self.chkIsClosed, 15, 1, 1, 4)
        self.edtEventSrcNumber = QtGui.QLineEdit(EventNotesPageExWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEventSrcNumber.sizePolicy().hasHeightForWidth())
        self.edtEventSrcNumber.setSizePolicy(sizePolicy)
        self.edtEventSrcNumber.setObjectName(_fromUtf8("edtEventSrcNumber"))
        self.gridLayout_2.addWidget(self.edtEventSrcNumber, 5, 3, 1, 1)
        self.lblCureMethod = QtGui.QLabel(EventNotesPageExWidget)
        self.lblCureMethod.setObjectName(_fromUtf8("lblCureMethod"))
        self.gridLayout_2.addWidget(self.lblCureMethod, 14, 0, 1, 1)
        self.cmbContract = CContractComboBox(EventNotesPageExWidget)
        self.cmbContract.setObjectName(_fromUtf8("cmbContract"))
        self.gridLayout_2.addWidget(self.cmbContract, 0, 1, 1, 6)
        self.lblContract = QtGui.QLabel(EventNotesPageExWidget)
        self.lblContract.setObjectName(_fromUtf8("lblContract"))
        self.gridLayout_2.addWidget(self.lblContract, 0, 0, 1, 1)
        self.cmbPatientModel = CPatientModelComboBox(EventNotesPageExWidget)
        self.cmbPatientModel.setObjectName(_fromUtf8("cmbPatientModel"))
        self.gridLayout_2.addWidget(self.cmbPatientModel, 12, 1, 1, 6)
        self.lblExpose = QtGui.QLabel(EventNotesPageExWidget)
        self.lblExpose.setObjectName(_fromUtf8("lblExpose"))
        self.gridLayout_2.addWidget(self.lblExpose, 18, 0, 1, 1)
        self.chkExpose = CROCheckBox(EventNotesPageExWidget)
        self.chkExpose.setText(_fromUtf8(""))
        self.chkExpose.setObjectName(_fromUtf8("chkExpose"))
        self.gridLayout_2.addWidget(self.chkExpose, 18, 1, 1, 1)
        self.lblPatientModel.setBuddy(self.cmbPatientModel)
        self.lblEventExternalId.setBuddy(self.edtEventExternalIdValue)
        self.lblEventCuratorIdValue.setBuddy(self.cmbEventCurator)
        self.lblRelegateOrg.setBuddy(self.cmbRelegateOrg)
        self.lblEventAssistantIdValue.setBuddy(self.cmbEventAssistant)
        self.lblEventNote.setBuddy(self.edtEventNote)
        self.lblCureType.setBuddy(self.cmbCureType)
        self.lblCureMethod.setBuddy(self.cmbCureMethod)

        self.retranslateUi(EventNotesPageExWidget)
        QtCore.QMetaObject.connectSlotsByName(EventNotesPageExWidget)
        EventNotesPageExWidget.setTabOrder(self.cmbContract, self.edtPrevEventInfo)
        EventNotesPageExWidget.setTabOrder(self.edtPrevEventInfo, self.edtEventExternalIdValue)
        EventNotesPageExWidget.setTabOrder(self.edtEventExternalIdValue, self.cmbClientRelationConsents)
        EventNotesPageExWidget.setTabOrder(self.cmbClientRelationConsents, self.cmbRelegateOrg)
        EventNotesPageExWidget.setTabOrder(self.cmbRelegateOrg, self.btnSelectRelegateOrg)
        EventNotesPageExWidget.setTabOrder(self.btnSelectRelegateOrg, self.edtEventSrcDate)
        EventNotesPageExWidget.setTabOrder(self.edtEventSrcDate, self.edtEventSrcNumber)
        EventNotesPageExWidget.setTabOrder(self.edtEventSrcNumber, self.cmbRelegatePerson)
        EventNotesPageExWidget.setTabOrder(self.cmbRelegatePerson, self.cmbEventAssistant)
        EventNotesPageExWidget.setTabOrder(self.cmbEventAssistant, self.cmbEventCurator)
        EventNotesPageExWidget.setTabOrder(self.cmbEventCurator, self.cmbPatientModel)
        EventNotesPageExWidget.setTabOrder(self.cmbPatientModel, self.cmbCureType)
        EventNotesPageExWidget.setTabOrder(self.cmbCureType, self.cmbCureMethod)
        EventNotesPageExWidget.setTabOrder(self.cmbCureMethod, self.chkIsClosed)
        EventNotesPageExWidget.setTabOrder(self.chkIsClosed, self.edtExpertiseDate)
        EventNotesPageExWidget.setTabOrder(self.edtExpertiseDate, self.cmbExpertPerson)
        EventNotesPageExWidget.setTabOrder(self.cmbExpertPerson, self.edtEventNote)
        EventNotesPageExWidget.setTabOrder(self.edtEventNote, self.btnAttachedFiles)

    def retranslateUi(self, EventNotesPageExWidget):
        EventNotesPageExWidget.setWindowTitle(_translate("EventNotesPageExWidget", "Form", None))
        self.lblEventModifyDateTime.setText(_translate("EventNotesPageExWidget", "Дата и время последнего изменения", None))
        self.edtEventSrcDate.setDisplayFormat(_translate("EventNotesPageExWidget", "dd.MM.yyyy", None))
        self.lblPatientModel.setText(_translate("EventNotesPageExWidget", "Модель пациента", None))
        self.btnAttachedFiles.setText(_translate("EventNotesPageExWidget", "Прикреплённые файлы", None))
        self.lblN.setText(_translate("EventNotesPageExWidget", "№", None))
        self.btnSelectRelegateOrg.setText(_translate("EventNotesPageExWidget", "...", None))
        self.lblEventId.setText(_translate("EventNotesPageExWidget", "Код карточки", None))
        self.lblPrevEvent.setText(_translate("EventNotesPageExWidget", "предыдущее событие", None))
        self.lblEventExternalId.setToolTip(_translate("EventNotesPageExWidget", "Внешний идентификатор записи", None))
        self.lblEventExternalId.setText(_translate("EventNotesPageExWidget", "Номер документа", None))
        self.lblEventCuratorIdValue.setText(_translate("EventNotesPageExWidget", "Куратор", None))
        self.lblRelegateOrg.setText(_translate("EventNotesPageExWidget", "Направитель", None))
        self.lblEventModifyPerson.setText(_translate("EventNotesPageExWidget", "Автор последнего изменения", None))
        self.lblRelegate.setText(_translate("EventNotesPageExWidget", "Направление", None))
        self.lblEventAssistantIdValue.setText(_translate("EventNotesPageExWidget", "Ассистент", None))
        self.lblEventCreateDateTime.setText(_translate("EventNotesPageExWidget", "Дата и время создания", None))
        self.lblIsClosed.setText(_translate("EventNotesPageExWidget", "Событие закрыто", None))
        self.lblExpertPerson.setText(_translate("EventNotesPageExWidget", "Эксперт", None))
        self.lblEventNote.setText(_translate("EventNotesPageExWidget", "Примечания", None))
        self.lblExpertiseDate.setText(_translate("EventNotesPageExWidget", "Дата экспертизы случая", None))
        self.lblEventCreatePerson.setText(_translate("EventNotesPageExWidget", "Автор", None))
        self.lblRelegatePerson.setText(_translate("EventNotesPageExWidget", "Направил", None))
        self.lblCureType.setText(_translate("EventNotesPageExWidget", "Вид лечения", None))
        self.lblClientRelationConsents.setText(_translate("EventNotesPageExWidget", "Лицо по уходу", None))
        self.edtExpertiseDate.setDisplayFormat(_translate("EventNotesPageExWidget", "dd.MM.yyyy", None))
        self.lblCureMethod.setText(_translate("EventNotesPageExWidget", "Метод лечения", None))
        self.lblContract.setText(_translate("EventNotesPageExWidget", "Договор", None))
        self.lblExpose.setText(_translate("EventNotesPageExWidget", "Выставлять в счёт", None))

from Events.widgets.PatientModelComboBox import CPatientModelComboBox
from Orgs.OrgComboBox import CContractComboBox, CPolyclinicComboBox
from Orgs.PersonComboBoxEx import CPersonComboBoxEx
from Registry.Utils import CClientRelationComboBoxPatron
from library.Attach.AttachButton import CAttachButton
from library.DateEdit import CDateEdit
from library.ROCheckBox import CROCheckBox
from library.crbcombobox import CRBComboBox
