# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\Samson\UP_s11\client\Events\TempInvalidEditDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TempInvalidEditDialog(object):
    def setupUi(self, TempInvalidEditDialog):
        TempInvalidEditDialog.setObjectName(_fromUtf8("TempInvalidEditDialog"))
        TempInvalidEditDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        TempInvalidEditDialog.resize(908, 885)
        self.gridLayout_7 = QtGui.QGridLayout(TempInvalidEditDialog)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.buttonBox = QtGui.QDialogButtonBox(TempInvalidEditDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_7.addWidget(self.buttonBox, 1, 0, 1, 2)
        self.scrollArea = QtGui.QScrollArea(TempInvalidEditDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 881, 882))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_8 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.grpMainInfo = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpMainInfo.sizePolicy().hasHeightForWidth())
        self.grpMainInfo.setSizePolicy(sizePolicy)
        self.grpMainInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.grpMainInfo.setFlat(False)
        self.grpMainInfo.setObjectName(_fromUtf8("grpMainInfo"))
        self.gridLayout_6 = QtGui.QGridLayout(self.grpMainInfo)
        self.gridLayout_6.setContentsMargins(2, 0, 2, 1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cmbExtraReason = CRBComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbExtraReason.sizePolicy().hasHeightForWidth())
        self.cmbExtraReason.setSizePolicy(sizePolicy)
        self.cmbExtraReason.setObjectName(_fromUtf8("cmbExtraReason"))
        self.gridLayout_6.addWidget(self.cmbExtraReason, 3, 1, 1, 3)
        self.edtDiagnosis = CICDCodeEditEx(self.grpMainInfo)
        self.edtDiagnosis.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDiagnosis.sizePolicy().hasHeightForWidth())
        self.edtDiagnosis.setSizePolicy(sizePolicy)
        self.edtDiagnosis.setObjectName(_fromUtf8("edtDiagnosis"))
        self.gridLayout_6.addWidget(self.edtDiagnosis, 7, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtBegDatePermit = CDateEdit(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDatePermit.sizePolicy().hasHeightForWidth())
        self.edtBegDatePermit.setSizePolicy(sizePolicy)
        self.edtBegDatePermit.setCalendarPopup(True)
        self.edtBegDatePermit.setObjectName(_fromUtf8("edtBegDatePermit"))
        self.horizontalLayout_3.addWidget(self.edtBegDatePermit)
        self.edtEndDatePermit = CDateEdit(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDatePermit.sizePolicy().hasHeightForWidth())
        self.edtEndDatePermit.setSizePolicy(sizePolicy)
        self.edtEndDatePermit.setCalendarPopup(True)
        self.edtEndDatePermit.setObjectName(_fromUtf8("edtEndDatePermit"))
        self.horizontalLayout_3.addWidget(self.edtEndDatePermit)
        self.edtNumberPermit = QtGui.QLineEdit(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtNumberPermit.sizePolicy().hasHeightForWidth())
        self.edtNumberPermit.setSizePolicy(sizePolicy)
        self.edtNumberPermit.setObjectName(_fromUtf8("edtNumberPermit"))
        self.horizontalLayout_3.addWidget(self.edtNumberPermit)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 9, 1, 1, 3)
        self.lblExtraReason = QtGui.QLabel(self.grpMainInfo)
        self.lblExtraReason.setObjectName(_fromUtf8("lblExtraReason"))
        self.gridLayout_6.addWidget(self.lblExtraReason, 3, 0, 1, 1)
        self.lblDoctype = QtGui.QLabel(self.grpMainInfo)
        self.lblDoctype.setObjectName(_fromUtf8("lblDoctype"))
        self.gridLayout_6.addWidget(self.lblDoctype, 0, 0, 1, 1)
        self.lblReceiver = QtGui.QLabel(self.grpMainInfo)
        self.lblReceiver.setObjectName(_fromUtf8("lblReceiver"))
        self.gridLayout_6.addWidget(self.lblReceiver, 4, 0, 1, 1)
        self.btnClientRelations = QtGui.QToolButton(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClientRelations.sizePolicy().hasHeightForWidth())
        self.btnClientRelations.setSizePolicy(sizePolicy)
        self.btnClientRelations.setObjectName(_fromUtf8("btnClientRelations"))
        self.gridLayout_6.addWidget(self.btnClientRelations, 4, 3, 1, 1)
        self.cmbReceiver = CClientRelationSimpleComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReceiver.sizePolicy().hasHeightForWidth())
        self.cmbReceiver.setSizePolicy(sizePolicy)
        self.cmbReceiver.setObjectName(_fromUtf8("cmbReceiver"))
        self.gridLayout_6.addWidget(self.cmbReceiver, 4, 1, 1, 2)
        self.lblReason = QtGui.QLabel(self.grpMainInfo)
        self.lblReason.setObjectName(_fromUtf8("lblReason"))
        self.gridLayout_6.addWidget(self.lblReason, 1, 0, 1, 1)
        self.cmbDoctype = CRBComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDoctype.sizePolicy().hasHeightForWidth())
        self.cmbDoctype.setSizePolicy(sizePolicy)
        self.cmbDoctype.setObjectName(_fromUtf8("cmbDoctype"))
        self.gridLayout_6.addWidget(self.cmbDoctype, 0, 1, 1, 3)
        self.cmbReason = CRBComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReason.sizePolicy().hasHeightForWidth())
        self.cmbReason.setSizePolicy(sizePolicy)
        self.cmbReason.setObjectName(_fromUtf8("cmbReason"))
        self.gridLayout_6.addWidget(self.cmbReason, 1, 1, 1, 3)
        self.lblInfContact = QtGui.QLabel(self.grpMainInfo)
        self.lblInfContact.setObjectName(_fromUtf8("lblInfContact"))
        self.gridLayout_6.addWidget(self.lblInfContact, 13, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblOtherSex = QtGui.QLabel(self.grpMainInfo)
        self.lblOtherSex.setObjectName(_fromUtf8("lblOtherSex"))
        self.horizontalLayout.addWidget(self.lblOtherSex)
        self.cmbOtherSex = CROComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbOtherSex.sizePolicy().hasHeightForWidth())
        self.cmbOtherSex.setSizePolicy(sizePolicy)
        self.cmbOtherSex.setMinimumSize(QtCore.QSize(40, 0))
        self.cmbOtherSex.setMaximumSize(QtCore.QSize(40, 16777215))
        self.cmbOtherSex.setObjectName(_fromUtf8("cmbOtherSex"))
        self.cmbOtherSex.addItem(_fromUtf8(""))
        self.cmbOtherSex.setItemText(0, _fromUtf8(""))
        self.cmbOtherSex.addItem(_fromUtf8(""))
        self.cmbOtherSex.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cmbOtherSex)
        self.lblOtherAge = QtGui.QLabel(self.grpMainInfo)
        self.lblOtherAge.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOtherAge.setObjectName(_fromUtf8("lblOtherAge"))
        self.horizontalLayout.addWidget(self.lblOtherAge)
        self.edtOtherAge = QtGui.QSpinBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOtherAge.sizePolicy().hasHeightForWidth())
        self.edtOtherAge.setSizePolicy(sizePolicy)
        self.edtOtherAge.setObjectName(_fromUtf8("edtOtherAge"))
        self.horizontalLayout.addWidget(self.edtOtherAge)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_6.addLayout(self.horizontalLayout, 6, 1, 1, 3)
        self.lblDiagnosis = QtGui.QLabel(self.grpMainInfo)
        self.lblDiagnosis.setEnabled(True)
        self.lblDiagnosis.setObjectName(_fromUtf8("lblDiagnosis"))
        self.gridLayout_6.addWidget(self.lblDiagnosis, 7, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.edtBreakDate = CDateEdit(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBreakDate.sizePolicy().hasHeightForWidth())
        self.edtBreakDate.setSizePolicy(sizePolicy)
        self.edtBreakDate.setCalendarPopup(True)
        self.edtBreakDate.setObjectName(_fromUtf8("edtBreakDate"))
        self.horizontalLayout_7.addWidget(self.edtBreakDate)
        self.cmbBreak = CRBComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbBreak.sizePolicy().hasHeightForWidth())
        self.cmbBreak.setSizePolicy(sizePolicy)
        self.cmbBreak.setObjectName(_fromUtf8("cmbBreak"))
        self.horizontalLayout_7.addWidget(self.cmbBreak)
        self.gridLayout_6.addLayout(self.horizontalLayout_7, 15, 1, 1, 3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.edtCaseBegDate = CDateEdit(self.grpMainInfo)
        self.edtCaseBegDate.setEnabled(False)
        self.edtCaseBegDate.setObjectName(_fromUtf8("edtCaseBegDate"))
        self.horizontalLayout_6.addWidget(self.edtCaseBegDate)
        self.lblCaseLength = QtGui.QLabel(self.grpMainInfo)
        self.lblCaseLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCaseLength.setObjectName(_fromUtf8("lblCaseLength"))
        self.horizontalLayout_6.addWidget(self.lblCaseLength)
        self.lblCaseLengthValue = QtGui.QLabel(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCaseLengthValue.sizePolicy().hasHeightForWidth())
        self.lblCaseLengthValue.setSizePolicy(sizePolicy)
        self.lblCaseLengthValue.setMinimumSize(QtCore.QSize(32, 0))
        self.lblCaseLengthValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblCaseLengthValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblCaseLengthValue.setText(_fromUtf8(""))
        self.lblCaseLengthValue.setObjectName(_fromUtf8("lblCaseLengthValue"))
        self.horizontalLayout_6.addWidget(self.lblCaseLengthValue)
        self.lblLengthValueTool = QtGui.QLabel(self.grpMainInfo)
        self.lblLengthValueTool.setToolTip(_fromUtf8(""))
        self.lblLengthValueTool.setObjectName(_fromUtf8("lblLengthValueTool"))
        self.horizontalLayout_6.addWidget(self.lblLengthValueTool)
        self.lblLengthValue = QtGui.QLabel(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLengthValue.sizePolicy().hasHeightForWidth())
        self.lblLengthValue.setSizePolicy(sizePolicy)
        self.lblLengthValue.setMinimumSize(QtCore.QSize(32, 0))
        self.lblLengthValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblLengthValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblLengthValue.setText(_fromUtf8(""))
        self.lblLengthValue.setObjectName(_fromUtf8("lblLengthValue"))
        self.horizontalLayout_6.addWidget(self.lblLengthValue)
        self.lblExternalLength = QtGui.QLabel(self.grpMainInfo)
        self.lblExternalLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblExternalLength.setObjectName(_fromUtf8("lblExternalLength"))
        self.horizontalLayout_6.addWidget(self.lblExternalLength)
        self.lblExternalLengthValue = QtGui.QLabel(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExternalLengthValue.sizePolicy().hasHeightForWidth())
        self.lblExternalLengthValue.setSizePolicy(sizePolicy)
        self.lblExternalLengthValue.setMinimumSize(QtCore.QSize(32, 0))
        self.lblExternalLengthValue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblExternalLengthValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblExternalLengthValue.setText(_fromUtf8(""))
        self.lblExternalLengthValue.setObjectName(_fromUtf8("lblExternalLengthValue"))
        self.horizontalLayout_6.addWidget(self.lblExternalLengthValue)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.gridLayout_6.addLayout(self.horizontalLayout_6, 8, 1, 1, 3)
        self.cmbAccountPregnancyTo12Weeks = CROComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAccountPregnancyTo12Weeks.sizePolicy().hasHeightForWidth())
        self.cmbAccountPregnancyTo12Weeks.setSizePolicy(sizePolicy)
        self.cmbAccountPregnancyTo12Weeks.setObjectName(_fromUtf8("cmbAccountPregnancyTo12Weeks"))
        self.cmbAccountPregnancyTo12Weeks.addItem(_fromUtf8(""))
        self.cmbAccountPregnancyTo12Weeks.addItem(_fromUtf8(""))
        self.cmbAccountPregnancyTo12Weeks.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbAccountPregnancyTo12Weeks, 14, 1, 1, 3)
        self.lblPresenceStationary = QtGui.QLabel(self.grpMainInfo)
        self.lblPresenceStationary.setObjectName(_fromUtf8("lblPresenceStationary"))
        self.gridLayout_6.addWidget(self.lblPresenceStationary, 16, 0, 1, 1)
        self.lblDisability = QtGui.QLabel(self.grpMainInfo)
        self.lblDisability.setObjectName(_fromUtf8("lblDisability"))
        self.gridLayout_6.addWidget(self.lblDisability, 17, 0, 1, 1)
        self.cmbResult = CRBComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbResult.sizePolicy().hasHeightForWidth())
        self.cmbResult.setSizePolicy(sizePolicy)
        self.cmbResult.setObjectName(_fromUtf8("cmbResult"))
        self.gridLayout_6.addWidget(self.cmbResult, 21, 1, 1, 3)
        self.cmbDisability = CRBComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDisability.sizePolicy().hasHeightForWidth())
        self.cmbDisability.setSizePolicy(sizePolicy)
        self.cmbDisability.setObjectName(_fromUtf8("cmbDisability"))
        self.gridLayout_6.addWidget(self.cmbDisability, 17, 1, 1, 3)
        self.btnSelectHeadOrganisation = QtGui.QToolButton(self.grpMainInfo)
        self.btnSelectHeadOrganisation.setObjectName(_fromUtf8("btnSelectHeadOrganisation"))
        self.gridLayout_6.addWidget(self.btnSelectHeadOrganisation, 10, 3, 1, 1)
        self.lblOrganisationOGRN = QtGui.QLabel(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOrganisationOGRN.sizePolicy().hasHeightForWidth())
        self.lblOrganisationOGRN.setSizePolicy(sizePolicy)
        self.lblOrganisationOGRN.setObjectName(_fromUtf8("lblOrganisationOGRN"))
        self.gridLayout_6.addWidget(self.lblOrganisationOGRN, 12, 1, 1, 3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.edtResultDate = CDateEdit(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtResultDate.sizePolicy().hasHeightForWidth())
        self.edtResultDate.setSizePolicy(sizePolicy)
        self.edtResultDate.setCalendarPopup(True)
        self.edtResultDate.setObjectName(_fromUtf8("edtResultDate"))
        self.horizontalLayout_5.addWidget(self.edtResultDate)
        self.lblResultOtherwiseDate = QtGui.QLabel(self.grpMainInfo)
        self.lblResultOtherwiseDate.setObjectName(_fromUtf8("lblResultOtherwiseDate"))
        self.horizontalLayout_5.addWidget(self.lblResultOtherwiseDate)
        self.edtResultOtherwiseDate = CDateEdit(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtResultOtherwiseDate.sizePolicy().hasHeightForWidth())
        self.edtResultOtherwiseDate.setSizePolicy(sizePolicy)
        self.edtResultOtherwiseDate.setCalendarPopup(True)
        self.edtResultOtherwiseDate.setObjectName(_fromUtf8("edtResultOtherwiseDate"))
        self.horizontalLayout_5.addWidget(self.edtResultOtherwiseDate)
        self.label = QtGui.QLabel(self.grpMainInfo)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.chkInsuranceOfficeMark = QtGui.QCheckBox(self.grpMainInfo)
        self.chkInsuranceOfficeMark.setObjectName(_fromUtf8("chkInsuranceOfficeMark"))
        self.horizontalLayout_5.addWidget(self.chkInsuranceOfficeMark)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 22, 1, 1, 3)
        self.edtOGRN = QtGui.QLineEdit(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtOGRN.sizePolicy().hasHeightForWidth())
        self.edtOGRN.setSizePolicy(sizePolicy)
        self.edtOGRN.setObjectName(_fromUtf8("edtOGRN"))
        self.gridLayout_6.addWidget(self.edtOGRN, 10, 1, 1, 2)
        self.lblOGRN = QtGui.QLabel(self.grpMainInfo)
        self.lblOGRN.setObjectName(_fromUtf8("lblOGRN"))
        self.gridLayout_6.addWidget(self.lblOGRN, 10, 0, 1, 1)
        self.lblResult = QtGui.QLabel(self.grpMainInfo)
        self.lblResult.setObjectName(_fromUtf8("lblResult"))
        self.gridLayout_6.addWidget(self.lblResult, 21, 0, 1, 1)
        self.lblAccountPregnancyTo12Weeks = QtGui.QLabel(self.grpMainInfo)
        self.lblAccountPregnancyTo12Weeks.setObjectName(_fromUtf8("lblAccountPregnancyTo12Weeks"))
        self.gridLayout_6.addWidget(self.lblAccountPregnancyTo12Weeks, 14, 0, 1, 1)
        self.cmbDiseaseCharacter = CRBComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDiseaseCharacter.sizePolicy().hasHeightForWidth())
        self.cmbDiseaseCharacter.setSizePolicy(sizePolicy)
        self.cmbDiseaseCharacter.setObjectName(_fromUtf8("cmbDiseaseCharacter"))
        self.gridLayout_6.addWidget(self.cmbDiseaseCharacter, 7, 2, 1, 2)
        self.lblPermit = QtGui.QLabel(self.grpMainInfo)
        self.lblPermit.setObjectName(_fromUtf8("lblPermit"))
        self.gridLayout_6.addWidget(self.lblPermit, 9, 0, 1, 1)
        self.lblOrganisation = QtGui.QLabel(self.grpMainInfo)
        self.lblOrganisation.setObjectName(_fromUtf8("lblOrganisation"))
        self.gridLayout_6.addWidget(self.lblOrganisation, 12, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.edtBegDateStationary = CDateEdit(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtBegDateStationary.sizePolicy().hasHeightForWidth())
        self.edtBegDateStationary.setSizePolicy(sizePolicy)
        self.edtBegDateStationary.setCalendarPopup(True)
        self.edtBegDateStationary.setObjectName(_fromUtf8("edtBegDateStationary"))
        self.horizontalLayout_4.addWidget(self.edtBegDateStationary)
        self.edtEndDateStationary = CDateEdit(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtEndDateStationary.sizePolicy().hasHeightForWidth())
        self.edtEndDateStationary.setSizePolicy(sizePolicy)
        self.edtEndDateStationary.setCalendarPopup(True)
        self.edtEndDateStationary.setObjectName(_fromUtf8("edtEndDateStationary"))
        self.horizontalLayout_4.addWidget(self.edtEndDateStationary)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 16, 1, 1, 3)
        self.lblCaseBegDate = QtGui.QLabel(self.grpMainInfo)
        self.lblCaseBegDate.setObjectName(_fromUtf8("lblCaseBegDate"))
        self.gridLayout_6.addWidget(self.lblCaseBegDate, 8, 0, 1, 1)
        self.lblResultDate = QtGui.QLabel(self.grpMainInfo)
        self.lblResultDate.setObjectName(_fromUtf8("lblResultDate"))
        self.gridLayout_6.addWidget(self.lblResultDate, 22, 0, 1, 1)
        self.lblChangedReason = QtGui.QLabel(self.grpMainInfo)
        self.lblChangedReason.setObjectName(_fromUtf8("lblChangedReason"))
        self.gridLayout_6.addWidget(self.lblChangedReason, 2, 0, 1, 1)
        self.cmbChangedReason = CRBComboBox(self.grpMainInfo)
        self.cmbChangedReason.setObjectName(_fromUtf8("cmbChangedReason"))
        self.gridLayout_6.addWidget(self.cmbChangedReason, 2, 1, 1, 3)
        self.lblTempInvalidBreak = QtGui.QLabel(self.grpMainInfo)
        self.lblTempInvalidBreak.setObjectName(_fromUtf8("lblTempInvalidBreak"))
        self.gridLayout_6.addWidget(self.lblTempInvalidBreak, 15, 0, 1, 1)
        self.cmbTypeEducationalInstitution = CRBComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTypeEducationalInstitution.sizePolicy().hasHeightForWidth())
        self.cmbTypeEducationalInstitution.setSizePolicy(sizePolicy)
        self.cmbTypeEducationalInstitution.setObjectName(_fromUtf8("cmbTypeEducationalInstitution"))
        self.gridLayout_6.addWidget(self.cmbTypeEducationalInstitution, 5, 1, 1, 3)
        self.chkUserCert = QtGui.QCheckBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkUserCert.sizePolicy().hasHeightForWidth())
        self.chkUserCert.setSizePolicy(sizePolicy)
        self.chkUserCert.setObjectName(_fromUtf8("chkUserCert"))
        self.gridLayout_6.addWidget(self.chkUserCert, 23, 0, 1, 1)
        self.cmbUserCert = CCertComboBox(self.grpMainInfo)
        self.cmbUserCert.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbUserCert.sizePolicy().hasHeightForWidth())
        self.cmbUserCert.setSizePolicy(sizePolicy)
        self.cmbUserCert.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.cmbUserCert.setObjectName(_fromUtf8("cmbUserCert"))
        self.gridLayout_6.addWidget(self.cmbUserCert, 23, 1, 1, 3)
        self.lblTypeEducationalInstitution = QtGui.QLabel(self.grpMainInfo)
        self.lblTypeEducationalInstitution.setObjectName(_fromUtf8("lblTypeEducationalInstitution"))
        self.gridLayout_6.addWidget(self.lblTypeEducationalInstitution, 5, 0, 1, 1)
        self.edtInfContact = QtGui.QLineEdit(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtInfContact.sizePolicy().hasHeightForWidth())
        self.edtInfContact.setSizePolicy(sizePolicy)
        self.edtInfContact.setInputMask(_fromUtf8(""))
        self.edtInfContact.setObjectName(_fromUtf8("edtInfContact"))
        self.gridLayout_6.addWidget(self.edtInfContact, 13, 1, 1, 3)
        self.lblEvent = QtGui.QLabel(self.grpMainInfo)
        self.lblEvent.setObjectName(_fromUtf8("lblEvent"))
        self.gridLayout_6.addWidget(self.lblEvent, 18, 0, 1, 1)
        self.cmbEvent = CClientEventsComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEvent.sizePolicy().hasHeightForWidth())
        self.cmbEvent.setSizePolicy(sizePolicy)
        self.cmbEvent.setObjectName(_fromUtf8("cmbEvent"))
        self.gridLayout_6.addWidget(self.cmbEvent, 18, 1, 1, 3)
        self.lblMseDate = QtGui.QLabel(self.grpMainInfo)
        self.lblMseDate.setObjectName(_fromUtf8("lblMseDate"))
        self.gridLayout_6.addWidget(self.lblMseDate, 19, 0, 1, 1)
        self.edtMseDate = CDateEdit(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtMseDate.sizePolicy().hasHeightForWidth())
        self.edtMseDate.setSizePolicy(sizePolicy)
        self.edtMseDate.setCalendarPopup(True)
        self.edtMseDate.setObjectName(_fromUtf8("edtMseDate"))
        self.gridLayout_6.addWidget(self.edtMseDate, 19, 1, 1, 1)
        self.gridLayout_8.addWidget(self.grpMainInfo, 0, 0, 2, 1)
        self.grpTempInvalidPeriods = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpTempInvalidPeriods.sizePolicy().hasHeightForWidth())
        self.grpTempInvalidPeriods.setSizePolicy(sizePolicy)
        self.grpTempInvalidPeriods.setAlignment(QtCore.Qt.AlignCenter)
        self.grpTempInvalidPeriods.setObjectName(_fromUtf8("grpTempInvalidPeriods"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpTempInvalidPeriods)
        self.gridLayout_3.setContentsMargins(1, 0, 1, 1)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblPeriods = CTempInvalidPeriodsInDocTableView(self.grpTempInvalidPeriods)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblPeriods.sizePolicy().hasHeightForWidth())
        self.tblPeriods.setSizePolicy(sizePolicy)
        self.tblPeriods.setObjectName(_fromUtf8("tblPeriods"))
        self.gridLayout_3.addWidget(self.tblPeriods, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.grpTempInvalidPeriods, 0, 1, 1, 1)
        self.grpTempInvalidDocuments = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpTempInvalidDocuments.sizePolicy().hasHeightForWidth())
        self.grpTempInvalidDocuments.setSizePolicy(sizePolicy)
        self.grpTempInvalidDocuments.setAlignment(QtCore.Qt.AlignCenter)
        self.grpTempInvalidDocuments.setObjectName(_fromUtf8("grpTempInvalidDocuments"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpTempInvalidDocuments)
        self.gridLayout_2.setContentsMargins(1, 0, 1, 1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblDocuments = CTempInvalidDocumentsInDocTableView(self.grpTempInvalidDocuments)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblDocuments.sizePolicy().hasHeightForWidth())
        self.tblDocuments.setSizePolicy(sizePolicy)
        self.tblDocuments.setObjectName(_fromUtf8("tblDocuments"))
        self.gridLayout_2.addWidget(self.tblDocuments, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.grpTempInvalidDocuments, 1, 1, 1, 1)
        self.splitter = QtGui.QSplitter(self.scrollAreaWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.grbTempInvalidDocumentCare = QtGui.QGroupBox(self.splitter)
        self.grbTempInvalidDocumentCare.setAlignment(QtCore.Qt.AlignCenter)
        self.grbTempInvalidDocumentCare.setObjectName(_fromUtf8("grbTempInvalidDocumentCare"))
        self.gridLayout = QtGui.QGridLayout(self.grbTempInvalidDocumentCare)
        self.gridLayout.setContentsMargins(1, 0, 1, 1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tblCare = CTempInvalidDocumentCareInDocTableView(self.grbTempInvalidDocumentCare)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblCare.sizePolicy().hasHeightForWidth())
        self.tblCare.setSizePolicy(sizePolicy)
        self.tblCare.setObjectName(_fromUtf8("tblCare"))
        self.gridLayout.addWidget(self.tblCare, 0, 0, 1, 1)
        self.grpMedicalCommission = QtGui.QGroupBox(self.splitter)
        self.grpMedicalCommission.setAlignment(QtCore.Qt.AlignCenter)
        self.grpMedicalCommission.setObjectName(_fromUtf8("grpMedicalCommission"))
        self.gridLayout_4 = QtGui.QGridLayout(self.grpMedicalCommission)
        self.gridLayout_4.setContentsMargins(1, 0, 1, 1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tblMedicalCommission = CMedicalCommissionInDocTableView(self.grpMedicalCommission)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblMedicalCommission.sizePolicy().hasHeightForWidth())
        self.tblMedicalCommission.setSizePolicy(sizePolicy)
        self.tblMedicalCommission.setObjectName(_fromUtf8("tblMedicalCommission"))
        self.gridLayout_4.addWidget(self.tblMedicalCommission, 0, 0, 1, 1)
        self.grpMedicalCommissionMSI = QtGui.QGroupBox(self.splitter)
        self.grpMedicalCommissionMSI.setAlignment(QtCore.Qt.AlignCenter)
        self.grpMedicalCommissionMSI.setObjectName(_fromUtf8("grpMedicalCommissionMSI"))
        self.gridLayout_5 = QtGui.QGridLayout(self.grpMedicalCommissionMSI)
        self.gridLayout_5.setContentsMargins(1, 0, 1, 1)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tblMedicalCommissionMSI = CMedicalCommissionInDocTableView(self.grpMedicalCommissionMSI)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblMedicalCommissionMSI.sizePolicy().hasHeightForWidth())
        self.tblMedicalCommissionMSI.setSizePolicy(sizePolicy)
        self.tblMedicalCommissionMSI.setObjectName(_fromUtf8("tblMedicalCommissionMSI"))
        self.gridLayout_5.addWidget(self.tblMedicalCommissionMSI, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.splitter, 2, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_7.addWidget(self.scrollArea, 0, 0, 1, 2)
        self.lblExtraReason.setBuddy(self.cmbExtraReason)
        self.lblDoctype.setBuddy(self.cmbDoctype)
        self.lblReceiver.setBuddy(self.cmbReceiver)
        self.lblReason.setBuddy(self.cmbReason)
        self.lblInfContact.setBuddy(self.edtInfContact)
        self.lblOtherSex.setBuddy(self.cmbOtherSex)
        self.lblDiagnosis.setBuddy(self.edtDiagnosis)
        self.lblPresenceStationary.setBuddy(self.edtBegDateStationary)
        self.lblDisability.setBuddy(self.cmbDisability)
        self.lblResultOtherwiseDate.setBuddy(self.edtResultOtherwiseDate)
        self.lblOGRN.setBuddy(self.edtOGRN)
        self.lblResult.setBuddy(self.cmbResult)
        self.lblAccountPregnancyTo12Weeks.setBuddy(self.cmbAccountPregnancyTo12Weeks)
        self.lblCaseBegDate.setBuddy(self.edtCaseBegDate)
        self.lblResultDate.setBuddy(self.edtResultDate)
        self.lblTempInvalidBreak.setBuddy(self.edtBreakDate)
        self.lblTypeEducationalInstitution.setBuddy(self.cmbTypeEducationalInstitution)
        self.lblEvent.setBuddy(self.cmbEvent)
        self.lblMseDate.setBuddy(self.edtBegDateStationary)

        self.retranslateUi(TempInvalidEditDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TempInvalidEditDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TempInvalidEditDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TempInvalidEditDialog)
        TempInvalidEditDialog.setTabOrder(self.cmbDoctype, self.cmbReason)
        TempInvalidEditDialog.setTabOrder(self.cmbReason, self.cmbChangedReason)
        TempInvalidEditDialog.setTabOrder(self.cmbChangedReason, self.cmbExtraReason)
        TempInvalidEditDialog.setTabOrder(self.cmbExtraReason, self.cmbReceiver)
        TempInvalidEditDialog.setTabOrder(self.cmbReceiver, self.btnClientRelations)
        TempInvalidEditDialog.setTabOrder(self.btnClientRelations, self.cmbOtherSex)
        TempInvalidEditDialog.setTabOrder(self.cmbOtherSex, self.edtOtherAge)
        TempInvalidEditDialog.setTabOrder(self.edtOtherAge, self.edtDiagnosis)
        TempInvalidEditDialog.setTabOrder(self.edtDiagnosis, self.cmbDiseaseCharacter)
        TempInvalidEditDialog.setTabOrder(self.cmbDiseaseCharacter, self.edtCaseBegDate)
        TempInvalidEditDialog.setTabOrder(self.edtCaseBegDate, self.edtBegDatePermit)
        TempInvalidEditDialog.setTabOrder(self.edtBegDatePermit, self.edtEndDatePermit)
        TempInvalidEditDialog.setTabOrder(self.edtEndDatePermit, self.edtNumberPermit)
        TempInvalidEditDialog.setTabOrder(self.edtNumberPermit, self.edtOGRN)
        TempInvalidEditDialog.setTabOrder(self.edtOGRN, self.btnSelectHeadOrganisation)
        TempInvalidEditDialog.setTabOrder(self.btnSelectHeadOrganisation, self.cmbAccountPregnancyTo12Weeks)
        TempInvalidEditDialog.setTabOrder(self.cmbAccountPregnancyTo12Weeks, self.edtBreakDate)
        TempInvalidEditDialog.setTabOrder(self.edtBreakDate, self.cmbBreak)
        TempInvalidEditDialog.setTabOrder(self.cmbBreak, self.edtBegDateStationary)
        TempInvalidEditDialog.setTabOrder(self.edtBegDateStationary, self.edtEndDateStationary)
        TempInvalidEditDialog.setTabOrder(self.edtEndDateStationary, self.cmbDisability)
        TempInvalidEditDialog.setTabOrder(self.cmbDisability, self.cmbResult)
        TempInvalidEditDialog.setTabOrder(self.cmbResult, self.edtResultDate)
        TempInvalidEditDialog.setTabOrder(self.edtResultDate, self.edtResultOtherwiseDate)
        TempInvalidEditDialog.setTabOrder(self.edtResultOtherwiseDate, self.chkInsuranceOfficeMark)
        TempInvalidEditDialog.setTabOrder(self.chkInsuranceOfficeMark, self.tblPeriods)
        TempInvalidEditDialog.setTabOrder(self.tblPeriods, self.tblDocuments)
        TempInvalidEditDialog.setTabOrder(self.tblDocuments, self.tblMedicalCommission)
        TempInvalidEditDialog.setTabOrder(self.tblMedicalCommission, self.tblMedicalCommissionMSI)
        TempInvalidEditDialog.setTabOrder(self.tblMedicalCommissionMSI, self.buttonBox)

    def retranslateUi(self, TempInvalidEditDialog):
        TempInvalidEditDialog.setWindowTitle(_translate("TempInvalidEditDialog", "Документ временной нетрудоспособности", None))
        self.grpMainInfo.setTitle(_translate("TempInvalidEditDialog", "&Основная информация", None))
        self.edtBegDatePermit.setDisplayFormat(_translate("TempInvalidEditDialog", "dd.MM.yyyy", None))
        self.edtEndDatePermit.setDisplayFormat(_translate("TempInvalidEditDialog", "dd.MM.yyyy", None))
        self.edtNumberPermit.setInputMask(_translate("TempInvalidEditDialog", "9999999; ", None))
        self.lblExtraReason.setText(_translate("TempInvalidEditDialog", "Доп.причина", None))
        self.lblDoctype.setText(_translate("TempInvalidEditDialog", "&Тип", None))
        self.lblReceiver.setText(_translate("TempInvalidEditDialog", "Получатель", None))
        self.btnClientRelations.setToolTip(_translate("TempInvalidEditDialog", "Связи пациента", None))
        self.btnClientRelations.setText(_translate("TempInvalidEditDialog", "...", None))
        self.lblReason.setText(_translate("TempInvalidEditDialog", "&Причина", None))
        self.lblInfContact.setText(_translate("TempInvalidEditDialog", "Контакт", None))
        self.lblOtherSex.setText(_translate("TempInvalidEditDialog", "Пол ", None))
        self.cmbOtherSex.setItemText(1, _translate("TempInvalidEditDialog", "М", None))
        self.cmbOtherSex.setItemText(2, _translate("TempInvalidEditDialog", "Ж", None))
        self.lblOtherAge.setText(_translate("TempInvalidEditDialog", " возраст ", None))
        self.lblDiagnosis.setText(_translate("TempInvalidEditDialog", "Диагноз", None))
        self.edtBreakDate.setDisplayFormat(_translate("TempInvalidEditDialog", "dd.MM.yyyy", None))
        self.edtCaseBegDate.setDisplayFormat(_translate("TempInvalidEditDialog", "dd.MM.yyyy", None))
        self.lblCaseLength.setText(_translate("TempInvalidEditDialog", " дней ", None))
        self.lblCaseLengthValue.setToolTip(_translate("TempInvalidEditDialog", "Длительность ВУТ", None))
        self.lblLengthValueTool.setText(_translate("TempInvalidEditDialog", " Длит. ", None))
        self.lblLengthValue.setToolTip(_translate("TempInvalidEditDialog", "Длительность Периода", None))
        self.lblExternalLength.setText(_translate("TempInvalidEditDialog", " вне ЛПУ ", None))
        self.lblExternalLengthValue.setToolTip(_translate("TempInvalidEditDialog", "Длительность Периода вне ЛПУ", None))
        self.cmbAccountPregnancyTo12Weeks.setItemText(0, _translate("TempInvalidEditDialog", "Не задано", None))
        self.cmbAccountPregnancyTo12Weeks.setItemText(1, _translate("TempInvalidEditDialog", "Нет", None))
        self.cmbAccountPregnancyTo12Weeks.setItemText(2, _translate("TempInvalidEditDialog", "Да", None))
        self.lblPresenceStationary.setText(_translate("TempInvalidEditDialog", "В стационаре", None))
        self.lblDisability.setText(_translate("TempInvalidEditDialog", "Инвалидность", None))
        self.btnSelectHeadOrganisation.setText(_translate("TempInvalidEditDialog", "...", None))
        self.edtResultDate.setDisplayFormat(_translate("TempInvalidEditDialog", "dd.MM.yyyy", None))
        self.lblResultOtherwiseDate.setText(_translate("TempInvalidEditDialog", " Иное ", None))
        self.edtResultOtherwiseDate.setDisplayFormat(_translate("TempInvalidEditDialog", "dd.MM.yyyy", None))
        self.chkInsuranceOfficeMark.setText(_translate("TempInvalidEditDialog", "Страх.стол", None))
        self.edtOGRN.setInputMask(_translate("TempInvalidEditDialog", "999999999999900; ", None))
        self.lblOGRN.setText(_translate("TempInvalidEditDialog", "ОГРН", None))
        self.lblResult.setText(_translate("TempInvalidEditDialog", "Результат", None))
        self.lblAccountPregnancyTo12Weeks.setText(_translate("TempInvalidEditDialog", "Берем. до 12 н.", None))
        self.lblPermit.setText(_translate("TempInvalidEditDialog", "Путёвка/дата1,2", None))
        self.lblOrganisation.setText(_translate("TempInvalidEditDialog", "Организация", None))
        self.edtBegDateStationary.setDisplayFormat(_translate("TempInvalidEditDialog", "dd.MM.yyyy", None))
        self.edtEndDateStationary.setDisplayFormat(_translate("TempInvalidEditDialog", "dd.MM.yyyy", None))
        self.lblCaseBegDate.setText(_translate("TempInvalidEditDialog", "Дата начала ВУТ", None))
        self.lblResultDate.setText(_translate("TempInvalidEditDialog", "К работе", None))
        self.lblChangedReason.setText(_translate("TempInvalidEditDialog", "Изм. причина", None))
        self.lblTempInvalidBreak.setText(_translate("TempInvalidEditDialog", "Нарушение", None))
        self.chkUserCert.setText(_translate("TempInvalidEditDialog", "Подпись", None))
        self.lblTypeEducationalInstitution.setText(_translate("TempInvalidEditDialog", "Тип уч. заведения", None))
        self.edtInfContact.setToolTip(_translate("TempInvalidEditDialog", "Контакт с инфекционными больными", None))
        self.lblEvent.setText(_translate("TempInvalidEditDialog", "Эпизод", None))
        self.lblMseDate.setText(_translate("TempInvalidEditDialog", "Дата направления на МСЭ", None))
        self.edtMseDate.setDisplayFormat(_translate("TempInvalidEditDialog", "dd.MM.yyyy", None))
        self.grpTempInvalidPeriods.setTitle(_translate("TempInvalidEditDialog", "&Периоды", None))
        self.grpTempInvalidDocuments.setTitle(_translate("TempInvalidEditDialog", "&Бланки", None))
        self.grbTempInvalidDocumentCare.setTitle(_translate("TempInvalidEditDialog", "&Лица по уходу", None))
        self.grpMedicalCommission.setTitle(_translate("TempInvalidEditDialog", "&Врачебная комиссия", None))
        self.grpMedicalCommissionMSI.setTitle(_translate("TempInvalidEditDialog", "&МСЭ", None))

from Events.MedicalCommissionInDocTableView import CMedicalCommissionInDocTableView
from Events.TempInvalidDocumentCareInDocTableView import CTempInvalidDocumentCareInDocTableView
from Events.TempInvalidDocumentsInDocTableView import CTempInvalidDocumentsInDocTableView
from Events.TempInvalidPeriodsInDocTableView import CTempInvalidPeriodsInDocTableView
from Registry.ClientEventsComboBox import CClientEventsComboBox
from Registry.ClientRelationSimpleComboBox import CClientRelationSimpleComboBox
from library.CertComboBox import CCertComboBox
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEditEx
from library.ROComboBox import CROComboBox
from library.crbcombobox import CRBComboBox
