# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\Events\TempDisabilityEditDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TempDisabilityEditDialog(object):
    def setupUi(self, TempDisabilityEditDialog):
        TempDisabilityEditDialog.setObjectName(_fromUtf8("TempDisabilityEditDialog"))
        TempDisabilityEditDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        TempDisabilityEditDialog.resize(1310, 497)
        self.gridLayout_7 = QtGui.QGridLayout(TempDisabilityEditDialog)
        self.gridLayout_7.setMargin(4)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.buttonBox = QtGui.QDialogButtonBox(TempDisabilityEditDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_7.addWidget(self.buttonBox, 1, 0, 1, 2)
        self.scrollArea = QtGui.QScrollArea(TempDisabilityEditDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1300, 460))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_8 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.grpTempDisabilityDocuments = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpTempDisabilityDocuments.sizePolicy().hasHeightForWidth())
        self.grpTempDisabilityDocuments.setSizePolicy(sizePolicy)
        self.grpTempDisabilityDocuments.setAlignment(QtCore.Qt.AlignCenter)
        self.grpTempDisabilityDocuments.setObjectName(_fromUtf8("grpTempDisabilityDocuments"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grpTempDisabilityDocuments)
        self.gridLayout_3.setContentsMargins(1, 0, 1, 1)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblDocuments = CInDocTableView(self.grpTempDisabilityDocuments)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblDocuments.sizePolicy().hasHeightForWidth())
        self.tblDocuments.setSizePolicy(sizePolicy)
        self.tblDocuments.setObjectName(_fromUtf8("tblDocuments"))
        self.gridLayout_3.addWidget(self.tblDocuments, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.grpTempDisabilityDocuments, 0, 1, 1, 1)
        self.grpMainInfo = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpMainInfo.sizePolicy().hasHeightForWidth())
        self.grpMainInfo.setSizePolicy(sizePolicy)
        self.grpMainInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.grpMainInfo.setFlat(False)
        self.grpMainInfo.setObjectName(_fromUtf8("grpMainInfo"))
        self.gridLayout_6 = QtGui.QGridLayout(self.grpMainInfo)
        self.gridLayout_6.setContentsMargins(2, 0, 2, 1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblCaseDateDueTo = QtGui.QLabel(self.grpMainInfo)
        self.lblCaseDateDueTo.setObjectName(_fromUtf8("lblCaseDateDueTo"))
        self.gridLayout_6.addWidget(self.lblCaseDateDueTo, 9, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.edtCaseBegDate = CDateEdit(self.grpMainInfo)
        self.edtCaseBegDate.setEnabled(True)
        self.edtCaseBegDate.setCalendarPopup(True)
        self.edtCaseBegDate.setObjectName(_fromUtf8("edtCaseBegDate"))
        self.horizontalLayout_6.addWidget(self.edtCaseBegDate)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout_6.addLayout(self.horizontalLayout_6, 8, 1, 1, 3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblDiagnosis = QtGui.QLabel(self.grpMainInfo)
        self.lblDiagnosis.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDiagnosis.sizePolicy().hasHeightForWidth())
        self.lblDiagnosis.setSizePolicy(sizePolicy)
        self.lblDiagnosis.setObjectName(_fromUtf8("lblDiagnosis"))
        self.horizontalLayout_2.addWidget(self.lblDiagnosis)
        self.edtDiagnosis = CICDCodeEditEx(self.grpMainInfo)
        self.edtDiagnosis.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtDiagnosis.sizePolicy().hasHeightForWidth())
        self.edtDiagnosis.setSizePolicy(sizePolicy)
        self.edtDiagnosis.setMaximumSize(QtCore.QSize(60, 16777215))
        self.edtDiagnosis.setObjectName(_fromUtf8("edtDiagnosis"))
        self.horizontalLayout_2.addWidget(self.edtDiagnosis)
        self.cmbDiseaseCharacter = CRBComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDiseaseCharacter.sizePolicy().hasHeightForWidth())
        self.cmbDiseaseCharacter.setSizePolicy(sizePolicy)
        self.cmbDiseaseCharacter.setObjectName(_fromUtf8("cmbDiseaseCharacter"))
        self.horizontalLayout_2.addWidget(self.cmbDiseaseCharacter)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 10, 0, 1, 4)
        self.btnClientRelations = QtGui.QToolButton(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClientRelations.sizePolicy().hasHeightForWidth())
        self.btnClientRelations.setSizePolicy(sizePolicy)
        self.btnClientRelations.setObjectName(_fromUtf8("btnClientRelations"))
        self.gridLayout_6.addWidget(self.btnClientRelations, 2, 3, 1, 1)
        self.cmbSetType = QtGui.QComboBox(self.grpMainInfo)
        self.cmbSetType.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSetType.sizePolicy().hasHeightForWidth())
        self.cmbSetType.setSizePolicy(sizePolicy)
        self.cmbSetType.setObjectName(_fromUtf8("cmbSetType"))
        self.cmbSetType.addItem(_fromUtf8(""))
        self.cmbSetType.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cmbSetType, 3, 1, 1, 3)
        self.cmbReason = CRBComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReason.sizePolicy().hasHeightForWidth())
        self.cmbReason.setSizePolicy(sizePolicy)
        self.cmbReason.setObjectName(_fromUtf8("cmbReason"))
        self.gridLayout_6.addWidget(self.cmbReason, 5, 1, 1, 3)
        self.cmbReceiver = CClientRelationSimpleComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReceiver.sizePolicy().hasHeightForWidth())
        self.cmbReceiver.setSizePolicy(sizePolicy)
        self.cmbReceiver.setObjectName(_fromUtf8("cmbReceiver"))
        self.gridLayout_6.addWidget(self.cmbReceiver, 2, 1, 1, 2)
        self.lblReceiver = QtGui.QLabel(self.grpMainInfo)
        self.lblReceiver.setObjectName(_fromUtf8("lblReceiver"))
        self.gridLayout_6.addWidget(self.lblReceiver, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtNextCase = CDateEdit(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtNextCase.sizePolicy().hasHeightForWidth())
        self.edtNextCase.setSizePolicy(sizePolicy)
        self.edtNextCase.setCalendarPopup(True)
        self.edtNextCase.setObjectName(_fromUtf8("edtNextCase"))
        self.horizontalLayout.addWidget(self.edtNextCase)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_6.addLayout(self.horizontalLayout, 12, 1, 1, 3)
        self.lblGroup = QtGui.QLabel(self.grpMainInfo)
        self.lblGroup.setObjectName(_fromUtf8("lblGroup"))
        self.gridLayout_6.addWidget(self.lblGroup, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 18, 0, 1, 4)
        self.lblSetType = QtGui.QLabel(self.grpMainInfo)
        self.lblSetType.setObjectName(_fromUtf8("lblSetType"))
        self.gridLayout_6.addWidget(self.lblSetType, 3, 0, 1, 1)
        self.lblReason = QtGui.QLabel(self.grpMainInfo)
        self.lblReason.setObjectName(_fromUtf8("lblReason"))
        self.gridLayout_6.addWidget(self.lblReason, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.edtCaseDateDueTo = CDateEdit(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtCaseDateDueTo.sizePolicy().hasHeightForWidth())
        self.edtCaseDateDueTo.setSizePolicy(sizePolicy)
        self.edtCaseDateDueTo.setCalendarPopup(True)
        self.edtCaseDateDueTo.setObjectName(_fromUtf8("edtCaseDateDueTo"))
        self.horizontalLayout_3.addWidget(self.edtCaseDateDueTo)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.chkCaseDateIndef = QtGui.QCheckBox(self.grpMainInfo)
        self.chkCaseDateIndef.setObjectName(_fromUtf8("chkCaseDateIndef"))
        self.horizontalLayout_3.addWidget(self.chkCaseDateIndef)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 9, 1, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 19, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.edtSkipCaseBegDate = CDateEdit(self.grpMainInfo)
        self.edtSkipCaseBegDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSkipCaseBegDate.sizePolicy().hasHeightForWidth())
        self.edtSkipCaseBegDate.setSizePolicy(sizePolicy)
        self.edtSkipCaseBegDate.setCalendarPopup(True)
        self.edtSkipCaseBegDate.setObjectName(_fromUtf8("edtSkipCaseBegDate"))
        self.gridLayout.addWidget(self.edtSkipCaseBegDate, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.edtSkipCaseEndDate = CDateEdit(self.grpMainInfo)
        self.edtSkipCaseEndDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSkipCaseEndDate.sizePolicy().hasHeightForWidth())
        self.edtSkipCaseEndDate.setSizePolicy(sizePolicy)
        self.edtSkipCaseEndDate.setCalendarPopup(True)
        self.edtSkipCaseEndDate.setObjectName(_fromUtf8("edtSkipCaseEndDate"))
        self.gridLayout.addWidget(self.edtSkipCaseEndDate, 0, 3, 1, 1)
        self.cmbSkipCaseReason = QtGui.QComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSkipCaseReason.sizePolicy().hasHeightForWidth())
        self.cmbSkipCaseReason.setSizePolicy(sizePolicy)
        self.cmbSkipCaseReason.setEditable(False)
        self.cmbSkipCaseReason.setObjectName(_fromUtf8("cmbSkipCaseReason"))
        self.cmbSkipCaseReason.addItem(_fromUtf8(""))
        self.cmbSkipCaseReason.addItem(_fromUtf8(""))
        self.cmbSkipCaseReason.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbSkipCaseReason, 0, 5, 1, 1)
        self.lblChildCase = QtGui.QLabel(self.grpMainInfo)
        self.lblChildCase.setObjectName(_fromUtf8("lblChildCase"))
        self.gridLayout.addWidget(self.lblChildCase, 1, 0, 1, 6)
        self.edtChildCaseBegDate = CDateEdit(self.grpMainInfo)
        self.edtChildCaseBegDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtChildCaseBegDate.sizePolicy().hasHeightForWidth())
        self.edtChildCaseBegDate.setSizePolicy(sizePolicy)
        self.edtChildCaseBegDate.setCalendarPopup(True)
        self.edtChildCaseBegDate.setObjectName(_fromUtf8("edtChildCaseBegDate"))
        self.gridLayout.addWidget(self.edtChildCaseBegDate, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.lblResultOtherwiseDate = QtGui.QLabel(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblResultOtherwiseDate.sizePolicy().hasHeightForWidth())
        self.lblResultOtherwiseDate.setSizePolicy(sizePolicy)
        self.lblResultOtherwiseDate.setObjectName(_fromUtf8("lblResultOtherwiseDate"))
        self.gridLayout.addWidget(self.lblResultOtherwiseDate, 2, 2, 1, 1)
        self.edtChildCaseEndDate = CDateEdit(self.grpMainInfo)
        self.edtChildCaseEndDate.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtChildCaseEndDate.sizePolicy().hasHeightForWidth())
        self.edtChildCaseEndDate.setSizePolicy(sizePolicy)
        self.edtChildCaseEndDate.setCalendarPopup(True)
        self.edtChildCaseEndDate.setObjectName(_fromUtf8("edtChildCaseEndDate"))
        self.gridLayout.addWidget(self.edtChildCaseEndDate, 2, 3, 1, 1)
        self.chkChildCase = QtGui.QCheckBox(self.grpMainInfo)
        self.chkChildCase.setObjectName(_fromUtf8("chkChildCase"))
        self.gridLayout.addWidget(self.chkChildCase, 2, 5, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 16, 0, 1, 4)
        self.cmbGroup = CRBComboBox(self.grpMainInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbGroup.sizePolicy().hasHeightForWidth())
        self.cmbGroup.setSizePolicy(sizePolicy)
        self.cmbGroup.setObjectName(_fromUtf8("cmbGroup"))
        self.gridLayout_6.addWidget(self.cmbGroup, 4, 1, 1, 3)
        self.lblNextDate = QtGui.QLabel(self.grpMainInfo)
        self.lblNextDate.setObjectName(_fromUtf8("lblNextDate"))
        self.gridLayout_6.addWidget(self.lblNextDate, 12, 0, 1, 1)
        self.lblCaseBegDate = QtGui.QLabel(self.grpMainInfo)
        self.lblCaseBegDate.setObjectName(_fromUtf8("lblCaseBegDate"))
        self.gridLayout_6.addWidget(self.lblCaseBegDate, 8, 0, 1, 1)
        self.lblSkipCase = QtGui.QLabel(self.grpMainInfo)
        self.lblSkipCase.setObjectName(_fromUtf8("lblSkipCase"))
        self.gridLayout_6.addWidget(self.lblSkipCase, 15, 0, 1, 4)
        self.edtReasonNote = QtGui.QLineEdit(self.grpMainInfo)
        self.edtReasonNote.setObjectName(_fromUtf8("edtReasonNote"))
        self.gridLayout_6.addWidget(self.edtReasonNote, 7, 1, 1, 3)
        self.lblReasonNote = QtGui.QLabel(self.grpMainInfo)
        self.lblReasonNote.setObjectName(_fromUtf8("lblReasonNote"))
        self.gridLayout_6.addWidget(self.lblReasonNote, 7, 0, 1, 1)
        self.gridLayout_8.addWidget(self.grpMainInfo, 0, 0, 2, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_7.addWidget(self.scrollArea, 0, 0, 1, 2)
        self.lblDiagnosis.setBuddy(self.edtDiagnosis)
        self.lblReceiver.setBuddy(self.cmbReceiver)
        self.lblGroup.setBuddy(self.cmbGroup)
        self.lblSetType.setBuddy(self.cmbSetType)
        self.lblReason.setBuddy(self.cmbReason)
        self.lblResultOtherwiseDate.setBuddy(self.edtChildCaseEndDate)
        self.lblCaseBegDate.setBuddy(self.edtCaseBegDate)

        self.retranslateUi(TempDisabilityEditDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TempDisabilityEditDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TempDisabilityEditDialog.reject)
        QtCore.QObject.connect(self.chkCaseDateIndef, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtCaseDateDueTo.setDisabled)
        QtCore.QObject.connect(self.chkChildCase, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtChildCaseBegDate.setEnabled)
        QtCore.QObject.connect(self.chkChildCase, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtChildCaseEndDate.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(TempDisabilityEditDialog)
        TempDisabilityEditDialog.setTabOrder(self.cmbReceiver, self.btnClientRelations)
        TempDisabilityEditDialog.setTabOrder(self.btnClientRelations, self.edtCaseBegDate)
        TempDisabilityEditDialog.setTabOrder(self.edtCaseBegDate, self.edtCaseDateDueTo)
        TempDisabilityEditDialog.setTabOrder(self.edtCaseDateDueTo, self.edtSkipCaseBegDate)
        TempDisabilityEditDialog.setTabOrder(self.edtSkipCaseBegDate, self.edtSkipCaseEndDate)
        TempDisabilityEditDialog.setTabOrder(self.edtSkipCaseEndDate, self.tblDocuments)
        TempDisabilityEditDialog.setTabOrder(self.tblDocuments, self.buttonBox)

    def retranslateUi(self, TempDisabilityEditDialog):
        TempDisabilityEditDialog.setWindowTitle(_translate("TempDisabilityEditDialog", "Документ временной нетрудоспособности", None))
        self.grpTempDisabilityDocuments.setTitle(_translate("TempDisabilityEditDialog", "&Документы", None))
        self.grpMainInfo.setTitle(_translate("TempDisabilityEditDialog", "&Основная информация", None))
        self.lblCaseDateDueTo.setText(_translate("TempDisabilityEditDialog", "Инвалидность установлена на срок до", None))
        self.edtCaseBegDate.setDisplayFormat(_translate("TempDisabilityEditDialog", "dd.MM.yyyy", None))
        self.lblDiagnosis.setText(_translate("TempDisabilityEditDialog", "Диагноз", None))
        self.btnClientRelations.setToolTip(_translate("TempDisabilityEditDialog", "Связи пациента", None))
        self.btnClientRelations.setText(_translate("TempDisabilityEditDialog", "...", None))
        self.cmbSetType.setItemText(0, _translate("TempDisabilityEditDialog", "Впервые", None))
        self.cmbSetType.setItemText(1, _translate("TempDisabilityEditDialog", "Повторно", None))
        self.lblReceiver.setText(_translate("TempDisabilityEditDialog", "Получатель", None))
        self.lblGroup.setText(_translate("TempDisabilityEditDialog", "Группа инвалидности", None))
        self.lblSetType.setText(_translate("TempDisabilityEditDialog", "&Тип установления инвалидности", None))
        self.lblReason.setText(_translate("TempDisabilityEditDialog", "&Причина инвалидности", None))
        self.edtCaseDateDueTo.setDisplayFormat(_translate("TempDisabilityEditDialog", "dd.MM.yyyy", None))
        self.chkCaseDateIndef.setText(_translate("TempDisabilityEditDialog", "бессрочно", None))
        self.label_2.setText(_translate("TempDisabilityEditDialog", "признана", None))
        self.edtSkipCaseBegDate.setDisplayFormat(_translate("TempDisabilityEditDialog", "dd.MM.yyyy", None))
        self.label_3.setText(_translate("TempDisabilityEditDialog", "с", None))
        self.label_4.setText(_translate("TempDisabilityEditDialog", "по", None))
        self.edtSkipCaseEndDate.setDisplayFormat(_translate("TempDisabilityEditDialog", "dd.MM.yyyy", None))
        self.cmbSkipCaseReason.setItemText(0, _translate("TempDisabilityEditDialog", "Не установлено", None))
        self.cmbSkipCaseReason.setItemText(1, _translate("TempDisabilityEditDialog", "Уважительной", None))
        self.cmbSkipCaseReason.setItemText(2, _translate("TempDisabilityEditDialog", "Неуважительной", None))
        self.lblChildCase.setText(_translate("TempDisabilityEditDialog", "Инвалидность (категория \"ребенок-инвалид\") за прошлое время", None))
        self.edtChildCaseBegDate.setDisplayFormat(_translate("TempDisabilityEditDialog", "dd.MM.yyyy", None))
        self.label_5.setText(_translate("TempDisabilityEditDialog", "с", None))
        self.lblResultOtherwiseDate.setText(_translate("TempDisabilityEditDialog", "по", None))
        self.edtChildCaseEndDate.setDisplayFormat(_translate("TempDisabilityEditDialog", "dd.MM.yyyy", None))
        self.chkChildCase.setText(_translate("TempDisabilityEditDialog", "Установлена", None))
        self.lblNextDate.setText(_translate("TempDisabilityEditDialog", "Дата очередного освидетельствования", None))
        self.lblCaseBegDate.setText(_translate("TempDisabilityEditDialog", "Дата начала инвалидности", None))
        self.lblSkipCase.setText(_translate("TempDisabilityEditDialog", "Причина пропуска срока переосвидетельствования за прошлое время", None))
        self.lblReasonNote.setText(_translate("TempDisabilityEditDialog", "Уточнение причины", None))

from Registry.ClientRelationSimpleComboBox import CClientRelationSimpleComboBox
from library.DateEdit import CDateEdit
from library.ICDCodeEdit import CICDCodeEditEx
from library.InDocTable import CInDocTableView
from library.crbcombobox import CRBComboBox
