# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ServiceFilterDialog.ui'
#
# Created: Tue Sep 30 08:14:10 2025
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ServiceFilterDialog(object):
    def setupUi(self, ServiceFilterDialog):
        ServiceFilterDialog.setObjectName(_fromUtf8("ServiceFilterDialog"))
        ServiceFilterDialog.resize(407, 326)
        ServiceFilterDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ServiceFilterDialog)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbServiceGroup = CRBComboBox(ServiceFilterDialog)
        self.cmbServiceGroup.setObjectName(_fromUtf8("cmbServiceGroup"))
        self.gridLayout.addWidget(self.cmbServiceGroup, 0, 1, 1, 1)
        self.label = QtGui.QLabel(ServiceFilterDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 7, 0, 1, 1)
        self.lblServiceGroup = QtGui.QLabel(ServiceFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblServiceGroup.sizePolicy().hasHeightForWidth())
        self.lblServiceGroup.setSizePolicy(sizePolicy)
        self.lblServiceGroup.setObjectName(_fromUtf8("lblServiceGroup"))
        self.gridLayout.addWidget(self.lblServiceGroup, 0, 0, 1, 1)
        self.chkEIS = QtGui.QCheckBox(ServiceFilterDialog)
        self.chkEIS.setTristate(True)
        self.chkEIS.setObjectName(_fromUtf8("chkEIS"))
        self.gridLayout.addWidget(self.chkEIS, 8, 1, 1, 1)
        self.edtNote = QtGui.QLineEdit(ServiceFilterDialog)
        self.edtNote.setObjectName(_fromUtf8("edtNote"))
        self.gridLayout.addWidget(self.edtNote, 7, 1, 1, 1)
        self.lblClass = QtGui.QLabel(ServiceFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblClass.sizePolicy().hasHeightForWidth())
        self.lblClass.setSizePolicy(sizePolicy)
        self.lblClass.setObjectName(_fromUtf8("lblClass"))
        self.gridLayout.addWidget(self.lblClass, 3, 0, 1, 1)
        self.cmbType = CRBComboBox(ServiceFilterDialog)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.gridLayout.addWidget(self.cmbType, 2, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edtBegDate = CDateEdit(ServiceFilterDialog)
        self.edtBegDate.setObjectName(_fromUtf8("edtBegDate"))
        self.horizontalLayout.addWidget(self.edtBegDate)
        self.lblTo = QtGui.QLabel(ServiceFilterDialog)
        self.lblTo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTo.setObjectName(_fromUtf8("lblTo"))
        self.horizontalLayout.addWidget(self.lblTo)
        self.edtEndDate = CDateEdit(ServiceFilterDialog)
        self.edtEndDate.setObjectName(_fromUtf8("edtEndDate"))
        self.horizontalLayout.addWidget(self.edtEndDate)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 12, 1, 1, 1)
        self.lblCreatePeriod = QtGui.QLabel(ServiceFilterDialog)
        self.lblCreatePeriod.setObjectName(_fromUtf8("lblCreatePeriod"))
        self.gridLayout.addWidget(self.lblCreatePeriod, 14, 0, 1, 1)
        self.lblType = QtGui.QLabel(ServiceFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblType.sizePolicy().hasHeightForWidth())
        self.lblType.setSizePolicy(sizePolicy)
        self.lblType.setObjectName(_fromUtf8("lblType"))
        self.gridLayout.addWidget(self.lblType, 2, 0, 1, 1)
        self.lblName = QtGui.QLabel(ServiceFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 5, 0, 1, 1)
        self.cmbClass = CRBComboBox(ServiceFilterDialog)
        self.cmbClass.setObjectName(_fromUtf8("cmbClass"))
        self.gridLayout.addWidget(self.cmbClass, 3, 1, 1, 1)
        self.chkNomenclature = QtGui.QCheckBox(ServiceFilterDialog)
        self.chkNomenclature.setTristate(True)
        self.chkNomenclature.setObjectName(_fromUtf8("chkNomenclature"))
        self.gridLayout.addWidget(self.chkNomenclature, 9, 1, 1, 1)
        self.edtCode = QtGui.QLineEdit(ServiceFilterDialog)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout.addWidget(self.edtCode, 4, 1, 1, 1)
        self.lblSection = QtGui.QLabel(ServiceFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSection.sizePolicy().hasHeightForWidth())
        self.lblSection.setSizePolicy(sizePolicy)
        self.lblSection.setObjectName(_fromUtf8("lblSection"))
        self.gridLayout.addWidget(self.lblSection, 1, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(ServiceFilterDialog)
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 5, 1, 1, 1)
        self.cmbSection = CRBComboBox(ServiceFilterDialog)
        self.cmbSection.setObjectName(_fromUtf8("cmbSection"))
        self.gridLayout.addWidget(self.cmbSection, 1, 1, 1, 1)
        self.lblCode = QtGui.QLabel(ServiceFilterDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 15, 0, 1, 1)
        self.lblPeriod = QtGui.QLabel(ServiceFilterDialog)
        self.lblPeriod.setObjectName(_fromUtf8("lblPeriod"))
        self.gridLayout.addWidget(self.lblPeriod, 12, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ServiceFilterDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 17, 0, 1, 2)
        self.horizontalLayoutCreatePeriod = QtGui.QHBoxLayout()
        self.horizontalLayoutCreatePeriod.setSpacing(4)
        self.horizontalLayoutCreatePeriod.setObjectName(_fromUtf8("horizontalLayoutCreatePeriod"))
        self.edtCreatePeriodBegDate = CDateEdit(ServiceFilterDialog)
        self.edtCreatePeriodBegDate.setObjectName(_fromUtf8("edtCreatePeriodBegDate"))
        self.horizontalLayoutCreatePeriod.addWidget(self.edtCreatePeriodBegDate)
        self.lblCreatePeriodTo = QtGui.QLabel(ServiceFilterDialog)
        self.lblCreatePeriodTo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCreatePeriodTo.setObjectName(_fromUtf8("lblCreatePeriodTo"))
        self.horizontalLayoutCreatePeriod.addWidget(self.lblCreatePeriodTo)
        self.edtCreatePeriodEndDate = CDateEdit(ServiceFilterDialog)
        self.edtCreatePeriodEndDate.setObjectName(_fromUtf8("edtCreatePeriodEndDate"))
        self.horizontalLayoutCreatePeriod.addWidget(self.edtCreatePeriodEndDate)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutCreatePeriod.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayoutCreatePeriod, 14, 1, 1, 1)
        self.chkCloseServices = QtGui.QCheckBox(ServiceFilterDialog)
        self.chkCloseServices.setObjectName(_fromUtf8("chkCloseServices"))
        self.gridLayout.addWidget(self.chkCloseServices, 16, 0, 1, 1)
        self.label.setBuddy(self.edtNote)
        self.lblServiceGroup.setBuddy(self.cmbServiceGroup)
        self.lblClass.setBuddy(self.cmbClass)
        self.lblTo.setBuddy(self.edtEndDate)
        self.lblCreatePeriod.setBuddy(self.edtCreatePeriodBegDate)
        self.lblType.setBuddy(self.cmbType)
        self.lblName.setBuddy(self.edtName)
        self.lblSection.setBuddy(self.cmbSection)
        self.lblCode.setBuddy(self.edtCode)
        self.lblPeriod.setBuddy(self.edtBegDate)
        self.lblCreatePeriodTo.setBuddy(self.edtCreatePeriodEndDate)

        self.retranslateUi(ServiceFilterDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ServiceFilterDialog.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ServiceFilterDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(ServiceFilterDialog)
        ServiceFilterDialog.setTabOrder(self.cmbServiceGroup, self.cmbSection)
        ServiceFilterDialog.setTabOrder(self.cmbSection, self.cmbType)
        ServiceFilterDialog.setTabOrder(self.cmbType, self.cmbClass)
        ServiceFilterDialog.setTabOrder(self.cmbClass, self.edtCode)
        ServiceFilterDialog.setTabOrder(self.edtCode, self.edtName)
        ServiceFilterDialog.setTabOrder(self.edtName, self.edtNote)
        ServiceFilterDialog.setTabOrder(self.edtNote, self.chkEIS)
        ServiceFilterDialog.setTabOrder(self.chkEIS, self.chkNomenclature)
        ServiceFilterDialog.setTabOrder(self.chkNomenclature, self.edtBegDate)
        ServiceFilterDialog.setTabOrder(self.edtBegDate, self.edtEndDate)
        ServiceFilterDialog.setTabOrder(self.edtEndDate, self.edtCreatePeriodBegDate)
        ServiceFilterDialog.setTabOrder(self.edtCreatePeriodBegDate, self.edtCreatePeriodEndDate)
        ServiceFilterDialog.setTabOrder(self.edtCreatePeriodEndDate, self.buttonBox)

    def retranslateUi(self, ServiceFilterDialog):
        ServiceFilterDialog.setWindowTitle(_translate("ServiceFilterDialog", "Фильтр услуг", None))
        self.label.setText(_translate("ServiceFilterDialog", "&Примечение содержит", None))
        self.lblServiceGroup.setText(_translate("ServiceFilterDialog", "&Группа", None))
        self.chkEIS.setText(_translate("ServiceFilterDialog", "Унаследовано из ЕИС", None))
        self.lblClass.setText(_translate("ServiceFilterDialog", "&Класс", None))
        self.lblTo.setText(_translate("ServiceFilterDialog", "по", None))
        self.lblCreatePeriod.setText(_translate("ServiceFilterDialog", "Добавлено в период с", None))
        self.lblType.setText(_translate("ServiceFilterDialog", "&Тип", None))
        self.lblName.setText(_translate("ServiceFilterDialog", "&Название содержит", None))
        self.chkNomenclature.setText(_translate("ServiceFilterDialog", "Унаследовано из номенклатуры", None))
        self.lblSection.setText(_translate("ServiceFilterDialog", "&Раздел", None))
        self.lblCode.setText(_translate("ServiceFilterDialog", "Код начинается &с", None))
        self.lblPeriod.setText(_translate("ServiceFilterDialog", "Период &c", None))
        self.lblCreatePeriodTo.setText(_translate("ServiceFilterDialog", "по", None))
        self.chkCloseServices.setText(_translate("ServiceFilterDialog", "Только актуальные", None))

from library.crbcombobox import CRBComboBox
from library.DateEdit import CDateEdit
