# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\samson\DataCheck\LogicalControlDoubles.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LogicalControlDoubles(object):
    def setupUi(self, LogicalControlDoubles):
        LogicalControlDoubles.setObjectName(_fromUtf8("LogicalControlDoubles"))
        LogicalControlDoubles.resize(686, 363)
        self.gridLayout_2 = QtGui.QGridLayout(LogicalControlDoubles)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget = QtGui.QWidget(LogicalControlDoubles)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 8, 1, 1)
        self.chkBirthDateClient = QtGui.QCheckBox(self.widget)
        self.chkBirthDateClient.setChecked(True)
        self.chkBirthDateClient.setObjectName(_fromUtf8("chkBirthDateClient"))
        self.gridLayout.addWidget(self.chkBirthDateClient, 1, 1, 1, 1)
        self.chkPolicyClient = QtGui.QCheckBox(self.widget)
        self.chkPolicyClient.setChecked(True)
        self.chkPolicyClient.setObjectName(_fromUtf8("chkPolicyClient"))
        self.gridLayout.addWidget(self.chkPolicyClient, 1, 2, 1, 1)
        self.chkPatrNameClient = QtGui.QCheckBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkPatrNameClient.sizePolicy().hasHeightForWidth())
        self.chkPatrNameClient.setSizePolicy(sizePolicy)
        self.chkPatrNameClient.setChecked(True)
        self.chkPatrNameClient.setObjectName(_fromUtf8("chkPatrNameClient"))
        self.gridLayout.addWidget(self.chkPatrNameClient, 2, 0, 1, 1)
        self.chkLastNameClient = QtGui.QCheckBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkLastNameClient.sizePolicy().hasHeightForWidth())
        self.chkLastNameClient.setSizePolicy(sizePolicy)
        self.chkLastNameClient.setChecked(True)
        self.chkLastNameClient.setObjectName(_fromUtf8("chkLastNameClient"))
        self.gridLayout.addWidget(self.chkLastNameClient, 0, 0, 1, 1)
        self.chkFirstNameClient = QtGui.QCheckBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFirstNameClient.sizePolicy().hasHeightForWidth())
        self.chkFirstNameClient.setSizePolicy(sizePolicy)
        self.chkFirstNameClient.setChecked(True)
        self.chkFirstNameClient.setObjectName(_fromUtf8("chkFirstNameClient"))
        self.gridLayout.addWidget(self.chkFirstNameClient, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 8, 1, 1)
        self.chkSexClient = QtGui.QCheckBox(self.widget)
        self.chkSexClient.setChecked(True)
        self.chkSexClient.setObjectName(_fromUtf8("chkSexClient"))
        self.gridLayout.addWidget(self.chkSexClient, 0, 1, 1, 1)
        self.lblBirthDateFilter = QtGui.QLabel(self.widget)
        self.lblBirthDateFilter.setObjectName(_fromUtf8("lblBirthDateFilter"))
        self.gridLayout.addWidget(self.lblBirthDateFilter, 1, 6, 1, 1)
        self.chkSNILSClient = QtGui.QCheckBox(self.widget)
        self.chkSNILSClient.setChecked(True)
        self.chkSNILSClient.setObjectName(_fromUtf8("chkSNILSClient"))
        self.gridLayout.addWidget(self.chkSNILSClient, 2, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 8, 1, 1)
        self.chkDocumentsClient = QtGui.QCheckBox(self.widget)
        self.chkDocumentsClient.setChecked(True)
        self.chkDocumentsClient.setObjectName(_fromUtf8("chkDocumentsClient"))
        self.gridLayout.addWidget(self.chkDocumentsClient, 0, 2, 1, 1)
        self.chkLastNameFilter = QtGui.QCheckBox(self.widget)
        self.chkLastNameFilter.setObjectName(_fromUtf8("chkLastNameFilter"))
        self.gridLayout.addWidget(self.chkLastNameFilter, 0, 4, 1, 1)
        self.edtBirthDateFilterFrom = CDateEdit(self.widget)
        self.edtBirthDateFilterFrom.setEnabled(False)
        self.edtBirthDateFilterFrom.setObjectName(_fromUtf8("edtBirthDateFilterFrom"))
        self.gridLayout.addWidget(self.edtBirthDateFilterFrom, 1, 5, 1, 1)
        self.chkLimitFilter = QtGui.QCheckBox(self.widget)
        self.chkLimitFilter.setObjectName(_fromUtf8("chkLimitFilter"))
        self.gridLayout.addWidget(self.chkLimitFilter, 2, 4, 1, 1)
        self.lblLastNameFilter = QtGui.QLabel(self.widget)
        self.lblLastNameFilter.setObjectName(_fromUtf8("lblLastNameFilter"))
        self.gridLayout.addWidget(self.lblLastNameFilter, 0, 6, 1, 1)
        self.chkBirthDateFilter = QtGui.QCheckBox(self.widget)
        self.chkBirthDateFilter.setObjectName(_fromUtf8("chkBirthDateFilter"))
        self.gridLayout.addWidget(self.chkBirthDateFilter, 1, 4, 1, 1)
        self.lblLimitFilter = QtGui.QLabel(self.widget)
        self.lblLimitFilter.setObjectName(_fromUtf8("lblLimitFilter"))
        self.gridLayout.addWidget(self.lblLimitFilter, 2, 6, 1, 2)
        self.edtBirthDateFilterTo = CDateEdit(self.widget)
        self.edtBirthDateFilterTo.setEnabled(False)
        self.edtBirthDateFilterTo.setObjectName(_fromUtf8("edtBirthDateFilterTo"))
        self.gridLayout.addWidget(self.edtBirthDateFilterTo, 1, 7, 1, 1)
        self.edtLastNameFilterFrom = QtGui.QLineEdit(self.widget)
        self.edtLastNameFilterFrom.setEnabled(False)
        self.edtLastNameFilterFrom.setObjectName(_fromUtf8("edtLastNameFilterFrom"))
        self.gridLayout.addWidget(self.edtLastNameFilterFrom, 0, 5, 1, 1)
        self.edtLimitFilter = QtGui.QLineEdit(self.widget)
        self.edtLimitFilter.setEnabled(False)
        self.edtLimitFilter.setObjectName(_fromUtf8("edtLimitFilter"))
        self.gridLayout.addWidget(self.edtLimitFilter, 2, 5, 1, 1)
        self.edtLastNameFilterTo = QtGui.QLineEdit(self.widget)
        self.edtLastNameFilterTo.setEnabled(False)
        self.edtLastNameFilterTo.setObjectName(_fromUtf8("edtLastNameFilterTo"))
        self.gridLayout.addWidget(self.edtLastNameFilterTo, 0, 7, 1, 1)
        self.chkHaveDocumentsClient = QtGui.QCheckBox(self.widget)
        self.chkHaveDocumentsClient.setEnabled(True)
        self.chkHaveDocumentsClient.setObjectName(_fromUtf8("chkHaveDocumentsClient"))
        self.gridLayout.addWidget(self.chkHaveDocumentsClient, 0, 3, 1, 1)
        self.chkHavePolicyClient = QtGui.QCheckBox(self.widget)
        self.chkHavePolicyClient.setEnabled(True)
        self.chkHavePolicyClient.setObjectName(_fromUtf8("chkHavePolicyClient"))
        self.gridLayout.addWidget(self.chkHavePolicyClient, 1, 3, 1, 1)
        self.chkHaveSNILSClient = QtGui.QCheckBox(self.widget)
        self.chkHaveSNILSClient.setEnabled(True)
        self.chkHaveSNILSClient.setObjectName(_fromUtf8("chkHaveSNILSClient"))
        self.gridLayout.addWidget(self.chkHaveSNILSClient, 2, 3, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 7)
        self.prbControlDoubles = CProgressBar(LogicalControlDoubles)
        self.prbControlDoubles.setObjectName(_fromUtf8("prbControlDoubles"))
        self.gridLayout_2.addWidget(self.prbControlDoubles, 1, 0, 1, 7)
        self.tblDoubleClients = CControlDoublesPopupMenu(LogicalControlDoubles)
        self.tblDoubleClients.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tblDoubleClients.setObjectName(_fromUtf8("tblDoubleClients"))
        self.gridLayout_2.addWidget(self.tblDoubleClients, 2, 0, 1, 7)
        self.btnNewTuning = QtGui.QPushButton(LogicalControlDoubles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewTuning.sizePolicy().hasHeightForWidth())
        self.btnNewTuning.setSizePolicy(sizePolicy)
        self.btnNewTuning.setMinimumSize(QtCore.QSize(100, 0))
        self.btnNewTuning.setObjectName(_fromUtf8("btnNewTuning"))
        self.gridLayout_2.addWidget(self.btnNewTuning, 3, 0, 1, 1)
        self.label = QtGui.QLabel(LogicalControlDoubles)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(214, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 3, 1, 1)
        self.lblCountRecords = QtGui.QLabel(LogicalControlDoubles)
        self.lblCountRecords.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCountRecords.setObjectName(_fromUtf8("lblCountRecords"))
        self.gridLayout_2.addWidget(self.lblCountRecords, 3, 2, 1, 1)
        self.btnBeginCheck = QtGui.QPushButton(LogicalControlDoubles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBeginCheck.sizePolicy().hasHeightForWidth())
        self.btnBeginCheck.setSizePolicy(sizePolicy)
        self.btnBeginCheck.setMinimumSize(QtCore.QSize(100, 0))
        self.btnBeginCheck.setObjectName(_fromUtf8("btnBeginCheck"))
        self.gridLayout_2.addWidget(self.btnBeginCheck, 3, 5, 1, 1)
        self.btnEndCheck = QtGui.QPushButton(LogicalControlDoubles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEndCheck.sizePolicy().hasHeightForWidth())
        self.btnEndCheck.setSizePolicy(sizePolicy)
        self.btnEndCheck.setMinimumSize(QtCore.QSize(100, 0))
        self.btnEndCheck.setObjectName(_fromUtf8("btnEndCheck"))
        self.gridLayout_2.addWidget(self.btnEndCheck, 3, 6, 1, 1)
        self.btnPrint = QtGui.QPushButton(LogicalControlDoubles)
        self.btnPrint.setObjectName(_fromUtf8("btnPrint"))
        self.gridLayout_2.addWidget(self.btnPrint, 3, 4, 1, 1)

        self.retranslateUi(LogicalControlDoubles)
        QtCore.QObject.connect(self.chkBirthDateFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBirthDateFilterFrom.setEnabled)
        QtCore.QObject.connect(self.chkBirthDateFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtBirthDateFilterTo.setEnabled)
        QtCore.QObject.connect(self.chkLastNameFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtLastNameFilterFrom.setEnabled)
        QtCore.QObject.connect(self.chkLastNameFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtLastNameFilterTo.setEnabled)
        QtCore.QObject.connect(self.chkLimitFilter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.edtLimitFilter.setEnabled)
        QtCore.QObject.connect(self.chkDocumentsClient, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkHaveDocumentsClient.setEnabled)
        QtCore.QObject.connect(self.chkPolicyClient, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkHavePolicyClient.setEnabled)
        QtCore.QObject.connect(self.chkSNILSClient, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.chkHaveSNILSClient.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(LogicalControlDoubles)
        LogicalControlDoubles.setTabOrder(self.chkLastNameClient, self.chkFirstNameClient)
        LogicalControlDoubles.setTabOrder(self.chkFirstNameClient, self.chkPatrNameClient)
        LogicalControlDoubles.setTabOrder(self.chkPatrNameClient, self.chkSexClient)
        LogicalControlDoubles.setTabOrder(self.chkSexClient, self.chkBirthDateClient)
        LogicalControlDoubles.setTabOrder(self.chkBirthDateClient, self.chkDocumentsClient)
        LogicalControlDoubles.setTabOrder(self.chkDocumentsClient, self.chkHaveDocumentsClient)
        LogicalControlDoubles.setTabOrder(self.chkHaveDocumentsClient, self.chkPolicyClient)
        LogicalControlDoubles.setTabOrder(self.chkPolicyClient, self.chkHavePolicyClient)
        LogicalControlDoubles.setTabOrder(self.chkHavePolicyClient, self.chkSNILSClient)
        LogicalControlDoubles.setTabOrder(self.chkSNILSClient, self.chkHaveSNILSClient)
        LogicalControlDoubles.setTabOrder(self.chkHaveSNILSClient, self.chkLastNameFilter)
        LogicalControlDoubles.setTabOrder(self.chkLastNameFilter, self.edtLastNameFilterFrom)
        LogicalControlDoubles.setTabOrder(self.edtLastNameFilterFrom, self.edtLastNameFilterTo)
        LogicalControlDoubles.setTabOrder(self.edtLastNameFilterTo, self.chkBirthDateFilter)
        LogicalControlDoubles.setTabOrder(self.chkBirthDateFilter, self.edtBirthDateFilterFrom)
        LogicalControlDoubles.setTabOrder(self.edtBirthDateFilterFrom, self.edtBirthDateFilterTo)
        LogicalControlDoubles.setTabOrder(self.edtBirthDateFilterTo, self.chkLimitFilter)
        LogicalControlDoubles.setTabOrder(self.chkLimitFilter, self.edtLimitFilter)
        LogicalControlDoubles.setTabOrder(self.edtLimitFilter, self.tblDoubleClients)
        LogicalControlDoubles.setTabOrder(self.tblDoubleClients, self.btnNewTuning)
        LogicalControlDoubles.setTabOrder(self.btnNewTuning, self.btnPrint)
        LogicalControlDoubles.setTabOrder(self.btnPrint, self.btnBeginCheck)
        LogicalControlDoubles.setTabOrder(self.btnBeginCheck, self.btnEndCheck)

    def retranslateUi(self, LogicalControlDoubles):
        LogicalControlDoubles.setWindowTitle(_translate("LogicalControlDoubles", "Контроль двойников", None))
        self.chkBirthDateClient.setText(_translate("LogicalControlDoubles", "Дата рождения", None))
        self.chkPolicyClient.setText(_translate("LogicalControlDoubles", "Полис", None))
        self.chkPatrNameClient.setText(_translate("LogicalControlDoubles", "Отчество", None))
        self.chkLastNameClient.setText(_translate("LogicalControlDoubles", "Фамилия", None))
        self.chkFirstNameClient.setText(_translate("LogicalControlDoubles", "Имя", None))
        self.chkSexClient.setText(_translate("LogicalControlDoubles", "Пол пациента", None))
        self.lblBirthDateFilter.setText(_translate("LogicalControlDoubles", "по", None))
        self.chkSNILSClient.setText(_translate("LogicalControlDoubles", "СНИЛС", None))
        self.chkDocumentsClient.setText(_translate("LogicalControlDoubles", "Документы", None))
        self.chkLastNameFilter.setText(_translate("LogicalControlDoubles", "Ограничить фамилии с", None))
        self.chkLimitFilter.setText(_translate("LogicalControlDoubles", "Ограничить поиск до", None))
        self.lblLastNameFilter.setText(_translate("LogicalControlDoubles", "по", None))
        self.chkBirthDateFilter.setText(_translate("LogicalControlDoubles", "Ограничить даты с", None))
        self.lblLimitFilter.setText(_translate("LogicalControlDoubles", "записей", None))
        self.chkHaveDocumentsClient.setText(_translate("LogicalControlDoubles", "Заполнено", None))
        self.chkHavePolicyClient.setText(_translate("LogicalControlDoubles", "Заполнено", None))
        self.chkHaveSNILSClient.setText(_translate("LogicalControlDoubles", "Заполнено", None))
        self.btnNewTuning.setText(_translate("LogicalControlDoubles", "Новое условие", None))
        self.label.setText(_translate("LogicalControlDoubles", "Всего записей:", None))
        self.lblCountRecords.setText(_translate("LogicalControlDoubles", "0", None))
        self.btnBeginCheck.setText(_translate("LogicalControlDoubles", "Начать проверку", None))
        self.btnEndCheck.setText(_translate("LogicalControlDoubles", "Закрыть", None))
        self.btnPrint.setText(_translate("LogicalControlDoubles", "Печать", None))

from DataCheck.ControlDoublesPopupMenu import CControlDoublesPopupMenu
from library.DateEdit import CDateEdit
from library.ProgressBar import CProgressBar
