# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\samson\UP_s11\client_pre_release\RefBooks\PrintTemplate\RBPrintTemplateEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PrintTemplateEditorDialog(object):
    def setupUi(self, PrintTemplateEditorDialog):
        PrintTemplateEditorDialog.setObjectName(_fromUtf8("PrintTemplateEditorDialog"))
        PrintTemplateEditorDialog.resize(691, 525)
        PrintTemplateEditorDialog.setSizeGripEnabled(True)
        self.gridLayout_2 = QtGui.QGridLayout(PrintTemplateEditorDialog)
        self.gridLayout_2.setMargin(4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(PrintTemplateEditorDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPrintTemplate = QtGui.QWidget()
        self.tabPrintTemplate.setObjectName(_fromUtf8("tabPrintTemplate"))
        self.gridLayout = QtGui.QGridLayout(self.tabPrintTemplate)
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkNeedEventId = QtGui.QCheckBox(self.tabPrintTemplate)
        self.chkNeedEventId.setText(_fromUtf8(""))
        self.chkNeedEventId.setObjectName(_fromUtf8("chkNeedEventId"))
        self.horizontalLayout.addWidget(self.chkNeedEventId)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lblRequireSignerPerson = QtGui.QLabel(self.tabPrintTemplate)
        self.lblRequireSignerPerson.setObjectName(_fromUtf8("lblRequireSignerPerson"))
        self.horizontalLayout.addWidget(self.lblRequireSignerPerson)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 1, 1, 1)
        self.lblInAmbCard = QtGui.QLabel(self.tabPrintTemplate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInAmbCard.sizePolicy().hasHeightForWidth())
        self.lblInAmbCard.setSizePolicy(sizePolicy)
        self.lblInAmbCard.setObjectName(_fromUtf8("lblInAmbCard"))
        self.gridLayout.addWidget(self.lblInAmbCard, 5, 0, 1, 1)
        self.lblType = QtGui.QLabel(self.tabPrintTemplate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblType.sizePolicy().hasHeightForWidth())
        self.lblType.setSizePolicy(sizePolicy)
        self.lblType.setObjectName(_fromUtf8("lblType"))
        self.gridLayout.addWidget(self.lblType, 7, 0, 1, 1)
        self.cmbRequireSignerPerson = QtGui.QComboBox(self.tabPrintTemplate)
        self.cmbRequireSignerPerson.setObjectName(_fromUtf8("cmbRequireSignerPerson"))
        self.cmbRequireSignerPerson.addItem(_fromUtf8(""))
        self.cmbRequireSignerPerson.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbRequireSignerPerson, 6, 2, 1, 1)
        self.cmbType = QtGui.QComboBox(self.tabPrintTemplate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbType.sizePolicy().hasHeightForWidth())
        self.cmbType.setSizePolicy(sizePolicy)
        self.cmbType.setObjectName(_fromUtf8("cmbType"))
        self.cmbType.addItem(_fromUtf8(""))
        self.cmbType.addItem(_fromUtf8(""))
        self.cmbType.addItem(_fromUtf8(""))
        self.cmbType.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbType, 7, 1, 1, 1)
        self.edtContext = QtGui.QLineEdit(self.tabPrintTemplate)
        self.edtContext.setObjectName(_fromUtf8("edtContext"))
        self.gridLayout.addWidget(self.edtContext, 0, 1, 1, 1)
        self.chkInAmbCard = QtGui.QCheckBox(self.tabPrintTemplate)
        self.chkInAmbCard.setText(_fromUtf8(""))
        self.chkInAmbCard.setObjectName(_fromUtf8("chkInAmbCard"))
        self.gridLayout.addWidget(self.chkInAmbCard, 5, 1, 1, 1)
        self.chkPrintBlank = QtGui.QCheckBox(self.tabPrintTemplate)
        self.chkPrintBlank.setObjectName(_fromUtf8("chkPrintBlank"))
        self.gridLayout.addWidget(self.chkPrintBlank, 5, 2, 1, 1)
        self.btnEdit = QtGui.QPushButton(self.tabPrintTemplate)
        self.btnEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEdit.sizePolicy().hasHeightForWidth())
        self.btnEdit.setSizePolicy(sizePolicy)
        self.btnEdit.setObjectName(_fromUtf8("btnEdit"))
        self.gridLayout.addWidget(self.btnEdit, 7, 2, 1, 1)
        self.lblDefault = QtGui.QLabel(self.tabPrintTemplate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDefault.sizePolicy().hasHeightForWidth())
        self.lblDefault.setSizePolicy(sizePolicy)
        self.lblDefault.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblDefault.setObjectName(_fromUtf8("lblDefault"))
        self.gridLayout.addWidget(self.lblDefault, 8, 0, 1, 1)
        self.lblNeedEventId = QtGui.QLabel(self.tabPrintTemplate)
        self.lblNeedEventId.setObjectName(_fromUtf8("lblNeedEventId"))
        self.gridLayout.addWidget(self.lblNeedEventId, 6, 0, 1, 1)
        self.edtDefault = QtGui.QTextEdit(self.tabPrintTemplate)
        self.edtDefault.setObjectName(_fromUtf8("edtDefault"))
        self.gridLayout.addWidget(self.edtDefault, 8, 1, 1, 2)
        self.lblContext = QtGui.QLabel(self.tabPrintTemplate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblContext.sizePolicy().hasHeightForWidth())
        self.lblContext.setSizePolicy(sizePolicy)
        self.lblContext.setObjectName(_fromUtf8("lblContext"))
        self.gridLayout.addWidget(self.lblContext, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(131, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.lblCode = QtGui.QLabel(self.tabPrintTemplate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCode.sizePolicy().hasHeightForWidth())
        self.lblCode.setSizePolicy(sizePolicy)
        self.lblCode.setObjectName(_fromUtf8("lblCode"))
        self.gridLayout.addWidget(self.lblCode, 1, 0, 1, 1)
        self.edtCode = QtGui.QLineEdit(self.tabPrintTemplate)
        self.edtCode.setObjectName(_fromUtf8("edtCode"))
        self.gridLayout.addWidget(self.edtCode, 1, 1, 1, 1)
        self.lblGroupName = QtGui.QLabel(self.tabPrintTemplate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGroupName.sizePolicy().hasHeightForWidth())
        self.lblGroupName.setSizePolicy(sizePolicy)
        self.lblGroupName.setObjectName(_fromUtf8("lblGroupName"))
        self.gridLayout.addWidget(self.lblGroupName, 3, 0, 1, 1)
        self.lblFileName = QtGui.QLabel(self.tabPrintTemplate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFileName.sizePolicy().hasHeightForWidth())
        self.lblFileName.setSizePolicy(sizePolicy)
        self.lblFileName.setObjectName(_fromUtf8("lblFileName"))
        self.gridLayout.addWidget(self.lblFileName, 4, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(133, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.lblName = QtGui.QLabel(self.tabPrintTemplate)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        self.lblName.setObjectName(_fromUtf8("lblName"))
        self.gridLayout.addWidget(self.lblName, 2, 0, 1, 1)
        self.edtName = QtGui.QLineEdit(self.tabPrintTemplate)
        self.edtName.setMinimumSize(QtCore.QSize(200, 0))
        self.edtName.setObjectName(_fromUtf8("edtName"))
        self.gridLayout.addWidget(self.edtName, 2, 1, 1, 2)
        self.edtGroupName = QtGui.QLineEdit(self.tabPrintTemplate)
        self.edtGroupName.setMinimumSize(QtCore.QSize(200, 0))
        self.edtGroupName.setObjectName(_fromUtf8("edtGroupName"))
        self.gridLayout.addWidget(self.edtGroupName, 3, 1, 1, 2)
        self.edtFileName = QtGui.QLineEdit(self.tabPrintTemplate)
        self.edtFileName.setMinimumSize(QtCore.QSize(200, 0))
        self.edtFileName.setObjectName(_fromUtf8("edtFileName"))
        self.gridLayout.addWidget(self.edtFileName, 4, 1, 1, 2)
        self.tabWidget.addTab(self.tabPrintTemplate, _fromUtf8(""))
        self.tabClientConsents = QtGui.QWidget()
        self.tabClientConsents.setObjectName(_fromUtf8("tabClientConsents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabClientConsents)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tblClientConsents = CInDocTableView(self.tabClientConsents)
        self.tblClientConsents.setObjectName(_fromUtf8("tblClientConsents"))
        self.gridLayout_3.addWidget(self.tblClientConsents, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabClientConsents, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(PrintTemplateEditorDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.lblDefault.setBuddy(self.edtDefault)
        self.lblContext.setBuddy(self.edtContext)
        self.lblCode.setBuddy(self.edtCode)
        self.lblGroupName.setBuddy(self.edtName)
        self.lblFileName.setBuddy(self.edtFileName)
        self.lblName.setBuddy(self.edtName)

        self.retranslateUi(PrintTemplateEditorDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PrintTemplateEditorDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PrintTemplateEditorDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PrintTemplateEditorDialog)
        PrintTemplateEditorDialog.setTabOrder(self.edtContext, self.edtCode)
        PrintTemplateEditorDialog.setTabOrder(self.edtCode, self.edtName)
        PrintTemplateEditorDialog.setTabOrder(self.edtName, self.edtFileName)
        PrintTemplateEditorDialog.setTabOrder(self.edtFileName, self.chkInAmbCard)
        PrintTemplateEditorDialog.setTabOrder(self.chkInAmbCard, self.cmbType)
        PrintTemplateEditorDialog.setTabOrder(self.cmbType, self.btnEdit)
        PrintTemplateEditorDialog.setTabOrder(self.btnEdit, self.edtDefault)

    def retranslateUi(self, PrintTemplateEditorDialog):
        PrintTemplateEditorDialog.setWindowTitle(_translate("PrintTemplateEditorDialog", "ChangeMe!", None))
        self.lblRequireSignerPerson.setText(_translate("PrintTemplateEditorDialog", "Требует подписи", None))
        self.lblInAmbCard.setText(_translate("PrintTemplateEditorDialog", "Для отображения в Мед.карте", None))
        self.lblType.setText(_translate("PrintTemplateEditorDialog", "Тип", None))
        self.cmbRequireSignerPerson.setItemText(0, _translate("PrintTemplateEditorDialog", "Исполнителя", None))
        self.cmbRequireSignerPerson.setItemText(1, _translate("PrintTemplateEditorDialog", "Назначившего", None))
        self.cmbType.setItemText(0, _translate("PrintTemplateEditorDialog", "HTML", None))
        self.cmbType.setItemText(1, _translate("PrintTemplateEditorDialog", "Exaro", None))
        self.cmbType.setItemText(2, _translate("PrintTemplateEditorDialog", "SVG", None))
        self.cmbType.setItemText(3, _translate("PrintTemplateEditorDialog", "CSS", None))
        self.chkPrintBlank.setText(_translate("PrintTemplateEditorDialog", "Отключить печать подложки", None))
        self.btnEdit.setToolTip(_translate("PrintTemplateEditorDialog", "Изменить шаблон Exaro во внешнем редакторе", None))
        self.btnEdit.setText(_translate("PrintTemplateEditorDialog", "Редактировать", None))
        self.lblDefault.setText(_translate("PrintTemplateEditorDialog", "&Шаблон", None))
        self.lblNeedEventId.setText(_translate("PrintTemplateEditorDialog", "Требует идентификатор события", None))
        self.lblContext.setText(_translate("PrintTemplateEditorDialog", "Кон&текст", None))
        self.lblCode.setText(_translate("PrintTemplateEditorDialog", "&Код", None))
        self.lblGroupName.setText(_translate("PrintTemplateEditorDialog", "Группа", None))
        self.lblFileName.setText(_translate("PrintTemplateEditorDialog", "Имя &файла", None))
        self.lblName.setText(_translate("PrintTemplateEditorDialog", "На&именование", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPrintTemplate), _translate("PrintTemplateEditorDialog", "&Шаблон печати", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabClientConsents), _translate("PrintTemplateEditorDialog", "&Согласия пациента", None))

from library.InDocTable import CInDocTableView
